(self.AMP=self.AMP||[]).push({n:"amp-live-list",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $Poller$$module$extensions$amp_live_list$0_1$poller$$=function($win$jscomp$376$$,$wait$jscomp$2$$,$work$jscomp$2$$){this.$win$=$win$jscomp$376$$;this.$H$=$wait$jscomp$2$$;this.$I$=$work$jscomp$2$$;this.$G$=null;this.$F$=!1;this.$J$=this.$D$=null},$JSCompiler_StaticMethods_Poller$$module$extensions$amp_live_list$0_1$poller_prototype$getTimeout_$$=function($JSCompiler_StaticMethods_Poller$$module$extensions$amp_live_list$0_1$poller_prototype$getTimeout_$self$$){return $JSCompiler_StaticMethods_Poller$$module$extensions$amp_live_list$0_1$poller_prototype$getTimeout_$self$$.$D$?
$JSCompiler_StaticMethods_Poller$$module$extensions$amp_live_list$0_1$poller_prototype$getTimeout_$self$$.$D$():$JSCompiler_StaticMethods_Poller$$module$extensions$amp_live_list$0_1$poller_prototype$getTimeout_$self$$.$H$+_.$getJitter$$module$src$exponential_backoff$$($JSCompiler_StaticMethods_Poller$$module$extensions$amp_live_list$0_1$poller_prototype$getTimeout_$self$$.$H$,.2)},$JSCompiler_StaticMethods_poll_$$=function($JSCompiler_StaticMethods_poll_$self$$,$opt_immediate$jscomp$1$$){if($JSCompiler_StaticMethods_poll_$self$$.$F$){var $work$jscomp$3$$=
function(){$JSCompiler_StaticMethods_poll_$self$$.$J$=$JSCompiler_StaticMethods_poll_$self$$.$I$().then(function(){$JSCompiler_StaticMethods_poll_$self$$.$D$&&($JSCompiler_StaticMethods_poll_$self$$.$D$=null);$JSCompiler_StaticMethods_poll_$$($JSCompiler_StaticMethods_poll_$self$$)}).catch(function($opt_immediate$jscomp$1$$){if($opt_immediate$jscomp$1$$.$retriable$)$JSCompiler_StaticMethods_poll_$self$$.$D$||($JSCompiler_StaticMethods_poll_$self$$.$D$=_.$exponentialBackoffClock$$module$src$exponential_backoff$$()),
$JSCompiler_StaticMethods_poll_$$($JSCompiler_StaticMethods_poll_$self$$);else throw $opt_immediate$jscomp$1$$;})};$opt_immediate$jscomp$1$$?$work$jscomp$3$$():$JSCompiler_StaticMethods_poll_$self$$.$G$=_.$Services$$module$src$services$timerFor$$($JSCompiler_StaticMethods_poll_$self$$.$win$).delay($work$jscomp$3$$,$JSCompiler_StaticMethods_Poller$$module$extensions$amp_live_list$0_1$poller_prototype$getTimeout_$$($JSCompiler_StaticMethods_poll_$self$$))}},$LiveListManager$$module$extensions$amp_live_list$0_1$live_list_manager$$=
function($ampdoc$jscomp$214$$){var $$jscomp$this$jscomp$803$$=this;this.ampdoc=$ampdoc$jscomp$214$$;this.$D$=Object.create(null);this.$I$=_.$Services$$module$src$services$viewerForDoc$$(this.ampdoc);this.$K$=_.$Services$$module$src$services$extensionsFor$$(this.ampdoc.$win$);this.$G$=15E3;this.$J$=[this.$G$];this.$F$=null;this.$M$=this.ampdoc.$AmpDoc$$module$src$service$ampdoc_impl_prototype$getUrl$();this.$H$=0;this.$O$=this.$fetchDocument_$.bind(this);this.$P$=$isDocTransformed$$module$extensions$amp_live_list$0_1$live_list_manager$$($ampdoc$jscomp$214$$.getRootNode());
this.ampdoc.$whenReady$().then(function(){$$jscomp$this$jscomp$803$$.$G$=Math.min.apply(Math,$$jscomp$this$jscomp$803$$.$J$);var $ampdoc$jscomp$214$$=Object.keys($$jscomp$this$jscomp$803$$.$D$).map(function($ampdoc$jscomp$214$$){return $$jscomp$this$jscomp$803$$.$D$[$ampdoc$jscomp$214$$].$K$});$$jscomp$this$jscomp$803$$.$H$=Math.max.apply(Math,$ampdoc$jscomp$214$$);_.$getMode$$module$src$mode$$().localDev&&($ampdoc$jscomp$214$$=$$jscomp$this$jscomp$803$$.ampdoc.$win$.location.pathname,-1!=$ampdoc$jscomp$214$$.indexOf("/examples/live-list-update.amp.html")||
-1!=$ampdoc$jscomp$214$$.indexOf("/examples/live-blog.amp.html")||-1!=$ampdoc$jscomp$214$$.indexOf("/examples/live-blog-non-floating-button.amp.html"))&&($$jscomp$this$jscomp$803$$.$G$=5E3);$$jscomp$this$jscomp$803$$.$F$=new $Poller$$module$extensions$amp_live_list$0_1$poller$$($$jscomp$this$jscomp$803$$.ampdoc.$win$,$$jscomp$this$jscomp$803$$.$G$,$$jscomp$this$jscomp$803$$.$O$);_.$JSCompiler_StaticMethods_Viewer$$module$src$service$viewer_impl_prototype$isVisible$$($$jscomp$this$jscomp$803$$.$I$)&&
$JSCompiler_StaticMethods_hasActiveLiveLists_$$($$jscomp$this$jscomp$803$$)&&$$jscomp$this$jscomp$803$$.$F$.start();$JSCompiler_StaticMethods_setupVisibilityHandler_$$($$jscomp$this$jscomp$803$$)})},$JSCompiler_StaticMethods_hasActiveLiveLists_$$=function($JSCompiler_StaticMethods_hasActiveLiveLists_$self$$){return Object.keys($JSCompiler_StaticMethods_hasActiveLiveLists_$self$$.$D$).some(function($key$jscomp$137$$){return!$JSCompiler_StaticMethods_hasActiveLiveLists_$self$$.$D$[$key$jscomp$137$$].element.hasAttribute("disabled")})},
$JSCompiler_StaticMethods_setupVisibilityHandler_$$=function($JSCompiler_StaticMethods_setupVisibilityHandler_$self$$){_.$JSCompiler_StaticMethods_Viewer$$module$src$service$viewer_impl_prototype$onVisibilityChanged$$($JSCompiler_StaticMethods_setupVisibilityHandler_$self$$.$I$,function(){_.$JSCompiler_StaticMethods_Viewer$$module$src$service$viewer_impl_prototype$isVisible$$($JSCompiler_StaticMethods_setupVisibilityHandler_$self$$.$I$)?$JSCompiler_StaticMethods_setupVisibilityHandler_$self$$.$F$.start(!0):
$JSCompiler_StaticMethods_setupVisibilityHandler_$self$$.$F$.stop()})},$JSCompiler_StaticMethods_installExtensionsForDoc_$$=function($JSCompiler_StaticMethods_installExtensionsForDoc_$self$$,$doc$jscomp$101$$){_.$toArray$$module$src$types$$($doc$jscomp$101$$.querySelectorAll("script[custom-element], script[custom-template]")).forEach(function($doc$jscomp$101$$){$doc$jscomp$101$$=$doc$jscomp$101$$.getAttribute("custom-element")||$doc$jscomp$101$$.getAttribute("custom-template");_.$JSCompiler_StaticMethods_installExtensionForDoc$$($JSCompiler_StaticMethods_installExtensionsForDoc_$self$$.$K$,
$JSCompiler_StaticMethods_installExtensionsForDoc_$self$$.ampdoc,$doc$jscomp$101$$)})},$isDocTransformed$$module$extensions$amp_live_list$0_1$live_list_manager$$=function($root$jscomp$84_transformed$$){if(!$root$jscomp$84_transformed$$.ownerDocument)return!1;$root$jscomp$84_transformed$$=$root$jscomp$84_transformed$$.ownerDocument.documentElement.getAttribute("transformed");return!!$root$jscomp$84_transformed$$&&_.$startsWith$$module$src$string$$($root$jscomp$84_transformed$$,"google;v=")},$liveListManagerForDoc$$module$extensions$amp_live_list$0_1$live_list_manager$$=
function($ampdoc$jscomp$216$$){_.$registerServiceBuilderForDoc$$module$src$service$$($ampdoc$jscomp$216$$,"liveListManager",$LiveListManager$$module$extensions$amp_live_list$0_1$live_list_manager$$,!0);return _.$getServiceForDoc$$module$src$service$$($ampdoc$jscomp$216$$,"liveListManager")},$getNumberMaxOrDefault$$module$extensions$amp_live_list$0_1$amp_live_list$$=function($value$jscomp$252$$,$defaultValue$jscomp$7$$){return Math.max(parseInt($value$jscomp$252$$,10)||0,$defaultValue$jscomp$7$$)},
$AmpLiveList$$module$extensions$amp_live_list$0_1$amp_live_list$$=function($$jscomp$super$this$jscomp$75_element$jscomp$559$$){$$jscomp$super$this$jscomp$75_element$jscomp$559$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$75_element$jscomp$559$$)||this;$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$F$=null;$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$U$=null;$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$S$=null;$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$D$=null;
$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$P$=null;$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$V$="";$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$X$=0;$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$W$=0;$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$K$=0;$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$M$=!1;$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$G$=Object.create(null);$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$O$=[];$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$H$=
[];$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$J$=[];$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$R$=null;$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$I$=0;$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$Y$=$$jscomp$super$this$jscomp$75_element$jscomp$559$$.$sortByDataSortTime_$.bind($$jscomp$super$this$jscomp$75_element$jscomp$559$$);return $$jscomp$super$this$jscomp$75_element$jscomp$559$$},$JSCompiler_StaticMethods_toggleUpdateButton_$$=function($JSCompiler_StaticMethods_toggleUpdateButton_$self$$,
$visible$jscomp$9$$){$JSCompiler_StaticMethods_toggleUpdateButton_$self$$.$S$.classList.toggle("amp-hidden",!$visible$jscomp$9$$);$JSCompiler_StaticMethods_toggleUpdateButton_$self$$.$S$.classList.toggle("amp-active",$visible$jscomp$9$$)},$JSCompiler_StaticMethods_insert_$$=function($JSCompiler_StaticMethods_insert_$self$$,$orphans$$){var $count$jscomp$29$$=0;$orphans$$.forEach(function($orphans$$){if(0==$JSCompiler_StaticMethods_insert_$self$$.$D$.childElementCount)$JSCompiler_StaticMethods_insert_$self$$.$D$.appendChild($orphans$$);
else{var $orphan$$=$JSCompiler_StaticMethods_getSortTime_$$($orphans$$);if($JSCompiler_StaticMethods_insert_$self$$.$M$)for(var $child$300_child$jscomp$32$$=$JSCompiler_StaticMethods_insert_$self$$.$D$.lastElementChild;$child$300_child$jscomp$32$$;$child$300_child$jscomp$32$$=$child$300_child$jscomp$32$$.previousElementSibling){var $childSortTime_childSortTime$301$$=$JSCompiler_StaticMethods_getSortTime_$$($child$300_child$jscomp$32$$);if($orphan$$>=$childSortTime_childSortTime$301$$){$child$300_child$jscomp$32$$.nextElementSibling?
$JSCompiler_StaticMethods_insert_$self$$.$D$.insertBefore($orphans$$,$child$300_child$jscomp$32$$.nextElementSibling):$JSCompiler_StaticMethods_insert_$self$$.$D$.appendChild($orphans$$);$count$jscomp$29$$++;break}else if(!$child$300_child$jscomp$32$$.previousElementSibling){$JSCompiler_StaticMethods_insert_$self$$.$D$.insertBefore($orphans$$,$child$300_child$jscomp$32$$);$count$jscomp$29$$++;break}}else for($child$300_child$jscomp$32$$=$JSCompiler_StaticMethods_insert_$self$$.$D$.firstElementChild;$child$300_child$jscomp$32$$;$child$300_child$jscomp$32$$=
$child$300_child$jscomp$32$$.nextElementSibling)if($childSortTime_childSortTime$301$$=$JSCompiler_StaticMethods_getSortTime_$$($child$300_child$jscomp$32$$),$orphan$$>=$childSortTime_childSortTime$301$$){$JSCompiler_StaticMethods_insert_$self$$.$D$.insertBefore($orphans$$,$child$300_child$jscomp$32$$);$count$jscomp$29$$++;break}else if(!$child$300_child$jscomp$32$$.nextElementSibling){$JSCompiler_StaticMethods_insert_$self$$.$D$.appendChild($orphans$$);$count$jscomp$29$$++;break}}});return $count$jscomp$29$$},
$JSCompiler_StaticMethods_replace_$$=function($parent$jscomp$46$$,$orphans$jscomp$1$$){var $count$jscomp$30$$=0;$orphans$jscomp$1$$.forEach(function($orphans$jscomp$1$$){var $orphan$jscomp$1$$=$orphans$jscomp$1$$.getAttribute("id");if($orphan$jscomp$1$$=$parent$jscomp$46$$.querySelector("#"+$orphan$jscomp$1$$))$parent$jscomp$46$$.replaceChild($orphans$jscomp$1$$,$orphan$jscomp$1$$),$count$jscomp$30$$++})},$JSCompiler_StaticMethods_tombstone_$$=function($parent$jscomp$47$$,$orphans$jscomp$2$$){var $count$jscomp$31$$=
0;$orphans$jscomp$2$$.forEach(function($orphans$jscomp$2$$){$orphans$jscomp$2$$=$orphans$jscomp$2$$.getAttribute("id");if($orphans$jscomp$2$$=$parent$jscomp$47$$.querySelector("#"+$orphans$jscomp$2$$))$orphans$jscomp$2$$.setAttribute("data-tombstone",""),$orphans$jscomp$2$$.textContent="",$count$jscomp$31$$++});return $count$jscomp$31$$},$JSCompiler_StaticMethods_removeOverflowItems_$$=function($JSCompiler_StaticMethods_removeOverflowItems_$self$$,$parent$jscomp$48$$){var $numOfItemsToDelete$$=$JSCompiler_StaticMethods_removeOverflowItems_$self$$.$I$-
$JSCompiler_StaticMethods_removeOverflowItems_$self$$.$W$;if(1>$numOfItemsToDelete$$)return Promise.resolve();var $deleteItemsCandidates$$=[],$actualDeleteItems$$=[];if($JSCompiler_StaticMethods_removeOverflowItems_$self$$.$M$)for(var $child$302_child$jscomp$33$$=$parent$jscomp$48$$.firstElementChild;$child$302_child$jscomp$33$$&&!($deleteItemsCandidates$$.length>=$numOfItemsToDelete$$);$child$302_child$jscomp$33$$=$child$302_child$jscomp$33$$.nextElementSibling)$child$302_child$jscomp$33$$.hasAttribute("data-tombstone")||
$deleteItemsCandidates$$.push($child$302_child$jscomp$33$$);else for($child$302_child$jscomp$33$$=$parent$jscomp$48$$.lastElementChild;$child$302_child$jscomp$33$$&&!($deleteItemsCandidates$$.length>=$numOfItemsToDelete$$);$child$302_child$jscomp$33$$=$child$302_child$jscomp$33$$.previousElementSibling)$child$302_child$jscomp$33$$.hasAttribute("data-tombstone")||$deleteItemsCandidates$$.push($child$302_child$jscomp$33$$);return _.$JSCompiler_StaticMethods_runPromise$$(_.$JSCompiler_StaticMethods_getVsync$$($JSCompiler_StaticMethods_removeOverflowItems_$self$$),
{measure:function(){for(var $parent$jscomp$48$$=0;$parent$jscomp$48$$<$deleteItemsCandidates$$.length;$parent$jscomp$48$$++){var $numOfItemsToDelete$$=$deleteItemsCandidates$$[$parent$jscomp$48$$];if($JSCompiler_StaticMethods_removeOverflowItems_$self$$.$M$){if(!($JSCompiler_StaticMethods_removeOverflowItems_$self$$.$F$.$getLayoutRect$($numOfItemsToDelete$$).bottom<_.$JSCompiler_StaticMethods_Viewport$$module$src$service$viewport$viewport_impl_prototype$getScrollTop$$($JSCompiler_StaticMethods_removeOverflowItems_$self$$.$F$)))break}else if(!(_.$isExperimentOn$$module$src$experiments$$($JSCompiler_StaticMethods_removeOverflowItems_$self$$.$win$,
"layers")?0<$JSCompiler_StaticMethods_removeOverflowItems_$self$$.$F$.$getLayoutRect$($numOfItemsToDelete$$).top:$JSCompiler_StaticMethods_removeOverflowItems_$self$$.$F$.$getLayoutRect$($numOfItemsToDelete$$).top>_.$JSCompiler_StaticMethods_Viewport$$module$src$service$viewport$viewport_impl_prototype$getScrollTop$$($JSCompiler_StaticMethods_removeOverflowItems_$self$$.$F$)+$JSCompiler_StaticMethods_removeOverflowItems_$self$$.$F$.$getSize$().height))break;$actualDeleteItems$$.push($numOfItemsToDelete$$)}},
$mutate$:function(){$actualDeleteItems$$.forEach(function($numOfItemsToDelete$$){$parent$jscomp$48$$.removeChild($numOfItemsToDelete$$);$JSCompiler_StaticMethods_removeOverflowItems_$self$$.$I$--})}})},$JSCompiler_StaticMethods_preparePendingItemsInsert_$$=function($JSCompiler_StaticMethods_preparePendingItemsInsert_$self$$,$items$jscomp$7$$){$items$jscomp$7$$.sort($JSCompiler_StaticMethods_preparePendingItemsInsert_$self$$.$Y$).forEach(function($JSCompiler_StaticMethods_preparePendingItemsInsert_$self$$){$JSCompiler_StaticMethods_preparePendingItemsInsert_$self$$.classList.add("amp-live-list-item");
$JSCompiler_StaticMethods_preparePendingItemsInsert_$self$$.classList.add("amp-live-list-item-new")});$JSCompiler_StaticMethods_preparePendingItemsInsert_$self$$.$O$.push.apply($JSCompiler_StaticMethods_preparePendingItemsInsert_$self$$.$O$,$items$jscomp$7$$)},$JSCompiler_StaticMethods_preparePendingItemsReplace_$$=function($JSCompiler_StaticMethods_preparePendingItemsReplace_$self$$,$items$jscomp$8$$){$items$jscomp$8$$.forEach(function($items$jscomp$8$$){a:{var $elem$jscomp$7$$=$JSCompiler_StaticMethods_preparePendingItemsReplace_$self$$.$H$;
for(var $i$jscomp$inline_3893$$=0;$i$jscomp$inline_3893$$<$elem$jscomp$7$$.length;$i$jscomp$inline_3893$$++)if($elem$jscomp$7$$[$i$jscomp$inline_3893$$].getAttribute("id")==$items$jscomp$8$$.getAttribute("id")){$elem$jscomp$7$$=$i$jscomp$inline_3893$$;break a}$elem$jscomp$7$$=-1}$items$jscomp$8$$.classList.add("amp-live-list-item");-1==$elem$jscomp$7$$?$JSCompiler_StaticMethods_preparePendingItemsReplace_$self$$.$H$.push($items$jscomp$8$$):$JSCompiler_StaticMethods_preparePendingItemsReplace_$self$$.$H$[$elem$jscomp$7$$]=
$items$jscomp$8$$})},$JSCompiler_StaticMethods_getUpdates_$$=function($JSCompiler_StaticMethods_getUpdates_$self$$,$child$jscomp$35_updatedElement$jscomp$1$$){var $insert$$=[],$replace$$=[],$tombstone$$=[];for($child$jscomp$35_updatedElement$jscomp$1$$=$child$jscomp$35_updatedElement$jscomp$1$$.firstElementChild;$child$jscomp$35_updatedElement$jscomp$1$$;$child$jscomp$35_updatedElement$jscomp$1$$=$child$jscomp$35_updatedElement$jscomp$1$$.nextElementSibling){var $id$jscomp$86_orphan$304_orphan$jscomp$3$$=
$child$jscomp$35_updatedElement$jscomp$1$$.getAttribute("id"),$JSCompiler_StaticMethods_isChildNew_$self$jscomp$inline_3895_JSCompiler_StaticMethods_isChildUpdate_$self$jscomp$inline_3899_JSCompiler_inline_result$jscomp$883_updateTime$$=$JSCompiler_StaticMethods_getUpdates_$self$$,$elem$jscomp$inline_3896_id$jscomp$inline_3901$$=$child$jscomp$35_updatedElement$jscomp$1$$,$elem$jscomp$inline_3900_id$jscomp$inline_3897_updateTime$jscomp$inline_3902$$=$elem$jscomp$inline_3896_id$jscomp$inline_3901$$.getAttribute("id");
$elem$jscomp$inline_3896_id$jscomp$inline_3901$$.hasAttribute("data-tombstone")||$elem$jscomp$inline_3900_id$jscomp$inline_3897_updateTime$jscomp$inline_3902$$ in $JSCompiler_StaticMethods_isChildNew_$self$jscomp$inline_3895_JSCompiler_StaticMethods_isChildUpdate_$self$jscomp$inline_3899_JSCompiler_inline_result$jscomp$883_updateTime$$.$G$?($JSCompiler_StaticMethods_isChildNew_$self$jscomp$inline_3895_JSCompiler_StaticMethods_isChildUpdate_$self$jscomp$inline_3899_JSCompiler_inline_result$jscomp$883_updateTime$$=
$JSCompiler_StaticMethods_getUpdates_$self$$,$elem$jscomp$inline_3900_id$jscomp$inline_3897_updateTime$jscomp$inline_3902$$=$child$jscomp$35_updatedElement$jscomp$1$$,!$elem$jscomp$inline_3900_id$jscomp$inline_3897_updateTime$jscomp$inline_3902$$.hasAttribute("data-update-time")||$elem$jscomp$inline_3900_id$jscomp$inline_3897_updateTime$jscomp$inline_3902$$.hasAttribute("data-tombstone")?$JSCompiler_StaticMethods_isChildNew_$self$jscomp$inline_3895_JSCompiler_StaticMethods_isChildUpdate_$self$jscomp$inline_3899_JSCompiler_inline_result$jscomp$883_updateTime$$=
!1:($elem$jscomp$inline_3896_id$jscomp$inline_3901$$=$elem$jscomp$inline_3900_id$jscomp$inline_3897_updateTime$jscomp$inline_3902$$.getAttribute("id"),$elem$jscomp$inline_3900_id$jscomp$inline_3897_updateTime$jscomp$inline_3902$$=$JSCompiler_StaticMethods_getUpdateTime_$$($elem$jscomp$inline_3900_id$jscomp$inline_3897_updateTime$jscomp$inline_3902$$),$JSCompiler_StaticMethods_isChildNew_$self$jscomp$inline_3895_JSCompiler_StaticMethods_isChildUpdate_$self$jscomp$inline_3899_JSCompiler_inline_result$jscomp$883_updateTime$$=
$elem$jscomp$inline_3896_id$jscomp$inline_3901$$ in $JSCompiler_StaticMethods_isChildNew_$self$jscomp$inline_3895_JSCompiler_StaticMethods_isChildUpdate_$self$jscomp$inline_3899_JSCompiler_inline_result$jscomp$883_updateTime$$.$G$&&-1!=$JSCompiler_StaticMethods_isChildNew_$self$jscomp$inline_3895_JSCompiler_StaticMethods_isChildUpdate_$self$jscomp$inline_3899_JSCompiler_inline_result$jscomp$883_updateTime$$.$G$[$elem$jscomp$inline_3896_id$jscomp$inline_3901$$]&&$elem$jscomp$inline_3900_id$jscomp$inline_3897_updateTime$jscomp$inline_3902$$>
$JSCompiler_StaticMethods_isChildNew_$self$jscomp$inline_3895_JSCompiler_StaticMethods_isChildUpdate_$self$jscomp$inline_3899_JSCompiler_inline_result$jscomp$883_updateTime$$.$G$[$elem$jscomp$inline_3896_id$jscomp$inline_3901$$]),$JSCompiler_StaticMethods_isChildNew_$self$jscomp$inline_3895_JSCompiler_StaticMethods_isChildUpdate_$self$jscomp$inline_3899_JSCompiler_inline_result$jscomp$883_updateTime$$?($JSCompiler_StaticMethods_isChildNew_$self$jscomp$inline_3895_JSCompiler_StaticMethods_isChildUpdate_$self$jscomp$inline_3899_JSCompiler_inline_result$jscomp$883_updateTime$$=
$JSCompiler_StaticMethods_getUpdateTime_$$($child$jscomp$35_updatedElement$jscomp$1$$),$JSCompiler_StaticMethods_getUpdates_$self$$.$G$[$id$jscomp$86_orphan$304_orphan$jscomp$3$$]=$JSCompiler_StaticMethods_isChildNew_$self$jscomp$inline_3895_JSCompiler_StaticMethods_isChildUpdate_$self$jscomp$inline_3899_JSCompiler_inline_result$jscomp$883_updateTime$$,$id$jscomp$86_orphan$304_orphan$jscomp$3$$=$JSCompiler_StaticMethods_getUpdates_$self$$.$win$.document.importNode($child$jscomp$35_updatedElement$jscomp$1$$,
!0),$JSCompiler_StaticMethods_isChildNew_$self$jscomp$inline_3895_JSCompiler_StaticMethods_isChildUpdate_$self$jscomp$inline_3899_JSCompiler_inline_result$jscomp$883_updateTime$$>$JSCompiler_StaticMethods_getUpdates_$self$$.$K$&&($JSCompiler_StaticMethods_getUpdates_$self$$.$K$=$JSCompiler_StaticMethods_isChildNew_$self$jscomp$inline_3895_JSCompiler_StaticMethods_isChildUpdate_$self$jscomp$inline_3899_JSCompiler_inline_result$jscomp$883_updateTime$$),$replace$$.push($id$jscomp$86_orphan$304_orphan$jscomp$3$$)):
$child$jscomp$35_updatedElement$jscomp$1$$.hasAttribute("data-tombstone")&&-1!=$JSCompiler_StaticMethods_getUpdates_$self$$.$G$[$id$jscomp$86_orphan$304_orphan$jscomp$3$$]&&($JSCompiler_StaticMethods_getUpdates_$self$$.$G$[$id$jscomp$86_orphan$304_orphan$jscomp$3$$]=-1,$tombstone$$.push($child$jscomp$35_updatedElement$jscomp$1$$))):($id$jscomp$86_orphan$304_orphan$jscomp$3$$=$JSCompiler_StaticMethods_getUpdates_$self$$.$win$.document.importNode($child$jscomp$35_updatedElement$jscomp$1$$,!0),$insert$$.push($id$jscomp$86_orphan$304_orphan$jscomp$3$$),
$JSCompiler_StaticMethods_cacheChild_$$($JSCompiler_StaticMethods_getUpdates_$self$$,$child$jscomp$35_updatedElement$jscomp$1$$))}return{$insert$:$insert$$,replace:$replace$$,$tombstone$:$tombstone$$}},$JSCompiler_StaticMethods_cacheChild_$$=function($JSCompiler_StaticMethods_cacheChild_$self$$,$child$jscomp$36_updateTime$jscomp$2$$){var $id$jscomp$89$$=$child$jscomp$36_updateTime$jscomp$2$$.getAttribute("id");$child$jscomp$36_updateTime$jscomp$2$$=$JSCompiler_StaticMethods_getUpdateTime_$$($child$jscomp$36_updateTime$jscomp$2$$);
$child$jscomp$36_updateTime$jscomp$2$$>$JSCompiler_StaticMethods_cacheChild_$self$$.$K$&&($JSCompiler_StaticMethods_cacheChild_$self$$.$K$=$child$jscomp$36_updateTime$jscomp$2$$);$JSCompiler_StaticMethods_cacheChild_$self$$.$G$[$id$jscomp$89$$]=$child$jscomp$36_updateTime$jscomp$2$$},$JSCompiler_StaticMethods_validateLiveListItems_$$=function($JSCompiler_StaticMethods_validateLiveListItems_$self$$,$element$jscomp$560$$,$opt_cacheIds$$){var $numItems$$=0;$JSCompiler_StaticMethods_eachChildElement_$$($element$jscomp$560$$,
function($element$jscomp$560$$){$element$jscomp$560$$.hasAttribute("id")&&0<Number($element$jscomp$560$$.getAttribute("data-sort-time"))&&$opt_cacheIds$$&&$JSCompiler_StaticMethods_cacheChild_$$($JSCompiler_StaticMethods_validateLiveListItems_$self$$,$element$jscomp$560$$);$numItems$$++});return $numItems$$},$JSCompiler_StaticMethods_eachChildElement_$$=function($child$jscomp$39_parent$jscomp$49$$,$cb$jscomp$12$$){for($child$jscomp$39_parent$jscomp$49$$=$child$jscomp$39_parent$jscomp$49$$.firstElementChild;$child$jscomp$39_parent$jscomp$49$$;$child$jscomp$39_parent$jscomp$49$$=
$child$jscomp$39_parent$jscomp$49$$.nextElementSibling)$cb$jscomp$12$$($child$jscomp$39_parent$jscomp$49$$)},$JSCompiler_StaticMethods_getSortTime_$$=function($elem$jscomp$12$$){return Number($elem$jscomp$12$$.getAttribute("data-sort-time"))},$JSCompiler_StaticMethods_getUpdateTime_$$=function($elem$jscomp$13$$){return $elem$jscomp$13$$.hasAttribute("data-update-time")?Number($elem$jscomp$13$$.getAttribute("data-update-time")):$JSCompiler_StaticMethods_getSortTime_$$($elem$jscomp$13$$)};$Poller$$module$extensions$amp_live_list$0_1$poller$$.prototype.start=function($opt_immediate$$){this.$F$||(this.$F$=!0,$JSCompiler_StaticMethods_poll_$$(this,$opt_immediate$$))};$Poller$$module$extensions$amp_live_list$0_1$poller$$.prototype.stop=function(){this.$F$&&(this.$F$=!1,this.$G$&&(_.$Services$$module$src$services$timerFor$$(this.$win$).cancel(this.$G$),this.$G$=null))};_.$JSCompiler_prototypeAlias$$=$LiveListManager$$module$extensions$amp_live_list$0_1$live_list_manager$$.prototype;_.$JSCompiler_prototypeAlias$$.$dispose$=function(){this.$F$.stop()};
_.$JSCompiler_prototypeAlias$$.$fetchDocument_$=function(){var $pathname$jscomp$inline_3873_resourceUrl$jscomp$inline_3870_url$jscomp$194$$=this.$M$;0<this.$H$&&($pathname$jscomp$inline_3873_resourceUrl$jscomp$inline_3870_url$jscomp$194$$=_.$addParamToUrl$$module$src$url$$($pathname$jscomp$inline_3873_resourceUrl$jscomp$inline_3870_url$jscomp$194$$,"amp_latest_update_time",String(this.$H$)));if(this.$P$){var $JSCompiler_StaticMethods_getCdnUrlOnOrigin$self$jscomp$inline_3869_hash$jscomp$inline_3872$$=
_.$Services$$module$src$services$urlForDoc$$(this.ampdoc.$getBody$());if(!_.$isProxyOrigin$$module$src$url$$($pathname$jscomp$inline_3873_resourceUrl$jscomp$inline_3870_url$jscomp$194$$)){var $$jscomp$inline_3871_encodedHost$jscomp$inline_3875$$=$JSCompiler_StaticMethods_getCdnUrlOnOrigin$self$jscomp$inline_3869_hash$jscomp$inline_3872$$.parse($pathname$jscomp$inline_3873_resourceUrl$jscomp$inline_3870_url$jscomp$194$$);$JSCompiler_StaticMethods_getCdnUrlOnOrigin$self$jscomp$inline_3869_hash$jscomp$inline_3872$$=
$$jscomp$inline_3871_encodedHost$jscomp$inline_3875$$.hash;$pathname$jscomp$inline_3873_resourceUrl$jscomp$inline_3870_url$jscomp$194$$=$$jscomp$inline_3871_encodedHost$jscomp$inline_3875$$.pathname;var $search$jscomp$inline_3874$$=$$jscomp$inline_3871_encodedHost$jscomp$inline_3875$$.search;$$jscomp$inline_3871_encodedHost$jscomp$inline_3875$$=encodeURIComponent($$jscomp$inline_3871_encodedHost$jscomp$inline_3875$$.host);$pathname$jscomp$inline_3873_resourceUrl$jscomp$inline_3870_url$jscomp$194$$=
_.$urls$$module$src$config$$.cdn+"/c/"+$$jscomp$inline_3871_encodedHost$jscomp$inline_3875$$+$pathname$jscomp$inline_3873_resourceUrl$jscomp$inline_3870_url$jscomp$194$$+$search$jscomp$inline_3874$$+$JSCompiler_StaticMethods_getCdnUrlOnOrigin$self$jscomp$inline_3869_hash$jscomp$inline_3872$$}}return _.$fetchDocument$$module$src$document_fetcher$$(this.ampdoc.$win$,$pathname$jscomp$inline_3873_resourceUrl$jscomp$inline_3870_url$jscomp$194$$,{requireAmpResponseSourceOrigin:!1}).then(this.$getLiveLists_$.bind(this))};
_.$JSCompiler_prototypeAlias$$.$getLiveLists_$=function($doc$jscomp$100_latestUpdateTime_updateTimes$$){$JSCompiler_StaticMethods_installExtensionsForDoc_$$(this,$doc$jscomp$100_latestUpdateTime_updateTimes$$);$doc$jscomp$100_latestUpdateTime_updateTimes$$=Array.prototype.slice.call($doc$jscomp$100_latestUpdateTime_updateTimes$$.getElementsByTagName("amp-live-list")).map(this.$updateLiveList_$.bind(this));$doc$jscomp$100_latestUpdateTime_updateTimes$$=Math.max.apply(Math,[0].concat($doc$jscomp$100_latestUpdateTime_updateTimes$$));
0<$doc$jscomp$100_latestUpdateTime_updateTimes$$&&(this.$H$=$doc$jscomp$100_latestUpdateTime_updateTimes$$);$JSCompiler_StaticMethods_hasActiveLiveLists_$$(this)||this.$F$.stop()};
_.$JSCompiler_prototypeAlias$$.$updateLiveList_$=function($liveList$$){var $id$jscomp$84_inClientDomLiveList$$=$liveList$$.getAttribute("id");$id$jscomp$84_inClientDomLiveList$$=this.$D$[$id$jscomp$84_inClientDomLiveList$$];$liveList$$.hasAttribute("disabled")?$id$jscomp$84_inClientDomLiveList$$.element.setAttribute("disabled",""):$id$jscomp$84_inClientDomLiveList$$.element.removeAttribute("disabled");return $id$jscomp$84_inClientDomLiveList$$.element.hasAttribute("disabled")?0:$id$jscomp$84_inClientDomLiveList$$.update($liveList$$)};
_.$JSCompiler_prototypeAlias$$.register=function($id$jscomp$85$$,$liveList$jscomp$1$$){$id$jscomp$85$$ in this.$D$||(this.$D$[$id$jscomp$85$$]=$liveList$jscomp$1$$,this.$J$.push($liveList$jscomp$1$$.$X$))};_.$$jscomp$inherits$$($AmpLiveList$$module$extensions$amp_live_list$0_1$amp_live_list$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpLiveList$$module$extensions$amp_live_list$0_1$amp_live_list$$.prototype;_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$85$$){return"container"==$layout$jscomp$85$$||"fixed-height"==$layout$jscomp$85$$};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){this.$F$=this.$getViewport$();this.$U$=$liveListManagerForDoc$$module$extensions$amp_live_list$0_1$live_list_manager$$(this.$getAmpDoc$());this.$S$=_.$childElementByAttr$$module$src$dom$$(this.element,"update");this.$D$=_.$childElementByAttr$$module$src$dom$$(this.element,"items");this.$P$=_.$childElementByAttr$$module$src$dom$$(this.element,"pagination");this.$V$=this.element.getAttribute("id");this.$X$=$getNumberMaxOrDefault$$module$extensions$amp_live_list$0_1$amp_live_list$$(this.element.getAttribute("data-poll-interval"),
15E3);var $maxItems$$=this.element.getAttribute("data-max-items-per-page"),$actualCount$$=[].slice.call(this.$D$.children).filter(function($maxItems$$){return!$maxItems$$.hasAttribute("data-tombstone")}).length;this.$W$=Math.max($getNumberMaxOrDefault$$module$extensions$amp_live_list$0_1$amp_live_list$$($maxItems$$,1),$actualCount$$);_.$isExperimentOn$$module$src$experiments$$(this.$win$,"amp-live-list-sorting")&&(this.$M$="ascending"===this.element.getAttribute("sort"));this.$U$.register(this.$V$,
this);$JSCompiler_StaticMethods_toggleUpdateButton_$$(this,!1);$JSCompiler_StaticMethods_eachChildElement_$$(this.$D$,function($maxItems$$){$maxItems$$.classList.add("amp-live-list-item")});this.$I$=$JSCompiler_StaticMethods_validateLiveListItems_$$(this,this.$D$,!0);_.$JSCompiler_StaticMethods_registerDefaultAction$$(this,this.$updateAction_$.bind(this),"update");this.element.hasAttribute("aria-live")||this.element.setAttribute("aria-live","polite")};
_.$JSCompiler_prototypeAlias$$.update=function($updatedElement$$){var $$jscomp$this$jscomp$807$$=this,$container$jscomp$27_mutateItems$$=_.$childElementByAttr$$module$src$dom$$($updatedElement$$,"items");if(!$container$jscomp$27_mutateItems$$)return this.$K$;$JSCompiler_StaticMethods_validateLiveListItems_$$(this,$container$jscomp$27_mutateItems$$);$container$jscomp$27_mutateItems$$=$JSCompiler_StaticMethods_getUpdates_$$(this,$container$jscomp$27_mutateItems$$);$JSCompiler_StaticMethods_preparePendingItemsInsert_$$(this,
$container$jscomp$27_mutateItems$$.$insert$);$JSCompiler_StaticMethods_preparePendingItemsReplace_$$(this,$container$jscomp$27_mutateItems$$.replace);this.$J$.push.apply(this.$J$,$container$jscomp$27_mutateItems$$.$tombstone$);this.$R$=_.$childElementByAttr$$module$src$dom$$($updatedElement$$,"pagination");0<this.$O$.length?this.$mutateElement$(function(){$JSCompiler_StaticMethods_toggleUpdateButton_$$($$jscomp$this$jscomp$807$$,!0);$$jscomp$this$jscomp$807$$.$F$.$H$.update()}):(0<this.$H$.length||
0<this.$J$.length)&&this.$updateAction_$();return this.$K$};
_.$JSCompiler_prototypeAlias$$.$updateAction_$=function(){var $$jscomp$this$jscomp$808$$=this,$hasInsertItems$$=0<this.$O$.length,$hasTombstoneItems$$=0<this.$J$.length,$hasReplaceItems_updateHasNewItems$$=0<this.$H$.length;$hasReplaceItems_updateHasNewItems$$=$hasInsertItems$$||$hasReplaceItems_updateHasNewItems$$;var $promise$jscomp$53$$=this.$mutateElement$(function(){var $hasReplaceItems_updateHasNewItems$$=_.$JSCompiler_StaticMethods_assertElement$$(_.$user$$module$src$log$$(),$$jscomp$this$jscomp$808$$.$D$);
$hasInsertItems$$&&($JSCompiler_StaticMethods_eachChildElement_$$($hasReplaceItems_updateHasNewItems$$,function($$jscomp$this$jscomp$808$$){$$jscomp$this$jscomp$808$$.classList.remove("amp-live-list-item-new")}),$$jscomp$this$jscomp$808$$.$I$+=$JSCompiler_StaticMethods_insert_$$($$jscomp$this$jscomp$808$$,$$jscomp$this$jscomp$808$$.$O$),$$jscomp$this$jscomp$808$$.$O$.length=0);0<$$jscomp$this$jscomp$808$$.$H$.length&&($JSCompiler_StaticMethods_replace_$$($hasReplaceItems_updateHasNewItems$$,$$jscomp$this$jscomp$808$$.$H$),
$$jscomp$this$jscomp$808$$.$H$.length=0);0<$$jscomp$this$jscomp$808$$.$J$.length&&($$jscomp$this$jscomp$808$$.$I$-=$JSCompiler_StaticMethods_tombstone_$$($hasReplaceItems_updateHasNewItems$$,$$jscomp$this$jscomp$808$$.$J$),$$jscomp$this$jscomp$808$$.$J$.length=0);($hasInsertItems$$||$hasTombstoneItems$$)&&$$jscomp$this$jscomp$808$$.$P$&&$$jscomp$this$jscomp$808$$.$R$&&($$jscomp$this$jscomp$808$$.element.replaceChild($$jscomp$this$jscomp$808$$.$R$,$$jscomp$this$jscomp$808$$.$P$),$$jscomp$this$jscomp$808$$.$P$=
_.$childElementByAttr$$module$src$dom$$($$jscomp$this$jscomp$808$$.element,"pagination"));$JSCompiler_StaticMethods_toggleUpdateButton_$$($$jscomp$this$jscomp$808$$,!1);$$jscomp$this$jscomp$808$$.$R$=null;return $JSCompiler_StaticMethods_removeOverflowItems_$$($$jscomp$this$jscomp$808$$,$hasReplaceItems_updateHasNewItems$$)});$hasReplaceItems_updateHasNewItems$$&&($promise$jscomp$53$$=$promise$jscomp$53$$.then(function(){var $hasInsertItems$$=$$jscomp$this$jscomp$808$$.$win$.document.createEvent("Event");
$hasInsertItems$$.initEvent("amp:dom-update",!0,!0);$$jscomp$this$jscomp$808$$.$D$.dispatchEvent($hasInsertItems$$)}));$hasInsertItems$$&&($promise$jscomp$53$$=$promise$jscomp$53$$.then(function(){return _.$JSCompiler_StaticMethods_animateScrollIntoView$$($$jscomp$this$jscomp$808$$.$F$,$$jscomp$this$jscomp$808$$.$M$&&$$jscomp$this$jscomp$808$$.$D$.lastElementChild?$$jscomp$this$jscomp$808$$.$D$.lastElementChild:$$jscomp$this$jscomp$808$$.element,$$jscomp$this$jscomp$808$$.$M$?"bottom":"top")}));return $promise$jscomp$53$$};
_.$JSCompiler_prototypeAlias$$.$sortByDataSortTime_$=function($a$jscomp$254$$,$b$jscomp$225$$){return $JSCompiler_StaticMethods_getSortTime_$$($a$jscomp$254$$)-$JSCompiler_StaticMethods_getSortTime_$$($b$jscomp$225$$)};self.AMP.registerElement("amp-live-list",$AmpLiveList$$module$extensions$amp_live_list$0_1$amp_live_list$$,"amp-live-list>[update]{position:relative;z-index:1000}amp-live-list>.amp-active[update]{display:block}amp-live-list>[items]>[data-tombstone]{display:none}@-webkit-keyframes amp-live-list-item-highlight{0%{box-shadow:0 0 5px 2px #51cbee}to{box-shadow:0}}@keyframes amp-live-list-item-highlight{0%{box-shadow:0 0 5px 2px #51cbee}to{box-shadow:0}}\n/*# sourceURL=/extensions/amp-live-list/0.1/amp-live-list.css*/");
})});

//# sourceMappingURL=amp-live-list-0.1.js.map
