(self.AMP=self.AMP||[]).push({n:"amp-google-document-embed",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $AmpDriveViewer$$module$extensions$amp_google_document_embed$0_1$amp_google_document_embed$$=function($$jscomp$super$this$jscomp$56_element$jscomp$486$$){$$jscomp$super$this$jscomp$56_element$jscomp$486$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$56_element$jscomp$486$$)||this;$$jscomp$super$this$jscomp$56_element$jscomp$486$$.$D$=null;return $$jscomp$super$this$jscomp$56_element$jscomp$486$$},$JSCompiler_StaticMethods_AmpDriveViewer$$module$extensions$amp_google_document_embed$0_1$amp_google_document_embed_prototype$getSrc_$$=
function($src$jscomp$40$$){return $src$jscomp$40$$.match($GOOGLE_DOCS_EMBED_RE$$module$extensions$amp_google_document_embed$0_1$amp_google_document_embed$$)?$src$jscomp$40$$:_.$addParamToUrl$$module$src$url$$("https://docs.google.com/gview?embedded=true","url",$src$jscomp$40$$)},$ATTRIBUTES_TO_PROPAGATE$$module$extensions$amp_google_document_embed$0_1$amp_google_document_embed$$=["title"],$GOOGLE_DOCS_EMBED_RE$$module$extensions$amp_google_document_embed$0_1$amp_google_document_embed$$=/^https?:\/\/docs\.google\.com.+\/pub.*\??/;
_.$$jscomp$inherits$$($AmpDriveViewer$$module$extensions$amp_google_document_embed$0_1$amp_google_document_embed$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpDriveViewer$$module$extensions$amp_google_document_embed$0_1$amp_google_document_embed$$.prototype;_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($opt_onLayout$jscomp$18$$){this.$preconnect$.url("https://docs.google.com",$opt_onLayout$jscomp$18$$)};_.$JSCompiler_prototypeAlias$$.$renderOutsideViewport$=function(){return.75};
_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$71$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$71$$)};_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $iframe$jscomp$55$$=this.element.ownerDocument.createElement("iframe");this.$D$=$iframe$jscomp$55$$;$iframe$jscomp$55$$.setAttribute("frameborder","0");$iframe$jscomp$55$$.setAttribute("allowfullscreen","");_.$JSCompiler_StaticMethods_propagateAttributes$$(this,$ATTRIBUTES_TO_PROPAGATE$$module$extensions$amp_google_document_embed$0_1$amp_google_document_embed$$,$iframe$jscomp$55$$);$iframe$jscomp$55$$.src=$JSCompiler_StaticMethods_AmpDriveViewer$$module$extensions$amp_google_document_embed$0_1$amp_google_document_embed_prototype$getSrc_$$(this.element.getAttribute("src"));
_.$JSCompiler_StaticMethods_applyFillContent$$($iframe$jscomp$55$$);this.element.appendChild($iframe$jscomp$55$$);return this.$loadPromise$($iframe$jscomp$55$$)};
_.$JSCompiler_prototypeAlias$$.$mutatedAttributesCallback$=function($mutations$jscomp$10$$){var $attrs$jscomp$8_src$jscomp$39$$=$ATTRIBUTES_TO_PROPAGATE$$module$extensions$amp_google_document_embed$0_1$amp_google_document_embed$$.filter(function($attrs$jscomp$8_src$jscomp$39$$){return void 0!==$mutations$jscomp$10$$[$attrs$jscomp$8_src$jscomp$39$$]}),$iframe$jscomp$56$$=this.$D$;_.$JSCompiler_StaticMethods_propagateAttributes$$(this,$attrs$jscomp$8_src$jscomp$39$$,$iframe$jscomp$56$$,!0);if($attrs$jscomp$8_src$jscomp$39$$=
$mutations$jscomp$10$$.src)$iframe$jscomp$56$$.src=$JSCompiler_StaticMethods_AmpDriveViewer$$module$extensions$amp_google_document_embed$0_1$amp_google_document_embed_prototype$getSrc_$$($attrs$jscomp$8_src$jscomp$39$$)};_.$JSCompiler_prototypeAlias$$.$unlayoutOnPause$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$D$=null);return!0};self.AMP.registerElement("amp-google-document-embed",$AmpDriveViewer$$module$extensions$amp_google_document_embed$0_1$amp_google_document_embed$$);
})});

//# sourceMappingURL=amp-google-document-embed-0.1.js.map
