(self.AMP=self.AMP||[]).push({n:"amp-nexxtv-player",i:["_base_i","_base_media"],v:"1904281823091",f:(function(AMP,_){
var $AmpNexxtvPlayer$$module$extensions$amp_nexxtv_player$0_1$amp_nexxtv_player$$=function($element$jscomp$575$$){var $$jscomp$super$this$jscomp$80$$=AMP.BaseElement.call(this,$element$jscomp$575$$)||this;$$jscomp$super$this$jscomp$80$$.$D$=null;$$jscomp$super$this$jscomp$80$$.$I$=_.$once$$module$src$utils$function$$(function(){var $element$jscomp$575$$=$$jscomp$super$this$jscomp$80$$.element,$mediaId$jscomp$inline_4000$$=$element$jscomp$575$$.getAttribute("data-mediaid"),$client$jscomp$inline_4001_src$jscomp$inline_4008$$=
$element$jscomp$575$$.getAttribute("data-client"),$delay$jscomp$inline_4002$$=$element$jscomp$575$$.getAttribute("data-seek-to")||"0",$mode$jscomp$inline_4003$$=$element$jscomp$575$$.getAttribute("data-mode")||"static",$streamtype$jscomp$inline_4004$$=$element$jscomp$575$$.getAttribute("data-streamtype")||"video",$origin$jscomp$inline_4005$$=$element$jscomp$575$$.getAttribute("data-origin")||"https://embed.nexx.cloud/",$disableAds$jscomp$inline_4006$$=$element$jscomp$575$$.getAttribute("data-disable-ads");
$element$jscomp$575$$=$element$jscomp$575$$.getAttribute("data-streaming-filter");$client$jscomp$inline_4001_src$jscomp$inline_4008$$=$origin$jscomp$inline_4005$$+(encodeURIComponent($client$jscomp$inline_4001_src$jscomp$inline_4008$$)+"/");$client$jscomp$inline_4001_src$jscomp$inline_4008$$+=encodeURIComponent($streamtype$jscomp$inline_4004$$)+"/";$client$jscomp$inline_4001_src$jscomp$inline_4008$$+=encodeURIComponent($mediaId$jscomp$inline_4000$$);$client$jscomp$inline_4001_src$jscomp$inline_4008$$+=
"?dataMode="+encodeURIComponent($mode$jscomp$inline_4003$$)+"&platform=amp";0<$delay$jscomp$inline_4002$$&&($client$jscomp$inline_4001_src$jscomp$inline_4008$$+="&delay="+encodeURIComponent($delay$jscomp$inline_4002$$));"1"===$disableAds$jscomp$inline_4006$$&&($client$jscomp$inline_4001_src$jscomp$inline_4008$$+="&disableAds=1");null!==$element$jscomp$575$$&&0<$element$jscomp$575$$.length&&($client$jscomp$inline_4001_src$jscomp$inline_4008$$+="&streamingFilter="+encodeURIComponent($element$jscomp$575$$));
return _.$parseUrlDeprecated$$module$src$url$$($client$jscomp$inline_4001_src$jscomp$inline_4008$$).href});$$jscomp$super$this$jscomp$80$$.$H$=null;$$jscomp$super$this$jscomp$80$$.$F$=null;$$jscomp$super$this$jscomp$80$$.$G$=null;return $$jscomp$super$this$jscomp$80$$},$JSCompiler_StaticMethods_AmpNexxtvPlayer$$module$extensions$amp_nexxtv_player$0_1$amp_nexxtv_player_prototype$sendCommand_$$=function($JSCompiler_StaticMethods_AmpNexxtvPlayer$$module$extensions$amp_nexxtv_player$0_1$amp_nexxtv_player_prototype$sendCommand_$self$$,
$command$jscomp$6$$){$JSCompiler_StaticMethods_AmpNexxtvPlayer$$module$extensions$amp_nexxtv_player$0_1$amp_nexxtv_player_prototype$sendCommand_$self$$.$F$.then(function(){$JSCompiler_StaticMethods_AmpNexxtvPlayer$$module$extensions$amp_nexxtv_player$0_1$amp_nexxtv_player_prototype$sendCommand_$self$$.$D$&&$JSCompiler_StaticMethods_AmpNexxtvPlayer$$module$extensions$amp_nexxtv_player$0_1$amp_nexxtv_player_prototype$sendCommand_$self$$.$D$.contentWindow&&$JSCompiler_StaticMethods_AmpNexxtvPlayer$$module$extensions$amp_nexxtv_player$0_1$amp_nexxtv_player_prototype$sendCommand_$self$$.$D$.contentWindow.postMessage(_.$dict$$module$src$utils$object$$({cmd:$command$jscomp$6$$}),
"*")})};_.$$jscomp$inherits$$($AmpNexxtvPlayer$$module$extensions$amp_nexxtv_player$0_1$amp_nexxtv_player$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpNexxtvPlayer$$module$extensions$amp_nexxtv_player$0_1$amp_nexxtv_player$$.prototype;_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($opt_onLayout$jscomp$23$$){this.$preconnect$.url(this.$I$(),$opt_onLayout$jscomp$23$$)};_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$89$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$89$$)};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){var $deferred$jscomp$50$$=new _.$Deferred$$module$src$utils$promise$$;this.$F$=$deferred$jscomp$50$$.$promise$;this.$G$=$deferred$jscomp$50$$.resolve;_.$installVideoManagerForDoc$$module$src$service$video_manager_impl$$(this.element);_.$Services$$module$src$services$videoManagerForDoc$$(this.element).register(this)};
_.$JSCompiler_prototypeAlias$$.$viewportCallback$=function($visible$jscomp$11$$){this.element.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$VISIBILITY$,{visible:$visible$jscomp$11$$})};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $$jscomp$this$jscomp$831$$=this;this.$D$=_.$createFrameFor$$module$src$iframe_video$$(this,this.$I$());this.$H$=_.$listen$$module$src$event_helper$$(this.$win$,"message",function($loaded$jscomp$2$$){var $data$jscomp$inline_4013_event$jscomp$165$$=$loaded$jscomp$2$$.data;$data$jscomp$inline_4013_event$jscomp$165$$&&$loaded$jscomp$2$$.source===$$jscomp$this$jscomp$831$$.$D$.contentWindow&&($loaded$jscomp$2$$=_.$objOrParseJson$$module$src$iframe_video$$($data$jscomp$inline_4013_event$jscomp$165$$))&&
_.$redispatch$$module$src$iframe_video$$($$jscomp$this$jscomp$831$$.element,$loaded$jscomp$2$$.event,{play:_.$VideoEvents$$module$src$video_interface$$.$PLAYING$,pause:_.$VideoEvents$$module$src$video_interface$$.$PAUSE$,mute:_.$VideoEvents$$module$src$video_interface$$.$MUTED$,unmute:_.$VideoEvents$$module$src$video_interface$$.$UNMUTED$})});this.element.appendChild(this.$D$);var $loaded$jscomp$2$$=this.$loadPromise$(this.$D$).then(function(){$$jscomp$this$jscomp$831$$.element.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$LOAD$)});
this.$G$($loaded$jscomp$2$$);return $loaded$jscomp$2$$};_.$JSCompiler_prototypeAlias$$.$pauseCallback$=function(){this.$D$&&this.pause()};_.$JSCompiler_prototypeAlias$$.$unlayoutOnPause$=function(){return!0};
_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$D$=null);this.$H$&&this.$H$();var $deferred$jscomp$51$$=new _.$Deferred$$module$src$utils$promise$$;this.$F$=$deferred$jscomp$51$$.$promise$;this.$G$=$deferred$jscomp$51$$.resolve;return!0};_.$JSCompiler_prototypeAlias$$.play=function(){$JSCompiler_StaticMethods_AmpNexxtvPlayer$$module$extensions$amp_nexxtv_player$0_1$amp_nexxtv_player_prototype$sendCommand_$$(this,"play")};
_.$JSCompiler_prototypeAlias$$.pause=function(){$JSCompiler_StaticMethods_AmpNexxtvPlayer$$module$extensions$amp_nexxtv_player$0_1$amp_nexxtv_player_prototype$sendCommand_$$(this,"pause")};_.$JSCompiler_prototypeAlias$$.$mute$=function(){$JSCompiler_StaticMethods_AmpNexxtvPlayer$$module$extensions$amp_nexxtv_player$0_1$amp_nexxtv_player_prototype$sendCommand_$$(this,"mute")};
_.$JSCompiler_prototypeAlias$$.$unmute$=function(){$JSCompiler_StaticMethods_AmpNexxtvPlayer$$module$extensions$amp_nexxtv_player$0_1$amp_nexxtv_player_prototype$sendCommand_$$(this,"unmute")};_.$JSCompiler_prototypeAlias$$.$supportsPlatform$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$isInteractive$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$showControls$=function(){};_.$JSCompiler_prototypeAlias$$.$hideControls$=function(){};
_.$JSCompiler_prototypeAlias$$.$fullscreenEnter$=function(){this.$D$&&_.$fullscreenEnter$$module$src$dom$$(this.$D$)};_.$JSCompiler_prototypeAlias$$.$fullscreenExit$=function(){this.$D$&&_.$fullscreenExit$$module$src$dom$$(this.$D$)};_.$JSCompiler_prototypeAlias$$.getMetadata=function(){};_.$JSCompiler_prototypeAlias$$.$preimplementsMediaSessionAPI$=function(){return!1};_.$JSCompiler_prototypeAlias$$.$preimplementsAutoFullscreen$=function(){return!1};
_.$JSCompiler_prototypeAlias$$.$getCurrentTime$=function(){return 0};_.$JSCompiler_prototypeAlias$$.$getDuration$=function(){return 1};_.$JSCompiler_prototypeAlias$$.$getPlayedRanges$=function(){return[]};_.$JSCompiler_prototypeAlias$$.$seekTo$=function(){this.$user$().error("amp-nexxtv-player","`seekTo` not supported.")};self.AMP.registerElement("amp-nexxtv-player",$AmpNexxtvPlayer$$module$extensions$amp_nexxtv_player$0_1$amp_nexxtv_player$$);
})});

//# sourceMappingURL=amp-nexxtv-player-0.1.js.map
