(self.AMP=self.AMP||[]).push({n:"amp-vk",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $AmpVk$$module$extensions$amp_vk$0_1$amp_vk$$=function($$jscomp$super$this$jscomp$123_element$jscomp$772$$){$$jscomp$super$this$jscomp$123_element$jscomp$772$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$123_element$jscomp$772$$)||this;$$jscomp$super$this$jscomp$123_element$jscomp$772$$.$F$=null;$$jscomp$super$this$jscomp$123_element$jscomp$772$$.$O$=0;$$jscomp$super$this$jscomp$123_element$jscomp$772$$.$G$=null;$$jscomp$super$this$jscomp$123_element$jscomp$772$$.$D$=null;$$jscomp$super$this$jscomp$123_element$jscomp$772$$.$J$=
null;$$jscomp$super$this$jscomp$123_element$jscomp$772$$.$M$=null;$$jscomp$super$this$jscomp$123_element$jscomp$772$$.$I$=null;$$jscomp$super$this$jscomp$123_element$jscomp$772$$.$H$=null;$$jscomp$super$this$jscomp$123_element$jscomp$772$$.$K$=null;return $$jscomp$super$this$jscomp$123_element$jscomp$772$$},$JSCompiler_StaticMethods_getIFrameSrc_$$=function($JSCompiler_StaticMethods_getIFrameSrc_$self$$){var $createdTime$jscomp$2$$=Date.now().toString(16),$iframeSrcPromise$$;"post"===$JSCompiler_StaticMethods_getIFrameSrc_$self$$.$D$?
$iframeSrcPromise$$=$JSCompiler_StaticMethods_getVkPostIFrameSrc_$$($JSCompiler_StaticMethods_getIFrameSrc_$self$$):"poll"===$JSCompiler_StaticMethods_getIFrameSrc_$self$$.$D$&&($iframeSrcPromise$$=$JSCompiler_StaticMethods_getVkPollIFrameSrc_$$($JSCompiler_StaticMethods_getIFrameSrc_$self$$));return $iframeSrcPromise$$.then(function($JSCompiler_StaticMethods_getIFrameSrc_$self$$){return _.$appendEncodedParamStringToUrl$$module$src$url$$($JSCompiler_StaticMethods_getIFrameSrc_$self$$,$createdTime$jscomp$2$$)})},
$JSCompiler_StaticMethods_getVkPostIFrameSrc_$$=function($JSCompiler_StaticMethods_getVkPostIFrameSrc_$self$$){return _.$Services$$module$src$services$viewerForDoc$$($JSCompiler_StaticMethods_getVkPostIFrameSrc_$self$$.element).$I$.then(function($ref$jscomp$4$$){var $startWidth$$=$JSCompiler_StaticMethods_getVkPostIFrameSrc_$self$$.element.offsetWidth,$pageUrl$jscomp$6$$=$JSCompiler_StaticMethods_getVkPostIFrameSrc_$self$$.$getAmpDoc$().$AmpDoc$$module$src$service$ampdoc_impl_prototype$getUrl$();
return _.$addParamsToUrl$$module$src$url$$("https://vk.com/widget_post.php",_.$dict$$module$src$utils$object$$({app:"0",width:"100%",_ver:"1",owner_id:$JSCompiler_StaticMethods_getVkPostIFrameSrc_$self$$.$J$,post_id:$JSCompiler_StaticMethods_getVkPostIFrameSrc_$self$$.$M$,hash:$JSCompiler_StaticMethods_getVkPostIFrameSrc_$self$$.$I$,amp:"1",startWidth:$startWidth$$,url:$pageUrl$jscomp$6$$,referrer:$ref$jscomp$4$$,title:"AMP Post"}))})},$JSCompiler_StaticMethods_getVkPollIFrameSrc_$$=function($JSCompiler_StaticMethods_getVkPollIFrameSrc_$self$$){return _.$Services$$module$src$services$viewerForDoc$$($JSCompiler_StaticMethods_getVkPollIFrameSrc_$self$$.element).$I$.then(function($ref$jscomp$5$$){var $pageUrl$jscomp$7$$=
$JSCompiler_StaticMethods_getVkPollIFrameSrc_$self$$.$getAmpDoc$().$AmpDoc$$module$src$service$ampdoc_impl_prototype$getUrl$();return _.$addParamsToUrl$$module$src$url$$("https://vk.com/al_widget_poll.php",_.$dict$$module$src$utils$object$$({app:$JSCompiler_StaticMethods_getVkPollIFrameSrc_$self$$.$H$,width:"100%",_ver:"1",poll_id:$JSCompiler_StaticMethods_getVkPollIFrameSrc_$self$$.$K$,amp:"1",url:$pageUrl$jscomp$7$$,title:"AMP Poll",description:"",referrer:$ref$jscomp$5$$}))})},$EmbedType$$module$extensions$amp_vk$0_1$amp_vk$$=
{$POST$:"post",$POLL$:"poll"};_.$$jscomp$inherits$$($AmpVk$$module$extensions$amp_vk$0_1$amp_vk$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpVk$$module$extensions$amp_vk$0_1$amp_vk$$.prototype;_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($opt_onLayout$jscomp$31$$){this.$preconnect$.url("https://vk.com",$opt_onLayout$jscomp$31$$)};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){this.$D$=this.element.getAttribute("data-embedtype");_.$JSCompiler_StaticMethods_assertEnumValue$$(_.$user$$module$src$log$$(),$EmbedType$$module$extensions$amp_vk$0_1$amp_vk$$,this.$D$,"data-embedtype");"post"===this.$D$?(this.$J$=this.element.getAttribute("data-owner-id"),this.$M$=this.element.getAttribute("data-post-id"),this.$I$=this.element.getAttribute("data-hash")):"poll"===this.$D$&&(this.$H$=this.element.getAttribute("data-api-id"),
this.$K$=this.element.getAttribute("data-poll-id"))};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $$jscomp$this$jscomp$1421$$=this,$iframe$jscomp$100$$=this.element.ownerDocument.createElement("iframe");this.$F$=$iframe$jscomp$100$$;this.$G$=_.$listen$$module$src$event_helper$$(this.$win$,"message",this.$handleVkIframeMessage_$.bind(this));return $JSCompiler_StaticMethods_getIFrameSrc_$$(this).then(function($src$jscomp$78$$){$iframe$jscomp$100$$.src=$src$jscomp$78$$;$iframe$jscomp$100$$.setAttribute("name","fXD");$iframe$jscomp$100$$.setAttribute("scrolling",
"no");$iframe$jscomp$100$$.setAttribute("frameborder","0");$iframe$jscomp$100$$.setAttribute("allowfullscreen","true");_.$JSCompiler_StaticMethods_applyFillContent$$($iframe$jscomp$100$$);$$jscomp$this$jscomp$1421$$.element.appendChild($iframe$jscomp$100$$);return $$jscomp$this$jscomp$1421$$.$loadPromise$($iframe$jscomp$100$$)})};
_.$JSCompiler_prototypeAlias$$.$handleVkIframeMessage_$=function($e$jscomp$342_eventData$jscomp$23_matches$jscomp$21_newHeight$jscomp$17$$){"https://vk.com"===$e$jscomp$342_eventData$jscomp$23_matches$jscomp$21_newHeight$jscomp$17$$.origin&&$e$jscomp$342_eventData$jscomp$23_matches$jscomp$21_newHeight$jscomp$17$$.source===this.$F$.contentWindow&&($e$jscomp$342_eventData$jscomp$23_matches$jscomp$21_newHeight$jscomp$17$$=$e$jscomp$342_eventData$jscomp$23_matches$jscomp$21_newHeight$jscomp$17$$.data)&&
($e$jscomp$342_eventData$jscomp$23_matches$jscomp$21_newHeight$jscomp$17$$=/\["resize",\[(\d+)\]]/.exec($e$jscomp$342_eventData$jscomp$23_matches$jscomp$21_newHeight$jscomp$17$$))&&$e$jscomp$342_eventData$jscomp$23_matches$jscomp$21_newHeight$jscomp$17$$[1]&&($e$jscomp$342_eventData$jscomp$23_matches$jscomp$21_newHeight$jscomp$17$$=parseInt($e$jscomp$342_eventData$jscomp$23_matches$jscomp$21_newHeight$jscomp$17$$[1],10),this.$O$!==$e$jscomp$342_eventData$jscomp$23_matches$jscomp$21_newHeight$jscomp$17$$&&
(this.$O$=$e$jscomp$342_eventData$jscomp$23_matches$jscomp$21_newHeight$jscomp$17$$,_.$JSCompiler_StaticMethods_changeHeight$$(this,$e$jscomp$342_eventData$jscomp$23_matches$jscomp$21_newHeight$jscomp$17$$)))};_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$122$$){return"responsive"===$layout$jscomp$122$$||"flex-item"===$layout$jscomp$122$$||"fixed"===$layout$jscomp$122$$};_.$JSCompiler_prototypeAlias$$.$unlayoutOnPause$=function(){return!0};
_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$F$&&(_.$removeElement$$module$src$dom$$(this.$F$),this.$F$=null);this.$G$&&this.$G$();return!0};self.AMP.registerElement("amp-vk",$AmpVk$$module$extensions$amp_vk$0_1$amp_vk$$);
})});

//# sourceMappingURL=amp-vk-0.1.js.map
