(self.AMP=self.AMP||[]).push({n:"amp-soundcloud",i:["_base_i","_base_media"],v:"1904281823091",f:(function(AMP,_){
var $AmpSoundcloud$$module$extensions$amp_soundcloud$0_1$amp_soundcloud$$=function($$jscomp$super$this$jscomp$99_element$jscomp$626$$){$$jscomp$super$this$jscomp$99_element$jscomp$626$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$99_element$jscomp$626$$)||this;$$jscomp$super$this$jscomp$99_element$jscomp$626$$.$D$=null;return $$jscomp$super$this$jscomp$99_element$jscomp$626$$};_.$$jscomp$inherits$$($AmpSoundcloud$$module$extensions$amp_soundcloud$0_1$amp_soundcloud$$,AMP.BaseElement);
$AmpSoundcloud$$module$extensions$amp_soundcloud$0_1$amp_soundcloud$$.prototype.$preconnectCallback$=function($opt_onLayout$jscomp$26$$){this.$preconnect$.url("https://api.soundcloud.com/",$opt_onLayout$jscomp$26$$)};$AmpSoundcloud$$module$extensions$amp_soundcloud$0_1$amp_soundcloud$$.prototype.$isLayoutSupported$=function($layout$jscomp$102$$){return"fixed-height"==$layout$jscomp$102$$};
$AmpSoundcloud$$module$extensions$amp_soundcloud$0_1$amp_soundcloud$$.prototype.$layoutCallback$=function(){var $height$jscomp$73$$=this.element.getAttribute("height"),$color$jscomp$2$$=this.element.getAttribute("data-color"),$visual$$=this.element.getAttribute("data-visual"),$src$jscomp$66_url$jscomp$203$$="https://api.soundcloud.com/"+(this.element.hasAttribute("data-trackid")?"tracks":"playlists")+"/",$mediaid$$=this.element.getAttribute("data-trackid")||this.element.getAttribute("data-playlistid"),
$secret$$=this.element.getAttribute("data-secret-token"),$iframe$jscomp$82$$=this.element.ownerDocument.createElement("iframe");$iframe$jscomp$82$$.setAttribute("frameborder","no");$iframe$jscomp$82$$.setAttribute("scrolling","no");$src$jscomp$66_url$jscomp$203$$="https://w.soundcloud.com/player/?url="+encodeURIComponent($src$jscomp$66_url$jscomp$203$$+$mediaid$$);$secret$$&&($src$jscomp$66_url$jscomp$203$$+=encodeURIComponent("?secret_token="+$secret$$));"true"===$visual$$?$src$jscomp$66_url$jscomp$203$$+=
"&visual=true":$color$jscomp$2$$&&($src$jscomp$66_url$jscomp$203$$+="&color="+encodeURIComponent($color$jscomp$2$$));$iframe$jscomp$82$$.src=$src$jscomp$66_url$jscomp$203$$;_.$JSCompiler_StaticMethods_applyFillContent$$($iframe$jscomp$82$$);$iframe$jscomp$82$$.height=$height$jscomp$73$$;this.element.appendChild($iframe$jscomp$82$$);this.$D$=$iframe$jscomp$82$$;return this.$loadPromise$($iframe$jscomp$82$$)};
$AmpSoundcloud$$module$extensions$amp_soundcloud$0_1$amp_soundcloud$$.prototype.$pauseCallback$=function(){this.$D$&&this.$D$.contentWindow&&this.$D$.contentWindow.postMessage(JSON.stringify(_.$dict$$module$src$utils$object$$({method:"pause"})),"https://w.soundcloud.com")};self.AMP.registerElement("amp-soundcloud",$AmpSoundcloud$$module$extensions$amp_soundcloud$0_1$amp_soundcloud$$);
})});

//# sourceMappingURL=amp-soundcloud-0.1.js.map
