(self.AMP=self.AMP||[]).push({n:"amp-google-vrview-image",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $AmpGoogleVrviewImage$$module$extensions$amp_google_vrview_image$0_1$amp_google_vrview_image$$=function($$jscomp$super$this$jscomp$57_element$jscomp$487$$){$$jscomp$super$this$jscomp$57_element$jscomp$487$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$57_element$jscomp$487$$)||this;$$jscomp$super$this$jscomp$57_element$jscomp$487$$.$F$="";$$jscomp$super$this$jscomp$57_element$jscomp$487$$.$D$="";return $$jscomp$super$this$jscomp$57_element$jscomp$487$$};
_.$$jscomp$inherits$$($AmpGoogleVrviewImage$$module$extensions$amp_google_vrview_image$0_1$amp_google_vrview_image$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpGoogleVrviewImage$$module$extensions$amp_google_vrview_image$0_1$amp_google_vrview_image$$.prototype;_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$72$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$72$$)};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){this.$F$=this.element.getAttribute("src");var $src$jscomp$41$$=_.$addParamToUrl$$module$src$url$$("https://storage.googleapis.com/vrview/2.0/index.html","image",this.$F$);this.element.hasAttribute("stereo")&&($src$jscomp$41$$=_.$addParamToUrl$$module$src$url$$($src$jscomp$41$$,"is_stereo","true"));var $yaw$$=this.element.getAttribute("yaw");$yaw$$&&($src$jscomp$41$$=_.$addParamToUrl$$module$src$url$$($src$jscomp$41$$,"start_yaw",$yaw$$));this.element.hasAttribute("yaw-only")&&
($src$jscomp$41$$=_.$addParamToUrl$$module$src$url$$($src$jscomp$41$$,"is_yaw_only","true"));this.$D$=$src$jscomp$41$$};_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function(){this.$D$&&(this.$preconnect$.preload(this.$D$),this.$preconnect$.preload(this.$F$))};_.$JSCompiler_prototypeAlias$$.$createPlaceholderCallback$=function(){return null};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $iframe$jscomp$57$$=this.element.ownerDocument.createElement("iframe");$iframe$jscomp$57$$.onload=function(){$iframe$jscomp$57$$.readyState="complete"};_.$JSCompiler_StaticMethods_applyFillContent$$($iframe$jscomp$57$$);$iframe$jscomp$57$$.setAttribute("frameborder","0");$iframe$jscomp$57$$.setAttribute("allowfullscreen","true");$iframe$jscomp$57$$.setAttribute("src",this.$D$);this.element.appendChild($iframe$jscomp$57$$);return this.$loadPromise$($iframe$jscomp$57$$)};
self.AMP.registerElement("amp-google-vrview-image",$AmpGoogleVrviewImage$$module$extensions$amp_google_vrview_image$0_1$amp_google_vrview_image$$);
})});

//# sourceMappingURL=amp-google-vrview-image-0.1.js.map
