(self.AMP=self.AMP||[]).push({n:"amp-wistia-player",i:["_base_i","_base_media"],v:"1904281823091",f:(function(AMP,_){
var $AmpWistiaPlayer$$module$extensions$amp_wistia_player$0_1$amp_wistia_player$$=function($$jscomp$super$this$jscomp$124_element$jscomp$775$$){$$jscomp$super$this$jscomp$124_element$jscomp$775$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$124_element$jscomp$775$$)||this;$$jscomp$super$this$jscomp$124_element$jscomp$775$$.$D$=null;$$jscomp$super$this$jscomp$124_element$jscomp$775$$.$F$=null;$$jscomp$super$this$jscomp$124_element$jscomp$775$$.$G$=null;$$jscomp$super$this$jscomp$124_element$jscomp$775$$.$H$=
null;return $$jscomp$super$this$jscomp$124_element$jscomp$775$$},$JSCompiler_StaticMethods_AmpWistiaPlayer$$module$extensions$amp_wistia_player$0_1$amp_wistia_player_prototype$sendCommand_$$=function($JSCompiler_StaticMethods_AmpWistiaPlayer$$module$extensions$amp_wistia_player$0_1$amp_wistia_player_prototype$sendCommand_$self$$,$command$jscomp$10$$){$JSCompiler_StaticMethods_AmpWistiaPlayer$$module$extensions$amp_wistia_player$0_1$amp_wistia_player_prototype$sendCommand_$self$$.$F$.then(function(){$JSCompiler_StaticMethods_AmpWistiaPlayer$$module$extensions$amp_wistia_player$0_1$amp_wistia_player_prototype$sendCommand_$self$$.$D$&&
$JSCompiler_StaticMethods_AmpWistiaPlayer$$module$extensions$amp_wistia_player$0_1$amp_wistia_player_prototype$sendCommand_$self$$.$D$.contentWindow&&$JSCompiler_StaticMethods_AmpWistiaPlayer$$module$extensions$amp_wistia_player$0_1$amp_wistia_player_prototype$sendCommand_$self$$.$D$.contentWindow.postMessage($command$jscomp$10$$,"*")})};_.$$jscomp$inherits$$($AmpWistiaPlayer$$module$extensions$amp_wistia_player$0_1$amp_wistia_player$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpWistiaPlayer$$module$extensions$amp_wistia_player$0_1$amp_wistia_player$$.prototype;
_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($onLayout$jscomp$12$$){this.$preconnect$.url("https://fast.wistia.net",$onLayout$jscomp$12$$)};_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$124$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$124$$)};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){var $deferred$jscomp$68$$=new _.$Deferred$$module$src$utils$promise$$;this.$F$=$deferred$jscomp$68$$.$promise$;this.$G$=$deferred$jscomp$68$$.resolve;_.$installVideoManagerForDoc$$module$src$service$video_manager_impl$$(this.element);_.$Services$$module$src$services$videoManagerForDoc$$(this.element).register(this)};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $$jscomp$this$jscomp$1441$$=this,$element$jscomp$776$$=this.element,$iframe$jscomp$101_loaded$jscomp$5_mediaId$jscomp$1$$=$element$jscomp$776$$.getAttribute("data-media-hashed-id");$iframe$jscomp$101_loaded$jscomp$5_mediaId$jscomp$1$$=_.$createFrameFor$$module$src$iframe_video$$(this,"https://fast.wistia.net/embed/iframe/"+encodeURIComponent($iframe$jscomp$101_loaded$jscomp$5_mediaId$jscomp$1$$));$iframe$jscomp$101_loaded$jscomp$5_mediaId$jscomp$1$$.setAttribute("title",
$element$jscomp$776$$.getAttribute("title")||"Wistia Video Player");$iframe$jscomp$101_loaded$jscomp$5_mediaId$jscomp$1$$.setAttribute("scrolling","no");$iframe$jscomp$101_loaded$jscomp$5_mediaId$jscomp$1$$.setAttribute("allowtransparency","");this.$D$=$iframe$jscomp$101_loaded$jscomp$5_mediaId$jscomp$1$$;this.$H$=_.$listen$$module$src$event_helper$$(this.$win$,"message",this.$handleWistiaMessage_$.bind(this));$iframe$jscomp$101_loaded$jscomp$5_mediaId$jscomp$1$$=this.$loadPromise$(this.$D$).then(function(){$JSCompiler_StaticMethods_AmpWistiaPlayer$$module$extensions$amp_wistia_player$0_1$amp_wistia_player_prototype$sendCommand_$$($$jscomp$this$jscomp$1441$$,
"amp-listening");$element$jscomp$776$$.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$LOAD$)});this.$G$($iframe$jscomp$101_loaded$jscomp$5_mediaId$jscomp$1$$);return $iframe$jscomp$101_loaded$jscomp$5_mediaId$jscomp$1$$};
_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$D$=null);this.$H$&&this.$H$();var $deferred$jscomp$69$$=new _.$Deferred$$module$src$utils$promise$$;this.$F$=$deferred$jscomp$69$$.$promise$;this.$G$=$deferred$jscomp$69$$.resolve;return!0};_.$JSCompiler_prototypeAlias$$.$viewportCallback$=function($visible$jscomp$15$$){this.element.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$VISIBILITY$,{visible:$visible$jscomp$15$$})};
_.$JSCompiler_prototypeAlias$$.$pauseCallback$=function(){this.$D$&&this.pause()};
_.$JSCompiler_prototypeAlias$$.$handleWistiaMessage_$=function($data$jscomp$262_event$jscomp$267_eventData$jscomp$24$$){if(_.$originMatches$$module$src$iframe_video$$($data$jscomp$262_event$jscomp$267_eventData$jscomp$24$$,this.$D$,"https://fast.wistia.net")&&($data$jscomp$262_event$jscomp$267_eventData$jscomp$24$$=$data$jscomp$262_event$jscomp$267_eventData$jscomp$24$$.data,_.$isJsonOrObj$$module$src$iframe_video$$($data$jscomp$262_event$jscomp$267_eventData$jscomp$24$$)&&($data$jscomp$262_event$jscomp$267_eventData$jscomp$24$$=
_.$objOrParseJson$$module$src$iframe_video$$($data$jscomp$262_event$jscomp$267_eventData$jscomp$24$$),void 0!==$data$jscomp$262_event$jscomp$267_eventData$jscomp$24$$))){var $element$jscomp$777$$=this.element;if("_trigger"==$data$jscomp$262_event$jscomp$267_eventData$jscomp$24$$.method){var $playerEvent$$=$data$jscomp$262_event$jscomp$267_eventData$jscomp$24$$.args?$data$jscomp$262_event$jscomp$267_eventData$jscomp$24$$.args[0]:void 0;"statechange"===$playerEvent$$?_.$redispatch$$module$src$iframe_video$$($element$jscomp$777$$,
$data$jscomp$262_event$jscomp$267_eventData$jscomp$24$$.args?$data$jscomp$262_event$jscomp$267_eventData$jscomp$24$$.args[1]:void 0,{playing:_.$VideoEvents$$module$src$video_interface$$.$PLAYING$,paused:_.$VideoEvents$$module$src$video_interface$$.$PAUSE$,ended:[_.$VideoEvents$$module$src$video_interface$$.$PAUSE$,_.$VideoEvents$$module$src$video_interface$$.$ENDED$]}):"mutechange"==$playerEvent$$&&$element$jscomp$777$$.$dispatchCustomEvent$(_.$mutedOrUnmutedEvent$$module$src$iframe_video$$($data$jscomp$262_event$jscomp$267_eventData$jscomp$24$$.args?
$data$jscomp$262_event$jscomp$267_eventData$jscomp$24$$.args[1]:void 0))}}};_.$JSCompiler_prototypeAlias$$.play=function(){$JSCompiler_StaticMethods_AmpWistiaPlayer$$module$extensions$amp_wistia_player$0_1$amp_wistia_player_prototype$sendCommand_$$(this,"amp-play")};_.$JSCompiler_prototypeAlias$$.pause=function(){$JSCompiler_StaticMethods_AmpWistiaPlayer$$module$extensions$amp_wistia_player$0_1$amp_wistia_player_prototype$sendCommand_$$(this,"amp-pause")};
_.$JSCompiler_prototypeAlias$$.$mute$=function(){$JSCompiler_StaticMethods_AmpWistiaPlayer$$module$extensions$amp_wistia_player$0_1$amp_wistia_player_prototype$sendCommand_$$(this,"amp-mute")};_.$JSCompiler_prototypeAlias$$.$unmute$=function(){$JSCompiler_StaticMethods_AmpWistiaPlayer$$module$extensions$amp_wistia_player$0_1$amp_wistia_player_prototype$sendCommand_$$(this,"amp-unmute")};_.$JSCompiler_prototypeAlias$$.$supportsPlatform$=function(){return!0};
_.$JSCompiler_prototypeAlias$$.$isInteractive$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$showControls$=function(){};_.$JSCompiler_prototypeAlias$$.$hideControls$=function(){};_.$JSCompiler_prototypeAlias$$.$fullscreenEnter$=function(){this.$D$&&_.$fullscreenEnter$$module$src$dom$$(this.$D$)};_.$JSCompiler_prototypeAlias$$.$fullscreenExit$=function(){this.$D$&&_.$fullscreenExit$$module$src$dom$$(this.$D$)};_.$JSCompiler_prototypeAlias$$.getMetadata=function(){};
_.$JSCompiler_prototypeAlias$$.$preimplementsMediaSessionAPI$=function(){return!1};_.$JSCompiler_prototypeAlias$$.$preimplementsAutoFullscreen$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$getCurrentTime$=function(){return 0};_.$JSCompiler_prototypeAlias$$.$getDuration$=function(){return 1};_.$JSCompiler_prototypeAlias$$.$getPlayedRanges$=function(){return[]};_.$JSCompiler_prototypeAlias$$.$seekTo$=function(){this.$user$().error("amp-wistia-player","`seekTo` not supported.")};
self.AMP.registerElement("amp-wistia-player",$AmpWistiaPlayer$$module$extensions$amp_wistia_player$0_1$amp_wistia_player$$);
})});

//# sourceMappingURL=amp-wistia-player-0.1.js.map
