(self.AMP=self.AMP||[]).push({n:"amp-gfycat",i:["_base_i","_base_media"],v:"1904281823091",f:(function(AMP,_){
var $AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat$$=function($$jscomp$super$this$jscomp$54_element$jscomp$484$$){$$jscomp$super$this$jscomp$54_element$jscomp$484$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$54_element$jscomp$484$$)||this;$$jscomp$super$this$jscomp$54_element$jscomp$484$$.$H$="";$$jscomp$super$this$jscomp$54_element$jscomp$484$$.$D$=null;$$jscomp$super$this$jscomp$54_element$jscomp$484$$.$G$=null;$$jscomp$super$this$jscomp$54_element$jscomp$484$$.$F$=null;return $$jscomp$super$this$jscomp$54_element$jscomp$484$$},
$JSCompiler_StaticMethods_AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat_prototype$getVideoIframeSrc_$$=function($JSCompiler_StaticMethods_AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat_prototype$getVideoIframeSrc_$self$$){if($JSCompiler_StaticMethods_AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat_prototype$getVideoIframeSrc_$self$$.$G$)return $JSCompiler_StaticMethods_AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat_prototype$getVideoIframeSrc_$self$$.$G$;var $src$jscomp$37$$=
"https://gfycat.com/ifr/"+encodeURIComponent($JSCompiler_StaticMethods_AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat_prototype$getVideoIframeSrc_$self$$.$H$),$params$jscomp$32$$=_.$getDataParamsFromAttributes$$module$src$dom$$($JSCompiler_StaticMethods_AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat_prototype$getVideoIframeSrc_$self$$.element);$JSCompiler_StaticMethods_AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat_prototype$getVideoIframeSrc_$self$$.element.hasAttribute("noautoplay")&&
($params$jscomp$32$$.autoplay="0");$src$jscomp$37$$=_.$addParamsToUrl$$module$src$url$$($src$jscomp$37$$,$params$jscomp$32$$);return $JSCompiler_StaticMethods_AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat_prototype$getVideoIframeSrc_$self$$.$G$=$src$jscomp$37$$};_.$$jscomp$inherits$$($AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat$$.prototype;
_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($opt_onLayout$jscomp$16$$){this.$preconnect$.url("https://gfycat.com",$opt_onLayout$jscomp$16$$);this.$preconnect$.url("https://giant.gfycat.com",$opt_onLayout$jscomp$16$$);this.$preconnect$.url("https://thumbs.gfycat.com",$opt_onLayout$jscomp$16$$)};_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$69$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$69$$)};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){this.$H$=this.element.getAttribute("data-gfyid");this.element.hasAttribute("noautoplay")||this.element.setAttribute("autoplay","");_.$installVideoManagerForDoc$$module$src$service$video_manager_impl$$(this.element);_.$Services$$module$src$services$videoManagerForDoc$$(this.element).register(this)};
_.$JSCompiler_prototypeAlias$$.$createPlaceholderCallback$=function(){var $placeholder$jscomp$13$$=this.$win$.document.createElement("amp-img"),$videoid$$=this.$H$;_.$JSCompiler_StaticMethods_propagateAttributes$$(this,["alt","aria-label"],$placeholder$jscomp$13$$);$placeholder$jscomp$13$$.setAttribute("src","https://thumbs.gfycat.com/"+encodeURIComponent($videoid$$)+"-poster.jpg");$placeholder$jscomp$13$$.setAttribute("layout","fill");$placeholder$jscomp$13$$.setAttribute("placeholder","");$placeholder$jscomp$13$$.setAttribute("referrerpolicy",
"origin");this.element.hasAttribute("aria-label")?$placeholder$jscomp$13$$.setAttribute("alt","Loading gif "+this.element.getAttribute("aria-label")):this.element.hasAttribute("alt")?$placeholder$jscomp$13$$.setAttribute("alt","Loading gif "+this.element.getAttribute("alt")):$placeholder$jscomp$13$$.setAttribute("alt","Loading gif");_.$JSCompiler_StaticMethods_applyFillContent$$($placeholder$jscomp$13$$);return $placeholder$jscomp$13$$};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $$jscomp$this$jscomp$678$$=this,$iframe$jscomp$53$$=this.element.ownerDocument.createElement("iframe"),$src$jscomp$38$$=$JSCompiler_StaticMethods_AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat_prototype$getVideoIframeSrc_$$(this);$iframe$jscomp$53$$.setAttribute("frameborder","0");$iframe$jscomp$53$$.src=$src$jscomp$38$$;_.$JSCompiler_StaticMethods_applyFillContent$$($iframe$jscomp$53$$);this.$D$=$iframe$jscomp$53$$;this.$F$=_.$listen$$module$src$event_helper$$(this.$win$,
"message",this.$handleGfycatMessages_$.bind(this));this.element.appendChild($iframe$jscomp$53$$);return this.$loadPromise$(this.$D$).then(function(){$$jscomp$this$jscomp$678$$.element.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$LOAD$)})};_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$D$=null);this.$F$&&this.$F$();return!0};
_.$JSCompiler_prototypeAlias$$.$handleGfycatMessages_$=function($event$jscomp$139$$){var $eventData$jscomp$11$$=$event$jscomp$139$$.data;"https://gfycat.com"===$event$jscomp$139$$.origin&&$event$jscomp$139$$.source==this.$D$.contentWindow&&"string"===typeof $eventData$jscomp$11$$&&("paused"==$eventData$jscomp$11$$?this.element.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$PAUSE$):"playing"==$eventData$jscomp$11$$&&this.element.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$PLAYING$))};
_.$JSCompiler_prototypeAlias$$.$pauseCallback$=function(){this.pause()};_.$JSCompiler_prototypeAlias$$.$supportsPlatform$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$isInteractive$=function(){return!1};_.$JSCompiler_prototypeAlias$$.play=function(){this.$D$&&this.$D$.contentWindow&&this.$D$.contentWindow.postMessage("play","*")};_.$JSCompiler_prototypeAlias$$.pause=function(){this.$D$&&this.$D$.contentWindow&&this.$D$.contentWindow.postMessage("pause","*")};
_.$JSCompiler_prototypeAlias$$.$mute$=function(){};_.$JSCompiler_prototypeAlias$$.$unmute$=function(){};_.$JSCompiler_prototypeAlias$$.$showControls$=function(){};_.$JSCompiler_prototypeAlias$$.$hideControls$=function(){};_.$JSCompiler_prototypeAlias$$.$fullscreenEnter$=function(){};_.$JSCompiler_prototypeAlias$$.$fullscreenExit$=function(){};_.$JSCompiler_prototypeAlias$$.getMetadata=function(){};_.$JSCompiler_prototypeAlias$$.$preimplementsMediaSessionAPI$=function(){return!1};
_.$JSCompiler_prototypeAlias$$.$preimplementsAutoFullscreen$=function(){return!1};_.$JSCompiler_prototypeAlias$$.$getCurrentTime$=function(){return 0};_.$JSCompiler_prototypeAlias$$.$getDuration$=function(){return 1};_.$JSCompiler_prototypeAlias$$.$getPlayedRanges$=function(){return[]};_.$JSCompiler_prototypeAlias$$.$seekTo$=function(){this.$user$().error("amp-gfycat","`seekTo` not supported.")};self.AMP.registerElement("amp-gfycat",$AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat$$);
})});

//# sourceMappingURL=amp-gfycat-0.1.js.map
