(self.AMP=self.AMP||[]).push({n:"amp-link-rewriter",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $getScopeElements$$module$extensions$amp_link_rewriter$0_1$scope$$=function($ampDoc$jscomp$23_doc$jscomp$97$$,$configOpts$$){$ampDoc$jscomp$23_doc$jscomp$97$$=$ampDoc$jscomp$23_doc$jscomp$97$$.getRootNode();var $cssSelector$jscomp$1$$=$configOpts$$.section.join(" a, "),$selection$$=$ampDoc$jscomp$23_doc$jscomp$97$$.querySelectorAll("a"),$filteredSelection$$=[];0!==$configOpts$$.section.length&&($selection$$=$ampDoc$jscomp$23_doc$jscomp$97$$.querySelectorAll($cssSelector$jscomp$1$$+" a"));$selection$$.forEach(function($ampDoc$jscomp$23_doc$jscomp$97$$){$hasAttributeValues$$module$extensions$amp_link_rewriter$0_1$scope$$($ampDoc$jscomp$23_doc$jscomp$97$$,
$configOpts$$)&&$filteredSelection$$.push($ampDoc$jscomp$23_doc$jscomp$97$$)});return $filteredSelection$$},$hasAttributeValues$$module$extensions$amp_link_rewriter$0_1$scope$$=function($htmlElement$jscomp$4$$,$configOpts$jscomp$1$$){var $anchorAttr$$=$configOpts$jscomp$1$$.$attribute$;return Object.keys($anchorAttr$$).every(function($configOpts$jscomp$1$$){return(new RegExp($anchorAttr$$[$configOpts$jscomp$1$$])).test($htmlElement$jscomp$4$$.getAttribute($configOpts$jscomp$1$$))})},$parseAttribute$$module$extensions$amp_link_rewriter$0_1$config_options$$=
function($attribute$jscomp$7$$){var $newAttr$jscomp$2$$={};Object.keys($attribute$jscomp$7$$).forEach(function($key$jscomp$133$$){$newAttr$jscomp$2$$[$key$jscomp$133$$]="^"+$attribute$jscomp$7$$[$key$jscomp$133$$]+"$"});return $newAttr$jscomp$2$$},$LinkRewriter$$module$extensions$amp_link_rewriter$0_1$link_rewriter$$=function($referrer$jscomp$12$$,$ampElement$jscomp$2$$,$ampDoc$jscomp$24_config$jscomp$inline_3801$$){this.$F$=$ampDoc$jscomp$24_config$jscomp$inline_3801$$;try{var $JSCompiler_inline_result$jscomp$5959$$=
_.$getChildJsonConfig$$module$src$json$$($ampElement$jscomp$2$$)}catch($e$296$jscomp$inline_6681$$){throw _.$user$$module$src$log$$($ampElement$jscomp$2$$).$createError$("%s: %s","amp-link-rewriter",$e$296$jscomp$inline_6681$$);}$ampDoc$jscomp$24_config$jscomp$inline_3801$$=$JSCompiler_inline_result$jscomp$5959$$;this.$G$={output:$ampDoc$jscomp$24_config$jscomp$inline_3801$$.output.toString(),section:_.$hasOwn$$module$src$utils$object$$($ampDoc$jscomp$24_config$jscomp$inline_3801$$,"section")?$ampDoc$jscomp$24_config$jscomp$inline_3801$$.section:
[],$attribute$:_.$hasOwn$$module$src$utils$object$$($ampDoc$jscomp$24_config$jscomp$inline_3801$$,"attribute")?$parseAttribute$$module$extensions$amp_link_rewriter$0_1$config_options$$($ampDoc$jscomp$24_config$jscomp$inline_3801$$.attribute):{},$vars$:_.$hasOwn$$module$src$utils$object$$($ampDoc$jscomp$24_config$jscomp$inline_3801$$,"vars")?$ampDoc$jscomp$24_config$jscomp$inline_3801$$.vars:{}};this.$H$=$getScopeElements$$module$extensions$amp_link_rewriter$0_1$scope$$(this.$F$,this.$G$);this.$I$=
$referrer$jscomp$12$$;this.$D$="";this.$J$=_.$Services$$module$src$services$urlReplacementsForDoc$$($ampElement$jscomp$2$$)},$JSCompiler_StaticMethods_isListed_$$=function($JSCompiler_StaticMethods_isListed_$self$$,$anchor$jscomp$15$$){return null===$JSCompiler_StaticMethods_isListed_$self$$.$H$||0===$JSCompiler_StaticMethods_isListed_$self$$.$H$.length||0<$JSCompiler_StaticMethods_isListed_$self$$.$H$.filter(function($JSCompiler_StaticMethods_isListed_$self$$){return $JSCompiler_StaticMethods_isListed_$self$$===
$anchor$jscomp$15$$}).length?!0:!1},$JSCompiler_StaticMethods_isInternalLink_$$=function($htmlElement$jscomp$5$$,$trimmedDomains$$){var $href$jscomp$11$$=$htmlElement$jscomp$5$$.href;return $trimmedDomains$$.some(function($htmlElement$jscomp$5$$){var $trimmedDomains$$=$href$jscomp$11$$.match($REG_DOMAIN_URL$$module$extensions$amp_link_rewriter$0_1$link_rewriter$$);return $trimmedDomains$$?$REG_DOMAIN_URL$$module$extensions$amp_link_rewriter$0_1$link_rewriter$$.test($href$jscomp$11$$)&&$trimmedDomains$$[1]===
$htmlElement$jscomp$5$$:!0})},$JSCompiler_StaticMethods_replaceVars_$$=function($JSCompiler_StaticMethods_replaceVars_$self$$,$htmlElement$jscomp$7$$,$vars$jscomp$25$$){$WL_ANCHOR_ATTR$$module$extensions$amp_link_rewriter$0_1$link_rewriter$$.forEach(function($JSCompiler_StaticMethods_replaceVars_$self$$){$htmlElement$jscomp$7$$.getAttribute($JSCompiler_StaticMethods_replaceVars_$self$$)&&($vars$jscomp$25$$[$JSCompiler_StaticMethods_replaceVars_$self$$]=$htmlElement$jscomp$7$$.getAttribute($JSCompiler_StaticMethods_replaceVars_$self$$))});
var $dataset$jscomp$2$$=_.$getDataParamsFromAttributes$$module$src$dom$$($htmlElement$jscomp$7$$,void 0,$PREFIX_DATA_ATTR$$module$extensions$amp_link_rewriter$0_1$link_rewriter$$);Object.assign($vars$jscomp$25$$,$dataset$jscomp$2$$);$vars$jscomp$25$$.random=Math.random().toString(32).substr(2);Object.keys($vars$jscomp$25$$).forEach(function($htmlElement$jscomp$7$$){$vars$jscomp$25$$[$htmlElement$jscomp$7$$]&&($JSCompiler_StaticMethods_replaceVars_$self$$.$D$=$JSCompiler_StaticMethods_replaceVars_$self$$.$D$.replace("${"+
$htmlElement$jscomp$7$$+"}",encodeURIComponent($vars$jscomp$25$$[$htmlElement$jscomp$7$$])))});$JSCompiler_StaticMethods_replaceVars_$self$$.$D$=$JSCompiler_StaticMethods_replaceVars_$self$$.$D$.replace(/\${[A-Za-z0-9]+}+/,function(){return""});return $JSCompiler_StaticMethods_replaceVars_$self$$.$D$},$AmpLinkRewriter$$module$extensions$amp_link_rewriter$0_1$amp_link_rewriter$$=function($$jscomp$super$this$jscomp$73_element$jscomp$553$$){$$jscomp$super$this$jscomp$73_element$jscomp$553$$=AMP.BaseElement.call(this,
$$jscomp$super$this$jscomp$73_element$jscomp$553$$)||this;$$jscomp$super$this$jscomp$73_element$jscomp$553$$.$D$=$$jscomp$super$this$jscomp$73_element$jscomp$553$$.$getAmpDoc$();$$jscomp$super$this$jscomp$73_element$jscomp$553$$.$G$=null;$$jscomp$super$this$jscomp$73_element$jscomp$553$$.$F$="";$$jscomp$super$this$jscomp$73_element$jscomp$553$$.$H$=_.$Services$$module$src$services$navigationForDoc$$($$jscomp$super$this$jscomp$73_element$jscomp$553$$.$D$);return $$jscomp$super$this$jscomp$73_element$jscomp$553$$},
$JSCompiler_StaticMethods_attachClickEvent_$$=function($JSCompiler_StaticMethods_attachClickEvent_$self$$){_.$JSCompiler_StaticMethods_registerAnchorMutator$$($JSCompiler_StaticMethods_attachClickEvent_$self$$.$H$,function($anchor$jscomp$16$$){var $JSCompiler_StaticMethods_LinkRewriter$$module$extensions$amp_link_rewriter$0_1$link_rewriter_prototype$handleClick$self$jscomp$inline_3803$$=$JSCompiler_StaticMethods_attachClickEvent_$self$$.$G$;if($anchor$jscomp$16$$&&($JSCompiler_StaticMethods_LinkRewriter$$module$extensions$amp_link_rewriter$0_1$link_rewriter_prototype$handleClick$self$jscomp$inline_3803$$.$D$=
$JSCompiler_StaticMethods_LinkRewriter$$module$extensions$amp_link_rewriter$0_1$link_rewriter_prototype$handleClick$self$jscomp$inline_3803$$.$G$.output,$anchor$jscomp$16$$.href.match($REG_DOMAIN_URL$$module$extensions$amp_link_rewriter$0_1$link_rewriter$$)[1]!==$JSCompiler_StaticMethods_LinkRewriter$$module$extensions$amp_link_rewriter$0_1$link_rewriter_prototype$handleClick$self$jscomp$inline_3803$$.$D$.match($REG_DOMAIN_URL$$module$extensions$amp_link_rewriter$0_1$link_rewriter$$)[1]&&$JSCompiler_StaticMethods_isListed_$$($JSCompiler_StaticMethods_LinkRewriter$$module$extensions$amp_link_rewriter$0_1$link_rewriter_prototype$handleClick$self$jscomp$inline_3803$$,
$anchor$jscomp$16$$))){var $sourceTrimmedDomain$jscomp$inline_3805_vars$jscomp$inline_6688$$=_.$Services$$module$src$services$documentInfoForDoc$$($JSCompiler_StaticMethods_LinkRewriter$$module$extensions$amp_link_rewriter$0_1$link_rewriter_prototype$handleClick$self$jscomp$inline_3803$$.$F$).sourceUrl.match($REG_DOMAIN_URL$$module$extensions$amp_link_rewriter$0_1$link_rewriter$$)[1],$canonicalTrimmedDomain$jscomp$inline_3806$$=_.$Services$$module$src$services$documentInfoForDoc$$($JSCompiler_StaticMethods_LinkRewriter$$module$extensions$amp_link_rewriter$0_1$link_rewriter_prototype$handleClick$self$jscomp$inline_3803$$.$F$).canonicalUrl.match($REG_DOMAIN_URL$$module$extensions$amp_link_rewriter$0_1$link_rewriter$$)[1];
$JSCompiler_StaticMethods_isInternalLink_$$($anchor$jscomp$16$$,[$sourceTrimmedDomain$jscomp$inline_3805_vars$jscomp$inline_6688$$,$canonicalTrimmedDomain$jscomp$inline_3806$$])||($JSCompiler_StaticMethods_LinkRewriter$$module$extensions$amp_link_rewriter$0_1$link_rewriter_prototype$handleClick$self$jscomp$inline_3803$$.$D$=_.$JSCompiler_StaticMethods_expandUrlSync$$($JSCompiler_StaticMethods_LinkRewriter$$module$extensions$amp_link_rewriter$0_1$link_rewriter_prototype$handleClick$self$jscomp$inline_3803$$.$J$,
$JSCompiler_StaticMethods_LinkRewriter$$module$extensions$amp_link_rewriter$0_1$link_rewriter_prototype$handleClick$self$jscomp$inline_3803$$.$D$,{$DOCUMENT_REFERRER$:$JSCompiler_StaticMethods_LinkRewriter$$module$extensions$amp_link_rewriter$0_1$link_rewriter_prototype$handleClick$self$jscomp$inline_3803$$.$I$},void 0,$PAGE_PROP_WHITELIST$$module$extensions$amp_link_rewriter$0_1$link_rewriter$$),$sourceTrimmedDomain$jscomp$inline_3805_vars$jscomp$inline_6688$$=$JSCompiler_StaticMethods_LinkRewriter$$module$extensions$amp_link_rewriter$0_1$link_rewriter_prototype$handleClick$self$jscomp$inline_3803$$.$G$.$vars$,
$sourceTrimmedDomain$jscomp$inline_3805_vars$jscomp$inline_6688$$ instanceof Object&&($anchor$jscomp$16$$.href=$JSCompiler_StaticMethods_replaceVars_$$($JSCompiler_StaticMethods_LinkRewriter$$module$extensions$amp_link_rewriter$0_1$link_rewriter_prototype$handleClick$self$jscomp$inline_3803$$,$anchor$jscomp$16$$,$sourceTrimmedDomain$jscomp$inline_3805_vars$jscomp$inline_6688$$)))}},0)};var $WL_ANCHOR_ATTR$$module$extensions$amp_link_rewriter$0_1$link_rewriter$$=["href","id","rel","rev"],$PREFIX_DATA_ATTR$$module$extensions$amp_link_rewriter$0_1$link_rewriter$$=/^vars(.+)/,$REG_DOMAIN_URL$$module$extensions$amp_link_rewriter$0_1$link_rewriter$$=/^(?:https?:)?(?:\/\/)?([^\/?]+)/i,$PAGE_PROP_WHITELIST$$module$extensions$amp_link_rewriter$0_1$link_rewriter$$={SOURCE_URL:!0,DOCUMENT_REFERRER:!0};_.$$jscomp$inherits$$($AmpLinkRewriter$$module$extensions$amp_link_rewriter$0_1$amp_link_rewriter$$,AMP.BaseElement);
$AmpLinkRewriter$$module$extensions$amp_link_rewriter$0_1$amp_link_rewriter$$.prototype.$buildCallback$=function(){var $$jscomp$this$jscomp$780$$=this,$viewer$jscomp$45$$=_.$Services$$module$src$services$viewerForDoc$$(this.$D$);return this.$D$.$whenBodyAvailable$().then(function(){return $viewer$jscomp$45$$.$I$}).then(function($viewer$jscomp$45$$){return $$jscomp$this$jscomp$780$$.$F$=$viewer$jscomp$45$$}).then(this.$I$.bind(this))};
$AmpLinkRewriter$$module$extensions$amp_link_rewriter$0_1$amp_link_rewriter$$.prototype.$I$=function(){this.$G$=new $LinkRewriter$$module$extensions$amp_link_rewriter$0_1$link_rewriter$$(this.$F$,this.element,this.$D$);$JSCompiler_StaticMethods_attachClickEvent_$$(this)};$AmpLinkRewriter$$module$extensions$amp_link_rewriter$0_1$amp_link_rewriter$$.prototype.$isLayoutSupported$=function($layout$jscomp$83$$){return"nodisplay"===$layout$jscomp$83$$};self.AMP.registerElement("amp-link-rewriter",$AmpLinkRewriter$$module$extensions$amp_link_rewriter$0_1$amp_link_rewriter$$);
})});

//# sourceMappingURL=amp-link-rewriter-0.1.js.map
