(self.AMP=self.AMP||[]).push({n:"amp-auto-lightbox",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $resolveFalse$$module$extensions$amp_auto_lightbox$0_1$utils$promise$$=function(){return _.$tryResolve$$module$src$utils$promise$$(function(){return!1})},$resolveTrue$$module$extensions$amp_auto_lightbox$0_1$utils$promise$$=function(){return _.$tryResolve$$module$src$utils$promise$$(function(){return!0})},$CarouselCriteria$$module$extensions$amp_auto_lightbox$0_1$carousel_criteria$meetsAll$$=function($element$jscomp$366_images$$){if(!_.$isExperimentOn$$module$src$experiments$$($element$jscomp$366_images$$.ownerDocument.defaultView,
"amp-auto-lightbox-carousel"))return $resolveFalse$$module$extensions$amp_auto_lightbox$0_1$utils$promise$$();var $slides$$=$element$jscomp$366_images$$.querySelectorAll(".amp-carousel-slide");$element$jscomp$366_images$$=$element$jscomp$366_images$$.querySelectorAll("amp-img");if(1>$element$jscomp$366_images$$.length||$slides$$.length!=$element$jscomp$366_images$$.length)return $resolveFalse$$module$extensions$amp_auto_lightbox$0_1$utils$promise$$();var $promise$jscomp$38$$=$resolveTrue$$module$extensions$amp_auto_lightbox$0_1$utils$promise$$();
_.$iterateCursor$$module$src$dom$$($slides$$,function($element$jscomp$366_images$$){$promise$jscomp$38$$=$promise$jscomp$38$$.then(function($slides$$){return $slides$$?$SlideCriteria$$module$extensions$amp_auto_lightbox$0_1$carousel_criteria$meetsAll$$($element$jscomp$366_images$$):!1})});return $promise$jscomp$38$$},$SlideCriteria$$module$extensions$amp_auto_lightbox$0_1$carousel_criteria$meetsAll$$=function($element$jscomp$367$$){if("AMP-IMG"==$element$jscomp$367$$.tagName)return _.$tryResolve$$module$src$utils$promise$$(function(){return!_.$isActionableByTap$$module$src$auto_lightbox$$($element$jscomp$367$$)});
var $img$jscomp$7$$=$element$jscomp$367$$.querySelector("amp-img");return $img$jscomp$7$$?$SlideCriteria$$module$extensions$amp_auto_lightbox$0_1$carousel_criteria$meetsSizingCriteria$$($img$jscomp$7$$,$element$jscomp$367$$).then(function($img$jscomp$7$$){return $img$jscomp$7$$?!_.$isActionableByTap$$module$src$auto_lightbox$$($element$jscomp$367$$):!1}):$resolveFalse$$module$extensions$amp_auto_lightbox$0_1$utils$promise$$()},$SlideCriteria$$module$extensions$amp_auto_lightbox$0_1$carousel_criteria$meetsSizingCriteria$$=
function($img$jscomp$8$$,$slide$jscomp$1$$){return $img$jscomp$8$$.$getImpl$().then(function($impl$jscomp$26$$){return new Promise(function($resolve$jscomp$61$$){$impl$jscomp$26$$.$measureElement$(function(){var $impl$jscomp$26$$=$img$jscomp$8$$.$getLayoutBox$(),$imgWidth$$=$impl$jscomp$26$$.width;$impl$jscomp$26$$=$impl$jscomp$26$$.height;var $$jscomp$destructuring$var356$$=$slide$jscomp$1$$.getBoundingClientRect();$resolve$jscomp$61$$(.5<=$imgWidth$$*$impl$jscomp$26$$/($$jscomp$destructuring$var356$$.width*
$$jscomp$destructuring$var356$$.height))})})})},$NOOP$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$=function(){},$Criteria$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$meetsAll$$=function($element$jscomp$368$$){if("AMP-IMG"==$element$jscomp$368$$.tagName.toUpperCase()){var $$jscomp$inline_6453_naturalHeight$jscomp$inline_6455$$=$element$jscomp$368$$.querySelector("img");var $JSCompiler_temp$jscomp$5939_JSCompiler_temp$jscomp$779_disabledAncestor$jscomp$inline_2939_naturalWidth$jscomp$inline_6454$$=
$$jscomp$inline_6453_naturalHeight$jscomp$inline_6455$$.naturalWidth;$$jscomp$inline_6453_naturalHeight$jscomp$inline_6455$$=$$jscomp$inline_6453_naturalHeight$jscomp$inline_6455$$.naturalHeight;var $$jscomp$inline_6456_vw$jscomp$inline_6461$$=$element$jscomp$368$$.$getLayoutBox$(),$renderArea$jscomp$inline_6463_renderWidth$jscomp$inline_6457$$=$$jscomp$inline_6456_vw$jscomp$inline_6461$$.width,$renderHeight$jscomp$inline_6458$$=$$jscomp$inline_6456_vw$jscomp$inline_6461$$.height,$$jscomp$inline_6459_vh$jscomp$inline_6462$$=
_.$Services$$module$src$services$viewportForDoc$$($element$jscomp$368$$).$getSize$();$$jscomp$inline_6456_vw$jscomp$inline_6461$$=$$jscomp$inline_6459_vh$jscomp$inline_6462$$.width;$$jscomp$inline_6459_vh$jscomp$inline_6462$$=$$jscomp$inline_6459_vh$jscomp$inline_6462$$.height;$renderArea$jscomp$inline_6463_renderWidth$jscomp$inline_6457$$*=$renderHeight$jscomp$inline_6458$$;$JSCompiler_temp$jscomp$5939_JSCompiler_temp$jscomp$779_disabledAncestor$jscomp$inline_2939_naturalWidth$jscomp$inline_6454$$=
1.2<=$JSCompiler_temp$jscomp$5939_JSCompiler_temp$jscomp$779_disabledAncestor$jscomp$inline_2939_naturalWidth$jscomp$inline_6454$$*$$jscomp$inline_6453_naturalHeight$jscomp$inline_6455$$/$renderArea$jscomp$inline_6463_renderWidth$jscomp$inline_6457$$||$JSCompiler_temp$jscomp$5939_JSCompiler_temp$jscomp$779_disabledAncestor$jscomp$inline_2939_naturalWidth$jscomp$inline_6454$$>$$jscomp$inline_6456_vw$jscomp$inline_6461$$||$$jscomp$inline_6453_naturalHeight$jscomp$inline_6455$$>$$jscomp$inline_6459_vh$jscomp$inline_6462$$||
.25<=$renderArea$jscomp$inline_6463_renderWidth$jscomp$inline_6457$$/($$jscomp$inline_6456_vw$jscomp$inline_6461$$*$$jscomp$inline_6459_vh$jscomp$inline_6462$$)}else $JSCompiler_temp$jscomp$5939_JSCompiler_temp$jscomp$779_disabledAncestor$jscomp$inline_2939_naturalWidth$jscomp$inline_6454$$=!0;$JSCompiler_temp$jscomp$5939_JSCompiler_temp$jscomp$779_disabledAncestor$jscomp$inline_2939_naturalWidth$jscomp$inline_6454$$&&($JSCompiler_temp$jscomp$5939_JSCompiler_temp$jscomp$779_disabledAncestor$jscomp$inline_2939_naturalWidth$jscomp$inline_6454$$=
($JSCompiler_temp$jscomp$5939_JSCompiler_temp$jscomp$779_disabledAncestor$jscomp$inline_2939_naturalWidth$jscomp$inline_6454$$=_.$closestAncestorElementBySelector$$module$src$dom$$($element$jscomp$368$$,"a[href],amp-script,amp-story,button,amp-lightbox,amp-carousel,[placeholder],[data-amp-auto-lightbox-disable],amp-selector [option],[subscriptions-action]"))&&($JSCompiler_temp$jscomp$5939_JSCompiler_temp$jscomp$779_disabledAncestor$jscomp$inline_2939_naturalWidth$jscomp$inline_6454$$!=$element$jscomp$368$$||
_.$matches$$module$src$dom$$($JSCompiler_temp$jscomp$5939_JSCompiler_temp$jscomp$779_disabledAncestor$jscomp$inline_2939_naturalWidth$jscomp$inline_6454$$,"[placeholder],[data-amp-auto-lightbox-disable],amp-selector [option],[subscriptions-action]"))?!1:!_.$JSCompiler_StaticMethods_hasResolvableAction$$(_.$Services$$module$src$services$actionServiceForDoc$$($element$jscomp$368$$),$element$jscomp$368$$));return $JSCompiler_temp$jscomp$5939_JSCompiler_temp$jscomp$779_disabledAncestor$jscomp$inline_2939_naturalWidth$jscomp$inline_6454$$?
"AMP-CAROUSEL"==$element$jscomp$368$$.tagName.toUpperCase()?$CarouselCriteria$$module$extensions$amp_auto_lightbox$0_1$carousel_criteria$meetsAll$$($element$jscomp$368$$):$resolveTrue$$module$extensions$amp_auto_lightbox$0_1$utils$promise$$():$resolveFalse$$module$extensions$amp_auto_lightbox$0_1$utils$promise$$()},$markAsVisited$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$=function($candidate$jscomp$6$$){return $Mutation$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$mutate$$($candidate$jscomp$6$$,
function(){$candidate$jscomp$6$$.setAttribute("i-amphtml-auto-lightbox-visited","")})},$candidateSelector$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$=function($tagName$jscomp$32$$){return $tagName$jscomp$32$$+":not([lightbox]):not([i-amphtml-auto-lightbox-visited])"},$whenLoaded$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$=function($element$jscomp$373$$){return _.$whenUpgradedToCustomElement$$module$src$dom$$($element$jscomp$373$$).then(function($element$jscomp$373$$){return $element$jscomp$373$$.signals().whenSignal("load-end")})},
$DocMetaAnnotations$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$getAllLdJsonTypes$$=function($ampdoc$jscomp$153$$){return _.$toArray$$module$src$types$$($ampdoc$jscomp$153$$.getRootNode().querySelectorAll('script[type="application/ld+json"]')).map(function($ampdoc$jscomp$153$$){return(_.$tryParseJson$$module$src$json$$($ampdoc$jscomp$153$$.textContent)||{})["@type"]}).filter(function($ampdoc$jscomp$153$$){return $ampdoc$jscomp$153$$})},$DocMetaAnnotations$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$hasValidLdJsonType$$=
function($ampdoc$jscomp$154$$){return $DocMetaAnnotations$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$getAllLdJsonTypes$$($ampdoc$jscomp$154$$).some(function($ampdoc$jscomp$154$$){return $ENABLED_LD_JSON_TYPES$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$[$ampdoc$jscomp$154$$]})},$Mutation$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$mutate$$=function($ampEl$$,$mutator$jscomp$11$$){return _.$whenUpgradedToCustomElement$$module$src$dom$$($ampEl$$).then(function($ampEl$$){return $ampEl$$.$resources_$.$mutateElement$($ampEl$$,
$mutator$jscomp$11$$)})},$apply$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$=function($ampdoc$jscomp$158$$,$element$jscomp$375$$){return $Mutation$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$mutate$$($element$jscomp$375$$,function(){$element$jscomp$375$$.setAttribute("lightbox","i-amphtml-auto-lightbox-"+$uid$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$++)}).then(function(){_.$JSCompiler_StaticMethods_installExtensionForDoc$$(_.$Services$$module$src$services$extensionsFor$$($ampdoc$jscomp$158$$.$win$),
$ampdoc$jscomp$158$$,"amp-lightbox-gallery");$element$jscomp$375$$.$dispatchCustomEvent$("amp-auto-lightbox:newly-set");return $element$jscomp$375$$})},$runCandidates$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$=function($ampdoc$jscomp$159$$,$candidates$jscomp$1$$){$candidates$jscomp$1$$.map(function($candidates$jscomp$1$$){return $whenLoaded$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$($candidates$jscomp$1$$).then(function(){return $Criteria$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$meetsAll$$($candidates$jscomp$1$$).then(function($candidate$jscomp$7$$){if($candidate$jscomp$7$$)return _.$dev$$module$src$log$$().$Log$$module$src$log_prototype$info$("amp-auto-lightbox",
"apply",$candidates$jscomp$1$$),$apply$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$($ampdoc$jscomp$159$$,$candidates$jscomp$1$$)})},$NOOP$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$)})},$scan$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$=function($ampdoc$jscomp$160$$,$candidates$jscomp$inline_2955_opt_root$jscomp$2_root$jscomp$inline_2953$$){var $JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$;
($JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$=!!$ampdoc$jscomp$160$$.getRootNode().querySelector('script[custom-element="amp-lightbox-gallery"]')&&!!$ampdoc$jscomp$160$$.getRootNode().querySelector("[lightbox]:not([i-amphtml-auto-lightbox-visited])"))||($JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$=
($JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$=$ampdoc$jscomp$160$$.getRootNode().querySelector('meta[property="og:type"]'))?$JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$.getAttribute("content"):void 0,$JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$=
"article"!=$JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$&&!$DocMetaAnnotations$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$hasValidLdJsonType$$($ampdoc$jscomp$160$$));if($JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$)$JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$=
!1;else if($JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$=$ampdoc$jscomp$160$$.$win$,_.$getMode$$module$src$mode$$($JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$).localDev&&!_.$getMode$$module$src$mode$$($JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$).test)$JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$=
!0;else{var $firstElementChild$jscomp$inline_6469$$=$ampdoc$jscomp$160$$.$getBody$().firstElementChild;$JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$=$firstElementChild$jscomp$inline_6469$$?_.$JSCompiler_StaticMethods_Url$$module$src$service$url_impl_prototype$isProxyOrigin$$(_.$Services$$module$src$services$urlForDoc$$($firstElementChild$jscomp$inline_6469$$),$JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$.location):
!1}$JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$?($candidates$jscomp$inline_2955_opt_root$jscomp$2_root$jscomp$inline_2953$$=$candidates$jscomp$inline_2955_opt_root$jscomp$2_root$jscomp$inline_2953$$||$ampdoc$jscomp$160$$.$win$.document,$JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$=
$CANDIDATES$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$.map($candidateSelector$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$).join(","),$candidates$jscomp$inline_2955_opt_root$jscomp$2_root$jscomp$inline_2953$$=_.$toArray$$module$src$types$$($candidates$jscomp$inline_2955_opt_root$jscomp$2_root$jscomp$inline_2953$$.querySelectorAll($JSCompiler_inline_result$jscomp$7116_JSCompiler_temp$jscomp$5941_JSCompiler_temp$jscomp$7115_selector$jscomp$inline_2954_tag$jscomp$inline_7195_win$jscomp$inline_6468$$)),
$candidates$jscomp$inline_2955_opt_root$jscomp$2_root$jscomp$inline_2953$$.forEach($markAsVisited$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$),$runCandidates$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$($ampdoc$jscomp$160$$,$candidates$jscomp$inline_2955_opt_root$jscomp$2_root$jscomp$inline_2953$$)):_.$dev$$module$src$log$$().$Log$$module$src$log_prototype$info$("amp-auto-lightbox","disabled")};var $ENABLED_LD_JSON_TYPES$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$={Article:!0,NewsArticle:!0,BlogPosting:!0,LiveBlogPosting:!0,DiscussionForumPosting:!0},$CANDIDATES$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$=["amp-img","amp-carousel"],$uid$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$=0;
(function($$jscomp$destructuring$var364$$){var $ampdoc$jscomp$161$$=$$jscomp$destructuring$var364$$.ampdoc;$ampdoc$jscomp$161$$.$whenReady$().then(function(){$ampdoc$jscomp$161$$.getRootNode().addEventListener("amp:dom-update",function($$jscomp$destructuring$var364$$){$scan$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$($ampdoc$jscomp$161$$,$$jscomp$destructuring$var364$$.target)});$scan$$module$extensions$amp_auto_lightbox$0_1$amp_auto_lightbox$$($ampdoc$jscomp$161$$)})})(self.AMP);
})});

//# sourceMappingURL=amp-auto-lightbox-0.1.js.map
