(self.AMP=self.AMP||[]).push({n:"amp-ad-custom",i:["_base_i","_base_ad"],v:"1904281823091",f:(function(AMP,_){
var $pushIfNotExist$$module$src$utils$array$$=function($array$jscomp$13$$,$item$jscomp$1$$){0>$array$jscomp$13$$.indexOf($item$jscomp$1$$)&&$array$jscomp$13$$.push($item$jscomp$1$$)},$Validator$$module$extensions$amp_a4a$0_1$amp_ad_type_defs$$=function(){},$Renderer$$module$extensions$amp_a4a$0_1$amp_ad_type_defs$$=function(){},$getAmpAdMetadata$$module$extensions$amp_a4a$0_1$amp_ad_utils$$=function($creative$jscomp$5$$){for(var $metadataStart$jscomp$1$$=-1,$metadataString$jscomp$1$$,$i$jscomp$188_metadataEnd$jscomp$1$$=
0;$i$jscomp$188_metadataEnd$jscomp$1$$<$METADATA_STRINGS$$module$extensions$amp_a4a$0_1$amp_ad_utils$$.length&&!($metadataString$jscomp$1$$=$METADATA_STRINGS$$module$extensions$amp_a4a$0_1$amp_ad_utils$$[$i$jscomp$188_metadataEnd$jscomp$1$$],$metadataStart$jscomp$1$$=$creative$jscomp$5$$.lastIndexOf($metadataString$jscomp$1$$),0<=$metadataStart$jscomp$1$$);$i$jscomp$188_metadataEnd$jscomp$1$$++);if(0>$metadataStart$jscomp$1$$)return _.$dev$$module$src$log$$().$Log$$module$src$log_prototype$warn$("amp-ad-util",
"Could not locate start index for amp meta data in: "+$creative$jscomp$5$$),null;$i$jscomp$188_metadataEnd$jscomp$1$$=$creative$jscomp$5$$.lastIndexOf("\x3c/script>");if(0>$i$jscomp$188_metadataEnd$jscomp$1$$)return _.$dev$$module$src$log$$().$Log$$module$src$log_prototype$warn$("amp-ad-util","Could not locate closing script tag for amp meta data in: %s",$creative$jscomp$5$$),null;try{var $metaDataObj$jscomp$1$$=_.$parseJson$$module$src$json$$($creative$jscomp$5$$.slice($metadataStart$jscomp$1$$+
$metadataString$jscomp$1$$.length,$i$jscomp$188_metadataEnd$jscomp$1$$)),$ampRuntimeUtf16CharOffsets$jscomp$1$$=$metaDataObj$jscomp$1$$.ampRuntimeUtf16CharOffsets;if(!_.$isArray$$module$src$types$$($ampRuntimeUtf16CharOffsets$jscomp$1$$)){var $headStart_metaData$jscomp$1$$=$creative$jscomp$5$$.indexOf("<head>"),$headSubstring$$=$creative$jscomp$5$$.slice($headStart_metaData$jscomp$1$$,$creative$jscomp$5$$.indexOf("</head>")+7),$scriptStart$$=$headSubstring$$.indexOf("<script"),$scriptEnd$$=$headSubstring$$.lastIndexOf("\x3c/script>");
if(0>$scriptStart$$||0>$scriptEnd$$)throw Error("The mandatory script tag is missing or incorrect.");$ampRuntimeUtf16CharOffsets$jscomp$1$$=[$headStart_metaData$jscomp$1$$+$scriptStart$$,$headStart_metaData$jscomp$1$$+$scriptEnd$$+9]}else if(2!=$ampRuntimeUtf16CharOffsets$jscomp$1$$.length||"number"!==typeof $ampRuntimeUtf16CharOffsets$jscomp$1$$[0]||"number"!==typeof $ampRuntimeUtf16CharOffsets$jscomp$1$$[1])throw Error("Invalid runtime offsets");$headStart_metaData$jscomp$1$$={};if($metaDataObj$jscomp$1$$.customElementExtensions){if($headStart_metaData$jscomp$1$$.$customElementExtensions$=
$metaDataObj$jscomp$1$$.customElementExtensions,!_.$isArray$$module$src$types$$($headStart_metaData$jscomp$1$$.$customElementExtensions$))throw Error("Invalid extensions",$headStart_metaData$jscomp$1$$.$customElementExtensions$);}else $headStart_metaData$jscomp$1$$.$customElementExtensions$=[];if($metaDataObj$jscomp$1$$.customStylesheets){$headStart_metaData$jscomp$1$$.$customStylesheets$=$metaDataObj$jscomp$1$$.customStylesheets;if(!_.$isArray$$module$src$types$$($headStart_metaData$jscomp$1$$.$customStylesheets$))throw Error("Invalid custom stylesheets");
$headStart_metaData$jscomp$1$$.$customStylesheets$.forEach(function($creative$jscomp$5$$){if(!_.$isObject$$module$src$types$$($creative$jscomp$5$$)||!$creative$jscomp$5$$.href||"string"!==typeof $creative$jscomp$5$$.href||!_.$isSecureUrlDeprecated$$module$src$url$$($creative$jscomp$5$$.href))throw Error("Invalid custom stylesheets");})}_.$isArray$$module$src$types$$($metaDataObj$jscomp$1$$.images)&&($headStart_metaData$jscomp$1$$.images=$metaDataObj$jscomp$1$$.images.splice(0,5));$headStart_metaData$jscomp$1$$.$minifiedCreative$=
$creative$jscomp$5$$.slice(0,$ampRuntimeUtf16CharOffsets$jscomp$1$$[0])+$creative$jscomp$5$$.slice($ampRuntimeUtf16CharOffsets$jscomp$1$$[1],$metadataStart$jscomp$1$$)+$creative$jscomp$5$$.slice($i$jscomp$188_metadataEnd$jscomp$1$$+9);return $headStart_metaData$jscomp$1$$}catch($err$jscomp$25$$){return _.$dev$$module$src$log$$().$Log$$module$src$log_prototype$warn$("amp-ad-util","Invalid amp metadata: %s",$creative$jscomp$5$$.slice($metadataStart$jscomp$1$$+$metadataString$jscomp$1$$.length,$i$jscomp$188_metadataEnd$jscomp$1$$)),
null}},$AmpAdNetworkBase$$module$extensions$amp_a4a$0_1$amp_ad_network_base$$=function($$jscomp$super$this$jscomp$7_element$jscomp$301$$){$$jscomp$super$this$jscomp$7_element$jscomp$301$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$7_element$jscomp$301$$)||this;$$jscomp$super$this$jscomp$7_element$jscomp$301$$.$G$=null;$$jscomp$super$this$jscomp$7_element$jscomp$301$$.$I$=_.$map$$module$src$utils$object$$();$$jscomp$super$this$jscomp$7_element$jscomp$301$$.$F$=_.$map$$module$src$utils$object$$();
$$jscomp$super$this$jscomp$7_element$jscomp$301$$.$H$=_.$map$$module$src$utils$object$$();$$jscomp$super$this$jscomp$7_element$jscomp$301$$.$D$={};for(var $failureType$$ in $FailureType$$module$extensions$amp_a4a$0_1$amp_ad_type_defs$$)$$jscomp$super$this$jscomp$7_element$jscomp$301$$.$H$[$failureType$$]="COLLAPSE";$$jscomp$super$this$jscomp$7_element$jscomp$301$$.$K$=0;return $$jscomp$super$this$jscomp$7_element$jscomp$301$$},$JSCompiler_StaticMethods_registerRenderer$$=function($JSCompiler_StaticMethods_registerRenderer$self$$,
$renderer$$,$type$jscomp$176$$){$JSCompiler_StaticMethods_registerRenderer$self$$.$F$[$type$jscomp$176$$]&&_.$dev$$module$src$log$$().$Log$$module$src$log_prototype$warn$("amp-ad-network-base","Rendering mode already registered for type '"+$type$jscomp$176$$+"'");$JSCompiler_StaticMethods_registerRenderer$self$$.$F$[$type$jscomp$176$$]=$renderer$$},$JSCompiler_StaticMethods_sendRequest_$$=function($JSCompiler_StaticMethods_sendRequest_$self$$){_.$Services$$module$src$services$viewerForDoc$$($JSCompiler_StaticMethods_sendRequest_$self$$.$getAmpDoc$()).$D$.then(function(){var $url$jscomp$139$$=
$JSCompiler_StaticMethods_getRequestUrl$$($JSCompiler_StaticMethods_sendRequest_$self$$);$JSCompiler_StaticMethods_sendRequest_$self$$.$G$=_.$Services$$module$src$services$xhrFor$$($JSCompiler_StaticMethods_sendRequest_$self$$.$win$).fetch($url$jscomp$139$$,{mode:"cors",method:"GET",credentials:"include"})})},$JSCompiler_StaticMethods_invokeValidator_$$=function($JSCompiler_StaticMethods_invokeValidator_$self$$,$response$jscomp$41$$){return $response$jscomp$41$$.arrayBuffer?$response$jscomp$41$$.arrayBuffer().then(function($unvalidatedBytes$$){$response$jscomp$41$$.headers.get("AMP-Ad-Response-Type");
return $JSCompiler_StaticMethods_Validator$$module$extensions$amp_a4a$0_1$amp_ad_type_defs_prototype$validate$$($JSCompiler_StaticMethods_invokeValidator_$self$$.$D$,$unvalidatedBytes$$,$response$jscomp$41$$.headers).catch(function($JSCompiler_StaticMethods_invokeValidator_$self$$){return Promise.reject({type:"VALIDATOR_ERROR",$msg$:$JSCompiler_StaticMethods_invokeValidator_$self$$})})}):Promise.reject($JSCompiler_StaticMethods_handleFailure_$$($JSCompiler_StaticMethods_invokeValidator_$self$$,"INVALID_RESPONSE"))},
$JSCompiler_StaticMethods_invokeRenderer_$$=function($JSCompiler_StaticMethods_invokeRenderer_$self$$,$validatorOutput$$){return $JSCompiler_StaticMethods_invokeRenderer_$self$$.$F$[$validatorOutput$$.type].render($JSCompiler_StaticMethods_invokeRenderer_$self$$.$D$,$JSCompiler_StaticMethods_invokeRenderer_$self$$.element,$validatorOutput$$.$creativeData$).catch(function($JSCompiler_StaticMethods_invokeRenderer_$self$$){return Promise.reject({type:"RENDERER_ERROR",$msg$:$JSCompiler_StaticMethods_invokeRenderer_$self$$})})},
$JSCompiler_StaticMethods_handleFailure_$$=function($JSCompiler_StaticMethods_handleFailure_$self$$,$failureType$jscomp$1_recoveryMode$$,$error$jscomp$57$$){$failureType$jscomp$1_recoveryMode$$=$JSCompiler_StaticMethods_handleFailure_$self$$.$H$[$failureType$jscomp$1_recoveryMode$$];$error$jscomp$57$$&&_.$dev$$module$src$log$$().$Log$$module$src$log_prototype$warn$("amp-ad-network-base",$error$jscomp$57$$);switch($failureType$jscomp$1_recoveryMode$$){case "COLLAPSE":$JSCompiler_StaticMethods_handleFailure_$self$$.$attemptChangeSize$(0,
0);break;case "RETRY":$JSCompiler_StaticMethods_handleFailure_$self$$.$K$--&&$JSCompiler_StaticMethods_sendRequest_$$($JSCompiler_StaticMethods_handleFailure_$self$$);break;default:_.$dev$$module$src$log$$().error("amp-ad-network-base","Invalid recovery mode!")}},$NameFrameRenderer$$module$extensions$amp_a4a$0_1$name_frame_renderer$$=function(){},$renderCreativeIntoFriendlyFrame$$module$extensions$amp_a4a$0_1$friendly_frame_util$$=function($adUrl$jscomp$5$$,$size$jscomp$23$$,$element$jscomp$303$$,
$creativeMetadata$$){var $iframe$jscomp$22$$=_.$createElementWithAttributes$$module$src$dom$$($element$jscomp$303$$.ownerDocument,"iframe",_.$dict$$module$src$utils$object$$({height:$size$jscomp$23$$.height,width:$size$jscomp$23$$.width,frameborder:"0",allowfullscreen:"",allowtransparency:"",scrolling:"no"})),$fontsArray$jscomp$1$$=[];$creativeMetadata$$.$customStylesheets$&&$creativeMetadata$$.$customStylesheets$.forEach(function($adUrl$jscomp$5$$){($adUrl$jscomp$5$$=$adUrl$jscomp$5$$.href)&&$fontsArray$jscomp$1$$.push($adUrl$jscomp$5$$)});
return _.$installFriendlyIframeEmbed$$module$src$friendly_iframe_embed$$($iframe$jscomp$22$$,$element$jscomp$303$$,{host:$element$jscomp$303$$,url:$adUrl$jscomp$5$$,html:$creativeMetadata$$.$minifiedCreative$,$extensionIds$:$creativeMetadata$$.$customElementExtensions$||[],fonts:$fontsArray$jscomp$1$$},function($adUrl$jscomp$5$$){var $size$jscomp$23$$=$element$jscomp$303$$.$getAmpDoc$(),$creativeMetadata$$=new _.$A4AVariableSource$$module$extensions$amp_a4a$0_1$a4a_variable_source$$($element$jscomp$303$$.$getAmpDoc$(),
$adUrl$jscomp$5$$);_.$installServiceInEmbedScope$$module$src$service$$($adUrl$jscomp$5$$,"url-replace",new _.$UrlReplacements$$module$src$service$url_replacements_impl$$($size$jscomp$23$$,$creativeMetadata$$))}).then(function($adUrl$jscomp$5$$){var $size$jscomp$23$$=$element$jscomp$303$$.$isInViewport$();_.$JSCompiler_StaticMethods_FriendlyIframeEmbed$$module$src$friendly_iframe_embed_prototype$setVisible_$$($adUrl$jscomp$5$$,$size$jscomp$23$$);_.$setStyle$$module$src$style$$(($adUrl$jscomp$5$$.iframe.contentDocument||
$adUrl$jscomp$5$$.$win$.document).body,"visibility","visible");return $iframe$jscomp$22$$})},$TemplateValidator$$module$extensions$amp_a4a$0_1$template_validator$$=function(){},$JSCompiler_StaticMethods_Validator$$module$extensions$amp_a4a$0_1$amp_ad_type_defs_prototype$validate$$=function($context$jscomp$21$$,$body$jscomp$18_unvalidatedBytes$jscomp$1$$,$headers$jscomp$5$$){$body$jscomp$18_unvalidatedBytes$jscomp$1$$=_.$utf8Decode$$module$src$utils$bytes$$($body$jscomp$18_unvalidatedBytes$jscomp$1$$);
var $parsedResponseBody$$=_.$tryParseJson$$module$src$json$$($body$jscomp$18_unvalidatedBytes$jscomp$1$$);return!$parsedResponseBody$$||!$headers$jscomp$5$$||"amp-mustache"!==$headers$jscomp$5$$.get("AMP-Ad-Template-Extension")&&"amp-mustache"!==$headers$jscomp$5$$.get("AMP-template-amp-creative")?Promise.resolve({$creativeData$:{$creative$:$body$jscomp$18_unvalidatedBytes$jscomp$1$$},$adResponseType$:"template",type:"NON_AMP"}):($ampAdTemplateHelper$$module$extensions$amp_a4a$0_1$template_validator$$||
($ampAdTemplateHelper$$module$extensions$amp_a4a$0_1$template_validator$$=new _.$AmpAdTemplateHelper$$module$extensions$amp_a4a$0_1$amp_ad_template_helper$$($context$jscomp$21$$.$win$))).fetch($parsedResponseBody$$.$templateUrl$).then(function($body$jscomp$18_unvalidatedBytes$jscomp$1$$){$body$jscomp$18_unvalidatedBytes$jscomp$1$$=$getAmpAdMetadata$$module$extensions$amp_a4a$0_1$amp_ad_utils$$($body$jscomp$18_unvalidatedBytes$jscomp$1$$);$parsedResponseBody$$.$analytics$&&$pushIfNotExist$$module$src$utils$array$$($body$jscomp$18_unvalidatedBytes$jscomp$1$$.customElementExtensions,
"amp-analytics");$pushIfNotExist$$module$src$utils$array$$($body$jscomp$18_unvalidatedBytes$jscomp$1$$.customElementExtensions,"amp-mustache");var $headers$jscomp$5$$=_.$Services$$module$src$services$extensionsFor$$($context$jscomp$21$$.$win$);$body$jscomp$18_unvalidatedBytes$jscomp$1$$.$customElementExtensions$.forEach(function($context$jscomp$21$$){return _.$JSCompiler_StaticMethods_preloadExtension$$($headers$jscomp$5$$,$context$jscomp$21$$)});return Promise.resolve({$creativeData$:{$templateData$:$parsedResponseBody$$,
$creativeMetadata$:$body$jscomp$18_unvalidatedBytes$jscomp$1$$},$adResponseType$:"template",type:"AMP"})})},$TemplateRenderer$$module$extensions$amp_a4a$0_1$template_renderer$$=function(){},$AmpAdTemplate$$module$extensions$amp_ad_custom$0_1$amp_ad_custom$$=function($$jscomp$super$this$jscomp$8_element$jscomp$305$$){$$jscomp$super$this$jscomp$8_element$jscomp$305$$=$AmpAdNetworkBase$$module$extensions$amp_a4a$0_1$amp_ad_network_base$$.call(this,$$jscomp$super$this$jscomp$8_element$jscomp$305$$)||
this;var $type$jscomp$inline_2335$$="template";$type$jscomp$inline_2335$$=void 0===$type$jscomp$inline_2335$$?"default":$type$jscomp$inline_2335$$;$$jscomp$super$this$jscomp$8_element$jscomp$305$$.$I$[$type$jscomp$inline_2335$$]&&_.$dev$$module$src$log$$().$Log$$module$src$log_prototype$warn$("amp-ad-network-base",$type$jscomp$inline_2335$$+" validator already registered.");$$jscomp$super$this$jscomp$8_element$jscomp$305$$.$I$[$type$jscomp$inline_2335$$]=$validator$$module$extensions$amp_ad_custom$0_1$amp_ad_custom$$;
$JSCompiler_StaticMethods_registerRenderer$$($$jscomp$super$this$jscomp$8_element$jscomp$305$$,new $TemplateRenderer$$module$extensions$amp_a4a$0_1$template_renderer$$,"AMP");$JSCompiler_StaticMethods_registerRenderer$$($$jscomp$super$this$jscomp$8_element$jscomp$305$$,$nameFrameRenderer$$module$extensions$amp_ad_custom$0_1$amp_ad_custom$$,"NON_AMP");$$jscomp$super$this$jscomp$8_element$jscomp$305$$.$J$=$$jscomp$super$this$jscomp$8_element$jscomp$305$$.element.getAttribute("src");$$jscomp$super$this$jscomp$8_element$jscomp$305$$.getContext().$win$=
$$jscomp$super$this$jscomp$8_element$jscomp$305$$.$win$;return $$jscomp$super$this$jscomp$8_element$jscomp$305$$},$JSCompiler_StaticMethods_getRequestUrl$$=function($JSCompiler_StaticMethods_getRequestUrl$self$$){var $url$jscomp$140$$=$JSCompiler_StaticMethods_getRequestUrl$self$$.$J$;Object.keys($JSCompiler_StaticMethods_getRequestUrl$self$$.element.dataset).forEach(function($dataField$$){if(_.$startsWith$$module$src$string$$($dataField$$,"requestParam")){var $requestParamName$$=$dataField$$.slice(12,
$dataField$$.length);$requestParamName$$&&($url$jscomp$140$$=_.$addParamToUrl$$module$src$url$$($url$jscomp$140$$,$requestParamName$$.charAt(0).toLowerCase()+$requestParamName$$.slice(1),$JSCompiler_StaticMethods_getRequestUrl$self$$.element.dataset[$dataField$$]))}});return $JSCompiler_StaticMethods_getRequestUrl$self$$.getContext().$adUrl$=$url$jscomp$140$$},$FailureType$$module$extensions$amp_a4a$0_1$amp_ad_type_defs$$={$REQUEST_ERROR$:"REQUEST_ERROR",$INVALID_RESPONSE$:"INVALID_RESPONSE",$EMPTY_RESPONSE$:"EMPTY_RESPONSE",
$VALIDATOR_ERROR$:"VALIDATOR_ERROR",$RENDERER_ERROR$:"RENDERER_ERROR"},$METADATA_STRINGS$$module$extensions$amp_a4a$0_1$amp_ad_utils$$=["<script amp-ad-metadata type=application/json>",'<script type="application/json" amp-ad-metadata>',"<script type=application/json amp-ad-metadata>"];_.$$jscomp$inherits$$($AmpAdNetworkBase$$module$extensions$amp_a4a$0_1$amp_ad_network_base$$,AMP.BaseElement);$AmpAdNetworkBase$$module$extensions$amp_a4a$0_1$amp_ad_network_base$$.prototype.$isLayoutSupported$=function($layout$jscomp$34$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$34$$)};$AmpAdNetworkBase$$module$extensions$amp_a4a$0_1$amp_ad_network_base$$.prototype.$onLayoutMeasure$=function(){$JSCompiler_StaticMethods_sendRequest_$$(this)};
$AmpAdNetworkBase$$module$extensions$amp_a4a$0_1$amp_ad_network_base$$.prototype.$layoutCallback$=function(){var $$jscomp$this$jscomp$311$$=this;return this.$G$.then(function($response$jscomp$40$$){return $JSCompiler_StaticMethods_invokeValidator_$$($$jscomp$this$jscomp$311$$,$response$jscomp$40$$)}).then(function($validatorResult$$){return $JSCompiler_StaticMethods_invokeRenderer_$$($$jscomp$this$jscomp$311$$,$validatorResult$$)}).catch(function($error$jscomp$56$$){return $JSCompiler_StaticMethods_handleFailure_$$($$jscomp$this$jscomp$311$$,
$error$jscomp$56$$.type,$error$jscomp$56$$.$msg$)})};$AmpAdNetworkBase$$module$extensions$amp_a4a$0_1$amp_ad_network_base$$.prototype.getContext=function(){return this.$D$};_.$$jscomp$inherits$$($NameFrameRenderer$$module$extensions$amp_a4a$0_1$name_frame_renderer$$,$Renderer$$module$extensions$amp_a4a$0_1$amp_ad_type_defs$$);
$NameFrameRenderer$$module$extensions$amp_a4a$0_1$name_frame_renderer$$.prototype.render=function($attributes$jscomp$14_context$jscomp$20$$,$element$jscomp$302$$,$crossDomainData_iframe$jscomp$21$$){if(!$crossDomainData_iframe$jscomp$21$$.$creative$&&!$crossDomainData_iframe$jscomp$21$$.$rawCreativeBytes$)return Promise.resolve();var $creative$jscomp$6$$=$crossDomainData_iframe$jscomp$21$$.$creative$||_.$utf8Decode$$module$src$utils$bytes$$($crossDomainData_iframe$jscomp$21$$.$rawCreativeBytes$),
$srcPath$jscomp$1$$=_.$getDefaultBootstrapBaseUrl$$module$src$3p_frame$$($attributes$jscomp$14_context$jscomp$20$$.$win$,"nameframe"),$contextMetadata$jscomp$1$$=_.$getContextMetadata$$module$src$iframe_attributes$$($attributes$jscomp$14_context$jscomp$20$$.$win$,$element$jscomp$302$$,$attributes$jscomp$14_context$jscomp$20$$.sentinel,$crossDomainData_iframe$jscomp$21$$.$additionalContextMetadata$);$contextMetadata$jscomp$1$$.creative=$creative$jscomp$6$$;$attributes$jscomp$14_context$jscomp$20$$=
_.$dict$$module$src$utils$object$$({src:$srcPath$jscomp$1$$,name:JSON.stringify($contextMetadata$jscomp$1$$),height:$attributes$jscomp$14_context$jscomp$20$$.size.height,width:$attributes$jscomp$14_context$jscomp$20$$.size.width,frameborder:"0",allowfullscreen:"",allowtransparency:"",scrolling:"no",marginwidth:"0",marginheight:"0"});$crossDomainData_iframe$jscomp$21$$.sentinel&&($attributes$jscomp$14_context$jscomp$20$$["data-amp-3p-sentinel"]=$crossDomainData_iframe$jscomp$21$$.sentinel);$crossDomainData_iframe$jscomp$21$$=
_.$createElementWithAttributes$$module$src$dom$$($element$jscomp$302$$.ownerDocument,"iframe",$attributes$jscomp$14_context$jscomp$20$$);$element$jscomp$302$$.appendChild($crossDomainData_iframe$jscomp$21$$);return Promise.resolve()};var $ampAdTemplateHelper$$module$extensions$amp_a4a$0_1$template_validator$$;_.$$jscomp$inherits$$($TemplateValidator$$module$extensions$amp_a4a$0_1$template_validator$$,$Validator$$module$extensions$amp_a4a$0_1$amp_ad_type_defs$$);_.$$jscomp$inherits$$($TemplateRenderer$$module$extensions$amp_a4a$0_1$template_renderer$$,$Renderer$$module$extensions$amp_a4a$0_1$amp_ad_type_defs$$);
$TemplateRenderer$$module$extensions$amp_a4a$0_1$template_renderer$$.prototype.render=function($context$jscomp$22$$,$element$jscomp$304$$,$creativeData$$){return $renderCreativeIntoFriendlyFrame$$module$extensions$amp_a4a$0_1$friendly_frame_util$$($context$jscomp$22$$.$adUrl$,$context$jscomp$22$$.size,$element$jscomp$304$$,$creativeData$$.$creativeMetadata$).then(function($element$jscomp$304$$){var $iframe$jscomp$23$$=$creativeData$$.$templateData$,$data$jscomp$115$$=$iframe$jscomp$23$$.data;return $data$jscomp$115$$?
($ampAdTemplateHelper$$module$extensions$amp_a4a$0_1$template_validator$$||($ampAdTemplateHelper$$module$extensions$amp_a4a$0_1$template_validator$$=new _.$AmpAdTemplateHelper$$module$extensions$amp_a4a$0_1$amp_ad_template_helper$$($context$jscomp$22$$.$win$))).render($data$jscomp$115$$,$element$jscomp$304$$.contentWindow.document.body).then(function($context$jscomp$22$$){var $creativeData$$=$iframe$jscomp$23$$.$analytics$;$creativeData$$&&_.$JSCompiler_StaticMethods_insertAnalytics$$($context$jscomp$22$$,
$creativeData$$);$creativeData$$=$element$jscomp$304$$.contentWindow.document.querySelector("template");$creativeData$$.parentNode.replaceChild($context$jscomp$22$$,$creativeData$$)}):Promise.resolve()})};var $validator$$module$extensions$amp_ad_custom$0_1$amp_ad_custom$$=new $TemplateValidator$$module$extensions$amp_a4a$0_1$template_validator$$,$nameFrameRenderer$$module$extensions$amp_ad_custom$0_1$amp_ad_custom$$=new $NameFrameRenderer$$module$extensions$amp_a4a$0_1$name_frame_renderer$$;_.$$jscomp$inherits$$($AmpAdTemplate$$module$extensions$amp_ad_custom$0_1$amp_ad_custom$$,$AmpAdNetworkBase$$module$extensions$amp_a4a$0_1$amp_ad_network_base$$);
$AmpAdTemplate$$module$extensions$amp_ad_custom$0_1$amp_ad_custom$$.prototype.$buildCallback$=function(){this.getContext().size={width:this.element.getAttribute("width"),height:this.element.getAttribute("height"),$layout$:this.element.getAttribute("layout")}};self.AMP.registerElement("amp-ad-custom",$AmpAdTemplate$$module$extensions$amp_ad_custom$0_1$amp_ad_custom$$);
})});

//# sourceMappingURL=amp-ad-custom-0.1.js.map
