(self.AMP=self.AMP||[]).push({n:"amp-selector",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $areEqualOrdered$$module$src$utils$array$$=function($arr1$$,$arr2$$){if($arr1$$.length!==$arr2$$.length)return!1;for(var $i$jscomp$55$$=0;$i$jscomp$55$$<$arr1$$.length;$i$jscomp$55$$++)if($arr1$$[$i$jscomp$55$$]!==$arr2$$[$i$jscomp$55$$])return!1;return!0},$AmpSelector$$module$extensions$amp_selector$0_1$amp_selector$$=function($$jscomp$super$this$jscomp$92_element$jscomp$597$$){$$jscomp$super$this$jscomp$92_element$jscomp$597$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$92_element$jscomp$597$$)||
this;$$jscomp$super$this$jscomp$92_element$jscomp$597$$.$H$=!1;$$jscomp$super$this$jscomp$92_element$jscomp$597$$.$F$=[];$$jscomp$super$this$jscomp$92_element$jscomp$597$$.$D$=[];$$jscomp$super$this$jscomp$92_element$jscomp$597$$.$J$=[];$$jscomp$super$this$jscomp$92_element$jscomp$597$$.$K$=null;$$jscomp$super$this$jscomp$92_element$jscomp$597$$.$G$=0;$$jscomp$super$this$jscomp$92_element$jscomp$597$$.$I$="none";return $$jscomp$super$this$jscomp$92_element$jscomp$597$$},$JSCompiler_StaticMethods_selectedAttributeMutated_$$=
function($JSCompiler_StaticMethods_selectedAttributeMutated_$self$$,$current$jscomp$9_i$319_newValue$jscomp$29$$){var $isSelected_selected$jscomp$2$$=Array.isArray($current$jscomp$9_i$319_newValue$jscomp$29$$)?$current$jscomp$9_i$319_newValue$jscomp$29$$:[$current$jscomp$9_i$319_newValue$jscomp$29$$];if(null===$current$jscomp$9_i$319_newValue$jscomp$29$$||0==$isSelected_selected$jscomp$2$$.length)$JSCompiler_StaticMethods_selectedAttributeMutated_$self$$.$clearAllSelections_$();else if($JSCompiler_StaticMethods_selectedAttributeMutated_$self$$.$H$||
($isSelected_selected$jscomp$2$$=$isSelected_selected$jscomp$2$$.slice(0,1)),$current$jscomp$9_i$319_newValue$jscomp$29$$=$JSCompiler_StaticMethods_selectedOptions_$$($JSCompiler_StaticMethods_selectedAttributeMutated_$self$$),!$areEqualOrdered$$module$src$utils$array$$($current$jscomp$9_i$319_newValue$jscomp$29$$.sort(),$isSelected_selected$jscomp$2$$.sort())){$isSelected_selected$jscomp$2$$=$isSelected_selected$jscomp$2$$.reduce(function($JSCompiler_StaticMethods_selectedAttributeMutated_$self$$,
$current$jscomp$9_i$319_newValue$jscomp$29$$){$JSCompiler_StaticMethods_selectedAttributeMutated_$self$$[$current$jscomp$9_i$319_newValue$jscomp$29$$]=!0;return $JSCompiler_StaticMethods_selectedAttributeMutated_$self$$},Object.create(null));for($current$jscomp$9_i$319_newValue$jscomp$29$$=0;$current$jscomp$9_i$319_newValue$jscomp$29$$<$JSCompiler_StaticMethods_selectedAttributeMutated_$self$$.$D$.length;$current$jscomp$9_i$319_newValue$jscomp$29$$++){var $element$jscomp$598$$=$JSCompiler_StaticMethods_selectedAttributeMutated_$self$$.$D$[$current$jscomp$9_i$319_newValue$jscomp$29$$],
$option$jscomp$12$$=$element$jscomp$598$$.getAttribute("option");$isSelected_selected$jscomp$2$$[$option$jscomp$12$$]?$JSCompiler_StaticMethods_setSelection_$$($JSCompiler_StaticMethods_selectedAttributeMutated_$self$$,$element$jscomp$598$$):$JSCompiler_StaticMethods_clearSelection_$$($JSCompiler_StaticMethods_selectedAttributeMutated_$self$$,$element$jscomp$598$$)}$JSCompiler_StaticMethods_updateFocus_$$($JSCompiler_StaticMethods_selectedAttributeMutated_$self$$);$JSCompiler_StaticMethods_setInputs_$$($JSCompiler_StaticMethods_selectedAttributeMutated_$self$$)}},
$JSCompiler_StaticMethods_updateFocus_$$=function($JSCompiler_StaticMethods_updateFocus_$self$$,$focusElement_opt_focusEl$$){"none"!=$JSCompiler_StaticMethods_updateFocus_$self$$.$I$&&($JSCompiler_StaticMethods_updateFocus_$self$$.$D$.forEach(function($JSCompiler_StaticMethods_updateFocus_$self$$){$JSCompiler_StaticMethods_updateFocus_$self$$.tabIndex=-1}),$focusElement_opt_focusEl$$||($focusElement_opt_focusEl$$=$JSCompiler_StaticMethods_updateFocus_$self$$.$H$?$JSCompiler_StaticMethods_updateFocus_$self$$.$D$[0]:
$JSCompiler_StaticMethods_updateFocus_$self$$.$F$[0]||$JSCompiler_StaticMethods_updateFocus_$self$$.$D$[0]),$focusElement_opt_focusEl$$&&($JSCompiler_StaticMethods_updateFocus_$self$$.$G$=$JSCompiler_StaticMethods_updateFocus_$self$$.$D$.indexOf($focusElement_opt_focusEl$$),$focusElement_opt_focusEl$$.tabIndex=0))},$JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$init_$$=function($JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$init_$self$$,
$elements$jscomp$39_opt_elements$$){$JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$init_$self$$.$F$.length=0;$elements$jscomp$39_opt_elements$$=$elements$jscomp$39_opt_elements$$?$elements$jscomp$39_opt_elements$$:_.$toArray$$module$src$types$$($JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$init_$self$$.element.querySelectorAll("[option]"));$elements$jscomp$39_opt_elements$$.forEach(function($elements$jscomp$39_opt_elements$$){$elements$jscomp$39_opt_elements$$.hasAttribute("role")||
$elements$jscomp$39_opt_elements$$.setAttribute("role","option");$elements$jscomp$39_opt_elements$$.hasAttribute("disabled")&&$elements$jscomp$39_opt_elements$$.setAttribute("aria-disabled","true");$elements$jscomp$39_opt_elements$$.hasAttribute("selected")?$JSCompiler_StaticMethods_setSelection_$$($JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$init_$self$$,$elements$jscomp$39_opt_elements$$):$JSCompiler_StaticMethods_clearSelection_$$($JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$init_$self$$,
$elements$jscomp$39_opt_elements$$);$elements$jscomp$39_opt_elements$$.tabIndex=0});$JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$init_$self$$.$D$=$elements$jscomp$39_opt_elements$$;$JSCompiler_StaticMethods_updateFocus_$$($JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$init_$self$$);$JSCompiler_StaticMethods_setInputs_$$($JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$init_$self$$)},
$JSCompiler_StaticMethods_setInputs_$$=function($JSCompiler_StaticMethods_setInputs_$self$$){var $selectedValues$$=[],$elementName$jscomp$8$$=$JSCompiler_StaticMethods_setInputs_$self$$.element.getAttribute("name");if($elementName$jscomp$8$$&&!$JSCompiler_StaticMethods_setInputs_$self$$.element.hasAttribute("disabled")){var $formId$$=$JSCompiler_StaticMethods_setInputs_$self$$.element.getAttribute("form");$JSCompiler_StaticMethods_setInputs_$self$$.$J$.forEach(function($selectedValues$$){$JSCompiler_StaticMethods_setInputs_$self$$.element.removeChild($selectedValues$$)});
$JSCompiler_StaticMethods_setInputs_$self$$.$J$=[];var $doc$jscomp$109$$=$JSCompiler_StaticMethods_setInputs_$self$$.$win$.document,$fragment$jscomp$10$$=$doc$jscomp$109$$.createDocumentFragment();$JSCompiler_StaticMethods_setInputs_$self$$.$F$.forEach(function($option$jscomp$14_value$jscomp$269$$){if(!$option$jscomp$14_value$jscomp$269$$.hasAttribute("disabled")){var $hidden$jscomp$2$$=$doc$jscomp$109$$.createElement("input");$option$jscomp$14_value$jscomp$269$$=$option$jscomp$14_value$jscomp$269$$.getAttribute("option");
$hidden$jscomp$2$$.setAttribute("type","hidden");$hidden$jscomp$2$$.setAttribute("name",$elementName$jscomp$8$$);$hidden$jscomp$2$$.setAttribute("value",$option$jscomp$14_value$jscomp$269$$);$formId$$&&$hidden$jscomp$2$$.setAttribute("form",$formId$$);$JSCompiler_StaticMethods_setInputs_$self$$.$J$.push($hidden$jscomp$2$$);$fragment$jscomp$10$$.appendChild($hidden$jscomp$2$$);$selectedValues$$.push($option$jscomp$14_value$jscomp$269$$)}});$JSCompiler_StaticMethods_setInputs_$self$$.element.appendChild($fragment$jscomp$10$$)}},
$JSCompiler_StaticMethods_onOptionPicked_$$=function($JSCompiler_StaticMethods_onOptionPicked_$self$$,$el$jscomp$86$$){$el$jscomp$86$$.hasAttribute("disabled")||$JSCompiler_StaticMethods_onOptionPicked_$self$$.$mutateElement$(function(){$el$jscomp$86$$.hasAttribute("selected")?$JSCompiler_StaticMethods_onOptionPicked_$self$$.$H$&&($JSCompiler_StaticMethods_clearSelection_$$($JSCompiler_StaticMethods_onOptionPicked_$self$$,$el$jscomp$86$$),$JSCompiler_StaticMethods_setInputs_$$($JSCompiler_StaticMethods_onOptionPicked_$self$$)):
($JSCompiler_StaticMethods_setSelection_$$($JSCompiler_StaticMethods_onOptionPicked_$self$$,$el$jscomp$86$$),$JSCompiler_StaticMethods_setInputs_$$($JSCompiler_StaticMethods_onOptionPicked_$self$$));$JSCompiler_StaticMethods_updateFocus_$$($JSCompiler_StaticMethods_onOptionPicked_$self$$,$el$jscomp$86$$);$JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$fireSelectEvent_$$($JSCompiler_StaticMethods_onOptionPicked_$self$$,$el$jscomp$86$$)})},$JSCompiler_StaticMethods_selectedOptions_$$=
function($JSCompiler_StaticMethods_selectedOptions_$self$$){return $JSCompiler_StaticMethods_selectedOptions_$self$$.$F$.map(function($JSCompiler_StaticMethods_selectedOptions_$self$$){return $JSCompiler_StaticMethods_selectedOptions_$self$$.getAttribute("option")})},$JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$fireSelectEvent_$$=function($JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$fireSelectEvent_$self$$,
$el$jscomp$90_selectEvent$jscomp$1$$){$el$jscomp$90_selectEvent$jscomp$1$$=_.$createCustomEvent$$module$src$event_helper$$($JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$fireSelectEvent_$self$$.$win$,"amp-selector.select",_.$dict$$module$src$utils$object$$({targetOption:$el$jscomp$90_selectEvent$jscomp$1$$.getAttribute("option"),selectedOptions:$JSCompiler_StaticMethods_selectedOptions_$$($JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$fireSelectEvent_$self$$)}));
$JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$fireSelectEvent_$self$$.$K$.$trigger$($JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$fireSelectEvent_$self$$.element,"select",$el$jscomp$90_selectEvent$jscomp$1$$,100)},$JSCompiler_StaticMethods_select_$$=function($JSCompiler_StaticMethods_select_$self$$,$delta$jscomp$9_previousEl$$){var $previousIndex$$=$JSCompiler_StaticMethods_select_$self$$.$D$.indexOf($JSCompiler_StaticMethods_select_$self$$.$F$[0]);
$JSCompiler_StaticMethods_setSelection_$$($JSCompiler_StaticMethods_select_$self$$,$JSCompiler_StaticMethods_select_$self$$.$D$[_.$mod$$module$src$utils$math$$(-1===$previousIndex$$&&0>$delta$jscomp$9_previousEl$$?$delta$jscomp$9_previousEl$$:$previousIndex$$+$delta$jscomp$9_previousEl$$,$JSCompiler_StaticMethods_select_$self$$.$D$.length)]);($delta$jscomp$9_previousEl$$=$JSCompiler_StaticMethods_select_$self$$.$D$[$previousIndex$$])&&$JSCompiler_StaticMethods_clearSelection_$$($JSCompiler_StaticMethods_select_$self$$,
$delta$jscomp$9_previousEl$$)},$JSCompiler_StaticMethods_clearSelection_$$=function($JSCompiler_StaticMethods_clearSelection_$self$$,$element$jscomp$599_selIndex$$){$element$jscomp$599_selIndex$$.removeAttribute("selected");$element$jscomp$599_selIndex$$.setAttribute("aria-selected","false");$element$jscomp$599_selIndex$$=$JSCompiler_StaticMethods_clearSelection_$self$$.$F$.indexOf($element$jscomp$599_selIndex$$);-1!==$element$jscomp$599_selIndex$$&&$JSCompiler_StaticMethods_clearSelection_$self$$.$F$.splice($element$jscomp$599_selIndex$$,
1)},$JSCompiler_StaticMethods_setSelection_$$=function($JSCompiler_StaticMethods_setSelection_$self$$,$element$jscomp$600$$){$JSCompiler_StaticMethods_setSelection_$self$$.$F$.includes($element$jscomp$600$$)||($JSCompiler_StaticMethods_setSelection_$self$$.$H$||$JSCompiler_StaticMethods_setSelection_$self$$.$clearAllSelections_$(),$element$jscomp$600$$.setAttribute("selected",""),$element$jscomp$600$$.setAttribute("aria-selected","true"),$JSCompiler_StaticMethods_setSelection_$self$$.$F$.push($element$jscomp$600$$))};var $KEYBOARD_SELECT_MODES$$module$extensions$amp_selector$0_1$amp_selector$$={NONE:"none",$FOCUS$:"focus",$SELECT$:"select"};_.$$jscomp$inherits$$($AmpSelector$$module$extensions$amp_selector$0_1$amp_selector$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpSelector$$module$extensions$amp_selector$0_1$amp_selector$$.prototype;_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function(){return!0};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){var $$jscomp$this$jscomp$871$$=this;this.$K$=_.$Services$$module$src$services$actionServiceForDoc$$(this.element);this.$H$=this.element.hasAttribute("multiple");this.element.hasAttribute("role")||this.element.setAttribute("role","listbox");this.$H$&&this.element.setAttribute("aria-multiselectable","true");this.element.hasAttribute("disabled")&&this.element.setAttribute("aria-disabled","true");var $kbSelectMode$$=this.element.getAttribute("keyboard-select-mode");
$kbSelectMode$$?($kbSelectMode$$=$kbSelectMode$$.toLowerCase(),_.$JSCompiler_StaticMethods_assertEnumValue$$(_.$user$$module$src$log$$(),$KEYBOARD_SELECT_MODES$$module$extensions$amp_selector$0_1$amp_selector$$,$kbSelectMode$$)):$kbSelectMode$$="none";this.$I$=$kbSelectMode$$;_.$JSCompiler_StaticMethods_registerAction$$(this,"clear",this.$clearAllSelections_$.bind(this));$JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$init_$$(this);this.element.addEventListener("click",
this.$AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$clickHandler_$.bind(this));this.element.addEventListener("keydown",this.$AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$keyDownHandler_$.bind(this));_.$JSCompiler_StaticMethods_registerAction$$(this,"selectUp",function($kbSelectMode$$){$kbSelectMode$$=$kbSelectMode$$.args;$JSCompiler_StaticMethods_select_$$($$jscomp$this$jscomp$871$$,$kbSelectMode$$&&void 0!==$kbSelectMode$$.delta?-$kbSelectMode$$.delta:
-1)},1);_.$JSCompiler_StaticMethods_registerAction$$(this,"selectDown",function($kbSelectMode$$){$kbSelectMode$$=$kbSelectMode$$.args;$JSCompiler_StaticMethods_select_$$($$jscomp$this$jscomp$871$$,$kbSelectMode$$&&void 0!==$kbSelectMode$$.delta?$kbSelectMode$$.delta:1)},1);_.$JSCompiler_StaticMethods_registerAction$$(this,"toggle",function($kbSelectMode$$){var $index$jscomp$inline_4211_invocation$jscomp$47_selectedEl$jscomp$inline_4216$$=$kbSelectMode$$.args;if($index$jscomp$inline_4211_invocation$jscomp$47_selectedEl$jscomp$inline_4216$$&&
void 0!==$index$jscomp$inline_4211_invocation$jscomp$47_selectedEl$jscomp$inline_4216$$.index){$kbSelectMode$$=$index$jscomp$inline_4211_invocation$jscomp$47_selectedEl$jscomp$inline_4216$$.index;var $opt_value$jscomp$inline_4212$$=$index$jscomp$inline_4211_invocation$jscomp$47_selectedEl$jscomp$inline_4216$$.value;$index$jscomp$inline_4211_invocation$jscomp$47_selectedEl$jscomp$inline_4216$$=$$jscomp$this$jscomp$871$$.$D$[$kbSelectMode$$];var $indexCurrentStatus$jscomp$inline_4214$$=$index$jscomp$inline_4211_invocation$jscomp$47_selectedEl$jscomp$inline_4216$$.hasAttribute("selected"),
$selectedIndex$jscomp$inline_4215$$=$$jscomp$this$jscomp$871$$.$D$.indexOf($$jscomp$this$jscomp$871$$.$F$[0]);(void 0!==$opt_value$jscomp$inline_4212$$?$opt_value$jscomp$inline_4212$$:!$indexCurrentStatus$jscomp$inline_4214$$)!==$indexCurrentStatus$jscomp$inline_4214$$&&($selectedIndex$jscomp$inline_4215$$!==$kbSelectMode$$?($JSCompiler_StaticMethods_setSelection_$$($$jscomp$this$jscomp$871$$,$index$jscomp$inline_4211_invocation$jscomp$47_selectedEl$jscomp$inline_4216$$),($kbSelectMode$$=$$jscomp$this$jscomp$871$$.$D$[$selectedIndex$jscomp$inline_4215$$])&&
$JSCompiler_StaticMethods_clearSelection_$$($$jscomp$this$jscomp$871$$,$kbSelectMode$$)):$JSCompiler_StaticMethods_clearSelection_$$($$jscomp$this$jscomp$871$$,$index$jscomp$inline_4211_invocation$jscomp$47_selectedEl$jscomp$inline_4216$$),$JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$fireSelectEvent_$$($$jscomp$this$jscomp$871$$,$index$jscomp$inline_4211_invocation$jscomp$47_selectedEl$jscomp$inline_4216$$))}},1);this.element.addEventListener("amp:dom-update",
this.$maybeRefreshOnUpdate_$.bind(this))};
_.$JSCompiler_prototypeAlias$$.$mutatedAttributesCallback$=function($disabled$jscomp$4_mutations$jscomp$24$$){var $selected$jscomp$1$$=$disabled$jscomp$4_mutations$jscomp$24$$.selected;void 0!==$selected$jscomp$1$$&&$JSCompiler_StaticMethods_selectedAttributeMutated_$$(this,$selected$jscomp$1$$);$disabled$jscomp$4_mutations$jscomp$24$$=$disabled$jscomp$4_mutations$jscomp$24$$.disabled;void 0!==$disabled$jscomp$4_mutations$jscomp$24$$&&($disabled$jscomp$4_mutations$jscomp$24$$?this.element.setAttribute("aria-disabled",
"true"):this.element.removeAttribute("aria-disabled"))};_.$JSCompiler_prototypeAlias$$.$maybeRefreshOnUpdate_$=function(){var $newElements$$=_.$toArray$$module$src$types$$(this.element.querySelectorAll("[option]"));$areEqualOrdered$$module$src$utils$array$$(this.$D$,$newElements$$)||$JSCompiler_StaticMethods_AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$init_$$(this,$newElements$$)};
_.$JSCompiler_prototypeAlias$$.$AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$clickHandler_$=function($el$jscomp$88_event$jscomp$186$$){!this.element.hasAttribute("disabled")&&($el$jscomp$88_event$jscomp$186$$=$el$jscomp$88_event$jscomp$186$$.target)&&($el$jscomp$88_event$jscomp$186$$.hasAttribute("option")||($el$jscomp$88_event$jscomp$186$$=_.$closestAncestorElementBySelector$$module$src$dom$$($el$jscomp$88_event$jscomp$186$$,"[option]")),$el$jscomp$88_event$jscomp$186$$&&
$JSCompiler_StaticMethods_onOptionPicked_$$(this,$el$jscomp$88_event$jscomp$186$$))};
_.$JSCompiler_prototypeAlias$$.$AmpSelector$$module$extensions$amp_selector$0_1$amp_selector_prototype$keyDownHandler_$=function($event$jscomp$187_focusedOption$jscomp$inline_4223_newSelectedOption$jscomp$inline_4222$$){if(!this.element.hasAttribute("disabled"))switch($event$jscomp$187_focusedOption$jscomp$inline_4223_newSelectedOption$jscomp$inline_4222$$.key){case "ArrowLeft":case "ArrowUp":case "ArrowRight":case "ArrowDown":if("none"!=this.$I$)a:{var $dir$jscomp$inline_4221_doc$jscomp$inline_4220_key$jscomp$inline_4227$$=
this.$win$.document;switch($event$jscomp$187_focusedOption$jscomp$inline_4223_newSelectedOption$jscomp$inline_4222$$.key){case "ArrowLeft":$dir$jscomp$inline_4221_doc$jscomp$inline_4220_key$jscomp$inline_4227$$=_.$isRTL$$module$src$dom$$($dir$jscomp$inline_4221_doc$jscomp$inline_4220_key$jscomp$inline_4227$$)?1:-1;break;case "ArrowUp":$dir$jscomp$inline_4221_doc$jscomp$inline_4220_key$jscomp$inline_4227$$=-1;break;case "ArrowRight":$dir$jscomp$inline_4221_doc$jscomp$inline_4220_key$jscomp$inline_4227$$=
_.$isRTL$$module$src$dom$$($dir$jscomp$inline_4221_doc$jscomp$inline_4220_key$jscomp$inline_4227$$)?-1:1;break;case "ArrowDown":$dir$jscomp$inline_4221_doc$jscomp$inline_4220_key$jscomp$inline_4227$$=1;break;default:break a}$event$jscomp$187_focusedOption$jscomp$inline_4223_newSelectedOption$jscomp$inline_4222$$.preventDefault();this.$D$[this.$G$].tabIndex=-1;this.$G$=(this.$G$+$dir$jscomp$inline_4221_doc$jscomp$inline_4220_key$jscomp$inline_4227$$)%this.$D$.length;0>this.$G$&&(this.$G$+=this.$D$.length);
$event$jscomp$187_focusedOption$jscomp$inline_4223_newSelectedOption$jscomp$inline_4222$$=this.$D$[this.$G$];$event$jscomp$187_focusedOption$jscomp$inline_4223_newSelectedOption$jscomp$inline_4222$$.tabIndex=0;_.$tryFocus$$module$src$dom$$($event$jscomp$187_focusedOption$jscomp$inline_4223_newSelectedOption$jscomp$inline_4222$$);$event$jscomp$187_focusedOption$jscomp$inline_4223_newSelectedOption$jscomp$inline_4222$$=this.$D$[this.$G$];"select"==this.$I$&&$JSCompiler_StaticMethods_onOptionPicked_$$(this,
$event$jscomp$187_focusedOption$jscomp$inline_4223_newSelectedOption$jscomp$inline_4222$$)}break;case "Enter":case " ":$dir$jscomp$inline_4221_doc$jscomp$inline_4220_key$jscomp$inline_4227$$=$event$jscomp$187_focusedOption$jscomp$inline_4223_newSelectedOption$jscomp$inline_4222$$.key," "!=$dir$jscomp$inline_4221_doc$jscomp$inline_4220_key$jscomp$inline_4227$$&&"Enter"!=$dir$jscomp$inline_4221_doc$jscomp$inline_4220_key$jscomp$inline_4227$$||!this.$D$.includes($event$jscomp$187_focusedOption$jscomp$inline_4223_newSelectedOption$jscomp$inline_4222$$.target)||
($event$jscomp$187_focusedOption$jscomp$inline_4223_newSelectedOption$jscomp$inline_4222$$.preventDefault(),$JSCompiler_StaticMethods_onOptionPicked_$$(this,$event$jscomp$187_focusedOption$jscomp$inline_4223_newSelectedOption$jscomp$inline_4222$$.target))}};_.$JSCompiler_prototypeAlias$$.$clearAllSelections_$=function(){for(;0<this.$F$.length;){var $el$jscomp$92$$=this.$F$.pop();$JSCompiler_StaticMethods_clearSelection_$$(this,$el$jscomp$92$$)}$JSCompiler_StaticMethods_setInputs_$$(this)};
self.AMP.registerElement("amp-selector",$AmpSelector$$module$extensions$amp_selector$0_1$amp_selector$$,"amp-selector [option]{cursor:pointer}amp-selector [option][selected]{cursor:auto;outline:1px solid rgba(0,0,0,0.7)}amp-selector [disabled][option],amp-selector[disabled] [option],amp-selector[disabled] [selected],amp-selector [selected][disabled]{cursor:auto;outline:none}\n/*# sourceURL=/extensions/amp-selector/0.1/amp-selector.css*/");
})});

//# sourceMappingURL=amp-selector-0.1.js.map
