(self.AMP=self.AMP||[]).push({n:"amp-audio",i:["_base_i","_base_media"],v:"1904281823091",f:(function(AMP,_){
var $AmpAudio$$module$extensions$amp_audio$0_1$amp_audio$$=function($$jscomp$super$this$jscomp$23_element$jscomp$364$$){$$jscomp$super$this$jscomp$23_element$jscomp$364$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$23_element$jscomp$364$$)||this;$$jscomp$super$this$jscomp$23_element$jscomp$364$$.$D$=null;$$jscomp$super$this$jscomp$23_element$jscomp$364$$.$F$=_.$EMPTY_METADATA$$module$src$mediasession_helper$$;$$jscomp$super$this$jscomp$23_element$jscomp$364$$.$G$=!1;return $$jscomp$super$this$jscomp$23_element$jscomp$364$$},
$JSCompiler_StaticMethods_buildAudioElement$$=function($JSCompiler_StaticMethods_buildAudioElement$self$$){var $audio$$=$JSCompiler_StaticMethods_buildAudioElement$self$$.element.ownerDocument.createElement("audio");$audio$$.play?($audio$$.controls=!0,$JSCompiler_StaticMethods_buildAudioElement$self$$.element.getAttribute("src"),_.$JSCompiler_StaticMethods_propagateAttributes$$($JSCompiler_StaticMethods_buildAudioElement$self$$,"src preload autoplay muted loop aria-label aria-describedby aria-labelledby controlsList".split(" "),
$audio$$),_.$JSCompiler_StaticMethods_applyFillContent$$($audio$$),$JSCompiler_StaticMethods_buildAudioElement$self$$.$getRealChildNodes$().forEach(function($JSCompiler_StaticMethods_buildAudioElement$self$$){$JSCompiler_StaticMethods_buildAudioElement$self$$.getAttribute&&$JSCompiler_StaticMethods_buildAudioElement$self$$.getAttribute("src")&&$JSCompiler_StaticMethods_buildAudioElement$self$$.getAttribute("src");$audio$$.appendChild($JSCompiler_StaticMethods_buildAudioElement$self$$)}),$JSCompiler_StaticMethods_buildAudioElement$self$$.element.appendChild($audio$$),
$JSCompiler_StaticMethods_buildAudioElement$self$$.$D$=$audio$$,_.$listen$$module$src$event_helper$$($JSCompiler_StaticMethods_buildAudioElement$self$$.$D$,"playing",function(){return $JSCompiler_StaticMethods_audioPlaying_$$($JSCompiler_StaticMethods_buildAudioElement$self$$)})):($JSCompiler_StaticMethods_buildAudioElement$self$$.$toggleFallback$(!0),Promise.resolve())},$JSCompiler_StaticMethods_isInvocationValid_$$=function($JSCompiler_StaticMethods_isInvocationValid_$self$$){return $JSCompiler_StaticMethods_isInvocationValid_$self$$.$D$?
_.$closestAncestorElementBySelector$$module$src$dom$$($JSCompiler_StaticMethods_isInvocationValid_$self$$.element,"AMP-STORY")?(_.$user$$module$src$log$$().$Log$$module$src$log_prototype$warn$("amp-audio","<amp-story> elements do not support actions on <amp-audio> elements"),!1):!0:!1},$JSCompiler_StaticMethods_setPlayingStateForTesting_$$=function($JSCompiler_StaticMethods_setPlayingStateForTesting_$self$$,$isPlaying$jscomp$1$$){_.$getMode$$module$src$mode$$().test&&($JSCompiler_StaticMethods_setPlayingStateForTesting_$self$$.$G$=
$isPlaying$jscomp$1$$)},$JSCompiler_StaticMethods_audioPlaying_$$=function($JSCompiler_StaticMethods_audioPlaying_$self$$){_.$setMediaSession$$module$src$mediasession_helper$$($JSCompiler_StaticMethods_audioPlaying_$self$$.element,$JSCompiler_StaticMethods_audioPlaying_$self$$.$win$,$JSCompiler_StaticMethods_audioPlaying_$self$$.$F$,function(){$JSCompiler_StaticMethods_audioPlaying_$self$$.$D$.play();$JSCompiler_StaticMethods_setPlayingStateForTesting_$$($JSCompiler_StaticMethods_audioPlaying_$self$$,
!0)},function(){$JSCompiler_StaticMethods_audioPlaying_$self$$.$D$.pause();$JSCompiler_StaticMethods_setPlayingStateForTesting_$$($JSCompiler_StaticMethods_audioPlaying_$self$$,!1)})};_.$$jscomp$inherits$$($AmpAudio$$module$extensions$amp_audio$0_1$amp_audio$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpAudio$$module$extensions$amp_audio$0_1$amp_audio$$.prototype;
_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$41$$){return"fixed"==$layout$jscomp$41$$||"fixed-height"==$layout$jscomp$41$$};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){"nodisplay"===this.$getLayout$()&&(this.element.removeAttribute("autoplay"),$JSCompiler_StaticMethods_buildAudioElement$$(this));_.$JSCompiler_StaticMethods_registerAction$$(this,"play",this.$AmpAudio$$module$extensions$amp_audio$0_1$amp_audio_prototype$play_$.bind(this));_.$JSCompiler_StaticMethods_registerAction$$(this,"pause",this.$AmpAudio$$module$extensions$amp_audio$0_1$amp_audio_prototype$pause_$.bind(this))};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){"nodisplay"!==this.$getLayout$()&&$JSCompiler_StaticMethods_buildAudioElement$$(this);var $artwork$jscomp$1_document$jscomp$9$$=this.$getAmpDoc$().$win$.document,$artist$$=this.element.getAttribute("artist")||"",$title$jscomp$21$$=this.element.getAttribute("title")||this.element.getAttribute("aria-label")||$artwork$jscomp$1_document$jscomp$9$$.title||"",$album$$=this.element.getAttribute("album")||"";$artwork$jscomp$1_document$jscomp$9$$=
this.element.getAttribute("artwork")||_.$parseSchemaImage$$module$src$mediasession_helper$$($artwork$jscomp$1_document$jscomp$9$$)||_.$parseOgImage$$module$src$mediasession_helper$$($artwork$jscomp$1_document$jscomp$9$$)||_.$parseFavicon$$module$src$mediasession_helper$$($artwork$jscomp$1_document$jscomp$9$$)||"";this.$F$={title:$title$jscomp$21$$,$artist$:$artist$$,$album$:$album$$,$artwork$:[{src:$artwork$jscomp$1_document$jscomp$9$$}]};return this.$loadPromise$(this.$D$)};
_.$JSCompiler_prototypeAlias$$.$renderOutsideViewport$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$pauseCallback$=function(){this.$D$&&(this.$D$.pause(),$JSCompiler_StaticMethods_setPlayingStateForTesting_$$(this,!1))};_.$JSCompiler_prototypeAlias$$.$AmpAudio$$module$extensions$amp_audio$0_1$amp_audio_prototype$pause_$=function(){$JSCompiler_StaticMethods_isInvocationValid_$$(this)&&(this.$D$.pause(),$JSCompiler_StaticMethods_setPlayingStateForTesting_$$(this,!1))};
_.$JSCompiler_prototypeAlias$$.$AmpAudio$$module$extensions$amp_audio$0_1$amp_audio_prototype$play_$=function(){$JSCompiler_StaticMethods_isInvocationValid_$$(this)&&(this.$D$.play(),$JSCompiler_StaticMethods_setPlayingStateForTesting_$$(this,!0))};self.AMP.registerElement("amp-audio",$AmpAudio$$module$extensions$amp_audio$0_1$amp_audio$$);
})});

//# sourceMappingURL=amp-audio-0.1.js.map
