(self.AMP=self.AMP||[]).push({n:"amp-video-iframe",i:["_base_i","_base_media"],v:"1904281823091",f:(function(AMP,_){
var $disableScrollingOnIframe$$module$src$iframe_helper$$=function($iframe$jscomp$7$$){_.$addAttributesToElement$$module$src$dom$$($iframe$jscomp$7$$,_.$dict$$module$src$utils$object$$({scrolling:"no"}));_.$setStyle$$module$src$style$$($iframe$jscomp$7$$,"overflow","hidden");return $iframe$jscomp$7$$},$AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe$$=function($element$jscomp$751$$){var $$jscomp$super$this$jscomp$117$$=AMP.BaseElement.call(this,$element$jscomp$751$$)||this;
$$jscomp$super$this$jscomp$117$$.$D$=null;$$jscomp$super$this$jscomp$117$$.$G$=null;$$jscomp$super$this$jscomp$117$$.$H$=null;$$jscomp$super$this$jscomp$117$$.$F$=!1;$$jscomp$super$this$jscomp$117$$.$I$=function($element$jscomp$751$$){a:{if($$jscomp$super$this$jscomp$117$$.$D$&&_.$originMatches$$module$src$iframe_video$$($element$jscomp$751$$,$$jscomp$super$this$jscomp$117$$.$D$,/.*/)&&($element$jscomp$751$$=$element$jscomp$751$$.data,_.$isJsonOrObj$$module$src$iframe_video$$($element$jscomp$751$$))){$element$jscomp$751$$=
_.$objOrParseJson$$module$src$iframe_video$$($element$jscomp$751$$);var $$jscomp$inline_7003_JSCompiler_inline_result$jscomp$1117_data$jscomp$inline_5537_e$jscomp$329_eventData$jscomp$inline_5536_eventType$jscomp$inline_7007$$=$element$jscomp$751$$.id,$intersectionRatio$jscomp$inline_7004_isCanPlayEvent$jscomp$inline_5541_methodReceived$jscomp$inline_5539$$=$element$jscomp$751$$.method;if($intersectionRatio$jscomp$inline_7004_isCanPlayEvent$jscomp$inline_5541_methodReceived$jscomp$inline_5539$$)"getIntersection"==
$intersectionRatio$jscomp$inline_7004_isCanPlayEvent$jscomp$inline_5541_methodReceived$jscomp$inline_5539$$&&($element$jscomp$751$$=$$jscomp$super$this$jscomp$117$$.element.$getIntersectionChangeEntry$(),$intersectionRatio$jscomp$inline_7004_isCanPlayEvent$jscomp$inline_5541_methodReceived$jscomp$inline_5539$$=$element$jscomp$751$$.intersectionRatio,$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$postMessage_$$($$jscomp$super$this$jscomp$117$$,
_.$dict$$module$src$utils$object$$({id:$$jscomp$inline_7003_JSCompiler_inline_result$jscomp$1117_data$jscomp$inline_5537_e$jscomp$329_eventData$jscomp$inline_5536_eventType$jscomp$inline_7007$$,args:{intersectionRatio:.5>$intersectionRatio$jscomp$inline_7004_isCanPlayEvent$jscomp$inline_5541_methodReceived$jscomp$inline_5539$$?0:$intersectionRatio$jscomp$inline_7004_isCanPlayEvent$jscomp$inline_5541_methodReceived$jscomp$inline_5539$$,time:$element$jscomp$751$$.time}})));else{$$jscomp$inline_7003_JSCompiler_inline_result$jscomp$1117_data$jscomp$inline_5537_e$jscomp$329_eventData$jscomp$inline_5536_eventType$jscomp$inline_7007$$=
$element$jscomp$751$$.event;$intersectionRatio$jscomp$inline_7004_isCanPlayEvent$jscomp$inline_5541_methodReceived$jscomp$inline_5539$$="canplay"==$$jscomp$inline_7003_JSCompiler_inline_result$jscomp$1117_data$jscomp$inline_5537_e$jscomp$329_eventData$jscomp$inline_5536_eventType$jscomp$inline_7007$$;$$jscomp$super$this$jscomp$117$$.$F$=$$jscomp$super$this$jscomp$117$$.$F$||$intersectionRatio$jscomp$inline_7004_isCanPlayEvent$jscomp$inline_5541_methodReceived$jscomp$inline_5539$$;var $$jscomp$inline_5542_resolve$jscomp$inline_5544$$=
$$jscomp$super$this$jscomp$117$$.$H$,$reject$jscomp$inline_5543$$=$$jscomp$inline_5542_resolve$jscomp$inline_5544$$.reject;$$jscomp$inline_5542_resolve$jscomp$inline_5544$$=$$jscomp$inline_5542_resolve$jscomp$inline_5544$$.resolve;if($intersectionRatio$jscomp$inline_7004_isCanPlayEvent$jscomp$inline_5541_methodReceived$jscomp$inline_5539$$){$element$jscomp$751$$=$$jscomp$inline_5542_resolve$jscomp$inline_5544$$();break a}if("error"==$$jscomp$inline_7003_JSCompiler_inline_result$jscomp$1117_data$jscomp$inline_5537_e$jscomp$329_eventData$jscomp$inline_5536_eventType$jscomp$inline_7007$$&&
!$$jscomp$super$this$jscomp$117$$.$F$){$element$jscomp$751$$=$reject$jscomp$inline_5543$$("Received `error` event.");break a}"analytics"==$$jscomp$inline_7003_JSCompiler_inline_result$jscomp$1117_data$jscomp$inline_5537_e$jscomp$329_eventData$jscomp$inline_5536_eventType$jscomp$inline_7007$$?($$jscomp$inline_7003_JSCompiler_inline_result$jscomp$1117_data$jscomp$inline_5537_e$jscomp$329_eventData$jscomp$inline_5536_eventType$jscomp$inline_7007$$=$element$jscomp$751$$.analytics,$element$jscomp$751$$=
$$jscomp$inline_7003_JSCompiler_inline_result$jscomp$1117_data$jscomp$inline_5537_e$jscomp$329_eventData$jscomp$inline_5536_eventType$jscomp$inline_7007$$.eventType,$$jscomp$inline_7003_JSCompiler_inline_result$jscomp$1117_data$jscomp$inline_5537_e$jscomp$329_eventData$jscomp$inline_5536_eventType$jscomp$inline_7007$$=$$jscomp$inline_7003_JSCompiler_inline_result$jscomp$1117_data$jscomp$inline_5537_e$jscomp$329_eventData$jscomp$inline_5536_eventType$jscomp$inline_7007$$.vars,$$jscomp$inline_7003_JSCompiler_inline_result$jscomp$1117_data$jscomp$inline_5537_e$jscomp$329_eventData$jscomp$inline_5536_eventType$jscomp$inline_7007$$=
void 0===$$jscomp$inline_7003_JSCompiler_inline_result$jscomp$1117_data$jscomp$inline_5537_e$jscomp$329_eventData$jscomp$inline_5536_eventType$jscomp$inline_7007$$?{}:$$jscomp$inline_7003_JSCompiler_inline_result$jscomp$1117_data$jscomp$inline_5537_e$jscomp$329_eventData$jscomp$inline_5536_eventType$jscomp$inline_7007$$,_.$JSCompiler_StaticMethods_assertString$$(_.$user$$module$src$log$$(),$element$jscomp$751$$,"`eventType` missing in analytics event"),$$jscomp$super$this$jscomp$117$$.element.$dispatchCustomEvent$("video-hosted-custom",
{$eventType$:$element$jscomp$751$$,$vars$:$$jscomp$inline_7003_JSCompiler_inline_result$jscomp$1117_data$jscomp$inline_5537_e$jscomp$329_eventData$jscomp$inline_5536_eventType$jscomp$inline_7007$$})):-1<$ALLOWED_EVENTS$$module$extensions$amp_video_iframe$0_1$amp_video_iframe$$.indexOf($$jscomp$inline_7003_JSCompiler_inline_result$jscomp$1117_data$jscomp$inline_5537_e$jscomp$329_eventData$jscomp$inline_5536_eventType$jscomp$inline_7007$$)&&$$jscomp$super$this$jscomp$117$$.element.$dispatchCustomEvent$($$jscomp$inline_7003_JSCompiler_inline_result$jscomp$1117_data$jscomp$inline_5537_e$jscomp$329_eventData$jscomp$inline_5536_eventType$jscomp$inline_7007$$)}}$element$jscomp$751$$=
void 0}return $element$jscomp$751$$};return $$jscomp$super$this$jscomp$117$$},$JSCompiler_StaticMethods_getMetadata_$$=function($$jscomp$destructuring$var707_JSCompiler_StaticMethods_getMetadata_$self$$){$$jscomp$destructuring$var707_JSCompiler_StaticMethods_getMetadata_$self$$=_.$Services$$module$src$services$documentInfoForDoc$$($$jscomp$destructuring$var707_JSCompiler_StaticMethods_getMetadata_$self$$.element);return _.$dict$$module$src$utils$object$$({sourceUrl:$$jscomp$destructuring$var707_JSCompiler_StaticMethods_getMetadata_$self$$.sourceUrl,
canonicalUrl:$$jscomp$destructuring$var707_JSCompiler_StaticMethods_getMetadata_$self$$.canonicalUrl})},$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$getSrc_$$=function($JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$getSrc_$self$$){var $element$jscomp$755$$=$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$getSrc_$self$$.element,
$JSCompiler_inline_result$jscomp$575_urlService$jscomp$14$$=_.$Services$$module$src$services$urlForDoc$$($element$jscomp$755$$);var $JSCompiler_inline_result$jscomp$573$$=$element$jscomp$755$$.getAttribute("src");var $JSCompiler_temp_const$jscomp$574$$=_.$getSourceOrigin$$module$src$url$$($JSCompiler_inline_result$jscomp$573$$),$win$jscomp$inline_5563$$=$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$getSrc_$self$$.$win$;$JSCompiler_inline_result$jscomp$575_urlService$jscomp$14$$=
$win$jscomp$inline_5563$$.origin||$JSCompiler_inline_result$jscomp$575_urlService$jscomp$14$$.parse($win$jscomp$inline_5563$$.location.href).origin;$JSCompiler_temp_const$jscomp$574$$===$JSCompiler_inline_result$jscomp$575_urlService$jscomp$14$$&&$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$getSrc_$self$$.$user$().$Log$$module$src$log_prototype$warn$("amp-video-iframe","Origins of document inside amp-video-iframe and the host are the same, which allows for same-origin behavior. However in AMP cache, origins won't match. Please ensure you do not rely on any same-origin privileges.",
$element$jscomp$755$$);return-1<$JSCompiler_inline_result$jscomp$573$$.indexOf("#")?$JSCompiler_inline_result$jscomp$573$$:$JSCompiler_inline_result$jscomp$573$$+"#amp=1"},$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$method_$$=function($JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$method_$self$$,$method$jscomp$35$$){$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$postMessage_$$($JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$method_$self$$,
_.$dict$$module$src$utils$object$$({event:"method",method:$method$jscomp$35$$}))},$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$postMessage_$$=function($JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$postMessage_$self$$,$message$jscomp$77$$){if($JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$postMessage_$self$$.$D$&&$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$postMessage_$self$$.$D$.contentWindow){var $promise$jscomp$72$$=
$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$postMessage_$self$$.$H$.$promise$;$promise$jscomp$72$$&&$promise$jscomp$72$$.then(function(){$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$postMessage_$self$$.$D$.contentWindow.postMessage(JSON.stringify($message$jscomp$77$$),"*")})}},$_template$$module$extensions$amp_video_iframe$0_1$amp_video_iframe$$=["<amp-img layout=fill placeholder></amp-img>"],
$SANDBOX$$module$extensions$amp_video_iframe$0_1$amp_video_iframe$$=["allow-scripts","allow-same-origin","allow-popups","allow-popups-to-escape-sandbox","allow-top-navigation-by-user-activation"],$ALLOWED_EVENTS$$module$extensions$amp_video_iframe$0_1$amp_video_iframe$$=[_.$VideoEvents$$module$src$video_interface$$.$PLAYING$,_.$VideoEvents$$module$src$video_interface$$.$PAUSE$,_.$VideoEvents$$module$src$video_interface$$.$ENDED$,_.$VideoEvents$$module$src$video_interface$$.$MUTED$,_.$VideoEvents$$module$src$video_interface$$.$UNMUTED$,
_.$VideoEvents$$module$src$video_interface$$.$AD_START$,_.$VideoEvents$$module$src$video_interface$$.$AD_END$];_.$$jscomp$inherits$$($AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe$$.prototype;_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$116$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$116$$)};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){var $element$jscomp$752$$=this.element,$isIntegrationTest$$=$element$jscomp$752$$.hasAttribute("i-amphtml-integration-test");this.$user$().$Log$$module$src$log_prototype$assert$($isIntegrationTest$$||!_.$looksLikeTrackingIframe$$module$src$iframe_helper$$($element$jscomp$752$$),"<amp-video-iframe> does not allow tracking iframes. Please use amp-analytics instead.");_.$installVideoManagerForDoc$$module$src$service$video_manager_impl$$($element$jscomp$752$$)};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $$jscomp$this$jscomp$1389$$=this,$name$jscomp$280$$=JSON.stringify($JSCompiler_StaticMethods_getMetadata_$$(this));this.$D$=$disableScrollingOnIframe$$module$src$iframe_helper$$(_.$createFrameFor$$module$src$iframe_video$$(this,$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$getSrc_$$(this),$name$jscomp$280$$,$SANDBOX$$module$extensions$amp_video_iframe$0_1$amp_video_iframe$$));
this.$G$=_.$internalListenImplementation$$module$src$event_helper_listen$$(this.$win$,"message",this.$I$,void 0);this.$H$=new _.$Deferred$$module$src$utils$promise$$;return this.$H$.$promise$.then(function(){var $name$jscomp$280$$=$$jscomp$this$jscomp$1389$$.element;_.$Services$$module$src$services$videoManagerForDoc$$($name$jscomp$280$$).register($$jscomp$this$jscomp$1389$$);$name$jscomp$280$$.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$LOAD$)})};
_.$JSCompiler_prototypeAlias$$.$mutatedAttributesCallback$=function($iframe$jscomp$inline_5553_mutations$jscomp$26$$){$iframe$jscomp$inline_5553_mutations$jscomp$26$$.src&&($iframe$jscomp$inline_5553_mutations$jscomp$26$$=this.$D$)&&$iframe$jscomp$inline_5553_mutations$jscomp$26$$.src!=$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$getSrc_$$(this)&&($iframe$jscomp$inline_5553_mutations$jscomp$26$$.src=$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$getSrc_$$(this))};
_.$JSCompiler_prototypeAlias$$.$createPlaceholderCallback$=function(){var $element$jscomp$754$$=this.element,$poster$jscomp$7$$=_.$htmlFor$$module$src$static_template$$($element$jscomp$754$$)($_template$$module$extensions$amp_video_iframe$0_1$amp_video_iframe$$);$poster$jscomp$7$$.setAttribute("src",_.$JSCompiler_StaticMethods_assertString$$(this.$user$(),$element$jscomp$754$$.getAttribute("poster")));return $poster$jscomp$7$$};
_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$F$=this.$F$=!1;this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$D$=null);this.$G$&&(this.$G$(),this.$G$=null);return!0};_.$JSCompiler_prototypeAlias$$.$pauseCallback$=function(){this.pause()};_.$JSCompiler_prototypeAlias$$.pause=function(){$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$method_$$(this,"pause")};
_.$JSCompiler_prototypeAlias$$.play=function(){$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$method_$$(this,"play")};_.$JSCompiler_prototypeAlias$$.$mute$=function(){$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$method_$$(this,"mute")};
_.$JSCompiler_prototypeAlias$$.$unmute$=function(){$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$method_$$(this,"unmute")};_.$JSCompiler_prototypeAlias$$.$isInteractive$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$supportsPlatform$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$preimplementsMediaSessionAPI$=function(){return this.element.hasAttribute("implements-media-session")};
_.$JSCompiler_prototypeAlias$$.$preimplementsAutoFullscreen$=function(){return this.element.hasAttribute("implements-rotate-to-fullscreen")};_.$JSCompiler_prototypeAlias$$.$fullscreenEnter$=function(){$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$method_$$(this,"fullscreenenter")};
_.$JSCompiler_prototypeAlias$$.$fullscreenExit$=function(){$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$method_$$(this,"fullscreenexit")};_.$JSCompiler_prototypeAlias$$.$showControls$=function(){$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$method_$$(this,"showcontrols")};
_.$JSCompiler_prototypeAlias$$.$hideControls$=function(){$JSCompiler_StaticMethods_AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe_prototype$method_$$(this,"hidecontrols")};_.$JSCompiler_prototypeAlias$$.getMetadata=function(){};_.$JSCompiler_prototypeAlias$$.$getDuration$=function(){return 0};_.$JSCompiler_prototypeAlias$$.$getCurrentTime$=function(){return 0};_.$JSCompiler_prototypeAlias$$.$getPlayedRanges$=function(){return[]};
_.$JSCompiler_prototypeAlias$$.$seekTo$=function(){this.$user$().error("amp-video-iframe","`seekTo` not supported.")};self.AMP.registerElement("amp-video-iframe",$AmpVideoIframe$$module$extensions$amp_video_iframe$0_1$amp_video_iframe$$);
})});

//# sourceMappingURL=amp-video-iframe-0.1.js.map
