(self.AMP=self.AMP||[]).push({n:"amp-facebook-comments",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $AmpFacebookComments$$module$extensions$amp_facebook_comments$0_1$amp_facebook_comments$$=function($element$jscomp$435$$){var $$jscomp$super$this$jscomp$46$$=AMP.BaseElement.call(this,$element$jscomp$435$$)||this;$$jscomp$super$this$jscomp$46$$.$D$=null;$$jscomp$super$this$jscomp$46$$.$G$=$element$jscomp$435$$.hasAttribute("data-locale")?$element$jscomp$435$$.getAttribute("data-locale"):_.$dashToUnderline$$module$src$string$$();$$jscomp$super$this$jscomp$46$$.$F$=null;return $$jscomp$super$this$jscomp$46$$};
_.$$jscomp$inherits$$($AmpFacebookComments$$module$extensions$amp_facebook_comments$0_1$amp_facebook_comments$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpFacebookComments$$module$extensions$amp_facebook_comments$0_1$amp_facebook_comments$$.prototype;_.$JSCompiler_prototypeAlias$$.$renderOutsideViewport$=function(){return.75};
_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($opt_onLayout$jscomp$12$$){this.$preconnect$.url("https://facebook.com",$opt_onLayout$jscomp$12$$);this.$preconnect$.preload("https://connect.facebook.net/"+this.$G$+"/sdk.js","script");_.$preloadBootstrap$$module$src$3p_frame$$(this.$win$,this.$preconnect$)};_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$63$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$63$$)};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $$jscomp$this$jscomp$628$$=this,$iframe$jscomp$49$$=_.$getIframe$$module$src$3p_frame$$(this.$win$,this.element,"facebook");_.$JSCompiler_StaticMethods_applyFillContent$$($iframe$jscomp$49$$);_.$listenFor$$module$src$iframe_helper$$($iframe$jscomp$49$$,"embed-size",function($iframe$jscomp$49$$){_.$JSCompiler_StaticMethods_changeHeight$$($$jscomp$this$jscomp$628$$,$iframe$jscomp$49$$.height)},!0);this.$F$=_.$listen$$module$src$event_helper$$(this.$win$,
"message",this.$AmpFacebookComments$$module$extensions$amp_facebook_comments$0_1$amp_facebook_comments_prototype$handleFacebookMessages_$.bind(this));this.$toggleLoading$(!0);this.element.appendChild($iframe$jscomp$49$$);this.$D$=$iframe$jscomp$49$$;return this.$loadPromise$($iframe$jscomp$49$$)};
_.$JSCompiler_prototypeAlias$$.$AmpFacebookComments$$module$extensions$amp_facebook_comments$0_1$amp_facebook_comments_prototype$handleFacebookMessages_$=function($event$jscomp$122_eventData$jscomp$7$$){this.$D$&&$event$jscomp$122_eventData$jscomp$7$$.source!=this.$D$.contentWindow||($event$jscomp$122_eventData$jscomp$7$$=$event$jscomp$122_eventData$jscomp$7$$.data)&&(_.$isObject$$module$src$types$$($event$jscomp$122_eventData$jscomp$7$$)?$event$jscomp$122_eventData$jscomp$7$$:_.$tryParseJson$$module$src$json$$($event$jscomp$122_eventData$jscomp$7$$))&&
"ready"==$event$jscomp$122_eventData$jscomp$7$$.action&&this.$toggleLoading$(!1)};_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$D$=null);this.$F$&&this.$F$();return!0};self.AMP.registerElement("amp-facebook-comments",$AmpFacebookComments$$module$extensions$amp_facebook_comments$0_1$amp_facebook_comments$$);
})});

//# sourceMappingURL=amp-facebook-comments-0.1.js.map
