(self.AMP=self.AMP||[]).push({n:"amp-fit-text",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$=function($$jscomp$super$this$jscomp$50_element$jscomp$439$$){$$jscomp$super$this$jscomp$50_element$jscomp$439$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$50_element$jscomp$439$$)||this;$$jscomp$super$this$jscomp$50_element$jscomp$439$$.$F$=null;$$jscomp$super$this$jscomp$50_element$jscomp$439$$.$D$=null;$$jscomp$super$this$jscomp$50_element$jscomp$439$$.$G$=null;$$jscomp$super$this$jscomp$50_element$jscomp$439$$.$I$=-1;
$$jscomp$super$this$jscomp$50_element$jscomp$439$$.$H$=-1;return $$jscomp$super$this$jscomp$50_element$jscomp$439$$};_.$$jscomp$inherits$$($AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$.prototype;_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$67$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$67$$)};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){var $$jscomp$this$jscomp$632$$=this;this.$F$=this.element.ownerDocument.createElement("div");_.$JSCompiler_StaticMethods_applyFillContent$$(this.$F$);this.$F$.classList.add("i-amphtml-fit-text-content");_.$setStyles$$module$src$style$$(this.$F$,{zIndex:2});this.$D$=this.element.ownerDocument.createElement("div");_.$setStyles$$module$src$style$$(this.$D$,{lineHeight:"1.15em"});this.$F$.appendChild(this.$D$);this.$G$=this.element.ownerDocument.createElement("div");
_.$setStyles$$module$src$style$$(this.$G$,{position:"absolute",top:0,left:0,zIndex:1,visibility:"hidden",lineHeight:"1.15em"});this.$getRealChildNodes$().forEach(function($node$jscomp$78$$){$$jscomp$this$jscomp$632$$.$D$.appendChild($node$jscomp$78$$)});this.$G$.innerHTML=this.$D$.innerHTML;this.element.appendChild(this.$F$);this.element.appendChild(this.$G$);this.$I$=_.$getLengthNumeral$$module$src$layout$$(this.element.getAttribute("min-font-size"))||6;this.$H$=_.$getLengthNumeral$$module$src$layout$$(this.element.getAttribute("max-font-size"))||
72};_.$JSCompiler_prototypeAlias$$.$prerenderAllowed$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$isRelayoutNeeded$=function(){return!0};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $$jscomp$this$jscomp$633$$=this;return this.$mutateElement$(function(){var $maxHeight$jscomp$inline_3406_numberOfLines$jscomp$inline_6608$$=$$jscomp$this$jscomp$633$$.element.offsetHeight,$content$jscomp$inline_6602_measurer$jscomp$inline_6594$$=$$jscomp$this$jscomp$633$$.$G$,$expectedWidth$jscomp$inline_6596_measurer$jscomp$inline_6603_overflown$jscomp$inline_6606$$=$$jscomp$this$jscomp$633$$.element.offsetWidth;var $JSCompiler_inline_result$jscomp$5953_lineHeight$jscomp$inline_6607_minFontSize$jscomp$inline_6597$$=
$$jscomp$this$jscomp$633$$.$I$;var $maxFontSize$jscomp$inline_6598$$=$$jscomp$this$jscomp$633$$.$H$;for($maxFontSize$jscomp$inline_6598$$++;1<$maxFontSize$jscomp$inline_6598$$-$JSCompiler_inline_result$jscomp$5953_lineHeight$jscomp$inline_6607_minFontSize$jscomp$inline_6597$$;){var $mid$jscomp$inline_6599$$=Math.floor(($JSCompiler_inline_result$jscomp$5953_lineHeight$jscomp$inline_6607_minFontSize$jscomp$inline_6597$$+$maxFontSize$jscomp$inline_6598$$)/2);_.$setStyle$$module$src$style$$($content$jscomp$inline_6602_measurer$jscomp$inline_6594$$,
"fontSize",_.$px$$module$src$style$$($mid$jscomp$inline_6599$$));var $width$jscomp$inline_6600$$=$content$jscomp$inline_6602_measurer$jscomp$inline_6594$$.offsetWidth;$content$jscomp$inline_6602_measurer$jscomp$inline_6594$$.offsetHeight>$maxHeight$jscomp$inline_3406_numberOfLines$jscomp$inline_6608$$||$width$jscomp$inline_6600$$>$expectedWidth$jscomp$inline_6596_measurer$jscomp$inline_6603_overflown$jscomp$inline_6606$$?$maxFontSize$jscomp$inline_6598$$=$mid$jscomp$inline_6599$$:$JSCompiler_inline_result$jscomp$5953_lineHeight$jscomp$inline_6607_minFontSize$jscomp$inline_6597$$=
$mid$jscomp$inline_6599$$}_.$setStyle$$module$src$style$$($$jscomp$this$jscomp$633$$.$D$,"fontSize",_.$px$$module$src$style$$($JSCompiler_inline_result$jscomp$5953_lineHeight$jscomp$inline_6607_minFontSize$jscomp$inline_6597$$));$content$jscomp$inline_6602_measurer$jscomp$inline_6594$$=$$jscomp$this$jscomp$633$$.$D$;$expectedWidth$jscomp$inline_6596_measurer$jscomp$inline_6603_overflown$jscomp$inline_6606$$=$$jscomp$this$jscomp$633$$.$G$;_.$setStyle$$module$src$style$$($expectedWidth$jscomp$inline_6596_measurer$jscomp$inline_6603_overflown$jscomp$inline_6606$$,
"fontSize",_.$px$$module$src$style$$($JSCompiler_inline_result$jscomp$5953_lineHeight$jscomp$inline_6607_minFontSize$jscomp$inline_6597$$));$expectedWidth$jscomp$inline_6596_measurer$jscomp$inline_6603_overflown$jscomp$inline_6606$$=$expectedWidth$jscomp$inline_6596_measurer$jscomp$inline_6603_overflown$jscomp$inline_6606$$.offsetHeight>$maxHeight$jscomp$inline_3406_numberOfLines$jscomp$inline_6608$$;$JSCompiler_inline_result$jscomp$5953_lineHeight$jscomp$inline_6607_minFontSize$jscomp$inline_6597$$*=
1.15;$maxHeight$jscomp$inline_3406_numberOfLines$jscomp$inline_6608$$=Math.floor($maxHeight$jscomp$inline_3406_numberOfLines$jscomp$inline_6608$$/$JSCompiler_inline_result$jscomp$5953_lineHeight$jscomp$inline_6607_minFontSize$jscomp$inline_6597$$);$content$jscomp$inline_6602_measurer$jscomp$inline_6594$$.classList.toggle("i-amphtml-fit-text-content-overflown",$expectedWidth$jscomp$inline_6596_measurer$jscomp$inline_6603_overflown$jscomp$inline_6606$$);_.$setStyles$$module$src$style$$($content$jscomp$inline_6602_measurer$jscomp$inline_6594$$,
{$lineClamp$:$expectedWidth$jscomp$inline_6596_measurer$jscomp$inline_6603_overflown$jscomp$inline_6606$$?$maxHeight$jscomp$inline_3406_numberOfLines$jscomp$inline_6608$$:"",maxHeight:$expectedWidth$jscomp$inline_6596_measurer$jscomp$inline_6603_overflown$jscomp$inline_6606$$?_.$px$$module$src$style$$($JSCompiler_inline_result$jscomp$5953_lineHeight$jscomp$inline_6607_minFontSize$jscomp$inline_6597$$*$maxHeight$jscomp$inline_3406_numberOfLines$jscomp$inline_6608$$):""})})};
self.AMP.registerElement("amp-fit-text",$AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$,".i-amphtml-fit-text-content,.i-amphtml-fit-text-content.i-amphtml-fill-content{display:block;display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-ms-flex-direction:column;flex-direction:column;-ms-flex-wrap:nowrap;flex-wrap:nowrap;-webkit-box-pack:center;-ms-flex-pack:center;justify-content:center}.i-amphtml-fit-text-content-overflown{display:block;display:-webkit-box;-webkit-box-orient:vertical;overflow:hidden}\n/*# sourceURL=/extensions/amp-fit-text/0.1/amp-fit-text.css*/");
})});

//# sourceMappingURL=amp-fit-text-0.1.js.map
