(self.AMP=self.AMP||[]).push({n:"amp-delight-player",i:["_base_i","_base_media"],v:"1904281823091",f:(function(AMP,_){
var $AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player$$=function($$jscomp$super$this$jscomp$44_element$jscomp$428$$){$$jscomp$super$this$jscomp$44_element$jscomp$428$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$44_element$jscomp$428$$)||this;$$jscomp$super$this$jscomp$44_element$jscomp$428$$.$J$="https://players.delight-vr.com";$$jscomp$super$this$jscomp$44_element$jscomp$428$$.$K$="";$$jscomp$super$this$jscomp$44_element$jscomp$428$$.$W$=1;$$jscomp$super$this$jscomp$44_element$jscomp$428$$.$R$=
0;$$jscomp$super$this$jscomp$44_element$jscomp$428$$.$V$=[];$$jscomp$super$this$jscomp$44_element$jscomp$428$$.$S$=!1;$$jscomp$super$this$jscomp$44_element$jscomp$428$$.$D$=null;$$jscomp$super$this$jscomp$44_element$jscomp$428$$.$G$=null;$$jscomp$super$this$jscomp$44_element$jscomp$428$$.$H$=null;$$jscomp$super$this$jscomp$44_element$jscomp$428$$.$I$=null;$$jscomp$super$this$jscomp$44_element$jscomp$428$$.$P$=null;$$jscomp$super$this$jscomp$44_element$jscomp$428$$.$F$=null;$$jscomp$super$this$jscomp$44_element$jscomp$428$$.$O$=
null;$$jscomp$super$this$jscomp$44_element$jscomp$428$$.$M$=null;$$jscomp$super$this$jscomp$44_element$jscomp$428$$.$U$=null;return $$jscomp$super$this$jscomp$44_element$jscomp$428$$},$JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$$=function($JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$self$$,$type$jscomp$201$$,$payload$jscomp$18$$){$payload$jscomp$18$$=
void 0===$payload$jscomp$18$$?{}:$payload$jscomp$18$$;$JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$self$$.$G$.then(function($JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$self$$){$JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$self$$&&$JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$self$$.contentWindow&&
$JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$self$$.contentWindow.postMessage(JSON.stringify({type:$type$jscomp$201$$,$payload$:$payload$jscomp$18$$}),"*")})},$JSCompiler_StaticMethods_registerEventHandlers_$$=function($JSCompiler_StaticMethods_registerEventHandlers_$self$$){function $dispatchOrientationChangeEvents$$(){$JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$$($JSCompiler_StaticMethods_registerEventHandlers_$self$$,
"x-dl8-iframe-window-orientationchange",{orientation:window.orientation})}function $dispatchScreenOrientationChangeEvents$$(){var $dispatchOrientationChangeEvents$$=window.screen.orientation||window.screen.$G$||window.screen.$I$;$JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$$($JSCompiler_StaticMethods_registerEventHandlers_$self$$,"x-dl8-iframe-screen-change",{orientation:{angle:$dispatchOrientationChangeEvents$$.angle,
type:$dispatchOrientationChangeEvents$$.type}})}if(window.screen){var $screen$282$$=window.screen.orientation||window.screen.$G$||window.screen.$I$;$screen$282$$&&$screen$282$$.addEventListener?$JSCompiler_StaticMethods_registerEventHandlers_$self$$.$P$=_.$internalListenImplementation$$module$src$event_helper_listen$$($screen$282$$,"change",$dispatchScreenOrientationChangeEvents$$,void 0):$JSCompiler_StaticMethods_registerEventHandlers_$self$$.$F$=_.$internalListenImplementation$$module$src$event_helper_listen$$($JSCompiler_StaticMethods_registerEventHandlers_$self$$.$win$,
"orientationchange",$dispatchOrientationChangeEvents$$,void 0)}else $JSCompiler_StaticMethods_registerEventHandlers_$self$$.$F$=_.$internalListenImplementation$$module$src$event_helper_listen$$($JSCompiler_StaticMethods_registerEventHandlers_$self$$.$win$,"orientationchange",$dispatchOrientationChangeEvents$$,void 0);$JSCompiler_StaticMethods_registerEventHandlers_$self$$.$O$=_.$listen$$module$src$event_helper$$($JSCompiler_StaticMethods_registerEventHandlers_$self$$.$win$,"deviceorientation",function($dispatchOrientationChangeEvents$$){$JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$$($JSCompiler_StaticMethods_registerEventHandlers_$self$$,
"x-dl8-iframe-window-deviceorientation",{alpha:$dispatchOrientationChangeEvents$$.alpha,beta:$dispatchOrientationChangeEvents$$.beta,gamma:$dispatchOrientationChangeEvents$$.gamma,absolute:$dispatchOrientationChangeEvents$$.absolute,timeStamp:$dispatchOrientationChangeEvents$$.timeStamp})});$JSCompiler_StaticMethods_registerEventHandlers_$self$$.$M$=_.$listen$$module$src$event_helper$$($JSCompiler_StaticMethods_registerEventHandlers_$self$$.$win$,"devicemotion",function($dispatchOrientationChangeEvents$$){$JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$$($JSCompiler_StaticMethods_registerEventHandlers_$self$$,
"x-dl8-iframe-window-devicemotion",{acceleration:{x:$dispatchOrientationChangeEvents$$.acceleration.x,y:$dispatchOrientationChangeEvents$$.acceleration.y,z:$dispatchOrientationChangeEvents$$.acceleration.z},accelerationIncludingGravity:{x:$dispatchOrientationChangeEvents$$.accelerationIncludingGravity.x,y:$dispatchOrientationChangeEvents$$.accelerationIncludingGravity.y,z:$dispatchOrientationChangeEvents$$.accelerationIncludingGravity.z},rotationRate:{alpha:$dispatchOrientationChangeEvents$$.rotationRate.alpha,
beta:$dispatchOrientationChangeEvents$$.rotationRate.beta,gamma:$dispatchOrientationChangeEvents$$.rotationRate.gamma},interval:$dispatchOrientationChangeEvents$$.interval,timeStamp:$dispatchOrientationChangeEvents$$.timeStamp})})};var $_template$$module$extensions$amp_delight_player$0_1$amp_delight_player$$=["<div placeholder><amp-img layout=fill></amp-img></div>"];_.$$jscomp$inherits$$($AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player$$.prototype;_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($onLayout$jscomp$4$$){this.$preconnect$.url(this.$J$,$onLayout$jscomp$4$$)};
_.$JSCompiler_prototypeAlias$$.$renderOutsideViewport$=function(){return!1};_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){this.$K$=this.element.getAttribute("data-content-id");var $deferred$jscomp$42$$=new _.$Deferred$$module$src$utils$promise$$;this.$G$=$deferred$jscomp$42$$.$promise$;this.$H$=$deferred$jscomp$42$$.resolve;_.$installVideoManagerForDoc$$module$src$service$video_manager_impl$$(this.element);_.$Services$$module$src$services$videoManagerForDoc$$(this.element).register(this)};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $$jscomp$this$jscomp$617$$=this,$iframe$jscomp$46$$=_.$createFrameFor$$module$src$iframe_video$$(this,this.$J$+"/player/"+this.$K$+"?amp=1");$iframe$jscomp$46$$.setAttribute("allow","vr");this.$I$=_.$listen$$module$src$event_helper$$(this.$win$,"message",function($iframe$jscomp$46$$){if($iframe$jscomp$46$$.source===$$jscomp$this$jscomp$617$$.$D$.contentWindow&&($iframe$jscomp$46$$=_.$objOrParseJson$$module$src$iframe_video$$($iframe$jscomp$46$$.data),
void 0!==$iframe$jscomp$46$$&&void 0!==$iframe$jscomp$46$$.type)){var $data$jscomp$inline_3372_event$jscomp$118_guid$jscomp$inline_3374_payload$jscomp$inline_3375$$=$$jscomp$this$jscomp$617$$.element;switch($iframe$jscomp$46$$.type){case "x-dl8-ping":($iframe$jscomp$46$$=$iframe$jscomp$46$$.guid)&&$$jscomp$this$jscomp$617$$.$D$.contentWindow.postMessage(JSON.stringify({type:"x-dl8-pong",$guid$:$iframe$jscomp$46$$,$idx$:0}),"*");break;case "x-dl8-to-parent-ready":$data$jscomp$inline_3372_event$jscomp$118_guid$jscomp$inline_3374_payload$jscomp$inline_3375$$.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$LOAD$);
$$jscomp$this$jscomp$617$$.$H$($$jscomp$this$jscomp$617$$.$D$);break;case "x-dl8-to-parent-playing":$data$jscomp$inline_3372_event$jscomp$118_guid$jscomp$inline_3374_payload$jscomp$inline_3375$$.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$PLAYING$);break;case "x-dl8-to-parent-paused":$data$jscomp$inline_3372_event$jscomp$118_guid$jscomp$inline_3374_payload$jscomp$inline_3375$$.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$PAUSE$);break;case "x-dl8-to-parent-ended":$data$jscomp$inline_3372_event$jscomp$118_guid$jscomp$inline_3374_payload$jscomp$inline_3375$$.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$ENDED$);
break;case "x-dl8-to-parent-timeupdate":$iframe$jscomp$46$$=$iframe$jscomp$46$$.payload;$$jscomp$this$jscomp$617$$.$R$=$iframe$jscomp$46$$.currentTime;$$jscomp$this$jscomp$617$$.$V$=$iframe$jscomp$46$$.$playedRanges$;break;case "x-dl8-to-parent-muted":$data$jscomp$inline_3372_event$jscomp$118_guid$jscomp$inline_3374_payload$jscomp$inline_3375$$.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$MUTED$);break;case "x-dl8-to-parent-unmuted":$data$jscomp$inline_3372_event$jscomp$118_guid$jscomp$inline_3374_payload$jscomp$inline_3375$$.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$UNMUTED$);
break;case "x-dl8-to-parent-duration":$$jscomp$this$jscomp$617$$.$W$=$iframe$jscomp$46$$.payload.duration;break;case "x-dl8-iframe-enter-fullscreen":_.$setStyle$$module$src$style$$($$jscomp$this$jscomp$617$$.$D$,"position","fixed");break;case "x-dl8-iframe-exit-fullscreen":_.$setStyle$$module$src$style$$($$jscomp$this$jscomp$617$$.$D$,"position","absolute");break;case "x-dl8-to-parent-entered-fullscreen":$$jscomp$this$jscomp$617$$.$S$=!0;break;case "x-dl8-to-parent-exited-fullscreen":$$jscomp$this$jscomp$617$$.$S$=
!1}}});this.$D$=$iframe$jscomp$46$$;$JSCompiler_StaticMethods_registerEventHandlers_$$(this);return this.$loadPromise$($iframe$jscomp$46$$)};
_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){if(this.element.hasAttribute("dock"))return!1;this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$D$=null);this.$I$&&this.$I$();var $deferred$jscomp$43$$=new _.$Deferred$$module$src$utils$promise$$;this.$G$=$deferred$jscomp$43$$.$promise$;this.$H$=$deferred$jscomp$43$$.resolve;this.$P$&&this.$P$();this.$F$&&this.$F$();this.$O$&&this.$O$();this.$M$&&this.$M$();return!0};_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$58$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$58$$)};
_.$JSCompiler_prototypeAlias$$.$createPlaceholderCallback$=function(){var $placeholder$jscomp$12$$=_.$htmlFor$$module$src$static_template$$(this.element)($_template$$module$extensions$amp_delight_player$0_1$amp_delight_player$$);$placeholder$jscomp$12$$.firstElementChild.setAttribute("src",this.$J$+"/poster/"+this.$K$);return this.$U$=$placeholder$jscomp$12$$};
_.$JSCompiler_prototypeAlias$$.$firstLayoutCompleted$=function(){var $$jscomp$this$jscomp$618$$=this,$el$jscomp$73$$=this.$U$,$promise$jscomp$43$$=null;$el$jscomp$73$$&&this.$isInViewport$()?($el$jscomp$73$$.classList.add("i-amphtml-delight-player-faded"),$promise$jscomp$43$$=_.$listenOncePromise$$module$src$event_helper$$($el$jscomp$73$$,"transitionend")):$promise$jscomp$43$$=Promise.resolve();return $promise$jscomp$43$$.then(function(){return AMP.BaseElement.prototype.$firstLayoutCompleted$.call($$jscomp$this$jscomp$618$$)})};
_.$JSCompiler_prototypeAlias$$.$pauseCallback$=function(){this.$D$&&this.$D$.contentWindow&&this.pause()};_.$JSCompiler_prototypeAlias$$.$resumeCallback$=function(){this.$D$&&this.$D$.contentWindow&&this.play(!1)};_.$JSCompiler_prototypeAlias$$.$supportsPlatform$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$isInteractive$=function(){return!0};
_.$JSCompiler_prototypeAlias$$.play=function(){$JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$$(this,"x-dl8-to-iframe-play")};_.$JSCompiler_prototypeAlias$$.pause=function(){$JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$$(this,"x-dl8-to-iframe-pause")};
_.$JSCompiler_prototypeAlias$$.$mute$=function(){$JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$$(this,"x-dl8-to-iframe-mute")};_.$JSCompiler_prototypeAlias$$.$unmute$=function(){$JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$$(this,"x-dl8-to-iframe-unmute")};
_.$JSCompiler_prototypeAlias$$.$showControls$=function(){$JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$$(this,"x-dl8-to-iframe-enable-interface")};_.$JSCompiler_prototypeAlias$$.$hideControls$=function(){$JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$$(this,"x-dl8-to-iframe-disable-interface")};
_.$JSCompiler_prototypeAlias$$.$fullscreenEnter$=function(){$JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$$(this,"x-dl8-to-iframe-enter-fullscreen")};_.$JSCompiler_prototypeAlias$$.$fullscreenExit$=function(){$JSCompiler_StaticMethods_AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player_prototype$sendCommand_$$(this,"x-dl8-to-iframe-exit-fullscreen")};
_.$JSCompiler_prototypeAlias$$.getMetadata=function(){};_.$JSCompiler_prototypeAlias$$.$preimplementsMediaSessionAPI$=function(){return!1};_.$JSCompiler_prototypeAlias$$.$preimplementsAutoFullscreen$=function(){return!1};_.$JSCompiler_prototypeAlias$$.$getCurrentTime$=function(){return this.$R$};_.$JSCompiler_prototypeAlias$$.$getDuration$=function(){return this.$W$};_.$JSCompiler_prototypeAlias$$.$getPlayedRanges$=function(){return this.$V$};
_.$JSCompiler_prototypeAlias$$.$seekTo$=function(){this.$user$().error("amp-delight-player","`seekTo` not supported.")};self.AMP.registerElement("amp-delight-player",$AmpDelightPlayer$$module$extensions$amp_delight_player$0_1$amp_delight_player$$,"amp-delight-player [placeholder]{-webkit-transition:opacity 0.5s ease-out;transition:opacity 0.5s ease-out;background:no-repeat 50%;background-size:cover;width:100%;height:100%}amp-delight-player [placeholder].i-amphtml-delight-player-faded{opacity:0;pointer-events:none}\n/*# sourceURL=/extensions/amp-delight-player/0.1/amp-delight-player.css*/");
})});

//# sourceMappingURL=amp-delight-player-0.1.js.map
