(self.AMP=self.AMP||[]).push({n:"amp-font",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $JSCompiler_StaticMethods_createTask$$=function($JSCompiler_StaticMethods_createTask$self$$,$task$jscomp$19$$){return function($opt_state$jscomp$2$$){_.$JSCompiler_StaticMethods_Vsync$$module$src$service$vsync_impl_prototype$run$$($JSCompiler_StaticMethods_createTask$self$$,$task$jscomp$19$$,$opt_state$jscomp$2$$)}},$FontLoader$$module$extensions$amp_font$0_1$fontloader$$=function($ampdoc$jscomp$188$$){this.$ampdoc_$=$ampdoc$jscomp$188$$;this.$G$=$ampdoc$jscomp$188$$.$win$.document;this.$D$=this.$F$=
null;this.$H$=this.$I$=!1},$JSCompiler_StaticMethods_load_$$=function($JSCompiler_StaticMethods_load_$self$$){return new Promise(function($resolve$jscomp$65$$,$reject$jscomp$25$$){var $fontString$$=$JSCompiler_StaticMethods_load_$self$$.$D$.fontStyle+" "+$JSCompiler_StaticMethods_load_$self$$.$D$.variant+" "+$JSCompiler_StaticMethods_load_$self$$.$D$.weight+" "+$JSCompiler_StaticMethods_load_$self$$.$D$.size+" '"+$JSCompiler_StaticMethods_load_$self$$.$D$.family+"'";"fonts"in $JSCompiler_StaticMethods_load_$self$$.$G$?
$JSCompiler_StaticMethods_load_$self$$.$G$.fonts.check($fontString$$)?$resolve$jscomp$65$$():$JSCompiler_StaticMethods_load_$self$$.$G$.fonts.load($fontString$$).then(function(){return $JSCompiler_StaticMethods_load_$self$$.$G$.fonts.load($fontString$$)}).then(function(){$JSCompiler_StaticMethods_load_$self$$.$G$.fonts.check($fontString$$)?$resolve$jscomp$65$$():$reject$jscomp$25$$(Error("Font could not be loaded, probably due to incorrect @font-face."))}).catch($reject$jscomp$25$$):$JSCompiler_StaticMethods_loadWithPolyfill_$$($JSCompiler_StaticMethods_load_$self$$).then($resolve$jscomp$65$$,
$reject$jscomp$25$$)})},$JSCompiler_StaticMethods_loadWithPolyfill_$$=function($JSCompiler_StaticMethods_loadWithPolyfill_$self$$){return new Promise(function($resolve$jscomp$66$$,$reject$jscomp$26$$){var $vsync$jscomp$6$$=_.$Services$$module$src$services$vsyncFor$$($JSCompiler_StaticMethods_loadWithPolyfill_$self$$.$ampdoc_$.$win$),$comparators$$=$JSCompiler_StaticMethods_createFontComparators_$$($JSCompiler_StaticMethods_loadWithPolyfill_$self$$),$vsyncTask$$=$JSCompiler_StaticMethods_createTask$$($vsync$jscomp$6$$,
{measure:function(){$JSCompiler_StaticMethods_loadWithPolyfill_$self$$.$I$?$resolve$jscomp$66$$():$JSCompiler_StaticMethods_loadWithPolyfill_$self$$.$H$?$reject$jscomp$26$$(Error("Font loading timed out.")):$comparators$$.some(function($JSCompiler_StaticMethods_loadWithPolyfill_$self$$){var $resolve$jscomp$66$$=2<Math.abs($JSCompiler_StaticMethods_loadWithPolyfill_$self$$.$D$.offsetHeight-$JSCompiler_StaticMethods_loadWithPolyfill_$self$$.$F$.offsetHeight);return 2<Math.abs($JSCompiler_StaticMethods_loadWithPolyfill_$self$$.$D$.offsetWidth-
$JSCompiler_StaticMethods_loadWithPolyfill_$self$$.$F$.offsetWidth)||$resolve$jscomp$66$$})?$resolve$jscomp$66$$():$vsyncTask$$()}});$vsyncTask$$()})},$JSCompiler_StaticMethods_createFontComparators_$$=function($JSCompiler_StaticMethods_createFontComparators_$self$$){var $containerElement$$=$JSCompiler_StaticMethods_createFontComparators_$self$$.$F$=$JSCompiler_StaticMethods_createFontComparators_$self$$.$G$.createElement("div");_.$setStyles$$module$src$style$$($containerElement$$,{fontSize:"40px",
fontVariant:$JSCompiler_StaticMethods_createFontComparators_$self$$.$D$.variant,fontWeight:$JSCompiler_StaticMethods_createFontComparators_$self$$.$D$.weight,fontStyle:$JSCompiler_StaticMethods_createFontComparators_$self$$.$D$.fontStyle,left:"-999px",lineHeight:"normal",margin:0,padding:0,position:"absolute",top:"-999px",visibility:"hidden"});var $comparators$jscomp$1$$=$DEFAULT_FONTS_$$module$extensions$amp_font$0_1$fontloader$$.map(function($comparators$jscomp$1$$){return new $FontComparator$$module$extensions$amp_font$0_1$fontloader$$($containerElement$$,
$JSCompiler_StaticMethods_createFontComparators_$self$$.$D$.family,$comparators$jscomp$1$$)});$JSCompiler_StaticMethods_createFontComparators_$self$$.$ampdoc_$.$getBody$().appendChild($containerElement$$);return $comparators$jscomp$1$$},$FontComparator$$module$extensions$amp_font$0_1$fontloader$$=function($container$jscomp$15$$,$customFont_testFontFamily$$,$defaultFont$jscomp$1$$){var $doc$jscomp$89$$=$container$jscomp$15$$.ownerDocument;$customFont_testFontFamily$$=$customFont_testFontFamily$$+","+
$defaultFont$jscomp$1$$;this.$D$=$JSCompiler_StaticMethods_getFontElement_$$($doc$jscomp$89$$,$defaultFont$jscomp$1$$);this.$F$=$JSCompiler_StaticMethods_getFontElement_$$($doc$jscomp$89$$,$customFont_testFontFamily$$);$container$jscomp$15$$.appendChild(this.$D$);$container$jscomp$15$$.appendChild(this.$F$)},$JSCompiler_StaticMethods_getFontElement_$$=function($doc$jscomp$90_element$jscomp$440$$,$fontFamily$jscomp$1$$){$doc$jscomp$90_element$jscomp$440$$=$doc$jscomp$90_element$jscomp$440$$.createElement("div");
$doc$jscomp$90_element$jscomp$440$$.textContent="MAxmTYklsjo190QW";_.$setStyles$$module$src$style$$($doc$jscomp$90_element$jscomp$440$$,{$float$:"left",fontFamily:$fontFamily$jscomp$1$$,margin:0,padding:0,whiteSpace:"nowrap"});return $doc$jscomp$90_element$jscomp$440$$},$AmpFont$$module$extensions$amp_font$0_1$amp_font$$=function($$jscomp$super$this$jscomp$51_element$jscomp$441$$){$$jscomp$super$this$jscomp$51_element$jscomp$441$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$51_element$jscomp$441$$)||
this;$$jscomp$super$this$jscomp$51_element$jscomp$441$$.$D$="";$$jscomp$super$this$jscomp$51_element$jscomp$441$$.$I$="";$$jscomp$super$this$jscomp$51_element$jscomp$441$$.$G$="";$$jscomp$super$this$jscomp$51_element$jscomp$441$$.$H$="";$$jscomp$super$this$jscomp$51_element$jscomp$441$$.$F$=null;return $$jscomp$super$this$jscomp$51_element$jscomp$441$$},$JSCompiler_StaticMethods_startLoad_$$=function($JSCompiler_StaticMethods_startLoad_$self$$){$JSCompiler_StaticMethods_startLoad_$self$$.$F$.load({fontStyle:$JSCompiler_StaticMethods_startLoad_$self$$.$G$,
variant:$JSCompiler_StaticMethods_startLoad_$self$$.$H$,weight:$JSCompiler_StaticMethods_startLoad_$self$$.$I$,size:"medium",family:$JSCompiler_StaticMethods_startLoad_$self$$.$D$},$JSCompiler_StaticMethods_AmpFont$$module$extensions$amp_font$0_1$amp_font_prototype$getTimeout_$$($JSCompiler_StaticMethods_startLoad_$self$$)).then(function(){var $addClassName$jscomp$inline_3419$$=$JSCompiler_StaticMethods_startLoad_$self$$.element.getAttribute("on-load-add-class"),$removeClassName$jscomp$inline_3420$$=
$JSCompiler_StaticMethods_startLoad_$self$$.element.getAttribute("on-load-remove-class");$JSCompiler_StaticMethods_onFontLoadFinish_$$($JSCompiler_StaticMethods_startLoad_$self$$,$addClassName$jscomp$inline_3419$$,$removeClassName$jscomp$inline_3420$$)}).catch(function(){var $addClassName$jscomp$inline_3423$$=$JSCompiler_StaticMethods_startLoad_$self$$.element.getAttribute("on-error-add-class"),$removeClassName$jscomp$inline_3424$$=$JSCompiler_StaticMethods_startLoad_$self$$.element.getAttribute("on-error-remove-class");
$JSCompiler_StaticMethods_onFontLoadFinish_$$($JSCompiler_StaticMethods_startLoad_$self$$,$addClassName$jscomp$inline_3423$$,$removeClassName$jscomp$inline_3424$$);_.$user$$module$src$log$$().$Log$$module$src$log_prototype$warn$("amp-font","Font download timed out for "+$JSCompiler_StaticMethods_startLoad_$self$$.$D$)})},$JSCompiler_StaticMethods_onFontLoadFinish_$$=function($JSCompiler_StaticMethods_onFontLoadFinish_$self$$,$addClassName$jscomp$2$$,$removeClassName$jscomp$2$$){var $ampdoc$jscomp$189_root$jscomp$77$$=
$JSCompiler_StaticMethods_onFontLoadFinish_$self$$.$getAmpDoc$();$ampdoc$jscomp$189_root$jscomp$77$$=$ampdoc$jscomp$189_root$jscomp$77$$.getRootNode().documentElement||$ampdoc$jscomp$189_root$jscomp$77$$.$getBody$();$addClassName$jscomp$2$$&&$ampdoc$jscomp$189_root$jscomp$77$$.classList.add($addClassName$jscomp$2$$);$removeClassName$jscomp$2$$&&$ampdoc$jscomp$189_root$jscomp$77$$.classList.remove($removeClassName$jscomp$2$$);$JSCompiler_StaticMethods_onFontLoadFinish_$self$$.$F$=null},$JSCompiler_StaticMethods_AmpFont$$module$extensions$amp_font$0_1$amp_font_prototype$getTimeout_$$=
function($JSCompiler_StaticMethods_AmpFont$$module$extensions$amp_font$0_1$amp_font_prototype$getTimeout_$self$$){var $timeoutInMs$$=parseInt($JSCompiler_StaticMethods_AmpFont$$module$extensions$amp_font$0_1$amp_font_prototype$getTimeout_$self$$.element.getAttribute("timeout"),10);$timeoutInMs$$=!_.$isFiniteNumber$$module$src$types$$($timeoutInMs$$)||0>$timeoutInMs$$?3E3:$timeoutInMs$$;return $timeoutInMs$$=Math.max($timeoutInMs$$-(Date.now()-_.$Services$$module$src$services$timerFor$$($JSCompiler_StaticMethods_AmpFont$$module$extensions$amp_font$0_1$amp_font_prototype$getTimeout_$self$$.$win$).$F$),
100)},$DEFAULT_FONTS_$$module$extensions$amp_font$0_1$fontloader$$=["sans-serif","serif"];
$FontLoader$$module$extensions$amp_font$0_1$fontloader$$.prototype.load=function($fontConfig$$,$timeout$jscomp$15$$){var $$jscomp$this$jscomp$634$$=this;this.$D$=$fontConfig$$;return _.$JSCompiler_StaticMethods_timeoutPromise$$(_.$Services$$module$src$services$timerFor$$(this.$ampdoc_$.$win$),$timeout$jscomp$15$$,$JSCompiler_StaticMethods_load_$$(this)).then(function(){$$jscomp$this$jscomp$634$$.$I$=!0;$$jscomp$this$jscomp$634$$.$F$&&_.$removeElement$$module$src$dom$$($$jscomp$this$jscomp$634$$.$F$);
$$jscomp$this$jscomp$634$$.$F$=null},function($fontConfig$$){$$jscomp$this$jscomp$634$$.$H$=!0;$$jscomp$this$jscomp$634$$.$F$&&_.$removeElement$$module$src$dom$$($$jscomp$this$jscomp$634$$.$F$);$$jscomp$this$jscomp$634$$.$F$=null;throw $fontConfig$$;})};_.$$jscomp$inherits$$($AmpFont$$module$extensions$amp_font$0_1$amp_font$$,AMP.BaseElement);$AmpFont$$module$extensions$amp_font$0_1$amp_font$$.prototype.$prerenderAllowed$=function(){return!0};
$AmpFont$$module$extensions$amp_font$0_1$amp_font$$.prototype.$buildCallback$=function(){this.$D$=this.element.getAttribute("font-family");this.$I$=this.element.getAttribute("font-weight")||"400";this.$G$=this.element.getAttribute("font-style")||"normal";this.$H$=this.element.getAttribute("font-variant")||"normal";this.$F$=new $FontLoader$$module$extensions$amp_font$0_1$fontloader$$(this.$getAmpDoc$());$JSCompiler_StaticMethods_startLoad_$$(this)};self.AMP.registerElement("amp-font",$AmpFont$$module$extensions$amp_font$0_1$amp_font$$);
})});

//# sourceMappingURL=amp-font-0.1.js.map
