(self.AMP=self.AMP||[]).push({n:"amp-ad-network-adzerk-impl",i:["_base_i","_base_ad"],v:"1904281823091",f:(function(AMP,_){
var $AmpAdNetworkAdzerkImpl$$module$extensions$amp_ad_network_adzerk_impl$0_1$amp_ad_network_adzerk_impl$$=function($$jscomp$super$this$jscomp$11_element$jscomp$311$$){$$jscomp$super$this$jscomp$11_element$jscomp$311$$=_.$AmpA4A$$module$extensions$amp_a4a$0_1$amp_a4a$$.call(this,$$jscomp$super$this$jscomp$11_element$jscomp$311$$)||this;$$jscomp$super$this$jscomp$11_element$jscomp$311$$.$F$=null;$$jscomp$super$this$jscomp$11_element$jscomp$311$$.$D$=null;$ampAdTemplateHelper$$module$extensions$amp_ad_network_adzerk_impl$0_1$amp_ad_network_adzerk_impl$$=
$ampAdTemplateHelper$$module$extensions$amp_ad_network_adzerk_impl$0_1$amp_ad_network_adzerk_impl$$||new _.$AmpAdTemplateHelper$$module$extensions$amp_a4a$0_1$amp_ad_template_helper$$($$jscomp$super$this$jscomp$11_element$jscomp$311$$.$win$);return $$jscomp$super$this$jscomp$11_element$jscomp$311$$},$ampAdTemplateHelper$$module$extensions$amp_ad_network_adzerk_impl$0_1$amp_ad_network_adzerk_impl$$;
_.$$jscomp$inherits$$($AmpAdNetworkAdzerkImpl$$module$extensions$amp_ad_network_adzerk_impl$0_1$amp_ad_network_adzerk_impl$$,_.$AmpA4A$$module$extensions$amp_a4a$0_1$amp_a4a$$);_.$JSCompiler_prototypeAlias$$=$AmpAdNetworkAdzerkImpl$$module$extensions$amp_ad_network_adzerk_impl$0_1$amp_ad_network_adzerk_impl$$.prototype;_.$JSCompiler_prototypeAlias$$.isValidElement=function(){return!!this.$getAdUrl$()};_.$JSCompiler_prototypeAlias$$.$getSigningServiceNames$=function(){return[]};
_.$JSCompiler_prototypeAlias$$.$getAdUrl$=function(){var $data$jscomp$116$$=this.element.getAttribute("data-r");return _.$getMode$$module$src$mode$$(this.$win$).localDev?"http://ads.localhost:"+this.$win$.location.port+"/adzerk/"+$data$jscomp$116$$:"https://engine.adzerk.net/amp?r="+encodeURIComponent($data$jscomp$116$$)};
_.$JSCompiler_prototypeAlias$$.$maybeValidateAmpCreative$=function($bytes$jscomp$12$$,$headers$jscomp$7$$){var $$jscomp$this$jscomp$324$$=this;if("amp-mustache"!==$headers$jscomp$7$$.get("AMP-template-amp-creative"))return Promise.resolve(null);var $checkStillCurrent$jscomp$5$$=this.$verifyStillCurrent$();return _.$tryResolve$$module$src$utils$promise$$(function(){return _.$utf8Decode$$module$src$utils$bytes$$($bytes$jscomp$12$$)}).then(function($bytes$jscomp$12$$){$checkStillCurrent$jscomp$5$$();
$$jscomp$this$jscomp$324$$.$D$=_.$tryParseJson$$module$src$json$$($bytes$jscomp$12$$)||{};return $ampAdTemplateHelper$$module$extensions$amp_ad_network_adzerk_impl$0_1$amp_ad_network_adzerk_impl$$.fetch($$jscomp$this$jscomp$324$$.$D$.$templateUrl$).then(function($bytes$jscomp$12$$){$bytes$jscomp$12$$=$bytes$jscomp$12$$.replace(/<script async.+?<\/script>/g,"");$$jscomp$this$jscomp$324$$.$F$={$minifiedCreative$:$bytes$jscomp$12$$,$customElementExtensions$:[],$extensions$:[]};return _.$utf8Encode$$module$src$utils$bytes$$($bytes$jscomp$12$$)}).catch(function($bytes$jscomp$12$$){_.$dev$$module$src$log$$().$Log$$module$src$log_prototype$warn$("amp-ad-network-adzerk-impl",
"Error fetching/expanding template",$$jscomp$this$jscomp$324$$.$D$,$bytes$jscomp$12$$);_.$JSCompiler_StaticMethods_forceCollapse$$($$jscomp$this$jscomp$324$$);return Promise.reject("NO-CONTENT-RESPONSE")})})};
_.$JSCompiler_prototypeAlias$$.$getAmpAdMetadata$=function(){this.$F$||(this.$F$={});this.$F$.customElementExtensions||(this.$F$.customElementExtensions=[]);if(this.$D$.$analytics$){var $array$jscomp$inline_2357_array$jscomp$inline_2360$$=this.$F$.customElementExtensions;0>$array$jscomp$inline_2357_array$jscomp$inline_2360$$.indexOf("amp-analytics")&&$array$jscomp$inline_2357_array$jscomp$inline_2360$$.push("amp-analytics")}$array$jscomp$inline_2357_array$jscomp$inline_2360$$=this.$F$.customElementExtensions;
0>$array$jscomp$inline_2357_array$jscomp$inline_2360$$.indexOf("amp-mustache")&&$array$jscomp$inline_2357_array$jscomp$inline_2360$$.push("amp-mustache");return this.$F$};
_.$JSCompiler_prototypeAlias$$.$onCreativeRender$=function(){var $$jscomp$this$jscomp$325$$=this;this.$D$&&this.$D$.data&&$ampAdTemplateHelper$$module$extensions$amp_ad_network_adzerk_impl$0_1$amp_ad_network_adzerk_impl$$.render(this.$D$.data,this.iframe.contentWindow.document.body).then(function($renderedElement$jscomp$1$$){$$jscomp$this$jscomp$325$$.$D$.$analytics$&&_.$JSCompiler_StaticMethods_insertAnalytics$$($renderedElement$jscomp$1$$,$$jscomp$this$jscomp$325$$.$D$.$analytics$);$$jscomp$this$jscomp$325$$.iframe.contentWindow.document.body.innerHTML=
$renderedElement$jscomp$1$$.innerHTML})};self.AMP.registerElement("amp-ad-network-adzerk-impl",$AmpAdNetworkAdzerkImpl$$module$extensions$amp_ad_network_adzerk_impl$0_1$amp_ad_network_adzerk_impl$$);
})});

//# sourceMappingURL=amp-ad-network-adzerk-impl-0.1.js.map
