(self.AMP=self.AMP||[]).push({n:"amp-imgur",i:["_base_i","_base_media"],v:"1904281823091",f:(function(AMP,_){
var $AmpImgur$$module$extensions$amp_imgur$0_1$amp_imgur$$=function($$jscomp$super$this$jscomp$65_element$jscomp$506$$){$$jscomp$super$this$jscomp$65_element$jscomp$506$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$65_element$jscomp$506$$)||this;$$jscomp$super$this$jscomp$65_element$jscomp$506$$.$D$=null;$$jscomp$super$this$jscomp$65_element$jscomp$506$$.$F$=null;$$jscomp$super$this$jscomp$65_element$jscomp$506$$.$G$="";return $$jscomp$super$this$jscomp$65_element$jscomp$506$$};
_.$$jscomp$inherits$$($AmpImgur$$module$extensions$amp_imgur$0_1$amp_imgur$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpImgur$$module$extensions$amp_imgur$0_1$amp_imgur$$.prototype;_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$78$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$78$$)};_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){this.$G$=this.element.getAttribute("data-imgur-id")};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $iframe$jscomp$63$$=this.element.ownerDocument.createElement("iframe");this.$D$=$iframe$jscomp$63$$;this.$F$=_.$listen$$module$src$event_helper$$(this.$win$,"message",this.$handleImgurMessages_$.bind(this));$iframe$jscomp$63$$.setAttribute("scrolling","no");$iframe$jscomp$63$$.setAttribute("frameborder","0");$iframe$jscomp$63$$.setAttribute("allowfullscreen","true");$iframe$jscomp$63$$.src="https://imgur.com/"+encodeURIComponent(this.$G$)+
"/embed?pub=true";_.$JSCompiler_StaticMethods_applyFillContent$$($iframe$jscomp$63$$);this.element.appendChild($iframe$jscomp$63$$);return this.$loadPromise$($iframe$jscomp$63$$)};
_.$JSCompiler_prototypeAlias$$.$handleImgurMessages_$=function($data$jscomp$176_event$jscomp$147_eventData$jscomp$13$$){"https://imgur.com"==$data$jscomp$176_event$jscomp$147_eventData$jscomp$13$$.origin&&$data$jscomp$176_event$jscomp$147_eventData$jscomp$13$$.source==this.$D$.contentWindow&&($data$jscomp$176_event$jscomp$147_eventData$jscomp$13$$=$data$jscomp$176_event$jscomp$147_eventData$jscomp$13$$.data)&&(_.$isObject$$module$src$types$$($data$jscomp$176_event$jscomp$147_eventData$jscomp$13$$)||
_.$startsWith$$module$src$string$$($data$jscomp$176_event$jscomp$147_eventData$jscomp$13$$,"{"))&&($data$jscomp$176_event$jscomp$147_eventData$jscomp$13$$=_.$isObject$$module$src$types$$($data$jscomp$176_event$jscomp$147_eventData$jscomp$13$$)?$data$jscomp$176_event$jscomp$147_eventData$jscomp$13$$:_.$tryParseJson$$module$src$json$$($data$jscomp$176_event$jscomp$147_eventData$jscomp$13$$),"resize_imgur"==$data$jscomp$176_event$jscomp$147_eventData$jscomp$13$$.message&&_.$JSCompiler_StaticMethods_attemptChangeHeight$$(this,
$data$jscomp$176_event$jscomp$147_eventData$jscomp$13$$.height).catch(function(){}))};_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$D$=null);this.$F$&&this.$F$();return!0};self.AMP.registerElement("amp-imgur",$AmpImgur$$module$extensions$amp_imgur$0_1$amp_imgur$$);
})});

//# sourceMappingURL=amp-imgur-0.1.js.map
