(self.AMP=self.AMP||[]).push({n:"amp-3q-player",i:["_base_i","_base_media"],v:"1904281823091",f:(function(AMP,_){
var $Amp3QPlayer$$module$extensions$amp_3q_player$0_1$amp_3q_player$$=function($$jscomp$super$this$jscomp$4_element$jscomp$288$$){$$jscomp$super$this$jscomp$4_element$jscomp$288$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$4_element$jscomp$288$$)||this;$$jscomp$super$this$jscomp$4_element$jscomp$288$$.$D$=null;$$jscomp$super$this$jscomp$4_element$jscomp$288$$.$H$=null;$$jscomp$super$this$jscomp$4_element$jscomp$288$$.$F$=null;$$jscomp$super$this$jscomp$4_element$jscomp$288$$.$G$=null;$$jscomp$super$this$jscomp$4_element$jscomp$288$$.$I$=
null;return $$jscomp$super$this$jscomp$4_element$jscomp$288$$},$JSCompiler_StaticMethods_sdnPostMessage_$$=function($JSCompiler_StaticMethods_sdnPostMessage_$self$$,$message$jscomp$50$$){$JSCompiler_StaticMethods_sdnPostMessage_$self$$.$F$.then(function(){$JSCompiler_StaticMethods_sdnPostMessage_$self$$.$D$&&$JSCompiler_StaticMethods_sdnPostMessage_$self$$.$D$.contentWindow&&$JSCompiler_StaticMethods_sdnPostMessage_$self$$.$D$.contentWindow.postMessage($message$jscomp$50$$,"*")})};
_.$$jscomp$inherits$$($Amp3QPlayer$$module$extensions$amp_3q_player$0_1$amp_3q_player$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$Amp3QPlayer$$module$extensions$amp_3q_player$0_1$amp_3q_player$$.prototype;_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($opt_onLayout$jscomp$2$$){this.$preconnect$.url("https://playout.3qsdn.com",$opt_onLayout$jscomp$2$$)};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){var $el$jscomp$35$$=this.element;this.$I$=$el$jscomp$35$$.getAttribute("data-id");var $deferred$jscomp$25$$=new _.$Deferred$$module$src$utils$promise$$;this.$F$=$deferred$jscomp$25$$.$promise$;this.$G$=$deferred$jscomp$25$$.resolve;_.$installVideoManagerForDoc$$module$src$service$video_manager_impl$$($el$jscomp$35$$);_.$Services$$module$src$services$videoManagerForDoc$$($el$jscomp$35$$).register(this)};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $$jscomp$this$jscomp$249$$=this;this.$D$=_.$createFrameFor$$module$src$iframe_video$$(this,"https://playout.3qsdn.com/"+encodeURIComponent(this.$I$)+"?autoplay=false&amp=true");this.$H$=_.$listen$$module$src$event_helper$$(this.$win$,"message",this.$sdnBridge_$.bind(this));return this.$loadPromise$(this.$D$).then(function(){return $$jscomp$this$jscomp$249$$.$F$})};
_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$D$=null);this.$H$&&this.$H$();var $deferred$jscomp$26$$=new _.$Deferred$$module$src$utils$promise$$;this.$F$=$deferred$jscomp$26$$.$promise$;this.$G$=$deferred$jscomp$26$$.resolve;return!0};_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$32$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$32$$)};
_.$JSCompiler_prototypeAlias$$.$viewportCallback$=function($visible$jscomp$4$$){this.element.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$VISIBILITY$,{visible:$visible$jscomp$4$$})};_.$JSCompiler_prototypeAlias$$.$pauseCallback$=function(){this.$D$&&this.pause()};
_.$JSCompiler_prototypeAlias$$.$sdnBridge_$=function($data$jscomp$111_event$jscomp$58_eventType$jscomp$27$$){$data$jscomp$111_event$jscomp$58_eventType$jscomp$27$$.source&&$data$jscomp$111_event$jscomp$58_eventType$jscomp$27$$.source!=this.$D$.contentWindow||($data$jscomp$111_event$jscomp$58_eventType$jscomp$27$$=_.$objOrParseJson$$module$src$iframe_video$$($data$jscomp$111_event$jscomp$58_eventType$jscomp$27$$.data),void 0!==$data$jscomp$111_event$jscomp$58_eventType$jscomp$27$$&&($data$jscomp$111_event$jscomp$58_eventType$jscomp$27$$=
$data$jscomp$111_event$jscomp$58_eventType$jscomp$27$$.data,"ready"==$data$jscomp$111_event$jscomp$58_eventType$jscomp$27$$&&this.$G$(),_.$redispatch$$module$src$iframe_video$$(this.element,$data$jscomp$111_event$jscomp$58_eventType$jscomp$27$$,{ready:_.$VideoEvents$$module$src$video_interface$$.$LOAD$,playing:_.$VideoEvents$$module$src$video_interface$$.$PLAYING$,paused:_.$VideoEvents$$module$src$video_interface$$.$PAUSE$,muted:_.$VideoEvents$$module$src$video_interface$$.$MUTED$,unmuted:_.$VideoEvents$$module$src$video_interface$$.$UNMUTED$})))};
_.$JSCompiler_prototypeAlias$$.play=function(){$JSCompiler_StaticMethods_sdnPostMessage_$$(this,"play2")};_.$JSCompiler_prototypeAlias$$.pause=function(){$JSCompiler_StaticMethods_sdnPostMessage_$$(this,"pause")};_.$JSCompiler_prototypeAlias$$.$mute$=function(){$JSCompiler_StaticMethods_sdnPostMessage_$$(this,"mute")};_.$JSCompiler_prototypeAlias$$.$unmute$=function(){$JSCompiler_StaticMethods_sdnPostMessage_$$(this,"unmute")};_.$JSCompiler_prototypeAlias$$.$supportsPlatform$=function(){return!0};
_.$JSCompiler_prototypeAlias$$.$isInteractive$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$showControls$=function(){$JSCompiler_StaticMethods_sdnPostMessage_$$(this,"showControlbar")};_.$JSCompiler_prototypeAlias$$.$hideControls$=function(){$JSCompiler_StaticMethods_sdnPostMessage_$$(this,"hideControlbar")};_.$JSCompiler_prototypeAlias$$.$fullscreenEnter$=function(){this.$D$&&_.$fullscreenEnter$$module$src$dom$$(this.$D$)};
_.$JSCompiler_prototypeAlias$$.$fullscreenExit$=function(){this.$D$&&_.$fullscreenExit$$module$src$dom$$(this.$D$)};_.$JSCompiler_prototypeAlias$$.getMetadata=function(){};_.$JSCompiler_prototypeAlias$$.$preimplementsMediaSessionAPI$=function(){return!1};_.$JSCompiler_prototypeAlias$$.$preimplementsAutoFullscreen$=function(){return!1};_.$JSCompiler_prototypeAlias$$.$getCurrentTime$=function(){return 0};_.$JSCompiler_prototypeAlias$$.$getDuration$=function(){return 1};
_.$JSCompiler_prototypeAlias$$.$getPlayedRanges$=function(){return[]};_.$JSCompiler_prototypeAlias$$.$seekTo$=function(){this.$user$().error("amp-3q-player","`seekTo` not supported.")};self.AMP.registerElement("amp-3q-player",$Amp3QPlayer$$module$extensions$amp_3q_player$0_1$amp_3q_player$$);
})});

//# sourceMappingURL=amp-3q-player-0.1.js.map
