(self.AMP=self.AMP||[]).push({n:"amp-iframe",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe$$=function($$jscomp$super$this$jscomp$60_element$jscomp$492$$){$$jscomp$super$this$jscomp$60_element$jscomp$492$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$60_element$jscomp$492$$)||this;$$jscomp$super$this$jscomp$60_element$jscomp$492$$.$K$=null;$$jscomp$super$this$jscomp$60_element$jscomp$492$$.$M$=!1;$$jscomp$super$this$jscomp$60_element$jscomp$492$$.$P$=!1;$$jscomp$super$this$jscomp$60_element$jscomp$492$$.$I$=!1;$$jscomp$super$this$jscomp$60_element$jscomp$492$$.$U$=
!1;$$jscomp$super$this$jscomp$60_element$jscomp$492$$.$O$=null;$$jscomp$super$this$jscomp$60_element$jscomp$492$$.$D$=null;$$jscomp$super$this$jscomp$60_element$jscomp$492$$.$R$=!1;$$jscomp$super$this$jscomp$60_element$jscomp$492$$.$F$=null;$$jscomp$super$this$jscomp$60_element$jscomp$492$$.$S$="";$$jscomp$super$this$jscomp$60_element$jscomp$492$$.$G$=null;$$jscomp$super$this$jscomp$60_element$jscomp$492$$.$J$=null;$$jscomp$super$this$jscomp$60_element$jscomp$492$$.$H$=null;return $$jscomp$super$this$jscomp$60_element$jscomp$492$$},
$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$assertSource_$$=function($JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$assertSource_$self_urlService$jscomp$6$$,$src$jscomp$43$$){var $containerSrc$$=window.location.href;$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$assertSource_$self_urlService$jscomp$6$$=_.$Services$$module$src$services$urlForDoc$$($JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$assertSource_$self_urlService$jscomp$6$$.element);
$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$assertSource_$self_urlService$jscomp$6$$.parse($src$jscomp$43$$);$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$assertSource_$self_urlService$jscomp$6$$.parse($containerSrc$$);return $src$jscomp$43$$},$JSCompiler_StaticMethods_transformSrc_$$=function($$jscomp$destructuring$var492_JSCompiler_StaticMethods_transformSrc_$self$$,$src$jscomp$44$$){if($src$jscomp$44$$){$$jscomp$destructuring$var492_JSCompiler_StaticMethods_transformSrc_$self$$=
_.$Services$$module$src$services$urlForDoc$$($$jscomp$destructuring$var492_JSCompiler_StaticMethods_transformSrc_$self$$.element).parse($src$jscomp$44$$);var $hash$jscomp$17$$=$$jscomp$destructuring$var492_JSCompiler_StaticMethods_transformSrc_$self$$.hash;return"data:"==$$jscomp$destructuring$var492_JSCompiler_StaticMethods_transformSrc_$self$$.protocol||$hash$jscomp$17$$&&"#"!=$hash$jscomp$17$$?$src$jscomp$44$$:_.$removeFragment$$module$src$url$$($src$jscomp$44$$)+"#amp=1"}},$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$measureIframeLayoutBox_$$=
function($JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$measureIframeLayoutBox_$self$$){if($JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$measureIframeLayoutBox_$self$$.$D$){var $iframeBox$jscomp$5$$=$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$measureIframeLayoutBox_$self$$.$getViewport$().$getLayoutRect$($JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$measureIframeLayoutBox_$self$$.$D$),
$box$jscomp$17$$=$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$measureIframeLayoutBox_$self$$.$getLayoutBox$();$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$measureIframeLayoutBox_$self$$.$O$=_.$moveLayoutRect$$module$src$layout_rect$$($iframeBox$jscomp$5$$,-$box$jscomp$17$$.left,-$box$jscomp$17$$.top)}},$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$updateSize_$$=
function($JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$updateSize_$self$$,$height$jscomp$58$$,$width$jscomp$63$$){if($JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$updateSize_$self$$.$R$)if(100>$height$jscomp$58$$)$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$updateSize_$self$$.$user$().error("amp-iframe","Ignoring embed-size request because the resize height is less than 100px. If you are using amp-iframe to display ads, consider using amp-ad instead.",
$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$updateSize_$self$$.element);else{var $newHeight$jscomp$14$$,$newWidth$jscomp$11$$;$height$jscomp$58$$=parseInt($height$jscomp$58$$,10);isNaN($height$jscomp$58$$)||($newHeight$jscomp$14$$=Math.max($height$jscomp$58$$+($JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$updateSize_$self$$.element.offsetHeight-$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$updateSize_$self$$.$D$.offsetHeight),
$height$jscomp$58$$));$width$jscomp$63$$=parseInt($width$jscomp$63$$,10);isNaN($width$jscomp$63$$)||($newWidth$jscomp$11$$=Math.max($width$jscomp$63$$+($JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$updateSize_$self$$.element.offsetWidth-$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$updateSize_$self$$.$D$.offsetWidth),$width$jscomp$63$$));void 0!==$newHeight$jscomp$14$$||void 0!==$newWidth$jscomp$11$$?$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$updateSize_$self$$.$attemptChangeSize$($newHeight$jscomp$14$$,
$newWidth$jscomp$11$$).then(function(){void 0!==$newHeight$jscomp$14$$&&$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$updateSize_$self$$.element.setAttribute("height",$newHeight$jscomp$14$$);void 0!==$newWidth$jscomp$11$$&&$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$updateSize_$self$$.element.setAttribute("width",$newWidth$jscomp$11$$)},function(){}):$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$updateSize_$self$$.$user$().error("amp-iframe",
"Ignoring embed-size request because no width or height value is provided",$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$updateSize_$self$$.element)}else $JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$updateSize_$self$$.$user$().error("amp-iframe","Ignoring embed-size request because this iframe is not resizable",$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$updateSize_$self$$.element)},
$JSCompiler_StaticMethods_registerIframeMessaging_$$=function($JSCompiler_StaticMethods_registerIframeMessaging_$self$$){if(_.$isExperimentOn$$module$src$experiments$$($JSCompiler_StaticMethods_registerIframeMessaging_$self$$.$win$,"iframe-messaging")){var $element$jscomp$495$$=$JSCompiler_StaticMethods_registerIframeMessaging_$self$$.element,$src$jscomp$46$$=$element$jscomp$495$$.getAttribute("src");$src$jscomp$46$$&&($JSCompiler_StaticMethods_registerIframeMessaging_$self$$.$H$=_.$Services$$module$src$services$urlForDoc$$($element$jscomp$495$$).parse($src$jscomp$46$$).origin);
_.$JSCompiler_StaticMethods_registerAction$$($JSCompiler_StaticMethods_registerIframeMessaging_$self$$,"postMessage",function($element$jscomp$495$$){$JSCompiler_StaticMethods_registerIframeMessaging_$self$$.$H$?$JSCompiler_StaticMethods_registerIframeMessaging_$self$$.$D$.contentWindow.postMessage($element$jscomp$495$$.args,$JSCompiler_StaticMethods_registerIframeMessaging_$self$$.$H$):_.$user$$module$src$log$$().error("amp-iframe",'"postMessage" action is only allowed with "src"attribute with an origin.')},
100);if($JSCompiler_StaticMethods_registerIframeMessaging_$self$$.$H$){var $unexpectedMessages$$=0,$listener$jscomp$91$$=function($element$jscomp$495$$){if($element$jscomp$495$$.source===$JSCompiler_StaticMethods_registerIframeMessaging_$self$$.$D$.contentWindow)if($element$jscomp$495$$.origin!==$JSCompiler_StaticMethods_registerIframeMessaging_$self$$.$H$)_.$user$$module$src$log$$().error("amp-iframe",'"message" received from unexpected origin: '+$element$jscomp$495$$.origin+". Only allowed from: "+
$JSCompiler_StaticMethods_registerIframeMessaging_$self$$.$H$);else{if($JSCompiler_StaticMethods_registerIframeMessaging_$self$$.$getAmpDoc$().getRootNode().activeElement!==$JSCompiler_StaticMethods_registerIframeMessaging_$self$$.$D$)var $src$jscomp$46$$=!1;else $src$jscomp$46$$=$JSCompiler_StaticMethods_registerIframeMessaging_$self$$.$win$.document.createElement("audio"),$src$jscomp$46$$.play(),$src$jscomp$46$$=$src$jscomp$46$$.paused?!1:!0;if($src$jscomp$46$$){$element$jscomp$495$$=$element$jscomp$495$$.data;
try{var $e$jscomp$229_unsanitized$$=_.$parseJson$$module$src$json$$(JSON.stringify($element$jscomp$495$$))}catch($e$292$$){_.$user$$module$src$log$$().error("amp-iframe",'Data from "message" event must be JSON.');return}$e$jscomp$229_unsanitized$$=_.$createCustomEvent$$module$src$event_helper$$($JSCompiler_StaticMethods_registerIframeMessaging_$self$$.$win$,"amp-iframe:message",_.$dict$$module$src$utils$object$$({data:$e$jscomp$229_unsanitized$$}));_.$Services$$module$src$services$actionServiceForDoc$$($JSCompiler_StaticMethods_registerIframeMessaging_$self$$.element).$trigger$($JSCompiler_StaticMethods_registerIframeMessaging_$self$$.element,
"message",$e$jscomp$229_unsanitized$$,100)}else $unexpectedMessages$$++,_.$user$$module$src$log$$().error("amp-iframe",'"message" event may only be triggered from a user gesture.'),10<=$unexpectedMessages$$&&(_.$user$$module$src$log$$().error("amp-iframe",'Too many non-gesture-triggered "message" events; detaching event listener.'),$JSCompiler_StaticMethods_registerIframeMessaging_$self$$.$win$.removeEventListener("message",$listener$jscomp$91$$))}};$JSCompiler_StaticMethods_registerIframeMessaging_$self$$.$win$.addEventListener("message",
$listener$jscomp$91$$)}}},$adSizes$$module$src$iframe_helper$$=[[300,250],[320,50],[300,50],[320,100]],$ATTRIBUTES_TO_PROPAGATE$$module$extensions$amp_iframe$0_1$amp_iframe$$="allowfullscreen allowpaymentrequest allowtransparency allow frameborder referrerpolicy scrolling".split(" "),$count$$module$extensions$amp_iframe$0_1$amp_iframe$$=0,$trackingIframeCount$$module$extensions$amp_iframe$0_1$amp_iframe$$=0;_.$$jscomp$inherits$$($AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe$$,AMP.BaseElement);
_.$JSCompiler_prototypeAlias$$=$AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe$$.prototype;_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$74$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$74$$)};
_.$JSCompiler_prototypeAlias$$.$firstAttachedCallback$=function(){this.$S$=this.element.getAttribute("sandbox");var $JSCompiler_temp$jscomp$853_srcdoc$jscomp$inline_3606$$;($JSCompiler_temp$jscomp$853_srcdoc$jscomp$inline_3606$$=$JSCompiler_StaticMethods_transformSrc_$$(this,this.element.getAttribute("src")))||($JSCompiler_temp$jscomp$853_srcdoc$jscomp$inline_3606$$=($JSCompiler_temp$jscomp$853_srcdoc$jscomp$inline_3606$$=this.element.getAttribute("srcdoc"))?"data:text/html;charset=utf-8;base64,"+
btoa(_.$bytesToString$$module$src$utils$bytes$$(_.$utf8Encode$$module$src$utils$bytes$$($JSCompiler_temp$jscomp$853_srcdoc$jscomp$inline_3606$$))):void 0);this.$G$=$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$assertSource_$$(this,$JSCompiler_temp$jscomp$853_srcdoc$jscomp$inline_3606$$)};_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($onLayout$jscomp$5$$){this.$G$&&this.$preconnect$.url(this.$G$,$onLayout$jscomp$5$$)};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){this.$K$=this.$getPlaceholder$();this.$M$=!!this.$K$;(this.$R$=this.element.hasAttribute("resizable"))&&this.element.setAttribute("scrolling","no");this.element.hasAttribute("frameborder")||this.element.setAttribute("frameborder","0");var $JSCompiler_inline_result$jscomp$855_element$jscomp$inline_3608$$=this.element;if("no"!=$JSCompiler_inline_result$jscomp$855_element$jscomp$inline_3608$$.getAttribute("scrolling")){var $wrapper$jscomp$inline_3609$$=
$JSCompiler_inline_result$jscomp$855_element$jscomp$inline_3608$$.ownerDocument.createElement("i-amphtml-scroll-container");$JSCompiler_inline_result$jscomp$855_element$jscomp$inline_3608$$.appendChild($wrapper$jscomp$inline_3609$$);$JSCompiler_inline_result$jscomp$855_element$jscomp$inline_3608$$=$wrapper$jscomp$inline_3609$$}this.$J$=$JSCompiler_inline_result$jscomp$855_element$jscomp$inline_3608$$;$JSCompiler_StaticMethods_registerIframeMessaging_$$(this)};
_.$JSCompiler_prototypeAlias$$.$onLayoutMeasure$=function(){$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$measureIframeLayoutBox_$$(this);var $element$jscomp$494$$=this.element;a:{var $$jscomp$inline_3612_width$jscomp$inline_3614$$=$element$jscomp$494$$.$getLayoutBox$();var $JSCompiler_inline_result$jscomp$850_height$jscomp$inline_3613$$=$$jscomp$inline_3612_width$jscomp$inline_3614$$.height;$$jscomp$inline_3612_width$jscomp$inline_3614$$=$$jscomp$inline_3612_width$jscomp$inline_3614$$.width;
for(var $i$jscomp$inline_3615$$=0;$i$jscomp$inline_3615$$<$adSizes$$module$src$iframe_helper$$.length;$i$jscomp$inline_3615$$++){var $refWidth$jscomp$inline_3616$$=$adSizes$$module$src$iframe_helper$$[$i$jscomp$inline_3615$$][0],$refHeight$jscomp$inline_3617$$=$adSizes$$module$src$iframe_helper$$[$i$jscomp$inline_3615$$][1];if(!($refHeight$jscomp$inline_3617$$>$JSCompiler_inline_result$jscomp$850_height$jscomp$inline_3613$$||$refWidth$jscomp$inline_3616$$>$$jscomp$inline_3612_width$jscomp$inline_3614$$)&&
20>=$JSCompiler_inline_result$jscomp$850_height$jscomp$inline_3613$$-$refHeight$jscomp$inline_3617$$&&20>=$$jscomp$inline_3612_width$jscomp$inline_3614$$-$refWidth$jscomp$inline_3616$$){$JSCompiler_inline_result$jscomp$850_height$jscomp$inline_3613$$=!0;break a}}$JSCompiler_inline_result$jscomp$850_height$jscomp$inline_3613$$=!1}this.$P$=$JSCompiler_inline_result$jscomp$850_height$jscomp$inline_3613$$;this.$I$=_.$looksLikeTrackingIframe$$module$src$iframe_helper$$(this.element);this.$U$=this.$P$&&
!_.$isAdPositionAllowed$$module$src$ad_helper$$($element$jscomp$494$$,this.$win$);this.$F$&&this.$F$.$fire$()};
_.$JSCompiler_prototypeAlias$$.$getIntersectionElementLayoutBox$=function(){if(!this.$D$)return AMP.BaseElement.prototype.$getIntersectionElementLayoutBox$.call(this);var $box$jscomp$18$$=this.$getLayoutBox$();this.$O$||$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$measureIframeLayoutBox_$$(this);return _.$moveLayoutRect$$module$src$layout_rect$$(this.$O$,$box$jscomp$18$$.left,$box$jscomp$18$$.top)};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $$jscomp$this$jscomp$683$$=this;this.$M$||(this.element.$getLayoutBox$(),this.$getViewport$().$getSize$());if(!this.$G$)return Promise.resolve();if(this.$I$&&($trackingIframeCount$$module$extensions$amp_iframe$0_1$amp_iframe$$++,1<$trackingIframeCount$$module$extensions$amp_iframe$0_1$amp_iframe$$))return console.error("Only 1 analytics/tracking iframe allowed per page. Please use amp-analytics instead or file a GitHub issue for your use case: https://github.com/ampproject/amphtml/issues/new"),
Promise.resolve();var $iframe$jscomp$60$$=this.element.ownerDocument.createElement("iframe");this.$D$=$iframe$jscomp$60$$;_.$JSCompiler_StaticMethods_applyFillContent$$($iframe$jscomp$60$$);$iframe$jscomp$60$$.name="amp_iframe"+$count$$module$extensions$amp_iframe$0_1$amp_iframe$$++;this.$M$&&_.$setStyle$$module$src$style$$($iframe$jscomp$60$$,"zIndex",-1);_.$JSCompiler_StaticMethods_propagateAttributes$$(this,$ATTRIBUTES_TO_PROPAGATE$$module$extensions$amp_iframe$0_1$amp_iframe$$,$iframe$jscomp$60$$);
var $allowVal$$=$iframe$jscomp$60$$.getAttribute("allow")||"";$allowVal$$=$allowVal$$.replace("autoplay","autoplay-disabled");$iframe$jscomp$60$$.setAttribute("allow",$allowVal$$);$iframe$jscomp$60$$.setAttribute("sandbox",this.$S$||"");$iframe$jscomp$60$$.src=this.$G$;this.$I$||(this.$F$=new _.$IntersectionObserverApi$$module$src$intersection_observer_polyfill$$(this,$iframe$jscomp$60$$));$iframe$jscomp$60$$.onload=function(){$iframe$jscomp$60$$.readyState="complete";$$jscomp$this$jscomp$683$$.$activateIframe_$();
$$jscomp$this$jscomp$683$$.$I$&&($$jscomp$this$jscomp$683$$.$G$=null,_.$Services$$module$src$services$timerFor$$($$jscomp$this$jscomp$683$$.$win$).$promise$(5E3).then(function(){_.$removeElement$$module$src$dom$$($iframe$jscomp$60$$);$$jscomp$this$jscomp$683$$.element.setAttribute("amp-removed","");$$jscomp$this$jscomp$683$$.$D$=null}))};_.$listenFor$$module$src$iframe_helper$$($iframe$jscomp$60$$,"embed-size",function($iframe$jscomp$60$$){$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$updateSize_$$($$jscomp$this$jscomp$683$$,
$iframe$jscomp$60$$.height,$iframe$jscomp$60$$.width)},void 0,void 0,!0);this.$M$&&_.$listenFor$$module$src$iframe_helper$$($iframe$jscomp$60$$,"embed-ready",this.$activateIframe_$.bind(this));this.$J$.appendChild($iframe$jscomp$60$$);return this.$loadPromise$($iframe$jscomp$60$$).then(function(){$$jscomp$this$jscomp$683$$.$J$!=$$jscomp$this$jscomp$683$$.element&&_.$Services$$module$src$services$timerFor$$($$jscomp$this$jscomp$683$$.$win$).delay(function(){$$jscomp$this$jscomp$683$$.$mutateElement$(function(){$$jscomp$this$jscomp$683$$.$J$.classList.add("amp-active")})},
1E3)})};_.$JSCompiler_prototypeAlias$$.$unlayoutOnPause$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$K$&&this.$togglePlaceholder$(!0),this.$D$=null,this.$F$&&(this.$F$.$destroy$(),this.$F$=null));return!0};_.$JSCompiler_prototypeAlias$$.$viewportCallback$=function($inViewport$jscomp$19$$){this.$F$&&(this.$F$.$isInViewport_$=$inViewport$jscomp$19$$)};
_.$JSCompiler_prototypeAlias$$.$getLayoutPriority$=function(){return this.$P$?2:this.$I$?1:AMP.BaseElement.prototype.$getLayoutPriority$.call(this)};
_.$JSCompiler_prototypeAlias$$.$mutatedAttributesCallback$=function($mutations$jscomp$11_src$jscomp$45$$){$mutations$jscomp$11_src$jscomp$45$$=$mutations$jscomp$11_src$jscomp$45$$.src;void 0!==$mutations$jscomp$11_src$jscomp$45$$&&(this.$G$=$JSCompiler_StaticMethods_transformSrc_$$(this,$mutations$jscomp$11_src$jscomp$45$$),this.$D$&&(this.$D$.src=$JSCompiler_StaticMethods_AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe_prototype$assertSource_$$(this,this.$G$)))};
_.$JSCompiler_prototypeAlias$$.$activateIframe_$=function(){var $$jscomp$this$jscomp$684$$=this;this.$K$&&_.$JSCompiler_StaticMethods_getVsync$$(this).$mutate$(function(){$$jscomp$this$jscomp$684$$.$D$&&(_.$setStyle$$module$src$style$$($$jscomp$this$jscomp$684$$.$D$,"zIndex",0),$$jscomp$this$jscomp$684$$.$togglePlaceholder$(!1))})};_.$JSCompiler_prototypeAlias$$.$firstLayoutCompleted$=function(){};
_.$JSCompiler_prototypeAlias$$.$throwIfCannotNavigate$=function(){if(!/\sallow-top-navigation\s/i.test(" "+this.$S$+" "))throw _.$user$$module$src$log$$().$createError$('"AMP.navigateTo" is only allowed on <amp-iframe> when its "sandbox" attribute contains "allow-top-navigation".');};self.AMP.registerElement("amp-iframe",$AmpIframe$$module$extensions$amp_iframe$0_1$amp_iframe$$);
})});

//# sourceMappingURL=amp-iframe-0.1.js.map
