(self.AMP=self.AMP||[]).push({n:"amp-kaltura-player",i:["_base_i","_base_media"],v:"1904281823091",f:(function(AMP,_){
var $AmpKaltura$$module$extensions$amp_kaltura_player$0_1$amp_kaltura_player$$=function($$jscomp$super$this$jscomp$70_element$jscomp$522$$){$$jscomp$super$this$jscomp$70_element$jscomp$522$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$70_element$jscomp$522$$)||this;$$jscomp$super$this$jscomp$70_element$jscomp$522$$.$F$=null;$$jscomp$super$this$jscomp$70_element$jscomp$522$$.$D$="";$$jscomp$super$this$jscomp$70_element$jscomp$522$$.$G$="";return $$jscomp$super$this$jscomp$70_element$jscomp$522$$};
_.$$jscomp$inherits$$($AmpKaltura$$module$extensions$amp_kaltura_player$0_1$amp_kaltura_player$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpKaltura$$module$extensions$amp_kaltura_player$0_1$amp_kaltura_player$$.prototype;_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($opt_onLayout$jscomp$21$$){this.$preconnect$.url("https://cdnapisec.kaltura.com",$opt_onLayout$jscomp$21$$)};_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$82$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$82$$)};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){this.$D$=this.element.getAttribute("data-partner");this.$G$=this.element.getAttribute("data-entryid")||"default"};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $src$jscomp$54_uiconfId$$=this.element.getAttribute("data-uiconf")||this.element.getAttribute("data-uiconf-id")||"default",$iframe$jscomp$69$$=this.element.ownerDocument.createElement("iframe");$src$jscomp$54_uiconfId$$="https://cdnapisec.kaltura.com/p/"+encodeURIComponent(this.$D$)+"/sp/"+encodeURIComponent(this.$D$)+"00/embedIframeJs/uiconf_id/"+encodeURIComponent($src$jscomp$54_uiconfId$$)+"/partner_id/"+encodeURIComponent(this.$D$)+
"?iframeembed=true&playerId=kaltura_player_amp&entry_id="+encodeURIComponent(this.$G$);var $params$jscomp$34$$=_.$getDataParamsFromAttributes$$module$src$dom$$(this.element,function($src$jscomp$54_uiconfId$$){return"flashvars["+$src$jscomp$54_uiconfId$$+"]"});$src$jscomp$54_uiconfId$$=_.$addParamsToUrl$$module$src$url$$($src$jscomp$54_uiconfId$$,$params$jscomp$34$$);$iframe$jscomp$69$$.setAttribute("frameborder","0");$iframe$jscomp$69$$.setAttribute("allowfullscreen","true");$iframe$jscomp$69$$.src=
$src$jscomp$54_uiconfId$$;_.$JSCompiler_StaticMethods_applyFillContent$$($iframe$jscomp$69$$);this.element.appendChild($iframe$jscomp$69$$);this.$F$=$iframe$jscomp$69$$;return this.$loadPromise$($iframe$jscomp$69$$)};
_.$JSCompiler_prototypeAlias$$.$createPlaceholderCallback$=function(){var $placeholder$jscomp$16$$=this.$win$.document.createElement("amp-img");_.$JSCompiler_StaticMethods_propagateAttributes$$(this,["aria-label"],$placeholder$jscomp$16$$);var $width$jscomp$70$$=this.element.getAttribute("width"),$height$jscomp$64$$=this.element.getAttribute("height"),$src$jscomp$55$$="https://cdnapisec.kaltura.com/p/"+encodeURIComponent(this.$D$)+"/thumbnail/entry_id/"+encodeURIComponent(this.$G$);$width$jscomp$70$$&&
($src$jscomp$55$$+="/width/"+$width$jscomp$70$$);$height$jscomp$64$$&&($src$jscomp$55$$+="/height/"+$height$jscomp$64$$);$placeholder$jscomp$16$$.setAttribute("src",$src$jscomp$55$$);$placeholder$jscomp$16$$.setAttribute("layout","fill");$placeholder$jscomp$16$$.setAttribute("placeholder","");$placeholder$jscomp$16$$.setAttribute("referrerpolicy","origin");$placeholder$jscomp$16$$.hasAttribute("aria-label")?$placeholder$jscomp$16$$.setAttribute("alt","Loading video - "+$placeholder$jscomp$16$$.getAttribute("aria-label")):
$placeholder$jscomp$16$$.setAttribute("alt","Loading video");return $placeholder$jscomp$16$$};_.$JSCompiler_prototypeAlias$$.$pauseCallback$=function(){this.$F$&&this.$F$.contentWindow&&this.$F$.contentWindow.postMessage(JSON.stringify(_.$dict$$module$src$utils$object$$({method:"pause",value:""})),"*")};self.AMP.registerElement("amp-kaltura-player",$AmpKaltura$$module$extensions$amp_kaltura_player$0_1$amp_kaltura_player$$);
})});

//# sourceMappingURL=amp-kaltura-player-0.1.js.map
