(self.AMP=self.AMP||[]).push({n:"amp-springboard-player",i:["_base_i","_base_media"],v:"1904281823091",f:(function(AMP,_){
var $AmpSpringboardPlayer$$module$extensions$amp_springboard_player$0_1$amp_springboard_player$$=function($$jscomp$super$this$jscomp$100_element$jscomp$627$$){$$jscomp$super$this$jscomp$100_element$jscomp$627$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$100_element$jscomp$627$$)||this;$$jscomp$super$this$jscomp$100_element$jscomp$627$$.$H$="";$$jscomp$super$this$jscomp$100_element$jscomp$627$$.$F$="";$$jscomp$super$this$jscomp$100_element$jscomp$627$$.$G$="";$$jscomp$super$this$jscomp$100_element$jscomp$627$$.$J$=
"";$$jscomp$super$this$jscomp$100_element$jscomp$627$$.$I$="";$$jscomp$super$this$jscomp$100_element$jscomp$627$$.$D$=null;return $$jscomp$super$this$jscomp$100_element$jscomp$627$$};_.$$jscomp$inherits$$($AmpSpringboardPlayer$$module$extensions$amp_springboard_player$0_1$amp_springboard_player$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpSpringboardPlayer$$module$extensions$amp_springboard_player$0_1$amp_springboard_player$$.prototype;
_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($opt_onLayout$jscomp$27$$){this.$preconnect$.url("https://cms.springboardplatform.com",$opt_onLayout$jscomp$27$$);this.$preconnect$.url("https://www.springboardplatform.com",$opt_onLayout$jscomp$27$$)};_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$103$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$103$$)};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){this.$H$=this.element.getAttribute("data-mode");this.$F$=this.element.getAttribute("data-content-id");this.$G$=this.element.getAttribute("data-domain");this.$J$=this.element.getAttribute("data-site-id");this.$I$=this.element.getAttribute("data-player-id")};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $iframe$jscomp$83$$=this.element.ownerDocument.createElement("iframe"),$items$jscomp$10$$=this.element.getAttribute("data-items")||"10";$iframe$jscomp$83$$.setAttribute("frameborder","0");$iframe$jscomp$83$$.setAttribute("allowfullscreen","true");$iframe$jscomp$83$$.id=this.$I$+"_"+this.$F$;$iframe$jscomp$83$$.src="https://cms.springboardplatform.com/embed_iframe/"+encodeURIComponent(this.$J$)+"/"+encodeURIComponent(this.$H$)+"/"+encodeURIComponent(this.$F$)+
"/"+encodeURIComponent(this.$I$)+"/"+encodeURIComponent(this.$G$)+"/"+encodeURIComponent($items$jscomp$10$$);_.$JSCompiler_StaticMethods_applyFillContent$$($iframe$jscomp$83$$);this.$D$=$iframe$jscomp$83$$;this.element.appendChild($iframe$jscomp$83$$);return this.$loadPromise$($iframe$jscomp$83$$)};_.$JSCompiler_prototypeAlias$$.$pauseCallback$=function(){this.$D$&&this.$D$.contentWindow&&this.$D$.contentWindow.postMessage("ampPause","*")};
_.$JSCompiler_prototypeAlias$$.$createPlaceholderCallback$=function(){var $placeholder$jscomp$20$$=this.$win$.document.createElement("amp-img");_.$JSCompiler_StaticMethods_propagateAttributes$$(this,["aria-label"],$placeholder$jscomp$20$$);$placeholder$jscomp$20$$.setAttribute("src","https://www.springboardplatform.com/storage/"+encodeURIComponent(this.$G$)+"/snapshots/"+encodeURIComponent(this.$F$)+".jpg");"playlist"==this.$H$&&$placeholder$jscomp$20$$.setAttribute("src","https://www.springboardplatform.com/storage/default/snapshots/default_snapshot.png");
$placeholder$jscomp$20$$.setAttribute("placeholder","");$placeholder$jscomp$20$$.setAttribute("referrerpolicy","origin");$placeholder$jscomp$20$$.setAttribute("layout","fill");$placeholder$jscomp$20$$.hasAttribute("aria-label")?$placeholder$jscomp$20$$.setAttribute("alt","Loading video - "+$placeholder$jscomp$20$$.getAttribute("aria-label")):$placeholder$jscomp$20$$.setAttribute("alt","Loading video");return $placeholder$jscomp$20$$};self.AMP.registerElement("amp-springboard-player",$AmpSpringboardPlayer$$module$extensions$amp_springboard_player$0_1$amp_springboard_player$$);
})});

//# sourceMappingURL=amp-springboard-player-0.1.js.map
