(self.AMP=self.AMP||[]).push({n:"amp-user-notification",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $AmpUserNotification$$module$extensions$amp_user_notification$0_1$amp_user_notification$$=function($$jscomp$super$this$jscomp$116_element$jscomp$726$$){$$jscomp$super$this$jscomp$116_element$jscomp$726$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$116_element$jscomp$726$$)||this;$$jscomp$super$this$jscomp$116_element$jscomp$726$$.$R$=null;$$jscomp$super$this$jscomp$116_element$jscomp$726$$.$D$=null;var $deferred$jscomp$63$$=new _.$Deferred$$module$src$utils$promise$$;$$jscomp$super$this$jscomp$116_element$jscomp$726$$.$S$=
$deferred$jscomp$63$$.$promise$;$$jscomp$super$this$jscomp$116_element$jscomp$726$$.$U$=$deferred$jscomp$63$$.resolve;$$jscomp$super$this$jscomp$116_element$jscomp$726$$.$I$=null;$$jscomp$super$this$jscomp$116_element$jscomp$726$$.$J$=!1;$$jscomp$super$this$jscomp$116_element$jscomp$726$$.$K$=null;$$jscomp$super$this$jscomp$116_element$jscomp$726$$.$O$=null;$$jscomp$super$this$jscomp$116_element$jscomp$726$$.$F$=null;$$jscomp$super$this$jscomp$116_element$jscomp$726$$.$M$=null;$$jscomp$super$this$jscomp$116_element$jscomp$726$$.$G$=
"";$$jscomp$super$this$jscomp$116_element$jscomp$726$$.$H$=null;$$jscomp$super$this$jscomp$116_element$jscomp$726$$.$P$=null;return $$jscomp$super$this$jscomp$116_element$jscomp$726$$},$JSCompiler_StaticMethods_isNotificationRequiredGeo_$$=function($JSCompiler_StaticMethods_isNotificationRequiredGeo_$self$$,$geoGroup$jscomp$3$$,$includeGeos$$){return _.$Services$$module$src$services$geoForDocOrNull$$($JSCompiler_StaticMethods_isNotificationRequiredGeo_$self$$.element).then(function($JSCompiler_StaticMethods_isNotificationRequiredGeo_$self$$){var $geo$jscomp$4$$=
$geoGroup$jscomp$3$$.split(/,\s*/).filter(function($geoGroup$jscomp$3$$){return 2==$JSCompiler_StaticMethods_isNotificationRequiredGeo_$self$$.$isInCountryGroup$($geoGroup$jscomp$3$$)});return!($includeGeos$$?!$geo$jscomp$4$$.length:$geo$jscomp$4$$.length)})},$JSCompiler_StaticMethods_buildGetHref_$$=function($JSCompiler_StaticMethods_buildGetHref_$self$$,$ampUserId$$){return _.$JSCompiler_StaticMethods_expandUrlAsync$$($JSCompiler_StaticMethods_buildGetHref_$self$$.$P$,$JSCompiler_StaticMethods_buildGetHref_$self$$.$M$).then(function($href$jscomp$15$$){return _.$addParamsToUrl$$module$src$url$$($href$jscomp$15$$,
{elementId:$JSCompiler_StaticMethods_buildGetHref_$self$$.$D$,ampUserId:$ampUserId$$})})},$JSCompiler_StaticMethods_postDismissEnpoint_$$=function($JSCompiler_StaticMethods_postDismissEnpoint_$self$$){var $enctype$$=$JSCompiler_StaticMethods_postDismissEnpoint_$self$$.element.getAttribute("enctype")||"application/json;charset=utf-8";_.$JSCompiler_StaticMethods_fetchJson$$(_.$Services$$module$src$services$xhrFor$$($JSCompiler_StaticMethods_postDismissEnpoint_$self$$.$win$),$JSCompiler_StaticMethods_postDismissEnpoint_$self$$.$I$,
{method:"POST",credentials:"include",requireAmpResponseSourceOrigin:!1,body:_.$dict$$module$src$utils$object$$({elementId:$JSCompiler_StaticMethods_postDismissEnpoint_$self$$.$D$,ampUserId:$JSCompiler_StaticMethods_postDismissEnpoint_$self$$.$R$}),headers:{"Content-Type":$enctype$$}})},$JSCompiler_StaticMethods_optoutOfCid_$$=function($JSCompiler_StaticMethods_optoutOfCid_$self$$){return _.$Services$$module$src$services$cidForDoc$$($JSCompiler_StaticMethods_optoutOfCid_$self$$.element).then(function($JSCompiler_StaticMethods_optoutOfCid_$self$$){return _.$optOutOfCid$$module$src$service$cid_impl$$($JSCompiler_StaticMethods_optoutOfCid_$self$$.ampdoc)}).then(function(){return $JSCompiler_StaticMethods_dismiss$$($JSCompiler_StaticMethods_optoutOfCid_$self$$,
!1)},function($reason$jscomp$64$$){_.$dev$$module$src$log$$().error("amp-user-notification","Failed to opt out of Cid",$reason$jscomp$64$$);$JSCompiler_StaticMethods_dismiss$$($JSCompiler_StaticMethods_optoutOfCid_$self$$,!0)})},$JSCompiler_StaticMethods_getAsyncCid_$$=function($JSCompiler_StaticMethods_getAsyncCid_$self$$){return _.$Services$$module$src$services$cidForDoc$$($JSCompiler_StaticMethods_getAsyncCid_$self$$.element).then(function($cid$jscomp$12$$){return $cid$jscomp$12$$.get({scope:"amp-user-notification",
createCookieIfNotPresent:!0},Promise.resolve(),$JSCompiler_StaticMethods_getAsyncCid_$self$$.$S$)})},$JSCompiler_StaticMethods_shouldShow$$=function($JSCompiler_StaticMethods_shouldShow$self$$){return $JSCompiler_StaticMethods_shouldShow$self$$.$isDismissed$().then(function($dismissed$$){return $dismissed$$?!1:$JSCompiler_StaticMethods_shouldShow$self$$.$M$?$JSCompiler_StaticMethods_getAsyncCid_$$($JSCompiler_StaticMethods_shouldShow$self$$).then($JSCompiler_StaticMethods_shouldShow$self$$.$getShowEndpoint_$.bind($JSCompiler_StaticMethods_shouldShow$self$$)).then($JSCompiler_StaticMethods_shouldShow$self$$.$onGetShowEndpointSuccess_$.bind($JSCompiler_StaticMethods_shouldShow$self$$)):
$JSCompiler_StaticMethods_shouldShow$self$$.$F$?$JSCompiler_StaticMethods_shouldShow$self$$.$F$:!0})},$JSCompiler_StaticMethods_dismiss$$=function($JSCompiler_StaticMethods_dismiss$self$$,$forceNoPersist$$){$JSCompiler_StaticMethods_dismiss$self$$.element.classList.remove("amp-active");$JSCompiler_StaticMethods_dismiss$self$$.element.classList.add("amp-hidden");$JSCompiler_StaticMethods_dismiss$self$$.$U$();_.$JSCompiler_StaticMethods_removeFromFixedLayer$$($JSCompiler_StaticMethods_dismiss$self$$.$getViewport$(),
$JSCompiler_StaticMethods_dismiss$self$$.element);$JSCompiler_StaticMethods_dismiss$self$$.$J$&&!$forceNoPersist$$&&$JSCompiler_StaticMethods_dismiss$self$$.$H$.then(function($forceNoPersist$$){$forceNoPersist$$.set($JSCompiler_StaticMethods_dismiss$self$$.$G$,!0)});$JSCompiler_StaticMethods_dismiss$self$$.$I$&&$JSCompiler_StaticMethods_postDismissEnpoint_$$($JSCompiler_StaticMethods_dismiss$self$$)},$UserNotificationManager$$module$extensions$amp_user_notification$0_1$amp_user_notification$$=function($ampdoc$jscomp$254$$){this.ampdoc=
$ampdoc$jscomp$254$$;this.$F$=Object.create(null);this.$D$=Object.create(null);this.$J$=_.$Services$$module$src$services$viewerForDoc$$(this.ampdoc);this.$G$=this.ampdoc.$whenReady$();this.$I$=Promise.all([this.$J$.$D$,this.$G$]);this.$K$=_.$getServicePromiseForDoc$$module$src$service$$(this.ampdoc,"notificationUIManager")},$JSCompiler_StaticMethods_registerUserNotification$$=function($JSCompiler_StaticMethods_registerUserNotification$self$$,$id$jscomp$115$$,$userNotification$jscomp$2$$){$JSCompiler_StaticMethods_registerUserNotification$self$$.$F$[$id$jscomp$115$$]=
$userNotification$jscomp$2$$;var $deferred$jscomp$64$$=$JSCompiler_StaticMethods_getOrCreateDeferById_$$($JSCompiler_StaticMethods_registerUserNotification$self$$,$id$jscomp$115$$);$JSCompiler_StaticMethods_registerUserNotification$self$$.$I$.then(function(){return $JSCompiler_StaticMethods_shouldShow$$($userNotification$jscomp$2$$)}).then(function($id$jscomp$115$$){if($id$jscomp$115$$)return $JSCompiler_StaticMethods_registerUserNotification$self$$.$K$.then(function($JSCompiler_StaticMethods_registerUserNotification$self$$){return _.$JSCompiler_StaticMethods_registerUI$$($JSCompiler_StaticMethods_registerUserNotification$self$$,
$userNotification$jscomp$2$$.show.bind($userNotification$jscomp$2$$))})}).then($deferred$jscomp$64$$.resolve.bind($JSCompiler_StaticMethods_registerUserNotification$self$$,$userNotification$jscomp$2$$)).catch(_.$rethrowAsync$$module$src$log$$.bind(null,"Notification service failed amp-user-notification",$id$jscomp$115$$))},$JSCompiler_StaticMethods_getOrCreateDeferById_$$=function($JSCompiler_StaticMethods_getOrCreateDeferById_$self$$,$id$jscomp$116$$){if($JSCompiler_StaticMethods_getOrCreateDeferById_$self$$.$D$[$id$jscomp$116$$])return $JSCompiler_StaticMethods_getOrCreateDeferById_$self$$.$D$[$id$jscomp$116$$];
var $$jscomp$destructuring$var642$$=new _.$Deferred$$module$src$utils$promise$$;return $JSCompiler_StaticMethods_getOrCreateDeferById_$self$$.$D$[$id$jscomp$116$$]={$promise$:$$jscomp$destructuring$var642$$.$promise$,resolve:$$jscomp$destructuring$var642$$.resolve}};_.$$jscomp$inherits$$($AmpUserNotification$$module$extensions$amp_user_notification$0_1$amp_user_notification$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpUserNotification$$module$extensions$amp_user_notification$0_1$amp_user_notification$$.prototype;_.$JSCompiler_prototypeAlias$$.$isAlwaysFixed$=function(){return!0};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){var $$jscomp$this$jscomp$1353$$=this,$ampdoc$jscomp$253$$=this.$getAmpDoc$();this.$P$=_.$Services$$module$src$services$urlReplacementsForDoc$$(this.element);this.$H$=_.$Services$$module$src$services$storageForDoc$$(this.element);this.$D$=this.element.id;this.$G$="amp-user-notification:"+this.$D$;this.$K$=this.element.getAttribute("data-show-if-geo");this.$O$=this.element.getAttribute("data-show-if-not-geo");this.$M$=this.element.getAttribute("data-show-if-href");
this.$K$&&(this.$F$=$JSCompiler_StaticMethods_isNotificationRequiredGeo_$$(this,this.$K$,!0));this.$O$&&(this.$F$=$JSCompiler_StaticMethods_isNotificationRequiredGeo_$$(this,this.$O$,!1));this.$I$=this.element.getAttribute("data-dismiss-href");this.element.getAttribute("role")||this.element.setAttribute("role","alert");var $persistDismissal$$=this.element.getAttribute("data-persist-dismissal");this.$J$="false"!=$persistDismissal$$&&"no"!=$persistDismissal$$;_.$JSCompiler_StaticMethods_registerDefaultAction$$(this,
function(){return $JSCompiler_StaticMethods_dismiss$$($$jscomp$this$jscomp$1353$$,!1)},"dismiss");_.$JSCompiler_StaticMethods_registerAction$$(this,"optoutOfCid",function(){return $JSCompiler_StaticMethods_optoutOfCid_$$($$jscomp$this$jscomp$1353$$)});_.$getServicePromiseForDoc$$module$src$service$$($ampdoc$jscomp$253$$,"userNotificationManager").then(function($ampdoc$jscomp$253$$){$JSCompiler_StaticMethods_registerUserNotification$$($ampdoc$jscomp$253$$,$$jscomp$this$jscomp$1353$$.$D$,$$jscomp$this$jscomp$1353$$)})};
_.$JSCompiler_prototypeAlias$$.$getShowEndpoint_$=function($ampUserId$jscomp$1$$){var $$jscomp$this$jscomp$1355$$=this;this.$R$=$ampUserId$jscomp$1$$;return $JSCompiler_StaticMethods_buildGetHref_$$(this,$ampUserId$jscomp$1$$).then(function($ampUserId$jscomp$1$$){return _.$JSCompiler_StaticMethods_fetchJson$$(_.$Services$$module$src$services$xhrFor$$($$jscomp$this$jscomp$1355$$.$win$),$ampUserId$jscomp$1$$,{credentials:"include",requireAmpResponseSourceOrigin:!1}).then(function($ampUserId$jscomp$1$$){return $ampUserId$jscomp$1$$.json()})})};
_.$JSCompiler_prototypeAlias$$.$onGetShowEndpointSuccess_$=function($data$jscomp$253$$){$data$jscomp$253$$.showNotification||this.$U$();return Promise.resolve($data$jscomp$253$$.showNotification)};_.$JSCompiler_prototypeAlias$$.show=function(){_.$toggle$$module$src$style$$(this.element,!0);this.element.classList.add("amp-active");_.$JSCompiler_StaticMethods_addToFixedLayer$$(this.$getViewport$(),this.element);return this.$S$};
_.$JSCompiler_prototypeAlias$$.$isDismissed$=function(){var $$jscomp$this$jscomp$1359$$=this;return this.$J$?this.$H$.then(function($storage$jscomp$8$$){return $storage$jscomp$8$$.get($$jscomp$this$jscomp$1359$$.$G$)}).then(function($$jscomp$this$jscomp$1359$$){return!!$$jscomp$this$jscomp$1359$$},function($$jscomp$this$jscomp$1359$$){_.$dev$$module$src$log$$().error("amp-user-notification","Failed to read storage",$$jscomp$this$jscomp$1359$$);return!1}):Promise.resolve(!1)};
$UserNotificationManager$$module$extensions$amp_user_notification$0_1$amp_user_notification$$.prototype.get=function($id$jscomp$113$$){var $$jscomp$this$jscomp$1361$$=this;this.$I$.then(function(){null==$$jscomp$this$jscomp$1361$$.ampdoc.getElementById($id$jscomp$113$$)&&_.$user$$module$src$log$$().$Log$$module$src$log_prototype$warn$("amp-user-notification","Did not find amp-user-notification element "+$id$jscomp$113$$+".")});return $JSCompiler_StaticMethods_getOrCreateDeferById_$$(this,$id$jscomp$113$$).$promise$};
$UserNotificationManager$$module$extensions$amp_user_notification$0_1$amp_user_notification$$.prototype.$H$=function($id$jscomp$114$$){var $$jscomp$this$jscomp$1362$$=this;return this.$G$.then(function(){return $$jscomp$this$jscomp$1362$$.$F$[$id$jscomp$114$$]})};var $AMP$jscomp$inline_5399$$=self.AMP;$AMP$jscomp$inline_5399$$.registerServiceForDoc("userNotificationManager",$UserNotificationManager$$module$extensions$amp_user_notification$0_1$amp_user_notification$$);
$AMP$jscomp$inline_5399$$.registerServiceForDoc("notificationUIManager",_.$NotificationUiManager$$module$src$service$notification_ui_manager$$);$AMP$jscomp$inline_5399$$.registerElement("amp-user-notification",$AmpUserNotification$$module$extensions$amp_user_notification$0_1$amp_user_notification$$,"amp-user-notification{position:fixed!important;bottom:0;left:0;overflow:hidden!important;visibility:hidden;background:hsla(0,0%,100%,0.7);z-index:1000;width:100%}amp-user-notification.amp-active{visibility:visible}amp-user-notification.amp-hidden{visibility:hidden}\n/*# sourceURL=/extensions/amp-user-notification/0.1/amp-user-notification.css*/");
})});

//# sourceMappingURL=amp-user-notification-0.1.js.map
