(self.AMP=self.AMP||[]).push({n:"amp-orientation-observer",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer$$=function($$jscomp$super$this$jscomp$83_element$jscomp$578$$){$$jscomp$super$this$jscomp$83_element$jscomp$578$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$83_element$jscomp$578$$)||this;$$jscomp$super$this$jscomp$83_element$jscomp$578$$.$ampdoc_$=_.$getAmpdoc$$module$src$service$$($$jscomp$super$this$jscomp$83_element$jscomp$578$$.element);$$jscomp$super$this$jscomp$83_element$jscomp$578$$.$K$=
null;$$jscomp$super$this$jscomp$83_element$jscomp$578$$.$D$=[0,360];$$jscomp$super$this$jscomp$83_element$jscomp$578$$.$G$=[-180,180];$$jscomp$super$this$jscomp$83_element$jscomp$578$$.$I$=[-90,90];$$jscomp$super$this$jscomp$83_element$jscomp$578$$.$F$=180;$$jscomp$super$this$jscomp$83_element$jscomp$578$$.$H$=0;$$jscomp$super$this$jscomp$83_element$jscomp$578$$.$J$=0;return $$jscomp$super$this$jscomp$83_element$jscomp$578$$},$JSCompiler_StaticMethods_AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer_prototype$parseAttributes_$$=
function($JSCompiler_StaticMethods_AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer_prototype$parseAttributes_$self_providedRange$$,$rangeName$$,$originalRange_rangeArray$$){return($JSCompiler_StaticMethods_AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer_prototype$parseAttributes_$self_providedRange$$=$JSCompiler_StaticMethods_AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer_prototype$parseAttributes_$self_providedRange$$.element.getAttribute($rangeName$$))?
($originalRange_rangeArray$$=$JSCompiler_StaticMethods_AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer_prototype$parseAttributes_$self_providedRange$$.trim().split(" "),[parseInt($originalRange_rangeArray$$[0],10),parseInt($originalRange_rangeArray$$[1],10)]):$originalRange_rangeArray$$},$JSCompiler_StaticMethods_AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer_prototype$triggerEvent_$$=function($JSCompiler_StaticMethods_AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer_prototype$triggerEvent_$self$$,
$eventName$jscomp$4$$,$event$jscomp$171_eventValue$$,$eventRange$$){$event$jscomp$171_eventValue$$=_.$createCustomEvent$$module$src$event_helper$$($JSCompiler_StaticMethods_AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer_prototype$triggerEvent_$self$$.$win$,"amp-orientation-observer."+$eventName$jscomp$4$$,_.$dict$$module$src$utils$object$$({angle:$event$jscomp$171_eventValue$$.toFixed(),percent:(0>$eventRange$$[0]?$event$jscomp$171_eventValue$$.toFixed()-
$eventRange$$[0]:$event$jscomp$171_eventValue$$.toFixed())/($eventRange$$[1]-$eventRange$$[0])}));$JSCompiler_StaticMethods_AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer_prototype$triggerEvent_$self$$.$K$.$trigger$($JSCompiler_StaticMethods_AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer_prototype$triggerEvent_$self$$.element,$eventName$jscomp$4$$,$event$jscomp$171_eventValue$$,1)};
_.$$jscomp$inherits$$($AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer$$,AMP.BaseElement);$AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer$$.prototype.$buildCallback$=function(){this.$K$=_.$Services$$module$src$services$actionServiceForDoc$$(this.element);_.$Services$$module$src$services$viewerForDoc$$(this.$ampdoc_$).$D$.then(this.$M$.bind(this))};
$AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer$$.prototype.$M$=function(){var $$jscomp$this$jscomp$835$$=this;this.$D$=$JSCompiler_StaticMethods_AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer_prototype$parseAttributes_$$(this,"alpha-range",this.$D$);this.$G$=$JSCompiler_StaticMethods_AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer_prototype$parseAttributes_$$(this,
"beta-range",this.$G$);this.$I$=$JSCompiler_StaticMethods_AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer_prototype$parseAttributes_$$(this,"gamma-range",this.$I$);this.$win$.addEventListener("deviceorientation",function($event$jscomp$169$$){$event$jscomp$169$$ instanceof DeviceOrientationEvent&&(.1<Math.abs($event$jscomp$169$$.alpha-$$jscomp$this$jscomp$835$$.$F$)&&($$jscomp$this$jscomp$835$$.$F$=$event$jscomp$169$$.alpha,$JSCompiler_StaticMethods_AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer_prototype$triggerEvent_$$($$jscomp$this$jscomp$835$$,
"alpha",$$jscomp$this$jscomp$835$$.$F$,$$jscomp$this$jscomp$835$$.$D$)),.1<Math.abs($event$jscomp$169$$.beta-$$jscomp$this$jscomp$835$$.$H$)&&($$jscomp$this$jscomp$835$$.$H$=$event$jscomp$169$$.beta,$JSCompiler_StaticMethods_AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer_prototype$triggerEvent_$$($$jscomp$this$jscomp$835$$,"beta",$$jscomp$this$jscomp$835$$.$H$,$$jscomp$this$jscomp$835$$.$G$)),.1<Math.abs($event$jscomp$169$$.gamma-$$jscomp$this$jscomp$835$$.$J$)&&
($$jscomp$this$jscomp$835$$.$J$=$event$jscomp$169$$.gamma,$JSCompiler_StaticMethods_AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer_prototype$triggerEvent_$$($$jscomp$this$jscomp$835$$,"gamma",$$jscomp$this$jscomp$835$$.$J$,$$jscomp$this$jscomp$835$$.$I$)))},!0)};self.AMP.registerElement("amp-orientation-observer",$AmpOrientationObserver$$module$extensions$amp_orientation_observer$0_1$amp_orientation_observer$$);
})});

//# sourceMappingURL=amp-orientation-observer-0.1.js.map
