(self.AMP=self.AMP||[]).push({n:"amp-o2-player",i:["_base_i","_base_media"],v:"1904281823091",f:(function(AMP,_){
var $AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$=function($$jscomp$super$this$jscomp$81_element$jscomp$576$$){$$jscomp$super$this$jscomp$81_element$jscomp$576$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$81_element$jscomp$576$$)||this;$$jscomp$super$this$jscomp$81_element$jscomp$576$$.$F$=null;$$jscomp$super$this$jscomp$81_element$jscomp$576$$.$I$="";$$jscomp$super$this$jscomp$81_element$jscomp$576$$.$H$="";$$jscomp$super$this$jscomp$81_element$jscomp$576$$.$D$="";$$jscomp$super$this$jscomp$81_element$jscomp$576$$.$G$=
"";return $$jscomp$super$this$jscomp$81_element$jscomp$576$$};_.$$jscomp$inherits$$($AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$.prototype;_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($onLayout$jscomp$7$$){this.$preconnect$.url(this.$D$,$onLayout$jscomp$7$$)};_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$90$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$90$$)};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){this.$I$=this.element.getAttribute("data-pid");this.$H$=this.element.getAttribute("data-bcid");var $bid$$=this.element.getAttribute("data-bid"),$vid$$=this.element.getAttribute("data-vid"),$macros$jscomp$5$$=this.element.getAttribute("data-macros");this.$D$="https://delivery."+("stage"!=this.element.getAttribute("data-env")?"":"dev.")+"vidible.tv";var $src$jscomp$61$$=this.$D$+"/htmlembed/",$queryParams$jscomp$6$$=[];$src$jscomp$61$$+="pid="+
encodeURIComponent(this.$I$)+"/"+encodeURIComponent(this.$H$)+".html";$bid$$&&$queryParams$jscomp$6$$.push("bid="+encodeURIComponent($bid$$));$vid$$&&$queryParams$jscomp$6$$.push("vid="+encodeURIComponent($vid$$));$macros$jscomp$5$$&&$queryParams$jscomp$6$$.push($macros$jscomp$5$$);0<$queryParams$jscomp$6$$.length&&($src$jscomp$61$$+="?"+$queryParams$jscomp$6$$.join("&"));this.$G$=$src$jscomp$61$$};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $iframe$jscomp$73$$=this.element.ownerDocument.createElement("iframe");$iframe$jscomp$73$$.setAttribute("frameborder","0");$iframe$jscomp$73$$.setAttribute("allowfullscreen","true");$iframe$jscomp$73$$.src=this.$G$;this.$F$=$iframe$jscomp$73$$;_.$JSCompiler_StaticMethods_applyFillContent$$($iframe$jscomp$73$$);this.element.appendChild($iframe$jscomp$73$$);return this.$loadPromise$($iframe$jscomp$73$$)};
_.$JSCompiler_prototypeAlias$$.$pauseCallback$=function(){this.$F$&&this.$F$.contentWindow&&this.$F$.contentWindow.postMessage(JSON.stringify(_.$dict$$module$src$utils$object$$({method:"pause",value:this.$D$})),"*")};self.AMP.registerElement("amp-o2-player",$AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$);
})});

//# sourceMappingURL=amp-o2-player-0.1.js.map
