(self.AMP=self.AMP||[]).push({n:"amp-action-macro",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$=function($$jscomp$super$this$jscomp$6_element$jscomp$299$$){$$jscomp$super$this$jscomp$6_element$jscomp$299$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$6_element$jscomp$299$$)||this;$$jscomp$super$this$jscomp$6_element$jscomp$299$$.$D$=null;$$jscomp$super$this$jscomp$6_element$jscomp$299$$.$F$=[];return $$jscomp$super$this$jscomp$6_element$jscomp$299$$};
_.$$jscomp$inherits$$($AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$,AMP.BaseElement);
$AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$.prototype.$buildCallback$=function(){var $argVarNames_element$jscomp$300$$=this.element;this.$D$=_.$Services$$module$src$services$actionServiceForDoc$$($argVarNames_element$jscomp$300$$);if($argVarNames_element$jscomp$300$$=$argVarNames_element$jscomp$300$$.getAttribute("arguments"))this.$F$=$argVarNames_element$jscomp$300$$.split(",").map(function($argVarNames_element$jscomp$300$$){return $argVarNames_element$jscomp$300$$.trim()});_.$JSCompiler_StaticMethods_registerAction$$(this,
"execute",this.$G$.bind(this))};$AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$.prototype.$getLayoutPriority$=function(){return 1};
$AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$.prototype.$G$=function($invocation$jscomp$22_trust$jscomp$6$$){var $actionEventType$jscomp$7$$=$invocation$jscomp$22_trust$jscomp$6$$.$F$,$args$jscomp$22$$=$invocation$jscomp$22_trust$jscomp$6$$.args,$event$jscomp$68$$=$invocation$jscomp$22_trust$jscomp$6$$.event;$invocation$jscomp$22_trust$jscomp$6$$=$invocation$jscomp$22_trust$jscomp$6$$.$D$;if($args$jscomp$22$$&&0<this.$F$.length)for(var $arg$jscomp$11$$ in $args$jscomp$22$$);
this.$D$.$trigger$(this.element,""+$actionEventType$jscomp$7$$,$event$jscomp$68$$,$invocation$jscomp$22_trust$jscomp$6$$,$args$jscomp$22$$)};$AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$.prototype.$renderOutsideViewport$=function(){return!0};self.AMP.registerElement("amp-action-macro",$AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$);
})});

//# sourceMappingURL=amp-action-macro-0.1.js.map
