(self.AMP=self.AMP||[]).push({n:"amp-youtube",i:["_base_i","_base_media"],v:"1904281823091",f:(function(AMP,_){
var $AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube$$=function($$jscomp$super$this$jscomp$126_element$jscomp$779$$){$$jscomp$super$this$jscomp$126_element$jscomp$779$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$126_element$jscomp$779$$)||this;$$jscomp$super$this$jscomp$126_element$jscomp$779$$.$F$=null;$$jscomp$super$this$jscomp$126_element$jscomp$779$$.$O$=null;$$jscomp$super$this$jscomp$126_element$jscomp$779$$.$H$=!1;$$jscomp$super$this$jscomp$126_element$jscomp$779$$.$D$=
null;$$jscomp$super$this$jscomp$126_element$jscomp$779$$.$G$=null;$$jscomp$super$this$jscomp$126_element$jscomp$779$$.$M$=null;$$jscomp$super$this$jscomp$126_element$jscomp$779$$.$I$=null;$$jscomp$super$this$jscomp$126_element$jscomp$779$$.$J$=null;$$jscomp$super$this$jscomp$126_element$jscomp$779$$.$K$=null;return $$jscomp$super$this$jscomp$126_element$jscomp$779$$},$JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$getVideoIframeSrc_$$=function($JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$getVideoIframeSrc_$self$$){if($JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$getVideoIframeSrc_$self$$.$M$)return $JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$getVideoIframeSrc_$self$$.$M$;
var $baseUrl$jscomp$inline_5817_src$jscomp$79_urlSuffix$jscomp$inline_5816$$="";"omit"===($JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$getVideoIframeSrc_$self$$.element.getAttribute("credentials")||"include")&&($baseUrl$jscomp$inline_5817_src$jscomp$79_urlSuffix$jscomp$inline_5816$$="-nocookie");$baseUrl$jscomp$inline_5817_src$jscomp$79_urlSuffix$jscomp$inline_5816$$="https://www.youtube"+$baseUrl$jscomp$inline_5817_src$jscomp$79_urlSuffix$jscomp$inline_5816$$+
".com/embed/";var $descriptor$jscomp$inline_5818_element$jscomp$780$$=$JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$getVideoIframeSrc_$self$$.$F$?encodeURIComponent($JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$getVideoIframeSrc_$self$$.$F$||"")+"?":"live_stream?channel="+(encodeURIComponent($JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$getVideoIframeSrc_$self$$.$O$||
"")+"&");$baseUrl$jscomp$inline_5817_src$jscomp$79_urlSuffix$jscomp$inline_5816$$=$baseUrl$jscomp$inline_5817_src$jscomp$79_urlSuffix$jscomp$inline_5816$$+$descriptor$jscomp$inline_5818_element$jscomp$780$$+"enablejsapi=1&amp=1";$descriptor$jscomp$inline_5818_element$jscomp$780$$=$JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$getVideoIframeSrc_$self$$.element;var $params$jscomp$44$$=_.$getDataParamsFromAttributes$$module$src$dom$$($descriptor$jscomp$inline_5818_element$jscomp$780$$);
"autoplay"in $params$jscomp$44$$&&(delete $params$jscomp$44$$.autoplay,$JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$getVideoIframeSrc_$self$$.$user$().error("AMP-YOUTUBE","Use autoplay attribute instead of data-param-autoplay"));"playsinline"in $params$jscomp$44$$||($params$jscomp$44$$.playsinline="1");$descriptor$jscomp$inline_5818_element$jscomp$780$$.hasAttribute("autoplay")&&("iv_load_policy"in $params$jscomp$44$$||($params$jscomp$44$$.iv_load_policy=
"3"),$params$jscomp$44$$.playsinline="1");$baseUrl$jscomp$inline_5817_src$jscomp$79_urlSuffix$jscomp$inline_5816$$=_.$addParamsToUrl$$module$src$url$$($baseUrl$jscomp$inline_5817_src$jscomp$79_urlSuffix$jscomp$inline_5816$$,$params$jscomp$44$$);return $JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$getVideoIframeSrc_$self$$.$M$=$baseUrl$jscomp$inline_5817_src$jscomp$79_urlSuffix$jscomp$inline_5816$$},$JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$sendCommand_$$=
function($JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$sendCommand_$self$$,$command$jscomp$11$$,$opt_args$jscomp$24$$){$JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$sendCommand_$self$$.$I$.then(function(){if($JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$sendCommand_$self$$.$D$&&$JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$sendCommand_$self$$.$D$.contentWindow){var $message$jscomp$88$$=
JSON.stringify(_.$dict$$module$src$utils$object$$({event:"command",func:$command$jscomp$11$$,args:$opt_args$jscomp$24$$||""}));$JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$sendCommand_$self$$.$D$.contentWindow.postMessage($message$jscomp$88$$,"*")}})},$JSCompiler_StaticMethods_buildImagePlaceholder_$$=function($JSCompiler_StaticMethods_buildImagePlaceholder_$self$$){var $el$jscomp$183$$=$JSCompiler_StaticMethods_buildImagePlaceholder_$self$$.element,
$imgPlaceholder$$=_.$htmlFor$$module$src$static_template$$($el$jscomp$183$$)($_template$$module$extensions$amp_youtube$0_1$amp_youtube$$),$videoid$jscomp$2$$=$JSCompiler_StaticMethods_buildImagePlaceholder_$self$$.$F$;_.$setStyles$$module$src$style$$($imgPlaceholder$$,{"object-fit":"cover",visibility:"hidden"});_.$JSCompiler_StaticMethods_propagateAttributes$$($JSCompiler_StaticMethods_buildImagePlaceholder_$self$$,["aria-label"],$imgPlaceholder$$);$imgPlaceholder$$.src="https://i.ytimg.com/vi/"+
encodeURIComponent($videoid$jscomp$2$$)+"/sddefault.jpg#404_is_fine";$imgPlaceholder$$.hasAttribute("aria-label")?$imgPlaceholder$$.setAttribute("alt","Loading video - "+$imgPlaceholder$$.getAttribute("aria-label")):$imgPlaceholder$$.setAttribute("alt","Loading video");_.$JSCompiler_StaticMethods_applyFillContent$$($imgPlaceholder$$);$el$jscomp$183$$.appendChild($imgPlaceholder$$);$JSCompiler_StaticMethods_buildImagePlaceholder_$self$$.$loadPromise$($imgPlaceholder$$).then(function(){if(120==$imgPlaceholder$$.naturalWidth&&
90==$imgPlaceholder$$.naturalHeight)throw Error("sddefault.jpg is not found");}).catch(function(){$imgPlaceholder$$.src="https://i.ytimg.com/vi/"+encodeURIComponent($videoid$jscomp$2$$)+"/hqdefault.jpg";return $JSCompiler_StaticMethods_buildImagePlaceholder_$self$$.$loadPromise$($imgPlaceholder$$)}).then(function(){_.$JSCompiler_StaticMethods_getVsync$$($JSCompiler_StaticMethods_buildImagePlaceholder_$self$$).$mutate$(function(){_.$setStyles$$module$src$style$$($imgPlaceholder$$,{visibility:""})})})},
$_template$$module$extensions$amp_youtube$0_1$amp_youtube$$=["<img placeholder referrerpolicy=origin>"];_.$$jscomp$inherits$$($AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube$$.prototype;
_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($opt_onLayout$jscomp$33$$){var $preconnect$jscomp$8$$=this.$preconnect$;$preconnect$jscomp$8$$.url($JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$getVideoIframeSrc_$$(this));$preconnect$jscomp$8$$.url("https://s.ytimg.com",$opt_onLayout$jscomp$33$$);$preconnect$jscomp$8$$.url("https://i.ytimg.com",$opt_onLayout$jscomp$33$$)};_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$126$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$126$$)};
_.$JSCompiler_prototypeAlias$$.$renderOutsideViewport$=function(){return.75};_.$JSCompiler_prototypeAlias$$.$viewportCallback$=function($visible$jscomp$16$$){this.element.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$VISIBILITY$,{visible:$visible$jscomp$16$$})};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){this.$F$=this.element.getAttribute("data-videoid");this.$O$=this.element.getAttribute("data-live-channelid");var $deferred$jscomp$70$$=new _.$Deferred$$module$src$utils$promise$$;this.$I$=$deferred$jscomp$70$$.$promise$;this.$J$=$deferred$jscomp$70$$.resolve;!this.$getPlaceholder$()&&this.$F$&&$JSCompiler_StaticMethods_buildImagePlaceholder_$$(this);_.$installVideoManagerForDoc$$module$src$service$video_manager_impl$$(this.element)};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $$jscomp$this$jscomp$1444$$=this,$iframe$jscomp$103_loaded$jscomp$6$$=_.$createFrameFor$$module$src$iframe_video$$(this,$JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$getVideoIframeSrc_$$(this));_.$addUnsafeAllowAutoplay$$module$src$iframe_video$$($iframe$jscomp$103_loaded$jscomp$6$$);this.$D$=$iframe$jscomp$103_loaded$jscomp$6$$;_.$Services$$module$src$services$videoManagerForDoc$$(this.element).register(this);
this.$K$=_.$listen$$module$src$event_helper$$(this.$win$,"message",this.$handleYoutubeMessage_$.bind(this));$iframe$jscomp$103_loaded$jscomp$6$$=this.$loadPromise$(this.$D$).then(function(){return _.$Services$$module$src$services$timerFor$$($$jscomp$this$jscomp$1444$$.$win$).$promise$(300)}).then(function(){$$jscomp$this$jscomp$1444$$.$D$&&$$jscomp$this$jscomp$1444$$.$D$.contentWindow.postMessage(JSON.stringify(_.$dict$$module$src$utils$object$$({event:"listening"})),"*");$$jscomp$this$jscomp$1444$$.element.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$LOAD$)});
this.$J$($iframe$jscomp$103_loaded$jscomp$6$$);return $iframe$jscomp$103_loaded$jscomp$6$$};_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$D$=null);this.$K$&&this.$K$();var $deferred$jscomp$71$$=new _.$Deferred$$module$src$utils$promise$$;this.$I$=$deferred$jscomp$71$$.$promise$;this.$J$=$deferred$jscomp$71$$.resolve;return!0};_.$JSCompiler_prototypeAlias$$.$pauseCallback$=function(){this.$D$&&this.$D$.contentWindow&&this.pause()};
_.$JSCompiler_prototypeAlias$$.$mutatedAttributesCallback$=function($mutations$jscomp$28$$){null!=$mutations$jscomp$28$$["data-videoid"]&&(this.$F$=this.element.getAttribute("data-videoid"),this.$D$&&$JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$sendCommand_$$(this,"loadVideoById",[this.$F$]))};
_.$JSCompiler_prototypeAlias$$.$handleYoutubeMessage_$=function($$jscomp$compprop133_event$jscomp$268_eventData$jscomp$25_eventType$jscomp$70$$){if(_.$originMatches$$module$src$iframe_video$$($$jscomp$compprop133_event$jscomp$268_eventData$jscomp$25_eventType$jscomp$70$$,this.$D$,"https://www.youtube.com")&&($$jscomp$compprop133_event$jscomp$268_eventData$jscomp$25_eventType$jscomp$70$$=$$jscomp$compprop133_event$jscomp$268_eventData$jscomp$25_eventType$jscomp$70$$.data,_.$isJsonOrObj$$module$src$iframe_video$$($$jscomp$compprop133_event$jscomp$268_eventData$jscomp$25_eventType$jscomp$70$$))){var $data$jscomp$264_element$jscomp$781$$=
_.$objOrParseJson$$module$src$iframe_video$$($$jscomp$compprop133_event$jscomp$268_eventData$jscomp$25_eventType$jscomp$70$$);if(null!=$data$jscomp$264_element$jscomp$781$$){$$jscomp$compprop133_event$jscomp$268_eventData$jscomp$25_eventType$jscomp$70$$=$data$jscomp$264_element$jscomp$781$$.event;var $info$jscomp$19$$=$data$jscomp$264_element$jscomp$781$$.info||{};$data$jscomp$264_element$jscomp$781$$=this.element;var $muted$jscomp$5_playerState$jscomp$1$$=$info$jscomp$19$$.playerState;"infoDelivery"==
$$jscomp$compprop133_event$jscomp$268_eventData$jscomp$25_eventType$jscomp$70$$&&null!=$muted$jscomp$5_playerState$jscomp$1$$?($$jscomp$compprop133_event$jscomp$268_eventData$jscomp$25_eventType$jscomp$70$$={},_.$redispatch$$module$src$iframe_video$$($data$jscomp$264_element$jscomp$781$$,$muted$jscomp$5_playerState$jscomp$1$$.toString(),($$jscomp$compprop133_event$jscomp$268_eventData$jscomp$25_eventType$jscomp$70$$[1]=_.$VideoEvents$$module$src$video_interface$$.$PLAYING$,$$jscomp$compprop133_event$jscomp$268_eventData$jscomp$25_eventType$jscomp$70$$[2]=
_.$VideoEvents$$module$src$video_interface$$.$PAUSE$,$$jscomp$compprop133_event$jscomp$268_eventData$jscomp$25_eventType$jscomp$70$$[0]=[_.$VideoEvents$$module$src$video_interface$$.$ENDED$,_.$VideoEvents$$module$src$video_interface$$.$PAUSE$],$$jscomp$compprop133_event$jscomp$268_eventData$jscomp$25_eventType$jscomp$70$$))):($muted$jscomp$5_playerState$jscomp$1$$=$info$jscomp$19$$.muted,"infoDelivery"==$$jscomp$compprop133_event$jscomp$268_eventData$jscomp$25_eventType$jscomp$70$$&&$info$jscomp$19$$&&
null!=$muted$jscomp$5_playerState$jscomp$1$$?this.$H$!=$muted$jscomp$5_playerState$jscomp$1$$&&(this.$H$=$muted$jscomp$5_playerState$jscomp$1$$,$data$jscomp$264_element$jscomp$781$$.$dispatchCustomEvent$(_.$mutedOrUnmutedEvent$$module$src$iframe_video$$(this.$H$))):"initialDelivery"==$$jscomp$compprop133_event$jscomp$268_eventData$jscomp$25_eventType$jscomp$70$$?(this.$G$=$info$jscomp$19$$,$data$jscomp$264_element$jscomp$781$$.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$LOADEDMETADATA$)):
"infoDelivery"==$$jscomp$compprop133_event$jscomp$268_eventData$jscomp$25_eventType$jscomp$70$$&&void 0!==$info$jscomp$19$$.currentTime&&(this.$G$.currentTime=$info$jscomp$19$$.currentTime))}}};_.$JSCompiler_prototypeAlias$$.$supportsPlatform$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$isInteractive$=function(){return!0};_.$JSCompiler_prototypeAlias$$.play=function(){$JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$sendCommand_$$(this,"playVideo")};
_.$JSCompiler_prototypeAlias$$.pause=function(){$JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$sendCommand_$$(this,"pauseVideo")};_.$JSCompiler_prototypeAlias$$.$mute$=function(){$JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$sendCommand_$$(this,"mute")};
_.$JSCompiler_prototypeAlias$$.$unmute$=function(){$JSCompiler_StaticMethods_AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube_prototype$sendCommand_$$(this,"unMute")};_.$JSCompiler_prototypeAlias$$.$showControls$=function(){};_.$JSCompiler_prototypeAlias$$.$hideControls$=function(){};_.$JSCompiler_prototypeAlias$$.$fullscreenEnter$=function(){this.$D$&&_.$fullscreenEnter$$module$src$dom$$(this.$D$)};_.$JSCompiler_prototypeAlias$$.$fullscreenExit$=function(){this.$D$&&_.$fullscreenExit$$module$src$dom$$(this.$D$)};
_.$JSCompiler_prototypeAlias$$.getMetadata=function(){};_.$JSCompiler_prototypeAlias$$.$preimplementsMediaSessionAPI$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$preimplementsAutoFullscreen$=function(){return!1};_.$JSCompiler_prototypeAlias$$.$getCurrentTime$=function(){return this.$G$?this.$G$.currentTime:NaN};_.$JSCompiler_prototypeAlias$$.$getDuration$=function(){return this.$G$?this.$G$.duration:NaN};_.$JSCompiler_prototypeAlias$$.$getPlayedRanges$=function(){return[]};
_.$JSCompiler_prototypeAlias$$.$seekTo$=function(){this.$user$().error("amp-youtube","`seekTo` not supported.")};self.AMP.registerElement("amp-youtube",$AmpYoutube$$module$extensions$amp_youtube$0_1$amp_youtube$$);
})});

//# sourceMappingURL=amp-youtube-0.1.js.map
