(self.AMP=self.AMP||[]).push({n:"amp-fx-flying-carpet",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$$=function($$jscomp$super$this$jscomp$52_element$jscomp$482$$){$$jscomp$super$this$jscomp$52_element$jscomp$482$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$52_element$jscomp$482$$)||this;$$jscomp$super$this$jscomp$52_element$jscomp$482$$.$AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$children_$=[];$$jscomp$super$this$jscomp$52_element$jscomp$482$$.$D$=0;$$jscomp$super$this$jscomp$52_element$jscomp$482$$.$F$=
null;$$jscomp$super$this$jscomp$52_element$jscomp$482$$.$G$=!1;return $$jscomp$super$this$jscomp$52_element$jscomp$482$$},$JSCompiler_StaticMethods_visibileChildren_$$=function($nodes$jscomp$18$$){return $nodes$jscomp$18$$.filter(function($nodes$jscomp$18$$){return 1===$nodes$jscomp$18$$.nodeType?!0:3===$nodes$jscomp$18$$.nodeType?/\S/.test($nodes$jscomp$18$$.textContent):!1})};_.$$jscomp$inherits$$($AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$$.prototype;_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$68$$){return"fixed-height"==$layout$jscomp$68$$};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){var $$jscomp$this$jscomp$671$$=this,$clip_doc$jscomp$95$$=this.element.ownerDocument,$container$jscomp$18$$=$clip_doc$jscomp$95$$.createElement("div");this.$AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$children_$=this.$getRealChildren$();this.$F$=$container$jscomp$18$$;var $childNodes$$=this.$getRealChildNodes$();this.$D$=$JSCompiler_StaticMethods_visibileChildren_$$($childNodes$$).length;this.$AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$children_$.forEach(function($clip_doc$jscomp$95$$){_.$Resource$$module$src$service$resource$setOwner$$($clip_doc$jscomp$95$$,
$$jscomp$this$jscomp$671$$.element)});$clip_doc$jscomp$95$$=$clip_doc$jscomp$95$$.createElement("div");$clip_doc$jscomp$95$$.setAttribute("class","i-amphtml-fx-flying-carpet-clip");$container$jscomp$18$$.setAttribute("class","i-amphtml-fx-flying-carpet-container");$childNodes$$.forEach(function($$jscomp$this$jscomp$671$$){return $container$jscomp$18$$.appendChild($$jscomp$this$jscomp$671$$)});$clip_doc$jscomp$95$$.appendChild($container$jscomp$18$$);this.element.appendChild($clip_doc$jscomp$95$$);
_.$JSCompiler_StaticMethods_addToFixedLayer$$(this.$getViewport$(),$container$jscomp$18$$,!1)};
_.$JSCompiler_prototypeAlias$$.$onMeasureChanged$=function(){var $$jscomp$this$jscomp$672$$=this,$width$jscomp$62$$=this.$layoutWidth_$;this.$mutateElement$(function(){_.$setStyle$$module$src$style$$($$jscomp$this$jscomp$672$$.$F$,"width",$width$jscomp$62$$,"px")});this.$G$&&(this.$scheduleLayout$(this.$AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$children_$),_.$listen$$module$src$event_helper$$(this.element,"amp:built",this.$layoutBuiltChild_$.bind(this)))};
_.$JSCompiler_prototypeAlias$$.$viewportCallback$=function($inViewport$jscomp$18$$){this.$updateInViewport$(this.$AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$children_$,$inViewport$jscomp$18$$)};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){try{this.element.$getLayoutBox$(),_.$JSCompiler_StaticMethods_getHeight$$(this.$getViewport$())}catch($e$291$$){throw this.collapse(),$e$291$$;}this.$scheduleLayout$(this.$AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$children_$);_.$listen$$module$src$event_helper$$(this.element,"amp:built",this.$layoutBuiltChild_$.bind(this));this.$G$=!0;return Promise.resolve()};
_.$JSCompiler_prototypeAlias$$.$layoutBuiltChild_$=function($child$jscomp$22_event$jscomp$138$$){$child$jscomp$22_event$jscomp$138$$=$child$jscomp$22_event$jscomp$138$$.target;$child$jscomp$22_event$jscomp$138$$.$getOwner$()===this.element&&this.$scheduleLayout$($child$jscomp$22_event$jscomp$138$$)};
_.$JSCompiler_prototypeAlias$$.$collapsedCallback$=function($child$jscomp$23_index$jscomp$145$$){$child$jscomp$23_index$jscomp$145$$=this.$AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$children_$.indexOf($child$jscomp$23_index$jscomp$145$$);-1<$child$jscomp$23_index$jscomp$145$$&&(this.$AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$children_$.splice($child$jscomp$23_index$jscomp$145$$,1),this.$D$--,0==this.$D$&&this.$attemptCollapse$().catch(function(){}))};
self.AMP.registerElement("amp-fx-flying-carpet",$AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$$,"amp-fx-flying-carpet{position:relative!important;box-sizing:border-box!important}amp-fx-flying-carpet>.i-amphtml-fx-flying-carpet-clip{position:absolute!important;top:0!important;left:0!important;width:100%!important;height:100%!important;border:0!important;margin:0!important;padding:0!important;clip:rect(0,auto,auto,0)!important;-webkit-clip-path:polygon(0px 0px,100% 0px,100% 100%,0px 100%)!important;clip-path:polygon(0px 0px,100% 0px,100% 100%,0px 100%)!important}amp-fx-flying-carpet>.i-amphtml-fx-flying-carpet-clip>.i-amphtml-fx-flying-carpet-container{position:fixed!important;top:0!important;width:100%;height:100%;-webkit-transform:translateZ(0)!important;display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-ms-flex-direction:column;flex-direction:column;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:center;-ms-flex-pack:center;justify-content:center}.i-amphtml-fx-flying-carpet-container>.i-amphtml-layout-fixed-height,.i-amphtml-fx-flying-carpet-container>.i-amphtml-layout-responsive{-ms-flex-item-align:stretch;align-self:stretch}\n/*# sourceURL=/extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.css*/");
})});

//# sourceMappingURL=amp-fx-flying-carpet-0.1.js.map
