(self.AMP=self.AMP||[]).push({n:"amp-access-poool",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $PooolVendor$$module$extensions$amp_access_poool$0_1$poool_impl$$=function($accessService$jscomp$6$$,$accessSource$jscomp$2$$){this.ampdoc=$accessService$jscomp$6$$.ampdoc;this.$G$=$accessSource$jscomp$2$$;this.$K$=$ACCESS_CONFIG$$module$extensions$amp_access_poool$0_1$poool_impl$$.authorization;this.$M$=$ACCESS_CONFIG$$module$extensions$amp_access_poool$0_1$poool_impl$$.iframe;this.$H$=_.$Services$$module$src$services$timerFor$$(this.ampdoc.$win$);this.$I$=_.$Services$$module$src$services$xhrFor$$(this.ampdoc.$win$);
this.$F$=this.$G$.$getAdapterConfig$();this.$O$=this.$F$.itemID||"";this.$D$=document.createElement("iframe");this.$D$.setAttribute("id","poool-iframe");this.$D$.setAttribute("scrolling","no");this.$D$.setAttribute("frameborder","0");_.$setStyle$$module$src$style$$(this.$D$,"width","100%");"unlock"==this.$F$.forceWidget?_.$setStyles$$module$src$style$$(this.$D$,{height:"250px",position:"fixed",bottom:"0"}):_.$setStyles$$module$src$style$$(this.$D$,{height:"500px",transform:"translateY(-70px)"})},
$JSCompiler_StaticMethods_getPooolAccess_$$=function($JSCompiler_StaticMethods_getPooolAccess_$self$$){var $url$jscomp$126$$=_.$addParamToUrl$$module$src$url$$($JSCompiler_StaticMethods_getPooolAccess_$self$$.$K$,"iid",$JSCompiler_StaticMethods_getPooolAccess_$self$$.$O$);return $JSCompiler_StaticMethods_getPooolAccess_$self$$.$G$.$buildUrl$($url$jscomp$126$$,!1).then(function($url$jscomp$126$$){return $JSCompiler_StaticMethods_getPooolAccess_$self$$.$G$.$AccessSource$$module$extensions$amp_access$0_1$amp_access_source_prototype$getLoginUrl$($url$jscomp$126$$)}).then(function($url$jscomp$126$$){_.$dev$$module$src$log$$().$Log$$module$src$log_prototype$info$("amp-access-poool",
"Authorization URL: ",$url$jscomp$126$$);return _.$JSCompiler_StaticMethods_timeoutPromise$$($JSCompiler_StaticMethods_getPooolAccess_$self$$.$H$,3E3,_.$JSCompiler_StaticMethods_fetchJson$$($JSCompiler_StaticMethods_getPooolAccess_$self$$.$I$,$url$jscomp$126$$)).then(function($JSCompiler_StaticMethods_getPooolAccess_$self$$){return $JSCompiler_StaticMethods_getPooolAccess_$self$$.json()})})},$JSCompiler_StaticMethods_renderPoool_$$=function($JSCompiler_StaticMethods_renderPoool_$self$$){var $pooolContainer$$=
document.getElementById("poool");$JSCompiler_StaticMethods_renderPoool_$self$$.$G$.$buildUrl$(_.$addParamsToUrl$$module$src$url$$($JSCompiler_StaticMethods_renderPoool_$self$$.$M$,_.$dict$$module$src$utils$object$$({bi:$JSCompiler_StaticMethods_renderPoool_$self$$.$F$.bundleID,iid:$JSCompiler_StaticMethods_renderPoool_$self$$.$F$.itemID,ce:$JSCompiler_StaticMethods_renderPoool_$self$$.$F$.cookiesEnabled,d:"undefined"!==typeof $JSCompiler_StaticMethods_renderPoool_$self$$.$F$.debug&&null!==$JSCompiler_StaticMethods_renderPoool_$self$$.$F$.debug?
$JSCompiler_StaticMethods_renderPoool_$self$$.$F$.debug:_.$getMode$$module$src$mode$$().$development$||_.$getMode$$module$src$mode$$().localDev,fw:$JSCompiler_StaticMethods_renderPoool_$self$$.$F$.forceWidget,cs:$JSCompiler_StaticMethods_renderPoool_$self$$.$F$.customSegment})),!1).then(function($url$jscomp$129$$){$JSCompiler_StaticMethods_renderPoool_$self$$.$D$.src=$url$jscomp$129$$;_.$listenFor$$module$src$iframe_helper$$($JSCompiler_StaticMethods_renderPoool_$self$$.$D$,"release",$JSCompiler_StaticMethods_renderPoool_$self$$.$P$.bind($JSCompiler_StaticMethods_renderPoool_$self$$));
_.$listenFor$$module$src$iframe_helper$$($JSCompiler_StaticMethods_renderPoool_$self$$.$D$,"resize",$JSCompiler_StaticMethods_renderPoool_$self$$.$J$.bind($JSCompiler_StaticMethods_renderPoool_$self$$));$pooolContainer$$.appendChild($JSCompiler_StaticMethods_renderPoool_$self$$.$D$)})},$ACCESS_CONFIG$$module$extensions$amp_access_poool$0_1$poool_impl$$={authorization:"https://api.poool.fr/api/v2/amp/access?rid=READER_ID",iframe:"https://assets.poool.fr/amp.html?rid=READER_ID&c=CANONICAL_URL&o=AMPDOC_URL&r=DOCUMENT_REFERRER"};
$PooolVendor$$module$extensions$amp_access_poool$0_1$poool_impl$$.prototype.$authorize$=function(){var $$jscomp$this$jscomp$263$$=this;return $JSCompiler_StaticMethods_getPooolAccess_$$(this).then(function($$jscomp$this$jscomp$263$$){return{$access$:$$jscomp$this$jscomp$263$$.$access$}},function($err$jscomp$24$$){if(!$err$jscomp$24$$||!$err$jscomp$24$$.response)throw $err$jscomp$24$$;if(402!==$err$jscomp$24$$.response.status)throw $err$jscomp$24$$;$JSCompiler_StaticMethods_renderPoool_$$($$jscomp$this$jscomp$263$$);
return{$access$:!1}})};$PooolVendor$$module$extensions$amp_access_poool$0_1$poool_impl$$.prototype.$P$=function(){document.querySelector("[poool-access-preview]").setAttribute("amp-access-hide","");document.querySelector("[poool-access-content]").removeAttribute("amp-access-hide");_.$resetStyles$$module$src$style$$(this.$D$,["transform"])};$PooolVendor$$module$extensions$amp_access_poool$0_1$poool_impl$$.prototype.$J$=function($msg$$){_.$setStyle$$module$src$style$$(this.$D$,"height",$msg$$.height)};
$PooolVendor$$module$extensions$amp_access_poool$0_1$poool_impl$$.prototype.$AccessClientAdapter$$module$extensions$amp_access$0_1$amp_access_client_prototype$pingback$=function(){return Promise.resolve()};(function($AMP$jscomp$5$$){$AMP$jscomp$5$$.registerServiceForDoc("poool",function($AMP$jscomp$5$$){return _.$Services$$module$src$services$accessServiceForDoc$$($AMP$jscomp$5$$.$getHeadNode$()).then(function($AMP$jscomp$5$$){var $ampdoc$jscomp$113$$=$AMP$jscomp$5$$.$getVendorSource$("poool");$AMP$jscomp$5$$=new $PooolVendor$$module$extensions$amp_access_poool$0_1$poool_impl$$($AMP$jscomp$5$$,$ampdoc$jscomp$113$$);$ampdoc$jscomp$113$$.$D$.$registerVendor$($AMP$jscomp$5$$);return $AMP$jscomp$5$$})})})(self.AMP);
})});

//# sourceMappingURL=amp-access-poool-0.1.js.map
