(self.AMP=self.AMP||[]).push({n:"amp-smartlinks",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $getConfigOptions$$module$extensions$amp_smartlinks$0_1$linkmate_options$$=function($element$jscomp$617_linkSelector$jscomp$inline_4327$$){var $JSCompiler_temp_const$jscomp$943$$=$element$jscomp$617_linkSelector$jscomp$inline_4327$$.getAttribute("nrtv-account-name").toLowerCase(),$JSCompiler_temp_const$jscomp$942$$=!!$element$jscomp$617_linkSelector$jscomp$inline_4327$$.hasAttribute("linkmate"),$JSCompiler_temp_const$jscomp$941$$=!!$element$jscomp$617_linkSelector$jscomp$inline_4327$$.hasAttribute("exclusive-links");
var $JSCompiler_inline_result$jscomp$944_linkAttribute$jscomp$inline_4324$$=($JSCompiler_inline_result$jscomp$944_linkAttribute$jscomp$inline_4324$$=$element$jscomp$617_linkSelector$jscomp$inline_4327$$.getAttribute("link-attribute"))?$JSCompiler_inline_result$jscomp$944_linkAttribute$jscomp$inline_4324$$.toLowerCase():"href";$element$jscomp$617_linkSelector$jscomp$inline_4327$$=$element$jscomp$617_linkSelector$jscomp$inline_4327$$.getAttribute("link-selector");return{$nrtvSlug$:$JSCompiler_temp_const$jscomp$943$$,
$linkmateEnabled$:$JSCompiler_temp_const$jscomp$942$$,$exclusiveLinks$:$JSCompiler_temp_const$jscomp$941$$,$linkAttribute$:$JSCompiler_inline_result$jscomp$944_linkAttribute$jscomp$inline_4324$$,$linkSelector$:$element$jscomp$617_linkSelector$jscomp$inline_4327$$?$element$jscomp$617_linkSelector$jscomp$inline_4327$$.toLowerCase():"a"}},$Linkmate$$module$extensions$amp_smartlinks$0_1$linkmate$$=function($ampDoc$jscomp$26$$,$xhr$jscomp$14$$,$linkmateOptions$$){this.$H$=$ampDoc$jscomp$26$$;this.$J$=
$xhr$jscomp$14$$;this.$M$=$linkmateOptions$$.$exclusiveLinks$;this.$K$=$linkmateOptions$$.$publisherID$;this.$F$=$linkmateOptions$$.$linkAttribute$;this.$I$=this.$H$.getRootNode();this.$G$=this.$D$=null},$JSCompiler_StaticMethods_runLinkmate$$=function($JSCompiler_StaticMethods_runLinkmate$self$$,$anchorList$jscomp$8$$){var $syncMappedLinks$$=null,$anchorListChanged_asyncMappedLinks$$=$JSCompiler_StaticMethods_runLinkmate$self$$.$D$&&!_.$deepEquals$$module$src$json$$($JSCompiler_StaticMethods_runLinkmate$self$$.$D$,
$anchorList$jscomp$8$$);$JSCompiler_StaticMethods_runLinkmate$self$$.$G$&&$anchorListChanged_asyncMappedLinks$$&&($syncMappedLinks$$=$JSCompiler_StaticMethods_mapLinks_$$($JSCompiler_StaticMethods_runLinkmate$self$$));if(!$JSCompiler_StaticMethods_runLinkmate$self$$.$G$||$anchorListChanged_asyncMappedLinks$$)return $anchorListChanged_asyncMappedLinks$$=$JSCompiler_StaticMethods_postToLinkmate_$$($JSCompiler_StaticMethods_runLinkmate$self$$,$anchorList$jscomp$8$$).then(function($syncMappedLinks$$){$JSCompiler_StaticMethods_runLinkmate$self$$.$G$=
$syncMappedLinks$$.data[0].smart_links;$JSCompiler_StaticMethods_runLinkmate$self$$.$D$=$anchorList$jscomp$8$$;return $JSCompiler_StaticMethods_mapLinks_$$($JSCompiler_StaticMethods_runLinkmate$self$$)}),new _.$TwoStepsResponse$$module$extensions$amp_skimlinks$0_1$link_rewriter$two_steps_response$$($syncMappedLinks$$,$anchorListChanged_asyncMappedLinks$$);$JSCompiler_StaticMethods_runLinkmate$self$$.$D$=$anchorList$jscomp$8$$;return new _.$TwoStepsResponse$$module$extensions$amp_skimlinks$0_1$link_rewriter$two_steps_response$$($syncMappedLinks$$,
null)},$JSCompiler_StaticMethods_postToLinkmate_$$=function($JSCompiler_StaticMethods_postToLinkmate_$self$$,$anchorList$jscomp$9_linksPayload_payload$jscomp$20$$){$anchorList$jscomp$9_linksPayload_payload$jscomp$20$$=$JSCompiler_StaticMethods_buildLinksPayload_$$($JSCompiler_StaticMethods_postToLinkmate_$self$$,$anchorList$jscomp$9_linksPayload_payload$jscomp$20$$);$anchorList$jscomp$9_linksPayload_payload$jscomp$20$$=_.$dict$$module$src$utils$object$$({article:_.$dict$$module$src$utils$object$$({name:$JSCompiler_StaticMethods_postToLinkmate_$self$$.$I$.title||
null,url:$JSCompiler_StaticMethods_postToLinkmate_$self$$.$H$.$AmpDoc$$module$src$service$ampdoc_impl_prototype$getUrl$()}),links:$anchorList$jscomp$9_linksPayload_payload$jscomp$20$$});var $fetchUrl$$="https://api.narrativ.com/api/v1/publishers/.pub_id./linkmate/smart_links/".replace(".pub_id.",$JSCompiler_StaticMethods_postToLinkmate_$self$$.$K$.toString());return _.$JSCompiler_StaticMethods_fetchJson$$($JSCompiler_StaticMethods_postToLinkmate_$self$$.$J$,$fetchUrl$$,{method:"POST",ampCors:!1,headers:_.$dict$$module$src$utils$object$$({"Content-Type":"application/json"}),
body:$anchorList$jscomp$9_linksPayload_payload$jscomp$20$$}).then(function($JSCompiler_StaticMethods_postToLinkmate_$self$$){return $JSCompiler_StaticMethods_postToLinkmate_$self$$.json()})},$JSCompiler_StaticMethods_buildLinksPayload_$$=function($JSCompiler_StaticMethods_buildLinksPayload_$self$$,$anchorList$jscomp$10$$){var $postLinks$$=[];$anchorList$jscomp$10$$.forEach(function($anchorList$jscomp$10$$){var $anchor$jscomp$26_exclusive$$=$anchorList$jscomp$10$$.getAttribute($JSCompiler_StaticMethods_buildLinksPayload_$self$$.$F$);
/shop-links.co/.test($anchor$jscomp$26_exclusive$$)?/\?amp=true$/.test($anchor$jscomp$26_exclusive$$)||($anchorList$jscomp$10$$[$JSCompiler_StaticMethods_buildLinksPayload_$self$$.$F$]+="?amp=true"):/#donotlink$/.test($anchor$jscomp$26_exclusive$$)||($anchorList$jscomp$10$$=$JSCompiler_StaticMethods_buildLinksPayload_$self$$.$M$||/#locklink$/.test($anchor$jscomp$26_exclusive$$),$postLinks$$.push({raw_url:$anchor$jscomp$26_exclusive$$,exclusive_match_requested:$anchorList$jscomp$10$$}))});return $postLinks$$},
$JSCompiler_StaticMethods_mapLinks_$$=function($JSCompiler_StaticMethods_mapLinks_$self$$){var $mappings$$=[];$JSCompiler_StaticMethods_mapLinks_$self$$.$D$.forEach(function($anchor$jscomp$27$$){$JSCompiler_StaticMethods_mapLinks_$self$$.$G$.forEach(function($smartLink$$){$anchor$jscomp$27$$.getAttribute($JSCompiler_StaticMethods_mapLinks_$self$$.$F$)===$smartLink$$.url&&$smartLink$$.auction_id&&$mappings$$.push({anchor:$anchor$jscomp$27$$,$replacementUrl$:"https://shop-links.co/"+$smartLink$$.auction_id+
"/?amp=true"})})});return $mappings$$},$AmpSmartlinks$$module$extensions$amp_smartlinks$0_1$amp_smartlinks$$=function($$jscomp$super$this$jscomp$97_element$jscomp$623$$){$$jscomp$super$this$jscomp$97_element$jscomp$623$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$97_element$jscomp$623$$)||this;$$jscomp$super$this$jscomp$97_element$jscomp$623$$.$G$=null;$$jscomp$super$this$jscomp$97_element$jscomp$623$$.$F$=null;$$jscomp$super$this$jscomp$97_element$jscomp$623$$.$H$=null;$$jscomp$super$this$jscomp$97_element$jscomp$623$$.$K$=
null;$$jscomp$super$this$jscomp$97_element$jscomp$623$$.$D$=null;$$jscomp$super$this$jscomp$97_element$jscomp$623$$.$J$=null;$$jscomp$super$this$jscomp$97_element$jscomp$623$$.$I$=null;return $$jscomp$super$this$jscomp$97_element$jscomp$623$$},$JSCompiler_StaticMethods_runSmartlinks_$$=function($JSCompiler_StaticMethods_runSmartlinks_$self$$){$JSCompiler_StaticMethods_getLinkmateOptions_$$($JSCompiler_StaticMethods_runSmartlinks_$self$$).then(function($JSCompiler_inline_result$jscomp$5970_config$jscomp$91$$){$JSCompiler_StaticMethods_runSmartlinks_$self$$.$D$.$linkmateExpected$=
$JSCompiler_inline_result$jscomp$5970_config$jscomp$91$$.linkmate_enabled;$JSCompiler_StaticMethods_runSmartlinks_$self$$.$D$.$publisherID$=$JSCompiler_inline_result$jscomp$5970_config$jscomp$91$$.publisher_id;$JSCompiler_StaticMethods_runSmartlinks_$self$$.signals().signal("load-start");$JSCompiler_inline_result$jscomp$5970_config$jscomp$91$$=_.$dict$$module$src$utils$object$$({events:[{is_amp:!0}],organization_id:$JSCompiler_StaticMethods_runSmartlinks_$self$$.$D$.$publisherID$,organization_type:"publisher",
user:{page_session_uuid:$JSCompiler_StaticMethods_generateUUID_$$(),source_url:$JSCompiler_StaticMethods_runSmartlinks_$self$$.$F$.$AmpDoc$$module$src$service$ampdoc_impl_prototype$getUrl$(),previous_url:$JSCompiler_StaticMethods_runSmartlinks_$self$$.$I$,user_agent:$JSCompiler_StaticMethods_runSmartlinks_$self$$.$F$.$win$.navigator.userAgent}});var $builder$jscomp$inline_4331$$=new _.$CustomEventReporterBuilder$$module$src$extension_analytics$$($JSCompiler_StaticMethods_runSmartlinks_$self$$.element);
$builder$jscomp$inline_4331$$.track("page-impression","https://api.narrativ.com/api/v1/events/impressions/page_impression/");$builder$jscomp$inline_4331$$.$D$.transport=_.$dict$$module$src$utils$object$$({beacon:!0,image:!1,xhrpost:!0,useBody:!0});$builder$jscomp$inline_4331$$.$D$.extraUrlParams=$JSCompiler_inline_result$jscomp$5970_config$jscomp$91$$;$builder$jscomp$inline_4331$$.$build$().$trigger$("page-impression");$JSCompiler_StaticMethods_runSmartlinks_$self$$.$J$=new $Linkmate$$module$extensions$amp_smartlinks$0_1$linkmate$$($JSCompiler_StaticMethods_runSmartlinks_$self$$.$F$,
$JSCompiler_StaticMethods_runSmartlinks_$self$$.$G$,$JSCompiler_StaticMethods_runSmartlinks_$self$$.$D$);$JSCompiler_StaticMethods_runSmartlinks_$self$$.$K$=$JSCompiler_StaticMethods_initLinkRewriter_$$($JSCompiler_StaticMethods_runSmartlinks_$self$$);$JSCompiler_StaticMethods_runSmartlinks_$self$$.$D$.$linkmateEnabled$&&$JSCompiler_StaticMethods_runSmartlinks_$self$$.$D$.$linkmateExpected$&&_.$JSCompiler_StaticMethods_LinkReplacementCache$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_replacement_cache_prototype$getAnchorReplacementList$$($JSCompiler_StaticMethods_runSmartlinks_$self$$.$K$.$D$)})},
$JSCompiler_StaticMethods_getLinkmateOptions_$$=function($JSCompiler_StaticMethods_getLinkmateOptions_$self$$){var $fetchUrl$jscomp$1$$="https://api.narrativ.com/api/v0/publishers/.nrtv_slug./amp_config/".replace(".nrtv_slug.",$JSCompiler_StaticMethods_getLinkmateOptions_$self$$.$D$.$nrtvSlug$);try{return _.$JSCompiler_StaticMethods_fetchJson$$($JSCompiler_StaticMethods_getLinkmateOptions_$self$$.$G$,$fetchUrl$jscomp$1$$,{method:"GET",ampCors:!1}).then(function($JSCompiler_StaticMethods_getLinkmateOptions_$self$$){return $JSCompiler_StaticMethods_getLinkmateOptions_$self$$.json()}).then(function($JSCompiler_StaticMethods_getLinkmateOptions_$self$$){return $JSCompiler_StaticMethods_getLinkmateOptions_$self$$.data[0].amp_config})}catch($err$jscomp$43$$){return null}},
$JSCompiler_StaticMethods_initLinkRewriter_$$=function($JSCompiler_StaticMethods_initLinkRewriter_$self$$){return _.$JSCompiler_StaticMethods_registerLinkRewriter$$($JSCompiler_StaticMethods_initLinkRewriter_$self$$.$H$,"amp-smartlinks",function($anchorList$jscomp$11$$){return $JSCompiler_StaticMethods_runLinkmate$$($JSCompiler_StaticMethods_initLinkRewriter_$self$$.$J$,$anchorList$jscomp$11$$)},{$linkSelector$:$JSCompiler_StaticMethods_initLinkRewriter_$self$$.$D$.$linkSelector$})},$JSCompiler_StaticMethods_generateUUID_$$=
function(){return"10000000-1000-4000-8000-100000000000".replace(/[018]/g,function($c$jscomp$175$$){return($c$jscomp$175$$^crypto.getRandomValues(new Uint8Array(1))[0]&15>>$c$jscomp$175$$/4).toString(16)})};_.$$jscomp$inherits$$($AmpSmartlinks$$module$extensions$amp_smartlinks$0_1$amp_smartlinks$$,AMP.BaseElement);
$AmpSmartlinks$$module$extensions$amp_smartlinks$0_1$amp_smartlinks$$.prototype.$buildCallback$=function(){var $$jscomp$this$jscomp$905$$=this;this.$F$=this.$getAmpDoc$();this.$G$=_.$Services$$module$src$services$xhrFor$$(this.$F$.$win$);var $viewer$jscomp$50$$=_.$Services$$module$src$services$viewerForDoc$$(this.$F$);this.$D$=$getConfigOptions$$module$extensions$amp_smartlinks$0_1$linkmate_options$$(this.element);this.$H$=new _.$LinkRewriterManager$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_rewriter_manager$$(this.$F$);
return this.$F$.$whenBodyAvailable$().then(function(){return $viewer$jscomp$50$$.$I$}).then(function($referrer$jscomp$19$$){$$jscomp$this$jscomp$905$$.$I$=$referrer$jscomp$19$$;$viewer$jscomp$50$$.$D$.then(function(){$JSCompiler_StaticMethods_runSmartlinks_$$($$jscomp$this$jscomp$905$$)})})};self.AMP.registerElement("amp-smartlinks",$AmpSmartlinks$$module$extensions$amp_smartlinks$0_1$amp_smartlinks$$);
})});

//# sourceMappingURL=amp-smartlinks-0.1.js.map
