(self.AMP=self.AMP||[]).push({n:"amp-ooyala-player",i:["_base_i","_base_media"],v:"1904281823091",f:(function(AMP,_){
var $AmpOoyalaPlayer$$module$extensions$amp_ooyala_player$0_1$amp_ooyala_player$$=function($$jscomp$super$this$jscomp$82_element$jscomp$577$$){$$jscomp$super$this$jscomp$82_element$jscomp$577$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$82_element$jscomp$577$$)||this;$$jscomp$super$this$jscomp$82_element$jscomp$577$$.$D$=null;$$jscomp$super$this$jscomp$82_element$jscomp$577$$.$J$="";$$jscomp$super$this$jscomp$82_element$jscomp$577$$.$K$="";$$jscomp$super$this$jscomp$82_element$jscomp$577$$.$I$=
"";$$jscomp$super$this$jscomp$82_element$jscomp$577$$.$F$=null;$$jscomp$super$this$jscomp$82_element$jscomp$577$$.$G$=null;$$jscomp$super$this$jscomp$82_element$jscomp$577$$.$H$=null;return $$jscomp$super$this$jscomp$82_element$jscomp$577$$},$JSCompiler_StaticMethods_AmpOoyalaPlayer$$module$extensions$amp_ooyala_player$0_1$amp_ooyala_player_prototype$sendCommand_$$=function($JSCompiler_StaticMethods_AmpOoyalaPlayer$$module$extensions$amp_ooyala_player$0_1$amp_ooyala_player_prototype$sendCommand_$self$$,
$command$jscomp$7$$){$JSCompiler_StaticMethods_AmpOoyalaPlayer$$module$extensions$amp_ooyala_player$0_1$amp_ooyala_player_prototype$sendCommand_$self$$.$F$.then(function(){$JSCompiler_StaticMethods_AmpOoyalaPlayer$$module$extensions$amp_ooyala_player$0_1$amp_ooyala_player_prototype$sendCommand_$self$$.$D$&&$JSCompiler_StaticMethods_AmpOoyalaPlayer$$module$extensions$amp_ooyala_player$0_1$amp_ooyala_player_prototype$sendCommand_$self$$.$D$.contentWindow&&$JSCompiler_StaticMethods_AmpOoyalaPlayer$$module$extensions$amp_ooyala_player$0_1$amp_ooyala_player_prototype$sendCommand_$self$$.$D$.contentWindow.postMessage($command$jscomp$7$$,
"*")})};_.$$jscomp$inherits$$($AmpOoyalaPlayer$$module$extensions$amp_ooyala_player$0_1$amp_ooyala_player$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpOoyalaPlayer$$module$extensions$amp_ooyala_player$0_1$amp_ooyala_player$$.prototype;_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($opt_onLayout$jscomp$24$$){this.$preconnect$.url("https://player.ooyala.com",$opt_onLayout$jscomp$24$$)};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){var $el$jscomp$79$$=this.element;this.$J$=$el$jscomp$79$$.getAttribute("data-embedcode");this.$K$=$el$jscomp$79$$.getAttribute("data-pcode");this.$I$=$el$jscomp$79$$.getAttribute("data-playerid");var $deferred$jscomp$52$$=new _.$Deferred$$module$src$utils$promise$$;this.$F$=$deferred$jscomp$52$$.$promise$;this.$G$=$deferred$jscomp$52$$.resolve;_.$installVideoManagerForDoc$$module$src$service$video_manager_impl$$($el$jscomp$79$$);_.$Services$$module$src$services$videoManagerForDoc$$($el$jscomp$79$$).register(this)};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $$jscomp$this$jscomp$833$$=this,$el$jscomp$80$$=this.element,$loaded$jscomp$3_src$jscomp$62$$="https://player.ooyala.com/iframe.html?platform=html5-priority";if("v4"==($el$jscomp$80$$.getAttribute("data-playerversion")||"").toLowerCase()){$loaded$jscomp$3_src$jscomp$62$$="https://player.ooyala.com/static/v4/sandbox/amp_iframe/skin-plugin/amp_iframe.html?pcode="+encodeURIComponent(this.$K$);var $configUrl$jscomp$1$$=$el$jscomp$80$$.getAttribute("data-config");
$configUrl$jscomp$1$$&&($loaded$jscomp$3_src$jscomp$62$$+="&options[skin.config]="+encodeURIComponent($configUrl$jscomp$1$$))}$loaded$jscomp$3_src$jscomp$62$$+="&ec="+encodeURIComponent(this.$J$)+"&pbid="+encodeURIComponent(this.$I$);this.$D$=_.$createFrameFor$$module$src$iframe_video$$(this,$loaded$jscomp$3_src$jscomp$62$$);this.$H$=_.$listen$$module$src$event_helper$$(this.$win$,"message",function($el$jscomp$80$$){$el$jscomp$80$$.source==$$jscomp$this$jscomp$833$$.$D$.contentWindow&&($el$jscomp$80$$=
_.$objOrParseJson$$module$src$iframe_video$$($el$jscomp$80$$.data),void 0!==$el$jscomp$80$$&&_.$redispatch$$module$src$iframe_video$$($$jscomp$this$jscomp$833$$.element,$el$jscomp$80$$.data,{playing:_.$VideoEvents$$module$src$video_interface$$.$PLAYING$,paused:_.$VideoEvents$$module$src$video_interface$$.$PAUSE$,muted:_.$VideoEvents$$module$src$video_interface$$.$MUTED$,unmuted:_.$VideoEvents$$module$src$video_interface$$.$UNMUTED$}))});$loaded$jscomp$3_src$jscomp$62$$=this.$loadPromise$(this.$D$).then(function(){$el$jscomp$80$$.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$LOAD$)});
this.$G$($loaded$jscomp$3_src$jscomp$62$$);return $loaded$jscomp$3_src$jscomp$62$$};_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$D$=null);this.$H$&&this.$H$();var $deferred$jscomp$53$$=new _.$Deferred$$module$src$utils$promise$$;this.$F$=$deferred$jscomp$53$$.$promise$;this.$G$=$deferred$jscomp$53$$.resolve;return!0};_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$91$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$91$$)};
_.$JSCompiler_prototypeAlias$$.$viewportCallback$=function($visible$jscomp$12$$){this.element.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$VISIBILITY$,{visible:$visible$jscomp$12$$})};_.$JSCompiler_prototypeAlias$$.$pauseCallback$=function(){this.$D$&&this.pause()};_.$JSCompiler_prototypeAlias$$.play=function(){$JSCompiler_StaticMethods_AmpOoyalaPlayer$$module$extensions$amp_ooyala_player$0_1$amp_ooyala_player_prototype$sendCommand_$$(this,"play")};
_.$JSCompiler_prototypeAlias$$.pause=function(){$JSCompiler_StaticMethods_AmpOoyalaPlayer$$module$extensions$amp_ooyala_player$0_1$amp_ooyala_player_prototype$sendCommand_$$(this,"pause")};_.$JSCompiler_prototypeAlias$$.$mute$=function(){$JSCompiler_StaticMethods_AmpOoyalaPlayer$$module$extensions$amp_ooyala_player$0_1$amp_ooyala_player_prototype$sendCommand_$$(this,"mute")};
_.$JSCompiler_prototypeAlias$$.$unmute$=function(){$JSCompiler_StaticMethods_AmpOoyalaPlayer$$module$extensions$amp_ooyala_player$0_1$amp_ooyala_player_prototype$sendCommand_$$(this,"unmute")};_.$JSCompiler_prototypeAlias$$.$supportsPlatform$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$isInteractive$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$showControls$=function(){};_.$JSCompiler_prototypeAlias$$.$hideControls$=function(){};
_.$JSCompiler_prototypeAlias$$.$fullscreenEnter$=function(){this.$D$&&_.$fullscreenEnter$$module$src$dom$$(this.$D$)};_.$JSCompiler_prototypeAlias$$.$fullscreenExit$=function(){this.$D$&&_.$fullscreenExit$$module$src$dom$$(this.$D$)};_.$JSCompiler_prototypeAlias$$.getMetadata=function(){};_.$JSCompiler_prototypeAlias$$.$preimplementsMediaSessionAPI$=function(){return!1};_.$JSCompiler_prototypeAlias$$.$preimplementsAutoFullscreen$=function(){return!1};
_.$JSCompiler_prototypeAlias$$.$getCurrentTime$=function(){return 0};_.$JSCompiler_prototypeAlias$$.$getDuration$=function(){return 1};_.$JSCompiler_prototypeAlias$$.$getPlayedRanges$=function(){return[]};_.$JSCompiler_prototypeAlias$$.$seekTo$=function(){this.$user$().error("amp-ooyala-player","`seekTo` not supported.")};self.AMP.registerElement("amp-ooyala-player",$AmpOoyalaPlayer$$module$extensions$amp_ooyala_player$0_1$amp_ooyala_player$$);
})});

//# sourceMappingURL=amp-ooyala-player-0.1.js.map
