(self.AMP=self.AMP||[]).push({n:"amp-ima-video",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $ImaPlayerData$$module$ads$google$ima_player_data$$=function(){this.currentTime=0;this.duration=1;this.$playedRanges$=[]},$AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video$$=function($$jscomp$super$this$jscomp$61_element$jscomp$498$$){$$jscomp$super$this$jscomp$61_element$jscomp$498$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$61_element$jscomp$498$$)||this;$$jscomp$super$this$jscomp$61_element$jscomp$498$$.$D$=null;$$jscomp$super$this$jscomp$61_element$jscomp$498$$.$O$=
null;$$jscomp$super$this$jscomp$61_element$jscomp$498$$.$F$=null;$$jscomp$super$this$jscomp$61_element$jscomp$498$$.$J$=null;$$jscomp$super$this$jscomp$61_element$jscomp$498$$.$K$=null;$$jscomp$super$this$jscomp$61_element$jscomp$498$$.$H$=null;$$jscomp$super$this$jscomp$61_element$jscomp$498$$.$I$=null;$$jscomp$super$this$jscomp$61_element$jscomp$498$$.$P$=!1;$$jscomp$super$this$jscomp$61_element$jscomp$498$$.$M$={};$$jscomp$super$this$jscomp$61_element$jscomp$498$$.$G$=new $ImaPlayerData$$module$ads$google$ima_player_data$$;
return $$jscomp$super$this$jscomp$61_element$jscomp$498$$},$JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$$=function($JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$self$$,$command$jscomp$4$$,$opt_args$jscomp$16$$){$JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$self$$.$D$&&$JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$self$$.$D$.contentWindow&&
$JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$self$$.$F$.then(function(){$JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$self$$.$D$.contentWindow.postMessage(JSON.stringify(_.$dict$$module$src$utils$object$$({event:"command",func:$command$jscomp$4$$,args:$opt_args$jscomp$16$$||""})),"*")});if($JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$self$$.$M$[$command$jscomp$4$$])$JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$self$$.$M$[$command$jscomp$4$$]()};
$ImaPlayerData$$module$ads$google$ima_player_data$$.prototype.update=function($played_videoPlayer$$){this.currentTime=$played_videoPlayer$$.currentTime;this.duration=$played_videoPlayer$$.duration;$played_videoPlayer$$=$played_videoPlayer$$.played;var $length$jscomp$42$$=$played_videoPlayer$$.length;this.$playedRanges$=[];for(var $i$jscomp$336$$=0;$i$jscomp$336$$<$length$jscomp$42$$;$i$jscomp$336$$++)this.$playedRanges$.push([$played_videoPlayer$$.start($i$jscomp$336$$),$played_videoPlayer$$.end($i$jscomp$336$$)])};_.$$jscomp$inherits$$($AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video$$.prototype;
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){var $$jscomp$this$jscomp$687$$=this;this.$O$=this.$getViewport$();"true"===this.element.getAttribute("data-delay-ad-request")&&(this.$M$.onFirstScroll=_.$JSCompiler_StaticMethods_Viewport$$module$src$service$viewport$viewport_impl_prototype$onScroll$$(this.$O$,function(){$JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$$($$jscomp$this$jscomp$687$$,"onFirstScroll")}),_.$Services$$module$src$services$timerFor$$(this.$win$).delay(function(){$JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$$($$jscomp$this$jscomp$687$$,
"onAdRequestDelayTimeout")},3E3));this.element.getAttribute("data-tag");var $childElements_scriptElement$jscomp$3_sourceElements$$=_.$childElementsByTag$$module$src$dom$$(this.element,"SOURCE"),$trackElements$$=_.$childElementsByTag$$module$src$dom$$(this.element,"TRACK");$childElements_scriptElement$jscomp$3_sourceElements$$=_.$toArray$$module$src$types$$($childElements_scriptElement$jscomp$3_sourceElements$$).concat(_.$toArray$$module$src$types$$($trackElements$$));if(0<$childElements_scriptElement$jscomp$3_sourceElements$$.length){var $children$jscomp$140$$=
[];$childElements_scriptElement$jscomp$3_sourceElements$$.forEach(function($childElements_scriptElement$jscomp$3_sourceElements$$){"SOURCE"!=$childElements_scriptElement$jscomp$3_sourceElements$$.tagName||$$jscomp$this$jscomp$687$$.$H$?"TRACK"!=$childElements_scriptElement$jscomp$3_sourceElements$$.tagName||$$jscomp$this$jscomp$687$$.$I$||($$jscomp$this$jscomp$687$$.$I$=$childElements_scriptElement$jscomp$3_sourceElements$$.src):$$jscomp$this$jscomp$687$$.$H$=$childElements_scriptElement$jscomp$3_sourceElements$$.src;
$children$jscomp$140$$.push($childElements_scriptElement$jscomp$3_sourceElements$$.outerHTML)});this.element.setAttribute("data-child-elements",JSON.stringify($children$jscomp$140$$))}($childElements_scriptElement$jscomp$3_sourceElements$$=_.$childElementsByTag$$module$src$dom$$(this.element,"SCRIPT")[0])&&_.$isJsonScriptTag$$module$src$dom$$($childElements_scriptElement$jscomp$3_sourceElements$$)&&this.element.setAttribute("data-ima-settings",$childElements_scriptElement$jscomp$3_sourceElements$$.innerHTML)};
_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function(){var $element$jscomp$499$$=this.element,$preconnect$jscomp$4$$=this.$preconnect$;$preconnect$jscomp$4$$.preload("https://imasdk.googleapis.com/js/sdkloader/ima3.js","script");var $source$jscomp$41$$=$element$jscomp$499$$.getAttribute("data-src");$source$jscomp$41$$&&$preconnect$jscomp$4$$.url($source$jscomp$41$$);this.$H$&&$preconnect$jscomp$4$$.url(this.$H$);this.$I$&&$preconnect$jscomp$4$$.url(this.$I$);$preconnect$jscomp$4$$.url($element$jscomp$499$$.getAttribute("data-tag"));
_.$preloadBootstrap$$module$src$3p_frame$$(this.$win$,$preconnect$jscomp$4$$)};_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$75$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$75$$)};_.$JSCompiler_prototypeAlias$$.$getConsentPolicy$=function(){return null};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $$jscomp$this$jscomp$688$$=this,$element$jscomp$500$$=this.element,$win$jscomp$363$$=this.$win$,$consentPolicyId$jscomp$4$$=AMP.BaseElement.prototype.$getConsentPolicy$.call(this);return($consentPolicyId$jscomp$4$$?_.$getConsentPolicyState$$module$src$consent$$($element$jscomp$500$$,$consentPolicyId$jscomp$4$$):Promise.resolve(null)).then(function($consentPolicyId$jscomp$4$$){$consentPolicyId$jscomp$4$$=_.$getIframe$$module$src$3p_frame$$($win$jscomp$363$$,
$element$jscomp$500$$,"ima-video",{initialConsentState:$consentPolicyId$jscomp$4$$},{$allowFullscreen$:!0});_.$JSCompiler_StaticMethods_applyFillContent$$($consentPolicyId$jscomp$4$$);_.$addUnsafeAllowAutoplay$$module$src$iframe_video$$($consentPolicyId$jscomp$4$$);$$jscomp$this$jscomp$688$$.$D$=$consentPolicyId$jscomp$4$$;var $iframe$jscomp$62_initialConsentState$$=new _.$Deferred$$module$src$utils$promise$$;$$jscomp$this$jscomp$688$$.$F$=$iframe$jscomp$62_initialConsentState$$.$promise$;$$jscomp$this$jscomp$688$$.$J$=
$iframe$jscomp$62_initialConsentState$$.resolve;$$jscomp$this$jscomp$688$$.$K$=_.$listen$$module$src$event_helper$$($$jscomp$this$jscomp$688$$.$win$,"message",function($element$jscomp$500$$){if($element$jscomp$500$$.source==$$jscomp$this$jscomp$688$$.$D$.contentWindow&&($element$jscomp$500$$=$element$jscomp$500$$.data,_.$isObject$$module$src$types$$($element$jscomp$500$$))){var $win$jscomp$363$$=$element$jscomp$500$$.event;_.$isEnumValue$$module$src$types$$(_.$VideoEvents$$module$src$video_interface$$,
$win$jscomp$363$$)?($win$jscomp$363$$==_.$VideoEvents$$module$src$video_interface$$.$LOAD$&&$$jscomp$this$jscomp$688$$.$J$($$jscomp$this$jscomp$688$$.$D$),$$jscomp$this$jscomp$688$$.element.$dispatchCustomEvent$($win$jscomp$363$$)):"imaPlayerData"==$win$jscomp$363$$?$$jscomp$this$jscomp$688$$.$G$=$element$jscomp$500$$.data:"fullscreenchange"==$win$jscomp$363$$&&($$jscomp$this$jscomp$688$$.$P$=!!$element$jscomp$500$$.isFullscreen)}});$element$jscomp$500$$.appendChild($consentPolicyId$jscomp$4$$);_.$installVideoManagerForDoc$$module$src$service$video_manager_impl$$($element$jscomp$500$$);
_.$Services$$module$src$services$videoManagerForDoc$$($element$jscomp$500$$).register($$jscomp$this$jscomp$688$$);return $$jscomp$this$jscomp$688$$.$loadPromise$($consentPolicyId$jscomp$4$$).then(function(){return $$jscomp$this$jscomp$688$$.$F$})})};_.$JSCompiler_prototypeAlias$$.$viewportCallback$=function($visible$jscomp$8$$){this.element.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$VISIBILITY$,{visible:$visible$jscomp$8$$})};
_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$D$=null);this.$K$&&this.$K$();var $deferred$jscomp$46$$=new _.$Deferred$$module$src$utils$promise$$;this.$F$=$deferred$jscomp$46$$.$promise$;this.$J$=$deferred$jscomp$46$$.resolve;return!0};
_.$JSCompiler_prototypeAlias$$.$onLayoutMeasure$=function(){if(this.$D$){var $$jscomp$destructuring$var499$$=this.$getLayoutBox$();$JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$$(this,"resize",{width:$$jscomp$destructuring$var499$$.width,height:$$jscomp$destructuring$var499$$.height})}};_.$JSCompiler_prototypeAlias$$.$supportsPlatform$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$isInteractive$=function(){return!0};
_.$JSCompiler_prototypeAlias$$.play=function(){$JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$$(this,"playVideo")};_.$JSCompiler_prototypeAlias$$.pause=function(){$JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$$(this,"pauseVideo")};
_.$JSCompiler_prototypeAlias$$.$mute$=function(){$JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$$(this,"mute")};_.$JSCompiler_prototypeAlias$$.$unmute$=function(){$JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$$(this,"unMute")};
_.$JSCompiler_prototypeAlias$$.$showControls$=function(){$JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$$(this,"showControls")};_.$JSCompiler_prototypeAlias$$.$hideControls$=function(){$JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$$(this,"hideControls")};
_.$JSCompiler_prototypeAlias$$.$fullscreenEnter$=function(){$JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$$(this,"enterFullscreen")};_.$JSCompiler_prototypeAlias$$.$fullscreenExit$=function(){$JSCompiler_StaticMethods_AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video_prototype$sendCommand_$$(this,"exitFullscreen")};_.$JSCompiler_prototypeAlias$$.getMetadata=function(){};
_.$JSCompiler_prototypeAlias$$.$preimplementsMediaSessionAPI$=function(){return!1};_.$JSCompiler_prototypeAlias$$.$preimplementsAutoFullscreen$=function(){return!1};_.$JSCompiler_prototypeAlias$$.$getCurrentTime$=function(){return this.$G$.currentTime};_.$JSCompiler_prototypeAlias$$.$getDuration$=function(){return this.$G$.duration};_.$JSCompiler_prototypeAlias$$.$getPlayedRanges$=function(){return this.$G$.$playedRanges$};
_.$JSCompiler_prototypeAlias$$.$seekTo$=function(){this.$user$().error("amp-ima-video","`seekTo` not supported.")};self.AMP.registerElement("amp-ima-video",$AmpImaVideo$$module$extensions$amp_ima_video$0_1$amp_ima_video$$);
})});

//# sourceMappingURL=amp-ima-video-0.1.js.map
