(self.AMP=self.AMP||[]).push({n:"amp-facebook-like",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $AmpFacebookLike$$module$extensions$amp_facebook_like$0_1$amp_facebook_like$$=function($element$jscomp$436$$){var $$jscomp$super$this$jscomp$47$$=AMP.BaseElement.call(this,$element$jscomp$436$$)||this;$$jscomp$super$this$jscomp$47$$.$D$=null;$$jscomp$super$this$jscomp$47$$.$G$=$element$jscomp$436$$.hasAttribute("data-locale")?$element$jscomp$436$$.getAttribute("data-locale"):_.$dashToUnderline$$module$src$string$$();$$jscomp$super$this$jscomp$47$$.$F$=null;return $$jscomp$super$this$jscomp$47$$};
_.$$jscomp$inherits$$($AmpFacebookLike$$module$extensions$amp_facebook_like$0_1$amp_facebook_like$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpFacebookLike$$module$extensions$amp_facebook_like$0_1$amp_facebook_like$$.prototype;_.$JSCompiler_prototypeAlias$$.$renderOutsideViewport$=function(){return.75};
_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($opt_onLayout$jscomp$13$$){this.$preconnect$.url("https://facebook.com",$opt_onLayout$jscomp$13$$);this.$preconnect$.preload("https://connect.facebook.net/"+this.$G$+"/sdk.js","script");_.$preloadBootstrap$$module$src$3p_frame$$(this.$win$,this.$preconnect$)};_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$64$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$64$$)};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $$jscomp$this$jscomp$629$$=this,$iframe$jscomp$50$$=_.$getIframe$$module$src$3p_frame$$(this.$win$,this.element,"facebook");_.$JSCompiler_StaticMethods_applyFillContent$$($iframe$jscomp$50$$);_.$listenFor$$module$src$iframe_helper$$($iframe$jscomp$50$$,"embed-size",function($iframe$jscomp$50$$){_.$JSCompiler_StaticMethods_attemptChangeHeight$$($$jscomp$this$jscomp$629$$,$iframe$jscomp$50$$.height).catch(function(){})},!0);this.$F$=_.$listen$$module$src$event_helper$$(this.$win$,
"message",this.$AmpFacebookLike$$module$extensions$amp_facebook_like$0_1$amp_facebook_like_prototype$handleFacebookMessages_$.bind(this));this.$toggleLoading$(!0);this.element.appendChild($iframe$jscomp$50$$);this.$D$=$iframe$jscomp$50$$;return this.$loadPromise$($iframe$jscomp$50$$)};
_.$JSCompiler_prototypeAlias$$.$AmpFacebookLike$$module$extensions$amp_facebook_like$0_1$amp_facebook_like_prototype$handleFacebookMessages_$=function($event$jscomp$123_eventData$jscomp$8$$){this.$D$&&$event$jscomp$123_eventData$jscomp$8$$.source!=this.$D$.contentWindow||($event$jscomp$123_eventData$jscomp$8$$=$event$jscomp$123_eventData$jscomp$8$$.data)&&(_.$isObject$$module$src$types$$($event$jscomp$123_eventData$jscomp$8$$)?$event$jscomp$123_eventData$jscomp$8$$:_.$tryParseJson$$module$src$json$$($event$jscomp$123_eventData$jscomp$8$$))&&
"ready"==$event$jscomp$123_eventData$jscomp$8$$.action&&this.$toggleLoading$(!1)};_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$D$=null);this.$F$&&this.$F$();return!0};self.AMP.registerElement("amp-facebook-like",$AmpFacebookLike$$module$extensions$amp_facebook_like$0_1$amp_facebook_like$$);
})});

//# sourceMappingURL=amp-facebook-like-0.1.js.map
