(self.AMP=self.AMP||[]).push({n:"amp-dynamic-css-classes",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $referrers_$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$=function($referrer$jscomp$9$$){var $domainBase$$="";return $referrer$jscomp$9$$.split(".").reduceRight(function($referrer$jscomp$9$$,$domain$jscomp$9$$){$domainBase$$&&($domain$jscomp$9$$+="."+$domainBase$$);$domainBase$$=$domain$jscomp$9$$;$referrer$jscomp$9$$.push($domain$jscomp$9$$);return $referrer$jscomp$9$$},[])},$normalizedReferrers$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$=
function($ampdoc$jscomp$174$$){var $JSCompiler_inline_result$jscomp$825_referrer$jscomp$inline_3382$$=($JSCompiler_inline_result$jscomp$825_referrer$jscomp$inline_3382$$=_.$Services$$module$src$services$viewerForDoc$$($ampdoc$jscomp$174$$).$V$)?_.$Services$$module$src$services$urlForDoc$$($ampdoc$jscomp$174$$.$getHeadNode$()).parse($JSCompiler_inline_result$jscomp$825_referrer$jscomp$inline_3382$$).hostname:"";return"t.co"===$JSCompiler_inline_result$jscomp$825_referrer$jscomp$inline_3382$$?$referrers_$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$("twitter.com"):
!$JSCompiler_inline_result$jscomp$825_referrer$jscomp$inline_3382$$&&/Pinterest/.test($ampdoc$jscomp$174$$.$win$.navigator.userAgent)?$referrers_$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$("www.pinterest.com"):$referrers_$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$($JSCompiler_inline_result$jscomp$825_referrer$jscomp$inline_3382$$)},$addDynamicCssClasses$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$=function($ampdoc$jscomp$175$$,
$classes$jscomp$1$$){$ampdoc$jscomp$175$$.$isBodyAvailable$()?$addCssClassesToBody$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$($ampdoc$jscomp$175$$.$getBody$(),$classes$jscomp$1$$):$ampdoc$jscomp$175$$.$whenBodyAvailable$().then(function($ampdoc$jscomp$175$$){return $addCssClassesToBody$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$($ampdoc$jscomp$175$$,$classes$jscomp$1$$)})},$addCssClassesToBody$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$=
function($body$jscomp$23_classList$jscomp$8$$,$classes$jscomp$2$$){$body$jscomp$23_classList$jscomp$8$$=$body$jscomp$23_classList$jscomp$8$$.classList;for(var $i$jscomp$316$$=0;$i$jscomp$316$$<$classes$jscomp$2$$.length;$i$jscomp$316$$++)$body$jscomp$23_classList$jscomp$8$$.add($classes$jscomp$2$$[$i$jscomp$316$$])},$addReferrerClasses$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$=function($ampdoc$jscomp$176$$){var $classes$jscomp$3$$=$normalizedReferrers$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$($ampdoc$jscomp$176$$).map(function($ampdoc$jscomp$176$$){return"amp-referrer-"+
$ampdoc$jscomp$176$$.replace(/\./g,"-")});_.$Services$$module$src$services$vsyncFor$$($ampdoc$jscomp$176$$.$win$).$mutate$(function(){$addDynamicCssClasses$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$($ampdoc$jscomp$176$$,$classes$jscomp$3$$)})},$addViewerClass$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$=function($ampdoc$jscomp$177$$){_.$Services$$module$src$services$viewerForDoc$$($ampdoc$jscomp$177$$).$G$&&_.$Services$$module$src$services$vsyncFor$$($ampdoc$jscomp$177$$.$win$).$mutate$(function(){$addDynamicCssClasses$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$($ampdoc$jscomp$177$$,
["amp-viewer"])})},$AmpDynamicCssClasses$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$=function($ampdoc$jscomp$179$$){$addReferrerClasses$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$($ampdoc$jscomp$179$$);$addViewerClass$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$($ampdoc$jscomp$179$$)};$AmpDynamicCssClasses$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$.prototype.$whenReady$=function(){return Promise.resolve()};
self.AMP.registerServiceForDoc("amp-dynamic-css-classes",$AmpDynamicCssClasses$$module$extensions$amp_dynamic_css_classes$0_1$amp_dynamic_css_classes$$);
})});

//# sourceMappingURL=amp-dynamic-css-classes-0.1.js.map
