(self.AMP=self.AMP||[]).push({n:"amp-izlesene",i:["_base_i","_base_media"],v:"1904281823091",f:(function(AMP,_){
var $AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$=function($$jscomp$super$this$jscomp$68_element$jscomp$519$$){$$jscomp$super$this$jscomp$68_element$jscomp$519$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$68_element$jscomp$519$$)||this;$$jscomp$super$this$jscomp$68_element$jscomp$519$$.$G$=null;$$jscomp$super$this$jscomp$68_element$jscomp$519$$.$D$=null;$$jscomp$super$this$jscomp$68_element$jscomp$519$$.$F$=null;return $$jscomp$super$this$jscomp$68_element$jscomp$519$$},
$JSCompiler_StaticMethods_AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene_prototype$getVideoIframeSrc_$$=function($JSCompiler_StaticMethods_AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene_prototype$getVideoIframeSrc_$self$$){if($JSCompiler_StaticMethods_AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene_prototype$getVideoIframeSrc_$self$$.$F$)return $JSCompiler_StaticMethods_AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene_prototype$getVideoIframeSrc_$self$$.$F$;
var $src$jscomp$51$$="https://www.izlesene.com/embedplayer/"+encodeURIComponent($JSCompiler_StaticMethods_AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene_prototype$getVideoIframeSrc_$self$$.$G$||"")+"/?",$params$jscomp$33$$=_.$getDataParamsFromAttributes$$module$src$dom$$($JSCompiler_StaticMethods_AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene_prototype$getVideoIframeSrc_$self$$.element);"autoplay"in $params$jscomp$33$$&&delete $params$jscomp$33$$.autoplay;$src$jscomp$51$$=
_.$addParamsToUrl$$module$src$url$$($src$jscomp$51$$,$params$jscomp$33$$);return $JSCompiler_StaticMethods_AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene_prototype$getVideoIframeSrc_$self$$.$F$=$src$jscomp$51$$};_.$$jscomp$inherits$$($AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$.prototype;
_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($opt_onLayout$jscomp$20$$){this.$preconnect$.url($JSCompiler_StaticMethods_AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene_prototype$getVideoIframeSrc_$$(this));this.$preconnect$.url("https://i1.imgiz.com",$opt_onLayout$jscomp$20$$)};_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$80$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$80$$)};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){this.$G$=this.element.getAttribute("data-videoid")};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $iframe$jscomp$67$$=this.element.ownerDocument.createElement("iframe"),$src$jscomp$52$$=$JSCompiler_StaticMethods_AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene_prototype$getVideoIframeSrc_$$(this);$iframe$jscomp$67$$.setAttribute("frameborder","0");$iframe$jscomp$67$$.setAttribute("allowfullscreen","true");$iframe$jscomp$67$$.src=$src$jscomp$52$$;_.$JSCompiler_StaticMethods_applyFillContent$$($iframe$jscomp$67$$);this.element.appendChild($iframe$jscomp$67$$);
this.$D$=$iframe$jscomp$67$$;return this.$loadPromise$($iframe$jscomp$67$$)};_.$JSCompiler_prototypeAlias$$.$pauseCallback$=function(){this.$D$&&this.$D$.contentWindow&&this.$D$.contentWindow.postMessage(_.$dict$$module$src$utils$object$$({command:"pause"}),"*")};self.AMP.registerElement("amp-izlesene",$AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$);
})});

//# sourceMappingURL=amp-izlesene-0.1.js.map
