(self.AMP=self.AMP||[]).push({n:"amp-call-tracking",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $fetch_$$module$extensions$amp_call_tracking$0_1$amp_call_tracking$$=function($win$jscomp$350$$,$url$jscomp$186$$){$url$jscomp$186$$ in $cachedResponsePromises_$$module$extensions$amp_call_tracking$0_1$amp_call_tracking$$||($cachedResponsePromises_$$module$extensions$amp_call_tracking$0_1$amp_call_tracking$$[$url$jscomp$186$$]=_.$JSCompiler_StaticMethods_fetchJson$$(_.$Services$$module$src$services$xhrFor$$($win$jscomp$350$$),$url$jscomp$186$$,{credentials:"include"}).then(function($win$jscomp$350$$){return $win$jscomp$350$$.json()}));
return $cachedResponsePromises_$$module$extensions$amp_call_tracking$0_1$amp_call_tracking$$[$url$jscomp$186$$]},$AmpCallTracking$$module$extensions$amp_call_tracking$0_1$amp_call_tracking$$=function($$jscomp$super$this$jscomp$31_element$jscomp$412$$){$$jscomp$super$this$jscomp$31_element$jscomp$412$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$31_element$jscomp$412$$)||this;$$jscomp$super$this$jscomp$31_element$jscomp$412$$.$D$=null;$$jscomp$super$this$jscomp$31_element$jscomp$412$$.$F$=
null;return $$jscomp$super$this$jscomp$31_element$jscomp$412$$},$cachedResponsePromises_$$module$extensions$amp_call_tracking$0_1$amp_call_tracking$$={};_.$$jscomp$inherits$$($AmpCallTracking$$module$extensions$amp_call_tracking$0_1$amp_call_tracking$$,AMP.BaseElement);$AmpCallTracking$$module$extensions$amp_call_tracking$0_1$amp_call_tracking$$.prototype.$isLayoutSupported$=function($layout$jscomp$51$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$51$$)||"container"==$layout$jscomp$51$$};
$AmpCallTracking$$module$extensions$amp_call_tracking$0_1$amp_call_tracking$$.prototype.$buildCallback$=function(){this.$F$=this.element.getAttribute("config");this.$D$=this.element.firstElementChild};
$AmpCallTracking$$module$extensions$amp_call_tracking$0_1$amp_call_tracking$$.prototype.$layoutCallback$=function(){var $$jscomp$this$jscomp$543$$=this;return _.$JSCompiler_StaticMethods_expandUrlAsync$$(_.$Services$$module$src$services$urlReplacementsForDoc$$(this.element),_.$JSCompiler_StaticMethods_assertString$$(_.$user$$module$src$log$$(),this.$F$)).then(function($url$jscomp$187$$){return $fetch_$$module$extensions$amp_call_tracking$0_1$amp_call_tracking$$($$jscomp$this$jscomp$543$$.$win$,$url$jscomp$187$$)}).then(function($data$jscomp$149$$){$$jscomp$this$jscomp$543$$.$D$.setAttribute("href",
"tel:"+$data$jscomp$149$$.phoneNumber);$$jscomp$this$jscomp$543$$.$D$.textContent=$data$jscomp$149$$.formattedPhoneNumber||$data$jscomp$149$$.phoneNumber})};self.AMP.registerElement("amp-call-tracking",$AmpCallTracking$$module$extensions$amp_call_tracking$0_1$amp_call_tracking$$);
})});

//# sourceMappingURL=amp-call-tracking-0.1.js.map
