(self.AMP=self.AMP||[]).push({n:"amp-mathml",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $AmpMathml$$module$extensions$amp_mathml$0_1$amp_mathml$$=function($$jscomp$super$this$jscomp$76_element$jscomp$563$$){$$jscomp$super$this$jscomp$76_element$jscomp$563$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$76_element$jscomp$563$$)||this;$$jscomp$super$this$jscomp$76_element$jscomp$563$$.$D$=null;return $$jscomp$super$this$jscomp$76_element$jscomp$563$$};_.$$jscomp$inherits$$($AmpMathml$$module$extensions$amp_mathml$0_1$amp_mathml$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpMathml$$module$extensions$amp_mathml$0_1$amp_mathml$$.prototype;_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function(){this.$preconnect$.url("https://cdnjs.cloudflare.com")};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){var $$jscomp$this$jscomp$813$$=this,$sizingWidth$$;this.element.hasAttribute("inline")&&($sizingWidth$$="1px");this.$mutateElement$(function(){_.$setStyles$$module$src$style$$($$jscomp$this$jscomp$813$$.element,{width:$sizingWidth$$,height:"1rem"})})};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $$jscomp$this$jscomp$814$$=this,$iframe$jscomp$70$$=_.$getIframe$$module$src$3p_frame$$(this.$win$,this.element,"mathml");_.$JSCompiler_StaticMethods_applyFillContent$$($iframe$jscomp$70$$);_.$listenFor$$module$src$iframe_helper$$($iframe$jscomp$70$$,"embed-size",function($iframe$jscomp$70$$){$$jscomp$this$jscomp$814$$.element.hasAttribute("inline")||($iframe$jscomp$70$$.width=void 0);$$jscomp$this$jscomp$814$$.element.$resources_$.$changeSize$($$jscomp$this$jscomp$814$$.element,
$iframe$jscomp$70$$.height,$iframe$jscomp$70$$.width)},!0);this.element.appendChild($iframe$jscomp$70$$);this.$D$=$iframe$jscomp$70$$;return this.$loadPromise$($iframe$jscomp$70$$)};_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$D$=null);return!0};_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$86$$){return"container"==$layout$jscomp$86$$};
self.AMP.registerElement("amp-mathml",$AmpMathml$$module$extensions$amp_mathml$0_1$amp_mathml$$,"amp-mathml[inline]{display:inline-block;vertical-align:middle}\n/*# sourceURL=/extensions/amp-mathml/0.1/amp-mathml.css*/");
})});

//# sourceMappingURL=amp-mathml-0.1.js.map
