(self.AMP=self.AMP||[]).push({n:"amp-ad-exit",i:["_base_i","_base_ad"],v:"1904281823091",f:(function(AMP,_){
var $JSCompiler_StaticMethods_expandStringSync$$=function($JSCompiler_StaticMethods_expandStringSync$self$$,$source$jscomp$20$$,$opt_bindings$jscomp$2$$){return(new _.$Expander$$module$src$service$url_expander$expander$$($JSCompiler_StaticMethods_expandStringSync$self$$.$D$,$opt_bindings$jscomp$2$$,void 0,!0,void 0,!0)).expand($source$jscomp$20$$)},$Filter$$module$extensions$amp_ad_exit$0_1$filters$filter$$=function($name$jscomp$181$$,$type$jscomp$177$$){this.name=$name$jscomp$181$$;this.type=$type$jscomp$177$$},
$assertConfig$$module$extensions$amp_ad_exit$0_1$config$$=function($config$jscomp$20$$){$config$jscomp$20$$.filters||($config$jscomp$20$$.filters={});$config$jscomp$20$$.transport||($config$jscomp$20$$.transport={});var $targets$jscomp$inline_2339$$=$config$jscomp$20$$.targets,$target$jscomp$inline_2341$$;for($target$jscomp$inline_2341$$ in $targets$jscomp$inline_2339$$)$assertTarget$$module$extensions$amp_ad_exit$0_1$config$$($targets$jscomp$inline_2339$$[$target$jscomp$inline_2341$$]);return $config$jscomp$20$$},
$assertTarget$$module$extensions$amp_ad_exit$0_1$config$$=function($target$jscomp$136$$){$target$jscomp$136$$.filters&&$target$jscomp$136$$.filters.forEach(function(){});if($target$jscomp$136$$.vars)for(var $variable$jscomp$1$$ in $target$jscomp$136$$.vars);},$assertVendor$$module$extensions$amp_ad_exit$0_1$config$$=function($vendor$jscomp$7$$){return _.$JSCompiler_StaticMethods_assertString$$(_.$user$$module$src$log$$(),_.$IFRAME_TRANSPORTS$$module$extensions$amp_analytics$0_1$iframe_transport_vendors$$[$vendor$jscomp$7$$],
"Unknown or invalid vendor "+$vendor$jscomp$7$$+", note that vendor must use transport: iframe")},$InactiveElementFilter$$module$extensions$amp_ad_exit$0_1$filters$inactive_element$$=function($name$jscomp$184$$,$spec$jscomp$4$$){$Filter$$module$extensions$amp_ad_exit$0_1$filters$filter$$.call(this,$name$jscomp$184$$,$spec$jscomp$4$$.type);this.$D$=$spec$jscomp$4$$.selector},$ClickDelayFilter$$module$extensions$amp_ad_exit$0_1$filters$click_delay$$=function($name$jscomp$185$$,$spec$jscomp$6$$,$win$jscomp$298$$){$Filter$$module$extensions$amp_ad_exit$0_1$filters$filter$$.call(this,
$name$jscomp$185$$,$spec$jscomp$6$$.type);this.spec=$spec$jscomp$6$$;this.$D$=Date.now();$spec$jscomp$6$$.$startTimingEvent$&&($win$jscomp$298$$.performance&&$win$jscomp$298$$.performance.timing?void 0==$win$jscomp$298$$.performance.timing[$spec$jscomp$6$$.$startTimingEvent$]?_.$dev$$module$src$log$$().$Log$$module$src$log_prototype$warn$("amp-ad-exit","Invalid performance timing event type "+$spec$jscomp$6$$.$startTimingEvent$+", falling back to now"):this.$D$=$win$jscomp$298$$.performance.timing[$spec$jscomp$6$$.$startTimingEvent$]:
_.$dev$$module$src$log$$().$Log$$module$src$log_prototype$warn$("amp-ad-exit","Browser does not support performance timing, falling back to now"))},$makeClickDelaySpec$$module$extensions$amp_ad_exit$0_1$filters$click_delay$$=function($startTimingEvent$$){return{type:"clickDelay",delay:1E3,$startTimingEvent$:$startTimingEvent$$}},$ClickLocationFilter$$module$extensions$amp_ad_exit$0_1$filters$click_location$$=function($name$jscomp$186$$,$spec$jscomp$7$$,$adExitElement$$){$Filter$$module$extensions$amp_ad_exit$0_1$filters$filter$$.call(this,
$name$jscomp$186$$,$spec$jscomp$7$$.type);this.$I$=$spec$jscomp$7$$.left||0;this.$J$=$spec$jscomp$7$$.right||0;this.$K$=$spec$jscomp$7$$.top||0;this.$H$=$spec$jscomp$7$$.bottom||0;this.$G$=$spec$jscomp$7$$.$relativeTo$;this.$F$=$adExitElement$$;this.$D$={top:0,right:0,bottom:0,left:0}},$createFilter$$module$extensions$amp_ad_exit$0_1$filters$factory$$=function($name$jscomp$187$$,$spec$jscomp$9$$,$adExitInstance$$){switch($spec$jscomp$9$$.type){case "clickDelay":return new $ClickDelayFilter$$module$extensions$amp_ad_exit$0_1$filters$click_delay$$($name$jscomp$187$$,
$spec$jscomp$9$$,$adExitInstance$$.$win$);case "clickLocation":return new $ClickLocationFilter$$module$extensions$amp_ad_exit$0_1$filters$click_location$$($name$jscomp$187$$,$spec$jscomp$9$$,$adExitInstance$$);case "inactiveElement":return new $InactiveElementFilter$$module$extensions$amp_ad_exit$0_1$filters$inactive_element$$($name$jscomp$187$$,$spec$jscomp$9$$)}},$AmpAdExit$$module$extensions$amp_ad_exit$0_1$amp_ad_exit$$=function($$jscomp$super$this$jscomp$9_element$jscomp$307$$){$$jscomp$super$this$jscomp$9_element$jscomp$307$$=
AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$9_element$jscomp$307$$)||this;$$jscomp$super$this$jscomp$9_element$jscomp$307$$.$K$={};$$jscomp$super$this$jscomp$9_element$jscomp$307$$.$H$=[];$$jscomp$super$this$jscomp$9_element$jscomp$307$$.$D$={$beacon$:!0,image:!0};$$jscomp$super$this$jscomp$9_element$jscomp$307$$.$I$={};_.$JSCompiler_StaticMethods_registerAction$$($$jscomp$super$this$jscomp$9_element$jscomp$307$$,"exit",$$jscomp$super$this$jscomp$9_element$jscomp$307$$.$exit$.bind($$jscomp$super$this$jscomp$9_element$jscomp$307$$));
$$jscomp$super$this$jscomp$9_element$jscomp$307$$.$M$={};$$jscomp$super$this$jscomp$9_element$jscomp$307$$.$F$=null;$$jscomp$super$this$jscomp$9_element$jscomp$307$$.$G$=null;$$jscomp$super$this$jscomp$9_element$jscomp$307$$.$J$={};return $$jscomp$super$this$jscomp$9_element$jscomp$307$$},$JSCompiler_StaticMethods_getUrlVariableRewriter_$$=function($JSCompiler_StaticMethods_getUrlVariableRewriter_$self$$,$args$jscomp$24$$,$event$jscomp$72$$,$target$jscomp$138$$){var $substitutionFunctions$$={CLICK_X:function(){return $event$jscomp$72$$.clientX},
CLICK_Y:function(){return $event$jscomp$72$$.clientY}},$replacements$$=_.$Services$$module$src$services$urlReplacementsForDoc$$($JSCompiler_StaticMethods_getUrlVariableRewriter_$self$$.element),$whitelist$jscomp$9$$={RANDOM:!0,CLICK_X:!0,CLICK_Y:!0};if($target$jscomp$138$$.vars){var $$jscomp$loop$451$$={},$customVarName$$;for($customVarName$$ in $target$jscomp$138$$.vars)$$jscomp$loop$451$$.$$jscomp$loop$prop$customVarName$453$=$customVarName$$,"_"==$$jscomp$loop$451$$.$$jscomp$loop$prop$customVarName$453$[0]&&
($$jscomp$loop$451$$.$$jscomp$loop$prop$customVar$452$=$target$jscomp$138$$.vars[$$jscomp$loop$451$$.$$jscomp$loop$prop$customVarName$453$],$$jscomp$loop$451$$.$$jscomp$loop$prop$customVar$452$&&($substitutionFunctions$$[$$jscomp$loop$451$$.$$jscomp$loop$prop$customVarName$453$]=function($event$jscomp$72$$){return function(){if($event$jscomp$72$$.$$jscomp$loop$prop$customVar$452$.$iframeTransportSignal$){var $target$jscomp$138$$=$JSCompiler_StaticMethods_expandStringSync$$($replacements$$,$event$jscomp$72$$.$$jscomp$loop$prop$customVar$452$.$iframeTransportSignal$,
{IFRAME_TRANSPORT_SIGNAL:function($args$jscomp$24$$,$event$jscomp$72$$){if(!$args$jscomp$24$$||!$event$jscomp$72$$)return"";if(($args$jscomp$24$$=$JSCompiler_StaticMethods_getUrlVariableRewriter_$self$$.$M$[$args$jscomp$24$$])&&$event$jscomp$72$$ in $args$jscomp$24$$)return $args$jscomp$24$$[$event$jscomp$72$$]}});if($event$jscomp$72$$.$$jscomp$loop$prop$customVar$452$.$iframeTransportSignal$=="IFRAME_TRANSPORT_SIGNAL"+$target$jscomp$138$$)_.$dev$$module$src$log$$().error("amp-ad-exit","Invalid IFRAME_TRANSPORT_SIGNAL format:"+
$target$jscomp$138$$+" (perhaps there is a space after a comma?)");else if(""!=$target$jscomp$138$$)return $target$jscomp$138$$}return $event$jscomp$72$$.$$jscomp$loop$prop$customVarName$453$ in $args$jscomp$24$$?$args$jscomp$24$$[$event$jscomp$72$$.$$jscomp$loop$prop$customVarName$453$]:$event$jscomp$72$$.$$jscomp$loop$prop$customVar$452$.defaultValue}}($$jscomp$loop$451$$),$whitelist$jscomp$9$$[$$jscomp$loop$451$$.$$jscomp$loop$prop$customVarName$453$]=!0)),$$jscomp$loop$451$$={$$jscomp$loop$prop$customVar$452$:$$jscomp$loop$451$$.$$jscomp$loop$prop$customVar$452$,
$$jscomp$loop$prop$customVarName$453$:$$jscomp$loop$451$$.$$jscomp$loop$prop$customVarName$453$}}return function($JSCompiler_StaticMethods_getUrlVariableRewriter_$self$$){return _.$JSCompiler_StaticMethods_expandUrlSync$$($replacements$$,$JSCompiler_StaticMethods_getUrlVariableRewriter_$self$$,$substitutionFunctions$$,void 0,$whitelist$jscomp$9$$)}},$JSCompiler_StaticMethods_AmpAdExit$$module$extensions$amp_ad_exit$0_1$amp_ad_exit_prototype$filter_$$=function($filters$jscomp$1$$,$event$jscomp$73$$){return $filters$jscomp$1$$.every(function($filters$jscomp$1$$){var $filter$jscomp$5$$=
$filters$jscomp$1$$.filter($event$jscomp$73$$);_.$user$$module$src$log$$().$Log$$module$src$log_prototype$info$("amp-ad-exit","Filter '"+$filters$jscomp$1$$.name+"': "+($filter$jscomp$5$$?"pass":"fail"));return $filter$jscomp$5$$})},$JSCompiler_StaticMethods_init3pResponseListener_$$=function($JSCompiler_StaticMethods_init3pResponseListener_$self$$){"inabox"!=_.$getMode$$module$src$mode$$().runtime&&($JSCompiler_StaticMethods_init3pResponseListener_$self$$.$G$=$JSCompiler_StaticMethods_init3pResponseListener_$self$$.$G$||
_.$getAmpAdResourceId$$module$src$ad_helper$$($JSCompiler_StaticMethods_init3pResponseListener_$self$$.element,_.$getTopWindow$$module$src$service$$($JSCompiler_StaticMethods_init3pResponseListener_$self$$.$win$)),$JSCompiler_StaticMethods_init3pResponseListener_$self$$.$G$?$JSCompiler_StaticMethods_init3pResponseListener_$self$$.$F$=_.$listen$$module$src$3p_frame_messaging$$($JSCompiler_StaticMethods_init3pResponseListener_$self$$.$getAmpDoc$().$win$,function($event$jscomp$74_responseMsg$$){$JSCompiler_StaticMethods_init3pResponseListener_$self$$.$J$[$event$jscomp$74_responseMsg$$.origin]&&
($event$jscomp$74_responseMsg$$=_.$deserializeMessage$$module$src$3p_frame_messaging$$($event$jscomp$74_responseMsg$$.data))&&"iframe-transport-response"==$event$jscomp$74_responseMsg$$.type&&(_.$parseUrlDeprecated$$module$src$url$$($assertVendor$$module$extensions$amp_ad_exit$0_1$config$$($event$jscomp$74_responseMsg$$.vendor)),$event$jscomp$74_responseMsg$$.creativeId==$JSCompiler_StaticMethods_init3pResponseListener_$self$$.$G$&&($JSCompiler_StaticMethods_init3pResponseListener_$self$$.$M$[$event$jscomp$74_responseMsg$$.vendor]=
$event$jscomp$74_responseMsg$$.message))}):_.$user$$module$src$log$$().$Log$$module$src$log_prototype$warn$("amp-ad-exit","No friendly parent amp-ad element was found for amp-ad-exit; not in inabox case."))};$Filter$$module$extensions$amp_ad_exit$0_1$filters$filter$$.prototype.filter=function(){};$Filter$$module$extensions$amp_ad_exit$0_1$filters$filter$$.prototype.$onLayoutMeasure$=function(){};_.$$jscomp$inherits$$($InactiveElementFilter$$module$extensions$amp_ad_exit$0_1$filters$inactive_element$$,$Filter$$module$extensions$amp_ad_exit$0_1$filters$filter$$);$InactiveElementFilter$$module$extensions$amp_ad_exit$0_1$filters$inactive_element$$.prototype.filter=function($event$jscomp$69$$){return!_.$matches$$module$src$dom$$($event$jscomp$69$$.target,this.$D$)};_.$$jscomp$inherits$$($ClickDelayFilter$$module$extensions$amp_ad_exit$0_1$filters$click_delay$$,$Filter$$module$extensions$amp_ad_exit$0_1$filters$filter$$);$ClickDelayFilter$$module$extensions$amp_ad_exit$0_1$filters$click_delay$$.prototype.filter=function(){return Date.now()-this.$D$>=this.spec.delay};_.$$jscomp$inherits$$($ClickLocationFilter$$module$extensions$amp_ad_exit$0_1$filters$click_location$$,$Filter$$module$extensions$amp_ad_exit$0_1$filters$filter$$);$ClickLocationFilter$$module$extensions$amp_ad_exit$0_1$filters$click_location$$.prototype.filter=function($event$jscomp$70$$){return $event$jscomp$70$$.clientX>=this.$D$.left&&$event$jscomp$70$$.clientX<=this.$D$.right&&$event$jscomp$70$$.clientY>=this.$D$.top&&$event$jscomp$70$$.clientY<=this.$D$.bottom?!0:!1};
$ClickLocationFilter$$module$extensions$amp_ad_exit$0_1$filters$click_location$$.prototype.$onLayoutMeasure$=function(){var $$jscomp$this$jscomp$315$$=this;_.$JSCompiler_StaticMethods_getVsync$$(this.$F$).measure(function(){var $rect$jscomp$14_win$jscomp$299$$=$$jscomp$this$jscomp$315$$.$F$.$win$;$$jscomp$this$jscomp$315$$.$G$?($rect$jscomp$14_win$jscomp$299$$=$rect$jscomp$14_win$jscomp$299$$.document.querySelector($$jscomp$this$jscomp$315$$.$G$).getBoundingClientRect(),$$jscomp$this$jscomp$315$$.$D$.left=
$rect$jscomp$14_win$jscomp$299$$.left,$$jscomp$this$jscomp$315$$.$D$.top=$rect$jscomp$14_win$jscomp$299$$.top,$$jscomp$this$jscomp$315$$.$D$.bottom=$rect$jscomp$14_win$jscomp$299$$.bottom,$$jscomp$this$jscomp$315$$.$D$.right=$rect$jscomp$14_win$jscomp$299$$.right):($$jscomp$this$jscomp$315$$.$D$.left=0,$$jscomp$this$jscomp$315$$.$D$.top=0,$$jscomp$this$jscomp$315$$.$D$.bottom=$rect$jscomp$14_win$jscomp$299$$.innerHeight,$$jscomp$this$jscomp$315$$.$D$.right=$rect$jscomp$14_win$jscomp$299$$.innerWidth);
$$jscomp$this$jscomp$315$$.$D$.left+=$$jscomp$this$jscomp$315$$.$I$;$$jscomp$this$jscomp$315$$.$D$.top+=$$jscomp$this$jscomp$315$$.$K$;$$jscomp$this$jscomp$315$$.$D$.right-=$$jscomp$this$jscomp$315$$.$J$;$$jscomp$this$jscomp$315$$.$D$.bottom-=$$jscomp$this$jscomp$315$$.$H$})};_.$$jscomp$inherits$$($AmpAdExit$$module$extensions$amp_ad_exit$0_1$amp_ad_exit$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpAdExit$$module$extensions$amp_ad_exit$0_1$amp_ad_exit$$.prototype;
_.$JSCompiler_prototypeAlias$$.$exit$=function($$jscomp$destructuring$var264_target$jscomp$137$$){var $$jscomp$this$jscomp$316$$=this,$args$jscomp$23_substituteVariables$$=$$jscomp$destructuring$var264_target$jscomp$137$$.args,$event$jscomp$71$$=$$jscomp$destructuring$var264_target$jscomp$137$$.event;$$jscomp$destructuring$var264_target$jscomp$137$$=this.$K$[$args$jscomp$23_substituteVariables$$.target];$event$jscomp$71$$.preventDefault();if($JSCompiler_StaticMethods_AmpAdExit$$module$extensions$amp_ad_exit$0_1$amp_ad_exit_prototype$filter_$$(this.$H$,
$event$jscomp$71$$)&&$JSCompiler_StaticMethods_AmpAdExit$$module$extensions$amp_ad_exit$0_1$amp_ad_exit_prototype$filter_$$($$jscomp$destructuring$var264_target$jscomp$137$$.filters,$event$jscomp$71$$)){$args$jscomp$23_substituteVariables$$=$JSCompiler_StaticMethods_getUrlVariableRewriter_$$(this,$args$jscomp$23_substituteVariables$$,$event$jscomp$71$$,$$jscomp$destructuring$var264_target$jscomp$137$$);$$jscomp$destructuring$var264_target$jscomp$137$$.$trackingUrls$&&$$jscomp$destructuring$var264_target$jscomp$137$$.$trackingUrls$.map($args$jscomp$23_substituteVariables$$).forEach(function($$jscomp$destructuring$var264_target$jscomp$137$$){"amp-ad-exit";
$$jscomp$this$jscomp$316$$.$D$.$beacon$&&$$jscomp$this$jscomp$316$$.$win$.navigator.sendBeacon&&$$jscomp$this$jscomp$316$$.$win$.navigator.sendBeacon($$jscomp$destructuring$var264_target$jscomp$137$$,"")||!$$jscomp$this$jscomp$316$$.$D$.image||($$jscomp$this$jscomp$316$$.$win$.document.createElement("img").src=$$jscomp$destructuring$var264_target$jscomp$137$$)});var $finalUrl$$=$args$jscomp$23_substituteVariables$$($$jscomp$destructuring$var264_target$jscomp$137$$.$finalUrl$);_.$HostServices$$module$src$inabox$host_services$isAvailable$$(this.$getAmpDoc$())?
_.$getServicePromiseForDoc$$module$src$service$$(this.$getAmpDoc$(),"host-exit").then(function($$jscomp$destructuring$var264_target$jscomp$137$$){return $$jscomp$destructuring$var264_target$jscomp$137$$.$G$($finalUrl$$)}).catch(function($$jscomp$destructuring$var264_target$jscomp$137$$){"amp-ad-exit";$$jscomp$destructuring$var264_target$jscomp$137$$.$fallback$&&_.$openWindowDialog$$module$src$dom$$($$jscomp$this$jscomp$316$$.$win$,$finalUrl$$,"_blank")}):_.$openWindowDialog$$module$src$dom$$(this.$win$,
$finalUrl$$,$$jscomp$destructuring$var264_target$jscomp$137$$.$behaviors$&&$$jscomp$destructuring$var264_target$jscomp$137$$.$behaviors$.$clickTarget$&&"_top"==$$jscomp$destructuring$var264_target$jscomp$137$$.$behaviors$.$clickTarget$?"_top":"_blank")}};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){var $$jscomp$this$jscomp$318$$=this;this.element.setAttribute("aria-hidden","true");this.$H$.push($createFilter$$module$extensions$amp_ad_exit$0_1$filters$factory$$("minDelay",$makeClickDelaySpec$$module$extensions$amp_ad_exit$0_1$filters$click_delay$$(),this));this.$H$.push($createFilter$$module$extensions$amp_ad_exit$0_1$filters$factory$$("carouselBtns",{type:"inactiveElement",selector:".amp-carousel-button"},this));var $child$jscomp$10$$=
this.element.children[0];try{var $config$jscomp$23$$=$assertConfig$$module$extensions$amp_ad_exit$0_1$config$$(_.$parseJson$$module$src$json$$($child$jscomp$10$$.textContent));if(_.$isObject$$module$src$types$$($config$jscomp$23$$.options)&&"string"===typeof $config$jscomp$23$$.options.startTimingEvent){var $defaultClickStartTimingEvent$$=$config$jscomp$23$$.options.startTimingEvent;this.$H$.splice(0,1,$createFilter$$module$extensions$amp_ad_exit$0_1$filters$factory$$("minDelay",$makeClickDelaySpec$$module$extensions$amp_ad_exit$0_1$filters$click_delay$$($config$jscomp$23$$.options.startTimingEvent),
this))}for(var $name$jscomp$188$$ in $config$jscomp$23$$.filters){var $spec$jscomp$10$$=$config$jscomp$23$$.filters[$name$jscomp$188$$];"clickDelay"==$spec$jscomp$10$$.type&&($spec$jscomp$10$$.$startTimingEvent$=$spec$jscomp$10$$.$startTimingEvent$||$defaultClickStartTimingEvent$$);this.$I$[$name$jscomp$188$$]=$createFilter$$module$extensions$amp_ad_exit$0_1$filters$factory$$($name$jscomp$188$$,$spec$jscomp$10$$,this)}for(var $name$239$$ in $config$jscomp$23$$.targets){var $target$jscomp$139$$=$config$jscomp$23$$.targets[$name$239$$];
this.$K$[$name$239$$]={$finalUrl$:$target$jscomp$139$$.finalUrl,$trackingUrls$:$target$jscomp$139$$.trackingUrls||[],$vars$:$target$jscomp$139$$.vars||{},filters:($target$jscomp$139$$.filters||[]).map(function($child$jscomp$10$$){return $$jscomp$this$jscomp$318$$.$I$[$child$jscomp$10$$]}).filter(function($$jscomp$this$jscomp$318$$){return $$jscomp$this$jscomp$318$$}),$behaviors$:$target$jscomp$139$$.behaviors||{}};for(var $customVar$$ in $target$jscomp$139$$.vars)if($target$jscomp$139$$.vars[$customVar$$].$iframeTransportSignal$){var $matches$jscomp$13$$=
$target$jscomp$139$$.vars[$customVar$$].$iframeTransportSignal$.match(/IFRAME_TRANSPORT_SIGNAL\(([^,]+)/);if($matches$jscomp$13$$&&!(2>$matches$jscomp$13$$.length)){var $vendor$jscomp$9$$=$matches$jscomp$13$$[1],$origin$jscomp$19$$=_.$parseUrlDeprecated$$module$src$url$$($assertVendor$$module$extensions$amp_ad_exit$0_1$config$$($vendor$jscomp$9$$)).origin;this.$J$[$origin$jscomp$19$$]=this.$J$[$origin$jscomp$19$$]||$vendor$jscomp$9$$}}}this.$D$.$beacon$=!1!==$config$jscomp$23$$.transport.beacon;this.$D$.image=
!1!==$config$jscomp$23$$.transport.image}catch($e$240$$){throw this.$user$().error("amp-ad-exit","Invalid JSON config",$e$240$$),$e$240$$;}$JSCompiler_StaticMethods_init3pResponseListener_$$(this)};_.$JSCompiler_prototypeAlias$$.$resumeCallback$=function(){$JSCompiler_StaticMethods_init3pResponseListener_$$(this)};_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$F$&&(this.$F$(),this.$F$=null);return AMP.BaseElement.prototype.$unlayoutCallback$.call(this)};
_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$onLayoutMeasure$=function(){for(var $name$jscomp$189$$ in this.$I$)this.$I$[$name$jscomp$189$$].$onLayoutMeasure$()};self.AMP.registerElement("amp-ad-exit",$AmpAdExit$$module$extensions$amp_ad_exit$0_1$amp_ad_exit$$);
})});

//# sourceMappingURL=amp-ad-exit-0.1.js.map
