(self.AMP=self.AMP||[]).push({n:"amp-brid-player",i:["_base_i","_base_media"],v:"1904281823091",f:(function(AMP,_){
var $AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player$$=function($$jscomp$super$this$jscomp$28_element$jscomp$404$$){$$jscomp$super$this$jscomp$28_element$jscomp$404$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$28_element$jscomp$404$$)||this;$$jscomp$super$this$jscomp$28_element$jscomp$404$$.$K$="";$$jscomp$super$this$jscomp$28_element$jscomp$404$$.$J$="";$$jscomp$super$this$jscomp$28_element$jscomp$404$$.$O$="";$$jscomp$super$this$jscomp$28_element$jscomp$404$$.$D$=
null;$$jscomp$super$this$jscomp$28_element$jscomp$404$$.$F$=null;$$jscomp$super$this$jscomp$28_element$jscomp$404$$.$H$=null;$$jscomp$super$this$jscomp$28_element$jscomp$404$$.$G$=null;$$jscomp$super$this$jscomp$28_element$jscomp$404$$.$M$=null;$$jscomp$super$this$jscomp$28_element$jscomp$404$$.$I$=null;return $$jscomp$super$this$jscomp$28_element$jscomp$404$$},$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$getVideoIframeSrc_$$=function($JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$getVideoIframeSrc_$self$$){if($JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$getVideoIframeSrc_$self$$.$G$)return $JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$getVideoIframeSrc_$self$$.$G$;
var $feedType_src$jscomp$29$$="",$itemsNum$$=$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$getVideoIframeSrc_$self$$.element.hasAttribute("data-dynamic")?"10":"1";$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$getVideoIframeSrc_$self$$.element.hasAttribute("data-video")?$feedType_src$jscomp$29$$="video":$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$getVideoIframeSrc_$self$$.element.hasAttribute("data-dynamic")?
$feedType_src$jscomp$29$$=$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$getVideoIframeSrc_$self$$.element.getAttribute("data-dynamic"):$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$getVideoIframeSrc_$self$$.element.hasAttribute("data-playlist")?$feedType_src$jscomp$29$$="playlist":$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$getVideoIframeSrc_$self$$.element.hasAttribute("data-outstream")&&
($feedType_src$jscomp$29$$="outstream");$feedType_src$jscomp$29$$="https://services.brid.tv/services/iframe/"+encodeURIComponent($feedType_src$jscomp$29$$)+"/"+encodeURIComponent($JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$getVideoIframeSrc_$self$$.$J$)+"/"+encodeURIComponent($JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$getVideoIframeSrc_$self$$.$K$)+"/"+encodeURIComponent($JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$getVideoIframeSrc_$self$$.$O$)+
"/0/"+$itemsNum$$+"/?amp=1";$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$getVideoIframeSrc_$self$$.$G$=_.$parseUrlDeprecated$$module$src$url$$($feedType_src$jscomp$29$$).href;return $JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$getVideoIframeSrc_$self$$.$G$},$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$sendCommand_$$=function($JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$sendCommand_$self$$,
$command$$,$opt_arg$$){$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$sendCommand_$self$$.$F$.then(function(){$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$sendCommand_$self$$.$D$&&$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$sendCommand_$self$$.$D$.contentWindow&&$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$sendCommand_$self$$.$D$.contentWindow.postMessage("Brid|"+
$command$$+(void 0===$opt_arg$$?"":"|"+$opt_arg$$),"*")})},$_template$$module$extensions$amp_brid_player$0_1$amp_brid_player$$=["<amp-img referrerpolicy=origin layout=fill placeholder><amp-img referrerpolicy=origin layout=fill fallback src=https://cdn.brid.tv/live/default/defaultSnapshot.png></amp-img></amp-img>"];_.$$jscomp$inherits$$($AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player$$.prototype;
_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($opt_onLayout$jscomp$9$$){this.$preconnect$.url("https://services.brid.tv",$opt_onLayout$jscomp$9$$);this.$preconnect$.url("https://cdn.brid.tv",$opt_onLayout$jscomp$9$$)};_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$48$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$48$$)};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){var $element$jscomp$405$$=this.element;this.$K$=$element$jscomp$405$$.getAttribute("data-partner");this.$O$=$element$jscomp$405$$.getAttribute("data-player");this.$J$=$element$jscomp$405$$.getAttribute("data-video")||$element$jscomp$405$$.getAttribute("data-playlist")||$element$jscomp$405$$.getAttribute("data-outstream");var $deferred$jscomp$35$$=new _.$Deferred$$module$src$utils$promise$$;this.$F$=$deferred$jscomp$35$$.$promise$;this.$H$=
$deferred$jscomp$35$$.resolve;_.$installVideoManagerForDoc$$module$src$service$video_manager_impl$$($element$jscomp$405$$);_.$Services$$module$src$services$videoManagerForDoc$$($element$jscomp$405$$).register(this)};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $$jscomp$this$jscomp$535$$=this,$iframe$jscomp$42$$=_.$createFrameFor$$module$src$iframe_video$$(this,$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$getVideoIframeSrc_$$(this));this.$D$=$iframe$jscomp$42$$;this.$I$=_.$listen$$module$src$event_helper$$(this.$win$,"message",this.$handleBridMessage_$.bind(this));return this.$loadPromise$($iframe$jscomp$42$$).then(function(){return $$jscomp$this$jscomp$535$$.$F$})};
_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$D$=null);this.$I$&&this.$I$();var $deferred$jscomp$36$$=new _.$Deferred$$module$src$utils$promise$$;this.$F$=$deferred$jscomp$36$$.$promise$;this.$H$=$deferred$jscomp$36$$.resolve;return!0};_.$JSCompiler_prototypeAlias$$.$pauseCallback$=function(){this.pause()};
_.$JSCompiler_prototypeAlias$$.$createPlaceholderCallback$=function(){var $element$jscomp$406_placeholder$jscomp$9$$=this.element;if($element$jscomp$406_placeholder$jscomp$9$$.hasAttribute("data-video")||$element$jscomp$406_placeholder$jscomp$9$$.hasAttribute("data-playlist")){var $altText_partnerID$$=this.$K$,$feedID$$=this.$J$;$element$jscomp$406_placeholder$jscomp$9$$=_.$htmlFor$$module$src$static_template$$($element$jscomp$406_placeholder$jscomp$9$$)($_template$$module$extensions$amp_brid_player$0_1$amp_brid_player$$);
_.$JSCompiler_StaticMethods_propagateAttributes$$(this,["aria-label"],$element$jscomp$406_placeholder$jscomp$9$$);_.$JSCompiler_StaticMethods_applyFillContent$$($element$jscomp$406_placeholder$jscomp$9$$);$element$jscomp$406_placeholder$jscomp$9$$.setAttribute("src","https://cdn.brid.tv/live/partners/"+encodeURIComponent($altText_partnerID$$)+("/snapshot/"+encodeURIComponent($feedID$$)+".jpg"));$altText_partnerID$$=$element$jscomp$406_placeholder$jscomp$9$$.hasAttribute("aria-label")?"Loading video - "+
$element$jscomp$406_placeholder$jscomp$9$$.getAttribute("aria-label"):"Loading video";$element$jscomp$406_placeholder$jscomp$9$$.setAttribute("alt",$altText_partnerID$$);return $element$jscomp$406_placeholder$jscomp$9$$}};
_.$JSCompiler_prototypeAlias$$.$handleBridMessage_$=function($element$jscomp$407_event$jscomp$107$$){if(_.$originMatches$$module$src$iframe_video$$($element$jscomp$407_event$jscomp$107$$,this.$D$,"https://services.brid.tv")){var $eventData$jscomp$4_params$jscomp$30$$=$element$jscomp$407_event$jscomp$107$$.data;"string"===typeof $eventData$jscomp$4_params$jscomp$30$$&&0===$eventData$jscomp$4_params$jscomp$30$$.indexOf("Brid")&&($element$jscomp$407_event$jscomp$107$$=this.element,$eventData$jscomp$4_params$jscomp$30$$=
$eventData$jscomp$4_params$jscomp$30$$.split("|"),"trigger"==$eventData$jscomp$4_params$jscomp$30$$[2]?("ready"==$eventData$jscomp$4_params$jscomp$30$$[3]&&this.$H$(this.$D$),_.$redispatch$$module$src$iframe_video$$($element$jscomp$407_event$jscomp$107$$,$eventData$jscomp$4_params$jscomp$30$$[3],{ready:_.$VideoEvents$$module$src$video_interface$$.$LOAD$,play:_.$VideoEvents$$module$src$video_interface$$.$PLAYING$,pause:_.$VideoEvents$$module$src$video_interface$$.$PAUSE$})):"volume"==$eventData$jscomp$4_params$jscomp$30$$[2]&&
(this.$M$=parseFloat($eventData$jscomp$4_params$jscomp$30$$[3]),$element$jscomp$407_event$jscomp$107$$.$dispatchCustomEvent$(_.$mutedOrUnmutedEvent$$module$src$iframe_video$$(0>=this.$M$))))}};_.$JSCompiler_prototypeAlias$$.$supportsPlatform$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$isInteractive$=function(){return!0};
_.$JSCompiler_prototypeAlias$$.play=function(){$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$sendCommand_$$(this,"play")};_.$JSCompiler_prototypeAlias$$.pause=function(){$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$sendCommand_$$(this,"pause")};
_.$JSCompiler_prototypeAlias$$.$mute$=function(){$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$sendCommand_$$(this,"muted",1);$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$sendCommand_$$(this,"volume",0)};
_.$JSCompiler_prototypeAlias$$.$unmute$=function(){$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$sendCommand_$$(this,"muted",0);$JSCompiler_StaticMethods_AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player_prototype$sendCommand_$$(this,"volume",1)};_.$JSCompiler_prototypeAlias$$.$showControls$=function(){};_.$JSCompiler_prototypeAlias$$.$hideControls$=function(){};
_.$JSCompiler_prototypeAlias$$.$fullscreenEnter$=function(){this.$D$&&_.$fullscreenEnter$$module$src$dom$$(this.$D$)};_.$JSCompiler_prototypeAlias$$.$fullscreenExit$=function(){this.$D$&&_.$fullscreenExit$$module$src$dom$$(this.$D$)};_.$JSCompiler_prototypeAlias$$.getMetadata=function(){};_.$JSCompiler_prototypeAlias$$.$preimplementsMediaSessionAPI$=function(){return!1};_.$JSCompiler_prototypeAlias$$.$preimplementsAutoFullscreen$=function(){return!1};
_.$JSCompiler_prototypeAlias$$.$getCurrentTime$=function(){return 0};_.$JSCompiler_prototypeAlias$$.$getDuration$=function(){return 1};_.$JSCompiler_prototypeAlias$$.$getPlayedRanges$=function(){return[]};_.$JSCompiler_prototypeAlias$$.$seekTo$=function(){this.$user$().error("amp-brid-player","`seekTo` not supported.")};self.AMP.registerElement("amp-brid-player",$AmpBridPlayer$$module$extensions$amp_brid_player$0_1$amp_brid_player$$);
})});

//# sourceMappingURL=amp-brid-player-0.1.js.map
