(self.AMP=self.AMP||[]).push({n:"amp-mowplayer",i:["_base_i","_base_media"],v:"1904281823091",f:(function(AMP,_){
var $AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer$$=function($$jscomp$super$this$jscomp$77_element$jscomp$564$$){$$jscomp$super$this$jscomp$77_element$jscomp$564$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$77_element$jscomp$564$$)||this;$$jscomp$super$this$jscomp$77_element$jscomp$564$$.$K$="";$$jscomp$super$this$jscomp$77_element$jscomp$564$$.$F$=!1;$$jscomp$super$this$jscomp$77_element$jscomp$564$$.$D$=null;$$jscomp$super$this$jscomp$77_element$jscomp$564$$.$J$=null;
$$jscomp$super$this$jscomp$77_element$jscomp$564$$.$G$=null;$$jscomp$super$this$jscomp$77_element$jscomp$564$$.$H$=null;$$jscomp$super$this$jscomp$77_element$jscomp$564$$.$I$=null;return $$jscomp$super$this$jscomp$77_element$jscomp$564$$},$JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$getVideoIframeSrc_$$=function($JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$getVideoIframeSrc_$self$$){return $JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$getVideoIframeSrc_$self$$.$J$?
$JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$getVideoIframeSrc_$self$$.$J$:$JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$getVideoIframeSrc_$self$$.$J$=_.$addParamsToUrl$$module$src$url$$("https://cdn.mowplayer.com/player.html",_.$dict$$module$src$utils$object$$({code:$JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$getVideoIframeSrc_$self$$.$K$}))},
$JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$sendCommand_$$=function($JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$sendCommand_$self$$,$command$jscomp$5$$,$opt_args$jscomp$17$$){$JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$sendCommand_$self$$.$G$.then(function(){if($JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$sendCommand_$self$$.$D$&&
$JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$sendCommand_$self$$.$D$.contentWindow){var $message$jscomp$66$$=JSON.stringify(_.$dict$$module$src$utils$object$$({event:"command",func:$command$jscomp$5$$,args:$opt_args$jscomp$17$$||""}));$JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$sendCommand_$self$$.$D$.contentWindow.postMessage($message$jscomp$66$$,"https://cdn.mowplayer.com")}})};
_.$$jscomp$inherits$$($AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer$$,AMP.BaseElement);_.$JSCompiler_prototypeAlias$$=$AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer$$.prototype;
_.$JSCompiler_prototypeAlias$$.$preconnectCallback$=function($opt_onLayout$jscomp$22$$){var $preconnect$jscomp$5$$=this.$preconnect$;$preconnect$jscomp$5$$.url($JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$getVideoIframeSrc_$$(this));$preconnect$jscomp$5$$.url("https://cdn.mowplayer.com",$opt_onLayout$jscomp$22$$);$preconnect$jscomp$5$$.url("https://code.mowplayer.com",$opt_onLayout$jscomp$22$$)};
_.$JSCompiler_prototypeAlias$$.$isLayoutSupported$=function($layout$jscomp$87$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$87$$)};_.$JSCompiler_prototypeAlias$$.$viewportCallback$=function($visible$jscomp$10$$){this.element.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$VISIBILITY$,{visible:$visible$jscomp$10$$})};
_.$JSCompiler_prototypeAlias$$.$buildCallback$=function(){this.$K$=this.element.getAttribute("data-mediaid");var $deferred$jscomp$48$$=new _.$Deferred$$module$src$utils$promise$$;this.$G$=$deferred$jscomp$48$$.$promise$;this.$H$=$deferred$jscomp$48$$.resolve;_.$installVideoManagerForDoc$$module$src$service$video_manager_impl$$(this.element);_.$Services$$module$src$services$videoManagerForDoc$$(this.element).register(this)};
_.$JSCompiler_prototypeAlias$$.$layoutCallback$=function(){var $$jscomp$this$jscomp$815$$=this;this.$D$=_.$createFrameFor$$module$src$iframe_video$$(this,$JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$getVideoIframeSrc_$$(this));this.$I$=_.$listen$$module$src$event_helper$$(this.$win$,"message",this.$handleMowMessage_$.bind(this));var $loaded$jscomp$1$$=this.$loadPromise$(this.$D$).then(function(){$$jscomp$this$jscomp$815$$.$D$&&$JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$sendCommand_$$($$jscomp$this$jscomp$815$$,
"listening",["amp",window.location.href,window.location.origin,!0]);$$jscomp$this$jscomp$815$$.element.$dispatchCustomEvent$(_.$VideoEvents$$module$src$video_interface$$.$LOAD$)});this.$H$($loaded$jscomp$1$$);return $loaded$jscomp$1$$};
_.$JSCompiler_prototypeAlias$$.$unlayoutCallback$=function(){this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$D$=null);this.$I$&&this.$I$();var $deferred$jscomp$49$$=new _.$Deferred$$module$src$utils$promise$$;this.$G$=$deferred$jscomp$49$$.$promise$;this.$H$=$deferred$jscomp$49$$.resolve;return!0};_.$JSCompiler_prototypeAlias$$.$pauseCallback$=function(){this.$D$&&this.$D$.contentWindow&&this.pause()};
_.$JSCompiler_prototypeAlias$$.$mutatedAttributesCallback$=function($mutations$jscomp$14$$){null!=$mutations$jscomp$14$$["data-mediaid"]&&this.$D$&&$JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$sendCommand_$$(this,"loadVideoById",[this.$K$])};
_.$JSCompiler_prototypeAlias$$.$handleMowMessage_$=function($$jscomp$compprop41_event$jscomp$164_eventData$jscomp$15_eventType$jscomp$58$$){if(_.$originMatches$$module$src$iframe_video$$($$jscomp$compprop41_event$jscomp$164_eventData$jscomp$15_eventType$jscomp$58$$,this.$D$,"https://cdn.mowplayer.com")&&($$jscomp$compprop41_event$jscomp$164_eventData$jscomp$15_eventType$jscomp$58$$=$$jscomp$compprop41_event$jscomp$164_eventData$jscomp$15_eventType$jscomp$58$$.data,_.$isJsonOrObj$$module$src$iframe_video$$($$jscomp$compprop41_event$jscomp$164_eventData$jscomp$15_eventType$jscomp$58$$))){var $data$jscomp$187_element$jscomp$565$$=
_.$objOrParseJson$$module$src$iframe_video$$($$jscomp$compprop41_event$jscomp$164_eventData$jscomp$15_eventType$jscomp$58$$);if(null!=$data$jscomp$187_element$jscomp$565$$){$$jscomp$compprop41_event$jscomp$164_eventData$jscomp$15_eventType$jscomp$58$$=$data$jscomp$187_element$jscomp$565$$.event;var $info$jscomp$16$$=$data$jscomp$187_element$jscomp$565$$.info||{};$data$jscomp$187_element$jscomp$565$$=this.element;"set_aspect_ratio"===$$jscomp$compprop41_event$jscomp$164_eventData$jscomp$15_eventType$jscomp$58$$&&
_.$JSCompiler_StaticMethods_attemptChangeHeight$$(this,$info$jscomp$16$$.new_height).catch(function(){});var $muted$jscomp$1_playerState$$=$info$jscomp$16$$.playerState;"infoDelivery"==$$jscomp$compprop41_event$jscomp$164_eventData$jscomp$15_eventType$jscomp$58$$&&null!=$muted$jscomp$1_playerState$$?($$jscomp$compprop41_event$jscomp$164_eventData$jscomp$15_eventType$jscomp$58$$={},_.$redispatch$$module$src$iframe_video$$($data$jscomp$187_element$jscomp$565$$,$muted$jscomp$1_playerState$$.toString(),
($$jscomp$compprop41_event$jscomp$164_eventData$jscomp$15_eventType$jscomp$58$$[1]=_.$VideoEvents$$module$src$video_interface$$.$PLAYING$,$$jscomp$compprop41_event$jscomp$164_eventData$jscomp$15_eventType$jscomp$58$$[2]=_.$VideoEvents$$module$src$video_interface$$.$PAUSE$,$$jscomp$compprop41_event$jscomp$164_eventData$jscomp$15_eventType$jscomp$58$$[0]=[_.$VideoEvents$$module$src$video_interface$$.$ENDED$,_.$VideoEvents$$module$src$video_interface$$.$PAUSE$],$$jscomp$compprop41_event$jscomp$164_eventData$jscomp$15_eventType$jscomp$58$$))):
($muted$jscomp$1_playerState$$=$info$jscomp$16$$.muted,"infoDelivery"==$$jscomp$compprop41_event$jscomp$164_eventData$jscomp$15_eventType$jscomp$58$$&&$info$jscomp$16$$&&null!=$muted$jscomp$1_playerState$$&&this.$F$!=$muted$jscomp$1_playerState$$&&(this.$F$=$muted$jscomp$1_playerState$$,$data$jscomp$187_element$jscomp$565$$.$dispatchCustomEvent$(_.$mutedOrUnmutedEvent$$module$src$iframe_video$$(this.$F$))))}}};_.$JSCompiler_prototypeAlias$$.$supportsPlatform$=function(){return!0};
_.$JSCompiler_prototypeAlias$$.$isInteractive$=function(){return!0};_.$JSCompiler_prototypeAlias$$.play=function(){$JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$sendCommand_$$(this,"playVideo")};_.$JSCompiler_prototypeAlias$$.pause=function(){$JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$sendCommand_$$(this,"pauseVideo")};
_.$JSCompiler_prototypeAlias$$.$mute$=function(){$JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$sendCommand_$$(this,"mute")};_.$JSCompiler_prototypeAlias$$.$unmute$=function(){$JSCompiler_StaticMethods_AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer_prototype$sendCommand_$$(this,"unMute")};_.$JSCompiler_prototypeAlias$$.$showControls$=function(){};_.$JSCompiler_prototypeAlias$$.$hideControls$=function(){};
_.$JSCompiler_prototypeAlias$$.$fullscreenEnter$=function(){this.$D$&&_.$fullscreenEnter$$module$src$dom$$(this.$D$)};_.$JSCompiler_prototypeAlias$$.$fullscreenExit$=function(){this.$D$&&_.$fullscreenExit$$module$src$dom$$(this.$D$)};_.$JSCompiler_prototypeAlias$$.getMetadata=function(){};_.$JSCompiler_prototypeAlias$$.$preimplementsMediaSessionAPI$=function(){return!0};_.$JSCompiler_prototypeAlias$$.$preimplementsAutoFullscreen$=function(){return!1};
_.$JSCompiler_prototypeAlias$$.$getCurrentTime$=function(){return 0};_.$JSCompiler_prototypeAlias$$.$getDuration$=function(){return 1};_.$JSCompiler_prototypeAlias$$.$getPlayedRanges$=function(){return[]};_.$JSCompiler_prototypeAlias$$.$seekTo$=function(){this.$user$().error("amp-mowplayer","`seekTo` not supported.")};self.AMP.registerElement("amp-mowplayer",$AmpMowplayer$$module$extensions$amp_mowplayer$0_1$amp_mowplayer$$);
})});

//# sourceMappingURL=amp-mowplayer-0.1.js.map
