(self.AMP=self.AMP||[]).push({n:"amp-position-observer",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer$$=function($$jscomp$super$this$jscomp$86_element$jscomp$586$$){$$jscomp$super$this$jscomp$86_element$jscomp$586$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$86_element$jscomp$586$$)||this;$$jscomp$super$this$jscomp$86_element$jscomp$586$$.$G$=null;$$jscomp$super$this$jscomp$86_element$jscomp$586$$.$P$=null;$$jscomp$super$this$jscomp$86_element$jscomp$586$$.$U$=null;$$jscomp$super$this$jscomp$86_element$jscomp$586$$.$D$=
!1;$$jscomp$super$this$jscomp$86_element$jscomp$586$$.$O$=0;$$jscomp$super$this$jscomp$86_element$jscomp$586$$.$F$=0;$$jscomp$super$this$jscomp$86_element$jscomp$586$$.$S$="0";$$jscomp$super$this$jscomp$86_element$jscomp$586$$.$R$="0";$$jscomp$super$this$jscomp$86_element$jscomp$586$$.$J$=0;$$jscomp$super$this$jscomp$86_element$jscomp$586$$.$X$=0;$$jscomp$super$this$jscomp$86_element$jscomp$586$$.$H$=null;$$jscomp$super$this$jscomp$86_element$jscomp$586$$.$M$=null;$$jscomp$super$this$jscomp$86_element$jscomp$586$$.$I$=
null;$$jscomp$super$this$jscomp$86_element$jscomp$586$$.$K$=0;$$jscomp$super$this$jscomp$86_element$jscomp$586$$.$W$=0;$$jscomp$super$this$jscomp$86_element$jscomp$586$$.$Y$=!1;$$jscomp$super$this$jscomp$86_element$jscomp$586$$.$V$=!1;return $$jscomp$super$this$jscomp$86_element$jscomp$586$$},$JSCompiler_StaticMethods_triggerScroll_$$=function($JSCompiler_StaticMethods_triggerScroll_$self$$){var $event$jscomp$181_scrolltop$$=_.$JSCompiler_StaticMethods_Viewport$$module$src$service$viewport$viewport_impl_prototype$getScrollTop$$($JSCompiler_StaticMethods_triggerScroll_$self$$.$U$);
$event$jscomp$181_scrolltop$$=_.$createCustomEvent$$module$src$event_helper$$($JSCompiler_StaticMethods_triggerScroll_$self$$.$win$,"amp-position-observer.scroll",_.$dict$$module$src$utils$object$$({percent:$JSCompiler_StaticMethods_triggerScroll_$self$$.$K$,positionObserverData:_.$dict$$module$src$utils$object$$({"start-scroll-offset":$event$jscomp$181_scrolltop$$,"end-scroll-offset":$event$jscomp$181_scrolltop$$+$JSCompiler_StaticMethods_triggerScroll_$self$$.$W$,"initial-inview-percent":$JSCompiler_StaticMethods_triggerScroll_$self$$.$K$})}));
$JSCompiler_StaticMethods_triggerScroll_$self$$.$G$.$trigger$($JSCompiler_StaticMethods_triggerScroll_$self$$.element,"scroll",$event$jscomp$181_scrolltop$$,1)},$JSCompiler_StaticMethods_AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer_prototype$parseAttributes_$$=function($JSCompiler_StaticMethods_AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer_prototype$parseAttributes_$self$$){var $margins$jscomp$4_ratios_topBottom_topBottom$318$$=
$JSCompiler_StaticMethods_AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer_prototype$parseAttributes_$self$$.element.getAttribute("intersection-ratios");$margins$jscomp$4_ratios_topBottom_topBottom$318$$&&($margins$jscomp$4_ratios_topBottom_topBottom$318$$=$margins$jscomp$4_ratios_topBottom_topBottom$318$$.trim().split(" "),$JSCompiler_StaticMethods_AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer_prototype$parseAttributes_$self$$.$O$=
parseFloat($margins$jscomp$4_ratios_topBottom_topBottom$318$$[0]),$JSCompiler_StaticMethods_AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer_prototype$parseAttributes_$self$$.$F$=$JSCompiler_StaticMethods_AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer_prototype$parseAttributes_$self$$.$O$,$margins$jscomp$4_ratios_topBottom_topBottom$318$$[1]&&($JSCompiler_StaticMethods_AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer_prototype$parseAttributes_$self$$.$F$=
parseFloat($margins$jscomp$4_ratios_topBottom_topBottom$318$$[1])));if($margins$jscomp$4_ratios_topBottom_topBottom$318$$=$JSCompiler_StaticMethods_AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer_prototype$parseAttributes_$self$$.element.getAttribute("viewport-margins"))$margins$jscomp$4_ratios_topBottom_topBottom$318$$=$margins$jscomp$4_ratios_topBottom_topBottom$318$$.trim().split(" "),$JSCompiler_StaticMethods_AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer_prototype$parseAttributes_$self$$.$S$=
$margins$jscomp$4_ratios_topBottom_topBottom$318$$[0],$JSCompiler_StaticMethods_AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer_prototype$parseAttributes_$self$$.$R$=$JSCompiler_StaticMethods_AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer_prototype$parseAttributes_$self$$.$S$,$margins$jscomp$4_ratios_topBottom_topBottom$318$$[1]&&($JSCompiler_StaticMethods_AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer_prototype$parseAttributes_$self$$.$R$=
$margins$jscomp$4_ratios_topBottom_topBottom$318$$[1]);$JSCompiler_StaticMethods_AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer_prototype$parseAttributes_$self$$.$M$=$JSCompiler_StaticMethods_AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer_prototype$parseAttributes_$self$$.element.getAttribute("target")},$JSCompiler_StaticMethods_validateAndResolveMargin_$$=function($JSCompiler_StaticMethods_validateAndResolveMargin_$self$$,
$num$jscomp$22_val$jscomp$25$$){$num$jscomp$22_val$jscomp$25$$=_.$parseLength$$module$src$layout$$($num$jscomp$22_val$jscomp$25$$);var $JSCompiler_inline_result$jscomp$904_length$jscomp$inline_4119$$=$num$jscomp$22_val$jscomp$25$$;$JSCompiler_inline_result$jscomp$904_length$jscomp$inline_4119$$;$JSCompiler_inline_result$jscomp$904_length$jscomp$inline_4119$$=$JSCompiler_inline_result$jscomp$904_length$jscomp$inline_4119$$.match(/[a-z]+/i)[0];$num$jscomp$22_val$jscomp$25$$=_.$getLengthNumeral$$module$src$layout$$($num$jscomp$22_val$jscomp$25$$);
if(!$num$jscomp$22_val$jscomp$25$$)return 0;"vh"==$JSCompiler_inline_result$jscomp$904_length$jscomp$inline_4119$$&&($num$jscomp$22_val$jscomp$25$$=$num$jscomp$22_val$jscomp$25$$/100*$JSCompiler_StaticMethods_validateAndResolveMargin_$self$$.$H$.height);return $num$jscomp$22_val$jscomp$25$$};_.$$jscomp$inherits$$($AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer$$,AMP.BaseElement);
$AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer$$.prototype.$buildCallback$=function(){_.$Services$$module$src$services$viewerForDoc$$(this.$getAmpDoc$()).$D$.then(this.$Z$.bind(this));this.$Y$=this.element.hasAttribute("once")};
$AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer$$.prototype.$Z$=function(){var $$jscomp$this$jscomp$854$$=this;$JSCompiler_StaticMethods_AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer_prototype$parseAttributes_$$(this);this.$G$=_.$Services$$module$src$services$actionServiceForDoc$$(this.element);this.$U$=_.$Services$$module$src$services$viewportForDoc$$(this.element);this.$P$||(_.$installPositionObserverServiceForDoc$$module$src$service$position_observer$position_observer_impl$$(this.$getAmpDoc$()),
this.$P$=_.$getServiceForDoc$$module$src$service$$(this.$getAmpDoc$(),"position-observer"));this.$getAmpDoc$().$whenReady$().then(function(){var $scene$jscomp$inline_4089$$;$$jscomp$this$jscomp$854$$.$M$?$scene$jscomp$inline_4089$$=_.$JSCompiler_StaticMethods_assertElement$$(_.$user$$module$src$log$$(),$$jscomp$this$jscomp$854$$.$getAmpDoc$().getElementById($$jscomp$this$jscomp$854$$.$M$),"No element found with id:"+$$jscomp$this$jscomp$854$$.$M$):$scene$jscomp$inline_4089$$=$$jscomp$this$jscomp$854$$.element.parentNode;
$$jscomp$this$jscomp$854$$.$getAmpDoc$().$getBody$()==$scene$jscomp$inline_4089$$&&($scene$jscomp$inline_4089$$=$$jscomp$this$jscomp$854$$.$win$.document.documentElement);$$jscomp$this$jscomp$854$$.$P$.observe($scene$jscomp$inline_4089$$,1,$$jscomp$this$jscomp$854$$.$aa$.bind($$jscomp$this$jscomp$854$$))})};
$AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer$$.prototype.$aa$=function($entry$jscomp$34_event$jscomp$inline_4108_relPos$$){if(!this.$Y$||!this.$V$){var $event$jscomp$inline_4111_totalProgress$jscomp$inline_4116_wasVisible$jscomp$1$$=this.$D$,$JSCompiler_inline_result$jscomp$908_prevViewportHeight_rect$jscomp$inline_4099_topOffset$jscomp$inline_4117$$=this.$H$&&this.$H$.height;this.$I$||(this.$I$=$entry$jscomp$34_event$jscomp$inline_4108_relPos$$.$viewportRect$.height);
var $positionRect$jscomp$2_viewportHeightChangeDelta$jscomp$inline_4093$$=this.$I$-$entry$jscomp$34_event$jscomp$inline_4108_relPos$$.$viewportRect$.height,$relativePos$jscomp$inline_4104_resizeOffset$jscomp$inline_4094$$=0;150>Math.abs($positionRect$jscomp$2_viewportHeightChangeDelta$jscomp$inline_4093$$)?$relativePos$jscomp$inline_4104_resizeOffset$jscomp$inline_4094$$=$positionRect$jscomp$2_viewportHeightChangeDelta$jscomp$inline_4093$$:this.$I$=null;$entry$jscomp$34_event$jscomp$inline_4108_relPos$$.$viewportRect$=
_.$layoutRectLtwh$$module$src$layout_rect$$($entry$jscomp$34_event$jscomp$inline_4108_relPos$$.$viewportRect$.left,$entry$jscomp$34_event$jscomp$inline_4108_relPos$$.$viewportRect$.top,$entry$jscomp$34_event$jscomp$inline_4108_relPos$$.$viewportRect$.width,$entry$jscomp$34_event$jscomp$inline_4108_relPos$$.$viewportRect$.height+$relativePos$jscomp$inline_4104_resizeOffset$jscomp$inline_4094$$);this.$H$=$entry$jscomp$34_event$jscomp$inline_4108_relPos$$.$viewportRect$;$JSCompiler_inline_result$jscomp$908_prevViewportHeight_rect$jscomp$inline_4099_topOffset$jscomp$inline_4117$$!=
$entry$jscomp$34_event$jscomp$inline_4108_relPos$$.$viewportRect$.height&&(this.$J$=$JSCompiler_StaticMethods_validateAndResolveMargin_$$(this,this.$S$),this.$X$=$JSCompiler_StaticMethods_validateAndResolveMargin_$$(this,this.$R$));$JSCompiler_inline_result$jscomp$908_prevViewportHeight_rect$jscomp$inline_4099_topOffset$jscomp$inline_4117$$=$entry$jscomp$34_event$jscomp$inline_4108_relPos$$.$viewportRect$;$JSCompiler_inline_result$jscomp$908_prevViewportHeight_rect$jscomp$inline_4099_topOffset$jscomp$inline_4117$$=
_.$layoutRectLtwh$$module$src$layout_rect$$($JSCompiler_inline_result$jscomp$908_prevViewportHeight_rect$jscomp$inline_4099_topOffset$jscomp$inline_4117$$.left,$JSCompiler_inline_result$jscomp$908_prevViewportHeight_rect$jscomp$inline_4099_topOffset$jscomp$inline_4117$$.top+this.$J$,$JSCompiler_inline_result$jscomp$908_prevViewportHeight_rect$jscomp$inline_4099_topOffset$jscomp$inline_4117$$.width,$JSCompiler_inline_result$jscomp$908_prevViewportHeight_rect$jscomp$inline_4099_topOffset$jscomp$inline_4117$$.height-
this.$X$-this.$J$);if($positionRect$jscomp$2_viewportHeightChangeDelta$jscomp$inline_4093$$=$entry$jscomp$34_event$jscomp$inline_4108_relPos$$.$positionRect$)if($relativePos$jscomp$inline_4104_resizeOffset$jscomp$inline_4094$$=$entry$jscomp$34_event$jscomp$inline_4108_relPos$$=_.$layoutRectsRelativePos$$module$src$layout_rect$$($positionRect$jscomp$2_viewportHeightChangeDelta$jscomp$inline_4093$$,$JSCompiler_inline_result$jscomp$908_prevViewportHeight_rect$jscomp$inline_4099_topOffset$jscomp$inline_4117$$),
"inside"==$relativePos$jscomp$inline_4104_resizeOffset$jscomp$inline_4094$$)this.$D$=!0;else{var $offset$jscomp$inline_4105$$=$positionRect$jscomp$2_viewportHeightChangeDelta$jscomp$inline_4093$$.height*("top"==$relativePos$jscomp$inline_4104_resizeOffset$jscomp$inline_4094$$?this.$O$:this.$F$);this.$D$="bottom"==$relativePos$jscomp$inline_4104_resizeOffset$jscomp$inline_4094$$?$positionRect$jscomp$2_viewportHeightChangeDelta$jscomp$inline_4093$$.top<=$JSCompiler_inline_result$jscomp$908_prevViewportHeight_rect$jscomp$inline_4099_topOffset$jscomp$inline_4117$$.bottom-
$offset$jscomp$inline_4105$$:$positionRect$jscomp$2_viewportHeightChangeDelta$jscomp$inline_4093$$.bottom>=$JSCompiler_inline_result$jscomp$908_prevViewportHeight_rect$jscomp$inline_4099_topOffset$jscomp$inline_4117$$.top+$offset$jscomp$inline_4105$$}else this.$D$=!1,$entry$jscomp$34_event$jscomp$inline_4108_relPos$$=$entry$jscomp$34_event$jscomp$inline_4108_relPos$$.$relativePos$;$event$jscomp$inline_4111_totalProgress$jscomp$inline_4116_wasVisible$jscomp$1$$&&!this.$D$&&(this.$K$="bottom"==$entry$jscomp$34_event$jscomp$inline_4108_relPos$$?
0:1,$JSCompiler_StaticMethods_triggerScroll_$$(this),$entry$jscomp$34_event$jscomp$inline_4108_relPos$$=_.$createCustomEvent$$module$src$event_helper$$(this.$win$,"amp-position-observer.exit",_.$dict$$module$src$utils$object$$({})),this.$G$.$trigger$(this.element,"exit",$entry$jscomp$34_event$jscomp$inline_4108_relPos$$,1),this.$V$=!0);!$event$jscomp$inline_4111_totalProgress$jscomp$inline_4116_wasVisible$jscomp$1$$&&this.$D$&&($event$jscomp$inline_4111_totalProgress$jscomp$inline_4116_wasVisible$jscomp$1$$=
_.$createCustomEvent$$module$src$event_helper$$(this.$win$,"amp-position-observer.enter",_.$dict$$module$src$utils$object$$({})),this.$G$.$trigger$(this.element,"enter",$event$jscomp$inline_4111_totalProgress$jscomp$inline_4116_wasVisible$jscomp$1$$,1));this.$D$&&($positionRect$jscomp$2_viewportHeightChangeDelta$jscomp$inline_4093$$&&($event$jscomp$inline_4111_totalProgress$jscomp$inline_4116_wasVisible$jscomp$1$$=$JSCompiler_inline_result$jscomp$908_prevViewportHeight_rect$jscomp$inline_4099_topOffset$jscomp$inline_4117$$.height+
$positionRect$jscomp$2_viewportHeightChangeDelta$jscomp$inline_4093$$.height-($positionRect$jscomp$2_viewportHeightChangeDelta$jscomp$inline_4093$$.height*this.$F$+$positionRect$jscomp$2_viewportHeightChangeDelta$jscomp$inline_4093$$.height*this.$O$),$JSCompiler_inline_result$jscomp$908_prevViewportHeight_rect$jscomp$inline_4099_topOffset$jscomp$inline_4117$$=Math.abs($positionRect$jscomp$2_viewportHeightChangeDelta$jscomp$inline_4093$$.top-this.$J$-($JSCompiler_inline_result$jscomp$908_prevViewportHeight_rect$jscomp$inline_4099_topOffset$jscomp$inline_4117$$.height-
$positionRect$jscomp$2_viewportHeightChangeDelta$jscomp$inline_4093$$.height*this.$F$)),this.$K$=$JSCompiler_inline_result$jscomp$908_prevViewportHeight_rect$jscomp$inline_4099_topOffset$jscomp$inline_4117$$/$event$jscomp$inline_4111_totalProgress$jscomp$inline_4116_wasVisible$jscomp$1$$,this.$W$=$event$jscomp$inline_4111_totalProgress$jscomp$inline_4116_wasVisible$jscomp$1$$-$JSCompiler_inline_result$jscomp$908_prevViewportHeight_rect$jscomp$inline_4099_topOffset$jscomp$inline_4117$$),$JSCompiler_StaticMethods_triggerScroll_$$(this))}};
self.AMP.registerElement("amp-position-observer",$AmpVisibilityObserver$$module$extensions$amp_position_observer$0_1$amp_position_observer$$);
})});

//# sourceMappingURL=amp-position-observer-0.1.js.map
