(self.AMP=self.AMP||[]).push({n:"amp-riddle-quiz",i:["_base_i","_base_misc"],v:"1904281823091",f:(function(AMP,_){
var $AmpRiddleQuiz$$module$extensions$amp_riddle_quiz$0_1$amp_riddle_quiz$$=function($$jscomp$super$this$jscomp$90_element$jscomp$592$$){$$jscomp$super$this$jscomp$90_element$jscomp$592$$=AMP.BaseElement.call(this,$$jscomp$super$this$jscomp$90_element$jscomp$592$$)||this;$$jscomp$super$this$jscomp$90_element$jscomp$592$$.$D$=null;$$jscomp$super$this$jscomp$90_element$jscomp$592$$.$F$=400;$$jscomp$super$this$jscomp$90_element$jscomp$592$$.$H$="";$$jscomp$super$this$jscomp$90_element$jscomp$592$$.$G$=
null;return $$jscomp$super$this$jscomp$90_element$jscomp$592$$},$JSCompiler_StaticMethods_riddleHeightChanged_$$=function($JSCompiler_StaticMethods_riddleHeightChanged_$self$$,$height$jscomp$72$$){_.$isFiniteNumber$$module$src$types$$($height$jscomp$72$$)&&$height$jscomp$72$$!==$JSCompiler_StaticMethods_riddleHeightChanged_$self$$.$F$&&($JSCompiler_StaticMethods_riddleHeightChanged_$self$$.$F$=$height$jscomp$72$$,_.$JSCompiler_StaticMethods_attemptChangeHeight$$($JSCompiler_StaticMethods_riddleHeightChanged_$self$$,
$JSCompiler_StaticMethods_riddleHeightChanged_$self$$.$F$).catch(function(){}))};_.$$jscomp$inherits$$($AmpRiddleQuiz$$module$extensions$amp_riddle_quiz$0_1$amp_riddle_quiz$$,AMP.BaseElement);
$AmpRiddleQuiz$$module$extensions$amp_riddle_quiz$0_1$amp_riddle_quiz$$.prototype.$I$=function($data$jscomp$206_event$jscomp$183$$){this.$D$&&"https://www.riddle.com"==$data$jscomp$206_event$jscomp$183$$.origin&&$data$jscomp$206_event$jscomp$183$$.source==this.$D$.contentWindow&&($data$jscomp$206_event$jscomp$183$$=$data$jscomp$206_event$jscomp$183$$.data,_.$isObject$$module$src$types$$($data$jscomp$206_event$jscomp$183$$)&&void 0!=$data$jscomp$206_event$jscomp$183$$.riddleId&&$data$jscomp$206_event$jscomp$183$$.riddleId==
this.$H$&&$JSCompiler_StaticMethods_riddleHeightChanged_$$(this,$data$jscomp$206_event$jscomp$183$$.riddleHeight))};$AmpRiddleQuiz$$module$extensions$amp_riddle_quiz$0_1$amp_riddle_quiz$$.prototype.$isLayoutSupported$=function($layout$jscomp$99$$){return _.$isLayoutSizeDefined$$module$src$layout$$($layout$jscomp$99$$)};
$AmpRiddleQuiz$$module$extensions$amp_riddle_quiz$0_1$amp_riddle_quiz$$.prototype.$layoutCallback$=function(){this.$H$=this.element.getAttribute("data-riddle-id");this.$G$=_.$listen$$module$src$event_helper$$(this.$win$,"message",this.$I$.bind(this));var $iframe$jscomp$81$$=this.element.ownerDocument.createElement("iframe");this.$D$=$iframe$jscomp$81$$;$iframe$jscomp$81$$.setAttribute("scrolling","no");$iframe$jscomp$81$$.setAttribute("frameborder","0");$iframe$jscomp$81$$.setAttribute("allowtransparency",
"true");$iframe$jscomp$81$$.setAttribute("allowfullscreen","true");$iframe$jscomp$81$$.src="https://www.riddle.com/a/iframe/"+encodeURIComponent(this.$H$);_.$JSCompiler_StaticMethods_applyFillContent$$($iframe$jscomp$81$$);this.element.appendChild($iframe$jscomp$81$$);return this.$loadPromise$($iframe$jscomp$81$$)};
$AmpRiddleQuiz$$module$extensions$amp_riddle_quiz$0_1$amp_riddle_quiz$$.prototype.$unlayoutCallback$=function(){this.$G$&&this.$G$();this.$D$&&(_.$removeElement$$module$src$dom$$(this.$D$),this.$D$=null);return!0};self.AMP.registerElement("amp-riddle-quiz",$AmpRiddleQuiz$$module$extensions$amp_riddle_quiz$0_1$amp_riddle_quiz$$,!1);
})});

//# sourceMappingURL=amp-riddle-quiz-0.1.js.map
