@startuml
box "AMP Client"
    participant AMPskimlinks as "amp-skimlinks"
end box

[-> AMPskimlinks: User visits AMP page.

==  on buildCallback ==
hnote over AMPskimlinks: Initialize amp-skimlinks
hnote over AMPskimlinks: Parse links in page
AMPskimlinks -> DomainResolverAPI as "Merchant Domain Resolver API \n (r.skimresources.com)": Request (GET): [domainA, domainB, domainC]?
note left
    Send all domains found in the
    page to our API and resolve
    which ones can be affiliated.
end note
DomainResolverAPI --> AMPskimlinks: Response: { DomainA: yes, domainB: false, domainC: false }
hnote over AMPskimlinks: Swap monetizable links
hnote over AMPskimlinks: Prepare tracking data
AMPskimlinks -> TrackingAPI as "Tracking API \n (t.skimresources.com)": Page impression tracking (POST): data={...}
TrackingAPI --> AMPskimlinks:
|||
AMPskimlinks -> TrackingAPI: Link impressions tracking (POST): data={...}
TrackingAPI --> AMPskimlinks:

== On DOM changes ==
hnote over AMPskimlinks: DOM changes handler
... Buffer DOM changes for X ms ...
AMPskimlinks -> DomainResolverAPI: Request (GET): [domainD, domainE]?
note left
    Send all **new** domains found in the
    page to our API.
end note
DomainResolverAPI --> AMPskimlinks: Response: { DomainD: yes, domainE: false }
hnote over AMPskimlinks: Swap monetizable links.

== On anchor click ==
'IF
AMPskimlinks -> AffiliationAPI as "Affiliation API \n (go.skimresources.com)": Navigate to affiliated url
note left AMPskimlinks #68b17a: **IF** link is affiliated
activate AMPskimlinks #68b17a
|||
AffiliationAPI ->] : Redirect to merchant page
deactivate AMPskimlinks

|||

' ELSE
AMPskimlinks -> TrackingAPI: Track non-affiliated click (sendBeacon, POST)
activate AMPskimlinks #orange
TrackingAPI --> AMPskimlinks
note left AMPskimlinks #orange: **ELSE** (link is not affiliated)
|||
AMPskimlinks ->] : Navigate to url
deactivate AMPskimlinks

' alt link is not affiliated
'     AMPskimlinks -> TrackingAPI: Track non-affilaited click (POST)
'     AMPskimlinks ->] : Go to Merchant page
' else link is affiliated
'     |||
'     AMPskimlinks -> AffiliationAPI: Affiliated click
'     AffiliationAPI ->] : Redirect to Merchant page
' end

box "Skimlinks APIs" #LightBlue
	participant DomainResolverAPI
    participant TrackingAPI
    participant AffiliationAPI
end box

@enduml