daysUntilStale: 358 # 1Y - 7d
daysUntilClose: 7
staleLabel: Stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed in 7 days if no further activity occurs. Thank you
  for your contributions.
closeComment: false
