comment: off
coverage:
  status:
    project:
      default:
        base: auto
        target: auto
        threshold: 100
    patch:
      default:
        base: auto
        target: 100
        threshold: 100
