# Overall settings for PR integration via codecov.io
# See https://docs.codecov.io/docs/codecovyml-reference
codecov:
  bot: 'amp-coverage-bot'
  ci:
    - 'travis.org'
  max_report_age: 24
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

# Pull request comments disabled because they were too noisy
# See https://docs.codecov.io/docs/pull-request-comments
comment: false

# Separate PR statuses for project-level and patch-level coverage
# See https://docs.codecov.io/docs/commit-status
coverage:
  precision: 2
  round: down
  range: '80...100'
  status:
    project:
      default:
        base: auto
        if_not_found: success
        informational: true # TODO(rsimha): Remove this line after testing
        only_pulls: true
        target: 80%
        threshold: 10%
    patch:
      default:
        base: auto
        informational: true # TODO(rsimha): Remove this line after testing
        if_not_found: success
        only_pulls: true
        target: 80%
        threshold: 10%
