# Settings for https://codecov.io integration

# See https://docs.codecov.io/docs/pull-request-comments
comment: off

# See https://docs.codecov.io/v4.3.0/docs/commit-status
coverage:
  status:
    project:
      base: auto # Use base commit for PRs, parent commit for push builds
      target: auto # Target same coverage as the base / parent commit
      threshold: 10 # Total project coverage must be within 10% of base / parent commit
    patch:
      base: auto # Use base commit for PRs, parent commit for push builds
      target: 100 # Target 100% coverage for diffs
      threshold: 50 # Patch coverage must be within 50% of target (at least 50%)
