name: amphtml

services:
  appserver:
    type: node:10
    build_as_root:
      - curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
    build:
      - yarn global add gulp-cli
      - yarn
    run_as_root:
      - echo "127.0.0.1 amphtml.lndo.site" >> /etc/hosts
    command: cd /app && yarn gulp serve --port=80 --host=0.0.0.0

tooling:
  yarn:
    service: appserver
  gulp:
    service: appserver
    cmd: "yarn gulp"
  watch:
    service: appserver
    cmd: "yarn gulp watch"
    description: "Watches for changes in files, re-builds when detected"
  check-types:
    service: appserver
    cmd: "yarn gulp check-types"
    description: "Check source code for JS type errors"
  dist:
    service: appserver
    cmd: "yarn gulp dist"
    description: "Build production binaries"
  unit:
    service: appserver
    cmd: "yarn gulp unit"
    description: "Run unit tests"
  integration:
    service: appserver
    cmd: "yarn gulp integration"
    description: "Run integration tests"
  e2e:
    service: appserver
    cmd: "yarn gulp e2e"
    description: "Runs e2e tests"

proxy:
  appserver:
    - amphtml.lndo.site
