const madge = require('madge');

const common = [
  'extensions/amp-ad/0.1/amp-ad.js',
  'extensions/amp-accordion/0.1/amp-accordion.js',
  'extensions/amp-carousel/0.1/amp-carousel.js',
];

const ads = [
  'extensions/amp-ad-exit/0.1/amp-ad-exit.js',
  'extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js',
  'extensions/amp-ad-network-adzerk-impl/0.1/amp-ad-network-adzerk-impl.js',
  'extensions/amp-ad-network-cloudflare-impl/0.1/' +
      'amp-ad-network-cloudflare-impl.js',
  'extensions/amp-ad-network-doubleclick-impl/0.1/' +
      'amp-ad-network-doubleclick-impl.js',
  'extensions/amp-ad-network-fake-impl/0.1/amp-ad-network-fake-impl.js',
  'extensions/amp-ad-network-gmossp-impl/0.1/amp-ad-network-gmossp-impl.js',
  'extensions/amp-ad-network-triplelift-impl/0.1/' +
      'amp-ad-network-triplelift-impl.js',
  'extensions/amp-auto-ads/0.1/amp-auto-ads.js',
];

const media = [
  'extensions/amp-brightcove/0.1/amp-brightcove.js',
  'extensions/amp-dailymotion/0.1/amp-dailymotion.js',
  'extensions/amp-ima-video/0.1/amp-ima-video.js',
  'extensions/amp-video-service/0.1/amp-video-service.js',
  'extensions/amp-video/0.1/amp-video.js',
  'extensions/amp-3q-player/0.1/amp-3q-player.js',
  'extensions/amp-brid-player/0.1/amp-brid-player.js',
  'extensions/amp-jwplayer/0.1/amp-jwplayer.js',
  'extensions/amp-kaltura-player/0.1/amp-kaltura-player.js',
  'extensions/amp-nexxtv-player/0.1/amp-nexxtv-player.js',
  'extensions/amp-o2-player/0.1/amp-o2-player.js',
  'extensions/amp-ooyala-player/0.1/amp-ooyala-player.js',
  'extensions/amp-reach-player/0.1/amp-reach-player.js',
  'extensions/amp-springboard-player/0.1/amp-springboard-player.js',
  'extensions/amp-wistia-player/0.1/amp-wistia-player.js',
  'extensions/amp-youtube/0.1/amp-youtube.js',
  'extensions/amp-gfycat/0.1/amp-gfycat.js',
  'extensions/amp-3d-gltf/0.1/amp-3d-gltf.js',
  'extensions/amp-apester-media/0.1/amp-apester-media.js',
  'extensions/amp-google-vrview-image/0.1/amp-google-vrview-image.js',
  'extensions/amp-hulu/0.1/amp-hulu.js',
  'extensions/amp-anim/0.1/amp-anim.js',
  'extensions/amp-imgur/0.1/amp-imgur.js',
  'extensions/amp-izlesene/0.1/amp-izlesene.js',
  'extensions/amp-playbuzz/0.1/amp-playbuzz.js',
  'extensions/amp-soundcloud/0.1/amp-soundcloud.js',
  'extensions/amp-audio/0.1/amp-audio.js',
  'extensions/amp-bodymovin-animation/0.1/amp-bodymovin-animation.js',
  'extensions/amp-vimeo/0.1/amp-vimeo.js',
];

const all = [
  'extensions/amp-a4a/0.1/amp-a4a.js',
  'extensions/amp-access-laterpay/0.1/amp-access-laterpay.js',
  'extensions/amp-access-scroll/0.1/amp-access-scroll.js',
  'extensions/amp-access/0.1/amp-access.js',
  'extensions/amp-addthis/0.1/amp-addthis.js',
  'extensions/amp-analytics/0.1/amp-analytics.js',
  'extensions/amp-animation/0.1/amp-animation.js',
  'extensions/amp-app-banner/0.1/amp-app-banner.js',
  'extensions/amp-beopinion/0.1/amp-beopinion.js',
  'extensions/amp-bind/0.1/amp-bind.js',
  'extensions/amp-byside-content/0.1/amp-byside-content.js',
  'extensions/amp-call-tracking/0.1/amp-call-tracking.js',
  'extensions/amp-compare-slider/0.1/amp-compare-slider.js',
  'extensions/amp-consent/0.1/amp-consent.js',
  'extensions/amp-crypto-polyfill/0.1/amp-crypto-polyfill.js',
  'extensions/amp-date-picker/0.1/amp-date-picker.js',
  'extensions/amp-dynamic-css-classes/0.1/amp-dynamic-css-classes.js',
  'extensions/amp-experiment/0.1/amp-experiment.js',
  'extensions/amp-facebook-comments/0.1/amp-facebook-comments.js',
  'extensions/amp-facebook-like/0.1/amp-facebook-like.js',
  'extensions/amp-facebook-page/0.1/amp-facebook-page.js',
  'extensions/amp-facebook/0.1/amp-facebook.js',
  'extensions/amp-fit-text/0.1/amp-fit-text.js',
  'extensions/amp-font/0.1/amp-font.js',
  'extensions/amp-form/0.1/amp-form.js',
  'extensions/amp-fx-collection/0.1/amp-fx-collection.js',
  'extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js',
  'extensions/amp-geo/0.1/amp-geo.js',
  'extensions/amp-gist/0.1/amp-gist.js',
  'extensions/amp-gwd-animation/0.1/amp-gwd-animation.js',
  'extensions/amp-iframe/0.1/amp-iframe.js',
  'extensions/amp-image-lightbox/0.1/amp-image-lightbox.js',
  'extensions/amp-image-viewer/0.1/amp-image-viewer.js',
  'extensions/amp-instagram/0.1/amp-instagram.js',
  'extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js',
  'extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js',
  'extensions/amp-lightbox/0.1/amp-lightbox.js',
  'extensions/amp-list/0.1/amp-list.js',
  'extensions/amp-live-list/0.1/amp-live-list.js',
  'extensions/amp-mathml/0.1/amp-mathml.js',
  'extensions/amp-mustache/0.1/amp-mustache.js',
  'extensions/amp-next-page/0.1/amp-next-page.js',
  'extensions/amp-pinterest/0.1/amp-pinterest.js',
  'extensions/amp-position-observer/0.1/amp-position-observer.js',
  'extensions/amp-reddit/0.1/amp-reddit.js',
  'extensions/amp-riddle-quiz/0.1/amp-riddle-quiz.js',
  'extensions/amp-selector/0.1/amp-selector.js',
  'extensions/amp-share-tracking/0.1/amp-share-tracking.js',
  'extensions/amp-sidebar/0.1/amp-sidebar.js',
  'extensions/amp-slides/0.1/amp-slides.js',
  'extensions/amp-social-share/0.1/amp-social-share.js',
  'extensions/amp-sticky-ad/1.0/amp-sticky-ad.js',
  'extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js',
  'extensions/amp-story/0.1/amp-story.js',
  'extensions/amp-timeago/0.1/amp-timeago.js',
  'extensions/amp-twitter/0.1/amp-twitter.js',
  'extensions/amp-user-notification/0.1/amp-user-notification.js',
  'extensions/amp-viewer-integration/0.1/amp-viewer-integration.js',
  'extensions/amp-vine/0.1/amp-vine.js',
  'extensions/amp-viz-vega/0.1/amp-viz-vega.js',
  'extensions/amp-vk/0.1/amp-vk.js',
  'extensions/amp-web-push/0.1/amp-web-push.js',
];

madge(['src/amp.js'].concat(all, ads, common, media), {
    fontSize: '8px',
  })
  .then((res) => res.image('madge.svg'))
  .then((writtenImagePath) => {
    console.log('Image written to ' + writtenImagePath);
  });
