(self.AMP=self.AMP||[]).push({n:"amp-izlesene",v:"1904281823091",f:(function(AMP,_){
var $$jscomp$objectCreate$$="function"==typeof Object.create?Object.create:function($prototype$$){function $ctor$$(){}$ctor$$.prototype=$prototype$$;return new $ctor$$},$JSCompiler_temp$jscomp$10$$;
if("function"==typeof Object.setPrototypeOf)$JSCompiler_temp$jscomp$10$$=Object.setPrototypeOf;else{var $JSCompiler_inline_result$jscomp$11$$;a:{var $JSCompiler_x$jscomp$inline_13$$={a:!0},$JSCompiler_y$jscomp$inline_14$$={};try{$JSCompiler_y$jscomp$inline_14$$.__proto__=$JSCompiler_x$jscomp$inline_13$$;$JSCompiler_inline_result$jscomp$11$$=$JSCompiler_y$jscomp$inline_14$$.a;break a}catch($JSCompiler_e$jscomp$inline_15$$){}$JSCompiler_inline_result$jscomp$11$$=!1}$JSCompiler_temp$jscomp$10$$=$JSCompiler_inline_result$jscomp$11$$?
function($target$jscomp$83$$,$proto$jscomp$3$$){$target$jscomp$83$$.__proto__=$proto$jscomp$3$$;if($target$jscomp$83$$.__proto__!==$proto$jscomp$3$$)throw new TypeError($target$jscomp$83$$+" is not extensible");return $target$jscomp$83$$}:null}var $$jscomp$setPrototypeOf$$=$JSCompiler_temp$jscomp$10$$;self.log=self.log||{user:null,dev:null,userForEmbed:null};var $logs$$module$src$log$$=self.log;function $dict$$module$src$utils$object$$($opt_initial$jscomp$1$$){return $opt_initial$jscomp$1$$||{}};$dict$$module$src$utils$object$$({c:!0,v:!0,a:!0,ad:!0,action:!0});/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function $getDataParamsFromAttributes$$module$src$dom$$($element$jscomp$18_params$jscomp$5$$){var $opt_computeParamNameFunc$$,$opt_paramPattern$$,$computeParamNameFunc$$=$opt_computeParamNameFunc$$||function($element$jscomp$18_params$jscomp$5$$){return $element$jscomp$18_params$jscomp$5$$},$dataset$$=$element$jscomp$18_params$jscomp$5$$.dataset;$element$jscomp$18_params$jscomp$5$$={};var $paramPattern$$=$opt_paramPattern$$?$opt_paramPattern$$:/^param(.+)/,$key$jscomp$46$$;for($key$jscomp$46$$ in $dataset$$){var $matches$$=
$key$jscomp$46$$.match($paramPattern$$);$matches$$&&($element$jscomp$18_params$jscomp$5$$[$computeParamNameFunc$$($matches$$[1][0].toLowerCase()+$matches$$[1].substr(1))]=$dataset$$[$key$jscomp$46$$])}return $element$jscomp$18_params$jscomp$5$$};function $AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$($$jscomp$super$this_element$jscomp$40$$){$$jscomp$super$this_element$jscomp$40$$=AMP.BaseElement.call(this,$$jscomp$super$this_element$jscomp$40$$)||this;$$jscomp$super$this_element$jscomp$40$$.$videoid_$=null;$$jscomp$super$this_element$jscomp$40$$.$iframe_$=null;$$jscomp$super$this_element$jscomp$40$$.$videoIframeSrc_$=null;return $$jscomp$super$this_element$jscomp$40$$}var $JSCompiler_parentCtor$jscomp$inline_18$$=AMP.BaseElement;
$AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$.prototype=$$jscomp$objectCreate$$($JSCompiler_parentCtor$jscomp$inline_18$$.prototype);$AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$.prototype.constructor=$AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$;
if($$jscomp$setPrototypeOf$$)$$jscomp$setPrototypeOf$$($AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$,$JSCompiler_parentCtor$jscomp$inline_18$$);else for(var $JSCompiler_p$jscomp$inline_19$$ in $JSCompiler_parentCtor$jscomp$inline_18$$)if("prototype"!=$JSCompiler_p$jscomp$inline_19$$)if(Object.defineProperties){var $JSCompiler_descriptor$jscomp$inline_20$$=Object.getOwnPropertyDescriptor($JSCompiler_parentCtor$jscomp$inline_18$$,$JSCompiler_p$jscomp$inline_19$$);$JSCompiler_descriptor$jscomp$inline_20$$&&
Object.defineProperty($AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$,$JSCompiler_p$jscomp$inline_19$$,$JSCompiler_descriptor$jscomp$inline_20$$)}else $AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$[$JSCompiler_p$jscomp$inline_19$$]=$JSCompiler_parentCtor$jscomp$inline_18$$[$JSCompiler_p$jscomp$inline_19$$];$AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$.$superClass_$=$JSCompiler_parentCtor$jscomp$inline_18$$.prototype;
$AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$.prototype.preconnectCallback=function($opt_onLayout$$){this.preconnect.url($JSCompiler_StaticMethods_getVideoIframeSrc_$$(this));this.preconnect.url("https://i1.imgiz.com",$opt_onLayout$$)};
$AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$.prototype.isLayoutSupported=function($layout$jscomp$3$$){return"fixed"==$layout$jscomp$3$$||"fixed-height"==$layout$jscomp$3$$||"responsive"==$layout$jscomp$3$$||"fill"==$layout$jscomp$3$$||"flex-item"==$layout$jscomp$3$$||"fluid"==$layout$jscomp$3$$||"intrinsic"==$layout$jscomp$3$$};
$AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$.prototype.buildCallback=function(){var $JSCompiler_shouldBeTrueish$jscomp$inline_22$$=this.element.getAttribute("data-videoid"),$JSCompiler_opt_1$jscomp$inline_23$$=this.element;if(!$logs$$module$src$log$$.user)throw Error("failed to call initLogConstructor");this.$videoid_$=$logs$$module$src$log$$.user.assert($JSCompiler_shouldBeTrueish$jscomp$inline_22$$,"The data-videoid attribute is required for <amp-izlesene> %s",$JSCompiler_opt_1$jscomp$inline_23$$,
void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};
function $JSCompiler_StaticMethods_getVideoIframeSrc_$$($JSCompiler_StaticMethods_getVideoIframeSrc_$self$$){if($JSCompiler_StaticMethods_getVideoIframeSrc_$self$$.$videoIframeSrc_$)return $JSCompiler_StaticMethods_getVideoIframeSrc_$self$$.$videoIframeSrc_$;var $JSCompiler_mainAndFragment$jscomp$inline_49_JSCompiler_temp_const$jscomp$35_src$jscomp$4$$="https://www.izlesene.com/embedplayer/"+encodeURIComponent($JSCompiler_StaticMethods_getVideoIframeSrc_$self$$.$videoid_$||"")+"/?",$JSCompiler_inline_result$jscomp$36_JSCompiler_newUrl$jscomp$inline_51_params$jscomp$6$$=
$getDataParamsFromAttributes$$module$src$dom$$($JSCompiler_StaticMethods_getVideoIframeSrc_$self$$.element);"autoplay"in $JSCompiler_inline_result$jscomp$36_JSCompiler_newUrl$jscomp$inline_51_params$jscomp$6$$&&delete $JSCompiler_inline_result$jscomp$36_JSCompiler_newUrl$jscomp$inline_51_params$jscomp$6$$.autoplay;var $JSCompiler_s$jscomp$inline_39$$=[];for($JSCompiler_k$jscomp$inline_40_JSCompiler_mainAndQuery$jscomp$inline_50$$ in $JSCompiler_inline_result$jscomp$36_JSCompiler_newUrl$jscomp$inline_51_params$jscomp$6$$){var $JSCompiler_v$jscomp$inline_41_sv$1$jscomp$inline_44$$=
$JSCompiler_inline_result$jscomp$36_JSCompiler_newUrl$jscomp$inline_51_params$jscomp$6$$[$JSCompiler_k$jscomp$inline_40_JSCompiler_mainAndQuery$jscomp$inline_50$$];if(null!=$JSCompiler_v$jscomp$inline_41_sv$1$jscomp$inline_44$$)if(Array.isArray($JSCompiler_v$jscomp$inline_41_sv$1$jscomp$inline_44$$))for(var $JSCompiler_i$jscomp$inline_42$$=0;$JSCompiler_i$jscomp$inline_42$$<$JSCompiler_v$jscomp$inline_41_sv$1$jscomp$inline_44$$.length;$JSCompiler_i$jscomp$inline_42$$++){var $JSCompiler_sv$jscomp$inline_43$$=
$JSCompiler_v$jscomp$inline_41_sv$1$jscomp$inline_44$$[$JSCompiler_i$jscomp$inline_42$$];$JSCompiler_s$jscomp$inline_39$$.push(encodeURIComponent($JSCompiler_k$jscomp$inline_40_JSCompiler_mainAndQuery$jscomp$inline_50$$)+"="+encodeURIComponent($JSCompiler_sv$jscomp$inline_43$$))}else $JSCompiler_s$jscomp$inline_39$$.push(encodeURIComponent($JSCompiler_k$jscomp$inline_40_JSCompiler_mainAndQuery$jscomp$inline_50$$)+"="+encodeURIComponent($JSCompiler_v$jscomp$inline_41_sv$1$jscomp$inline_44$$))}$JSCompiler_inline_result$jscomp$36_JSCompiler_newUrl$jscomp$inline_51_params$jscomp$6$$=
$JSCompiler_s$jscomp$inline_39$$.join("&");if($JSCompiler_inline_result$jscomp$36_JSCompiler_newUrl$jscomp$inline_51_params$jscomp$6$$){$JSCompiler_mainAndFragment$jscomp$inline_49_JSCompiler_temp_const$jscomp$35_src$jscomp$4$$=$JSCompiler_mainAndFragment$jscomp$inline_49_JSCompiler_temp_const$jscomp$35_src$jscomp$4$$.split("#",2);var $JSCompiler_k$jscomp$inline_40_JSCompiler_mainAndQuery$jscomp$inline_50$$=$JSCompiler_mainAndFragment$jscomp$inline_49_JSCompiler_temp_const$jscomp$35_src$jscomp$4$$[0].split("?",
2);$JSCompiler_inline_result$jscomp$36_JSCompiler_newUrl$jscomp$inline_51_params$jscomp$6$$=$JSCompiler_k$jscomp$inline_40_JSCompiler_mainAndQuery$jscomp$inline_50$$[0]+($JSCompiler_k$jscomp$inline_40_JSCompiler_mainAndQuery$jscomp$inline_50$$[1]?"?"+$JSCompiler_k$jscomp$inline_40_JSCompiler_mainAndQuery$jscomp$inline_50$$[1]+"&"+$JSCompiler_inline_result$jscomp$36_JSCompiler_newUrl$jscomp$inline_51_params$jscomp$6$$:"?"+$JSCompiler_inline_result$jscomp$36_JSCompiler_newUrl$jscomp$inline_51_params$jscomp$6$$);
$JSCompiler_mainAndFragment$jscomp$inline_49_JSCompiler_temp_const$jscomp$35_src$jscomp$4$$=$JSCompiler_inline_result$jscomp$36_JSCompiler_newUrl$jscomp$inline_51_params$jscomp$6$$+=$JSCompiler_mainAndFragment$jscomp$inline_49_JSCompiler_temp_const$jscomp$35_src$jscomp$4$$[1]?"#"+$JSCompiler_mainAndFragment$jscomp$inline_49_JSCompiler_temp_const$jscomp$35_src$jscomp$4$$[1]:""}return $JSCompiler_StaticMethods_getVideoIframeSrc_$self$$.$videoIframeSrc_$=$JSCompiler_mainAndFragment$jscomp$inline_49_JSCompiler_temp_const$jscomp$35_src$jscomp$4$$}
$AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$.prototype.layoutCallback=function(){var $iframe$$=this.element.ownerDocument.createElement("iframe"),$src$jscomp$5$$=$JSCompiler_StaticMethods_getVideoIframeSrc_$$(this);$iframe$$.setAttribute("frameborder","0");$iframe$$.setAttribute("allowfullscreen","true");$iframe$$.src=$src$jscomp$5$$;this.applyFillContent($iframe$$);this.element.appendChild($iframe$$);this.$iframe_$=$iframe$$;return this.loadPromise($iframe$$)};
$AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$.prototype.pauseCallback=function(){this.$iframe_$&&this.$iframe_$.contentWindow&&this.$iframe_$.contentWindow.postMessage($dict$$module$src$utils$object$$({command:"pause"}),"*")};(function($AMP$jscomp$1$$){$AMP$jscomp$1$$.registerElement("amp-izlesene",$AmpIzlesene$$module$extensions$amp_izlesene$0_1$amp_izlesene$$)})(self.AMP);
})});

//# sourceMappingURL=amp-izlesene-0.1.js.map
