(self.AMP=self.AMP||[]).push({n:"amp-apester-media",v:"1904281823091",f:(function(AMP,_){
var $JSCompiler_prototypeAlias$$,$$jscomp$objectCreate$$="function"==typeof Object.create?Object.create:function($prototype$$){function $ctor$$(){}$ctor$$.prototype=$prototype$$;return new $ctor$$},$JSCompiler_temp$jscomp$17$$;
if("function"==typeof Object.setPrototypeOf)$JSCompiler_temp$jscomp$17$$=Object.setPrototypeOf;else{var $JSCompiler_inline_result$jscomp$18$$;a:{var $JSCompiler_x$jscomp$inline_40$$={a:!0},$JSCompiler_y$jscomp$inline_41$$={};try{$JSCompiler_y$jscomp$inline_41$$.__proto__=$JSCompiler_x$jscomp$inline_40$$;$JSCompiler_inline_result$jscomp$18$$=$JSCompiler_y$jscomp$inline_41$$.a;break a}catch($JSCompiler_e$jscomp$inline_42$$){}$JSCompiler_inline_result$jscomp$18$$=!1}$JSCompiler_temp$jscomp$17$$=$JSCompiler_inline_result$jscomp$18$$?
function($target$jscomp$83$$,$proto$jscomp$3$$){$target$jscomp$83$$.__proto__=$proto$jscomp$3$$;if($target$jscomp$83$$.__proto__!==$proto$jscomp$3$$)throw new TypeError($target$jscomp$83$$+" is not extensible");return $target$jscomp$83$$}:null}var $$jscomp$setPrototypeOf$$=$JSCompiler_temp$jscomp$17$$;function $Deferred$$module$src$utils$promise$$(){var $resolve$$,$reject$$;this.promise=new Promise(function($res$$,$rej$$){$resolve$$=$res$$;$reject$$=$rej$$});this.resolve=$resolve$$;this.reject=$reject$$};function $tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($component$jscomp$4$$,$fallback$$){$fallback$$=void 0===$fallback$$?"":$fallback$$;try{return decodeURIComponent($component$jscomp$4$$)}catch($e$jscomp$8$$){return $fallback$$}};var $regex$$module$src$url_parse_query_string$$=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;
function $parseQueryString_$$module$src$url_parse_query_string$$($queryString$$){var $params$jscomp$1$$=Object.create(null);if(!$queryString$$)return $params$jscomp$1$$;for(var $match$$;$match$$=$regex$$module$src$url_parse_query_string$$.exec($queryString$$);){var $name$jscomp$70$$=$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($match$$[1],$match$$[1]),$value$jscomp$87$$=$match$$[2]?$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($match$$[2],$match$$[2]):"";
$params$jscomp$1$$[$name$jscomp$70$$]=$value$jscomp$87$$}return $params$jscomp$1$$};var $rtvVersion$$module$src$mode$$="";function $toArray$$module$src$types$$($arrayLike$jscomp$1$$){return $arrayLike$jscomp$1$$?Array.prototype.slice.call($arrayLike$jscomp$1$$):[]}function $isFiniteNumber$$module$src$types$$($value$jscomp$91$$){return"number"===typeof $value$jscomp$91$$&&isFinite($value$jscomp$91$$)};self.log=self.log||{user:null,dev:null,userForEmbed:null};var $logs$$module$src$log$$=self.log;function $dev$$module$src$log$$(){if($logs$$module$src$log$$.dev)return $logs$$module$src$log$$.dev;throw Error("failed to call initLogConstructor");};function $getService$$module$src$service$$($win$jscomp$8$$,$id$jscomp$11$$){$win$jscomp$8$$=$win$jscomp$8$$.__AMP_TOP||$win$jscomp$8$$;return $getServiceInternal$$module$src$service$$($win$jscomp$8$$,$id$jscomp$11$$)}
function $getServiceForDoc$$module$src$service$$($elementOrAmpDoc$$,$id$jscomp$15$$){var $ampdoc$jscomp$2_holder$jscomp$2$$=$getAmpdoc$$module$src$service$$($elementOrAmpDoc$$);$ampdoc$jscomp$2_holder$jscomp$2$$=$getAmpdocServiceHolder$$module$src$service$$($ampdoc$jscomp$2_holder$jscomp$2$$);return $getServiceInternal$$module$src$service$$($ampdoc$jscomp$2_holder$jscomp$2$$,$id$jscomp$15$$)}
function $getAmpdoc$$module$src$service$$($nodeOrDoc$jscomp$2$$){return $nodeOrDoc$jscomp$2$$.nodeType?$getService$$module$src$service$$(($nodeOrDoc$jscomp$2$$.ownerDocument||$nodeOrDoc$jscomp$2$$).defaultView,"ampdoc").getAmpDoc($nodeOrDoc$jscomp$2$$):$nodeOrDoc$jscomp$2$$}
function $getAmpdocServiceHolder$$module$src$service$$($ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$){$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$=$getAmpdoc$$module$src$service$$($ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$);return $ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$.isSingleDoc()?$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$.win:$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$}
function $getServiceInternal$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$,$id$jscomp$19$$){$isServiceRegistered$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$,$id$jscomp$19$$);var $services$$=$getServices$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$);$holder$jscomp$4_s$jscomp$8$$=$services$$[$id$jscomp$19$$];$holder$jscomp$4_s$jscomp$8$$.obj||($holder$jscomp$4_s$jscomp$8$$.obj=new $holder$jscomp$4_s$jscomp$8$$.ctor($holder$jscomp$4_s$jscomp$8$$.context),$holder$jscomp$4_s$jscomp$8$$.ctor=
null,$holder$jscomp$4_s$jscomp$8$$.context=null,$holder$jscomp$4_s$jscomp$8$$.resolve&&$holder$jscomp$4_s$jscomp$8$$.resolve($holder$jscomp$4_s$jscomp$8$$.obj));return $holder$jscomp$4_s$jscomp$8$$.obj}
function $getServicePromiseOrNullInternal$$module$src$service$$($holder$jscomp$8$$){var $s$jscomp$11$$=$getServices$$module$src$service$$($holder$jscomp$8$$)["amp-analytics-instrumentation"];if($s$jscomp$11$$){if($s$jscomp$11$$.promise)return $s$jscomp$11$$.promise;$getServiceInternal$$module$src$service$$($holder$jscomp$8$$,"amp-analytics-instrumentation");return $s$jscomp$11$$.promise=Promise.resolve($s$jscomp$11$$.obj)}return null}
function $getServices$$module$src$service$$($holder$jscomp$9$$){var $services$jscomp$5$$=$holder$jscomp$9$$.services;$services$jscomp$5$$||($services$jscomp$5$$=$holder$jscomp$9$$.services={});return $services$jscomp$5$$}
function $isServiceRegistered$$module$src$service$$($holder$jscomp$12_service$jscomp$4$$,$id$jscomp$27$$){$holder$jscomp$12_service$jscomp$4$$=$holder$jscomp$12_service$jscomp$4$$.services&&$holder$jscomp$12_service$jscomp$4$$.services[$id$jscomp$27$$];return!(!$holder$jscomp$12_service$jscomp$4$$||!$holder$jscomp$12_service$jscomp$4$$.ctor&&!$holder$jscomp$12_service$jscomp$4$$.obj)}
function $emptyServiceHolderWithPromise$$module$src$service$$(){var $deferred$$=new $Deferred$$module$src$utils$promise$$,$$jscomp$destructuring$var2_reject$jscomp$3$$=$deferred$$,$promise$jscomp$1$$=$$jscomp$destructuring$var2_reject$jscomp$3$$.promise,$resolve$jscomp$4$$=$$jscomp$destructuring$var2_reject$jscomp$3$$.resolve;$$jscomp$destructuring$var2_reject$jscomp$3$$=$$jscomp$destructuring$var2_reject$jscomp$3$$.reject;$promise$jscomp$1$$.catch(function(){});return{obj:null,promise:$promise$jscomp$1$$,
resolve:$resolve$jscomp$4$$,reject:$$jscomp$destructuring$var2_reject$jscomp$3$$,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function $dict$$module$src$utils$object$$($opt_initial$jscomp$1$$){return $opt_initial$jscomp$1$$||{}};function $removeElement$$module$src$dom$$($element$jscomp$13$$){$element$jscomp$13$$.parentElement&&$element$jscomp$13$$.parentElement.removeChild($element$jscomp$13$$)}
function $createElementWithAttributes$$module$src$dom$$($doc$jscomp$12_element$jscomp$16$$,$tagName$jscomp$5$$,$attributes$jscomp$2$$){$doc$jscomp$12_element$jscomp$16$$=$doc$jscomp$12_element$jscomp$16$$.createElement($tagName$jscomp$5$$);for(var $JSCompiler_attr$jscomp$inline_46$$ in $attributes$jscomp$2$$)$doc$jscomp$12_element$jscomp$16$$.setAttribute($JSCompiler_attr$jscomp$inline_46$$,$attributes$jscomp$2$$[$JSCompiler_attr$jscomp$inline_46$$]);return $doc$jscomp$12_element$jscomp$16$$};function $getElementServiceIfAvailableForDoc$$module$src$element_service$$($element$jscomp$33$$){var $s$jscomp$13$$=$getServicePromiseOrNullInternal$$module$src$service$$($getAmpdocServiceHolder$$module$src$service$$($element$jscomp$33$$));if($s$jscomp$13$$)return $s$jscomp$13$$;var $ampdoc$jscomp$7$$=$getAmpdoc$$module$src$service$$($element$jscomp$33$$);return $ampdoc$jscomp$7$$.whenBodyAvailable().then(function(){var $element$jscomp$33$$=$ampdoc$jscomp$7$$.win;var $s$jscomp$13$$=$ampdoc$jscomp$7$$.win.document.head;
if($s$jscomp$13$$){var $JSCompiler_inline_result$jscomp$190_JSCompiler_scripts$jscomp$inline_192$$=[];$s$jscomp$13$$=$s$jscomp$13$$.querySelectorAll("script[custom-element]");for(var $JSCompiler_i$jscomp$inline_194$$=0;$JSCompiler_i$jscomp$inline_194$$<$s$jscomp$13$$.length;$JSCompiler_i$jscomp$inline_194$$++)$JSCompiler_inline_result$jscomp$190_JSCompiler_scripts$jscomp$inline_192$$.push($s$jscomp$13$$[$JSCompiler_i$jscomp$inline_194$$].getAttribute("custom-element"))}else $JSCompiler_inline_result$jscomp$190_JSCompiler_scripts$jscomp$inline_192$$=
[];$element$jscomp$33$$=$JSCompiler_inline_result$jscomp$190_JSCompiler_scripts$jscomp$inline_192$$.includes("amp-analytics")?$getService$$module$src$service$$($element$jscomp$33$$,"extensions").waitForExtension($element$jscomp$33$$,"amp-analytics"):Promise.resolve();return $element$jscomp$33$$}).then(function(){var $s$jscomp$13$$=$ampdoc$jscomp$7$$.win;if($s$jscomp$13$$.ampExtendedElements&&$s$jscomp$13$$.ampExtendedElements["amp-analytics"]){$s$jscomp$13$$=$getAmpdocServiceHolder$$module$src$service$$($element$jscomp$33$$);
var $JSCompiler_cached$jscomp$inline_164$$=$getServicePromiseOrNullInternal$$module$src$service$$($s$jscomp$13$$);$JSCompiler_cached$jscomp$inline_164$$?$s$jscomp$13$$=$JSCompiler_cached$jscomp$inline_164$$:($s$jscomp$13$$=$getServices$$module$src$service$$($s$jscomp$13$$),$s$jscomp$13$$["amp-analytics-instrumentation"]=$emptyServiceHolderWithPromise$$module$src$service$$(),$s$jscomp$13$$=$s$jscomp$13$$["amp-analytics-instrumentation"].promise)}else $s$jscomp$13$$=null;return $s$jscomp$13$$})};function $triggerAnalyticsEvent$$module$src$analytics$$($target$jscomp$86$$,$eventType$jscomp$3$$,$opt_vars$$){$getElementServiceIfAvailableForDoc$$module$src$element_service$$($target$jscomp$86$$).then(function($analytics$$){$analytics$$&&$analytics$$.triggerEventForTarget($target$jscomp$86$$,$eventType$jscomp$3$$,$opt_vars$$)})};function $insertAnalyticsElement$$module$src$extension_analytics$$($parentElement$$,$config$jscomp$2_extensions$jscomp$1$$){var $ampdoc$jscomp$10_loadAnalytics$jscomp$1$$=!0;$ampdoc$jscomp$10_loadAnalytics$jscomp$1$$=void 0===$ampdoc$jscomp$10_loadAnalytics$jscomp$1$$?!1:$ampdoc$jscomp$10_loadAnalytics$jscomp$1$$;var $disableImmediate$$=void 0===$disableImmediate$$?!1:$disableImmediate$$;var $doc$jscomp$14$$=$parentElement$$.ownerDocument,$analyticsElem$$=$createElementWithAttributes$$module$src$dom$$($doc$jscomp$14$$,
"amp-analytics",$dict$$module$src$utils$object$$({sandbox:"true",trigger:$disableImmediate$$?"":"immediate"})),$scriptElem$$=$createElementWithAttributes$$module$src$dom$$($doc$jscomp$14$$,"script",$dict$$module$src$utils$object$$({type:"application/json"}));$scriptElem$$.textContent=JSON.stringify($config$jscomp$2_extensions$jscomp$1$$);$analyticsElem$$.appendChild($scriptElem$$);$analyticsElem$$.CONFIG=$config$jscomp$2_extensions$jscomp$1$$;$ampdoc$jscomp$10_loadAnalytics$jscomp$1$$?($config$jscomp$2_extensions$jscomp$1$$=
$getService$$module$src$service$$($parentElement$$.ownerDocument.defaultView,"extensions"),$ampdoc$jscomp$10_loadAnalytics$jscomp$1$$=$getAmpdoc$$module$src$service$$($parentElement$$),$config$jscomp$2_extensions$jscomp$1$$.installExtensionForDoc($ampdoc$jscomp$10_loadAnalytics$jscomp$1$$,"amp-analytics")):$getElementServiceIfAvailableForDoc$$module$src$element_service$$($parentElement$$).then(function(){});$parentElement$$.appendChild($analyticsElem$$)}
function $CustomEventReporter$$module$src$extension_analytics$$($parent$jscomp$14$$,$config$jscomp$3$$){var $$jscomp$this$jscomp$1$$=this;this.$id_$=$parent$jscomp$14$$.getResourceId();this.$parent_$=$parent$jscomp$14$$;this.$config_$=$config$jscomp$3$$;for(var $event$jscomp$5$$ in $config$jscomp$3$$.triggers){var $newEventType$$="sandbox-"+this.$id_$+"-"+$config$jscomp$3$$.triggers[$event$jscomp$5$$].on;$config$jscomp$3$$.triggers[$event$jscomp$5$$].on=$newEventType$$}this.$parent_$.signals().whenSignal("load-start").then(function(){$insertAnalyticsElement$$module$src$extension_analytics$$($$jscomp$this$jscomp$1$$.$parent_$,
$config$jscomp$3$$)})}$CustomEventReporter$$module$src$extension_analytics$$.prototype.trigger=function($eventType$jscomp$5$$,$opt_vars$jscomp$1$$){$triggerAnalyticsEvent$$module$src$analytics$$(this.$parent_$,"sandbox-"+this.$id_$+"-"+$eventType$jscomp$5$$,$opt_vars$jscomp$1$$)};function $CustomEventReporterBuilder$$module$src$extension_analytics$$($parent$jscomp$15$$){this.$parent_$=$parent$jscomp$15$$;this.$config_$={requests:{},triggers:{}}}
$CustomEventReporterBuilder$$module$src$extension_analytics$$.prototype.setTransportConfig=function($transportConfig$$){this.$config_$.transport=$transportConfig$$};$CustomEventReporterBuilder$$module$src$extension_analytics$$.prototype.setExtraUrlParams=function($extraUrlParamsConfig$$){this.$config_$.extraUrlParams=$extraUrlParamsConfig$$};
$CustomEventReporterBuilder$$module$src$extension_analytics$$.prototype.track=function($eventType$jscomp$7$$,$request$jscomp$5$$){$request$jscomp$5$$=Array.isArray($request$jscomp$5$$)?$request$jscomp$5$$:[$request$jscomp$5$$];for(var $requestList$$=[],$i$jscomp$11$$=0;$i$jscomp$11$$<$request$jscomp$5$$.length;$i$jscomp$11$$++){var $requestName$$=$eventType$jscomp$7$$+"-request-"+$i$jscomp$11$$;this.$config_$.requests[$requestName$$]=$request$jscomp$5$$[$i$jscomp$11$$];$requestList$$.push($requestName$$)}this.$config_$.triggers[$eventType$jscomp$7$$]=
{on:$eventType$jscomp$7$$,request:$requestList$$};return this};$CustomEventReporterBuilder$$module$src$extension_analytics$$.prototype.build=function(){var $report$$=new $CustomEventReporter$$module$src$extension_analytics$$(this.$parent_$,this.$config_$);this.$config_$=null;return $report$$};function $Pass$$module$src$pass$$($win$jscomp$42$$,$handler$jscomp$4$$){var $opt_defaultDelay$$,$$jscomp$this$jscomp$2$$=this;this.$timer_$=$getService$$module$src$service$$($win$jscomp$42$$,"timer");this.$handler_$=$handler$jscomp$4$$;this.$defaultDelay_$=$opt_defaultDelay$$||0;this.$scheduled_$=-1;this.$nextTime_$=0;this.$running_$=!1;this.$boundPass_$=function(){$$jscomp$this$jscomp$2$$.$scheduled_$=-1;$$jscomp$this$jscomp$2$$.$nextTime_$=0;$$jscomp$this$jscomp$2$$.$running_$=!0;$$jscomp$this$jscomp$2$$.$handler_$();
$$jscomp$this$jscomp$2$$.$running_$=!1}}$Pass$$module$src$pass$$.prototype.isPending=function(){return-1!=this.$scheduled_$};
$Pass$$module$src$pass$$.prototype.schedule=function($opt_delay$jscomp$2$$){var $delay$$=$opt_delay$jscomp$2$$||this.$defaultDelay_$;this.$running_$&&10>$delay$$&&($delay$$=10);var $nextTime$$=Date.now()+$delay$$;return!this.isPending()||-10>$nextTime$$-this.$nextTime_$?(this.cancel(),this.$nextTime_$=$nextTime$$,this.$scheduled_$=this.$timer_$.delay(this.$boundPass_$,$delay$$),!0):!1};
$Pass$$module$src$pass$$.prototype.cancel=function(){this.isPending()&&(this.$timer_$.cancel(this.$scheduled_$),this.$scheduled_$=-1)};var $optsSupported$$module$src$event_helper_listen$$;
function $internalListenImplementation$$module$src$event_helper_listen$$($element$jscomp$56$$,$listener$jscomp$62$$){var $opt_evtListenerOpts$$=void 0,$localElement$$=$element$jscomp$56$$,$localListener$$=$listener$jscomp$62$$;var $wrapped$$=function($element$jscomp$56$$){try{return $localListener$$($element$jscomp$56$$)}catch($e$jscomp$16$$){throw self.reportError($e$jscomp$16$$),$e$jscomp$16$$;}};var $optsSupported$$=$detectEvtListenerOptsSupport$$module$src$event_helper_listen$$(),$capture$$=!1;
$opt_evtListenerOpts$$&&($capture$$=$opt_evtListenerOpts$$.capture);$localElement$$.addEventListener("message",$wrapped$$,$optsSupported$$?$opt_evtListenerOpts$$:$capture$$);return function(){$localElement$$&&$localElement$$.removeEventListener("message",$wrapped$$,$optsSupported$$?$opt_evtListenerOpts$$:$capture$$);$wrapped$$=$localElement$$=$localListener$$=null}}
function $detectEvtListenerOptsSupport$$module$src$event_helper_listen$$(){if(void 0!==$optsSupported$$module$src$event_helper_listen$$)return $optsSupported$$module$src$event_helper_listen$$;$optsSupported$$module$src$event_helper_listen$$=!1;try{var $options$jscomp$14$$={get capture(){$optsSupported$$module$src$event_helper_listen$$=!0}};self.addEventListener("test-options",null,$options$jscomp$14$$);self.removeEventListener("test-options",null,$options$jscomp$14$$)}catch($err$jscomp$3$$){}return $optsSupported$$module$src$event_helper_listen$$}
;function $tryParseJson$$module$src$json$$($json$jscomp$1$$,$opt_onFailed$$){try{return JSON.parse($json$jscomp$1$$)}catch($e$jscomp$17$$){return $opt_onFailed$$&&$opt_onFailed$$($e$jscomp$17$$),null}};function $deserializeMessage$$module$src$3p_frame_messaging$$($message$jscomp$30$$){if(!$isAmpMessage$$module$src$3p_frame_messaging$$($message$jscomp$30$$))return null;var $startPos$$=$message$jscomp$30$$.indexOf("{");try{return JSON.parse($message$jscomp$30$$.substr($startPos$$))}catch($e$jscomp$18$$){return $dev$$module$src$log$$().error("MESSAGING","Failed to parse message: "+$message$jscomp$30$$,$e$jscomp$18$$),null}}
function $isAmpMessage$$module$src$3p_frame_messaging$$($message$jscomp$31$$){return"string"==typeof $message$jscomp$31$$&&0==$message$jscomp$31$$.indexOf("amp-")&&-1!=$message$jscomp$31$$.indexOf("{")};function $listen$$module$src$event_helper$$($element$jscomp$59$$,$listener$jscomp$64$$){return $internalListenImplementation$$module$src$event_helper_listen$$($element$jscomp$59$$,$listener$jscomp$64$$)};function $LruCache$$module$src$utils$lru_cache$$(){var $capacity$$=100;this.$capacity_$=$capacity$$;this.$access_$=this.$size_$=0;this.$cache_$=Object.create(null)}$LruCache$$module$src$utils$lru_cache$$.prototype.has=function($key$jscomp$44$$){return!!this.$cache_$[$key$jscomp$44$$]};$LruCache$$module$src$utils$lru_cache$$.prototype.get=function($key$jscomp$45$$){var $cacheable$$=this.$cache_$[$key$jscomp$45$$];if($cacheable$$)return $cacheable$$.access=++this.$access_$,$cacheable$$.payload};
$LruCache$$module$src$utils$lru_cache$$.prototype.put=function($JSCompiler_cache$jscomp$inline_62_key$jscomp$46$$,$payload$$){this.has($JSCompiler_cache$jscomp$inline_62_key$jscomp$46$$)||this.$size_$++;this.$cache_$[$JSCompiler_cache$jscomp$inline_62_key$jscomp$46$$]={payload:$payload$$,access:this.$access_$};if(!(this.$size_$<=this.$capacity_$)){$dev$$module$src$log$$().warn("lru-cache","Trimming LRU cache");$JSCompiler_cache$jscomp$inline_62_key$jscomp$46$$=this.$cache_$;var $JSCompiler_oldest$jscomp$inline_63$$=
this.$access_$+1,$JSCompiler_key$jscomp$inline_65$$;for($JSCompiler_key$jscomp$inline_65$$ in $JSCompiler_cache$jscomp$inline_62_key$jscomp$46$$){var $JSCompiler_access$jscomp$inline_66$$=$JSCompiler_cache$jscomp$inline_62_key$jscomp$46$$[$JSCompiler_key$jscomp$inline_65$$].access;if($JSCompiler_access$jscomp$inline_66$$<$JSCompiler_oldest$jscomp$inline_63$$){$JSCompiler_oldest$jscomp$inline_63$$=$JSCompiler_access$jscomp$inline_66$$;var $JSCompiler_oldestKey$jscomp$inline_64$$=$JSCompiler_key$jscomp$inline_65$$}}void 0!==
$JSCompiler_oldestKey$jscomp$inline_64$$&&(delete $JSCompiler_cache$jscomp$inline_62_key$jscomp$46$$[$JSCompiler_oldestKey$jscomp$inline_64$$],this.$size_$--)}};$dict$$module$src$utils$object$$({c:!0,v:!0,a:!0,ad:!0,action:!0});var $a$$module$src$url$$,$cache$$module$src$url$$;
function $parseUrlDeprecated$$module$src$url$$($JSCompiler_inline_result$jscomp$27_url$jscomp$22$$){var $opt_nocache$$;$a$$module$src$url$$||($a$$module$src$url$$=self.document.createElement("a"),$cache$$module$src$url$$=self.UrlCache||(self.UrlCache=new $LruCache$$module$src$utils$lru_cache$$));var $JSCompiler_opt_cache$jscomp$inline_69$$=$opt_nocache$$?null:$cache$$module$src$url$$,$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$=$a$$module$src$url$$;
if($JSCompiler_opt_cache$jscomp$inline_69$$&&$JSCompiler_opt_cache$jscomp$inline_69$$.has($JSCompiler_inline_result$jscomp$27_url$jscomp$22$$))$JSCompiler_inline_result$jscomp$27_url$jscomp$22$$=$JSCompiler_opt_cache$jscomp$inline_69$$.get($JSCompiler_inline_result$jscomp$27_url$jscomp$22$$);else{$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.href=$JSCompiler_inline_result$jscomp$27_url$jscomp$22$$;$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.protocol||
($JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.href=$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.href);var $JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$={href:$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.href,protocol:$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.protocol,host:$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.host,
hostname:$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.hostname,port:"0"==$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.port?"":$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.port,pathname:$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.pathname,search:$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.search,
hash:$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.hash,origin:null};"/"!==$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$.pathname[0]&&($JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$.pathname="/"+$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$.pathname);if("http:"==$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$.protocol&&80==$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$.port||
"https:"==$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$.protocol&&443==$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$.port)$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$.port="",$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$.host=$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$.hostname;$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$.origin=$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.origin&&
"null"!=$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.origin?$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.origin:"data:"!=$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$.protocol&&$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$.host?$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$.protocol+"//"+$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$.host:
$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$.href;$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$=self;if($JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.AMP_MODE)$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$=$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.AMP_MODE;else{var $JSCompiler_AMP_CONFIG$jscomp$inline_197_JSCompiler_singlePassType$jscomp$inline_204$$=
self.AMP_CONFIG||{},$JSCompiler_runningTests$jscomp$inline_201$$=!!$JSCompiler_AMP_CONFIG$jscomp$inline_197_JSCompiler_singlePassType$jscomp$inline_204$$.test||!(!$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.AMP_TEST&&!$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.__karma__),$JSCompiler_isLocalDev$jscomp$inline_202$$=!!$JSCompiler_AMP_CONFIG$jscomp$inline_197_JSCompiler_singlePassType$jscomp$inline_204$$.localDev||
$JSCompiler_runningTests$jscomp$inline_201$$,$JSCompiler_hashQuery$jscomp$inline_203$$=$parseQueryString_$$module$src$url_parse_query_string$$($JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.location.originalHash||$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.location.hash);$JSCompiler_AMP_CONFIG$jscomp$inline_197_JSCompiler_singlePassType$jscomp$inline_204$$=$JSCompiler_AMP_CONFIG$jscomp$inline_197_JSCompiler_singlePassType$jscomp$inline_204$$.spt;
var $JSCompiler_searchQuery$jscomp$inline_205$$=$parseQueryString_$$module$src$url_parse_query_string$$($JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.location.search);$rtvVersion$$module$src$mode$$||($rtvVersion$$module$src$mode$$=$JSCompiler_isLocalDev$jscomp$inline_202$$?"1904281823091":$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.AMP_CONFIG&&$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.AMP_CONFIG.v?
$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.AMP_CONFIG.v:"011904281823091");$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$=$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.AMP_MODE={localDev:$JSCompiler_isLocalDev$jscomp$inline_202$$,development:!("1"!=$JSCompiler_hashQuery$jscomp$inline_203$$.development&&!$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.AMP_DEV_MODE),
examiner:"2"==$JSCompiler_hashQuery$jscomp$inline_203$$.development,filter:$JSCompiler_hashQuery$jscomp$inline_203$$.filter,geoOverride:$JSCompiler_hashQuery$jscomp$inline_203$$["amp-geo"],minified:!0,lite:void 0!=$JSCompiler_searchQuery$jscomp$inline_205$$.amp_lite,test:$JSCompiler_runningTests$jscomp$inline_201$$,log:$JSCompiler_hashQuery$jscomp$inline_203$$.log,version:"1904281823091",rtvVersion:$rtvVersion$$module$src$mode$$,singlePassType:$JSCompiler_AMP_CONFIG$jscomp$inline_197_JSCompiler_singlePassType$jscomp$inline_204$$}}$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$=
$JSCompiler_a$jscomp$inline_70_JSCompiler_temp$jscomp$187_JSCompiler_win$jscomp$inline_168$$.test&&Object.freeze?Object.freeze($JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$):$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$;$JSCompiler_opt_cache$jscomp$inline_69$$&&$JSCompiler_opt_cache$jscomp$inline_69$$.put($JSCompiler_inline_result$jscomp$27_url$jscomp$22$$,$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$);$JSCompiler_inline_result$jscomp$27_url$jscomp$22$$=
$JSCompiler_frozen$jscomp$inline_72_JSCompiler_info$jscomp$inline_71$$}return $JSCompiler_inline_result$jscomp$27_url$jscomp$22$$}
function $appendEncodedParamStringToUrl$$module$src$url$$($url$jscomp$24$$,$paramString$$){var $opt_addToFront$$;if(!$paramString$$)return $url$jscomp$24$$;var $mainAndFragment$$=$url$jscomp$24$$.split("#",2),$mainAndQuery$$=$mainAndFragment$$[0].split("?",2),$newUrl$$=$mainAndQuery$$[0]+($mainAndQuery$$[1]?$opt_addToFront$$?"?"+$paramString$$+"&"+$mainAndQuery$$[1]:"?"+$mainAndQuery$$[1]+"&"+$paramString$$:"?"+$paramString$$);return $newUrl$$+=$mainAndFragment$$[1]?"#"+$mainAndFragment$$[1]:""}
function $serializeQueryString$$module$src$url$$($params$jscomp$5$$){var $s$jscomp$15$$=[],$k$jscomp$3$$;for($k$jscomp$3$$ in $params$jscomp$5$$){var $sv$5_v$jscomp$1$$=$params$jscomp$5$$[$k$jscomp$3$$];if(null!=$sv$5_v$jscomp$1$$)if(Array.isArray($sv$5_v$jscomp$1$$))for(var $i$jscomp$15$$=0;$i$jscomp$15$$<$sv$5_v$jscomp$1$$.length;$i$jscomp$15$$++){var $sv$$=$sv$5_v$jscomp$1$$[$i$jscomp$15$$];$s$jscomp$15$$.push(encodeURIComponent($k$jscomp$3$$)+"="+encodeURIComponent($sv$$))}else $s$jscomp$15$$.push(encodeURIComponent($k$jscomp$3$$)+
"="+encodeURIComponent($sv$5_v$jscomp$1$$))}return $s$jscomp$15$$.join("&")};function $remove$$module$src$utils$array$$($array$jscomp$7$$,$shouldRemove$$){for(var $removed$$=[],$index$jscomp$72$$=0,$i$jscomp$17$$=0;$i$jscomp$17$$<$array$jscomp$7$$.length;$i$jscomp$17$$++){var $item$$=$array$jscomp$7$$[$i$jscomp$17$$];$shouldRemove$$($item$$,$i$jscomp$17$$,$array$jscomp$7$$)?$removed$$.push($item$$):($index$jscomp$72$$<$i$jscomp$17$$&&($array$jscomp$7$$[$index$jscomp$72$$]=$item$$),$index$jscomp$72$$++)}$index$jscomp$72$$<$array$jscomp$7$$.length&&($array$jscomp$7$$.length=
$index$jscomp$72$$)};var $propertyNameCache$$module$src$style$$,$vendorPrefixes$$module$src$style$$="Webkit webkit Moz moz ms O o".split(" ");function $getListenForSentinel$$module$src$iframe_helper$$($JSCompiler_inline_result$jscomp$29_parentWin$jscomp$2$$,$sentinel$jscomp$1$$,$opt_create$jscomp$1$$){var $JSCompiler_listeningFors$jscomp$inline_76$$=$JSCompiler_inline_result$jscomp$29_parentWin$jscomp$2$$.listeningFors;!$JSCompiler_listeningFors$jscomp$inline_76$$&&$opt_create$jscomp$1$$&&($JSCompiler_listeningFors$jscomp$inline_76$$=$JSCompiler_inline_result$jscomp$29_parentWin$jscomp$2$$.listeningFors=Object.create(null));$JSCompiler_inline_result$jscomp$29_parentWin$jscomp$2$$=
$JSCompiler_listeningFors$jscomp$inline_76$$||null;if(!$JSCompiler_inline_result$jscomp$29_parentWin$jscomp$2$$)return $JSCompiler_inline_result$jscomp$29_parentWin$jscomp$2$$;var $listenSentinel$$=$JSCompiler_inline_result$jscomp$29_parentWin$jscomp$2$$[$sentinel$jscomp$1$$];!$listenSentinel$$&&$opt_create$jscomp$1$$&&($listenSentinel$$=$JSCompiler_inline_result$jscomp$29_parentWin$jscomp$2$$[$sentinel$jscomp$1$$]=[]);return $listenSentinel$$||null}
function $getOrCreateListenForEvents$$module$src$iframe_helper$$($listenSentinel$jscomp$1_parentWin$jscomp$3$$,$iframe$$,$opt_is3P$$){var $i$jscomp$21_sentinel$jscomp$2$$=$opt_is3P$$?$iframe$$.getAttribute("data-amp-3p-sentinel"):"amp";$listenSentinel$jscomp$1_parentWin$jscomp$3$$=$getListenForSentinel$$module$src$iframe_helper$$($listenSentinel$jscomp$1_parentWin$jscomp$3$$,$i$jscomp$21_sentinel$jscomp$2$$,!0);for($i$jscomp$21_sentinel$jscomp$2$$=0;$i$jscomp$21_sentinel$jscomp$2$$<$listenSentinel$jscomp$1_parentWin$jscomp$3$$.length;$i$jscomp$21_sentinel$jscomp$2$$++){var $we$$=
$listenSentinel$jscomp$1_parentWin$jscomp$3$$[$i$jscomp$21_sentinel$jscomp$2$$];if($we$$.frame===$iframe$$){var $windowEvents$$=$we$$;break}}$windowEvents$$||($windowEvents$$={frame:$iframe$$,events:Object.create(null)},$listenSentinel$jscomp$1_parentWin$jscomp$3$$.push($windowEvents$$));return $windowEvents$$.events}
function $dropListenSentinel$$module$src$iframe_helper$$($listenSentinel$jscomp$3$$){for(var $noopData$$=$dict$$module$src$utils$object$$({sentinel:"unlisten"}),$i$jscomp$23$$=$listenSentinel$jscomp$3$$.length-1;0<=$i$jscomp$23$$;$i$jscomp$23$$--){var $windowEvents$jscomp$2$$=$listenSentinel$jscomp$3$$[$i$jscomp$23$$];if(!$windowEvents$jscomp$2$$.frame.contentWindow){$listenSentinel$jscomp$3$$.splice($i$jscomp$23$$,1);var $events$$=$windowEvents$jscomp$2$$.events,$name$jscomp$75$$;for($name$jscomp$75$$ in $events$$)$events$$[$name$jscomp$75$$].splice(0,
Infinity).forEach(function($listenSentinel$jscomp$3$$){$listenSentinel$jscomp$3$$($noopData$$)})}}}
function $registerGlobalListenerIfNeeded$$module$src$iframe_helper$$($parentWin$jscomp$5$$){if(!$parentWin$jscomp$5$$.listeningFors){var $listenForListener$$=function($listenForListener$$){if($listenForListener$$.data){var $event$jscomp$11$$=$parseIfNeeded$$module$src$iframe_helper$$($listenForListener$$.data);if($event$jscomp$11$$&&$event$jscomp$11$$.sentinel){var $JSCompiler_inline_result$jscomp$30_JSCompiler_triggerWin$jscomp$inline_80_i$jscomp$24$$=$listenForListener$$.source;var $JSCompiler_listenSentinel$jscomp$inline_81$$=
$getListenForSentinel$$module$src$iframe_helper$$($parentWin$jscomp$5$$,$event$jscomp$11$$.sentinel);if($JSCompiler_listenSentinel$jscomp$inline_81$$){for(var $JSCompiler_windowEvents$jscomp$inline_82$$,$JSCompiler_i$jscomp$inline_83$$=0;$JSCompiler_i$jscomp$inline_83$$<$JSCompiler_listenSentinel$jscomp$inline_81$$.length;$JSCompiler_i$jscomp$inline_83$$++){var $JSCompiler_we$jscomp$inline_84$$=$JSCompiler_listenSentinel$jscomp$inline_81$$[$JSCompiler_i$jscomp$inline_83$$],$JSCompiler_contentWindow$jscomp$inline_85$$=
$JSCompiler_we$jscomp$inline_84$$.frame.contentWindow;if($JSCompiler_contentWindow$jscomp$inline_85$$){var $JSCompiler_temp$jscomp$158_JSCompiler_win$jscomp$inline_172$$;if(!($JSCompiler_temp$jscomp$158_JSCompiler_win$jscomp$inline_172$$=$JSCompiler_inline_result$jscomp$30_JSCompiler_triggerWin$jscomp$inline_80_i$jscomp$24$$==$JSCompiler_contentWindow$jscomp$inline_85$$))b:{for($JSCompiler_temp$jscomp$158_JSCompiler_win$jscomp$inline_172$$=$JSCompiler_inline_result$jscomp$30_JSCompiler_triggerWin$jscomp$inline_80_i$jscomp$24$$;$JSCompiler_temp$jscomp$158_JSCompiler_win$jscomp$inline_172$$&&
$JSCompiler_temp$jscomp$158_JSCompiler_win$jscomp$inline_172$$!=$JSCompiler_temp$jscomp$158_JSCompiler_win$jscomp$inline_172$$.parent;$JSCompiler_temp$jscomp$158_JSCompiler_win$jscomp$inline_172$$=$JSCompiler_temp$jscomp$158_JSCompiler_win$jscomp$inline_172$$.parent)if($JSCompiler_temp$jscomp$158_JSCompiler_win$jscomp$inline_172$$==$JSCompiler_contentWindow$jscomp$inline_85$$){$JSCompiler_temp$jscomp$158_JSCompiler_win$jscomp$inline_172$$=!0;break b}$JSCompiler_temp$jscomp$158_JSCompiler_win$jscomp$inline_172$$=
!1}if($JSCompiler_temp$jscomp$158_JSCompiler_win$jscomp$inline_172$$){$JSCompiler_windowEvents$jscomp$inline_82$$=$JSCompiler_we$jscomp$inline_84$$;break}}else setTimeout($dropListenSentinel$$module$src$iframe_helper$$,0,$JSCompiler_listenSentinel$jscomp$inline_81$$)}$JSCompiler_inline_result$jscomp$30_JSCompiler_triggerWin$jscomp$inline_80_i$jscomp$24$$=$JSCompiler_windowEvents$jscomp$inline_82$$?$JSCompiler_windowEvents$jscomp$inline_82$$.events:null}else $JSCompiler_inline_result$jscomp$30_JSCompiler_triggerWin$jscomp$inline_80_i$jscomp$24$$=
$JSCompiler_listenSentinel$jscomp$inline_81$$;var $listenForEvents$$=$JSCompiler_inline_result$jscomp$30_JSCompiler_triggerWin$jscomp$inline_80_i$jscomp$24$$;if($listenForEvents$$){var $listeners$$=$listenForEvents$$[$event$jscomp$11$$.type];if($listeners$$)for($listeners$$=$listeners$$.slice(),$JSCompiler_inline_result$jscomp$30_JSCompiler_triggerWin$jscomp$inline_80_i$jscomp$24$$=0;$JSCompiler_inline_result$jscomp$30_JSCompiler_triggerWin$jscomp$inline_80_i$jscomp$24$$<$listeners$$.length;$JSCompiler_inline_result$jscomp$30_JSCompiler_triggerWin$jscomp$inline_80_i$jscomp$24$$++)(0,$listeners$$[$JSCompiler_inline_result$jscomp$30_JSCompiler_triggerWin$jscomp$inline_80_i$jscomp$24$$])($event$jscomp$11$$,
$listenForListener$$.source,$listenForListener$$.origin)}}}};$parentWin$jscomp$5$$.addEventListener("message",$listenForListener$$)}}
function $listenFor$$module$src$iframe_helper$$($iframe$jscomp$1$$,$callback$jscomp$66$$,$listenForEvents$jscomp$1_opt_is3P$jscomp$1$$,$opt_includingNestedWindows$$){function $listener$jscomp$67$$($listenForEvents$jscomp$1_opt_is3P$jscomp$1$$,$listener$jscomp$67$$,$typeOfMessage$$){if("amp"==$listenForEvents$jscomp$1_opt_is3P$jscomp$1$$.sentinel){if($listener$jscomp$67$$!=$iframe$jscomp$1$$.contentWindow)return;var $parentWin$jscomp$6$$="null"==$typeOfMessage$$&&$opt_allowOpaqueOrigin$$;if($iframeOrigin$$!=
$typeOfMessage$$&&!$parentWin$jscomp$6$$)return}if($opt_includingNestedWindows$$||$listener$jscomp$67$$==$iframe$jscomp$1$$.contentWindow)"unlisten"==$listenForEvents$jscomp$1_opt_is3P$jscomp$1$$.sentinel?$unlisten$jscomp$2$$():$callback$jscomp$66$$($listenForEvents$jscomp$1_opt_is3P$jscomp$1$$,$listener$jscomp$67$$,$typeOfMessage$$)}var $typeOfMessage$$="send-intersections",$opt_allowOpaqueOrigin$$,$parentWin$jscomp$6$$=$iframe$jscomp$1$$.ownerDocument.defaultView;$registerGlobalListenerIfNeeded$$module$src$iframe_helper$$($parentWin$jscomp$6$$);
$listenForEvents$jscomp$1_opt_is3P$jscomp$1$$=$getOrCreateListenForEvents$$module$src$iframe_helper$$($parentWin$jscomp$6$$,$iframe$jscomp$1$$,$listenForEvents$jscomp$1_opt_is3P$jscomp$1$$);var $iframeOrigin$$=$parseUrlDeprecated$$module$src$url$$($iframe$jscomp$1$$.src).origin,$events$jscomp$1$$=$listenForEvents$jscomp$1_opt_is3P$jscomp$1$$[$typeOfMessage$$]||($listenForEvents$jscomp$1_opt_is3P$jscomp$1$$[$typeOfMessage$$]=[]),$unlisten$jscomp$2$$;$events$jscomp$1$$.push($listener$jscomp$67$$);return $unlisten$jscomp$2$$=
function(){if($listener$jscomp$67$$){var $iframe$jscomp$1$$=$events$jscomp$1$$.indexOf($listener$jscomp$67$$);-1<$iframe$jscomp$1$$&&$events$jscomp$1$$.splice($iframe$jscomp$1$$,1);$callback$jscomp$66$$=$events$jscomp$1$$=$listener$jscomp$67$$=null}}}
function $postMessageToWindows$$module$src$iframe_helper$$($iframe$jscomp$4_payload$jscomp$1$$,$targets$$,$type$jscomp$137$$,$i$jscomp$26_object$jscomp$2$$,$opt_is3P$jscomp$4_target$jscomp$88$$){if($iframe$jscomp$4_payload$jscomp$1$$.contentWindow)for($i$jscomp$26_object$jscomp$2$$.type=$type$jscomp$137$$,$i$jscomp$26_object$jscomp$2$$.sentinel=$opt_is3P$jscomp$4_target$jscomp$88$$?$iframe$jscomp$4_payload$jscomp$1$$.getAttribute("data-amp-3p-sentinel"):"amp",$iframe$jscomp$4_payload$jscomp$1$$=$i$jscomp$26_object$jscomp$2$$,
$opt_is3P$jscomp$4_target$jscomp$88$$&&($iframe$jscomp$4_payload$jscomp$1$$="amp-"+JSON.stringify($i$jscomp$26_object$jscomp$2$$)),$i$jscomp$26_object$jscomp$2$$=0;$i$jscomp$26_object$jscomp$2$$<$targets$$.length;$i$jscomp$26_object$jscomp$2$$++)$opt_is3P$jscomp$4_target$jscomp$88$$=$targets$$[$i$jscomp$26_object$jscomp$2$$],$opt_is3P$jscomp$4_target$jscomp$88$$.win.postMessage($iframe$jscomp$4_payload$jscomp$1$$,$opt_is3P$jscomp$4_target$jscomp$88$$.origin)}
function $parseIfNeeded$$module$src$iframe_helper$$($data$jscomp$61$$){"string"==typeof $data$jscomp$61$$&&($data$jscomp$61$$="{"==$data$jscomp$61$$.charAt(0)?$tryParseJson$$module$src$json$$($data$jscomp$61$$,function($data$jscomp$61$$){$dev$$module$src$log$$().warn("IFRAME-HELPER","Postmessage could not be parsed. Is it in a valid JSON format?",$data$jscomp$61$$)})||null:$isAmpMessage$$module$src$3p_frame_messaging$$($data$jscomp$61$$)?$deserializeMessage$$module$src$3p_frame_messaging$$($data$jscomp$61$$):
null);return $data$jscomp$61$$}
function $SubscriptionApi$$module$src$iframe_helper$$($iframe$jscomp$6$$,$is3p$$,$requestCallback$$){var $$jscomp$this$jscomp$3$$=this;this.$iframe_$=$iframe$jscomp$6$$;this.$is3p_$=$is3p$$;this.$clientWindows_$=[];this.$unlisten_$=$listenFor$$module$src$iframe_helper$$(this.$iframe_$,function($iframe$jscomp$6$$,$is3p$$,$origin$jscomp$4$$){$$jscomp$this$jscomp$3$$.$clientWindows_$.some(function($iframe$jscomp$6$$){return $iframe$jscomp$6$$.win==$is3p$$})||$$jscomp$this$jscomp$3$$.$clientWindows_$.push({win:$is3p$$,origin:$origin$jscomp$4$$});
$requestCallback$$($iframe$jscomp$6$$,$is3p$$,$origin$jscomp$4$$)},this.$is3p_$,this.$is3p_$)}$SubscriptionApi$$module$src$iframe_helper$$.prototype.send=function($type$jscomp$139$$,$data$jscomp$63$$){$remove$$module$src$utils$array$$(this.$clientWindows_$,function($type$jscomp$139$$){return!$type$jscomp$139$$.win.parent});$postMessageToWindows$$module$src$iframe_helper$$(this.$iframe_$,this.$clientWindows_$,$type$jscomp$139$$,$data$jscomp$63$$,this.$is3p_$)};
$SubscriptionApi$$module$src$iframe_helper$$.prototype.destroy=function(){this.$unlisten_$();this.$clientWindows_$.length=0};function $layoutRectLtwh$$module$src$layout_rect$$($left$jscomp$2$$,$top$jscomp$2$$,$width$jscomp$28$$,$height$jscomp$27$$){return{left:$left$jscomp$2$$,top:$top$jscomp$2$$,width:$width$jscomp$28$$,height:$height$jscomp$27$$,bottom:$top$jscomp$2$$+$height$jscomp$27$$,right:$left$jscomp$2$$+$width$jscomp$28$$,x:$left$jscomp$2$$,y:$top$jscomp$2$$}}
function $rectIntersection$$module$src$layout_rect$$($var_args$jscomp$55$$){for(var $x0$jscomp$2$$=-Infinity,$x1$jscomp$5$$=Infinity,$y0$jscomp$2$$=-Infinity,$y1$jscomp$5$$=Infinity,$i$jscomp$28$$=0;$i$jscomp$28$$<arguments.length;$i$jscomp$28$$++){var $current$$=arguments[$i$jscomp$28$$];if($current$$&&($x0$jscomp$2$$=Math.max($x0$jscomp$2$$,$current$$.left),$x1$jscomp$5$$=Math.min($x1$jscomp$5$$,$current$$.left+$current$$.width),$y0$jscomp$2$$=Math.max($y0$jscomp$2$$,$current$$.top),$y1$jscomp$5$$=
Math.min($y1$jscomp$5$$,$current$$.top+$current$$.height),$x1$jscomp$5$$<$x0$jscomp$2$$||$y1$jscomp$5$$<$y0$jscomp$2$$))return null}return Infinity==$x1$jscomp$5$$?null:$layoutRectLtwh$$module$src$layout_rect$$($x0$jscomp$2$$,$y0$jscomp$2$$,$x1$jscomp$5$$-$x0$jscomp$2$$,$y1$jscomp$5$$-$y0$jscomp$2$$)}
function $moveLayoutRect$$module$src$layout_rect$$($rect$jscomp$2$$,$dx$jscomp$4$$,$dy$jscomp$4$$){return 0==$dx$jscomp$4$$&&0==$dy$jscomp$4$$||0==$rect$jscomp$2$$.width&&0==$rect$jscomp$2$$.height?$rect$jscomp$2$$:$layoutRectLtwh$$module$src$layout_rect$$($rect$jscomp$2$$.left+$dx$jscomp$4$$,$rect$jscomp$2$$.top+$dy$jscomp$4$$,$rect$jscomp$2$$.width,$rect$jscomp$2$$.height)};var $DEFAULT_THRESHOLD$$module$src$intersection_observer_polyfill$$=[0,.05,.1,.15,.2,.25,.3,.35,.4,.45,.5,.55,.6,.65,.7,.75,.8,.85,.9,.95,1],$INIT_TIME$$module$src$intersection_observer_polyfill$$=Date.now();
function $IntersectionObserverApi$$module$src$intersection_observer_polyfill$$($baseElement$$,$iframe$jscomp$8$$){var $opt_is3p$$,$$jscomp$this$jscomp$4$$=this;this.$baseElement_$=$baseElement$$;this.$intersectionObserver_$=null;this.$isInViewport_$=this.$shouldObserve_$=!1;this.$unlistenOnDestroy_$=null;this.$viewport_$=$baseElement$$.getViewport();this.$subscriptionApi_$=new $SubscriptionApi$$module$src$iframe_helper$$($iframe$jscomp$8$$,$opt_is3p$$||!1,function(){$JSCompiler_StaticMethods_startSendingIntersection_$$($$jscomp$this$jscomp$4$$)});
this.$intersectionObserver_$=new $IntersectionObserverPolyfill$$module$src$intersection_observer_polyfill$$(function($baseElement$$){for(var $iframe$jscomp$8$$=0;$iframe$jscomp$8$$<$baseElement$$.length;$iframe$jscomp$8$$++)delete $baseElement$$[$iframe$jscomp$8$$].target;$$jscomp$this$jscomp$4$$.$subscriptionApi_$.send("intersection",$dict$$module$src$utils$object$$({changes:$baseElement$$}))});this.$intersectionObserver_$.tick(this.$viewport_$.getRect());this.fire=function(){$$jscomp$this$jscomp$4$$.$shouldObserve_$&&
$$jscomp$this$jscomp$4$$.$isInViewport_$&&$$jscomp$this$jscomp$4$$.$intersectionObserver_$.tick($$jscomp$this$jscomp$4$$.$viewport_$.getRect())}}
function $JSCompiler_StaticMethods_startSendingIntersection_$$($JSCompiler_StaticMethods_startSendingIntersection_$self$$){$JSCompiler_StaticMethods_startSendingIntersection_$self$$.$shouldObserve_$=!0;$JSCompiler_StaticMethods_startSendingIntersection_$self$$.$intersectionObserver_$.observe($JSCompiler_StaticMethods_startSendingIntersection_$self$$.$baseElement_$.element);$JSCompiler_StaticMethods_startSendingIntersection_$self$$.$baseElement_$.getVsync().measure(function(){$JSCompiler_StaticMethods_startSendingIntersection_$self$$.$isInViewport_$=
$JSCompiler_StaticMethods_startSendingIntersection_$self$$.$baseElement_$.isInViewport();$JSCompiler_StaticMethods_startSendingIntersection_$self$$.fire()});var $unlistenViewportScroll$$=$JSCompiler_StaticMethods_startSendingIntersection_$self$$.$viewport_$.onScroll($JSCompiler_StaticMethods_startSendingIntersection_$self$$.fire),$unlistenViewportChange$$=$JSCompiler_StaticMethods_startSendingIntersection_$self$$.$viewport_$.onChanged($JSCompiler_StaticMethods_startSendingIntersection_$self$$.fire);
$JSCompiler_StaticMethods_startSendingIntersection_$self$$.$unlistenOnDestroy_$=function(){$unlistenViewportScroll$$();$unlistenViewportChange$$()}}$IntersectionObserverApi$$module$src$intersection_observer_polyfill$$.prototype.onViewportCallback=function($inViewport$$){this.$isInViewport_$=$inViewport$$};
$IntersectionObserverApi$$module$src$intersection_observer_polyfill$$.prototype.destroy=function(){this.$shouldObserve_$=!1;this.$intersectionObserver_$.disconnect();this.$intersectionObserver_$=null;this.$unlistenOnDestroy_$&&(this.$unlistenOnDestroy_$(),this.$unlistenOnDestroy_$=null);this.$subscriptionApi_$.destroy();this.$subscriptionApi_$=null};
function $IntersectionObserverPolyfill$$module$src$intersection_observer_polyfill$$($callback$jscomp$67_i$jscomp$30$$){var $opt_option$$={threshold:$DEFAULT_THRESHOLD$$module$src$intersection_observer_polyfill$$};this.$callback_$=$callback$jscomp$67_i$jscomp$30$$;var $threshold$$=$opt_option$$&&$opt_option$$.threshold;$threshold$$=$threshold$$?Array.isArray($threshold$$)?$threshold$$:[$threshold$$]:[0];for($callback$jscomp$67_i$jscomp$30$$=0;$callback$jscomp$67_i$jscomp$30$$<$threshold$$.length;$callback$jscomp$67_i$jscomp$30$$++)$isFiniteNumber$$module$src$types$$($threshold$$[$callback$jscomp$67_i$jscomp$30$$]);
this.$threshold_$=$threshold$$.sort();this.$lastViewportRect_$=null;this.$lastIframeRect_$=void 0;this.$observeEntries_$=[];this.$mutationPass_$=this.$hiddenObserverUnlistener_$=null}$JSCompiler_prototypeAlias$$=$IntersectionObserverPolyfill$$module$src$intersection_observer_polyfill$$.prototype;$JSCompiler_prototypeAlias$$.disconnect=function(){this.$observeEntries_$.length=0;$JSCompiler_StaticMethods_disconnectMutationObserver_$$(this)};
$JSCompiler_prototypeAlias$$.observe=function($JSCompiler_ampdoc$jscomp$inline_208_JSCompiler_embedService$jscomp$inline_178_JSCompiler_holder$jscomp$inline_209_JSCompiler_inline_result$jscomp$156_element$jscomp$71$$){for(var $JSCompiler_win$jscomp$inline_176_ampdoc$jscomp$11_change$jscomp$1_i$jscomp$31$$=0;$JSCompiler_win$jscomp$inline_176_ampdoc$jscomp$11_change$jscomp$1_i$jscomp$31$$<this.$observeEntries_$.length;$JSCompiler_win$jscomp$inline_176_ampdoc$jscomp$11_change$jscomp$1_i$jscomp$31$$++)if(this.$observeEntries_$[$JSCompiler_win$jscomp$inline_176_ampdoc$jscomp$11_change$jscomp$1_i$jscomp$31$$].element===
$JSCompiler_ampdoc$jscomp$inline_208_JSCompiler_embedService$jscomp$inline_178_JSCompiler_holder$jscomp$inline_209_JSCompiler_inline_result$jscomp$156_element$jscomp$71$$){$dev$$module$src$log$$().warn("INTERSECTION-OBSERVER","should observe same element once");return}var $newState$$={element:$JSCompiler_ampdoc$jscomp$inline_208_JSCompiler_embedService$jscomp$inline_178_JSCompiler_holder$jscomp$inline_209_JSCompiler_inline_result$jscomp$156_element$jscomp$71$$,currentThresholdSlot:0};this.$lastViewportRect_$&&
($JSCompiler_win$jscomp$inline_176_ampdoc$jscomp$11_change$jscomp$1_i$jscomp$31$$=$JSCompiler_StaticMethods_getValidIntersectionChangeEntry_$$(this,$newState$$,this.$lastViewportRect_$,this.$lastIframeRect_$))&&this.$callback_$([$JSCompiler_win$jscomp$inline_176_ampdoc$jscomp$11_change$jscomp$1_i$jscomp$31$$]);$JSCompiler_win$jscomp$inline_176_ampdoc$jscomp$11_change$jscomp$1_i$jscomp$31$$=$getAmpdoc$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_208_JSCompiler_embedService$jscomp$inline_178_JSCompiler_holder$jscomp$inline_209_JSCompiler_inline_result$jscomp$156_element$jscomp$71$$);
if($JSCompiler_win$jscomp$inline_176_ampdoc$jscomp$11_change$jscomp$1_i$jscomp$31$$.win.MutationObserver&&!this.$hiddenObserverUnlistener_$){this.$mutationPass_$=new $Pass$$module$src$pass$$($JSCompiler_win$jscomp$inline_176_ampdoc$jscomp$11_change$jscomp$1_i$jscomp$31$$.win,this.$handleMutationObserverPass_$.bind(this,$JSCompiler_ampdoc$jscomp$inline_208_JSCompiler_embedService$jscomp$inline_178_JSCompiler_holder$jscomp$inline_209_JSCompiler_inline_result$jscomp$156_element$jscomp$71$$));a:if($JSCompiler_win$jscomp$inline_176_ampdoc$jscomp$11_change$jscomp$1_i$jscomp$31$$=
$JSCompiler_ampdoc$jscomp$inline_208_JSCompiler_embedService$jscomp$inline_178_JSCompiler_holder$jscomp$inline_209_JSCompiler_inline_result$jscomp$156_element$jscomp$71$$.ownerDocument.defaultView,$JSCompiler_win$jscomp$inline_176_ampdoc$jscomp$11_change$jscomp$1_i$jscomp$31$$!=($JSCompiler_win$jscomp$inline_176_ampdoc$jscomp$11_change$jscomp$1_i$jscomp$31$$.__AMP_TOP||$JSCompiler_win$jscomp$inline_176_ampdoc$jscomp$11_change$jscomp$1_i$jscomp$31$$)){if($isServiceRegistered$$module$src$service$$($JSCompiler_win$jscomp$inline_176_ampdoc$jscomp$11_change$jscomp$1_i$jscomp$31$$,
"hidden-observer")&&($JSCompiler_ampdoc$jscomp$inline_208_JSCompiler_embedService$jscomp$inline_178_JSCompiler_holder$jscomp$inline_209_JSCompiler_inline_result$jscomp$156_element$jscomp$71$$=$getServiceInternal$$module$src$service$$($JSCompiler_win$jscomp$inline_176_ampdoc$jscomp$11_change$jscomp$1_i$jscomp$31$$,"hidden-observer")))break a;$JSCompiler_ampdoc$jscomp$inline_208_JSCompiler_embedService$jscomp$inline_178_JSCompiler_holder$jscomp$inline_209_JSCompiler_inline_result$jscomp$156_element$jscomp$71$$=
null}else $JSCompiler_ampdoc$jscomp$inline_208_JSCompiler_embedService$jscomp$inline_178_JSCompiler_holder$jscomp$inline_209_JSCompiler_inline_result$jscomp$156_element$jscomp$71$$=$getAmpdoc$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_208_JSCompiler_embedService$jscomp$inline_178_JSCompiler_holder$jscomp$inline_209_JSCompiler_inline_result$jscomp$156_element$jscomp$71$$),$JSCompiler_ampdoc$jscomp$inline_208_JSCompiler_embedService$jscomp$inline_178_JSCompiler_holder$jscomp$inline_209_JSCompiler_inline_result$jscomp$156_element$jscomp$71$$=
$getAmpdocServiceHolder$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_208_JSCompiler_embedService$jscomp$inline_178_JSCompiler_holder$jscomp$inline_209_JSCompiler_inline_result$jscomp$156_element$jscomp$71$$),$JSCompiler_ampdoc$jscomp$inline_208_JSCompiler_embedService$jscomp$inline_178_JSCompiler_holder$jscomp$inline_209_JSCompiler_inline_result$jscomp$156_element$jscomp$71$$=$isServiceRegistered$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_208_JSCompiler_embedService$jscomp$inline_178_JSCompiler_holder$jscomp$inline_209_JSCompiler_inline_result$jscomp$156_element$jscomp$71$$,
"hidden-observer")?$getServiceInternal$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_208_JSCompiler_embedService$jscomp$inline_178_JSCompiler_holder$jscomp$inline_209_JSCompiler_inline_result$jscomp$156_element$jscomp$71$$,"hidden-observer"):null;var $hiddenObserver$$=$JSCompiler_ampdoc$jscomp$inline_208_JSCompiler_embedService$jscomp$inline_178_JSCompiler_holder$jscomp$inline_209_JSCompiler_inline_result$jscomp$156_element$jscomp$71$$;this.$hiddenObserverUnlistener_$=$hiddenObserver$$.add(this.$handleMutationObserverNotification_$.bind(this))}this.$observeEntries_$.push($newState$$)};
$JSCompiler_prototypeAlias$$.unobserve=function($element$jscomp$72$$){for(var $i$jscomp$32$$=0;$i$jscomp$32$$<this.$observeEntries_$.length;$i$jscomp$32$$++)if(this.$observeEntries_$[$i$jscomp$32$$].element===$element$jscomp$72$$){this.$observeEntries_$.splice($i$jscomp$32$$,1);0>=this.$observeEntries_$.length&&$JSCompiler_StaticMethods_disconnectMutationObserver_$$(this);return}$dev$$module$src$log$$().warn("INTERSECTION-OBSERVER","unobserve non-observed element")};
$JSCompiler_prototypeAlias$$.tick=function($hostViewport$jscomp$1$$,$opt_iframe$$){$opt_iframe$$&&($hostViewport$jscomp$1$$=$moveLayoutRect$$module$src$layout_rect$$($hostViewport$jscomp$1$$,-$opt_iframe$$.left,-$opt_iframe$$.top),$opt_iframe$$=$moveLayoutRect$$module$src$layout_rect$$($opt_iframe$$,-$opt_iframe$$.left,-$opt_iframe$$.top));this.$lastViewportRect_$=$hostViewport$jscomp$1$$;this.$lastIframeRect_$=$opt_iframe$$;for(var $changes$$=[],$i$jscomp$33$$=0;$i$jscomp$33$$<this.$observeEntries_$.length;$i$jscomp$33$$++){var $change$jscomp$2$$=
$JSCompiler_StaticMethods_getValidIntersectionChangeEntry_$$(this,this.$observeEntries_$[$i$jscomp$33$$],$hostViewport$jscomp$1$$,$opt_iframe$$);$change$jscomp$2$$&&$changes$$.push($change$jscomp$2$$)}$changes$$.length&&this.$callback_$($changes$$)};
function $JSCompiler_StaticMethods_getValidIntersectionChangeEntry_$$($JSCompiler_StaticMethods_getValidIntersectionChangeEntry_$self_JSCompiler_boundingClientRect$jscomp$inline_103_JSCompiler_inline_result$jscomp$32_JSCompiler_sortedThreshold$jscomp$inline_92$$,$state$$,$JSCompiler_hostViewport$jscomp$inline_100_hostViewport$jscomp$2$$,$JSCompiler_intersection$jscomp$inline_101_opt_iframe$jscomp$1$$){var $element$jscomp$73$$=$state$$.element,$elementRect$$=$element$jscomp$73$$.getLayoutBox(),$JSCompiler_inline_result$jscomp$31_JSCompiler_larger$jscomp$inline_88_JSCompiler_largerBoxArea$jscomp$inline_90_owner$jscomp$1$$=
$element$jscomp$73$$.getOwner(),$ownerRect$$=$JSCompiler_inline_result$jscomp$31_JSCompiler_larger$jscomp$inline_88_JSCompiler_largerBoxArea$jscomp$inline_90_owner$jscomp$1$$&&$JSCompiler_inline_result$jscomp$31_JSCompiler_larger$jscomp$inline_88_JSCompiler_largerBoxArea$jscomp$inline_90_owner$jscomp$1$$.getLayoutBox(),$intersectionRect$$=$rectIntersection$$module$src$layout_rect$$($elementRect$$,$ownerRect$$,$JSCompiler_hostViewport$jscomp$inline_100_hostViewport$jscomp$2$$,$JSCompiler_intersection$jscomp$inline_101_opt_iframe$jscomp$1$$)||
$layoutRectLtwh$$module$src$layout_rect$$(0,0,0,0),$JSCompiler_rootBounds$jscomp$inline_104_JSCompiler_smaller$jscomp$inline_87_JSCompiler_smallerBoxArea$jscomp$inline_89_JSCompiler_startIdx$jscomp$inline_94$$=$intersectionRect$$;$JSCompiler_inline_result$jscomp$31_JSCompiler_larger$jscomp$inline_88_JSCompiler_largerBoxArea$jscomp$inline_90_owner$jscomp$1$$=$elementRect$$;$JSCompiler_rootBounds$jscomp$inline_104_JSCompiler_smaller$jscomp$inline_87_JSCompiler_smallerBoxArea$jscomp$inline_89_JSCompiler_startIdx$jscomp$inline_94$$=
$JSCompiler_rootBounds$jscomp$inline_104_JSCompiler_smaller$jscomp$inline_87_JSCompiler_smallerBoxArea$jscomp$inline_89_JSCompiler_startIdx$jscomp$inline_94$$.width*$JSCompiler_rootBounds$jscomp$inline_104_JSCompiler_smaller$jscomp$inline_87_JSCompiler_smallerBoxArea$jscomp$inline_89_JSCompiler_startIdx$jscomp$inline_94$$.height;$JSCompiler_inline_result$jscomp$31_JSCompiler_larger$jscomp$inline_88_JSCompiler_largerBoxArea$jscomp$inline_90_owner$jscomp$1$$=$JSCompiler_inline_result$jscomp$31_JSCompiler_larger$jscomp$inline_88_JSCompiler_largerBoxArea$jscomp$inline_90_owner$jscomp$1$$.width*
$JSCompiler_inline_result$jscomp$31_JSCompiler_larger$jscomp$inline_88_JSCompiler_largerBoxArea$jscomp$inline_90_owner$jscomp$1$$.height;$JSCompiler_inline_result$jscomp$31_JSCompiler_larger$jscomp$inline_88_JSCompiler_largerBoxArea$jscomp$inline_90_owner$jscomp$1$$=0===$JSCompiler_inline_result$jscomp$31_JSCompiler_larger$jscomp$inline_88_JSCompiler_largerBoxArea$jscomp$inline_90_owner$jscomp$1$$?0:$JSCompiler_rootBounds$jscomp$inline_104_JSCompiler_smaller$jscomp$inline_87_JSCompiler_smallerBoxArea$jscomp$inline_89_JSCompiler_startIdx$jscomp$inline_94$$/
$JSCompiler_inline_result$jscomp$31_JSCompiler_larger$jscomp$inline_88_JSCompiler_largerBoxArea$jscomp$inline_90_owner$jscomp$1$$;$JSCompiler_StaticMethods_getValidIntersectionChangeEntry_$self_JSCompiler_boundingClientRect$jscomp$inline_103_JSCompiler_inline_result$jscomp$32_JSCompiler_sortedThreshold$jscomp$inline_92$$=$JSCompiler_StaticMethods_getValidIntersectionChangeEntry_$self_JSCompiler_boundingClientRect$jscomp$inline_103_JSCompiler_inline_result$jscomp$32_JSCompiler_sortedThreshold$jscomp$inline_92$$.$threshold_$;
$JSCompiler_rootBounds$jscomp$inline_104_JSCompiler_smaller$jscomp$inline_87_JSCompiler_smallerBoxArea$jscomp$inline_89_JSCompiler_startIdx$jscomp$inline_94$$=0;var $JSCompiler_endIdx$jscomp$inline_95$$=$JSCompiler_StaticMethods_getValidIntersectionChangeEntry_$self_JSCompiler_boundingClientRect$jscomp$inline_103_JSCompiler_inline_result$jscomp$32_JSCompiler_sortedThreshold$jscomp$inline_92$$.length;if(0==$JSCompiler_inline_result$jscomp$31_JSCompiler_larger$jscomp$inline_88_JSCompiler_largerBoxArea$jscomp$inline_90_owner$jscomp$1$$)$JSCompiler_StaticMethods_getValidIntersectionChangeEntry_$self_JSCompiler_boundingClientRect$jscomp$inline_103_JSCompiler_inline_result$jscomp$32_JSCompiler_sortedThreshold$jscomp$inline_92$$=
0;else{for(var $JSCompiler_mid$jscomp$inline_96$$=($JSCompiler_rootBounds$jscomp$inline_104_JSCompiler_smaller$jscomp$inline_87_JSCompiler_smallerBoxArea$jscomp$inline_89_JSCompiler_startIdx$jscomp$inline_94$$+$JSCompiler_endIdx$jscomp$inline_95$$)/2|0;$JSCompiler_rootBounds$jscomp$inline_104_JSCompiler_smaller$jscomp$inline_87_JSCompiler_smallerBoxArea$jscomp$inline_89_JSCompiler_startIdx$jscomp$inline_94$$<$JSCompiler_mid$jscomp$inline_96$$;)$JSCompiler_inline_result$jscomp$31_JSCompiler_larger$jscomp$inline_88_JSCompiler_largerBoxArea$jscomp$inline_90_owner$jscomp$1$$<
$JSCompiler_StaticMethods_getValidIntersectionChangeEntry_$self_JSCompiler_boundingClientRect$jscomp$inline_103_JSCompiler_inline_result$jscomp$32_JSCompiler_sortedThreshold$jscomp$inline_92$$[$JSCompiler_mid$jscomp$inline_96$$]?$JSCompiler_endIdx$jscomp$inline_95$$=$JSCompiler_mid$jscomp$inline_96$$:$JSCompiler_rootBounds$jscomp$inline_104_JSCompiler_smaller$jscomp$inline_87_JSCompiler_smallerBoxArea$jscomp$inline_89_JSCompiler_startIdx$jscomp$inline_94$$=$JSCompiler_mid$jscomp$inline_96$$,$JSCompiler_mid$jscomp$inline_96$$=
($JSCompiler_rootBounds$jscomp$inline_104_JSCompiler_smaller$jscomp$inline_87_JSCompiler_smallerBoxArea$jscomp$inline_89_JSCompiler_startIdx$jscomp$inline_94$$+$JSCompiler_endIdx$jscomp$inline_95$$)/2|0;$JSCompiler_StaticMethods_getValidIntersectionChangeEntry_$self_JSCompiler_boundingClientRect$jscomp$inline_103_JSCompiler_inline_result$jscomp$32_JSCompiler_sortedThreshold$jscomp$inline_92$$=$JSCompiler_endIdx$jscomp$inline_95$$}var $newThresholdSlot$$=$JSCompiler_StaticMethods_getValidIntersectionChangeEntry_$self_JSCompiler_boundingClientRect$jscomp$inline_103_JSCompiler_inline_result$jscomp$32_JSCompiler_sortedThreshold$jscomp$inline_92$$;
if($newThresholdSlot$$==$state$$.currentThresholdSlot)return null;$state$$.currentThresholdSlot=$newThresholdSlot$$;$JSCompiler_hostViewport$jscomp$inline_100_hostViewport$jscomp$2$$=$JSCompiler_intersection$jscomp$inline_101_opt_iframe$jscomp$1$$?null:$JSCompiler_hostViewport$jscomp$inline_100_hostViewport$jscomp$2$$;$JSCompiler_intersection$jscomp$inline_101_opt_iframe$jscomp$1$$=$intersectionRect$$;$JSCompiler_StaticMethods_getValidIntersectionChangeEntry_$self_JSCompiler_boundingClientRect$jscomp$inline_103_JSCompiler_inline_result$jscomp$32_JSCompiler_sortedThreshold$jscomp$inline_92$$=
$elementRect$$;if($JSCompiler_rootBounds$jscomp$inline_104_JSCompiler_smaller$jscomp$inline_87_JSCompiler_smallerBoxArea$jscomp$inline_89_JSCompiler_startIdx$jscomp$inline_94$$=$JSCompiler_hostViewport$jscomp$inline_100_hostViewport$jscomp$2$$)$JSCompiler_intersection$jscomp$inline_101_opt_iframe$jscomp$1$$=$moveLayoutRect$$module$src$layout_rect$$($JSCompiler_intersection$jscomp$inline_101_opt_iframe$jscomp$1$$,-$JSCompiler_hostViewport$jscomp$inline_100_hostViewport$jscomp$2$$.left,-$JSCompiler_hostViewport$jscomp$inline_100_hostViewport$jscomp$2$$.top),
$JSCompiler_StaticMethods_getValidIntersectionChangeEntry_$self_JSCompiler_boundingClientRect$jscomp$inline_103_JSCompiler_inline_result$jscomp$32_JSCompiler_sortedThreshold$jscomp$inline_92$$=$moveLayoutRect$$module$src$layout_rect$$($JSCompiler_StaticMethods_getValidIntersectionChangeEntry_$self_JSCompiler_boundingClientRect$jscomp$inline_103_JSCompiler_inline_result$jscomp$32_JSCompiler_sortedThreshold$jscomp$inline_92$$,-$JSCompiler_hostViewport$jscomp$inline_100_hostViewport$jscomp$2$$.left,
-$JSCompiler_hostViewport$jscomp$inline_100_hostViewport$jscomp$2$$.top),$JSCompiler_rootBounds$jscomp$inline_104_JSCompiler_smaller$jscomp$inline_87_JSCompiler_smallerBoxArea$jscomp$inline_89_JSCompiler_startIdx$jscomp$inline_94$$=$moveLayoutRect$$module$src$layout_rect$$($JSCompiler_rootBounds$jscomp$inline_104_JSCompiler_smaller$jscomp$inline_87_JSCompiler_smallerBoxArea$jscomp$inline_89_JSCompiler_startIdx$jscomp$inline_94$$,-$JSCompiler_hostViewport$jscomp$inline_100_hostViewport$jscomp$2$$.left,
-$JSCompiler_hostViewport$jscomp$inline_100_hostViewport$jscomp$2$$.top);var $changeEntry$$={time:"undefined"!==typeof performance&&performance.now?performance.now():Date.now()-$INIT_TIME$$module$src$intersection_observer_polyfill$$,rootBounds:$JSCompiler_rootBounds$jscomp$inline_104_JSCompiler_smaller$jscomp$inline_87_JSCompiler_smallerBoxArea$jscomp$inline_89_JSCompiler_startIdx$jscomp$inline_94$$,boundingClientRect:$JSCompiler_StaticMethods_getValidIntersectionChangeEntry_$self_JSCompiler_boundingClientRect$jscomp$inline_103_JSCompiler_inline_result$jscomp$32_JSCompiler_sortedThreshold$jscomp$inline_92$$,
intersectionRect:$JSCompiler_intersection$jscomp$inline_101_opt_iframe$jscomp$1$$,intersectionRatio:$JSCompiler_inline_result$jscomp$31_JSCompiler_larger$jscomp$inline_88_JSCompiler_largerBoxArea$jscomp$inline_90_owner$jscomp$1$$,target:$element$jscomp$73$$};return $changeEntry$$}$JSCompiler_prototypeAlias$$.$handleMutationObserverNotification_$=function(){this.$mutationPass_$.isPending()||this.$mutationPass_$.schedule(16)};
$JSCompiler_prototypeAlias$$.$handleMutationObserverPass_$=function($element$jscomp$74$$){var $$jscomp$this$jscomp$6$$=this,$viewport$jscomp$1$$=$getServiceForDoc$$module$src$service$$($element$jscomp$74$$,"viewport"),$resources$$=$getServiceForDoc$$module$src$service$$($element$jscomp$74$$,"resources");$resources$$.onNextPass(function(){$$jscomp$this$jscomp$6$$.tick($viewport$jscomp$1$$.getRect())})};
function $JSCompiler_StaticMethods_disconnectMutationObserver_$$($JSCompiler_StaticMethods_disconnectMutationObserver_$self$$){$JSCompiler_StaticMethods_disconnectMutationObserver_$self$$.$hiddenObserverUnlistener_$&&$JSCompiler_StaticMethods_disconnectMutationObserver_$self$$.$hiddenObserverUnlistener_$();$JSCompiler_StaticMethods_disconnectMutationObserver_$self$$.$hiddenObserverUnlistener_$=null;$JSCompiler_StaticMethods_disconnectMutationObserver_$self$$.$mutationPass_$&&$JSCompiler_StaticMethods_disconnectMutationObserver_$self$$.$mutationPass_$.cancel();
$JSCompiler_StaticMethods_disconnectMutationObserver_$self$$.$mutationPass_$=null};var $webviewRegExp$$module$extensions$amp_apester_media$0_1$utils$$=/(WebView|(iPhone|iPod|iPad)(?!.*Safari)|Android.*(wv|.0.0.0)|Linux; U; Android)/ig;
function $getPlatform$$module$extensions$amp_apester_media$0_1$utils$$(){var $webview$$=!!navigator.userAgent.match($webviewRegExp$$module$extensions$amp_apester_media$0_1$utils$$),$JSCompiler_userAgent$jscomp$inline_108$$=navigator.userAgent||navigator.vendor||window.opera,$isMobile$$=/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino|android|ipad|playbook|silk/i.test($JSCompiler_userAgent$jscomp$inline_108$$)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test($JSCompiler_userAgent$jscomp$inline_108$$.substr(0,
4));return $isMobile$$?"mobile"+($webview$$?"-webview":""):"desktop"}function $extractElementTags$$module$extensions$amp_apester_media$0_1$utils$$($element$jscomp$76$$){var $tagsAttribute$$=$element$jscomp$76$$&&$element$jscomp$76$$.getAttribute("data-apester-tags");return $tagsAttribute$$?$tagsAttribute$$.split(",").map(function($element$jscomp$76$$){return $element$jscomp$76$$.trim()})||[]:[]}
function $extratctTitle$$module$extensions$amp_apester_media$0_1$utils$$($root$jscomp$7$$){var $scriptTags$$=$toArray$$module$src$types$$($root$jscomp$7$$.querySelectorAll('script[type="application/ld+json"]'));return $scriptTags$$.map(function($root$jscomp$7$$){var $scriptTags$$;if($scriptTags$$=$root$jscomp$7$$)$scriptTags$$=$root$jscomp$7$$,$scriptTags$$="SCRIPT"==$scriptTags$$.tagName&&"APPLICATION/LD+JSON"==$scriptTags$$.getAttribute("type").toUpperCase();return $scriptTags$$?$tryParseJson$$module$src$json$$($root$jscomp$7$$.textContent)||
{}:{}}).map(function($root$jscomp$7$$){return $root$jscomp$7$$&&$root$jscomp$7$$.headline}).filter(function($root$jscomp$7$$){return"string"===typeof $root$jscomp$7$$}).map(function($root$jscomp$7$$){return $root$jscomp$7$$.trim().split(" ").filter(function($root$jscomp$7$$){return 2<$root$jscomp$7$$.length})}).reduce(function($root$jscomp$7$$,$scriptTags$$){return $root$jscomp$7$$.concat($scriptTags$$)},[]).slice(0,5)}
function $extractArticleTags$$module$extensions$amp_apester_media$0_1$utils$$($root$jscomp$8$$){var $metaKeywords$$=$root$jscomp$8$$.querySelector('meta[name="keywords"]')||{content:""};return $metaKeywords$$.content.trim().split(",").filter(function($root$jscomp$8$$){return $root$jscomp$8$$}).map(function($root$jscomp$8$$){return $root$jscomp$8$$.trim()})}
function $extractTags$$module$extensions$amp_apester_media$0_1$utils$$($root$jscomp$9$$,$element$jscomp$77$$){var $extractedTags$$=$extractElementTags$$module$extensions$amp_apester_media$0_1$utils$$($element$jscomp$77$$)||[],$articleMetaTags$$=$extractArticleTags$$module$extensions$amp_apester_media$0_1$utils$$($root$jscomp$9$$),$concatedTags$$=$extractedTags$$.concat($articleMetaTags$$.length?$articleMetaTags$$:$extratctTitle$$module$extensions$amp_apester_media$0_1$utils$$($root$jscomp$9$$)||[]),
$loweredCase$$=$concatedTags$$.map(function($root$jscomp$9$$){return $root$jscomp$9$$.toLowerCase().trim()}),$noDuplication$$=$loweredCase$$.filter(function($root$jscomp$9$$,$element$jscomp$77$$,$extractedTags$$){return $extractedTags$$.indexOf($root$jscomp$9$$)===$element$jscomp$77$$});return $noDuplication$$}
function $registerEvent$$module$extensions$amp_apester_media$0_1$utils$$($eventName$$,$callback$jscomp$68$$,$unlisten$jscomp$4_win$jscomp$50$$,$iframe$jscomp$9$$,$unlisteners$$){$unlisten$jscomp$4_win$jscomp$50$$=$listen$$module$src$event_helper$$($unlisten$jscomp$4_win$jscomp$50$$,function($unlisten$jscomp$4_win$jscomp$50$$){var $unlisteners$$=$iframe$jscomp$9$$.contentWindow===$unlisten$jscomp$4_win$jscomp$50$$.source;$unlisten$jscomp$4_win$jscomp$50$$.data.type===$eventName$$&&$unlisteners$$&&
$callback$jscomp$68$$($unlisten$jscomp$4_win$jscomp$50$$.data)});$unlisteners$$.push($unlisten$jscomp$4_win$jscomp$50$$)}
function $generatePixelURL$$module$extensions$amp_apester_media$0_1$utils$$($publisherId$$,$affiliateId$$){var $qsObj$$={offer_id:2,aff_id:$affiliateId$$,aff_sub:$publisherId$$,aff_sub2:window.location.hostname,aff_sub3:"amp"},$qs$$=Object.keys($qsObj$$).map(function($publisherId$$){return $publisherId$$+"="+$qsObj$$[$publisherId$$]}).join("&");return"https://apester.go2cloud.org/aff_i?"+$qs$$};function $getLengthNumeral$$module$src$layout$$($length$jscomp$21_res$jscomp$2$$){$length$jscomp$21_res$jscomp$2$$=parseFloat($length$jscomp$21_res$jscomp$2$$);return $isFiniteNumber$$module$src$types$$($length$jscomp$21_res$jscomp$2$$)?$length$jscomp$21_res$jscomp$2$$:void 0};function $AmpApesterMedia$$module$extensions$amp_apester_media$0_1$amp_apester_media$$($$jscomp$super$this_element$jscomp$84$$){$$jscomp$super$this_element$jscomp$84$$=AMP.BaseElement.call(this,$$jscomp$super$this_element$jscomp$84$$)||this;$$jscomp$super$this_element$jscomp$84$$.$rendererBaseUrl_$="https://renderer.apester.com";$$jscomp$super$this_element$jscomp$84$$.$displayBaseUrl_$="https://display.apester.com";$$jscomp$super$this_element$jscomp$84$$.$staticContent_$="https://static.qmerce.com";
$$jscomp$super$this_element$jscomp$84$$.$loaderUrl_$="https://static.apester.com/js/assets/loader.gif";$$jscomp$super$this_element$jscomp$84$$.$seen_$=!1;$$jscomp$super$this_element$jscomp$84$$.$iframe_$=null;$$jscomp$super$this_element$jscomp$84$$.$placeholder_$=null;$$jscomp$super$this_element$jscomp$84$$.$ready_$=!1;$$jscomp$super$this_element$jscomp$84$$.$width_$=null;$$jscomp$super$this_element$jscomp$84$$.$height_$=null;$$jscomp$super$this_element$jscomp$84$$.$random_$=!1;$$jscomp$super$this_element$jscomp$84$$.$mediaAttribute_$=
null;$$jscomp$super$this_element$jscomp$84$$.$embedOptions_$={};$$jscomp$super$this_element$jscomp$84$$.$mediaId_$=null;$$jscomp$super$this_element$jscomp$84$$.$unlisteners_$=[];$$jscomp$super$this_element$jscomp$84$$.$intersectionObserverApi_$=null;return $$jscomp$super$this_element$jscomp$84$$}var $JSCompiler_parentCtor$jscomp$inline_113$$=AMP.BaseElement;$AmpApesterMedia$$module$extensions$amp_apester_media$0_1$amp_apester_media$$.prototype=$$jscomp$objectCreate$$($JSCompiler_parentCtor$jscomp$inline_113$$.prototype);
$AmpApesterMedia$$module$extensions$amp_apester_media$0_1$amp_apester_media$$.prototype.constructor=$AmpApesterMedia$$module$extensions$amp_apester_media$0_1$amp_apester_media$$;
if($$jscomp$setPrototypeOf$$)$$jscomp$setPrototypeOf$$($AmpApesterMedia$$module$extensions$amp_apester_media$0_1$amp_apester_media$$,$JSCompiler_parentCtor$jscomp$inline_113$$);else for(var $JSCompiler_p$jscomp$inline_114$$ in $JSCompiler_parentCtor$jscomp$inline_113$$)if("prototype"!=$JSCompiler_p$jscomp$inline_114$$)if(Object.defineProperties){var $JSCompiler_descriptor$jscomp$inline_115$$=Object.getOwnPropertyDescriptor($JSCompiler_parentCtor$jscomp$inline_113$$,$JSCompiler_p$jscomp$inline_114$$);
$JSCompiler_descriptor$jscomp$inline_115$$&&Object.defineProperty($AmpApesterMedia$$module$extensions$amp_apester_media$0_1$amp_apester_media$$,$JSCompiler_p$jscomp$inline_114$$,$JSCompiler_descriptor$jscomp$inline_115$$)}else $AmpApesterMedia$$module$extensions$amp_apester_media$0_1$amp_apester_media$$[$JSCompiler_p$jscomp$inline_114$$]=$JSCompiler_parentCtor$jscomp$inline_113$$[$JSCompiler_p$jscomp$inline_114$$];
$AmpApesterMedia$$module$extensions$amp_apester_media$0_1$amp_apester_media$$.$superClass_$=$JSCompiler_parentCtor$jscomp$inline_113$$.prototype;$JSCompiler_prototypeAlias$$=$AmpApesterMedia$$module$extensions$amp_apester_media$0_1$amp_apester_media$$.prototype;$JSCompiler_prototypeAlias$$.preconnectCallback=function($onLayout$$){this.preconnect.url(this.$displayBaseUrl_$,$onLayout$$);this.preconnect.url(this.$rendererBaseUrl_$,$onLayout$$);this.preconnect.url(this.$staticContent_$,$onLayout$$)};
$JSCompiler_prototypeAlias$$.isLayoutSupported=function($layout$jscomp$3$$){return"fixed"==$layout$jscomp$3$$||"fixed-height"==$layout$jscomp$3$$||"responsive"==$layout$jscomp$3$$||"fill"==$layout$jscomp$3$$||"flex-item"==$layout$jscomp$3$$||"fluid"==$layout$jscomp$3$$||"intrinsic"==$layout$jscomp$3$$};
$JSCompiler_prototypeAlias$$.viewportCallback=function($inViewport$jscomp$1$$){if(this.$intersectionObserverApi_$)this.$intersectionObserverApi_$.onViewportCallback($inViewport$jscomp$1$$);$inViewport$jscomp$1$$&&!this.$seen_$&&this.$iframe_$&&this.$iframe_$.contentWindow&&(this.$seen_$=!0,this.$iframe_$.contentWindow.postMessage("interaction seen","*"));this.getPlaceholder()&&!this.$ready_$&&this.togglePlaceholder($inViewport$jscomp$1$$)};
$JSCompiler_prototypeAlias$$.buildCallback=function(){var $JSCompiler_shouldBeTrueish$jscomp$inline_117_width$jscomp$30$$=this.element.getAttribute("width"),$JSCompiler_opt_1$jscomp$inline_118_height$jscomp$29$$=this.element.getAttribute("height");this.$width_$=$getLengthNumeral$$module$src$layout$$($JSCompiler_shouldBeTrueish$jscomp$inline_117_width$jscomp$30$$);this.$height_$=$getLengthNumeral$$module$src$layout$$($JSCompiler_opt_1$jscomp$inline_118_height$jscomp$29$$);this.$random_$=this.element.hasAttribute("data-apester-channel-token");
$JSCompiler_shouldBeTrueish$jscomp$inline_117_width$jscomp$30$$=this.element.getAttribute("data-apester-media-id")||this.element.getAttribute("data-apester-channel-token");$JSCompiler_opt_1$jscomp$inline_118_height$jscomp$29$$=this.element;if(!$logs$$module$src$log$$.user)throw Error("failed to call initLogConstructor");this.$mediaAttribute_$=$logs$$module$src$log$$.user.assert($JSCompiler_shouldBeTrueish$jscomp$inline_117_width$jscomp$30$$,"Either the data-apester-media-id or the data-apester-channel-token attributes must be specified for <amp-apester-media> %s",
$JSCompiler_opt_1$jscomp$inline_118_height$jscomp$29$$,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0);this.$embedOptions_$={playlist:this.$random_$,idOrToken:this.$mediaAttribute_$,inative:"true"===this.element.getAttribute("data-apester-inative"),fallback:this.element.getAttribute("data-apester-fallback"),distributionChannelId:this.element.getAttribute("data-apester-channel-id"),renderer:!0,tags:$extractTags$$module$extensions$amp_apester_media$0_1$utils$$(this.getAmpDoc().getRootNode(),
this.element)}};$JSCompiler_prototypeAlias$$.firstLayoutCompleted=function(){this.viewportCallback(this.isInViewport())};$JSCompiler_prototypeAlias$$.onLayoutMeasure=function(){this.$intersectionObserverApi_$&&this.$intersectionObserverApi_$.fire()};
function $JSCompiler_StaticMethods_buildUrl_$$($JSCompiler_StaticMethods_buildUrl_$self$$){var $$jscomp$destructuring$var20_suffix$jscomp$2$$=$JSCompiler_StaticMethods_buildUrl_$self$$.$embedOptions_$,$idOrToken$$=$$jscomp$destructuring$var20_suffix$jscomp$2$$.idOrToken,$playlist$$=$$jscomp$destructuring$var20_suffix$jscomp$2$$.playlist,$inative$$=$$jscomp$destructuring$var20_suffix$jscomp$2$$.inative,$distributionChannelId$$=$$jscomp$destructuring$var20_suffix$jscomp$2$$.distributionChannelId,$fallback$jscomp$1$$=
$$jscomp$destructuring$var20_suffix$jscomp$2$$.fallback,$tags$$=$$jscomp$destructuring$var20_suffix$jscomp$2$$.tags,$encodedMediaAttribute$$=encodeURIComponent($JSCompiler_StaticMethods_buildUrl_$self$$.$mediaAttribute_$);$$jscomp$destructuring$var20_suffix$jscomp$2$$="";var $queryParams$$={renderer:!1};$queryParams$$.platform=$getPlatform$$module$extensions$amp_apester_media$0_1$utils$$();$inative$$?$idOrToken$$?$$jscomp$destructuring$var20_suffix$jscomp$2$$="/inatives/"+$idOrToken$$:$distributionChannelId$$&&
($$jscomp$destructuring$var20_suffix$jscomp$2$$="/channels/"+$distributionChannelId$$+"/inatives"):$playlist$$&&$tags$$?($$jscomp$destructuring$var20_suffix$jscomp$2$$="/tokens/"+$encodedMediaAttribute$$+"/interactions/random",$queryParams$$.tags=$tags$$,$queryParams$$.fallback=!!$fallback$jscomp$1$$):$$jscomp$destructuring$var20_suffix$jscomp$2$$=$playlist$$?"/tokens/"+$encodedMediaAttribute$$+"/interactions/random":"/interactions/"+$encodedMediaAttribute$$+"/display";return $appendEncodedParamStringToUrl$$module$src$url$$(""+
$JSCompiler_StaticMethods_buildUrl_$self$$.$displayBaseUrl_$+$$jscomp$destructuring$var20_suffix$jscomp$2$$,$serializeQueryString$$module$src$url$$($queryParams$$))}
function $JSCompiler_StaticMethods_queryMedia_$$($JSCompiler_StaticMethods_queryMedia_$self$$){var $url$jscomp$41$$=$JSCompiler_StaticMethods_buildUrl_$$($JSCompiler_StaticMethods_queryMedia_$self$$);return $getService$$module$src$service$$($JSCompiler_StaticMethods_queryMedia_$self$$.win,"xhr").fetchJson($url$jscomp$41$$,{requireAmpResponseSourceOrigin:!1}).then(function($JSCompiler_StaticMethods_queryMedia_$self$$){return 200===$JSCompiler_StaticMethods_queryMedia_$self$$.status?$JSCompiler_StaticMethods_queryMedia_$self$$.json():
$JSCompiler_StaticMethods_queryMedia_$self$$})}
function $JSCompiler_StaticMethods_constructUrlFromMedia_$$($JSCompiler_StaticMethods_constructUrlFromMedia_$self_JSCompiler_url$jscomp$inline_129$$,$id$jscomp$35$$,$usePlayer$$){var $queryParams$jscomp$1$$={};$queryParams$jscomp$1$$.channelId=$JSCompiler_StaticMethods_constructUrlFromMedia_$self_JSCompiler_url$jscomp$inline_129$$.$embedOptions_$.distributionChannelId;$queryParams$jscomp$1$$.type=$JSCompiler_StaticMethods_constructUrlFromMedia_$self_JSCompiler_url$jscomp$inline_129$$.$embedOptions_$.playlist?"playlist":
"editorial";$queryParams$jscomp$1$$.platform=$getPlatform$$module$extensions$amp_apester_media$0_1$utils$$();$queryParams$jscomp$1$$.cannonicalUrl=$getServiceForDoc$$module$src$service$$($JSCompiler_StaticMethods_constructUrlFromMedia_$self_JSCompiler_url$jscomp$inline_129$$.element,"documentInfo").get().canonicalUrl;$queryParams$jscomp$1$$.sdk="amp";$JSCompiler_StaticMethods_constructUrlFromMedia_$self_JSCompiler_url$jscomp$inline_129$$=$JSCompiler_StaticMethods_constructUrlFromMedia_$self_JSCompiler_url$jscomp$inline_129$$.$rendererBaseUrl_$+
"/"+($usePlayer$$?"v2":"interaction")+"/"+(""+encodeURIComponent($id$jscomp$35$$));return $appendEncodedParamStringToUrl$$module$src$url$$($JSCompiler_StaticMethods_constructUrlFromMedia_$self_JSCompiler_url$jscomp$inline_129$$,$serializeQueryString$$module$src$url$$($queryParams$jscomp$1$$))}
function $JSCompiler_StaticMethods_constructIframe_$$($JSCompiler_StaticMethods_constructIframe_$self$$,$src$jscomp$4$$){var $iframe$jscomp$10$$=$JSCompiler_StaticMethods_constructIframe_$self$$.element.ownerDocument.createElement("iframe");$iframe$jscomp$10$$.setAttribute("frameborder","0");$iframe$jscomp$10$$.setAttribute("allowtransparency","true");$iframe$jscomp$10$$.setAttribute("scrolling","no");$iframe$jscomp$10$$.src=$src$jscomp$4$$;$iframe$jscomp$10$$.name=$JSCompiler_StaticMethods_constructIframe_$self$$.win.location.href;
$iframe$jscomp$10$$.height=$JSCompiler_StaticMethods_constructIframe_$self$$.$height_$;$iframe$jscomp$10$$.width=$JSCompiler_StaticMethods_constructIframe_$self$$.$width_$;$iframe$jscomp$10$$.classList.add("amp-apester-iframe");$JSCompiler_StaticMethods_constructIframe_$self$$.applyFillContent($iframe$jscomp$10$$);return $iframe$jscomp$10$$}
$JSCompiler_prototypeAlias$$.layoutCallback=function(){var $$jscomp$this$jscomp$7$$=this;this.element.classList.add("amp-apester-container");var $vsync$$=$getService$$module$src$service$$(this.win,"vsync");return $JSCompiler_StaticMethods_queryMedia_$$(this).then(function($payload$jscomp$2_response$jscomp$2_src$jscomp$5$$){if(!$payload$jscomp$2_response$jscomp$2_src$jscomp$5$$||204===$payload$jscomp$2_response$jscomp$2_src$jscomp$5$$.status)return $dev$$module$src$log$$().error("amp-apester-media",
"Display","No Content for provided tag"),$$jscomp$this$jscomp$7$$.unlayoutCallback();$payload$jscomp$2_response$jscomp$2_src$jscomp$5$$=$payload$jscomp$2_response$jscomp$2_src$jscomp$5$$.payload;var $media$jscomp$1$$=$$jscomp$this$jscomp$7$$.$embedOptions_$.playlist?$payload$jscomp$2_response$jscomp$2_src$jscomp$5$$[Math.floor(Math.random()*$payload$jscomp$2_response$jscomp$2_src$jscomp$5$$.length)]:$payload$jscomp$2_response$jscomp$2_src$jscomp$5$$,$interactionId$$=$media$jscomp$1$$.interactionId;
$payload$jscomp$2_response$jscomp$2_src$jscomp$5$$=$JSCompiler_StaticMethods_constructUrlFromMedia_$$($$jscomp$this$jscomp$7$$,$interactionId$$,$media$jscomp$1$$.usePlayer);var $iframe$jscomp$11$$=$JSCompiler_StaticMethods_constructIframe_$$($$jscomp$this$jscomp$7$$,$payload$jscomp$2_response$jscomp$2_src$jscomp$5$$);$$jscomp$this$jscomp$7$$.$intersectionObserverApi_$=new $IntersectionObserverApi$$module$src$intersection_observer_polyfill$$($$jscomp$this$jscomp$7$$,$iframe$jscomp$11$$);$$jscomp$this$jscomp$7$$.$mediaId_$=
$interactionId$$;$$jscomp$this$jscomp$7$$.$iframe_$=$iframe$jscomp$11$$;$JSCompiler_StaticMethods_registerToApesterEvents_$$($$jscomp$this$jscomp$7$$);return $vsync$$.mutatePromise(function(){var $vsync$$=$$jscomp$this$jscomp$7$$.element.ownerDocument.createElement("div");$vsync$$.setAttribute("overflow","");$vsync$$.className="amp-apester-overflow";var $payload$jscomp$2_response$jscomp$2_src$jscomp$5$$=$$jscomp$this$jscomp$7$$.element.ownerDocument.createElement("button");$payload$jscomp$2_response$jscomp$2_src$jscomp$5$$.textContent=
"Full Size";$vsync$$.appendChild($payload$jscomp$2_response$jscomp$2_src$jscomp$5$$);$$jscomp$this$jscomp$7$$.element.appendChild($vsync$$);$$jscomp$this$jscomp$7$$.element.appendChild($iframe$jscomp$11$$)}).then(function(){return $$jscomp$this$jscomp$7$$.loadPromise($iframe$jscomp$11$$).then(function(){return $vsync$$.mutatePromise(function(){$$jscomp$this$jscomp$7$$.$iframe_$&&($$jscomp$this$jscomp$7$$.$iframe_$.classList.add("i-amphtml-apester-iframe-ready"),$media$jscomp$1$$.campaignData&&$$jscomp$this$jscomp$7$$.$iframe_$.contentWindow.postMessage({type:"campaigns",
data:$media$jscomp$1$$.campaignData},"*"));$$jscomp$this$jscomp$7$$.togglePlaceholder(!1);var $vsync$$=$media$jscomp$1$$.publisher;if($vsync$$&&$vsync$$.trackingPixel){var $payload$jscomp$2_response$jscomp$2_src$jscomp$5$$=$vsync$$.trackingPixel.affiliateId;$vsync$$=$vsync$$.publisherId;if($payload$jscomp$2_response$jscomp$2_src$jscomp$5$$){var $interactionId$$=new $CustomEventReporterBuilder$$module$src$extension_analytics$$($$jscomp$this$jscomp$7$$.element);$interactionId$$.track("interactionLoaded",
$generatePixelURL$$module$extensions$amp_apester_media$0_1$utils$$($vsync$$,$payload$jscomp$2_response$jscomp$2_src$jscomp$5$$));$interactionId$$.build().trigger("interactionLoaded")}}$$jscomp$this$jscomp$7$$.$ready_$=!0;$payload$jscomp$2_response$jscomp$2_src$jscomp$5$$=0;$media$jscomp$1$$&&$media$jscomp$1$$.data&&$media$jscomp$1$$.data.size&&($payload$jscomp$2_response$jscomp$2_src$jscomp$5$$=$media$jscomp$1$$.data.size.height);$payload$jscomp$2_response$jscomp$2_src$jscomp$5$$!=$$jscomp$this$jscomp$7$$.$height_$&&
($$jscomp$this$jscomp$7$$.$height_$=$payload$jscomp$2_response$jscomp$2_src$jscomp$5$$,$$jscomp$this$jscomp$7$$.$random_$?$$jscomp$this$jscomp$7$$.attemptChangeHeight($payload$jscomp$2_response$jscomp$2_src$jscomp$5$$):$$jscomp$this$jscomp$7$$.changeHeight($payload$jscomp$2_response$jscomp$2_src$jscomp$5$$))})})}).catch(function($$jscomp$this$jscomp$7$$){$dev$$module$src$log$$().error("amp-apester-media","Display",$$jscomp$this$jscomp$7$$)})},function($$jscomp$this$jscomp$7$$){$dev$$module$src$log$$().error("amp-apester-media",
"Display",$$jscomp$this$jscomp$7$$)})};
$JSCompiler_prototypeAlias$$.createPlaceholderCallback=function(){var $placeholder$$=this.element.ownerDocument.createElement("div"),$JSCompiler_img$jscomp$inline_144$$=this.element.ownerDocument.createElement("amp-img");$JSCompiler_img$jscomp$inline_144$$.setAttribute("src",this.$loaderUrl_$);$JSCompiler_img$jscomp$inline_144$$.setAttribute("layout","fixed");$JSCompiler_img$jscomp$inline_144$$.setAttribute("width","100");$JSCompiler_img$jscomp$inline_144$$.setAttribute("height","100");this.element.hasAttribute("aria-label")?
$placeholder$$.setAttribute("aria-label","Loading - "+this.element.getAttribute("aria-label")):$placeholder$$.setAttribute("aria-label","Loading Apester Media");$placeholder$$.setAttribute("placeholder","");$placeholder$$.className="amp-apester-loader";var $JSCompiler_styles$jscomp$inline_147$$={top:"50%",left:"50%",transform:"translate(-50%, -50%)"},$JSCompiler_k$jscomp$inline_148$$;for($JSCompiler_k$jscomp$inline_148$$ in $JSCompiler_styles$jscomp$inline_147$$){var $JSCompiler_element$jscomp$inline_181$$=
$JSCompiler_img$jscomp$inline_144$$,$JSCompiler_value$jscomp$inline_183$$=$JSCompiler_styles$jscomp$inline_147$$[$JSCompiler_k$jscomp$inline_148$$];var $JSCompiler_propertyName$jscomp$inline_185_JSCompiler_style$jscomp$inline_213$$=$JSCompiler_element$jscomp$inline_181$$.style;var $JSCompiler_camelCase$jscomp$inline_214$$=$JSCompiler_k$jscomp$inline_148$$;if(2>$JSCompiler_camelCase$jscomp$inline_214$$.length?0:0==$JSCompiler_camelCase$jscomp$inline_214$$.lastIndexOf("--",0))$JSCompiler_propertyName$jscomp$inline_185_JSCompiler_style$jscomp$inline_213$$=
$JSCompiler_camelCase$jscomp$inline_214$$;else{$propertyNameCache$$module$src$style$$||($propertyNameCache$$module$src$style$$=Object.create(null));var $JSCompiler_propertyName$jscomp$inline_216$$=$propertyNameCache$$module$src$style$$[$JSCompiler_camelCase$jscomp$inline_214$$];if(!$JSCompiler_propertyName$jscomp$inline_216$$){$JSCompiler_propertyName$jscomp$inline_216$$=$JSCompiler_camelCase$jscomp$inline_214$$;if(void 0===$JSCompiler_propertyName$jscomp$inline_185_JSCompiler_style$jscomp$inline_213$$[$JSCompiler_camelCase$jscomp$inline_214$$]){var $JSCompiler_prefixedPropertyName$jscomp$inline_218_JSCompiler_titleCase$jscomp$inline_217$$=
$JSCompiler_camelCase$jscomp$inline_214$$.charAt(0).toUpperCase()+$JSCompiler_camelCase$jscomp$inline_214$$.slice(1);b:{for(var $JSCompiler_i$jscomp$inline_226$$=0;$JSCompiler_i$jscomp$inline_226$$<$vendorPrefixes$$module$src$style$$.length;$JSCompiler_i$jscomp$inline_226$$++){var $JSCompiler_propertyName$jscomp$inline_227$$=$vendorPrefixes$$module$src$style$$[$JSCompiler_i$jscomp$inline_226$$]+$JSCompiler_prefixedPropertyName$jscomp$inline_218_JSCompiler_titleCase$jscomp$inline_217$$;if(void 0!==
$JSCompiler_propertyName$jscomp$inline_185_JSCompiler_style$jscomp$inline_213$$[$JSCompiler_propertyName$jscomp$inline_227$$]){$JSCompiler_prefixedPropertyName$jscomp$inline_218_JSCompiler_titleCase$jscomp$inline_217$$=$JSCompiler_propertyName$jscomp$inline_227$$;break b}}$JSCompiler_prefixedPropertyName$jscomp$inline_218_JSCompiler_titleCase$jscomp$inline_217$$=""}void 0!==$JSCompiler_propertyName$jscomp$inline_185_JSCompiler_style$jscomp$inline_213$$[$JSCompiler_prefixedPropertyName$jscomp$inline_218_JSCompiler_titleCase$jscomp$inline_217$$]&&
($JSCompiler_propertyName$jscomp$inline_216$$=$JSCompiler_prefixedPropertyName$jscomp$inline_218_JSCompiler_titleCase$jscomp$inline_217$$)}$propertyNameCache$$module$src$style$$[$JSCompiler_camelCase$jscomp$inline_214$$]=$JSCompiler_propertyName$jscomp$inline_216$$}$JSCompiler_propertyName$jscomp$inline_185_JSCompiler_style$jscomp$inline_213$$=$JSCompiler_propertyName$jscomp$inline_216$$}$JSCompiler_propertyName$jscomp$inline_185_JSCompiler_style$jscomp$inline_213$$&&($JSCompiler_element$jscomp$inline_181$$.style[$JSCompiler_propertyName$jscomp$inline_185_JSCompiler_style$jscomp$inline_213$$]=
$JSCompiler_value$jscomp$inline_183$$)}$placeholder$$.appendChild($JSCompiler_img$jscomp$inline_144$$);return this.$placeholder_$=$placeholder$$};$JSCompiler_prototypeAlias$$.unlayoutOnPause=function(){return!0};
$JSCompiler_prototypeAlias$$.unlayoutCallback=function(){this.$iframe_$&&(this.$intersectionObserverApi_$.destroy(),this.$intersectionObserverApi_$=null,this.$unlisteners_$.forEach(function($unlisten$jscomp$5$$){return $unlisten$jscomp$5$$()}),$removeElement$$module$src$dom$$(this.$iframe_$),this.$iframe_$=null);this.$placeholder_$&&($removeElement$$module$src$dom$$(this.$placeholder_$),this.$placeholder_$=null);return!1};
function $JSCompiler_StaticMethods_registerToApesterEvents_$$($JSCompiler_StaticMethods_registerToApesterEvents_$self$$){$registerEvent$$module$extensions$amp_apester_media$0_1$utils$$("fullscreen_on",function($data$jscomp$64$$){$JSCompiler_StaticMethods_registerToApesterEvents_$self$$.$mediaId_$===$data$jscomp$64$$.id&&$JSCompiler_StaticMethods_registerToApesterEvents_$self$$.element.classList.add("amp-apester-fullscreen")},$JSCompiler_StaticMethods_registerToApesterEvents_$self$$.win,$JSCompiler_StaticMethods_registerToApesterEvents_$self$$.$iframe_$,
$JSCompiler_StaticMethods_registerToApesterEvents_$self$$.$unlisteners_$);$registerEvent$$module$extensions$amp_apester_media$0_1$utils$$("fullscreen_off",function($data$jscomp$65$$){$JSCompiler_StaticMethods_registerToApesterEvents_$self$$.$mediaId_$===$data$jscomp$65$$.id&&$JSCompiler_StaticMethods_registerToApesterEvents_$self$$.element.classList.remove("amp-apester-fullscreen")},$JSCompiler_StaticMethods_registerToApesterEvents_$self$$.win,$JSCompiler_StaticMethods_registerToApesterEvents_$self$$.$iframe_$,
$JSCompiler_StaticMethods_registerToApesterEvents_$self$$.$unlisteners_$);$registerEvent$$module$extensions$amp_apester_media$0_1$utils$$("apester_resize_unit",function($data$jscomp$66$$){$JSCompiler_StaticMethods_registerToApesterEvents_$self$$.$mediaId_$===$data$jscomp$66$$.id&&$data$jscomp$66$$.height&&$JSCompiler_StaticMethods_registerToApesterEvents_$self$$.attemptChangeHeight($data$jscomp$66$$.height)},$JSCompiler_StaticMethods_registerToApesterEvents_$self$$.win,$JSCompiler_StaticMethods_registerToApesterEvents_$self$$.$iframe_$,
$JSCompiler_StaticMethods_registerToApesterEvents_$self$$.$unlisteners_$)}(function($AMP$jscomp$1$$){$AMP$jscomp$1$$.registerElement("amp-apester-media",$AmpApesterMedia$$module$extensions$amp_apester_media$0_1$amp_apester_media$$,".amp-apester-iframe{-webkit-transition:opacity 0.4s;transition:opacity 0.4s;opacity:0}.i-amphtml-apester-iframe-ready{-webkit-transition:opacity 1s ease-out;transition:opacity 1s ease-out;opacity:1!important}.amp-apester-loader{height:100%;width:100%;background-color:#fff}.amp-apester-container{max-width:700px;margin:0 auto;display:block;position:relative;width:100%}.amp-apester-overflow{position:absolute;margin:auto;top:50%;left:50%;-webkit-transform:translate(-50%,-50%);transform:translate(-50%,-50%)}.amp-apester-overflow button{border:none;background:#fff;cursor:pointer;padding:25px 80px;text-transform:uppercase;letter-spacing:1px;font-weight:700;outline:none;position:relative}.amp-apester-fullscreen{background:rgba(34,36,38,0.97)!important;position:fixed!important;width:100vw!important;height:100vh!important;z-index:2147483646!important;top:0;zoom:1;-webkit-overflow-scrolling:touch!important}\n/*# sourceURL=/extensions/amp-apester-media/0.1/amp-apester-media.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-apester-media-0.1.js.map
