(self.AMP=self.AMP||[]).push({n:"amp-audio",v:"1904281823091",f:(function(AMP,_){
var $JSCompiler_prototypeAlias$$,$$jscomp$objectCreate$$="function"==typeof Object.create?Object.create:function($prototype$$){function $ctor$$(){}$ctor$$.prototype=$prototype$$;return new $ctor$$},$JSCompiler_temp$jscomp$16$$;
if("function"==typeof Object.setPrototypeOf)$JSCompiler_temp$jscomp$16$$=Object.setPrototypeOf;else{var $JSCompiler_inline_result$jscomp$17$$;a:{var $JSCompiler_x$jscomp$inline_28$$={a:!0},$JSCompiler_y$jscomp$inline_29$$={};try{$JSCompiler_y$jscomp$inline_29$$.__proto__=$JSCompiler_x$jscomp$inline_28$$;$JSCompiler_inline_result$jscomp$17$$=$JSCompiler_y$jscomp$inline_29$$.a;break a}catch($JSCompiler_e$jscomp$inline_30$$){}$JSCompiler_inline_result$jscomp$17$$=!1}$JSCompiler_temp$jscomp$16$$=$JSCompiler_inline_result$jscomp$17$$?
function($target$jscomp$83$$,$proto$jscomp$3$$){$target$jscomp$83$$.__proto__=$proto$jscomp$3$$;if($target$jscomp$83$$.__proto__!==$proto$jscomp$3$$)throw new TypeError($target$jscomp$83$$+" is not extensible");return $target$jscomp$83$$}:null}var $$jscomp$setPrototypeOf$$=$JSCompiler_temp$jscomp$16$$;function $tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($component$jscomp$4$$,$fallback$$){$fallback$$=void 0===$fallback$$?"":$fallback$$;try{return decodeURIComponent($component$jscomp$4$$)}catch($e$jscomp$8$$){return $fallback$$}};var $regex$$module$src$url_parse_query_string$$=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;
function $parseQueryString_$$module$src$url_parse_query_string$$($queryString$$){var $params$jscomp$1$$=Object.create(null);if(!$queryString$$)return $params$jscomp$1$$;for(var $match$$;$match$$=$regex$$module$src$url_parse_query_string$$.exec($queryString$$);){var $name$jscomp$70$$=$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($match$$[1],$match$$[1]),$value$jscomp$87$$=$match$$[2]?$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($match$$[2],$match$$[2]):"";
$params$jscomp$1$$[$name$jscomp$70$$]=$value$jscomp$87$$}return $params$jscomp$1$$};var $rtvVersion$$module$src$mode$$="";
function $getMode$$module$src$mode$$(){var $opt_win$$,$win$$=$opt_win$$||self;if($win$$.AMP_MODE)var $JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_32$$=$win$$.AMP_MODE;else{$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_32$$=$win$$;var $JSCompiler_AMP_CONFIG$jscomp$inline_33_JSCompiler_singlePassType$jscomp$inline_40$$=self.AMP_CONFIG||{},$JSCompiler_runningTests$jscomp$inline_37$$=!!$JSCompiler_AMP_CONFIG$jscomp$inline_33_JSCompiler_singlePassType$jscomp$inline_40$$.test||!(!$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_32$$.AMP_TEST&&
!$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_32$$.__karma__),$JSCompiler_isLocalDev$jscomp$inline_38$$=!!$JSCompiler_AMP_CONFIG$jscomp$inline_33_JSCompiler_singlePassType$jscomp$inline_40$$.localDev||$JSCompiler_runningTests$jscomp$inline_37$$,$JSCompiler_hashQuery$jscomp$inline_39$$=$parseQueryString_$$module$src$url_parse_query_string$$($JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_32$$.location.originalHash||$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_32$$.location.hash);
$JSCompiler_AMP_CONFIG$jscomp$inline_33_JSCompiler_singlePassType$jscomp$inline_40$$=$JSCompiler_AMP_CONFIG$jscomp$inline_33_JSCompiler_singlePassType$jscomp$inline_40$$.spt;var $JSCompiler_searchQuery$jscomp$inline_41$$=$parseQueryString_$$module$src$url_parse_query_string$$($JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_32$$.location.search);$rtvVersion$$module$src$mode$$||($rtvVersion$$module$src$mode$$=$JSCompiler_isLocalDev$jscomp$inline_38$$?"1904281823091":$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_32$$.AMP_CONFIG&&
$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_32$$.AMP_CONFIG.v?$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_32$$.AMP_CONFIG.v:"011904281823091");$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_32$$=$win$$.AMP_MODE={localDev:$JSCompiler_isLocalDev$jscomp$inline_38$$,development:!("1"!=$JSCompiler_hashQuery$jscomp$inline_39$$.development&&!$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_32$$.AMP_DEV_MODE),examiner:"2"==$JSCompiler_hashQuery$jscomp$inline_39$$.development,
filter:$JSCompiler_hashQuery$jscomp$inline_39$$.filter,geoOverride:$JSCompiler_hashQuery$jscomp$inline_39$$["amp-geo"],minified:!0,lite:void 0!=$JSCompiler_searchQuery$jscomp$inline_41$$.amp_lite,test:$JSCompiler_runningTests$jscomp$inline_37$$,log:$JSCompiler_hashQuery$jscomp$inline_39$$.log,version:"1904281823091",rtvVersion:$rtvVersion$$module$src$mode$$,singlePassType:$JSCompiler_AMP_CONFIG$jscomp$inline_33_JSCompiler_singlePassType$jscomp$inline_40$$}}return $JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_32$$}
;var $toString_$$module$src$types$$=Object.prototype.toString;self.log=self.log||{user:null,dev:null,userForEmbed:null};var $logs$$module$src$log$$=self.log;function $user$$module$src$log$$(){if(!$logs$$module$src$log$$.user)throw Error("failed to call initLogConstructor");return $logs$$module$src$log$$.user}
function $userAssert$$module$src$log$$($shouldBeTrueish$jscomp$3$$,$opt_message$jscomp$14$$,$opt_1$jscomp$1$$,$opt_2$jscomp$1$$,$opt_3$jscomp$1$$){$user$$module$src$log$$().assert($shouldBeTrueish$jscomp$3$$,$opt_message$jscomp$14$$,$opt_1$jscomp$1$$,$opt_2$jscomp$1$$,$opt_3$jscomp$1$$,void 0,void 0,void 0,void 0,void 0,void 0)};function $getExistingServiceForDocInEmbedScope$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_90_JSCompiler_ampdoc$jscomp$inline_92_JSCompiler_inline_result$jscomp$inline_91_element$jscomp$11$$){var $opt_fallbackToTopWin$$,$win$jscomp$6$$=$JSCompiler_ampdoc$jscomp$inline_90_JSCompiler_ampdoc$jscomp$inline_92_JSCompiler_inline_result$jscomp$inline_91_element$jscomp$11$$.ownerDocument.defaultView,$isEmbed$$=$win$jscomp$6$$!=($win$jscomp$6$$.__AMP_TOP||$win$jscomp$6$$);if($isEmbed$$){if($isServiceRegistered$$module$src$service$$($win$jscomp$6$$,
"url")){var $embedService$$=$getServiceInternal$$module$src$service$$($win$jscomp$6$$,"url");if($embedService$$)return $embedService$$}if(!$opt_fallbackToTopWin$$)return null}$JSCompiler_ampdoc$jscomp$inline_90_JSCompiler_ampdoc$jscomp$inline_92_JSCompiler_inline_result$jscomp$inline_91_element$jscomp$11$$=$getAmpdoc$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_90_JSCompiler_ampdoc$jscomp$inline_92_JSCompiler_inline_result$jscomp$inline_91_element$jscomp$11$$);$JSCompiler_ampdoc$jscomp$inline_90_JSCompiler_ampdoc$jscomp$inline_92_JSCompiler_inline_result$jscomp$inline_91_element$jscomp$11$$=
$getAmpdoc$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_90_JSCompiler_ampdoc$jscomp$inline_92_JSCompiler_inline_result$jscomp$inline_91_element$jscomp$11$$);$JSCompiler_ampdoc$jscomp$inline_90_JSCompiler_ampdoc$jscomp$inline_92_JSCompiler_inline_result$jscomp$inline_91_element$jscomp$11$$=$JSCompiler_ampdoc$jscomp$inline_90_JSCompiler_ampdoc$jscomp$inline_92_JSCompiler_inline_result$jscomp$inline_91_element$jscomp$11$$.isSingleDoc()?$JSCompiler_ampdoc$jscomp$inline_90_JSCompiler_ampdoc$jscomp$inline_92_JSCompiler_inline_result$jscomp$inline_91_element$jscomp$11$$.win:
$JSCompiler_ampdoc$jscomp$inline_90_JSCompiler_ampdoc$jscomp$inline_92_JSCompiler_inline_result$jscomp$inline_91_element$jscomp$11$$;return $isServiceRegistered$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_90_JSCompiler_ampdoc$jscomp$inline_92_JSCompiler_inline_result$jscomp$inline_91_element$jscomp$11$$,"url")?$getServiceInternal$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_90_JSCompiler_ampdoc$jscomp$inline_92_JSCompiler_inline_result$jscomp$inline_91_element$jscomp$11$$,"url"):
null}
function $getAmpdoc$$module$src$service$$($JSCompiler_temp$jscomp$83_nodeOrDoc$jscomp$2$$){if($JSCompiler_temp$jscomp$83_nodeOrDoc$jscomp$2$$.nodeType){var $JSCompiler_win$jscomp$inline_94$$=($JSCompiler_temp$jscomp$83_nodeOrDoc$jscomp$2$$.ownerDocument||$JSCompiler_temp$jscomp$83_nodeOrDoc$jscomp$2$$).defaultView;$JSCompiler_win$jscomp$inline_94$$=$JSCompiler_win$jscomp$inline_94$$.__AMP_TOP||$JSCompiler_win$jscomp$inline_94$$;$JSCompiler_temp$jscomp$83_nodeOrDoc$jscomp$2$$=$getServiceInternal$$module$src$service$$($JSCompiler_win$jscomp$inline_94$$,"ampdoc").getAmpDoc($JSCompiler_temp$jscomp$83_nodeOrDoc$jscomp$2$$)}return $JSCompiler_temp$jscomp$83_nodeOrDoc$jscomp$2$$}
function $getServiceInternal$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$,$id$jscomp$19$$){$isServiceRegistered$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$,$id$jscomp$19$$);var $JSCompiler_services$jscomp$inline_50$$=$holder$jscomp$4_s$jscomp$8$$.services;$JSCompiler_services$jscomp$inline_50$$||($JSCompiler_services$jscomp$inline_50$$=$holder$jscomp$4_s$jscomp$8$$.services={});var $services$$=$JSCompiler_services$jscomp$inline_50$$;$holder$jscomp$4_s$jscomp$8$$=$services$$[$id$jscomp$19$$];
$holder$jscomp$4_s$jscomp$8$$.obj||($holder$jscomp$4_s$jscomp$8$$.obj=new $holder$jscomp$4_s$jscomp$8$$.ctor($holder$jscomp$4_s$jscomp$8$$.context),$holder$jscomp$4_s$jscomp$8$$.ctor=null,$holder$jscomp$4_s$jscomp$8$$.context=null,$holder$jscomp$4_s$jscomp$8$$.resolve&&$holder$jscomp$4_s$jscomp$8$$.resolve($holder$jscomp$4_s$jscomp$8$$.obj));return $holder$jscomp$4_s$jscomp$8$$.obj}
function $isServiceRegistered$$module$src$service$$($holder$jscomp$12_service$jscomp$4$$,$id$jscomp$27$$){$holder$jscomp$12_service$jscomp$4$$=$holder$jscomp$12_service$jscomp$4$$.services&&$holder$jscomp$12_service$jscomp$4$$.services[$id$jscomp$27$$];return!(!$holder$jscomp$12_service$jscomp$4$$||!$holder$jscomp$12_service$jscomp$4$$.ctor&&!$holder$jscomp$12_service$jscomp$4$$.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function $closest$$module$src$dom$$($el$jscomp$2_element$jscomp$17$$,$callback$jscomp$60$$){for(var $opt_stopAt$$;$el$jscomp$2_element$jscomp$17$$&&$el$jscomp$2_element$jscomp$17$$!==$opt_stopAt$$;$el$jscomp$2_element$jscomp$17$$=$el$jscomp$2_element$jscomp$17$$.parentElement)if($callback$jscomp$60$$($el$jscomp$2_element$jscomp$17$$))return $el$jscomp$2_element$jscomp$17$$;return null}
function $closestAncestorElementBySelector$$module$src$dom$$($element$jscomp$18$$){return $element$jscomp$18$$.closest?$element$jscomp$18$$.closest("AMP-STORY"):$closest$$module$src$dom$$($element$jscomp$18$$,function($element$jscomp$18$$){var $el$jscomp$3$$=$element$jscomp$18$$.matches||$element$jscomp$18$$.webkitMatchesSelector||$element$jscomp$18$$.mozMatchesSelector||$element$jscomp$18$$.msMatchesSelector||$element$jscomp$18$$.oMatchesSelector;return $el$jscomp$3$$?$el$jscomp$3$$.call($element$jscomp$18$$,
"AMP-STORY"):!1})};var $EMPTY_METADATA$$module$src$mediasession_helper$$={title:"",artist:"",album:"",artwork:[{src:""}]};
function $setMediaSession$$module$src$mediasession_helper$$($element$jscomp$56$$,$win$jscomp$42$$,$metadata$$,$playHandler$$,$pauseHandler$$){var $navigator$jscomp$1$$=$win$jscomp$42$$.navigator;"mediaSession"in $navigator$jscomp$1$$&&$win$jscomp$42$$.MediaMetadata&&($navigator$jscomp$1$$.mediaSession.metadata=new $win$jscomp$42$$.MediaMetadata($EMPTY_METADATA$$module$src$mediasession_helper$$),$validateMetadata$$module$src$mediasession_helper$$($element$jscomp$56$$,$metadata$$),$navigator$jscomp$1$$.mediaSession.metadata=
new $win$jscomp$42$$.MediaMetadata($metadata$$),$navigator$jscomp$1$$.mediaSession.setActionHandler("play",$playHandler$$),$navigator$jscomp$1$$.mediaSession.setActionHandler("pause",$pauseHandler$$))}
function $parseSchemaImage$$module$src$mediasession_helper$$($doc$jscomp$14$$){var $schema$$=$doc$jscomp$14$$.querySelector('script[type="application/ld+json"]');if($schema$$){try{var $JSCompiler_inline_result$jscomp$24$$=JSON.parse($schema$$.textContent)}catch($JSCompiler_e$jscomp$inline_58$$){$JSCompiler_inline_result$jscomp$24$$=null}var $schemaJson$$=$JSCompiler_inline_result$jscomp$24$$;if($schemaJson$$&&$schemaJson$$.image){if("string"===typeof $schemaJson$$.image)return $schemaJson$$.image;
if($schemaJson$$.image["@list"]&&"string"===typeof $schemaJson$$.image["@list"][0])return $schemaJson$$.image["@list"][0];if("string"===typeof $schemaJson$$.image.url)return $schemaJson$$.image.url;if("string"===typeof $schemaJson$$.image[0])return $schemaJson$$.image[0]}}}
function $validateMetadata$$module$src$mediasession_helper$$($element$jscomp$57$$,$metadata$jscomp$1$$){var $urlService$$=$getExistingServiceForDocInEmbedScope$$module$src$service$$($element$jscomp$57$$);if($metadata$jscomp$1$$&&$metadata$jscomp$1$$.artwork){var $artwork$$=$metadata$jscomp$1$$.artwork;$artwork$$.forEach(function($element$jscomp$57$$){if($element$jscomp$57$$){var $metadata$jscomp$1$$="[object Object]"===$toString_$$module$src$types$$.call($element$jscomp$57$$)?$element$jscomp$57$$.src:
$element$jscomp$57$$;$userAssert$$module$src$log$$($urlService$$.isProtocolValid($metadata$jscomp$1$$))}})}};function $LruCache$$module$src$utils$lru_cache$$(){var $capacity$$=100;this.$capacity_$=$capacity$$;this.$access_$=this.$size_$=0;this.$cache_$=Object.create(null)}$LruCache$$module$src$utils$lru_cache$$.prototype.has=function($key$jscomp$44$$){return!!this.$cache_$[$key$jscomp$44$$]};$LruCache$$module$src$utils$lru_cache$$.prototype.get=function($key$jscomp$45$$){var $cacheable$$=this.$cache_$[$key$jscomp$45$$];if($cacheable$$)return $cacheable$$.access=++this.$access_$,$cacheable$$.payload};
$LruCache$$module$src$utils$lru_cache$$.prototype.put=function($JSCompiler_cache$jscomp$inline_63_JSCompiler_inline_result$jscomp$82_key$jscomp$46$$,$payload$$){this.has($JSCompiler_cache$jscomp$inline_63_JSCompiler_inline_result$jscomp$82_key$jscomp$46$$)||this.$size_$++;this.$cache_$[$JSCompiler_cache$jscomp$inline_63_JSCompiler_inline_result$jscomp$82_key$jscomp$46$$]={payload:$payload$$,access:this.$access_$};if(!(this.$size_$<=this.$capacity_$)){if($logs$$module$src$log$$.dev)$JSCompiler_cache$jscomp$inline_63_JSCompiler_inline_result$jscomp$82_key$jscomp$46$$=
$logs$$module$src$log$$.dev;else throw Error("failed to call initLogConstructor");$JSCompiler_cache$jscomp$inline_63_JSCompiler_inline_result$jscomp$82_key$jscomp$46$$.warn("lru-cache","Trimming LRU cache");$JSCompiler_cache$jscomp$inline_63_JSCompiler_inline_result$jscomp$82_key$jscomp$46$$=this.$cache_$;var $JSCompiler_oldest$jscomp$inline_64$$=this.$access_$+1,$JSCompiler_key$jscomp$inline_66$$;for($JSCompiler_key$jscomp$inline_66$$ in $JSCompiler_cache$jscomp$inline_63_JSCompiler_inline_result$jscomp$82_key$jscomp$46$$){var $JSCompiler_access$jscomp$inline_67$$=
$JSCompiler_cache$jscomp$inline_63_JSCompiler_inline_result$jscomp$82_key$jscomp$46$$[$JSCompiler_key$jscomp$inline_66$$].access;if($JSCompiler_access$jscomp$inline_67$$<$JSCompiler_oldest$jscomp$inline_64$$){$JSCompiler_oldest$jscomp$inline_64$$=$JSCompiler_access$jscomp$inline_67$$;var $JSCompiler_oldestKey$jscomp$inline_65$$=$JSCompiler_key$jscomp$inline_66$$}}void 0!==$JSCompiler_oldestKey$jscomp$inline_65$$&&(delete $JSCompiler_cache$jscomp$inline_63_JSCompiler_inline_result$jscomp$82_key$jscomp$46$$[$JSCompiler_oldestKey$jscomp$inline_65$$],
this.$size_$--)}};(function($opt_initial$jscomp$1$$){return $opt_initial$jscomp$1$$||{}})({c:!0,v:!0,a:!0,ad:!0,action:!0});var $a$$module$src$url$$,$cache$$module$src$url$$;
function $assertHttpsUrl$$module$src$url$$($JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$,$elementContext$$){var $sourceName$$=void 0===$sourceName$$?"source":$sourceName$$;$userAssert$$module$src$log$$(null!=$JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$,"%s %s must be available",$elementContext$$,$sourceName$$);var $theUrlString$$=$JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$;
$JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$=$theUrlString$$;if("string"==typeof $JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$){$a$$module$src$url$$||($a$$module$src$url$$=self.document.createElement("a"),$cache$$module$src$url$$=self.UrlCache||(self.UrlCache=new $LruCache$$module$src$utils$lru_cache$$));var $JSCompiler_index$jscomp$inline_101_JSCompiler_opt_cache$jscomp$inline_106_JSCompiler_temp$jscomp$86$$=
$cache$$module$src$url$$,$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$=$a$$module$src$url$$;if($JSCompiler_index$jscomp$inline_101_JSCompiler_opt_cache$jscomp$inline_106_JSCompiler_temp$jscomp$86$$&&$JSCompiler_index$jscomp$inline_101_JSCompiler_opt_cache$jscomp$inline_106_JSCompiler_temp$jscomp$86$$.has($JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$))$JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$=
$JSCompiler_index$jscomp$inline_101_JSCompiler_opt_cache$jscomp$inline_106_JSCompiler_temp$jscomp$86$$.get($JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$);else{$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$.href=$JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$;$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$.protocol||
($JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$.href=$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$.href);var $JSCompiler_info$jscomp$inline_108$$={href:$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$.href,protocol:$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$.protocol,host:$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$.host,hostname:$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$.hostname,
port:"0"==$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$.port?"":$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$.port,pathname:$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$.pathname,search:$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$.search,hash:$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$.hash,origin:null};"/"!==$JSCompiler_info$jscomp$inline_108$$.pathname[0]&&($JSCompiler_info$jscomp$inline_108$$.pathname=
"/"+$JSCompiler_info$jscomp$inline_108$$.pathname);if("http:"==$JSCompiler_info$jscomp$inline_108$$.protocol&&80==$JSCompiler_info$jscomp$inline_108$$.port||"https:"==$JSCompiler_info$jscomp$inline_108$$.protocol&&443==$JSCompiler_info$jscomp$inline_108$$.port)$JSCompiler_info$jscomp$inline_108$$.port="",$JSCompiler_info$jscomp$inline_108$$.host=$JSCompiler_info$jscomp$inline_108$$.hostname;$JSCompiler_info$jscomp$inline_108$$.origin=$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$.origin&&
"null"!=$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$.origin?$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$.origin:"data:"!=$JSCompiler_info$jscomp$inline_108$$.protocol&&$JSCompiler_info$jscomp$inline_108$$.host?$JSCompiler_info$jscomp$inline_108$$.protocol+"//"+$JSCompiler_info$jscomp$inline_108$$.host:$JSCompiler_info$jscomp$inline_108$$.href;$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$=$getMode$$module$src$mode$$().test&&
Object.freeze?Object.freeze($JSCompiler_info$jscomp$inline_108$$):$JSCompiler_info$jscomp$inline_108$$;$JSCompiler_index$jscomp$inline_101_JSCompiler_opt_cache$jscomp$inline_106_JSCompiler_temp$jscomp$86$$&&$JSCompiler_index$jscomp$inline_101_JSCompiler_opt_cache$jscomp$inline_106_JSCompiler_temp$jscomp$86$$.put($JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$,$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$);
$JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$=$JSCompiler_a$jscomp$inline_107_JSCompiler_frozen$jscomp$inline_109$$}}($JSCompiler_index$jscomp$inline_101_JSCompiler_opt_cache$jscomp$inline_106_JSCompiler_temp$jscomp$86$$="https:"==$JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$.protocol||"localhost"==$JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$.hostname||
"127.0.0.1"==$JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$.hostname)||($JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$=$JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$.hostname,$JSCompiler_index$jscomp$inline_101_JSCompiler_opt_cache$jscomp$inline_106_JSCompiler_temp$jscomp$86$$=
$JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$.length-10,$JSCompiler_index$jscomp$inline_101_JSCompiler_opt_cache$jscomp$inline_106_JSCompiler_temp$jscomp$86$$=0<=$JSCompiler_index$jscomp$inline_101_JSCompiler_opt_cache$jscomp$inline_106_JSCompiler_temp$jscomp$86$$&&$JSCompiler_string$jscomp$inline_100_JSCompiler_url$jscomp$inline_69_JSCompiler_url$jscomp$inline_97_urlString$jscomp$1$$.indexOf(".localhost",$JSCompiler_index$jscomp$inline_101_JSCompiler_opt_cache$jscomp$inline_106_JSCompiler_temp$jscomp$86$$)==
$JSCompiler_index$jscomp$inline_101_JSCompiler_opt_cache$jscomp$inline_106_JSCompiler_temp$jscomp$86$$);$userAssert$$module$src$log$$($JSCompiler_index$jscomp$inline_101_JSCompiler_opt_cache$jscomp$inline_106_JSCompiler_temp$jscomp$86$$||/^(\/\/)/.test($theUrlString$$),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',$elementContext$$,$sourceName$$,$theUrlString$$)};var $optsSupported$$module$src$event_helper_listen$$;
function $internalListenImplementation$$module$src$event_helper_listen$$($element$jscomp$68$$,$listener$jscomp$62$$){var $opt_evtListenerOpts$$=void 0,$localElement$$=$element$jscomp$68$$,$localListener$$=$listener$jscomp$62$$;var $wrapped$$=function($element$jscomp$68$$){try{return $localListener$$($element$jscomp$68$$)}catch($e$jscomp$17$$){throw self.reportError($e$jscomp$17$$),$e$jscomp$17$$;}};var $optsSupported$$=$detectEvtListenerOptsSupport$$module$src$event_helper_listen$$(),$capture$$=!1;
$opt_evtListenerOpts$$&&($capture$$=$opt_evtListenerOpts$$.capture);$localElement$$.addEventListener("playing",$wrapped$$,$optsSupported$$?$opt_evtListenerOpts$$:$capture$$)}
function $detectEvtListenerOptsSupport$$module$src$event_helper_listen$$(){if(void 0!==$optsSupported$$module$src$event_helper_listen$$)return $optsSupported$$module$src$event_helper_listen$$;$optsSupported$$module$src$event_helper_listen$$=!1;try{var $options$jscomp$14$$={get capture(){$optsSupported$$module$src$event_helper_listen$$=!0}};self.addEventListener("test-options",null,$options$jscomp$14$$);self.removeEventListener("test-options",null,$options$jscomp$14$$)}catch($err$jscomp$3$$){}return $optsSupported$$module$src$event_helper_listen$$}
;function $listen$$module$src$event_helper$$($element$jscomp$69$$,$listener$jscomp$63$$){$internalListenImplementation$$module$src$event_helper_listen$$($element$jscomp$69$$,$listener$jscomp$63$$)};function $AmpAudio$$module$extensions$amp_audio$0_1$amp_audio$$($$jscomp$super$this_element$jscomp$72$$){$$jscomp$super$this_element$jscomp$72$$=AMP.BaseElement.call(this,$$jscomp$super$this_element$jscomp$72$$)||this;$$jscomp$super$this_element$jscomp$72$$.$audio_$=null;$$jscomp$super$this_element$jscomp$72$$.$metadata_$=$EMPTY_METADATA$$module$src$mediasession_helper$$;$$jscomp$super$this_element$jscomp$72$$.isPlaying=!1;return $$jscomp$super$this_element$jscomp$72$$}
var $JSCompiler_parentCtor$jscomp$inline_72$$=AMP.BaseElement;$AmpAudio$$module$extensions$amp_audio$0_1$amp_audio$$.prototype=$$jscomp$objectCreate$$($JSCompiler_parentCtor$jscomp$inline_72$$.prototype);$AmpAudio$$module$extensions$amp_audio$0_1$amp_audio$$.prototype.constructor=$AmpAudio$$module$extensions$amp_audio$0_1$amp_audio$$;
if($$jscomp$setPrototypeOf$$)$$jscomp$setPrototypeOf$$($AmpAudio$$module$extensions$amp_audio$0_1$amp_audio$$,$JSCompiler_parentCtor$jscomp$inline_72$$);else for(var $JSCompiler_p$jscomp$inline_73$$ in $JSCompiler_parentCtor$jscomp$inline_72$$)if("prototype"!=$JSCompiler_p$jscomp$inline_73$$)if(Object.defineProperties){var $JSCompiler_descriptor$jscomp$inline_74$$=Object.getOwnPropertyDescriptor($JSCompiler_parentCtor$jscomp$inline_72$$,$JSCompiler_p$jscomp$inline_73$$);$JSCompiler_descriptor$jscomp$inline_74$$&&
Object.defineProperty($AmpAudio$$module$extensions$amp_audio$0_1$amp_audio$$,$JSCompiler_p$jscomp$inline_73$$,$JSCompiler_descriptor$jscomp$inline_74$$)}else $AmpAudio$$module$extensions$amp_audio$0_1$amp_audio$$[$JSCompiler_p$jscomp$inline_73$$]=$JSCompiler_parentCtor$jscomp$inline_72$$[$JSCompiler_p$jscomp$inline_73$$];$AmpAudio$$module$extensions$amp_audio$0_1$amp_audio$$.$superClass_$=$JSCompiler_parentCtor$jscomp$inline_72$$.prototype;$JSCompiler_prototypeAlias$$=$AmpAudio$$module$extensions$amp_audio$0_1$amp_audio$$.prototype;
$JSCompiler_prototypeAlias$$.isLayoutSupported=function($layout$jscomp$3$$){return"fixed"==$layout$jscomp$3$$||"fixed-height"==$layout$jscomp$3$$};$JSCompiler_prototypeAlias$$.buildCallback=function(){"nodisplay"===this.getLayout()&&(this.element.removeAttribute("autoplay"),this.buildAudioElement());this.registerAction("play",this.$play_$.bind(this));this.registerAction("pause",this.$pause_$.bind(this))};
$JSCompiler_prototypeAlias$$.buildAudioElement=function(){var $$jscomp$this$jscomp$1$$=this,$audio$$=this.element.ownerDocument.createElement("audio");if(!$audio$$.play)return this.toggleFallback(!0),Promise.resolve();$audio$$.controls=!0;var $src$jscomp$5$$=this.element.getAttribute("src");$src$jscomp$5$$&&$assertHttpsUrl$$module$src$url$$($src$jscomp$5$$,this.element);this.propagateAttributes("src preload autoplay muted loop aria-label aria-describedby aria-labelledby controlsList".split(" "),$audio$$);
this.applyFillContent($audio$$);this.getRealChildNodes().forEach(function($$jscomp$this$jscomp$1$$){$$jscomp$this$jscomp$1$$.getAttribute&&$$jscomp$this$jscomp$1$$.getAttribute("src")&&$assertHttpsUrl$$module$src$url$$($$jscomp$this$jscomp$1$$.getAttribute("src"),$$jscomp$this$jscomp$1$$);$audio$$.appendChild($$jscomp$this$jscomp$1$$)});this.element.appendChild($audio$$);this.$audio_$=$audio$$;$listen$$module$src$event_helper$$(this.$audio_$,function(){return $JSCompiler_StaticMethods_audioPlaying_$$($$jscomp$this$jscomp$1$$)})};
$JSCompiler_prototypeAlias$$.layoutCallback=function(){"nodisplay"!==this.getLayout()&&this.buildAudioElement();var $JSCompiler_linkTag$jscomp$inline_80_document$jscomp$2$$=this.getAmpDoc().win.document,$artist$$=this.element.getAttribute("artist")||"",$title$jscomp$10$$=this.element.getAttribute("title")||this.element.getAttribute("aria-label")||$JSCompiler_linkTag$jscomp$inline_80_document$jscomp$2$$.title||"",$album$$=this.element.getAttribute("album")||"",$JSCompiler_metaTag$jscomp$inline_77_JSCompiler_temp$jscomp$25_JSCompiler_temp$jscomp$26$$;
($JSCompiler_metaTag$jscomp$inline_77_JSCompiler_temp$jscomp$25_JSCompiler_temp$jscomp$26$$=this.element.getAttribute("artwork")||$parseSchemaImage$$module$src$mediasession_helper$$($JSCompiler_linkTag$jscomp$inline_80_document$jscomp$2$$))||($JSCompiler_metaTag$jscomp$inline_77_JSCompiler_temp$jscomp$25_JSCompiler_temp$jscomp$26$$=($JSCompiler_metaTag$jscomp$inline_77_JSCompiler_temp$jscomp$25_JSCompiler_temp$jscomp$26$$=$JSCompiler_linkTag$jscomp$inline_80_document$jscomp$2$$.querySelector('meta[property="og:image"]'))?
$JSCompiler_metaTag$jscomp$inline_77_JSCompiler_temp$jscomp$25_JSCompiler_temp$jscomp$26$$.getAttribute("content"):void 0);$JSCompiler_metaTag$jscomp$inline_77_JSCompiler_temp$jscomp$25_JSCompiler_temp$jscomp$26$$||($JSCompiler_metaTag$jscomp$inline_77_JSCompiler_temp$jscomp$25_JSCompiler_temp$jscomp$26$$=($JSCompiler_linkTag$jscomp$inline_80_document$jscomp$2$$=$JSCompiler_linkTag$jscomp$inline_80_document$jscomp$2$$.querySelector('link[rel="shortcut icon"]')||$JSCompiler_linkTag$jscomp$inline_80_document$jscomp$2$$.querySelector('link[rel="icon"]'))?
$JSCompiler_linkTag$jscomp$inline_80_document$jscomp$2$$.getAttribute("href"):void 0);this.$metadata_$={title:$title$jscomp$10$$,artist:$artist$$,album:$album$$,artwork:[{src:$JSCompiler_metaTag$jscomp$inline_77_JSCompiler_temp$jscomp$25_JSCompiler_temp$jscomp$26$$||""}]};return this.loadPromise(this.$audio_$)};$JSCompiler_prototypeAlias$$.renderOutsideViewport=function(){return!0};
$JSCompiler_prototypeAlias$$.pauseCallback=function(){this.$audio_$&&(this.$audio_$.pause(),$JSCompiler_StaticMethods_setPlayingStateForTesting_$$(this,!1))};
function $JSCompiler_StaticMethods_isInvocationValid_$$($JSCompiler_StaticMethods_isInvocationValid_$self$$){return $JSCompiler_StaticMethods_isInvocationValid_$self$$.$audio_$?$closestAncestorElementBySelector$$module$src$dom$$($JSCompiler_StaticMethods_isInvocationValid_$self$$.element)?($user$$module$src$log$$().warn("amp-audio","<amp-story> elements do not support actions on <amp-audio> elements"),!1):!0:!1}
$JSCompiler_prototypeAlias$$.$pause_$=function(){$JSCompiler_StaticMethods_isInvocationValid_$$(this)&&(this.$audio_$.pause(),$JSCompiler_StaticMethods_setPlayingStateForTesting_$$(this,!1))};$JSCompiler_prototypeAlias$$.$play_$=function(){$JSCompiler_StaticMethods_isInvocationValid_$$(this)&&(this.$audio_$.play(),$JSCompiler_StaticMethods_setPlayingStateForTesting_$$(this,!0))};
function $JSCompiler_StaticMethods_setPlayingStateForTesting_$$($JSCompiler_StaticMethods_setPlayingStateForTesting_$self$$,$isPlaying$$){$getMode$$module$src$mode$$().test&&($JSCompiler_StaticMethods_setPlayingStateForTesting_$self$$.isPlaying=$isPlaying$$)}
function $JSCompiler_StaticMethods_audioPlaying_$$($JSCompiler_StaticMethods_audioPlaying_$self$$){$setMediaSession$$module$src$mediasession_helper$$($JSCompiler_StaticMethods_audioPlaying_$self$$.element,$JSCompiler_StaticMethods_audioPlaying_$self$$.win,$JSCompiler_StaticMethods_audioPlaying_$self$$.$metadata_$,function(){$JSCompiler_StaticMethods_audioPlaying_$self$$.$audio_$.play();$JSCompiler_StaticMethods_setPlayingStateForTesting_$$($JSCompiler_StaticMethods_audioPlaying_$self$$,!0)},function(){$JSCompiler_StaticMethods_audioPlaying_$self$$.$audio_$.pause();
$JSCompiler_StaticMethods_setPlayingStateForTesting_$$($JSCompiler_StaticMethods_audioPlaying_$self$$,!1)})}(function($AMP$jscomp$1$$){$AMP$jscomp$1$$.registerElement("amp-audio",$AmpAudio$$module$extensions$amp_audio$0_1$amp_audio$$)})(self.AMP);
})});

//# sourceMappingURL=amp-audio-0.1.js.map
