(self.AMP=self.AMP||[]).push({n:"amp-o2-player",v:"1904281823091",f:(function(AMP,_){
var $$jscomp$objectCreate$$="function"==typeof Object.create?Object.create:function($prototype$$){function $ctor$$(){}$ctor$$.prototype=$prototype$$;return new $ctor$$},$JSCompiler_temp$jscomp$9$$;
if("function"==typeof Object.setPrototypeOf)$JSCompiler_temp$jscomp$9$$=Object.setPrototypeOf;else{var $JSCompiler_inline_result$jscomp$10$$;a:{var $JSCompiler_x$jscomp$inline_12$$={a:!0},$JSCompiler_y$jscomp$inline_13$$={};try{$JSCompiler_y$jscomp$inline_13$$.__proto__=$JSCompiler_x$jscomp$inline_12$$;$JSCompiler_inline_result$jscomp$10$$=$JSCompiler_y$jscomp$inline_13$$.a;break a}catch($JSCompiler_e$jscomp$inline_14$$){}$JSCompiler_inline_result$jscomp$10$$=!1}$JSCompiler_temp$jscomp$9$$=$JSCompiler_inline_result$jscomp$10$$?
function($target$jscomp$83$$,$proto$jscomp$3$$){$target$jscomp$83$$.__proto__=$proto$jscomp$3$$;if($target$jscomp$83$$.__proto__!==$proto$jscomp$3$$)throw new TypeError($target$jscomp$83$$+" is not extensible");return $target$jscomp$83$$}:null}var $$jscomp$setPrototypeOf$$=$JSCompiler_temp$jscomp$9$$;function $dict$$module$src$utils$object$$($opt_initial$jscomp$1$$){return $opt_initial$jscomp$1$$||{}};self.log=self.log||{user:null,dev:null,userForEmbed:null};var $logs$$module$src$log$$=self.log;function $userAssert$$module$src$log$$($shouldBeTrueish$jscomp$3$$,$opt_message$jscomp$14$$,$opt_1$jscomp$1$$){if(!$logs$$module$src$log$$.user)throw Error("failed to call initLogConstructor");return $logs$$module$src$log$$.user.assert($shouldBeTrueish$jscomp$3$$,$opt_message$jscomp$14$$,$opt_1$jscomp$1$$,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function $AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$($$jscomp$super$this_element$jscomp$21$$){$$jscomp$super$this_element$jscomp$21$$=AMP.BaseElement.call(this,$$jscomp$super$this_element$jscomp$21$$)||this;$$jscomp$super$this_element$jscomp$21$$.$iframe_$=null;$$jscomp$super$this_element$jscomp$21$$.$pid_$="";$$jscomp$super$this_element$jscomp$21$$.$bcid_$="";$$jscomp$super$this_element$jscomp$21$$.$domain_$="";$$jscomp$super$this_element$jscomp$21$$.$src_$="";return $$jscomp$super$this_element$jscomp$21$$}
var $JSCompiler_parentCtor$jscomp$inline_19$$=AMP.BaseElement;$AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$.prototype=$$jscomp$objectCreate$$($JSCompiler_parentCtor$jscomp$inline_19$$.prototype);$AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$.prototype.constructor=$AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$;
if($$jscomp$setPrototypeOf$$)$$jscomp$setPrototypeOf$$($AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$,$JSCompiler_parentCtor$jscomp$inline_19$$);else for(var $JSCompiler_p$jscomp$inline_20$$ in $JSCompiler_parentCtor$jscomp$inline_19$$)if("prototype"!=$JSCompiler_p$jscomp$inline_20$$)if(Object.defineProperties){var $JSCompiler_descriptor$jscomp$inline_21$$=Object.getOwnPropertyDescriptor($JSCompiler_parentCtor$jscomp$inline_19$$,$JSCompiler_p$jscomp$inline_20$$);$JSCompiler_descriptor$jscomp$inline_21$$&&
Object.defineProperty($AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$,$JSCompiler_p$jscomp$inline_20$$,$JSCompiler_descriptor$jscomp$inline_21$$)}else $AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$[$JSCompiler_p$jscomp$inline_20$$]=$JSCompiler_parentCtor$jscomp$inline_19$$[$JSCompiler_p$jscomp$inline_20$$];$AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$.$superClass_$=$JSCompiler_parentCtor$jscomp$inline_19$$.prototype;
$AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$.prototype.preconnectCallback=function($onLayout$$){this.preconnect.url(this.$domain_$,$onLayout$$)};$AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$.prototype.isLayoutSupported=function($layout$jscomp$3$$){return"fixed"==$layout$jscomp$3$$||"fixed-height"==$layout$jscomp$3$$||"responsive"==$layout$jscomp$3$$||"fill"==$layout$jscomp$3$$||"flex-item"==$layout$jscomp$3$$||"fluid"==$layout$jscomp$3$$||"intrinsic"==$layout$jscomp$3$$};
$AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$.prototype.buildCallback=function(){this.$pid_$=$userAssert$$module$src$log$$(this.element.getAttribute("data-pid"),"data-pid attribute is required for <amp-o2-player> %s",this.element);this.$bcid_$=$userAssert$$module$src$log$$(this.element.getAttribute("data-bcid"),"data-bcid attribute is required for <amp-o2-player> %s",this.element);var $bid$$=this.element.getAttribute("data-bid"),$vid$$=this.element.getAttribute("data-vid"),$macros$$=
this.element.getAttribute("data-macros"),$env$$=this.element.getAttribute("data-env");this.$domain_$="https://delivery."+("stage"!=$env$$?"":"dev.")+"vidible.tv";var $src$jscomp$4$$=this.$domain_$+"/htmlembed/",$queryParams$$=[];$src$jscomp$4$$+="pid="+encodeURIComponent(this.$pid_$)+"/"+encodeURIComponent(this.$bcid_$)+".html";$bid$$&&$queryParams$$.push("bid="+encodeURIComponent($bid$$));$vid$$&&$queryParams$$.push("vid="+encodeURIComponent($vid$$));$macros$$&&$queryParams$$.push($macros$$);0<$queryParams$$.length&&
($src$jscomp$4$$+="?"+$queryParams$$.join("&"));this.$src_$=$src$jscomp$4$$};
$AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$.prototype.layoutCallback=function(){$userAssert$$module$src$log$$(this.$pid_$,"data-pid attribute is required for <amp-o2-player> %s",this.element);$userAssert$$module$src$log$$(this.$bcid_$,"data-bcid attribute is required for <amp-o2-player> %s",this.element);var $iframe$$=this.element.ownerDocument.createElement("iframe");$iframe$$.setAttribute("frameborder","0");$iframe$$.setAttribute("allowfullscreen","true");$iframe$$.src=this.$src_$;
this.$iframe_$=$iframe$$;this.applyFillContent($iframe$$);this.element.appendChild($iframe$$);return this.loadPromise($iframe$$)};$AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$.prototype.pauseCallback=function(){this.$iframe_$&&this.$iframe_$.contentWindow&&this.$iframe_$.contentWindow.postMessage(JSON.stringify($dict$$module$src$utils$object$$({method:"pause",value:this.$domain_$})),"*")};(function($AMP$jscomp$1$$){$AMP$jscomp$1$$.registerElement("amp-o2-player",$AmpO2Player$$module$extensions$amp_o2_player$0_1$amp_o2_player$$)})(self.AMP);
})});

//# sourceMappingURL=amp-o2-player-0.1.js.map
