(self.AMP=self.AMP||[]).push({n:"amp-fx-flying-carpet",v:"1904281823091",f:(function(AMP,_){
var $JSCompiler_prototypeAlias$$,$$jscomp$objectCreate$$="function"==typeof Object.create?Object.create:function($prototype$$){function $ctor$$(){}$ctor$$.prototype=$prototype$$;return new $ctor$$},$JSCompiler_temp$jscomp$9$$;
if("function"==typeof Object.setPrototypeOf)$JSCompiler_temp$jscomp$9$$=Object.setPrototypeOf;else{var $JSCompiler_inline_result$jscomp$10$$;a:{var $JSCompiler_x$jscomp$inline_12$$={a:!0},$JSCompiler_y$jscomp$inline_13$$={};try{$JSCompiler_y$jscomp$inline_13$$.__proto__=$JSCompiler_x$jscomp$inline_12$$;$JSCompiler_inline_result$jscomp$10$$=$JSCompiler_y$jscomp$inline_13$$.a;break a}catch($JSCompiler_e$jscomp$inline_14$$){}$JSCompiler_inline_result$jscomp$10$$=!1}$JSCompiler_temp$jscomp$9$$=$JSCompiler_inline_result$jscomp$10$$?
function($target$jscomp$83$$,$proto$jscomp$3$$){$target$jscomp$83$$.__proto__=$proto$jscomp$3$$;if($target$jscomp$83$$.__proto__!==$proto$jscomp$3$$)throw new TypeError($target$jscomp$83$$+" is not extensible");return $target$jscomp$83$$}:null}var $$jscomp$setPrototypeOf$$=$JSCompiler_temp$jscomp$9$$;self.log=self.log||{user:null,dev:null,userForEmbed:null};var $logs$$module$src$log$$=self.log;
function $userAssert$$module$src$log$$($shouldBeTrueish$jscomp$3$$,$opt_message$jscomp$14$$,$opt_1$jscomp$1$$,$opt_2$jscomp$1$$,$opt_3$jscomp$1$$){if(!$logs$$module$src$log$$.user)throw Error("failed to call initLogConstructor");$logs$$module$src$log$$.user.assert($shouldBeTrueish$jscomp$3$$,$opt_message$jscomp$14$$,$opt_1$jscomp$1$$,$opt_2$jscomp$1$$,$opt_3$jscomp$1$$,void 0,void 0,void 0,void 0,void 0,void 0)};var $propertyNameCache$$module$src$style$$,$vendorPrefixes$$module$src$style$$="Webkit webkit Moz moz ms O o".split(" ");var $optsSupported$$module$src$event_helper_listen$$;
function $internalListenImplementation$$module$src$event_helper_listen$$($element$jscomp$21$$,$listener$jscomp$62$$){var $opt_evtListenerOpts$$=void 0,$localElement$$=$element$jscomp$21$$,$localListener$$=$listener$jscomp$62$$;var $wrapped$$=function($element$jscomp$21$$){try{return $localListener$$($element$jscomp$21$$)}catch($e$jscomp$11$$){throw self.reportError($e$jscomp$11$$),$e$jscomp$11$$;}};var $optsSupported$$=$detectEvtListenerOptsSupport$$module$src$event_helper_listen$$(),$capture$$=!1;
$opt_evtListenerOpts$$&&($capture$$=$opt_evtListenerOpts$$.capture);$localElement$$.addEventListener("amp:built",$wrapped$$,$optsSupported$$?$opt_evtListenerOpts$$:$capture$$)}
function $detectEvtListenerOptsSupport$$module$src$event_helper_listen$$(){if(void 0!==$optsSupported$$module$src$event_helper_listen$$)return $optsSupported$$module$src$event_helper_listen$$;$optsSupported$$module$src$event_helper_listen$$=!1;try{var $options$jscomp$14$$={get capture(){$optsSupported$$module$src$event_helper_listen$$=!0}};self.addEventListener("test-options",null,$options$jscomp$14$$);self.removeEventListener("test-options",null,$options$jscomp$14$$)}catch($err$jscomp$3$$){}return $optsSupported$$module$src$event_helper_listen$$}
;function $listen$$module$src$event_helper$$($element$jscomp$22$$,$listener$jscomp$63$$){$internalListenImplementation$$module$src$event_helper_listen$$($element$jscomp$22$$,$listener$jscomp$63$$)};function $AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$$($$jscomp$super$this_element$jscomp$25$$){$$jscomp$super$this_element$jscomp$25$$=AMP.BaseElement.call(this,$$jscomp$super$this_element$jscomp$25$$)||this;$$jscomp$super$this_element$jscomp$25$$.$children_$=[];$$jscomp$super$this_element$jscomp$25$$.$totalChildren_$=0;$$jscomp$super$this_element$jscomp$25$$.$container_$=null;$$jscomp$super$this_element$jscomp$25$$.$firstLayoutCompleted_$=!1;return $$jscomp$super$this_element$jscomp$25$$}
var $JSCompiler_parentCtor$jscomp$inline_19$$=AMP.BaseElement;$AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$$.prototype=$$jscomp$objectCreate$$($JSCompiler_parentCtor$jscomp$inline_19$$.prototype);$AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$$.prototype.constructor=$AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$$;
if($$jscomp$setPrototypeOf$$)$$jscomp$setPrototypeOf$$($AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$$,$JSCompiler_parentCtor$jscomp$inline_19$$);else for(var $JSCompiler_p$jscomp$inline_20$$ in $JSCompiler_parentCtor$jscomp$inline_19$$)if("prototype"!=$JSCompiler_p$jscomp$inline_20$$)if(Object.defineProperties){var $JSCompiler_descriptor$jscomp$inline_21$$=Object.getOwnPropertyDescriptor($JSCompiler_parentCtor$jscomp$inline_19$$,$JSCompiler_p$jscomp$inline_20$$);
$JSCompiler_descriptor$jscomp$inline_21$$&&Object.defineProperty($AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$$,$JSCompiler_p$jscomp$inline_20$$,$JSCompiler_descriptor$jscomp$inline_21$$)}else $AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$$[$JSCompiler_p$jscomp$inline_20$$]=$JSCompiler_parentCtor$jscomp$inline_19$$[$JSCompiler_p$jscomp$inline_20$$];
$AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$$.$superClass_$=$JSCompiler_parentCtor$jscomp$inline_19$$.prototype;$JSCompiler_prototypeAlias$$=$AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$$.prototype;$JSCompiler_prototypeAlias$$.isLayoutSupported=function($layout$jscomp$3$$){return"fixed-height"==$layout$jscomp$3$$};
$JSCompiler_prototypeAlias$$.buildCallback=function(){var $$jscomp$this$$=this,$doc$jscomp$3$$=this.element.ownerDocument,$container$jscomp$4$$=$doc$jscomp$3$$.createElement("div");this.$children_$=this.getRealChildren();this.$container_$=$container$jscomp$4$$;var $childNodes$$=this.getRealChildNodes();this.$totalChildren_$=$JSCompiler_StaticMethods_visibileChildren_$$($childNodes$$).length;this.$children_$.forEach(function($doc$jscomp$3$$){return $$jscomp$this$$.setAsOwner($doc$jscomp$3$$)});var $clip$$=
$doc$jscomp$3$$.createElement("div");$clip$$.setAttribute("class","i-amphtml-fx-flying-carpet-clip");$container$jscomp$4$$.setAttribute("class","i-amphtml-fx-flying-carpet-container");$childNodes$$.forEach(function($$jscomp$this$$){return $container$jscomp$4$$.appendChild($$jscomp$this$$)});$clip$$.appendChild($container$jscomp$4$$);this.element.appendChild($clip$$);this.getViewport().addToFixedLayer($container$jscomp$4$$,!1)};
$JSCompiler_prototypeAlias$$.onMeasureChanged=function(){var $$jscomp$this$jscomp$1$$=this,$width$jscomp$28$$=this.getLayoutWidth();this.mutateElement(function(){var $JSCompiler_element$jscomp$inline_23$$=$$jscomp$this$jscomp$1$$.$container_$;var $JSCompiler_inline_result$jscomp$39_JSCompiler_style$jscomp$inline_43$$=$JSCompiler_element$jscomp$inline_23$$.style;$propertyNameCache$$module$src$style$$||($propertyNameCache$$module$src$style$$=Object.create(null));var $JSCompiler_propertyName$jscomp$inline_46$$=
$propertyNameCache$$module$src$style$$.width;if(!$JSCompiler_propertyName$jscomp$inline_46$$){$JSCompiler_propertyName$jscomp$inline_46$$="width";if(void 0===$JSCompiler_inline_result$jscomp$39_JSCompiler_style$jscomp$inline_43$$.width){var $JSCompiler_i$jscomp$inline_66_JSCompiler_inline_result$jscomp$56_JSCompiler_prefixedPropertyName$jscomp$inline_48$$;b:{for($JSCompiler_i$jscomp$inline_66_JSCompiler_inline_result$jscomp$56_JSCompiler_prefixedPropertyName$jscomp$inline_48$$=0;$JSCompiler_i$jscomp$inline_66_JSCompiler_inline_result$jscomp$56_JSCompiler_prefixedPropertyName$jscomp$inline_48$$<
$vendorPrefixes$$module$src$style$$.length;$JSCompiler_i$jscomp$inline_66_JSCompiler_inline_result$jscomp$56_JSCompiler_prefixedPropertyName$jscomp$inline_48$$++){var $JSCompiler_propertyName$jscomp$inline_67$$=$vendorPrefixes$$module$src$style$$[$JSCompiler_i$jscomp$inline_66_JSCompiler_inline_result$jscomp$56_JSCompiler_prefixedPropertyName$jscomp$inline_48$$]+"Width";if(void 0!==$JSCompiler_inline_result$jscomp$39_JSCompiler_style$jscomp$inline_43$$[$JSCompiler_propertyName$jscomp$inline_67$$]){$JSCompiler_i$jscomp$inline_66_JSCompiler_inline_result$jscomp$56_JSCompiler_prefixedPropertyName$jscomp$inline_48$$=
$JSCompiler_propertyName$jscomp$inline_67$$;break b}}$JSCompiler_i$jscomp$inline_66_JSCompiler_inline_result$jscomp$56_JSCompiler_prefixedPropertyName$jscomp$inline_48$$=""}void 0!==$JSCompiler_inline_result$jscomp$39_JSCompiler_style$jscomp$inline_43$$[$JSCompiler_i$jscomp$inline_66_JSCompiler_inline_result$jscomp$56_JSCompiler_prefixedPropertyName$jscomp$inline_48$$]&&($JSCompiler_propertyName$jscomp$inline_46$$=$JSCompiler_i$jscomp$inline_66_JSCompiler_inline_result$jscomp$56_JSCompiler_prefixedPropertyName$jscomp$inline_48$$)}$propertyNameCache$$module$src$style$$.width=
$JSCompiler_propertyName$jscomp$inline_46$$}$JSCompiler_inline_result$jscomp$39_JSCompiler_style$jscomp$inline_43$$=$JSCompiler_propertyName$jscomp$inline_46$$;$JSCompiler_inline_result$jscomp$39_JSCompiler_style$jscomp$inline_43$$&&($JSCompiler_element$jscomp$inline_23$$.style[$JSCompiler_inline_result$jscomp$39_JSCompiler_style$jscomp$inline_43$$]=$width$jscomp$28$$+"px")});this.$firstLayoutCompleted_$&&(this.scheduleLayout(this.$children_$),$listen$$module$src$event_helper$$(this.element,this.$layoutBuiltChild_$.bind(this)))};
$JSCompiler_prototypeAlias$$.viewportCallback=function($inViewport$$){this.updateInViewport(this.$children_$,$inViewport$$)};
$JSCompiler_prototypeAlias$$.layoutCallback=function(){try{var $JSCompiler_layoutBox$jscomp$inline_31_JSCompiler_listener$jscomp$inline_51$$=this.element.getLayoutBox(),$JSCompiler_minTop$jscomp$inline_35_JSCompiler_viewport$jscomp$inline_32$$=this.getViewport(),$JSCompiler_maxTop$jscomp$inline_36_JSCompiler_viewportHeight$jscomp$inline_33$$=$JSCompiler_minTop$jscomp$inline_35_JSCompiler_viewport$jscomp$inline_32$$.getHeight(),$JSCompiler_docHeight$jscomp$inline_34$$=$JSCompiler_minTop$jscomp$inline_35_JSCompiler_viewport$jscomp$inline_32$$.getScrollHeight();
$JSCompiler_minTop$jscomp$inline_35_JSCompiler_viewport$jscomp$inline_32$$=.75*$JSCompiler_maxTop$jscomp$inline_36_JSCompiler_viewportHeight$jscomp$inline_33$$;$JSCompiler_maxTop$jscomp$inline_36_JSCompiler_viewportHeight$jscomp$inline_33$$=$JSCompiler_docHeight$jscomp$inline_34$$-.95*$JSCompiler_maxTop$jscomp$inline_36_JSCompiler_viewportHeight$jscomp$inline_33$$;$userAssert$$module$src$log$$($JSCompiler_layoutBox$jscomp$inline_31_JSCompiler_listener$jscomp$inline_51$$.top>=$JSCompiler_minTop$jscomp$inline_35_JSCompiler_viewport$jscomp$inline_32$$,
"<amp-fx-flying-carpet> elements must be positioned after the 75% of first viewport: %s Current position: %s. Min: %s",this.element,$JSCompiler_layoutBox$jscomp$inline_31_JSCompiler_listener$jscomp$inline_51$$.top,$JSCompiler_minTop$jscomp$inline_35_JSCompiler_viewport$jscomp$inline_32$$);$userAssert$$module$src$log$$($JSCompiler_layoutBox$jscomp$inline_31_JSCompiler_listener$jscomp$inline_51$$.top<=$JSCompiler_maxTop$jscomp$inline_36_JSCompiler_viewportHeight$jscomp$inline_33$$,"<amp-fx-flying-carpet> elements must be positioned before the last viewport: %s Current position: %s. Max: %s",
this.element,$JSCompiler_layoutBox$jscomp$inline_31_JSCompiler_listener$jscomp$inline_51$$.top,$JSCompiler_maxTop$jscomp$inline_36_JSCompiler_viewportHeight$jscomp$inline_33$$)}catch($e$jscomp$13$$){throw this.collapse(),$e$jscomp$13$$;}this.scheduleLayout(this.$children_$);$JSCompiler_layoutBox$jscomp$inline_31_JSCompiler_listener$jscomp$inline_51$$=this.$layoutBuiltChild_$.bind(this);$internalListenImplementation$$module$src$event_helper_listen$$(this.element,$JSCompiler_layoutBox$jscomp$inline_31_JSCompiler_listener$jscomp$inline_51$$);
this.$firstLayoutCompleted_$=!0;return Promise.resolve()};$JSCompiler_prototypeAlias$$.$layoutBuiltChild_$=function($child$jscomp$2_event$jscomp$9$$){$child$jscomp$2_event$jscomp$9$$=$child$jscomp$2_event$jscomp$9$$.target;$child$jscomp$2_event$jscomp$9$$.getOwner()===this.element&&this.scheduleLayout($child$jscomp$2_event$jscomp$9$$)};
$JSCompiler_prototypeAlias$$.collapsedCallback=function($child$jscomp$3_index$jscomp$69$$){$child$jscomp$3_index$jscomp$69$$=this.$children_$.indexOf($child$jscomp$3_index$jscomp$69$$);if(-1<$child$jscomp$3_index$jscomp$69$$&&(this.$children_$.splice($child$jscomp$3_index$jscomp$69$$,1),this.$totalChildren_$--,0==this.$totalChildren_$))return this.attemptCollapse().catch(function(){})};$JSCompiler_prototypeAlias$$.getChildren=function(){return this.$children_$};
function $JSCompiler_StaticMethods_visibileChildren_$$($nodes$jscomp$15$$){return $nodes$jscomp$15$$.filter(function($nodes$jscomp$15$$){return 1===$nodes$jscomp$15$$.nodeType?!0:3===$nodes$jscomp$15$$.nodeType?/\S/.test($nodes$jscomp$15$$.textContent):!1})}(function($AMP$jscomp$1$$){$AMP$jscomp$1$$.registerElement("amp-fx-flying-carpet",$AmpFlyingCarpet$$module$extensions$amp_fx_flying_carpet$0_1$amp_fx_flying_carpet$$,"amp-fx-flying-carpet{position:relative!important;box-sizing:border-box!important}amp-fx-flying-carpet>.i-amphtml-fx-flying-carpet-clip{position:absolute!important;top:0!important;left:0!important;width:100%!important;height:100%!important;border:0!important;margin:0!important;padding:0!important;clip:rect(0,auto,auto,0)!important;-webkit-clip-path:polygon(0px 0px,100% 0px,100% 100%,0px 100%)!important;clip-path:polygon(0px 0px,100% 0px,100% 100%,0px 100%)!important}amp-fx-flying-carpet>.i-amphtml-fx-flying-carpet-clip>.i-amphtml-fx-flying-carpet-container{position:fixed!important;top:0!important;width:100%;height:100%;-webkit-transform:translateZ(0)!important;display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-ms-flex-direction:column;flex-direction:column;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:center;-ms-flex-pack:center;justify-content:center}.i-amphtml-fx-flying-carpet-container>.i-amphtml-layout-fixed-height,.i-amphtml-fx-flying-carpet-container>.i-amphtml-layout-responsive{-ms-flex-item-align:stretch;align-self:stretch}\n/*# sourceURL=/extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-fx-flying-carpet-0.1.js.map
