(self.AMP=self.AMP||[]).push({n:"amp-font",v:"1904281823091",f:(function(AMP,_){
var $$jscomp$objectCreate$$="function"==typeof Object.create?Object.create:function($prototype$$){function $ctor$$(){}$ctor$$.prototype=$prototype$$;return new $ctor$$},$JSCompiler_temp$jscomp$8$$;
if("function"==typeof Object.setPrototypeOf)$JSCompiler_temp$jscomp$8$$=Object.setPrototypeOf;else{var $JSCompiler_inline_result$jscomp$9$$;a:{var $JSCompiler_x$jscomp$inline_15$$={a:!0},$JSCompiler_y$jscomp$inline_16$$={};try{$JSCompiler_y$jscomp$inline_16$$.__proto__=$JSCompiler_x$jscomp$inline_15$$;$JSCompiler_inline_result$jscomp$9$$=$JSCompiler_y$jscomp$inline_16$$.a;break a}catch($JSCompiler_e$jscomp$inline_17$$){}$JSCompiler_inline_result$jscomp$9$$=!1}$JSCompiler_temp$jscomp$8$$=$JSCompiler_inline_result$jscomp$9$$?
function($target$jscomp$83$$,$proto$jscomp$3$$){$target$jscomp$83$$.__proto__=$proto$jscomp$3$$;if($target$jscomp$83$$.__proto__!==$proto$jscomp$3$$)throw new TypeError($target$jscomp$83$$+" is not extensible");return $target$jscomp$83$$}:null}var $$jscomp$setPrototypeOf$$=$JSCompiler_temp$jscomp$8$$;self.log=self.log||{user:null,dev:null,userForEmbed:null};var $logs$$module$src$log$$=self.log;function $user$$module$src$log$$(){if(!$logs$$module$src$log$$.user)throw Error("failed to call initLogConstructor");return $logs$$module$src$log$$.user};function $getService$$module$src$service$$($JSCompiler_holder$jscomp$inline_22_win$jscomp$8$$,$JSCompiler_s$jscomp$inline_25_id$jscomp$11$$){$JSCompiler_holder$jscomp$inline_22_win$jscomp$8$$=$JSCompiler_holder$jscomp$inline_22_win$jscomp$8$$.__AMP_TOP||$JSCompiler_holder$jscomp$inline_22_win$jscomp$8$$;var $JSCompiler_services$jscomp$inline_69$$=$JSCompiler_holder$jscomp$inline_22_win$jscomp$8$$.services;$JSCompiler_services$jscomp$inline_69$$||($JSCompiler_services$jscomp$inline_69$$=$JSCompiler_holder$jscomp$inline_22_win$jscomp$8$$.services=
{});$JSCompiler_s$jscomp$inline_25_id$jscomp$11$$=$JSCompiler_services$jscomp$inline_69$$[$JSCompiler_s$jscomp$inline_25_id$jscomp$11$$];$JSCompiler_s$jscomp$inline_25_id$jscomp$11$$.obj||($JSCompiler_s$jscomp$inline_25_id$jscomp$11$$.obj=new $JSCompiler_s$jscomp$inline_25_id$jscomp$11$$.ctor($JSCompiler_s$jscomp$inline_25_id$jscomp$11$$.context),$JSCompiler_s$jscomp$inline_25_id$jscomp$11$$.ctor=null,$JSCompiler_s$jscomp$inline_25_id$jscomp$11$$.context=null,$JSCompiler_s$jscomp$inline_25_id$jscomp$11$$.resolve&&
$JSCompiler_s$jscomp$inline_25_id$jscomp$11$$.resolve($JSCompiler_s$jscomp$inline_25_id$jscomp$11$$.obj));return $JSCompiler_s$jscomp$inline_25_id$jscomp$11$$.obj};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var $propertyNameCache$$module$src$style$$,$vendorPrefixes$$module$src$style$$="Webkit webkit Moz moz ms O o".split(" ");
function $setStyles$$module$src$style$$($element$jscomp$58$$,$styles$jscomp$1$$){for(var $k$jscomp$2$$ in $styles$jscomp$1$$){var $JSCompiler_element$jscomp$inline_27$$=$element$jscomp$58$$,$JSCompiler_value$jscomp$inline_29$$=$styles$jscomp$1$$[$k$jscomp$2$$];var $JSCompiler_propertyName$jscomp$inline_32_JSCompiler_style$jscomp$inline_71$$=$JSCompiler_element$jscomp$inline_27$$.style;var $JSCompiler_camelCase$jscomp$inline_72$$=$k$jscomp$2$$;if(2>$JSCompiler_camelCase$jscomp$inline_72$$.length?0:
0==$JSCompiler_camelCase$jscomp$inline_72$$.lastIndexOf("--",0))$JSCompiler_propertyName$jscomp$inline_32_JSCompiler_style$jscomp$inline_71$$=$JSCompiler_camelCase$jscomp$inline_72$$;else{$propertyNameCache$$module$src$style$$||($propertyNameCache$$module$src$style$$=Object.create(null));var $JSCompiler_propertyName$jscomp$inline_74$$=$propertyNameCache$$module$src$style$$[$JSCompiler_camelCase$jscomp$inline_72$$];if(!$JSCompiler_propertyName$jscomp$inline_74$$){$JSCompiler_propertyName$jscomp$inline_74$$=
$JSCompiler_camelCase$jscomp$inline_72$$;if(void 0===$JSCompiler_propertyName$jscomp$inline_32_JSCompiler_style$jscomp$inline_71$$[$JSCompiler_camelCase$jscomp$inline_72$$]){var $JSCompiler_prefixedPropertyName$jscomp$inline_76_JSCompiler_titleCase$jscomp$inline_75$$=$JSCompiler_camelCase$jscomp$inline_72$$.charAt(0).toUpperCase()+$JSCompiler_camelCase$jscomp$inline_72$$.slice(1);b:{for(var $JSCompiler_i$jscomp$inline_86$$=0;$JSCompiler_i$jscomp$inline_86$$<$vendorPrefixes$$module$src$style$$.length;$JSCompiler_i$jscomp$inline_86$$++){var $JSCompiler_propertyName$jscomp$inline_87$$=
$vendorPrefixes$$module$src$style$$[$JSCompiler_i$jscomp$inline_86$$]+$JSCompiler_prefixedPropertyName$jscomp$inline_76_JSCompiler_titleCase$jscomp$inline_75$$;if(void 0!==$JSCompiler_propertyName$jscomp$inline_32_JSCompiler_style$jscomp$inline_71$$[$JSCompiler_propertyName$jscomp$inline_87$$]){$JSCompiler_prefixedPropertyName$jscomp$inline_76_JSCompiler_titleCase$jscomp$inline_75$$=$JSCompiler_propertyName$jscomp$inline_87$$;break b}}$JSCompiler_prefixedPropertyName$jscomp$inline_76_JSCompiler_titleCase$jscomp$inline_75$$=
""}void 0!==$JSCompiler_propertyName$jscomp$inline_32_JSCompiler_style$jscomp$inline_71$$[$JSCompiler_prefixedPropertyName$jscomp$inline_76_JSCompiler_titleCase$jscomp$inline_75$$]&&($JSCompiler_propertyName$jscomp$inline_74$$=$JSCompiler_prefixedPropertyName$jscomp$inline_76_JSCompiler_titleCase$jscomp$inline_75$$)}$propertyNameCache$$module$src$style$$[$JSCompiler_camelCase$jscomp$inline_72$$]=$JSCompiler_propertyName$jscomp$inline_74$$}$JSCompiler_propertyName$jscomp$inline_32_JSCompiler_style$jscomp$inline_71$$=
$JSCompiler_propertyName$jscomp$inline_74$$}$JSCompiler_propertyName$jscomp$inline_32_JSCompiler_style$jscomp$inline_71$$&&($JSCompiler_element$jscomp$inline_27$$.style[$JSCompiler_propertyName$jscomp$inline_32_JSCompiler_style$jscomp$inline_71$$]=$JSCompiler_value$jscomp$inline_29$$)}};var $DEFAULT_FONTS_$$module$extensions$amp_font$0_1$fontloader$$=["sans-serif","serif"];function $FontLoader$$module$extensions$amp_font$0_1$fontloader$$($ampdoc$jscomp$10$$){this.$ampdoc_$=$ampdoc$jscomp$10$$;this.$document_$=$ampdoc$jscomp$10$$.win.document;this.$fontConfig_$=this.$container_$=null;this.$fontLoadRejected_$=this.$fontLoadResolved_$=!1}
$FontLoader$$module$extensions$amp_font$0_1$fontloader$$.prototype.load=function($fontConfig$$,$timeout$jscomp$3$$){var $$jscomp$this$jscomp$1$$=this;this.$fontConfig_$=$fontConfig$$;return $getService$$module$src$service$$(this.$ampdoc_$.win,"timer").timeoutPromise($timeout$jscomp$3$$,$JSCompiler_StaticMethods_load_$$(this)).then(function(){$$jscomp$this$jscomp$1$$.$fontLoadResolved_$=!0;$$jscomp$this$jscomp$1$$.$dispose_$()},function($fontConfig$$){$$jscomp$this$jscomp$1$$.$fontLoadRejected_$=!0;
$$jscomp$this$jscomp$1$$.$dispose_$();throw $fontConfig$$;})};
function $JSCompiler_StaticMethods_load_$$($JSCompiler_StaticMethods_load_$self$$){return new Promise(function($resolve$jscomp$10$$,$reject$jscomp$4$$){var $fontString$$=$JSCompiler_StaticMethods_load_$self$$.$fontConfig_$.fontStyle+" "+$JSCompiler_StaticMethods_load_$self$$.$fontConfig_$.variant+" "+$JSCompiler_StaticMethods_load_$self$$.$fontConfig_$.weight+" "+$JSCompiler_StaticMethods_load_$self$$.$fontConfig_$.size+" '"+$JSCompiler_StaticMethods_load_$self$$.$fontConfig_$.family+"'";"fonts"in
$JSCompiler_StaticMethods_load_$self$$.$document_$?$JSCompiler_StaticMethods_load_$self$$.$document_$.fonts.check($fontString$$)?$resolve$jscomp$10$$():$JSCompiler_StaticMethods_load_$self$$.$document_$.fonts.load($fontString$$).then(function(){return $JSCompiler_StaticMethods_load_$self$$.$document_$.fonts.load($fontString$$)}).then(function(){$JSCompiler_StaticMethods_load_$self$$.$document_$.fonts.check($fontString$$)?$resolve$jscomp$10$$():$reject$jscomp$4$$(Error("Font could not be loaded, probably due to incorrect @font-face."))}).catch($reject$jscomp$4$$):
$JSCompiler_StaticMethods_loadWithPolyfill_$$($JSCompiler_StaticMethods_load_$self$$).then($resolve$jscomp$10$$,$reject$jscomp$4$$)})}
function $JSCompiler_StaticMethods_loadWithPolyfill_$$($JSCompiler_StaticMethods_loadWithPolyfill_$self$$){return new Promise(function($resolve$jscomp$11$$,$reject$jscomp$5$$){var $vsync$$=$getService$$module$src$service$$($JSCompiler_StaticMethods_loadWithPolyfill_$self$$.$ampdoc_$.win,"vsync"),$comparators$$=$JSCompiler_StaticMethods_createFontComparators_$$($JSCompiler_StaticMethods_loadWithPolyfill_$self$$),$vsyncTask$$=$vsync$$.createTask({measure:function(){$JSCompiler_StaticMethods_loadWithPolyfill_$self$$.$fontLoadResolved_$?
$resolve$jscomp$11$$():$JSCompiler_StaticMethods_loadWithPolyfill_$self$$.$fontLoadRejected_$?$reject$jscomp$5$$(Error("Font loading timed out.")):$comparators$$.some(function($JSCompiler_StaticMethods_loadWithPolyfill_$self$$){return $JSCompiler_StaticMethods_loadWithPolyfill_$self$$.compare()})?$resolve$jscomp$11$$():$vsyncTask$$()}});$vsyncTask$$()})}
function $JSCompiler_StaticMethods_createFontComparators_$$($JSCompiler_StaticMethods_createFontComparators_$self$$){var $containerElement$$=$JSCompiler_StaticMethods_createFontComparators_$self$$.$container_$=$JSCompiler_StaticMethods_createFontComparators_$self$$.$document_$.createElement("div");$setStyles$$module$src$style$$($containerElement$$,{fontSize:"40px",fontVariant:$JSCompiler_StaticMethods_createFontComparators_$self$$.$fontConfig_$.variant,fontWeight:$JSCompiler_StaticMethods_createFontComparators_$self$$.$fontConfig_$.weight,
fontStyle:$JSCompiler_StaticMethods_createFontComparators_$self$$.$fontConfig_$.fontStyle,left:"-999px",lineHeight:"normal",margin:0,padding:0,position:"absolute",top:"-999px",visibility:"hidden"});var $comparators$jscomp$1$$=$DEFAULT_FONTS_$$module$extensions$amp_font$0_1$fontloader$$.map(function($comparators$jscomp$1$$){return new $FontComparator$$module$extensions$amp_font$0_1$fontloader$$($containerElement$$,$JSCompiler_StaticMethods_createFontComparators_$self$$.$fontConfig_$.family,$comparators$jscomp$1$$)});
$JSCompiler_StaticMethods_createFontComparators_$self$$.$ampdoc_$.getBody().appendChild($containerElement$$);return $comparators$jscomp$1$$}$FontLoader$$module$extensions$amp_font$0_1$fontloader$$.prototype.$dispose_$=function(){if(this.$container_$){var $JSCompiler_element$jscomp$inline_34$$=this.$container_$;$JSCompiler_element$jscomp$inline_34$$.parentElement&&$JSCompiler_element$jscomp$inline_34$$.parentElement.removeChild($JSCompiler_element$jscomp$inline_34$$)}this.$container_$=null};
function $FontComparator$$module$extensions$amp_font$0_1$fontloader$$($container$jscomp$4$$,$customFont$$,$defaultFont$jscomp$1$$){var $doc$jscomp$14$$=$container$jscomp$4$$.ownerDocument,$testFontFamily$$=$customFont$$+","+$defaultFont$jscomp$1$$;this.$defaultFontElement_$=$JSCompiler_StaticMethods_getFontElement_$$($doc$jscomp$14$$,$defaultFont$jscomp$1$$);this.$testFontElement_$=$JSCompiler_StaticMethods_getFontElement_$$($doc$jscomp$14$$,$testFontFamily$$);$container$jscomp$4$$.appendChild(this.$defaultFontElement_$);
$container$jscomp$4$$.appendChild(this.$testFontElement_$)}
function $JSCompiler_StaticMethods_getFontElement_$$($doc$jscomp$15_element$jscomp$61$$,$fontFamily$jscomp$1$$){$doc$jscomp$15_element$jscomp$61$$=$doc$jscomp$15_element$jscomp$61$$.createElement("div");$doc$jscomp$15_element$jscomp$61$$.textContent="MAxmTYklsjo190QW";$setStyles$$module$src$style$$($doc$jscomp$15_element$jscomp$61$$,{float:"left",fontFamily:$fontFamily$jscomp$1$$,margin:0,padding:0,whiteSpace:"nowrap"});return $doc$jscomp$15_element$jscomp$61$$}
$FontComparator$$module$extensions$amp_font$0_1$fontloader$$.prototype.compare=function(){var $hasWidthChanged$$=2<Math.abs(this.$defaultFontElement_$.offsetWidth-this.$testFontElement_$.offsetWidth),$hasHeightChanged$$=2<Math.abs(this.$defaultFontElement_$.offsetHeight-this.$testFontElement_$.offsetHeight);return $hasWidthChanged$$||$hasHeightChanged$$};function $AmpFont$$module$extensions$amp_font$0_1$amp_font$$($$jscomp$super$this_element$jscomp$62$$){$$jscomp$super$this_element$jscomp$62$$=AMP.BaseElement.call(this,$$jscomp$super$this_element$jscomp$62$$)||this;$$jscomp$super$this_element$jscomp$62$$.$fontFamily_$="";$$jscomp$super$this_element$jscomp$62$$.$fontWeight_$="";$$jscomp$super$this_element$jscomp$62$$.$fontStyle_$="";$$jscomp$super$this_element$jscomp$62$$.$fontVariant_$="";$$jscomp$super$this_element$jscomp$62$$.$fontLoader_$=null;
return $$jscomp$super$this_element$jscomp$62$$}var $JSCompiler_parentCtor$jscomp$inline_37$$=AMP.BaseElement;$AmpFont$$module$extensions$amp_font$0_1$amp_font$$.prototype=$$jscomp$objectCreate$$($JSCompiler_parentCtor$jscomp$inline_37$$.prototype);$AmpFont$$module$extensions$amp_font$0_1$amp_font$$.prototype.constructor=$AmpFont$$module$extensions$amp_font$0_1$amp_font$$;
if($$jscomp$setPrototypeOf$$)$$jscomp$setPrototypeOf$$($AmpFont$$module$extensions$amp_font$0_1$amp_font$$,$JSCompiler_parentCtor$jscomp$inline_37$$);else for(var $JSCompiler_p$jscomp$inline_38$$ in $JSCompiler_parentCtor$jscomp$inline_37$$)if("prototype"!=$JSCompiler_p$jscomp$inline_38$$)if(Object.defineProperties){var $JSCompiler_descriptor$jscomp$inline_39$$=Object.getOwnPropertyDescriptor($JSCompiler_parentCtor$jscomp$inline_37$$,$JSCompiler_p$jscomp$inline_38$$);$JSCompiler_descriptor$jscomp$inline_39$$&&
Object.defineProperty($AmpFont$$module$extensions$amp_font$0_1$amp_font$$,$JSCompiler_p$jscomp$inline_38$$,$JSCompiler_descriptor$jscomp$inline_39$$)}else $AmpFont$$module$extensions$amp_font$0_1$amp_font$$[$JSCompiler_p$jscomp$inline_38$$]=$JSCompiler_parentCtor$jscomp$inline_37$$[$JSCompiler_p$jscomp$inline_38$$];$AmpFont$$module$extensions$amp_font$0_1$amp_font$$.$superClass_$=$JSCompiler_parentCtor$jscomp$inline_37$$.prototype;
$AmpFont$$module$extensions$amp_font$0_1$amp_font$$.prototype.prerenderAllowed=function(){return!0};
$AmpFont$$module$extensions$amp_font$0_1$amp_font$$.prototype.buildCallback=function(){var $JSCompiler_shouldBeTrueish$jscomp$inline_41$$=this.element.getAttribute("font-family"),$JSCompiler_opt_1$jscomp$inline_42$$=this.element;this.$fontFamily_$=$user$$module$src$log$$().assert($JSCompiler_shouldBeTrueish$jscomp$inline_41$$,"The font-family attribute is required for <amp-font> %s",$JSCompiler_opt_1$jscomp$inline_42$$,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0);this.$fontWeight_$=this.element.getAttribute("font-weight")||
"400";this.$fontStyle_$=this.element.getAttribute("font-style")||"normal";this.$fontVariant_$=this.element.getAttribute("font-variant")||"normal";this.$fontLoader_$=new $FontLoader$$module$extensions$amp_font$0_1$fontloader$$(this.getAmpDoc());$JSCompiler_StaticMethods_startLoad_$$(this)};
function $JSCompiler_StaticMethods_startLoad_$$($JSCompiler_StaticMethods_startLoad_$self$$){$JSCompiler_StaticMethods_startLoad_$self$$.$fontLoader_$.load({fontStyle:$JSCompiler_StaticMethods_startLoad_$self$$.$fontStyle_$,variant:$JSCompiler_StaticMethods_startLoad_$self$$.$fontVariant_$,weight:$JSCompiler_StaticMethods_startLoad_$self$$.$fontWeight_$,size:"medium",family:$JSCompiler_StaticMethods_startLoad_$self$$.$fontFamily_$},$JSCompiler_StaticMethods_getTimeout_$$($JSCompiler_StaticMethods_startLoad_$self$$)).then(function(){var $JSCompiler_addClassName$jscomp$inline_54$$=
$JSCompiler_StaticMethods_startLoad_$self$$.element.getAttribute("on-load-add-class"),$JSCompiler_removeClassName$jscomp$inline_55$$=$JSCompiler_StaticMethods_startLoad_$self$$.element.getAttribute("on-load-remove-class");$JSCompiler_StaticMethods_onFontLoadFinish_$$($JSCompiler_StaticMethods_startLoad_$self$$,$JSCompiler_addClassName$jscomp$inline_54$$,$JSCompiler_removeClassName$jscomp$inline_55$$)}).catch(function(){var $JSCompiler_addClassName$jscomp$inline_58$$=$JSCompiler_StaticMethods_startLoad_$self$$.element.getAttribute("on-error-add-class"),
$JSCompiler_removeClassName$jscomp$inline_59$$=$JSCompiler_StaticMethods_startLoad_$self$$.element.getAttribute("on-error-remove-class");$JSCompiler_StaticMethods_onFontLoadFinish_$$($JSCompiler_StaticMethods_startLoad_$self$$,$JSCompiler_addClassName$jscomp$inline_58$$,$JSCompiler_removeClassName$jscomp$inline_59$$);$user$$module$src$log$$().warn("amp-font","Font download timed out for "+$JSCompiler_StaticMethods_startLoad_$self$$.$fontFamily_$)})}
function $JSCompiler_StaticMethods_onFontLoadFinish_$$($JSCompiler_StaticMethods_onFontLoadFinish_$self$$,$addClassName$jscomp$2$$,$removeClassName$jscomp$2$$){var $ampdoc$jscomp$11_root$jscomp$7$$=$JSCompiler_StaticMethods_onFontLoadFinish_$self$$.getAmpDoc();$ampdoc$jscomp$11_root$jscomp$7$$=$ampdoc$jscomp$11_root$jscomp$7$$.getRootNode().documentElement||$ampdoc$jscomp$11_root$jscomp$7$$.getBody();$addClassName$jscomp$2$$&&$ampdoc$jscomp$11_root$jscomp$7$$.classList.add($addClassName$jscomp$2$$);
$removeClassName$jscomp$2$$&&$ampdoc$jscomp$11_root$jscomp$7$$.classList.remove($removeClassName$jscomp$2$$);$JSCompiler_StaticMethods_onFontLoadFinish_$self$$.$dispose_$()}$AmpFont$$module$extensions$amp_font$0_1$amp_font$$.prototype.$dispose_$=function(){this.$fontLoader_$=null};
function $JSCompiler_StaticMethods_getTimeout_$$($JSCompiler_StaticMethods_getTimeout_$self$$){var $timeoutInMs$$=parseInt($JSCompiler_StaticMethods_getTimeout_$self$$.element.getAttribute("timeout"),10),$JSCompiler_value$jscomp$inline_61$$=$timeoutInMs$$;$timeoutInMs$$="number"!==typeof $JSCompiler_value$jscomp$inline_61$$||!isFinite($JSCompiler_value$jscomp$inline_61$$)||0>$timeoutInMs$$?3E3:$timeoutInMs$$;return $timeoutInMs$$=Math.max($timeoutInMs$$-$getService$$module$src$service$$($JSCompiler_StaticMethods_getTimeout_$self$$.win,
"timer").timeSinceStart(),100)}(function($AMP$jscomp$1$$){$AMP$jscomp$1$$.registerElement("amp-font",$AmpFont$$module$extensions$amp_font$0_1$amp_font$$)})(self.AMP);
})});

//# sourceMappingURL=amp-font-0.1.js.map
