(self.AMP=self.AMP||[]).push({n:"amp-web-push",v:"1904281823091",f:(function(AMP,_){
var $JSCompiler_prototypeAlias$$,$$jscomp$objectCreate$$="function"==typeof Object.create?Object.create:function($prototype$$){function $ctor$$(){}$ctor$$.prototype=$prototype$$;return new $ctor$$},$JSCompiler_temp$jscomp$12$$;
if("function"==typeof Object.setPrototypeOf)$JSCompiler_temp$jscomp$12$$=Object.setPrototypeOf;else{var $JSCompiler_inline_result$jscomp$13$$;a:{var $JSCompiler_x$jscomp$inline_29$$={a:!0},$JSCompiler_y$jscomp$inline_30$$={};try{$JSCompiler_y$jscomp$inline_30$$.__proto__=$JSCompiler_x$jscomp$inline_29$$;$JSCompiler_inline_result$jscomp$13$$=$JSCompiler_y$jscomp$inline_30$$.a;break a}catch($JSCompiler_e$jscomp$inline_31$$){}$JSCompiler_inline_result$jscomp$13$$=!1}$JSCompiler_temp$jscomp$12$$=$JSCompiler_inline_result$jscomp$13$$?
function($target$jscomp$83$$,$proto$jscomp$3$$){$target$jscomp$83$$.__proto__=$proto$jscomp$3$$;if($target$jscomp$83$$.__proto__!==$proto$jscomp$3$$)throw new TypeError($target$jscomp$83$$+" is not extensible");return $target$jscomp$83$$}:null}var $$jscomp$setPrototypeOf$$=$JSCompiler_temp$jscomp$12$$;
function $$jscomp$inherits$$($childCtor$$,$parentCtor$$){$childCtor$$.prototype=$$jscomp$objectCreate$$($parentCtor$$.prototype);$childCtor$$.prototype.constructor=$childCtor$$;if($$jscomp$setPrototypeOf$$)$$jscomp$setPrototypeOf$$($childCtor$$,$parentCtor$$);else for(var $p$$ in $parentCtor$$)if("prototype"!=$p$$)if(Object.defineProperties){var $descriptor$jscomp$1$$=Object.getOwnPropertyDescriptor($parentCtor$$,$p$$);$descriptor$jscomp$1$$&&Object.defineProperty($childCtor$$,$p$$,$descriptor$jscomp$1$$)}else $childCtor$$[$p$$]=
$parentCtor$$[$p$$];$childCtor$$.$superClass_$=$parentCtor$$.prototype}var $$jscomp$global$$=function($maybeGlobal$$){return"undefined"!=typeof window&&window===$maybeGlobal$$?$maybeGlobal$$:"undefined"!=typeof global&&null!=global?global:$maybeGlobal$$}(this);function $tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($component$jscomp$4$$,$fallback$$){$fallback$$=void 0===$fallback$$?"":$fallback$$;try{return decodeURIComponent($component$jscomp$4$$)}catch($e$jscomp$8$$){return $fallback$$}};var $regex$$module$src$url_parse_query_string$$=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;
function $parseQueryString_$$module$src$url_parse_query_string$$($queryString$$){var $params$jscomp$1$$=Object.create(null);if(!$queryString$$)return $params$jscomp$1$$;for(var $match$$;$match$$=$regex$$module$src$url_parse_query_string$$.exec($queryString$$);){var $name$jscomp$70$$=$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($match$$[1],$match$$[1]),$value$jscomp$86$$=$match$$[2]?$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($match$$[2],$match$$[2]):"";
$params$jscomp$1$$[$name$jscomp$70$$]=$value$jscomp$86$$}return $params$jscomp$1$$};var $rtvVersion$$module$src$mode$$="";
function $getMode$$module$src$mode$$(){var $opt_win$$,$win$$=$opt_win$$||self;if($win$$.AMP_MODE)var $JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_33$$=$win$$.AMP_MODE;else{$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_33$$=$win$$;var $JSCompiler_AMP_CONFIG$jscomp$inline_34_JSCompiler_singlePassType$jscomp$inline_41$$=self.AMP_CONFIG||{},$JSCompiler_runningTests$jscomp$inline_38$$=!!$JSCompiler_AMP_CONFIG$jscomp$inline_34_JSCompiler_singlePassType$jscomp$inline_41$$.test||!(!$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_33$$.AMP_TEST&&
!$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_33$$.__karma__),$JSCompiler_isLocalDev$jscomp$inline_39$$=!!$JSCompiler_AMP_CONFIG$jscomp$inline_34_JSCompiler_singlePassType$jscomp$inline_41$$.localDev||$JSCompiler_runningTests$jscomp$inline_38$$,$JSCompiler_hashQuery$jscomp$inline_40$$=$parseQueryString_$$module$src$url_parse_query_string$$($JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_33$$.location.originalHash||$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_33$$.location.hash);
$JSCompiler_AMP_CONFIG$jscomp$inline_34_JSCompiler_singlePassType$jscomp$inline_41$$=$JSCompiler_AMP_CONFIG$jscomp$inline_34_JSCompiler_singlePassType$jscomp$inline_41$$.spt;var $JSCompiler_searchQuery$jscomp$inline_42$$=$parseQueryString_$$module$src$url_parse_query_string$$($JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_33$$.location.search);$rtvVersion$$module$src$mode$$||($rtvVersion$$module$src$mode$$=$JSCompiler_isLocalDev$jscomp$inline_39$$?"1904281823091":$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_33$$.AMP_CONFIG&&
$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_33$$.AMP_CONFIG.v?$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_33$$.AMP_CONFIG.v:"011904281823091");$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_33$$=$win$$.AMP_MODE={localDev:$JSCompiler_isLocalDev$jscomp$inline_39$$,development:!("1"!=$JSCompiler_hashQuery$jscomp$inline_40$$.development&&!$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_33$$.AMP_DEV_MODE),examiner:"2"==$JSCompiler_hashQuery$jscomp$inline_40$$.development,
filter:$JSCompiler_hashQuery$jscomp$inline_40$$.filter,geoOverride:$JSCompiler_hashQuery$jscomp$inline_40$$["amp-geo"],minified:!0,lite:void 0!=$JSCompiler_searchQuery$jscomp$inline_42$$.amp_lite,test:$JSCompiler_runningTests$jscomp$inline_38$$,log:$JSCompiler_hashQuery$jscomp$inline_40$$.log,version:"1904281823091",rtvVersion:$rtvVersion$$module$src$mode$$,singlePassType:$JSCompiler_AMP_CONFIG$jscomp$inline_34_JSCompiler_singlePassType$jscomp$inline_41$$}}return $JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_33$$}
;self.log=self.log||{user:null,dev:null,userForEmbed:null};var $logs$$module$src$log$$=self.log;function $user$$module$src$log$$(){if(!$logs$$module$src$log$$.user)throw Error("failed to call initLogConstructor");return $logs$$module$src$log$$.user}function $dev$$module$src$log$$(){if($logs$$module$src$log$$.dev)return $logs$$module$src$log$$.dev;throw Error("failed to call initLogConstructor");};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var $regex$$module$third_party$css_escape$css_escape$$=/(\0)|^(-)$|([\x01-\x1f\x7f]|^-?[0-9])|([\x80-\uffff0-9a-zA-Z_-]+)|[^]/g;function $escaper$$module$third_party$css_escape$css_escape$$($match$jscomp$1$$,$nil$$,$dash$$,$hexEscape$$,$chars$$){return $chars$$?$chars$$:$nil$$?"\ufffd":$hexEscape$$?$match$jscomp$1$$.slice(0,-1)+"\\"+$match$jscomp$1$$.slice(-1).charCodeAt(0).toString(16)+" ":"\\"+$match$jscomp$1$$}
function $cssEscape$$module$third_party$css_escape$css_escape$$($value$jscomp$91$$){return String($value$jscomp$91$$).replace($regex$$module$third_party$css_escape$css_escape$$,$escaper$$module$third_party$css_escape$css_escape$$)};function $getService$$module$src$service$$($win$jscomp$8$$,$id$jscomp$11$$){$win$jscomp$8$$=$win$jscomp$8$$.__AMP_TOP||$win$jscomp$8$$;return $getServiceInternal$$module$src$service$$($win$jscomp$8$$,$id$jscomp$11$$)}
function $getServiceForDoc$$module$src$service$$($elementOrAmpDoc$$){var $JSCompiler_ampdoc$jscomp$inline_48_JSCompiler_inline_result$jscomp$17_ampdoc$jscomp$2$$=$getAmpdoc$$module$src$service$$($elementOrAmpDoc$$);$JSCompiler_ampdoc$jscomp$inline_48_JSCompiler_inline_result$jscomp$17_ampdoc$jscomp$2$$=$getAmpdoc$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_48_JSCompiler_inline_result$jscomp$17_ampdoc$jscomp$2$$);$JSCompiler_ampdoc$jscomp$inline_48_JSCompiler_inline_result$jscomp$17_ampdoc$jscomp$2$$=
$JSCompiler_ampdoc$jscomp$inline_48_JSCompiler_inline_result$jscomp$17_ampdoc$jscomp$2$$.isSingleDoc()?$JSCompiler_ampdoc$jscomp$inline_48_JSCompiler_inline_result$jscomp$17_ampdoc$jscomp$2$$.win:$JSCompiler_ampdoc$jscomp$inline_48_JSCompiler_inline_result$jscomp$17_ampdoc$jscomp$2$$;return $getServiceInternal$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_48_JSCompiler_inline_result$jscomp$17_ampdoc$jscomp$2$$,"amp-web-push-service")}
function $getAmpdoc$$module$src$service$$($nodeOrDoc$jscomp$2$$){return $nodeOrDoc$jscomp$2$$.nodeType?$getService$$module$src$service$$(($nodeOrDoc$jscomp$2$$.ownerDocument||$nodeOrDoc$jscomp$2$$).defaultView,"ampdoc").getAmpDoc($nodeOrDoc$jscomp$2$$):$nodeOrDoc$jscomp$2$$}
function $getServiceInternal$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$,$id$jscomp$19$$){var $JSCompiler_services$jscomp$inline_55$$=$holder$jscomp$4_s$jscomp$8$$.services;$JSCompiler_services$jscomp$inline_55$$||($JSCompiler_services$jscomp$inline_55$$=$holder$jscomp$4_s$jscomp$8$$.services={});var $services$$=$JSCompiler_services$jscomp$inline_55$$;$holder$jscomp$4_s$jscomp$8$$=$services$$[$id$jscomp$19$$];$holder$jscomp$4_s$jscomp$8$$.obj||($holder$jscomp$4_s$jscomp$8$$.obj=new $holder$jscomp$4_s$jscomp$8$$.ctor($holder$jscomp$4_s$jscomp$8$$.context),
$holder$jscomp$4_s$jscomp$8$$.ctor=null,$holder$jscomp$4_s$jscomp$8$$.context=null,$holder$jscomp$4_s$jscomp$8$$.resolve&&$holder$jscomp$4_s$jscomp$8$$.resolve($holder$jscomp$4_s$jscomp$8$$.obj));return $holder$jscomp$4_s$jscomp$8$$.obj};function $LruCache$$module$src$utils$lru_cache$$(){var $capacity$$=100;this.$capacity_$=$capacity$$;this.$access_$=this.$size_$=0;this.$cache_$=Object.create(null)}$LruCache$$module$src$utils$lru_cache$$.prototype.has=function($key$jscomp$37$$){return!!this.$cache_$[$key$jscomp$37$$]};$LruCache$$module$src$utils$lru_cache$$.prototype.get=function($key$jscomp$38$$){var $cacheable$$=this.$cache_$[$key$jscomp$38$$];if($cacheable$$)return $cacheable$$.access=++this.$access_$,$cacheable$$.payload};
$LruCache$$module$src$utils$lru_cache$$.prototype.put=function($JSCompiler_cache$jscomp$inline_58_key$jscomp$39$$,$payload$$){this.has($JSCompiler_cache$jscomp$inline_58_key$jscomp$39$$)||this.$size_$++;this.$cache_$[$JSCompiler_cache$jscomp$inline_58_key$jscomp$39$$]={payload:$payload$$,access:this.$access_$};if(!(this.$size_$<=this.$capacity_$)){$dev$$module$src$log$$().warn("lru-cache","Trimming LRU cache");$JSCompiler_cache$jscomp$inline_58_key$jscomp$39$$=this.$cache_$;var $JSCompiler_oldest$jscomp$inline_59$$=
this.$access_$+1,$JSCompiler_key$jscomp$inline_61$$;for($JSCompiler_key$jscomp$inline_61$$ in $JSCompiler_cache$jscomp$inline_58_key$jscomp$39$$){var $JSCompiler_access$jscomp$inline_62$$=$JSCompiler_cache$jscomp$inline_58_key$jscomp$39$$[$JSCompiler_key$jscomp$inline_61$$].access;if($JSCompiler_access$jscomp$inline_62$$<$JSCompiler_oldest$jscomp$inline_59$$){$JSCompiler_oldest$jscomp$inline_59$$=$JSCompiler_access$jscomp$inline_62$$;var $JSCompiler_oldestKey$jscomp$inline_60$$=$JSCompiler_key$jscomp$inline_61$$}}void 0!==
$JSCompiler_oldestKey$jscomp$inline_60$$&&(delete $JSCompiler_cache$jscomp$inline_58_key$jscomp$39$$[$JSCompiler_oldestKey$jscomp$inline_60$$],this.$size_$--)}};(function($opt_initial$jscomp$1$$){return $opt_initial$jscomp$1$$||{}})({c:!0,v:!0,a:!0,ad:!0,action:!0});var $a$$module$src$url$$,$cache$$module$src$url$$;
function $parseUrlDeprecated$$module$src$url$$($JSCompiler_inline_result$jscomp$21_url$jscomp$21$$){var $opt_nocache$$;$a$$module$src$url$$||($a$$module$src$url$$=self.document.createElement("a"),$cache$$module$src$url$$=self.UrlCache||(self.UrlCache=new $LruCache$$module$src$utils$lru_cache$$));var $JSCompiler_opt_cache$jscomp$inline_65$$=$opt_nocache$$?null:$cache$$module$src$url$$,$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$=$a$$module$src$url$$;if($JSCompiler_opt_cache$jscomp$inline_65$$&&
$JSCompiler_opt_cache$jscomp$inline_65$$.has($JSCompiler_inline_result$jscomp$21_url$jscomp$21$$))$JSCompiler_inline_result$jscomp$21_url$jscomp$21$$=$JSCompiler_opt_cache$jscomp$inline_65$$.get($JSCompiler_inline_result$jscomp$21_url$jscomp$21$$);else{$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$.href=$JSCompiler_inline_result$jscomp$21_url$jscomp$21$$;$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$.protocol||($JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$.href=
$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$.href);var $JSCompiler_info$jscomp$inline_67$$={href:$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$.href,protocol:$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$.protocol,host:$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$.host,hostname:$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$.hostname,port:"0"==$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$.port?
"":$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$.port,pathname:$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$.pathname,search:$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$.search,hash:$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$.hash,origin:null};"/"!==$JSCompiler_info$jscomp$inline_67$$.pathname[0]&&($JSCompiler_info$jscomp$inline_67$$.pathname="/"+$JSCompiler_info$jscomp$inline_67$$.pathname);if("http:"==$JSCompiler_info$jscomp$inline_67$$.protocol&&
80==$JSCompiler_info$jscomp$inline_67$$.port||"https:"==$JSCompiler_info$jscomp$inline_67$$.protocol&&443==$JSCompiler_info$jscomp$inline_67$$.port)$JSCompiler_info$jscomp$inline_67$$.port="",$JSCompiler_info$jscomp$inline_67$$.host=$JSCompiler_info$jscomp$inline_67$$.hostname;$JSCompiler_info$jscomp$inline_67$$.origin=$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$.origin&&"null"!=$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$.origin?$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$.origin:
"data:"!=$JSCompiler_info$jscomp$inline_67$$.protocol&&$JSCompiler_info$jscomp$inline_67$$.host?$JSCompiler_info$jscomp$inline_67$$.protocol+"//"+$JSCompiler_info$jscomp$inline_67$$.host:$JSCompiler_info$jscomp$inline_67$$.href;$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$=$getMode$$module$src$mode$$().test&&Object.freeze?Object.freeze($JSCompiler_info$jscomp$inline_67$$):$JSCompiler_info$jscomp$inline_67$$;$JSCompiler_opt_cache$jscomp$inline_65$$&&$JSCompiler_opt_cache$jscomp$inline_65$$.put($JSCompiler_inline_result$jscomp$21_url$jscomp$21$$,
$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$);$JSCompiler_inline_result$jscomp$21_url$jscomp$21$$=$JSCompiler_a$jscomp$inline_66_JSCompiler_frozen$jscomp$inline_68$$}return $JSCompiler_inline_result$jscomp$21_url$jscomp$21$$};var $WebPushConfigAttributes$$module$extensions$amp_web_push$0_1$amp_web_push_config$$={HELPER_FRAME_URL:"helper-iframe-url",PERMISSION_DIALOG_URL:"permission-dialog-url",SERVICE_WORKER_URL:"service-worker-url",SERVICE_WORKER_SCOPE:"service-worker-scope"};function $WebPushConfig$$module$extensions$amp_web_push$0_1$amp_web_push_config$$($element$jscomp$13$$){return AMP.BaseElement.call(this,$element$jscomp$13$$)||this}
$$jscomp$inherits$$($WebPushConfig$$module$extensions$amp_web_push$0_1$amp_web_push_config$$,AMP.BaseElement);$JSCompiler_prototypeAlias$$=$WebPushConfig$$module$extensions$amp_web_push$0_1$amp_web_push_config$$.prototype;
$JSCompiler_prototypeAlias$$.validate=function(){if("amp-web-push"!==this.element.getAttribute("id"))throw $user$$module$src$log$$().createError("<amp-web-push> must have an id attribute with value 'amp-web-push'.");if(1<this.getAmpDoc().getRootNode().querySelectorAll("#"+$cssEscape$$module$third_party$css_escape$css_escape$$("amp-web-push")).length)throw $user$$module$src$log$$().createError("Only one <amp-web-push> element may exist on a page.");var $config$jscomp$2$$={"helper-iframe-url":null,
"permission-dialog-url":null,"service-worker-url":null,"service-worker-scope":null},$attribute$$;for($attribute$$ in $WebPushConfigAttributes$$module$extensions$amp_web_push$0_1$amp_web_push_config$$){var $value$jscomp$94$$=$WebPushConfigAttributes$$module$extensions$amp_web_push$0_1$amp_web_push_config$$[$attribute$$],$JSCompiler_shouldBeTrueish$jscomp$inline_75$$=this.element.getAttribute($value$jscomp$94$$)||"service-worker-scope"===$value$jscomp$94$$;$user$$module$src$log$$().assert($JSCompiler_shouldBeTrueish$jscomp$inline_75$$,
"The "+$value$jscomp$94$$+" attribute is required for <amp-web-push>",void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0);$config$jscomp$2$$[$value$jscomp$94$$]=this.element.getAttribute($value$jscomp$94$$)}if(!$JSCompiler_StaticMethods_isValidHelperOrPermissionDialogUrl_$$($config$jscomp$2$$["helper-iframe-url"]))throw $user$$module$src$log$$().createError("<amp-web-push> must have a valid helper-iframe-url attribute. It should begin with the https:// protocol and point to the provided lightweight template page provided for AMP messaging.");
if(!$JSCompiler_StaticMethods_isValidHelperOrPermissionDialogUrl_$$($config$jscomp$2$$["permission-dialog-url"]))throw $user$$module$src$log$$().createError("<amp-web-push> must have a valid permission-dialog-url attribute. It should begin with the https:// protocol and point to the provided template page for showing the permission prompt.");if("https:"!==$parseUrlDeprecated$$module$src$url$$($config$jscomp$2$$["service-worker-url"]).protocol)throw $user$$module$src$log$$().createError("<amp-web-push> must have a valid service-worker-url attribute. It should begin with the https:// protocol and point to the service worker JavaScript file to be installed.");
if($parseUrlDeprecated$$module$src$url$$($config$jscomp$2$$["service-worker-url"]).origin!==$parseUrlDeprecated$$module$src$url$$($config$jscomp$2$$["permission-dialog-url"]).origin||$parseUrlDeprecated$$module$src$url$$($config$jscomp$2$$["permission-dialog-url"]).origin!==$parseUrlDeprecated$$module$src$url$$($config$jscomp$2$$["helper-iframe-url"]).origin)throw $user$$module$src$log$$().createError("<amp-web-push> URL attributes service-worker-url, permission-dialog-url, and helper-iframe-url must all share the same origin.");
};$JSCompiler_prototypeAlias$$.parseConfig=function(){var $config$jscomp$3$$={},$attribute$jscomp$1$$;for($attribute$jscomp$1$$ in $WebPushConfigAttributes$$module$extensions$amp_web_push$0_1$amp_web_push_config$$){var $value$jscomp$95$$=$WebPushConfigAttributes$$module$extensions$amp_web_push$0_1$amp_web_push_config$$[$attribute$jscomp$1$$];$config$jscomp$3$$[$value$jscomp$95$$]=this.element.getAttribute($value$jscomp$95$$)}return $config$jscomp$3$$};
$JSCompiler_prototypeAlias$$.buildCallback=function(){this.validate();var $config$jscomp$4$$=this.parseConfig(),$webPushService$$=$getServiceForDoc$$module$src$service$$(this.getAmpDoc());$webPushService$$.start($config$jscomp$4$$).catch(function(){});this.registerAction("subscribe",this.$onSubscribe_$.bind(this));this.registerAction("unsubscribe",this.$onUnsubscribe_$.bind(this))};
$JSCompiler_prototypeAlias$$.$onSubscribe_$=function($invocation$$){var $widget$$=$invocation$$.event.target;$widget$$.disabled=!0;$getServiceForDoc$$module$src$service$$(this.getAmpDoc()).subscribe(function(){$widget$$.disabled=!1}).then(function(){$widget$$.disabled=!1})};
$JSCompiler_prototypeAlias$$.$onUnsubscribe_$=function($invocation$jscomp$1$$){var $widget$jscomp$2$$=$invocation$jscomp$1$$.event.target;$widget$jscomp$2$$.disabled=!0;$getServiceForDoc$$module$src$service$$(this.getAmpDoc()).unsubscribe().then(function(){$widget$jscomp$2$$.disabled=!1})};
function $JSCompiler_StaticMethods_isValidHelperOrPermissionDialogUrl_$$($url$jscomp$40$$){try{var $parsedUrl$jscomp$1$$=$parseUrlDeprecated$$module$src$url$$($url$jscomp$40$$),$isNotRootUrl$$=1<$parsedUrl$jscomp$1$$.pathname.length,$isSecureUrl$$="https:"===$parsedUrl$jscomp$1$$.protocol;return $isSecureUrl$$&&$isNotRootUrl$$}catch($e$jscomp$14$$){return!1}};var $optsSupported$$module$src$event_helper_listen$$;
function $internalListenImplementation$$module$src$event_helper_listen$$($element$jscomp$14$$,$eventType$jscomp$3$$,$listener$jscomp$62$$){var $opt_evtListenerOpts$$=void 0,$localElement$$=$element$jscomp$14$$,$localListener$$=$listener$jscomp$62$$;var $wrapped$$=function($element$jscomp$14$$){try{return $localListener$$($element$jscomp$14$$)}catch($e$jscomp$15$$){throw self.reportError($e$jscomp$15$$),$e$jscomp$15$$;}};var $optsSupported$$=$detectEvtListenerOptsSupport$$module$src$event_helper_listen$$(),$capture$$=
!1;$opt_evtListenerOpts$$&&($capture$$=$opt_evtListenerOpts$$.capture);$localElement$$.addEventListener($eventType$jscomp$3$$,$wrapped$$,$optsSupported$$?$opt_evtListenerOpts$$:$capture$$);return function(){$localElement$$&&$localElement$$.removeEventListener($eventType$jscomp$3$$,$wrapped$$,$optsSupported$$?$opt_evtListenerOpts$$:$capture$$);$wrapped$$=$localElement$$=$localListener$$=null}}
function $detectEvtListenerOptsSupport$$module$src$event_helper_listen$$(){if(void 0!==$optsSupported$$module$src$event_helper_listen$$)return $optsSupported$$module$src$event_helper_listen$$;$optsSupported$$module$src$event_helper_listen$$=!1;try{var $options$jscomp$14$$={get capture(){$optsSupported$$module$src$event_helper_listen$$=!0}};self.addEventListener("test-options",null,$options$jscomp$14$$);self.removeEventListener("test-options",null,$options$jscomp$14$$)}catch($err$jscomp$3$$){}return $optsSupported$$module$src$event_helper_listen$$}
;function $listenOnce$$module$src$event_helper$$($element$jscomp$16$$,$eventType$jscomp$5$$,$listener$jscomp$64$$){var $localListener$jscomp$1$$=$listener$jscomp$64$$,$unlisten$$=$internalListenImplementation$$module$src$event_helper_listen$$($element$jscomp$16$$,$eventType$jscomp$5$$,function($element$jscomp$16$$){try{$localListener$jscomp$1$$($element$jscomp$16$$)}finally{$localListener$jscomp$1$$=null,$unlisten$$()}});return $unlisten$$}
function $loadPromise$$module$src$event_helper$$($eleOrWindow$jscomp$1$$){var $unlistenLoad$$,$unlistenError$$;if($eleOrWindow$jscomp$1$$.complete||"complete"==$eleOrWindow$jscomp$1$$.readyState||$eleOrWindow$jscomp$1$$.document&&"complete"==$eleOrWindow$jscomp$1$$.document.readyState)return Promise.resolve($eleOrWindow$jscomp$1$$);var $loadingPromise$$=new Promise(function($loadingPromise$$,$reject$jscomp$4$$){var $resolve$jscomp$6$$=$eleOrWindow$jscomp$1$$.tagName;$unlistenLoad$$="AUDIO"===$resolve$jscomp$6$$||
"VIDEO"===$resolve$jscomp$6$$?$listenOnce$$module$src$event_helper$$($eleOrWindow$jscomp$1$$,"loadstart",$loadingPromise$$):$listenOnce$$module$src$event_helper$$($eleOrWindow$jscomp$1$$,"load",$loadingPromise$$);$resolve$jscomp$6$$&&($unlistenError$$=$listenOnce$$module$src$event_helper$$($eleOrWindow$jscomp$1$$,"error",$reject$jscomp$4$$))});return $loadingPromise$$.then(function(){$unlistenError$$&&$unlistenError$$();return $eleOrWindow$jscomp$1$$},function(){$unlistenLoad$$&&$unlistenLoad$$();
var $unlistenError$$=$eleOrWindow$jscomp$1$$;$unlistenError$$&&$unlistenError$$.src&&($unlistenError$$=$unlistenError$$.src);throw $user$$module$src$log$$().createError("Failed to load:",$unlistenError$$);})};function $IFrameHost$$module$extensions$amp_web_push$0_1$iframehost$$($ampdoc$jscomp$7$$,$url$jscomp$41$$){this.$ampdoc_$=$ampdoc$jscomp$7$$;this.$url_$=$url$jscomp$41$$;this.$domElement_$=null;this.$loadPromise_$=new Promise(function(){})}
$IFrameHost$$module$extensions$amp_web_push$0_1$iframehost$$.prototype.load=function(){var $$jscomp$this$jscomp$3$$=this;return this.$ampdoc_$.whenReady().then(function(){$$jscomp$this$jscomp$3$$.$domElement_$=$$jscomp$this$jscomp$3$$.$ampdoc_$.win.document.createElement("iframe");var $JSCompiler_element$jscomp$inline_110$$=$$jscomp$this$jscomp$3$$.$domElement_$,$JSCompiler_opt_display$jscomp$inline_111$$=!1;void 0===$JSCompiler_opt_display$jscomp$inline_111$$&&($JSCompiler_opt_display$jscomp$inline_111$$=
$JSCompiler_element$jscomp$inline_110$$.hasAttribute("hidden"));$JSCompiler_opt_display$jscomp$inline_111$$?$JSCompiler_element$jscomp$inline_110$$.removeAttribute("hidden"):$JSCompiler_element$jscomp$inline_110$$.setAttribute("hidden","");$$jscomp$this$jscomp$3$$.$domElement_$.sandbox="allow-same-origin allow-scripts";$$jscomp$this$jscomp$3$$.$domElement_$.src=$$jscomp$this$jscomp$3$$.$url_$;$$jscomp$this$jscomp$3$$.$ampdoc_$.getBody().appendChild($$jscomp$this$jscomp$3$$.$domElement_$);$$jscomp$this$jscomp$3$$.$loadPromise_$=
$loadPromise$$module$src$event_helper$$($$jscomp$this$jscomp$3$$.$domElement_$);return $$jscomp$this$jscomp$3$$.whenReady()})};$IFrameHost$$module$extensions$amp_web_push$0_1$iframehost$$.prototype.getDomElement=function(){return this.$domElement_$};$IFrameHost$$module$extensions$amp_web_push$0_1$iframehost$$.prototype.whenReady=function(){return this.$loadPromise_$};function $WebPushWidget$$module$extensions$amp_web_push$0_1$amp_web_push_widget$$($element$jscomp$70$$){return AMP.BaseElement.call(this,$element$jscomp$70$$)||this}$$jscomp$inherits$$($WebPushWidget$$module$extensions$amp_web_push$0_1$amp_web_push_widget$$,AMP.BaseElement);$WebPushWidget$$module$extensions$amp_web_push$0_1$amp_web_push_widget$$.prototype.isLayoutSupported=function($layout$jscomp$3$$){return"fixed"==$layout$jscomp$3$$};
$WebPushWidget$$module$extensions$amp_web_push$0_1$amp_web_push_widget$$.prototype.buildCallback=function(){this.element.classList.add("amp-invisible")};function $WindowMessenger$$module$extensions$amp_web_push$0_1$window_messenger$$($options$jscomp$15$$){$options$jscomp$15$$||($options$jscomp$15$$={debug:!1,windowContext:window});this.$messages_$={};this.$listeners_$={};this.$debug_$=$options$jscomp$15$$.debug;this.$connected_$=this.$connecting_$=this.$listening_$=!1;this.$onChannelMessageReceivedProc_$=this.$onConnectConnectionMessageReceivedProc_$=this.$onListenConnectionMessageReceivedProc_$=this.$messagePort_$=this.$channel_$=null;this.$window_$=
$options$jscomp$15$$.windowContext||window}$JSCompiler_prototypeAlias$$=$WindowMessenger$$module$extensions$amp_web_push$0_1$window_messenger$$.prototype;
$JSCompiler_prototypeAlias$$.listen=function($allowedOrigins$$){var $$jscomp$this$jscomp$4$$=this;return(new Promise(function($resolve$jscomp$12$$,$reject$jscomp$5$$){$$jscomp$this$jscomp$4$$.$connected_$?$reject$jscomp$5$$(Error("Already connected.")):$$jscomp$this$jscomp$4$$.$listening_$?$reject$jscomp$5$$(Error("Already listening for connections.")):Array.isArray($allowedOrigins$$)?($$jscomp$this$jscomp$4$$.$onListenConnectionMessageReceivedProc_$=$$jscomp$this$jscomp$4$$.$onListenConnectionMessageReceived_$.bind($$jscomp$this$jscomp$4$$,
$allowedOrigins$$,$resolve$jscomp$12$$,$reject$jscomp$5$$),$$jscomp$this$jscomp$4$$.$window_$.addEventListener("message",$$jscomp$this$jscomp$4$$.$onListenConnectionMessageReceivedProc_$)):$reject$jscomp$5$$(Error("allowedOrigins should be a string array of allowed origins to accept messages from. Got:",$allowedOrigins$$))})).then(function(){$$jscomp$this$jscomp$4$$.send($WindowMessenger$$module$extensions$amp_web_push$0_1$window_messenger$$.Topics.CONNECT_HANDSHAKE,null);$$jscomp$this$jscomp$4$$.$connected_$=
!0})};
$JSCompiler_prototypeAlias$$.$onListenConnectionMessageReceived_$=function($JSCompiler_inline_result$jscomp$23_allowedOrigins$jscomp$2$$,$resolvePromise$$,$rejectPromise$$,$messageChannelEvent$$){var $message$jscomp$30$$=$messageChannelEvent$$.data,$$jscomp$destructuring$var14_JSCompiler_normalizedOrigin$jscomp$inline_116$$=$messageChannelEvent$$,$messagePorts$$=$$jscomp$destructuring$var14_JSCompiler_normalizedOrigin$jscomp$inline_116$$.ports;a:{$$jscomp$destructuring$var14_JSCompiler_normalizedOrigin$jscomp$inline_116$$=$parseUrlDeprecated$$module$src$url$$($$jscomp$destructuring$var14_JSCompiler_normalizedOrigin$jscomp$inline_116$$.origin).origin;
for(var $JSCompiler_i$jscomp$inline_117$$=0;$JSCompiler_i$jscomp$inline_117$$<$JSCompiler_inline_result$jscomp$23_allowedOrigins$jscomp$2$$.length;$JSCompiler_i$jscomp$inline_117$$++)if($parseUrlDeprecated$$module$src$url$$($JSCompiler_inline_result$jscomp$23_allowedOrigins$jscomp$2$$[$JSCompiler_i$jscomp$inline_117$$]).origin===$$jscomp$destructuring$var14_JSCompiler_normalizedOrigin$jscomp$inline_116$$){$JSCompiler_inline_result$jscomp$23_allowedOrigins$jscomp$2$$=!0;break a}$JSCompiler_inline_result$jscomp$23_allowedOrigins$jscomp$2$$=
!1}$JSCompiler_inline_result$jscomp$23_allowedOrigins$jscomp$2$$&&$message$jscomp$30$$&&$message$jscomp$30$$.topic===$WindowMessenger$$module$extensions$amp_web_push$0_1$window_messenger$$.Topics.CONNECT_HANDSHAKE&&(this.$window_$.removeEventListener("message",this.$onListenConnectionMessageReceivedProc_$),this.$messagePort_$=$messagePorts$$[0],this.$onChannelMessageReceivedProc_$=this.$onChannelMessageReceived_$.bind(this),this.$messagePort_$.addEventListener("message",this.$onChannelMessageReceivedProc_$,
!1),this.$messagePort_$.start(),$resolvePromise$$())};
$JSCompiler_prototypeAlias$$.connect=function($remoteWindowContext$$,$expectedRemoteOrigin$$){var $$jscomp$this$jscomp$5$$=this;return new Promise(function($resolve$jscomp$13$$,$reject$jscomp$6$$){$remoteWindowContext$$||$reject$jscomp$6$$(Error("Provide a valid Window context to connect to."));$expectedRemoteOrigin$$||$reject$jscomp$6$$(Error("Provide an expected origin for the remote Window or provide the wildcard *."));$$jscomp$this$jscomp$5$$.$connected_$?$reject$jscomp$6$$(Error("Already connected.")):
$$jscomp$this$jscomp$5$$.$connecting_$?$reject$jscomp$6$$(Error("Already connecting.")):($$jscomp$this$jscomp$5$$.$channel_$=new MessageChannel,$$jscomp$this$jscomp$5$$.$messagePort_$=$$jscomp$this$jscomp$5$$.$channel_$.port1,$$jscomp$this$jscomp$5$$.$onConnectConnectionMessageReceivedProc_$=$$jscomp$this$jscomp$5$$.$onConnectConnectionMessageReceived_$.bind($$jscomp$this$jscomp$5$$,$$jscomp$this$jscomp$5$$.$messagePort_$,$expectedRemoteOrigin$$,$resolve$jscomp$13$$),$$jscomp$this$jscomp$5$$.$messagePort_$.addEventListener("message",
$$jscomp$this$jscomp$5$$.$onConnectConnectionMessageReceivedProc_$),$$jscomp$this$jscomp$5$$.$messagePort_$.start(),$remoteWindowContext$$.postMessage({topic:$WindowMessenger$$module$extensions$amp_web_push$0_1$window_messenger$$.Topics.CONNECT_HANDSHAKE},"*"===$expectedRemoteOrigin$$?"*":$parseUrlDeprecated$$module$src$url$$($expectedRemoteOrigin$$).origin,[$$jscomp$this$jscomp$5$$.$channel_$.port2]))})};
$JSCompiler_prototypeAlias$$.$onConnectConnectionMessageReceived_$=function($messagePort$$,$expectedRemoteOrigin$jscomp$1$$,$resolvePromise$jscomp$1$$){this.$connected_$=!0;$messagePort$$.removeEventListener("message",this.$onConnectConnectionMessageReceivedProc_$);this.$onChannelMessageReceivedProc_$=this.$onChannelMessageReceived_$.bind(this);$messagePort$$.addEventListener("message",this.$onChannelMessageReceivedProc_$,!1);$resolvePromise$jscomp$1$$()};
$JSCompiler_prototypeAlias$$.$onChannelMessageReceived_$=function($event$jscomp$9_message$jscomp$31$$){$event$jscomp$9_message$jscomp$31$$=$event$jscomp$9_message$jscomp$31$$.data;if(this.$messages_$[$event$jscomp$9_message$jscomp$31$$.id]&&$event$jscomp$9_message$jscomp$31$$.isReply){var $existingMessage$$=this.$messages_$[$event$jscomp$9_message$jscomp$31$$.id];delete this.$messages_$[$event$jscomp$9_message$jscomp$31$$.id];var $promiseResolver$$=$existingMessage$$.promiseResolver;$existingMessage$$.message=
$event$jscomp$9_message$jscomp$31$$.data;$promiseResolver$$([$event$jscomp$9_message$jscomp$31$$.data,this.$sendReply_$.bind(this,$event$jscomp$9_message$jscomp$31$$.id,$existingMessage$$.topic)])}else{var $listeners$$=this.$listeners_$[$event$jscomp$9_message$jscomp$31$$.topic];if($listeners$$)for(var $i$jscomp$17$$=0;$i$jscomp$17$$<$listeners$$.length;$i$jscomp$17$$++)(0,$listeners$$[$i$jscomp$17$$])($event$jscomp$9_message$jscomp$31$$.data,this.$sendReply_$.bind(this,$event$jscomp$9_message$jscomp$31$$.id,
$event$jscomp$9_message$jscomp$31$$.topic))}};$JSCompiler_prototypeAlias$$.on=function($topic$$,$callback$jscomp$66$$){this.$listeners_$[$topic$$]?this.$listeners_$[$topic$$].push($callback$jscomp$66$$):this.$listeners_$[$topic$$]=[$callback$jscomp$66$$]};
$JSCompiler_prototypeAlias$$.off=function($topic$jscomp$1$$,$callback$jscomp$67$$){if($callback$jscomp$67$$){var $callbackIndex$$=this.$listeners_$[$topic$jscomp$1$$].indexOf($callback$jscomp$67$$);-1!==$callbackIndex$$&&this.$listeners_$[$topic$jscomp$1$$].splice($callbackIndex$$,1)}else this.$listeners_$[$topic$jscomp$1$$]&&delete this.$listeners_$[$topic$jscomp$1$$]};
$JSCompiler_prototypeAlias$$.$sendReply_$=function($id$jscomp$35$$,$topic$jscomp$2$$,$data$jscomp$57$$){var $$jscomp$this$jscomp$6$$=this,$payload$jscomp$1$$={id:$id$jscomp$35$$,topic:$topic$jscomp$2$$,data:$data$jscomp$57$$,isReply:!0};this.$messagePort_$.postMessage($payload$jscomp$1$$);return new Promise(function($id$jscomp$35$$){$$jscomp$this$jscomp$6$$.$messages_$[$payload$jscomp$1$$.id]={message:$data$jscomp$57$$,topic:$topic$jscomp$2$$,promiseResolver:$id$jscomp$35$$}})};
$JSCompiler_prototypeAlias$$.send=function($topic$jscomp$3$$,$data$jscomp$58$$){var $$jscomp$this$jscomp$7$$=this,$payload$jscomp$2$$={id:crypto.getRandomValues(new Uint8Array(10)).join(""),topic:$topic$jscomp$3$$,data:$data$jscomp$58$$};this.$messagePort_$.postMessage($payload$jscomp$2$$);return new Promise(function($resolve$jscomp$15$$){$$jscomp$this$jscomp$7$$.$messages_$[$payload$jscomp$2$$.id]={message:$data$jscomp$58$$,topic:$topic$jscomp$3$$,promiseResolver:$resolve$jscomp$15$$}})};
$$jscomp$global$$.Object.defineProperties($WindowMessenger$$module$extensions$amp_web_push$0_1$window_messenger$$,{Topics:{configurable:!0,enumerable:!0,get:function(){return{CONNECT_HANDSHAKE:"topic-connect-handshake",NOTIFICATION_PERMISSION_STATE:"topic-notification-permission-state",SERVICE_WORKER_STATE:"topic-service-worker-state",SERVICE_WORKER_REGISTRATION:"topic-service-worker-registration",SERVICE_WORKER_QUERY:"topic-service-worker-query",STORAGE_GET:"topic-storage-get"}}}});function $installStylesForDoc$$module$src$style_installer$$($ampdoc$jscomp$11$$,$cb$jscomp$1$$){var $cssText$$="amp-web-push-widget.amp-invisible{visibility:hidden}\n/*# sourceURL=/extensions/amp-web-push/0.1/amp-web-push.css*/",$opt_isRuntimeCss$$=!1,$opt_ext$$="amp-web-push",$cssRoot$$=$ampdoc$jscomp$11$$.getHeadNode(),$style$jscomp$6$$=$insertStyleElement$$module$src$style_installer$$($cssRoot$$,$maybeTransform$$module$src$style_installer$$($cssRoot$$,$cssText$$),$opt_isRuntimeCss$$||!1,$opt_ext$$||
null);if($cb$jscomp$1$$){var $rootNode$jscomp$1$$=$ampdoc$jscomp$11$$.getRootNode();if($styleLoaded$$module$src$style_installer$$($rootNode$jscomp$1$$,$style$jscomp$6$$))$cb$jscomp$1$$($style$jscomp$6$$);else var $interval$jscomp$1$$=setInterval(function(){$styleLoaded$$module$src$style_installer$$($rootNode$jscomp$1$$,$style$jscomp$6$$)&&(clearInterval($interval$jscomp$1$$),$cb$jscomp$1$$($style$jscomp$6$$))},4)}}
function $insertStyleElement$$module$src$style_installer$$($cssRoot$jscomp$1$$,$JSCompiler_after$jscomp$inline_125_cssText$jscomp$2$$,$isRuntimeCss$$,$ext$$){var $styleMap$$=$cssRoot$jscomp$1$$.__AMP_CSS_SM;if(!$styleMap$$){var $JSCompiler_obj$jscomp$inline_121_key$jscomp$48$$=Object.create(null);$styleMap$$=$cssRoot$jscomp$1$$.__AMP_CSS_SM=$JSCompiler_obj$jscomp$inline_121_key$jscomp$48$$}var $isExtCss$$=!$isRuntimeCss$$&&$ext$$&&"amp-custom"!=$ext$$&&"amp-keyframes"!=$ext$$;if($JSCompiler_obj$jscomp$inline_121_key$jscomp$48$$=
$isRuntimeCss$$?"amp-runtime":$isExtCss$$?"amp-extension="+$ext$$:null){var $existing$$=$getExistingStyleElement$$module$src$style_installer$$($cssRoot$jscomp$1$$,$styleMap$$,$JSCompiler_obj$jscomp$inline_121_key$jscomp$48$$);if($existing$$)return $existing$$.textContent!==$JSCompiler_after$jscomp$inline_125_cssText$jscomp$2$$&&($existing$$.textContent=$JSCompiler_after$jscomp$inline_125_cssText$jscomp$2$$),$existing$$}var $style$jscomp$8$$=($cssRoot$jscomp$1$$.ownerDocument||$cssRoot$jscomp$1$$).createElement("style");
$style$jscomp$8$$.textContent=$JSCompiler_after$jscomp$inline_125_cssText$jscomp$2$$;var $afterElement$$=null;$isRuntimeCss$$?$style$jscomp$8$$.setAttribute("amp-runtime",""):$isExtCss$$?($style$jscomp$8$$.setAttribute("amp-extension",$ext$$||""),$afterElement$$=$getExistingStyleElement$$module$src$style_installer$$($cssRoot$jscomp$1$$,$styleMap$$,"amp-runtime")):($ext$$&&$style$jscomp$8$$.setAttribute($ext$$,""),$afterElement$$=$cssRoot$jscomp$1$$.lastChild);$JSCompiler_after$jscomp$inline_125_cssText$jscomp$2$$=
$afterElement$$;$cssRoot$jscomp$1$$.insertBefore($style$jscomp$8$$,$JSCompiler_after$jscomp$inline_125_cssText$jscomp$2$$?$JSCompiler_after$jscomp$inline_125_cssText$jscomp$2$$.nextSibling:$cssRoot$jscomp$1$$.firstChild);$JSCompiler_obj$jscomp$inline_121_key$jscomp$48$$&&($styleMap$$[$JSCompiler_obj$jscomp$inline_121_key$jscomp$48$$]=$style$jscomp$8$$);return $style$jscomp$8$$}
function $getExistingStyleElement$$module$src$style_installer$$($cssRoot$jscomp$2_existing$jscomp$1$$,$styleMap$jscomp$1$$,$key$jscomp$49$$){return $styleMap$jscomp$1$$[$key$jscomp$49$$]?$styleMap$jscomp$1$$[$key$jscomp$49$$]:($cssRoot$jscomp$2_existing$jscomp$1$$=$cssRoot$jscomp$2_existing$jscomp$1$$.querySelector("style["+$key$jscomp$49$$+"]"))?$styleMap$jscomp$1$$[$key$jscomp$49$$]=$cssRoot$jscomp$2_existing$jscomp$1$$:null}
function $maybeTransform$$module$src$style_installer$$($cssRoot$jscomp$4_transformer$jscomp$1$$,$cssText$jscomp$3$$){return($cssRoot$jscomp$4_transformer$jscomp$1$$=$cssRoot$jscomp$4_transformer$jscomp$1$$.__AMP_CSS_TR)?$cssRoot$jscomp$4_transformer$jscomp$1$$($cssText$jscomp$3$$):$cssText$jscomp$3$$}
function $styleLoaded$$module$src$style_installer$$($doc$jscomp$23_i$jscomp$18$$,$style$jscomp$9$$){var $sheets$$=$doc$jscomp$23_i$jscomp$18$$.styleSheets;for($doc$jscomp$23_i$jscomp$18$$=0;$doc$jscomp$23_i$jscomp$18$$<$sheets$$.length;$doc$jscomp$23_i$jscomp$18$$++){var $sheet$$=$sheets$$[$doc$jscomp$23_i$jscomp$18$$];if($sheet$$.ownerNode==$style$jscomp$9$$)return!0}return!1};function $WebPushService$$module$extensions$amp_web_push$0_1$web_push_service$$($ampdoc$jscomp$12$$){this.ampdoc=$ampdoc$jscomp$12$$;$installStylesForDoc$$module$src$style_installer$$($ampdoc$jscomp$12$$,function(){});this.$config_$={"helper-iframe-url":null,"permission-dialog-url":null,"service-worker-url":null,debug:null};this.$debug_$=$getMode$$module$src$mode$$().development;this.$lastKnownPermission_$=this.$iframe_$=null;this.$frameMessenger_$=new $WindowMessenger$$module$extensions$amp_web_push$0_1$window_messenger$$({debug:this.$debug_$});
this.$popupMessenger_$=null}$JSCompiler_prototypeAlias$$=$WebPushService$$module$extensions$amp_web_push$0_1$web_push_service$$.prototype;
$JSCompiler_prototypeAlias$$.start=function($configJson$$){var $$jscomp$this$jscomp$8$$=this;if(!this.environmentSupportsWebPush())return $user$$module$src$log$$().warn("amp-web-push","Web push is not supported."),Promise.reject("Web push is not supported");this.initializeConfig($configJson$$);var $iframeLoadPromise$$=this.installHelperFrame();$iframeLoadPromise$$.then(function(){return $$jscomp$this$jscomp$8$$.$frameMessenger_$.connect($$jscomp$this$jscomp$8$$.$iframe_$.getDomElement().contentWindow,$parseUrlDeprecated$$module$src$url$$($$jscomp$this$jscomp$8$$.$config_$["helper-iframe-url"]).origin)}).then(function(){if($$jscomp$this$jscomp$8$$.isContinuingSubscriptionFromRedirect())$JSCompiler_StaticMethods_resumeSubscribingForPushNotifications_$$($$jscomp$this$jscomp$8$$);
else return $$jscomp$this$jscomp$8$$.updateWidgetVisibilities()});return $iframeLoadPromise$$};$JSCompiler_prototypeAlias$$.initializeConfig=function($configJson$jscomp$1$$){this.$config_$=$configJson$jscomp$1$$};
$JSCompiler_prototypeAlias$$.installHelperFrame=function(){var $helperUrlHasQueryParams$$=-1!==this.$config_$["helper-iframe-url"].indexOf("?"),$helperUrlQueryParamPrefix$$=$helperUrlHasQueryParams$$?"&":"?",$finalIframeUrl$$=""+this.$config_$["helper-iframe-url"]+$helperUrlQueryParamPrefix$$+("parentOrigin="+this.ampdoc.win.location.origin);this.$iframe_$=new $IFrameHost$$module$extensions$amp_web_push$0_1$iframehost$$(this.ampdoc,$finalIframeUrl$$);return this.$iframe_$.load()};
$JSCompiler_prototypeAlias$$.isContinuingSubscriptionFromRedirect=function(){return-1!==(this.ampdoc.win.testLocation||this.ampdoc.win.location).search.indexOf($WebPushService$$module$extensions$amp_web_push$0_1$web_push_service$$.PERMISSION_POPUP_URL_FRAGMENT)};
$JSCompiler_prototypeAlias$$.removePermissionPopupUrlFragmentFromUrl=function($url$jscomp$43$$){var $urlWithoutFragment$$=$url$jscomp$43$$.replace("?"+$WebPushService$$module$extensions$amp_web_push$0_1$web_push_service$$.PERMISSION_POPUP_URL_FRAGMENT,"");return $urlWithoutFragment$$=$urlWithoutFragment$$.replace("&"+$WebPushService$$module$extensions$amp_web_push$0_1$web_push_service$$.PERMISSION_POPUP_URL_FRAGMENT,"")};
function $JSCompiler_StaticMethods_queryHelperFrame_$$($JSCompiler_StaticMethods_queryHelperFrame_$self$$,$messageTopic$$,$message$jscomp$32$$){return $JSCompiler_StaticMethods_queryHelperFrame_$self$$.$iframe_$.whenReady().then(function(){return $JSCompiler_StaticMethods_queryHelperFrame_$self$$.$frameMessenger_$.send($messageTopic$$,$message$jscomp$32$$)}).then(function($JSCompiler_StaticMethods_queryHelperFrame_$self$$){var $result$jscomp$1$$=$JSCompiler_StaticMethods_queryHelperFrame_$self$$[0];
if($result$jscomp$1$$.success)return $result$jscomp$1$$.result;throw Error("AMP page helper iframe query topic "+$messageTopic$$+" "+("and message "+$message$jscomp$32$$+" failed with: "+$result$jscomp$1$$.error));})}
function $JSCompiler_StaticMethods_queryServiceWorker_$$($JSCompiler_StaticMethods_queryServiceWorker_$self$$,$messageTopic$jscomp$1$$){return $JSCompiler_StaticMethods_queryHelperFrame_$$($JSCompiler_StaticMethods_queryServiceWorker_$self$$,$WindowMessenger$$module$extensions$amp_web_push$0_1$window_messenger$$.Topics.SERVICE_WORKER_QUERY,{topic:$messageTopic$jscomp$1$$,payload:null})}
$JSCompiler_prototypeAlias$$.queryNotificationPermission=function(){return $JSCompiler_StaticMethods_queryHelperFrame_$$(this,$WindowMessenger$$module$extensions$amp_web_push$0_1$window_messenger$$.Topics.NOTIFICATION_PERMISSION_STATE,null)};
$JSCompiler_prototypeAlias$$.registerServiceWorker=function(){var $swUrl$$=this.$config_$["service-worker-url"],$swScope$$=this.$config_$["service-worker-scope"];return $JSCompiler_StaticMethods_queryHelperFrame_$$(this,$WindowMessenger$$module$extensions$amp_web_push$0_1$window_messenger$$.Topics.SERVICE_WORKER_REGISTRATION,{workerUrl:$swUrl$$,registrationOptions:$swScope$$?{scope:$swScope$$}:{}})};
$JSCompiler_prototypeAlias$$.querySubscriptionStateRemotely=function(){return $JSCompiler_StaticMethods_queryServiceWorker_$$(this,"amp-web-push-subscription-state")};$JSCompiler_prototypeAlias$$.subscribeForPushRemotely=function(){return $JSCompiler_StaticMethods_queryServiceWorker_$$(this,"amp-web-push-subscribe")};$JSCompiler_prototypeAlias$$.unsubscribeFromPushRemotely=function(){return $JSCompiler_StaticMethods_queryServiceWorker_$$(this,"amp-web-push-unsubscribe")};
$JSCompiler_prototypeAlias$$.isServiceWorkerActivated=function(){var $$jscomp$this$jscomp$10$$=this,$self$jscomp$1$$=this;return $JSCompiler_StaticMethods_queryHelperFrame_$$(this,$WindowMessenger$$module$extensions$amp_web_push$0_1$window_messenger$$.Topics.SERVICE_WORKER_STATE,null).then(function($serviceWorkerState$$){var $isControllingFrame$$=!0===$serviceWorkerState$$.isControllingFrame,$serviceWorkerHasCorrectUrl$$=$$jscomp$this$jscomp$10$$.isUrlSimilarForQueryParams($serviceWorkerState$$.url,
$self$jscomp$1$$.$config_$["service-worker-url"]),$serviceWorkerActivated$$="activated"===$serviceWorkerState$$.state;return $isControllingFrame$$&&$serviceWorkerHasCorrectUrl$$&&$serviceWorkerActivated$$})};
$JSCompiler_prototypeAlias$$.isUrlSimilarForQueryParams=function($originalUrlString$$,$urlToTestString$$){var $originalUrl$$=$parseUrlDeprecated$$module$src$url$$($originalUrlString$$),$originalUrlQueryParams$$=$parseQueryString_$$module$src$url_parse_query_string$$($originalUrl$$.search),$urlToTest$$=$parseUrlDeprecated$$module$src$url$$($urlToTestString$$),$urlToTestQueryParams$$=$parseQueryString_$$module$src$url_parse_query_string$$($urlToTest$$.search),$originalKey$$;for($originalKey$$ in $originalUrlQueryParams$$)if($urlToTestQueryParams$$[$originalKey$$]!==
$originalUrlQueryParams$$[$originalKey$$])return!1;return $originalUrl$$.origin===$urlToTest$$.origin&&$originalUrl$$.pathname===$urlToTest$$.pathname};
$JSCompiler_prototypeAlias$$.setWidgetVisibilities=function($widgetCategoryName$$,$isVisible$$){for(var $widgetDomElements$$=this.ampdoc.getRootNode().querySelectorAll($cssEscape$$module$third_party$css_escape$css_escape$$("amp-web-push-widget")+"[visibility="+$cssEscape$$module$third_party$css_escape$css_escape$$($widgetCategoryName$$)+"]"),$invisibilityCssClassName$$="amp-invisible",$i$jscomp$19$$=0;$i$jscomp$19$$<$widgetDomElements$$.length;$i$jscomp$19$$++){var $widgetDomElement$$=$widgetDomElements$$[$i$jscomp$19$$];
$isVisible$$?$widgetDomElement$$.classList.remove($invisibilityCssClassName$$):$widgetDomElement$$.classList.add($invisibilityCssClassName$$)}};
function $JSCompiler_StaticMethods_storeLastKnownPermission_$$($JSCompiler_StaticMethods_storeLastKnownPermission_$self$$){return $JSCompiler_StaticMethods_storeLastKnownPermission_$self$$.queryNotificationPermission().then(function($permission$jscomp$1$$){$JSCompiler_StaticMethods_storeLastKnownPermission_$self$$.$lastKnownPermission_$=$permission$jscomp$1$$})}
$JSCompiler_prototypeAlias$$.updateWidgetVisibilities=function(){var $$jscomp$this$jscomp$12$$=this;return $JSCompiler_StaticMethods_storeLastKnownPermission_$$(this).then(function(){return $JSCompiler_StaticMethods_queryHelperFrame_$$($$jscomp$this$jscomp$12$$,$WindowMessenger$$module$extensions$amp_web_push$0_1$window_messenger$$.Topics.NOTIFICATION_PERMISSION_STATE,{isQueryTopicSupported:$WindowMessenger$$module$extensions$amp_web_push$0_1$window_messenger$$.Topics.STORAGE_GET})}).then(function($response$jscomp$2$$){var $isSupported$$=
!0===$response$jscomp$2$$;return $isSupported$$?$JSCompiler_StaticMethods_queryHelperFrame_$$($$jscomp$this$jscomp$12$$,$WindowMessenger$$module$extensions$amp_web_push$0_1$window_messenger$$.Topics.STORAGE_GET,{key:"amp-web-push-notification-permission"}):Promise.resolve("default")}).then(function($canonicalNotificationPermission$$){if("denied"===$canonicalNotificationPermission$$)0<$$jscomp$this$jscomp$12$$.ampdoc.getRootNode().querySelectorAll($cssEscape$$module$third_party$css_escape$css_escape$$("amp-web-push-widget")+
"[visibility="+$cssEscape$$module$third_party$css_escape$css_escape$$("blocked")+"]").length?($$jscomp$this$jscomp$12$$.setWidgetVisibilities("unsubscribed",!1),$$jscomp$this$jscomp$12$$.setWidgetVisibilities("subscribed",!1),$$jscomp$this$jscomp$12$$.setWidgetVisibilities("blocked",!0)):$JSCompiler_StaticMethods_updateWidgetVisibilitiesUnsubscribed_$$($$jscomp$this$jscomp$12$$);else return $$jscomp$this$jscomp$12$$.isServiceWorkerActivated().then(function($canonicalNotificationPermission$$){$canonicalNotificationPermission$$?
$JSCompiler_StaticMethods_updateWidgetVisibilitiesServiceWorkerActivated_$$($$jscomp$this$jscomp$12$$):$JSCompiler_StaticMethods_updateWidgetVisibilitiesUnsubscribed_$$($$jscomp$this$jscomp$12$$)})})};
function $JSCompiler_StaticMethods_updateWidgetVisibilitiesServiceWorkerActivated_$$($JSCompiler_StaticMethods_updateWidgetVisibilitiesServiceWorkerActivated_$self$$){$getService$$module$src$service$$($JSCompiler_StaticMethods_updateWidgetVisibilitiesServiceWorkerActivated_$self$$.ampdoc.win,"timer").timeoutPromise(5E3,$JSCompiler_StaticMethods_updateWidgetVisibilitiesServiceWorkerActivated_$self$$.querySubscriptionStateRemotely().then(function($reply$$){switch("boolean"===typeof $reply$$?1:void 0){case $WebPushService$$module$extensions$amp_web_push$0_1$web_push_service$$.AMP_VERSION_INITIAL:var $isSubscribed$$=
$reply$$;$isSubscribed$$?($JSCompiler_StaticMethods_updateWidgetVisibilitiesServiceWorkerActivated_$self$$.setWidgetVisibilities("unsubscribed",!1),$JSCompiler_StaticMethods_updateWidgetVisibilitiesServiceWorkerActivated_$self$$.setWidgetVisibilities("subscribed",!0),$JSCompiler_StaticMethods_updateWidgetVisibilitiesServiceWorkerActivated_$self$$.setWidgetVisibilities("blocked",!1)):$JSCompiler_StaticMethods_updateWidgetVisibilitiesUnsubscribed_$$($JSCompiler_StaticMethods_updateWidgetVisibilitiesServiceWorkerActivated_$self$$);
break;default:throw $user$$module$src$log$$().createError("The controlling service worker replied to amp-web-push with an unexpected value.");}}),"The controlling service worker does not support amp-web-push.")}
function $JSCompiler_StaticMethods_updateWidgetVisibilitiesUnsubscribed_$$($JSCompiler_StaticMethods_updateWidgetVisibilitiesUnsubscribed_$self$$){$JSCompiler_StaticMethods_updateWidgetVisibilitiesUnsubscribed_$self$$.setWidgetVisibilities("unsubscribed",!0);$JSCompiler_StaticMethods_updateWidgetVisibilitiesUnsubscribed_$self$$.setWidgetVisibilities("subscribed",!1);$JSCompiler_StaticMethods_updateWidgetVisibilitiesUnsubscribed_$self$$.setWidgetVisibilities("blocked",!1)}
$JSCompiler_prototypeAlias$$.subscribe=function($onPopupClosed$$){var $$jscomp$this$jscomp$14$$=this,$promises$jscomp$2$$=[];$promises$jscomp$2$$.push(this.registerServiceWorker());$promises$jscomp$2$$.push(new Promise(function($promises$jscomp$2$$){switch($$jscomp$this$jscomp$14$$.$lastKnownPermission_$){case "granted":return $JSCompiler_StaticMethods_onPermissionGrantedSubscribe_$$($$jscomp$this$jscomp$14$$).then(function(){$promises$jscomp$2$$()});default:var $resolve$jscomp$16$$=$$jscomp$this$jscomp$14$$.openPopupOrRedirect();
$JSCompiler_StaticMethods_checkPermissionDialogClosedInterval_$$($$jscomp$this$jscomp$14$$,$resolve$jscomp$16$$,$onPopupClosed$$);$$jscomp$this$jscomp$14$$.$popupMessenger_$=new $WindowMessenger$$module$extensions$amp_web_push$0_1$window_messenger$$({debug:$$jscomp$this$jscomp$14$$.$debug_$});$$jscomp$this$jscomp$14$$.$popupMessenger_$.listen([$$jscomp$this$jscomp$14$$.$config_$["permission-dialog-url"]]);$$jscomp$this$jscomp$14$$.onPermissionDialogInteracted().then(function($onPopupClosed$$){return $$jscomp$this$jscomp$14$$.handlePermissionDialogInteraction($onPopupClosed$$)}).then(function(){$promises$jscomp$2$$()})}}));
return Promise.all($promises$jscomp$2$$)};
function $JSCompiler_StaticMethods_checkPermissionDialogClosedInterval_$$($JSCompiler_StaticMethods_checkPermissionDialogClosedInterval_$self$$,$permissionDialogWindow$jscomp$1$$,$onPopupClosed$jscomp$1$$){if($permissionDialogWindow$jscomp$1$$&&!$permissionDialogWindow$jscomp$1$$.closed)var $interval$jscomp$3$$=$JSCompiler_StaticMethods_checkPermissionDialogClosedInterval_$self$$.ampdoc.win.setInterval(function(){$permissionDialogWindow$jscomp$1$$.closed&&($onPopupClosed$jscomp$1$$(),$JSCompiler_StaticMethods_checkPermissionDialogClosedInterval_$self$$.ampdoc.win.clearInterval($interval$jscomp$3$$))},
500)}
$JSCompiler_prototypeAlias$$.handlePermissionDialogInteraction=function($reply$jscomp$1_result$jscomp$3$$){var $permission$jscomp$2$$=$reply$jscomp$1_result$jscomp$3$$[0];$reply$jscomp$1_result$jscomp$3$$=$reply$jscomp$1_result$jscomp$3$$[1];switch($permission$jscomp$2$$){case "denied":case "default":return $reply$jscomp$1_result$jscomp$3$$({closeFrame:!0}),this.updateWidgetVisibilities();case "granted":$reply$jscomp$1_result$jscomp$3$$({closeFrame:!0});$JSCompiler_StaticMethods_onPermissionGrantedSubscribe_$$(this);break;
default:throw Error("Unexpected permission value:",$permission$jscomp$2$$);}};function $JSCompiler_StaticMethods_onPermissionGrantedSubscribe_$$($JSCompiler_StaticMethods_onPermissionGrantedSubscribe_$self$$){return $JSCompiler_StaticMethods_onPermissionGrantedSubscribe_$self$$.subscribeForPushRemotely().then(function(){return $JSCompiler_StaticMethods_onPermissionGrantedSubscribe_$self$$.updateWidgetVisibilities()})}
$JSCompiler_prototypeAlias$$.unsubscribe=function(){var $$jscomp$this$jscomp$17$$=this;return this.unsubscribeFromPushRemotely().then(function(){return $$jscomp$this$jscomp$17$$.updateWidgetVisibilities()})};
$JSCompiler_prototypeAlias$$.onPermissionDialogInteracted=function(){var $$jscomp$this$jscomp$18$$=this;return new Promise(function($resolve$jscomp$17$$){$$jscomp$this$jscomp$18$$.$popupMessenger_$.on($WindowMessenger$$module$extensions$amp_web_push$0_1$window_messenger$$.Topics.NOTIFICATION_PERMISSION_STATE,function($$jscomp$this$jscomp$18$$,$replyToFrame$$){$resolve$jscomp$17$$([$$jscomp$this$jscomp$18$$,$replyToFrame$$])})})};
$JSCompiler_prototypeAlias$$.openPopupOrRedirect=function(){var $pageUrlHasQueryParams$$=-1!==this.ampdoc.win.location.href.indexOf("?"),$pageUrlQueryParamPrefix$$=$pageUrlHasQueryParams$$?"&":"?",$returningPopupUrl$$=this.ampdoc.win.location.href+$pageUrlQueryParamPrefix$$+$WebPushService$$module$extensions$amp_web_push$0_1$web_push_service$$.PERMISSION_POPUP_URL_FRAGMENT,$permissionDialogUrlHasQueryParams$$=-1!==this.$config_$["permission-dialog-url"].indexOf("?"),$permissionDialogUrlQueryParamPrefix$$=
$permissionDialogUrlHasQueryParams$$?"&":"?",$openingPopupUrl$$=this.$config_$["permission-dialog-url"]+$permissionDialogUrlQueryParamPrefix$$+("return="+encodeURIComponent($returningPopupUrl$$)),$JSCompiler_w$jscomp$inline_138_JSCompiler_win$jscomp$inline_141$$=Math.floor(Math.min(700,.9*screen.width)),$JSCompiler_h$jscomp$inline_139_JSCompiler_url$jscomp$inline_142$$=Math.floor(Math.min(450,.9*screen.height)),$d$$={w:$JSCompiler_w$jscomp$inline_138_JSCompiler_win$jscomp$inline_141$$,h:$JSCompiler_h$jscomp$inline_139_JSCompiler_url$jscomp$inline_142$$,
x:Math.floor((screen.width-$JSCompiler_w$jscomp$inline_138_JSCompiler_win$jscomp$inline_141$$)/2),y:Math.floor((screen.height-$JSCompiler_h$jscomp$inline_139_JSCompiler_url$jscomp$inline_142$$)/2)},$sizing$$="height="+$d$$.h+",width="+$d$$.w+",left="+$d$$.x+",top="+$d$$.y;$JSCompiler_w$jscomp$inline_138_JSCompiler_win$jscomp$inline_141$$=this.ampdoc.win;$JSCompiler_h$jscomp$inline_139_JSCompiler_url$jscomp$inline_142$$=$openingPopupUrl$$;try{var $JSCompiler_res$jscomp$inline_145$$=$JSCompiler_w$jscomp$inline_138_JSCompiler_win$jscomp$inline_141$$.open($JSCompiler_h$jscomp$inline_139_JSCompiler_url$jscomp$inline_142$$,
"_blank",$sizing$$+",resizable=yes,scrollbars=yes")}catch($JSCompiler_e$jscomp$inline_146$$){$dev$$module$src$log$$().error("DOM","Failed to open url on target: ","_blank",$JSCompiler_e$jscomp$inline_146$$)}$JSCompiler_res$jscomp$inline_145$$||($JSCompiler_res$jscomp$inline_145$$=$JSCompiler_w$jscomp$inline_138_JSCompiler_win$jscomp$inline_141$$.open($JSCompiler_h$jscomp$inline_139_JSCompiler_url$jscomp$inline_142$$,"_top"));return $JSCompiler_res$jscomp$inline_145$$};
function $JSCompiler_StaticMethods_resumeSubscribingForPushNotifications_$$($JSCompiler_StaticMethods_resumeSubscribingForPushNotifications_$self$$){$JSCompiler_StaticMethods_resumeSubscribingForPushNotifications_$self$$.ampdoc.win.history.replaceState(null,"",$JSCompiler_StaticMethods_resumeSubscribingForPushNotifications_$self$$.removePermissionPopupUrlFragmentFromUrl($JSCompiler_StaticMethods_resumeSubscribingForPushNotifications_$self$$.ampdoc.win.location.href));$JSCompiler_StaticMethods_resumeSubscribingForPushNotifications_$self$$.queryNotificationPermission().then(function($permission$jscomp$3$$){switch($permission$jscomp$3$$){case "denied":case "default":return $JSCompiler_StaticMethods_resumeSubscribingForPushNotifications_$self$$.updateWidgetVisibilities();
case "granted":$JSCompiler_StaticMethods_onPermissionGrantedSubscribe_$$($JSCompiler_StaticMethods_resumeSubscribingForPushNotifications_$self$$);break;default:throw Error("Unexpected permission value",$permission$jscomp$3$$);}})}
$JSCompiler_prototypeAlias$$.environmentSupportsWebPush=function(){return void 0!==this.ampdoc.win.Notification&&void 0!==this.ampdoc.win.navigator.serviceWorker&&void 0!==this.ampdoc.win.PushManager&&("https:"===this.ampdoc.win.location.protocol||"localhost"===this.ampdoc.win.location.hostname||"127.0.0.1"===this.ampdoc.win.location.hostname||$getMode$$module$src$mode$$().development||$getMode$$module$src$mode$$().test)};
$$jscomp$global$$.Object.defineProperties($WebPushService$$module$extensions$amp_web_push$0_1$web_push_service$$,{PERMISSION_POPUP_URL_FRAGMENT:{configurable:!0,enumerable:!0,get:function(){return"amp-web-push-subscribing=yes"}},AMP_VERSION_INITIAL:{configurable:!0,enumerable:!0,get:function(){return 1}}});(function($AMP$jscomp$1$$){$AMP$jscomp$1$$.registerServiceForDoc("amp-web-push-service",$WebPushService$$module$extensions$amp_web_push$0_1$web_push_service$$);$AMP$jscomp$1$$.registerElement("amp-web-push",$WebPushConfig$$module$extensions$amp_web_push$0_1$amp_web_push_config$$);$AMP$jscomp$1$$.registerElement("amp-web-push-widget",$WebPushWidget$$module$extensions$amp_web_push$0_1$amp_web_push_widget$$,"amp-web-push-widget.amp-invisible{visibility:hidden}\n/*# sourceURL=/extensions/amp-web-push/0.1/amp-web-push.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-web-push-0.1.js.map
