(self.AMP=self.AMP||[]).push({n:"amp-geo",v:"1904281823091",f:(function(AMP,_){
var $$jscomp$objectCreate$$="function"==typeof Object.create?Object.create:function($prototype$$){function $ctor$$(){}$ctor$$.prototype=$prototype$$;return new $ctor$$},$JSCompiler_temp$jscomp$16$$;
if("function"==typeof Object.setPrototypeOf)$JSCompiler_temp$jscomp$16$$=Object.setPrototypeOf;else{var $JSCompiler_inline_result$jscomp$17$$;a:{var $JSCompiler_x$jscomp$inline_26$$={a:!0},$JSCompiler_y$jscomp$inline_27$$={};try{$JSCompiler_y$jscomp$inline_27$$.__proto__=$JSCompiler_x$jscomp$inline_26$$;$JSCompiler_inline_result$jscomp$17$$=$JSCompiler_y$jscomp$inline_27$$.a;break a}catch($JSCompiler_e$jscomp$inline_28$$){}$JSCompiler_inline_result$jscomp$17$$=!1}$JSCompiler_temp$jscomp$16$$=$JSCompiler_inline_result$jscomp$17$$?
function($target$jscomp$83$$,$proto$jscomp$3$$){$target$jscomp$83$$.__proto__=$proto$jscomp$3$$;if($target$jscomp$83$$.__proto__!==$proto$jscomp$3$$)throw new TypeError($target$jscomp$83$$+" is not extensible");return $target$jscomp$83$$}:null}var $$jscomp$setPrototypeOf$$=$JSCompiler_temp$jscomp$16$$;
function $Deferred$$module$src$utils$promise$$(){var $resolve$$,$reject$$;this.promise=new Promise(function($res$$,$rej$$){$resolve$$=$res$$;$reject$$=$rej$$});this.resolve=$resolve$$;this.reject=$reject$$};function $tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($component$jscomp$4$$,$fallback$$){$fallback$$=void 0===$fallback$$?"":$fallback$$;try{return decodeURIComponent($component$jscomp$4$$)}catch($e$jscomp$8$$){return $fallback$$}};var $regex$$module$src$url_parse_query_string$$=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;
function $parseQueryString_$$module$src$url_parse_query_string$$($queryString$$){var $params$jscomp$1$$=Object.create(null);if(!$queryString$$)return $params$jscomp$1$$;for(var $match$$;$match$$=$regex$$module$src$url_parse_query_string$$.exec($queryString$$);){var $name$jscomp$70$$=$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($match$$[1],$match$$[1]),$value$jscomp$87$$=$match$$[2]?$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($match$$[2],$match$$[2]):"";
$params$jscomp$1$$[$name$jscomp$70$$]=$value$jscomp$87$$}return $params$jscomp$1$$};var $rtvVersion$$module$src$mode$$="";
function $getMode$$module$src$mode$$($opt_win$$){var $win$$=$opt_win$$||self;if($win$$.AMP_MODE)var $JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_30$$=$win$$.AMP_MODE;else{$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_30$$=$win$$;var $JSCompiler_AMP_CONFIG$jscomp$inline_31_JSCompiler_singlePassType$jscomp$inline_38$$=self.AMP_CONFIG||{},$JSCompiler_runningTests$jscomp$inline_35$$=!!$JSCompiler_AMP_CONFIG$jscomp$inline_31_JSCompiler_singlePassType$jscomp$inline_38$$.test||!(!$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_30$$.AMP_TEST&&
!$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_30$$.__karma__),$JSCompiler_isLocalDev$jscomp$inline_36$$=!!$JSCompiler_AMP_CONFIG$jscomp$inline_31_JSCompiler_singlePassType$jscomp$inline_38$$.localDev||$JSCompiler_runningTests$jscomp$inline_35$$,$JSCompiler_hashQuery$jscomp$inline_37$$=$parseQueryString_$$module$src$url_parse_query_string$$($JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_30$$.location.originalHash||$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_30$$.location.hash);
$JSCompiler_AMP_CONFIG$jscomp$inline_31_JSCompiler_singlePassType$jscomp$inline_38$$=$JSCompiler_AMP_CONFIG$jscomp$inline_31_JSCompiler_singlePassType$jscomp$inline_38$$.spt;var $JSCompiler_searchQuery$jscomp$inline_39$$=$parseQueryString_$$module$src$url_parse_query_string$$($JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_30$$.location.search);$rtvVersion$$module$src$mode$$||($rtvVersion$$module$src$mode$$=$JSCompiler_isLocalDev$jscomp$inline_36$$?"1904281823091":$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_30$$.AMP_CONFIG&&
$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_30$$.AMP_CONFIG.v?$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_30$$.AMP_CONFIG.v:"011904281823091");$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_30$$=$win$$.AMP_MODE={localDev:$JSCompiler_isLocalDev$jscomp$inline_36$$,development:!("1"!=$JSCompiler_hashQuery$jscomp$inline_37$$.development&&!$JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_30$$.AMP_DEV_MODE),examiner:"2"==$JSCompiler_hashQuery$jscomp$inline_37$$.development,
filter:$JSCompiler_hashQuery$jscomp$inline_37$$.filter,geoOverride:$JSCompiler_hashQuery$jscomp$inline_37$$["amp-geo"],minified:!0,lite:void 0!=$JSCompiler_searchQuery$jscomp$inline_39$$.amp_lite,test:$JSCompiler_runningTests$jscomp$inline_35$$,log:$JSCompiler_hashQuery$jscomp$inline_37$$.log,version:"1904281823091",rtvVersion:$rtvVersion$$module$src$mode$$,singlePassType:$JSCompiler_AMP_CONFIG$jscomp$inline_31_JSCompiler_singlePassType$jscomp$inline_38$$}}return $JSCompiler_temp$jscomp$18_JSCompiler_win$jscomp$inline_30$$}
;var $toString_$$module$src$types$$=Object.prototype.toString;self.log=self.log||{user:null,dev:null,userForEmbed:null};var $logs$$module$src$log$$=self.log;function $getAmpdoc$$module$src$service$$($JSCompiler_temp$jscomp$70_nodeOrDoc$jscomp$2$$){if($JSCompiler_temp$jscomp$70_nodeOrDoc$jscomp$2$$.nodeType){var $JSCompiler_win$jscomp$inline_72$$=($JSCompiler_temp$jscomp$70_nodeOrDoc$jscomp$2$$.ownerDocument||$JSCompiler_temp$jscomp$70_nodeOrDoc$jscomp$2$$).defaultView;$JSCompiler_win$jscomp$inline_72$$=$JSCompiler_win$jscomp$inline_72$$.__AMP_TOP||$JSCompiler_win$jscomp$inline_72$$;$JSCompiler_temp$jscomp$70_nodeOrDoc$jscomp$2$$=$getServiceInternal$$module$src$service$$($JSCompiler_win$jscomp$inline_72$$,
"ampdoc").getAmpDoc($JSCompiler_temp$jscomp$70_nodeOrDoc$jscomp$2$$)}return $JSCompiler_temp$jscomp$70_nodeOrDoc$jscomp$2$$}
function $getServiceInternal$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$,$id$jscomp$19$$){$isServiceRegistered$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$,$id$jscomp$19$$);var $JSCompiler_services$jscomp$inline_45$$=$holder$jscomp$4_s$jscomp$8$$.services;$JSCompiler_services$jscomp$inline_45$$||($JSCompiler_services$jscomp$inline_45$$=$holder$jscomp$4_s$jscomp$8$$.services={});var $services$$=$JSCompiler_services$jscomp$inline_45$$;$holder$jscomp$4_s$jscomp$8$$=$services$$[$id$jscomp$19$$];
$holder$jscomp$4_s$jscomp$8$$.obj||($holder$jscomp$4_s$jscomp$8$$.obj=new $holder$jscomp$4_s$jscomp$8$$.ctor($holder$jscomp$4_s$jscomp$8$$.context),$holder$jscomp$4_s$jscomp$8$$.ctor=null,$holder$jscomp$4_s$jscomp$8$$.context=null,$holder$jscomp$4_s$jscomp$8$$.resolve&&$holder$jscomp$4_s$jscomp$8$$.resolve($holder$jscomp$4_s$jscomp$8$$.obj));return $holder$jscomp$4_s$jscomp$8$$.obj}
function $isServiceRegistered$$module$src$service$$($holder$jscomp$12_service$jscomp$4$$,$id$jscomp$27$$){$holder$jscomp$12_service$jscomp$4$$=$holder$jscomp$12_service$jscomp$4$$.services&&$holder$jscomp$12_service$jscomp$4$$.services[$id$jscomp$27$$];return!(!$holder$jscomp$12_service$jscomp$4$$||!$holder$jscomp$12_service$jscomp$4$$.ctor&&!$holder$jscomp$12_service$jscomp$4$$.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function $isJsonScriptTag$$module$src$dom$$($element$jscomp$22$$){return"SCRIPT"==$element$jscomp$22$$.tagName&&$element$jscomp$22$$.hasAttribute("type")&&"APPLICATION/JSON"==$element$jscomp$22$$.getAttribute("type").toUpperCase()};var $ampGeoPresets$$module$extensions$amp_geo$0_1$amp_geo_presets$$={"preset-eea":"AT BE BG HR CY CZ DK EE FI FR DE GR HU IS IE IT LV LI LT LU MT NL NO PL PT RO SK SI ES SE GB AX IC EA GF PF TF GI GP GG JE MQ YT NC RE BL MF PM SJ VA WF EZ CH".split(" ")};(function($opt_initial$jscomp$1$$){return $opt_initial$jscomp$1$$||{}})({c:!0,v:!0,a:!0,ad:!0,action:!0});function $tryParseJson$$module$src$json$$($json$jscomp$1$$,$opt_onFailed$$){try{return JSON.parse($json$jscomp$1$$)}catch($e$jscomp$17$$){return $opt_onFailed$$&&$opt_onFailed$$($e$jscomp$17$$),null}};var $PRE_RENDER_REGEX$$module$extensions$amp_geo$0_1$amp_geo$$=/amp-iso-country-(\w+)/;
function $AmpGeo$$module$extensions$amp_geo$0_1$amp_geo$$($$jscomp$super$this_element$jscomp$56$$){$$jscomp$super$this_element$jscomp$56$$=AMP.BaseElement.call(this,$$jscomp$super$this_element$jscomp$56$$)||this;$$jscomp$super$this_element$jscomp$56$$.$mode_$=0;$$jscomp$super$this_element$jscomp$56$$.$error_$=!1;$$jscomp$super$this_element$jscomp$56$$.$country_$="unknown";$$jscomp$super$this_element$jscomp$56$$.$matchedGroups_$=[];$$jscomp$super$this_element$jscomp$56$$.$definedGroups_$=[];return $$jscomp$super$this_element$jscomp$56$$}
var $JSCompiler_parentCtor$jscomp$inline_48$$=AMP.BaseElement;$AmpGeo$$module$extensions$amp_geo$0_1$amp_geo$$.prototype=$$jscomp$objectCreate$$($JSCompiler_parentCtor$jscomp$inline_48$$.prototype);$AmpGeo$$module$extensions$amp_geo$0_1$amp_geo$$.prototype.constructor=$AmpGeo$$module$extensions$amp_geo$0_1$amp_geo$$;
if($$jscomp$setPrototypeOf$$)$$jscomp$setPrototypeOf$$($AmpGeo$$module$extensions$amp_geo$0_1$amp_geo$$,$JSCompiler_parentCtor$jscomp$inline_48$$);else for(var $JSCompiler_p$jscomp$inline_49$$ in $JSCompiler_parentCtor$jscomp$inline_48$$)if("prototype"!=$JSCompiler_p$jscomp$inline_49$$)if(Object.defineProperties){var $JSCompiler_descriptor$jscomp$inline_50$$=Object.getOwnPropertyDescriptor($JSCompiler_parentCtor$jscomp$inline_48$$,$JSCompiler_p$jscomp$inline_49$$);$JSCompiler_descriptor$jscomp$inline_50$$&&
Object.defineProperty($AmpGeo$$module$extensions$amp_geo$0_1$amp_geo$$,$JSCompiler_p$jscomp$inline_49$$,$JSCompiler_descriptor$jscomp$inline_50$$)}else $AmpGeo$$module$extensions$amp_geo$0_1$amp_geo$$[$JSCompiler_p$jscomp$inline_49$$]=$JSCompiler_parentCtor$jscomp$inline_48$$[$JSCompiler_p$jscomp$inline_49$$];$AmpGeo$$module$extensions$amp_geo$0_1$amp_geo$$.$superClass_$=$JSCompiler_parentCtor$jscomp$inline_48$$.prototype;
$AmpGeo$$module$extensions$amp_geo$0_1$amp_geo$$.prototype.prerenderAllowed=function(){return!0};
$AmpGeo$$module$extensions$amp_geo$0_1$amp_geo$$.prototype.buildCallback=function(){var $children$jscomp$127_config$jscomp$2$$=this.element.children;$children$jscomp$127_config$jscomp$2$$.length&&$JSCompiler_StaticMethods_assertWithErrorReturn_$$(1===$children$jscomp$127_config$jscomp$2$$.length&&$isJsonScriptTag$$module$src$dom$$($children$jscomp$127_config$jscomp$2$$[0]),'amp-geo can only have one <script type="application/json"> child');$children$jscomp$127_config$jscomp$2$$=$children$jscomp$127_config$jscomp$2$$.length?
$tryParseJson$$module$src$json$$($children$jscomp$127_config$jscomp$2$$[0].textContent,function(){return $JSCompiler_StaticMethods_assertWithErrorReturn_$$(!1,"amp-geo Unable to parse JSON")}):{};var $geo$$=$JSCompiler_StaticMethods_addToBody_$$(this,$children$jscomp$127_config$jscomp$2$$||{});$geoDeferred$$module$extensions$amp_geo$0_1$amp_geo$$.resolve($geo$$)};
function $JSCompiler_StaticMethods_assertWithErrorReturn_$$($shouldBeTrueish$jscomp$4$$,$opt_message$jscomp$15$$){if(!$shouldBeTrueish$jscomp$4$$){$geoDeferred$$module$extensions$amp_geo$0_1$amp_geo$$.resolve(null);if(!$logs$$module$src$log$$.user)throw Error("failed to call initLogConstructor");return $logs$$module$src$log$$.user.assert($shouldBeTrueish$jscomp$4$$,$opt_message$jscomp$15$$,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)}return $shouldBeTrueish$jscomp$4$$}
function $JSCompiler_StaticMethods_findCountry_$$($JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$,$JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$){var $preRenderMatch$$=$JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$.getBody().className.match($PRE_RENDER_REGEX$$module$extensions$amp_geo$0_1$amp_geo$$),
$trimmedCountryMatch$$=/^(\w{2})?\s*/.exec("{{AMP_ISO_COUNTRY_HOTPATCH}}");if($JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$=$getMode$$module$src$mode$$($JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$.win).geoOverride)$JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$=
$JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$.win,$JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$=!(!$JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$.AMP_CONFIG||
!$JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$.AMP_CONFIG.canary)||$getMode$$module$src$mode$$($JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$.win).localDev;if($JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$&&
/^\w+$/.test($getMode$$module$src$mode$$($JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$.win).geoOverride))$JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$.$mode_$=2,$JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$.$country_$=$getMode$$module$src$mode$$($JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$.win).geoOverride.toLowerCase();else{if($JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$=
$preRenderMatch$$){a:{$JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$=$JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$.element;var $JSCompiler_win$jscomp$inline_77$$=$JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$.ownerDocument.defaultView;
if($JSCompiler_win$jscomp$inline_77$$!=($JSCompiler_win$jscomp$inline_77$$.__AMP_TOP||$JSCompiler_win$jscomp$inline_77$$)){if($isServiceRegistered$$module$src$service$$($JSCompiler_win$jscomp$inline_77$$,"url")&&($JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$=
$getServiceInternal$$module$src$service$$($JSCompiler_win$jscomp$inline_77$$,"url")))break a;$JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$=null}else $JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$=
$getAmpdoc$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$),$JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$=
$getAmpdoc$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$),$JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$=
$JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$.isSingleDoc()?$JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$.win:
$JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$,$JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$=
$isServiceRegistered$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$,"url")?$getServiceInternal$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$,
"url"):null}$JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$=!$JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$.isProxyOrigin($JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$.win.location)}if($JSCompiler_ampdoc$jscomp$inline_85_JSCompiler_ampdoc$jscomp$inline_87_JSCompiler_element$jscomp$inline_75_JSCompiler_embedService$jscomp$inline_79_JSCompiler_inline_result$jscomp$69_JSCompiler_inline_result$jscomp$inline_86_JSCompiler_temp$jscomp$24_JSCompiler_temp$jscomp$68_JSCompiler_win$jscomp$inline_64_ampdoc$jscomp$10$$)$JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$.$mode_$=
1,$JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$.$country_$=$preRenderMatch$$[1];else if($trimmedCountryMatch$$[1])$JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$.$mode_$=0,$JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$.$country_$=$trimmedCountryMatch$$[1];else if(""===$trimmedCountryMatch$$[0]&&!$getMode$$module$src$mode$$($JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$.win).localDev){$JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$.$error_$=
!0;if($logs$$module$src$log$$.dev)$JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$=$logs$$module$src$log$$.dev;else throw Error("failed to call initLogConstructor");$JSCompiler_StaticMethods_findCountry_$self_JSCompiler_inline_result$jscomp$20$$.error("amp-geo","GEONOTPATCHED: amp-geo served unpatched, ISO country not set")}}}
function $JSCompiler_StaticMethods_matchCountryGroups_$$($JSCompiler_StaticMethods_matchCountryGroups_$self$$,$config$jscomp$3$$){var $ISOCountryGroups$$=$config$jscomp$3$$.ISOCountryGroups,$errorPrefix$$="<amp-geo> ISOCountryGroups";$ISOCountryGroups$$&&($JSCompiler_StaticMethods_assertWithErrorReturn_$$("[object Object]"===$toString_$$module$src$types$$.call($ISOCountryGroups$$),$errorPrefix$$+" must be an object"),$JSCompiler_StaticMethods_matchCountryGroups_$self$$.$definedGroups_$=Object.keys($ISOCountryGroups$$),
$JSCompiler_StaticMethods_matchCountryGroups_$self$$.$definedGroups_$.forEach(function($config$jscomp$3$$){$JSCompiler_StaticMethods_assertWithErrorReturn_$$(/^[a-z]+[a-z0-9]*$/i.test($config$jscomp$3$$)&&!/^amp/.test($config$jscomp$3$$),$errorPrefix$$+"["+$config$jscomp$3$$+"] name is invalid");$JSCompiler_StaticMethods_assertWithErrorReturn_$$(Array.isArray($ISOCountryGroups$$[$config$jscomp$3$$]),$errorPrefix$$+"["+$config$jscomp$3$$+"] must be an array");$JSCompiler_StaticMethods_checkGroup_$$($JSCompiler_StaticMethods_matchCountryGroups_$self$$,
$ISOCountryGroups$$[$config$jscomp$3$$])&&$JSCompiler_StaticMethods_matchCountryGroups_$self$$.$matchedGroups_$.push($config$jscomp$3$$)}))}
function $JSCompiler_StaticMethods_checkGroup_$$($JSCompiler_StaticMethods_checkGroup_$self$$,$countryGroup$$){var $expandedGroup$$=$countryGroup$$.reduce(function($JSCompiler_StaticMethods_checkGroup_$self$$,$countryGroup$$){if(/^preset-/.test($countryGroup$$))return $JSCompiler_StaticMethods_assertWithErrorReturn_$$(Array.isArray($ampGeoPresets$$module$extensions$amp_geo$0_1$amp_geo_presets$$[$countryGroup$$]),"<amp-geo> preset "+$countryGroup$$+" not found"),$JSCompiler_StaticMethods_checkGroup_$self$$.concat($ampGeoPresets$$module$extensions$amp_geo$0_1$amp_geo_presets$$[$countryGroup$$]);
$JSCompiler_StaticMethods_checkGroup_$self$$.push($countryGroup$$);return $JSCompiler_StaticMethods_checkGroup_$self$$},[]).map(function($JSCompiler_StaticMethods_checkGroup_$self$$){return $JSCompiler_StaticMethods_checkGroup_$self$$.toLowerCase()});return $expandedGroup$$.includes($JSCompiler_StaticMethods_checkGroup_$self$$.$country_$)}
function $JSCompiler_StaticMethods_clearPreRender_$$($body$jscomp$1_i$jscomp$19$$){var $classList$$=$body$jscomp$1_i$jscomp$19$$.classList,$classesToRemove$$=[],$stripRe$$=/^amp-iso-country-|^amp-geo-group-/i;for($body$jscomp$1_i$jscomp$19$$=$classList$$.length-1;0<$body$jscomp$1_i$jscomp$19$$;$body$jscomp$1_i$jscomp$19$$--)$stripRe$$.test($classList$$[$body$jscomp$1_i$jscomp$19$$])&&$classesToRemove$$.push($classList$$[$body$jscomp$1_i$jscomp$19$$]);return $classesToRemove$$}
function $JSCompiler_StaticMethods_addToBody_$$($JSCompiler_StaticMethods_addToBody_$self$$,$config$jscomp$4$$){var $ampdoc$jscomp$11$$=$JSCompiler_StaticMethods_addToBody_$self$$.getAmpDoc(),$states$$={};return $ampdoc$jscomp$11$$.whenBodyAvailable().then(function($body$jscomp$2$$){$JSCompiler_StaticMethods_findCountry_$$($JSCompiler_StaticMethods_addToBody_$self$$,$ampdoc$jscomp$11$$);$JSCompiler_StaticMethods_matchCountryGroups_$$($JSCompiler_StaticMethods_addToBody_$self$$,$config$jscomp$4$$);
var $classesToRemove$jscomp$1$$=[];switch($JSCompiler_StaticMethods_addToBody_$self$$.$mode_$){case 2:$classesToRemove$jscomp$1$$=$JSCompiler_StaticMethods_clearPreRender_$$($body$jscomp$2$$);case 0:$states$$.ISOCountry=$JSCompiler_StaticMethods_addToBody_$self$$.$country_$;var $classesToAdd$$=$JSCompiler_StaticMethods_addToBody_$self$$.$matchedGroups_$.map(function($JSCompiler_StaticMethods_addToBody_$self$$){$states$$[$JSCompiler_StaticMethods_addToBody_$self$$]=!0;return"amp-geo-group-"+$JSCompiler_StaticMethods_addToBody_$self$$});
$JSCompiler_StaticMethods_addToBody_$self$$.$matchedGroups_$.length||$classesToAdd$$.push("amp-geo-no-group");$JSCompiler_StaticMethods_addToBody_$self$$.$error_$&&$classesToAdd$$.push("amp-geo-error");$states$$.ISOCountryGroups=$JSCompiler_StaticMethods_addToBody_$self$$.$matchedGroups_$;$classesToAdd$$.push("amp-iso-country-"+$JSCompiler_StaticMethods_addToBody_$self$$.$country_$);$JSCompiler_StaticMethods_addToBody_$self$$.mutateElement(function(){var $JSCompiler_StaticMethods_addToBody_$self$$=
$body$jscomp$2$$.classList;$classesToRemove$jscomp$1$$.push("amp-geo-pending");$classesToRemove$jscomp$1$$.forEach(function($config$jscomp$4$$){return $JSCompiler_StaticMethods_addToBody_$self$$.remove($config$jscomp$4$$)});$classesToAdd$$.forEach(function($config$jscomp$4$$){return $JSCompiler_StaticMethods_addToBody_$self$$.add($config$jscomp$4$$)});if($config$jscomp$4$$.AmpBind){var $geoState$$=$ampdoc$jscomp$11$$.getElementById("ampGeo");$geoState$$&&$geoState$$.parentNode.removeChild($geoState$$);
var $state$$=$ampdoc$jscomp$11$$.win.document.createElement("amp-state"),$confScript$$=$ampdoc$jscomp$11$$.win.document.createElement("script");$confScript$$.setAttribute("type","application/json");$confScript$$.textContent=JSON.stringify($states$$);$state$$.appendChild($confScript$$);$state$$.id="ampGeo";$body$jscomp$2$$.appendChild($state$$)}},$body$jscomp$2$$)}return{ISOCountry:$JSCompiler_StaticMethods_addToBody_$self$$.$country_$,matchedISOCountryGroups:$JSCompiler_StaticMethods_addToBody_$self$$.$matchedGroups_$,
allISOCountryGroups:$JSCompiler_StaticMethods_addToBody_$self$$.$definedGroups_$,isInCountryGroup:$JSCompiler_StaticMethods_addToBody_$self$$.isInCountryGroup.bind($JSCompiler_StaticMethods_addToBody_$self$$)}})}
$AmpGeo$$module$extensions$amp_geo$0_1$amp_geo$$.prototype.isInCountryGroup=function($targetGroup$$){var $$jscomp$this$jscomp$5$$=this,$targets$$=$targetGroup$$.trim().split(/,\s*/);return $targets$$.filter(function($targetGroup$$){return 0<=$$jscomp$this$jscomp$5$$.$definedGroups_$.indexOf($targetGroup$$)}).length!==$targets$$.length?1:0<$targets$$.filter(function($targetGroup$$){return 0<=$$jscomp$this$jscomp$5$$.$matchedGroups_$.indexOf($targetGroup$$)}).length?2:3};
var $geoDeferred$$module$extensions$amp_geo$0_1$amp_geo$$=null;(function($AMP$jscomp$1$$){$geoDeferred$$module$extensions$amp_geo$0_1$amp_geo$$=new $Deferred$$module$src$utils$promise$$;$AMP$jscomp$1$$.registerElement("amp-geo",$AmpGeo$$module$extensions$amp_geo$0_1$amp_geo$$);$AMP$jscomp$1$$.registerServiceForDoc("geo",function(){return $geoDeferred$$module$extensions$amp_geo$0_1$amp_geo$$.promise})})(self.AMP);
})});

//# sourceMappingURL=amp-geo-0.1.js.map
