(self.AMP=self.AMP||[]).push({n:"amp-smartlinks",v:"1904281823091",f:(function(AMP,_){
var $$jscomp$objectCreate$$="function"==typeof Object.create?Object.create:function($prototype$$){function $ctor$$(){}$ctor$$.prototype=$prototype$$;return new $ctor$$},$JSCompiler_temp$jscomp$18$$;
if("function"==typeof Object.setPrototypeOf)$JSCompiler_temp$jscomp$18$$=Object.setPrototypeOf;else{var $JSCompiler_inline_result$jscomp$19$$;a:{var $JSCompiler_x$jscomp$inline_36$$={a:!0},$JSCompiler_y$jscomp$inline_37$$={};try{$JSCompiler_y$jscomp$inline_37$$.__proto__=$JSCompiler_x$jscomp$inline_36$$;$JSCompiler_inline_result$jscomp$19$$=$JSCompiler_y$jscomp$inline_37$$.a;break a}catch($JSCompiler_e$jscomp$inline_38$$){}$JSCompiler_inline_result$jscomp$19$$=!1}$JSCompiler_temp$jscomp$18$$=$JSCompiler_inline_result$jscomp$19$$?
function($target$jscomp$83$$,$proto$jscomp$3$$){$target$jscomp$83$$.__proto__=$proto$jscomp$3$$;if($target$jscomp$83$$.__proto__!==$proto$jscomp$3$$)throw new TypeError($target$jscomp$83$$+" is not extensible");return $target$jscomp$83$$}:null}var $$jscomp$setPrototypeOf$$=$JSCompiler_temp$jscomp$18$$;
function $$jscomp$inherits$$($childCtor$$,$parentCtor$$){$childCtor$$.prototype=$$jscomp$objectCreate$$($parentCtor$$.prototype);$childCtor$$.prototype.constructor=$childCtor$$;if($$jscomp$setPrototypeOf$$)$$jscomp$setPrototypeOf$$($childCtor$$,$parentCtor$$);else for(var $p$$ in $parentCtor$$)if("prototype"!=$p$$)if(Object.defineProperties){var $descriptor$jscomp$1$$=Object.getOwnPropertyDescriptor($parentCtor$$,$p$$);$descriptor$jscomp$1$$&&Object.defineProperty($childCtor$$,$p$$,$descriptor$jscomp$1$$)}else $childCtor$$[$p$$]=
$parentCtor$$[$p$$];$childCtor$$.$superClass_$=$parentCtor$$.prototype}var $$jscomp$global$$=function($maybeGlobal$$){return"undefined"!=typeof window&&window===$maybeGlobal$$?$maybeGlobal$$:"undefined"!=typeof global&&null!=global?global:$maybeGlobal$$}(this);function $Deferred$$module$src$utils$promise$$(){var $resolve$$,$reject$$;this.promise=new Promise(function($res$$,$rej$$){$resolve$$=$res$$;$reject$$=$rej$$});this.resolve=$resolve$$;this.reject=$reject$$};self.log=self.log||{user:null,dev:null,userForEmbed:null};var $logs$$module$src$log$$=self.log;function $getService$$module$src$service$$($win$jscomp$8$$,$id$jscomp$11$$){$win$jscomp$8$$=$win$jscomp$8$$.__AMP_TOP||$win$jscomp$8$$;return $getServiceInternal$$module$src$service$$($win$jscomp$8$$,$id$jscomp$11$$)}
function $getServiceForDoc$$module$src$service$$($elementOrAmpDoc$$,$id$jscomp$15$$){var $ampdoc$jscomp$2_holder$jscomp$2$$=$getAmpdoc$$module$src$service$$($elementOrAmpDoc$$);$ampdoc$jscomp$2_holder$jscomp$2$$=$getAmpdocServiceHolder$$module$src$service$$($ampdoc$jscomp$2_holder$jscomp$2$$);return $getServiceInternal$$module$src$service$$($ampdoc$jscomp$2_holder$jscomp$2$$,$id$jscomp$15$$)}
function $getAmpdoc$$module$src$service$$($nodeOrDoc$jscomp$2$$){return $nodeOrDoc$jscomp$2$$.nodeType?$getService$$module$src$service$$(($nodeOrDoc$jscomp$2$$.ownerDocument||$nodeOrDoc$jscomp$2$$).defaultView,"ampdoc").getAmpDoc($nodeOrDoc$jscomp$2$$):$nodeOrDoc$jscomp$2$$}
function $getAmpdocServiceHolder$$module$src$service$$($ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$){$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$=$getAmpdoc$$module$src$service$$($ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$);return $ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$.isSingleDoc()?$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$.win:$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$}
function $getServiceInternal$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$,$id$jscomp$19$$){var $services$$=$getServices$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$);$holder$jscomp$4_s$jscomp$8$$=$services$$[$id$jscomp$19$$];$holder$jscomp$4_s$jscomp$8$$.obj||($holder$jscomp$4_s$jscomp$8$$.obj=new $holder$jscomp$4_s$jscomp$8$$.ctor($holder$jscomp$4_s$jscomp$8$$.context),$holder$jscomp$4_s$jscomp$8$$.ctor=null,$holder$jscomp$4_s$jscomp$8$$.context=null,$holder$jscomp$4_s$jscomp$8$$.resolve&&
$holder$jscomp$4_s$jscomp$8$$.resolve($holder$jscomp$4_s$jscomp$8$$.obj));return $holder$jscomp$4_s$jscomp$8$$.obj}
function $getServicePromiseInternal$$module$src$service$$($holder$jscomp$6_services$jscomp$2$$,$id$jscomp$21$$){var $cached$$=$getServicePromiseOrNullInternal$$module$src$service$$($holder$jscomp$6_services$jscomp$2$$,$id$jscomp$21$$);if($cached$$)return $cached$$;$holder$jscomp$6_services$jscomp$2$$=$getServices$$module$src$service$$($holder$jscomp$6_services$jscomp$2$$);$holder$jscomp$6_services$jscomp$2$$[$id$jscomp$21$$]=$emptyServiceHolderWithPromise$$module$src$service$$();return $holder$jscomp$6_services$jscomp$2$$[$id$jscomp$21$$].promise}
function $getServicePromiseOrNullInternal$$module$src$service$$($holder$jscomp$8$$,$id$jscomp$23$$){var $s$jscomp$11$$=$getServices$$module$src$service$$($holder$jscomp$8$$)[$id$jscomp$23$$];if($s$jscomp$11$$){if($s$jscomp$11$$.promise)return $s$jscomp$11$$.promise;$getServiceInternal$$module$src$service$$($holder$jscomp$8$$,$id$jscomp$23$$);return $s$jscomp$11$$.promise=Promise.resolve($s$jscomp$11$$.obj)}return null}
function $getServices$$module$src$service$$($holder$jscomp$9$$){var $services$jscomp$5$$=$holder$jscomp$9$$.services;$services$jscomp$5$$||($services$jscomp$5$$=$holder$jscomp$9$$.services={});return $services$jscomp$5$$}
function $emptyServiceHolderWithPromise$$module$src$service$$(){var $deferred$$=new $Deferred$$module$src$utils$promise$$,$$jscomp$destructuring$var2_reject$jscomp$3$$=$deferred$$,$promise$jscomp$1$$=$$jscomp$destructuring$var2_reject$jscomp$3$$.promise,$resolve$jscomp$4$$=$$jscomp$destructuring$var2_reject$jscomp$3$$.resolve;$$jscomp$destructuring$var2_reject$jscomp$3$$=$$jscomp$destructuring$var2_reject$jscomp$3$$.reject;$promise$jscomp$1$$.catch(function(){});return{obj:null,promise:$promise$jscomp$1$$,
resolve:$resolve$jscomp$4$$,reject:$$jscomp$destructuring$var2_reject$jscomp$3$$,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function $dict$$module$src$utils$object$$($opt_initial$jscomp$1$$){return $opt_initial$jscomp$1$$||{}};function $createElementWithAttributes$$module$src$dom$$($doc$jscomp$12_element$jscomp$16$$,$tagName$jscomp$5$$,$attributes$jscomp$2$$){$doc$jscomp$12_element$jscomp$16$$=$doc$jscomp$12_element$jscomp$16$$.createElement($tagName$jscomp$5$$);for(var $JSCompiler_attr$jscomp$inline_48$$ in $attributes$jscomp$2$$)$doc$jscomp$12_element$jscomp$16$$.setAttribute($JSCompiler_attr$jscomp$inline_48$$,$attributes$jscomp$2$$[$JSCompiler_attr$jscomp$inline_48$$]);return $doc$jscomp$12_element$jscomp$16$$};function $getElementServiceIfAvailableForDoc$$module$src$element_service$$($element$jscomp$33$$){var $s$jscomp$13$$=$getServicePromiseOrNullInternal$$module$src$service$$($getAmpdocServiceHolder$$module$src$service$$($element$jscomp$33$$),"amp-analytics-instrumentation");if($s$jscomp$13$$)return $s$jscomp$13$$;var $ampdoc$jscomp$7$$=$getAmpdoc$$module$src$service$$($element$jscomp$33$$);return $ampdoc$jscomp$7$$.whenBodyAvailable().then(function(){var $element$jscomp$33$$=$ampdoc$jscomp$7$$.win;var $s$jscomp$13$$=
$ampdoc$jscomp$7$$.win.document.head;if($s$jscomp$13$$){var $JSCompiler_inline_result$jscomp$115_JSCompiler_scripts$jscomp$inline_117$$=[];$s$jscomp$13$$=$s$jscomp$13$$.querySelectorAll("script[custom-element]");for(var $JSCompiler_i$jscomp$inline_119$$=0;$JSCompiler_i$jscomp$inline_119$$<$s$jscomp$13$$.length;$JSCompiler_i$jscomp$inline_119$$++)$JSCompiler_inline_result$jscomp$115_JSCompiler_scripts$jscomp$inline_117$$.push($s$jscomp$13$$[$JSCompiler_i$jscomp$inline_119$$].getAttribute("custom-element"))}else $JSCompiler_inline_result$jscomp$115_JSCompiler_scripts$jscomp$inline_117$$=
[];$element$jscomp$33$$=$JSCompiler_inline_result$jscomp$115_JSCompiler_scripts$jscomp$inline_117$$.includes("amp-analytics")?$getService$$module$src$service$$($element$jscomp$33$$,"extensions").waitForExtension($element$jscomp$33$$,"amp-analytics"):Promise.resolve();return $element$jscomp$33$$}).then(function(){var $s$jscomp$13$$=$ampdoc$jscomp$7$$.win;return $s$jscomp$13$$.ampExtendedElements&&$s$jscomp$13$$.ampExtendedElements["amp-analytics"]?$getServicePromiseInternal$$module$src$service$$($getAmpdocServiceHolder$$module$src$service$$($element$jscomp$33$$),
"amp-analytics-instrumentation"):null})};function $triggerAnalyticsEvent$$module$src$analytics$$($target$jscomp$86$$,$eventType$jscomp$3$$,$opt_vars$$){$getElementServiceIfAvailableForDoc$$module$src$element_service$$($target$jscomp$86$$).then(function($analytics$$){$analytics$$&&$analytics$$.triggerEventForTarget($target$jscomp$86$$,$eventType$jscomp$3$$,$opt_vars$$)})};function $insertAnalyticsElement$$module$src$extension_analytics$$($parentElement$$,$config$jscomp$2_extensions$jscomp$1$$){var $ampdoc$jscomp$10_loadAnalytics$jscomp$1$$=!0;$ampdoc$jscomp$10_loadAnalytics$jscomp$1$$=void 0===$ampdoc$jscomp$10_loadAnalytics$jscomp$1$$?!1:$ampdoc$jscomp$10_loadAnalytics$jscomp$1$$;var $disableImmediate$$=void 0===$disableImmediate$$?!1:$disableImmediate$$;var $doc$jscomp$14$$=$parentElement$$.ownerDocument,$analyticsElem$$=$createElementWithAttributes$$module$src$dom$$($doc$jscomp$14$$,
"amp-analytics",$dict$$module$src$utils$object$$({sandbox:"true",trigger:$disableImmediate$$?"":"immediate"})),$scriptElem$$=$createElementWithAttributes$$module$src$dom$$($doc$jscomp$14$$,"script",$dict$$module$src$utils$object$$({type:"application/json"}));$scriptElem$$.textContent=JSON.stringify($config$jscomp$2_extensions$jscomp$1$$);$analyticsElem$$.appendChild($scriptElem$$);$analyticsElem$$.CONFIG=$config$jscomp$2_extensions$jscomp$1$$;$ampdoc$jscomp$10_loadAnalytics$jscomp$1$$?($config$jscomp$2_extensions$jscomp$1$$=
$getService$$module$src$service$$($parentElement$$.ownerDocument.defaultView,"extensions"),$ampdoc$jscomp$10_loadAnalytics$jscomp$1$$=$getAmpdoc$$module$src$service$$($parentElement$$),$config$jscomp$2_extensions$jscomp$1$$.installExtensionForDoc($ampdoc$jscomp$10_loadAnalytics$jscomp$1$$,"amp-analytics")):$getElementServiceIfAvailableForDoc$$module$src$element_service$$($parentElement$$).then(function(){});$parentElement$$.appendChild($analyticsElem$$)}
function $CustomEventReporter$$module$src$extension_analytics$$($parent$jscomp$14$$,$config$jscomp$3$$){var $$jscomp$this$jscomp$1$$=this;this.$id_$=$parent$jscomp$14$$.getResourceId();this.$parent_$=$parent$jscomp$14$$;this.$config_$=$config$jscomp$3$$;for(var $event$jscomp$5$$ in $config$jscomp$3$$.triggers){var $newEventType$$="sandbox-"+this.$id_$+"-"+$config$jscomp$3$$.triggers[$event$jscomp$5$$].on;$config$jscomp$3$$.triggers[$event$jscomp$5$$].on=$newEventType$$}this.$parent_$.signals().whenSignal("load-start").then(function(){$insertAnalyticsElement$$module$src$extension_analytics$$($$jscomp$this$jscomp$1$$.$parent_$,
$config$jscomp$3$$)})}$CustomEventReporter$$module$src$extension_analytics$$.prototype.trigger=function($eventType$jscomp$5$$,$opt_vars$jscomp$1$$){$triggerAnalyticsEvent$$module$src$analytics$$(this.$parent_$,"sandbox-"+this.$id_$+"-"+$eventType$jscomp$5$$,$opt_vars$jscomp$1$$)};function $CustomEventReporterBuilder$$module$src$extension_analytics$$($parent$jscomp$15$$){this.$parent_$=$parent$jscomp$15$$;this.$config_$={requests:{},triggers:{}}}
$CustomEventReporterBuilder$$module$src$extension_analytics$$.prototype.setTransportConfig=function($transportConfig$$){this.$config_$.transport=$transportConfig$$};$CustomEventReporterBuilder$$module$src$extension_analytics$$.prototype.setExtraUrlParams=function($extraUrlParamsConfig$$){this.$config_$.extraUrlParams=$extraUrlParamsConfig$$};
$CustomEventReporterBuilder$$module$src$extension_analytics$$.prototype.track=function($eventType$jscomp$7$$,$request$jscomp$5$$){$request$jscomp$5$$=Array.isArray($request$jscomp$5$$)?$request$jscomp$5$$:[$request$jscomp$5$$];for(var $requestList$$=[],$i$jscomp$11$$=0;$i$jscomp$11$$<$request$jscomp$5$$.length;$i$jscomp$11$$++){var $requestName$$=$eventType$jscomp$7$$+"-request-"+$i$jscomp$11$$;this.$config_$.requests[$requestName$$]=$request$jscomp$5$$[$i$jscomp$11$$];$requestList$$.push($requestName$$)}this.$config_$.triggers[$eventType$jscomp$7$$]=
{on:$eventType$jscomp$7$$,request:$requestList$$};return this};$CustomEventReporterBuilder$$module$src$extension_analytics$$.prototype.build=function(){var $report$$=new $CustomEventReporter$$module$src$extension_analytics$$(this.$parent_$,this.$config_$);this.$config_$=null;return $report$$};var $propertyNameCache$$module$src$style$$,$vendorPrefixes$$module$src$style$$="Webkit webkit Moz moz ms O o".split(" ");var $bodyMadeVisible$$module$src$style_installer$$=!1;function $PriorityQueue$$module$src$utils$priority_queue$$(){this.$queue_$=[]}$PriorityQueue$$module$src$utils$priority_queue$$.prototype.peek=function(){var $l$$=this.$queue_$.length;return $l$$?this.$queue_$[$l$$-1].item:null};
$PriorityQueue$$module$src$utils$priority_queue$$.prototype.enqueue=function($item$$,$priority$$){if(isNaN($priority$$))throw Error("Priority must not be NaN.");for(var $JSCompiler_target$jscomp$inline_63$$=$priority$$,$JSCompiler_i$jscomp$inline_64$$=-1,$JSCompiler_lo$jscomp$inline_65$$=0,$JSCompiler_hi$jscomp$inline_66$$=this.$queue_$.length;$JSCompiler_lo$jscomp$inline_65$$<=$JSCompiler_hi$jscomp$inline_66$$;){$JSCompiler_i$jscomp$inline_64$$=Math.floor(($JSCompiler_lo$jscomp$inline_65$$+$JSCompiler_hi$jscomp$inline_66$$)/
2);if($JSCompiler_i$jscomp$inline_64$$===this.$queue_$.length)break;if(this.$queue_$[$JSCompiler_i$jscomp$inline_64$$].priority<$JSCompiler_target$jscomp$inline_63$$)$JSCompiler_lo$jscomp$inline_65$$=$JSCompiler_i$jscomp$inline_64$$+1;else if(0<$JSCompiler_i$jscomp$inline_64$$&&this.$queue_$[$JSCompiler_i$jscomp$inline_64$$-1].priority>=$JSCompiler_target$jscomp$inline_63$$)$JSCompiler_hi$jscomp$inline_66$$=$JSCompiler_i$jscomp$inline_64$$-1;else break}this.$queue_$.splice($JSCompiler_i$jscomp$inline_64$$,
0,{item:$item$$,priority:$priority$$})};$PriorityQueue$$module$src$utils$priority_queue$$.prototype.forEach=function($callback$jscomp$66$$){for(var $index$jscomp$69$$=this.$queue_$.length;$index$jscomp$69$$--;)$callback$jscomp$66$$(this.$queue_$[$index$jscomp$69$$].item)};$PriorityQueue$$module$src$utils$priority_queue$$.prototype.dequeue=function(){return this.$queue_$.length?this.$queue_$.pop().item:null};
$$jscomp$global$$.Object.defineProperties($PriorityQueue$$module$src$utils$priority_queue$$.prototype,{length:{configurable:!0,enumerable:!0,get:function(){return this.$queue_$.length}}});var $deactivated$$module$src$chunk$$=/nochunking=1/.test(self.location.hash),$resolved$$module$src$chunk$$=Promise.resolve();
function $chunk$$module$src$chunk$$($elementOrAmpDoc$jscomp$19$$,$fn$jscomp$4$$){if($deactivated$$module$src$chunk$$)$resolved$$module$src$chunk$$.then($fn$jscomp$4$$);else{var $JSCompiler_constructor$jscomp$inline_104$$=$Chunks$$module$src$chunk$$,$JSCompiler_ampdoc$jscomp$inline_105$$=$getAmpdoc$$module$src$service$$($elementOrAmpDoc$jscomp$19$$),$JSCompiler_holder$jscomp$inline_106$$=$getAmpdocServiceHolder$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_105$$),$JSCompiler_services$jscomp$inline_124$$=
$getServices$$module$src$service$$($JSCompiler_holder$jscomp$inline_106$$),$JSCompiler_s$jscomp$inline_125$$=$JSCompiler_services$jscomp$inline_124$$.chunk;$JSCompiler_s$jscomp$inline_125$$||($JSCompiler_s$jscomp$inline_125$$=$JSCompiler_services$jscomp$inline_124$$.chunk={obj:null,promise:null,resolve:null,reject:null,context:null,ctor:null});$JSCompiler_s$jscomp$inline_125$$.ctor||$JSCompiler_s$jscomp$inline_125$$.obj||($JSCompiler_s$jscomp$inline_125$$.ctor=$JSCompiler_constructor$jscomp$inline_104$$,
$JSCompiler_s$jscomp$inline_125$$.context=$JSCompiler_ampdoc$jscomp$inline_105$$,$JSCompiler_s$jscomp$inline_125$$.resolve&&$getServiceInternal$$module$src$service$$($JSCompiler_holder$jscomp$inline_106$$,"chunk"));$getServiceForDoc$$module$src$service$$($elementOrAmpDoc$jscomp$19$$,"chunk").run($fn$jscomp$4$$,10)}}function $Task$$module$src$chunk$$($fn$jscomp$5$$){this.state="not_run";this.$fn_$=$fn$jscomp$5$$}
function $JSCompiler_StaticMethods_runTask_$$($JSCompiler_StaticMethods_runTask_$self$$,$idleDeadline$$){if("run"!=$JSCompiler_StaticMethods_runTask_$self$$.state){$JSCompiler_StaticMethods_runTask_$self$$.state="run";try{$JSCompiler_StaticMethods_runTask_$self$$.$fn_$($idleDeadline$$)}catch($e$jscomp$21$$){throw $JSCompiler_StaticMethods_runTask_$self$$.$onTaskError_$(),$e$jscomp$21$$;}}}$Task$$module$src$chunk$$.prototype.$getName_$=function(){return this.$fn_$.displayName||this.$fn_$.name};
$Task$$module$src$chunk$$.prototype.$onTaskError_$=function(){};$Task$$module$src$chunk$$.prototype.$immediateTriggerCondition_$=function(){return!1};$Task$$module$src$chunk$$.prototype.$useRequestIdleCallback_$=function(){return!0};
function $StartupTask$$module$src$chunk$$($fn$jscomp$6$$,$win$jscomp$48$$,$viewerPromise$$){$Task$$module$src$chunk$$.call(this,$fn$jscomp$6$$);var $$jscomp$this$jscomp$2$$=this;this.$win_$=$win$jscomp$48$$;this.$viewer_$=null;$viewerPromise$$.then(function($fn$jscomp$6$$){$$jscomp$this$jscomp$2$$.$viewer_$=$fn$jscomp$6$$;$$jscomp$this$jscomp$2$$.$viewer_$.isVisible()&&$JSCompiler_StaticMethods_runTask_$$($$jscomp$this$jscomp$2$$,null);$$jscomp$this$jscomp$2$$.$viewer_$.onVisibilityChanged(function(){$$jscomp$this$jscomp$2$$.$viewer_$.isVisible()&&
$JSCompiler_StaticMethods_runTask_$$($$jscomp$this$jscomp$2$$,null)})})}$$jscomp$inherits$$($StartupTask$$module$src$chunk$$,$Task$$module$src$chunk$$);
$StartupTask$$module$src$chunk$$.prototype.$onTaskError_$=function(){var $JSCompiler_doc$jscomp$inline_70_JSCompiler_element$jscomp$inline_109$$=self.document;if(!$bodyMadeVisible$$module$src$style_installer$$){$bodyMadeVisible$$module$src$style_installer$$=!0;$JSCompiler_doc$jscomp$inline_70_JSCompiler_element$jscomp$inline_109$$=$JSCompiler_doc$jscomp$inline_70_JSCompiler_element$jscomp$inline_109$$.body;var $JSCompiler_styles$jscomp$inline_110$$={opacity:1,visibility:"visible",animation:"none"},
$JSCompiler_k$jscomp$inline_111$$;for($JSCompiler_k$jscomp$inline_111$$ in $JSCompiler_styles$jscomp$inline_110$$){var $JSCompiler_element$jscomp$inline_127$$=$JSCompiler_doc$jscomp$inline_70_JSCompiler_element$jscomp$inline_109$$,$JSCompiler_value$jscomp$inline_129$$=$JSCompiler_styles$jscomp$inline_110$$[$JSCompiler_k$jscomp$inline_111$$];var $JSCompiler_propertyName$jscomp$inline_131_JSCompiler_style$jscomp$inline_135$$=$JSCompiler_element$jscomp$inline_127$$.style;var $JSCompiler_camelCase$jscomp$inline_136$$=
$JSCompiler_k$jscomp$inline_111$$;if(2>$JSCompiler_camelCase$jscomp$inline_136$$.length?0:0==$JSCompiler_camelCase$jscomp$inline_136$$.lastIndexOf("--",0))$JSCompiler_propertyName$jscomp$inline_131_JSCompiler_style$jscomp$inline_135$$=$JSCompiler_camelCase$jscomp$inline_136$$;else{$propertyNameCache$$module$src$style$$||($propertyNameCache$$module$src$style$$=Object.create(null));var $JSCompiler_propertyName$jscomp$inline_138$$=$propertyNameCache$$module$src$style$$[$JSCompiler_camelCase$jscomp$inline_136$$];
if(!$JSCompiler_propertyName$jscomp$inline_138$$){$JSCompiler_propertyName$jscomp$inline_138$$=$JSCompiler_camelCase$jscomp$inline_136$$;if(void 0===$JSCompiler_propertyName$jscomp$inline_131_JSCompiler_style$jscomp$inline_135$$[$JSCompiler_camelCase$jscomp$inline_136$$]){var $JSCompiler_prefixedPropertyName$jscomp$inline_140_JSCompiler_titleCase$jscomp$inline_139$$=$JSCompiler_camelCase$jscomp$inline_136$$.charAt(0).toUpperCase()+$JSCompiler_camelCase$jscomp$inline_136$$.slice(1);b:{for(var $JSCompiler_i$jscomp$inline_148$$=
0;$JSCompiler_i$jscomp$inline_148$$<$vendorPrefixes$$module$src$style$$.length;$JSCompiler_i$jscomp$inline_148$$++){var $JSCompiler_propertyName$jscomp$inline_149$$=$vendorPrefixes$$module$src$style$$[$JSCompiler_i$jscomp$inline_148$$]+$JSCompiler_prefixedPropertyName$jscomp$inline_140_JSCompiler_titleCase$jscomp$inline_139$$;if(void 0!==$JSCompiler_propertyName$jscomp$inline_131_JSCompiler_style$jscomp$inline_135$$[$JSCompiler_propertyName$jscomp$inline_149$$]){$JSCompiler_prefixedPropertyName$jscomp$inline_140_JSCompiler_titleCase$jscomp$inline_139$$=
$JSCompiler_propertyName$jscomp$inline_149$$;break b}}$JSCompiler_prefixedPropertyName$jscomp$inline_140_JSCompiler_titleCase$jscomp$inline_139$$=""}void 0!==$JSCompiler_propertyName$jscomp$inline_131_JSCompiler_style$jscomp$inline_135$$[$JSCompiler_prefixedPropertyName$jscomp$inline_140_JSCompiler_titleCase$jscomp$inline_139$$]&&($JSCompiler_propertyName$jscomp$inline_138$$=$JSCompiler_prefixedPropertyName$jscomp$inline_140_JSCompiler_titleCase$jscomp$inline_139$$)}$propertyNameCache$$module$src$style$$[$JSCompiler_camelCase$jscomp$inline_136$$]=
$JSCompiler_propertyName$jscomp$inline_138$$}$JSCompiler_propertyName$jscomp$inline_131_JSCompiler_style$jscomp$inline_135$$=$JSCompiler_propertyName$jscomp$inline_138$$}$JSCompiler_propertyName$jscomp$inline_131_JSCompiler_style$jscomp$inline_135$$&&($JSCompiler_element$jscomp$inline_127$$.style[$JSCompiler_propertyName$jscomp$inline_131_JSCompiler_style$jscomp$inline_135$$]=$JSCompiler_value$jscomp$inline_129$$)}}};
$StartupTask$$module$src$chunk$$.prototype.$immediateTriggerCondition_$=function(){return this.$viewer_$?this.$viewer_$.isVisible():this.$win_$.document.hidden?!1:!/visibilityState=(hidden|prerender)/.test(this.$win_$.location.hash)};$StartupTask$$module$src$chunk$$.prototype.$useRequestIdleCallback_$=function(){return!!this.$viewer_$};
function $Chunks$$module$src$chunk$$($ampDoc$$){var $$jscomp$this$jscomp$3$$=this;this.$win_$=$ampDoc$$.win;this.$tasks_$=new $PriorityQueue$$module$src$utils$priority_queue$$;this.$boundExecute_$=this.$execute_$.bind(this);this.$viewerPromise_$=$getServicePromiseInternal$$module$src$service$$($getAmpdocServiceHolder$$module$src$service$$($ampDoc$$),"viewer");this.$win_$.addEventListener("message",function($ampDoc$$){"amp-macro-task"==$ampDoc$$.data&&$$jscomp$this$jscomp$3$$.$execute_$(null)})}
$Chunks$$module$src$chunk$$.prototype.run=function($fn$jscomp$7$$,$priority$jscomp$2$$){var $t$$=new $Task$$module$src$chunk$$($fn$jscomp$7$$);$JSCompiler_StaticMethods_enqueueTask_$$(this,$t$$,$priority$jscomp$2$$)};
$Chunks$$module$src$chunk$$.prototype.runForStartup=function($fn$jscomp$8_t$jscomp$1$$){$fn$jscomp$8_t$jscomp$1$$=new $StartupTask$$module$src$chunk$$($fn$jscomp$8_t$jscomp$1$$,this.$win_$,this.$viewerPromise_$);$JSCompiler_StaticMethods_enqueueTask_$$(this,$fn$jscomp$8_t$jscomp$1$$,Number.POSITIVE_INFINITY)};
function $JSCompiler_StaticMethods_enqueueTask_$$($JSCompiler_StaticMethods_enqueueTask_$self$$,$task$$,$priority$jscomp$3$$){$JSCompiler_StaticMethods_enqueueTask_$self$$.$tasks_$.enqueue($task$$,$priority$jscomp$3$$);$resolved$$module$src$chunk$$.then(function(){$JSCompiler_StaticMethods_schedule_$$($JSCompiler_StaticMethods_enqueueTask_$self$$)})}
function $JSCompiler_StaticMethods_nextTask_$$($JSCompiler_StaticMethods_nextTask_$self$$,$opt_dequeue$$){for(var $t$jscomp$2$$=$JSCompiler_StaticMethods_nextTask_$self$$.$tasks_$.peek();$t$jscomp$2$$&&"not_run"!==$t$jscomp$2$$.state;)$JSCompiler_StaticMethods_nextTask_$self$$.$tasks_$.dequeue(),$t$jscomp$2$$=$JSCompiler_StaticMethods_nextTask_$self$$.$tasks_$.peek();$t$jscomp$2$$&&$opt_dequeue$$&&$JSCompiler_StaticMethods_nextTask_$self$$.$tasks_$.dequeue();return $t$jscomp$2$$}
$Chunks$$module$src$chunk$$.prototype.$execute_$=function($idleDeadline$jscomp$1$$){var $$jscomp$this$jscomp$5$$=this,$t$jscomp$3$$=$JSCompiler_StaticMethods_nextTask_$$(this,!0);if(!$t$jscomp$3$$)return!1;$JSCompiler_StaticMethods_runTask_$$($t$jscomp$3$$,$idleDeadline$jscomp$1$$);$resolved$$module$src$chunk$$.then(function(){$JSCompiler_StaticMethods_schedule_$$($$jscomp$this$jscomp$5$$)});return!0};
function $JSCompiler_StaticMethods_executeAsap_$$($JSCompiler_StaticMethods_executeAsap_$self$$){$resolved$$module$src$chunk$$.then(function(){$JSCompiler_StaticMethods_executeAsap_$self$$.$boundExecute_$(null)})}
function $JSCompiler_StaticMethods_schedule_$$($JSCompiler_StaticMethods_schedule_$self$$){var $nextTask$$=$JSCompiler_StaticMethods_nextTask_$$($JSCompiler_StaticMethods_schedule_$self$$);$nextTask$$&&($nextTask$$.$immediateTriggerCondition_$()?$JSCompiler_StaticMethods_executeAsap_$$($JSCompiler_StaticMethods_schedule_$self$$):$nextTask$$.$useRequestIdleCallback_$()&&$JSCompiler_StaticMethods_schedule_$self$$.$win_$.requestIdleCallback?$onIdle$$module$src$chunk$$($JSCompiler_StaticMethods_schedule_$self$$.$win_$,
$JSCompiler_StaticMethods_schedule_$self$$.$boundExecute_$):$JSCompiler_StaticMethods_schedule_$self$$.$win_$.postMessage("amp-macro-task","*"))}
function $onIdle$$module$src$chunk$$($win$jscomp$49$$,$fn$jscomp$9$$){function $rIC$$($info$$){if($info$$.timeRemaining()<$minimumTimeRemaining$$){var $remainingTimeout$$=2E3-(Date.now()-$startTime$jscomp$7$$);0>=$remainingTimeout$$||$info$$.didTimeout?$fn$jscomp$9$$($info$$):$win$jscomp$49$$.requestIdleCallback($rIC$$,{timeout:$remainingTimeout$$})}else $fn$jscomp$9$$($info$$)}var $minimumTimeRemaining$$=15,$startTime$jscomp$7$$=Date.now();$win$jscomp$49$$.requestIdleCallback($rIC$$,{timeout:2E3})}
;function $LinkReplacementCache$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_replacement_cache$$(){this.$anchorList_$=[];this.$replacementList_$=[]}$LinkReplacementCache$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_replacement_cache$$.prototype.updateLinkList=function($newAnchorList$$){this.$replacementList_$=$newAnchorList$$.map(this.getReplacementUrlForAnchor.bind(this));this.$anchorList_$=$newAnchorList$$};
$LinkReplacementCache$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_replacement_cache$$.prototype.updateReplacementUrls=function($replacementList$$){var $$jscomp$this$jscomp$7$$=this;$replacementList$$.forEach(function($replacementList$$){var $$jscomp$destructuring$var13$$=$replacementList$$.anchor,$replacementUrl$$=$replacementList$$.replacementUrl,$anchorIndex$$=$$jscomp$this$jscomp$7$$.$anchorList_$.indexOf($$jscomp$destructuring$var13$$);-1!==$anchorIndex$$&&($$jscomp$this$jscomp$7$$.$replacementList_$[$anchorIndex$$]=
$replacementUrl$$)})};$LinkReplacementCache$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_replacement_cache$$.prototype.getReplacementUrlForAnchor=function($anchor$jscomp$1_index$jscomp$70$$){$anchor$jscomp$1_index$jscomp$70$$=this.$anchorList_$.indexOf($anchor$jscomp$1_index$jscomp$70$$);return-1!==$anchor$jscomp$1_index$jscomp$70$$?this.$replacementList_$[$anchor$jscomp$1_index$jscomp$70$$]:null};
$LinkReplacementCache$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_replacement_cache$$.prototype.isInCache=function($anchor$jscomp$2$$){return-1!==this.$anchorList_$.indexOf($anchor$jscomp$2$$)};$LinkReplacementCache$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_replacement_cache$$.prototype.getAnchorReplacementList=function(){var $$jscomp$this$jscomp$8$$=this;return this.$anchorList_$.map(function($anchor$jscomp$3$$){return{anchor:$anchor$jscomp$3$$,replacementUrl:$$jscomp$this$jscomp$8$$.getReplacementUrlForAnchor($anchor$jscomp$3$$)}})};function $Observable$$module$src$observable$$(){this.$handlers_$=null}$Observable$$module$src$observable$$.prototype.add=function($handler$jscomp$4$$){var $$jscomp$this$jscomp$9$$=this;this.$handlers_$||(this.$handlers_$=[]);this.$handlers_$.push($handler$jscomp$4$$);return function(){$$jscomp$this$jscomp$9$$.remove($handler$jscomp$4$$)}};
$Observable$$module$src$observable$$.prototype.remove=function($handler$jscomp$5_index$jscomp$71$$){this.$handlers_$&&($handler$jscomp$5_index$jscomp$71$$=this.$handlers_$.indexOf($handler$jscomp$5_index$jscomp$71$$),-1<$handler$jscomp$5_index$jscomp$71$$&&this.$handlers_$.splice($handler$jscomp$5_index$jscomp$71$$,1))};$Observable$$module$src$observable$$.prototype.removeAll=function(){this.$handlers_$&&(this.$handlers_$.length=0)};
$Observable$$module$src$observable$$.prototype.fire=function($opt_event$$){if(this.$handlers_$)for(var $handlers$$=this.$handlers_$,$i$jscomp$17$$=0;$i$jscomp$17$$<$handlers$$.length;$i$jscomp$17$$++)(0,$handlers$$[$i$jscomp$17$$])($opt_event$$)};$Observable$$module$src$observable$$.prototype.getHandlerCount=function(){return this.$handlers_$?this.$handlers_$.length:0};function $TwoStepsResponse$$module$extensions$amp_skimlinks$0_1$link_rewriter$two_steps_response$$($syncResponse$$,$asyncResponse$$){this.syncResponse=$syncResponse$$;this.asyncResponse=$asyncResponse$$};function $LinkRewriter$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_rewriter$$($rootNode$jscomp$2$$,$id$jscomp$35$$,$resolveUnknownLinks$$,$options$jscomp$15$$){this.events=new $Observable$$module$src$observable$$;this.id=$id$jscomp$35$$;this.$rootNode_$=$rootNode$jscomp$2$$;this.$resolveUnknownLinks_$=$resolveUnknownLinks$$;this.$linkSelector_$=$options$jscomp$15$$.linkSelector||"a";this.$restoreDelay_$=300;this.$anchorReplacementCache_$=new $LinkReplacementCache$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_replacement_cache$$}
$LinkRewriter$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_rewriter$$.prototype.getReplacementUrl=function($anchor$jscomp$4$$){return this.isWatchingLink($anchor$jscomp$4$$)?this.$anchorReplacementCache_$.getReplacementUrlForAnchor($anchor$jscomp$4$$):null};$LinkRewriter$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_rewriter$$.prototype.getAnchorReplacementList=function(){return this.$anchorReplacementCache_$.getAnchorReplacementList()};
$LinkRewriter$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_rewriter$$.prototype.isWatchingLink=function($anchor$jscomp$5$$){return this.$anchorReplacementCache_$.isInCache($anchor$jscomp$5$$)};
$LinkRewriter$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_rewriter$$.prototype.rewriteAnchorUrl=function($anchor$jscomp$6$$){var $newUrl$$=this.getReplacementUrl($anchor$jscomp$6$$);if(!$newUrl$$||$newUrl$$===$anchor$jscomp$6$$.href)return!1;$anchor$jscomp$6$$.setAttribute("data-link-rewriter-original-url",$anchor$jscomp$6$$.href);$anchor$jscomp$6$$.href=$newUrl$$;setTimeout(function(){$anchor$jscomp$6$$.href=$anchor$jscomp$6$$.getAttribute("data-link-rewriter-original-url");$anchor$jscomp$6$$.removeAttribute("data-link-rewriter-original-url")},
this.$restoreDelay_$);return!0};
$LinkRewriter$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_rewriter$$.prototype.onDomUpdated=function(){var $$jscomp$this$jscomp$10$$=this;return new Promise(function($resolve$jscomp$12$$){var $elementOrShadowRoot$$=$$jscomp$this$jscomp$10$$.$rootNode_$.nodeType==Node.DOCUMENT_NODE?$$jscomp$this$jscomp$10$$.$rootNode_$.documentElement:$$jscomp$this$jscomp$10$$.$rootNode_$;$chunk$$module$src$chunk$$($elementOrShadowRoot$$,function(){return $JSCompiler_StaticMethods_scanLinksOnPage_$$($$jscomp$this$jscomp$10$$).then(function(){$$jscomp$this$jscomp$10$$.events.fire({type:"PAGE_SCANNED"});$resolve$jscomp$12$$()})})})};
function $JSCompiler_StaticMethods_scanLinksOnPage_$$($JSCompiler_StaticMethods_scanLinksOnPage_$self$$){var $anchorList$$=$JSCompiler_StaticMethods_getLinksInDOM_$$($JSCompiler_StaticMethods_scanLinksOnPage_$self$$),$unknownAnchors$$=$JSCompiler_StaticMethods_getUnknownAnchors_$$($JSCompiler_StaticMethods_scanLinksOnPage_$self$$,$anchorList$$);$JSCompiler_StaticMethods_scanLinksOnPage_$self$$.$anchorReplacementCache_$.updateLinkList($anchorList$$);if(!$unknownAnchors$$.length)return Promise.resolve();
$JSCompiler_StaticMethods_scanLinksOnPage_$self$$.$anchorReplacementCache_$.updateReplacementUrls($unknownAnchors$$.map(function($JSCompiler_StaticMethods_scanLinksOnPage_$self$$){return{anchor:$JSCompiler_StaticMethods_scanLinksOnPage_$self$$,replacementUrl:null}}));var $twoStepsResponse$$=$JSCompiler_StaticMethods_scanLinksOnPage_$self$$.$resolveUnknownLinks_$($unknownAnchors$$);if(!$logs$$module$src$log$$.user)throw Error("failed to call initLogConstructor");$logs$$module$src$log$$.user.assert($twoStepsResponse$$ instanceof
$TwoStepsResponse$$module$extensions$amp_skimlinks$0_1$link_rewriter$two_steps_response$$,'Invalid response from provided "resolveUnknownLinks" function."resolveUnknownLinks" should return an instance of TwoStepsResponse',void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0);$twoStepsResponse$$.syncResponse&&$JSCompiler_StaticMethods_scanLinksOnPage_$self$$.$anchorReplacementCache_$.updateReplacementUrls($twoStepsResponse$$.syncResponse);return $twoStepsResponse$$.asyncResponse?$twoStepsResponse$$.asyncResponse.then(function($anchorList$$){$JSCompiler_StaticMethods_scanLinksOnPage_$self$$.$anchorReplacementCache_$.updateReplacementUrls($anchorList$$)}):
Promise.resolve()}function $JSCompiler_StaticMethods_getUnknownAnchors_$$($JSCompiler_StaticMethods_getUnknownAnchors_$self$$,$anchorList$jscomp$1$$){var $unknownAnchors$jscomp$1$$=[];$anchorList$jscomp$1$$.forEach(function($anchorList$jscomp$1$$){$JSCompiler_StaticMethods_getUnknownAnchors_$self$$.isWatchingLink($anchorList$jscomp$1$$)||$unknownAnchors$jscomp$1$$.push($anchorList$jscomp$1$$)});return $unknownAnchors$jscomp$1$$}
function $JSCompiler_StaticMethods_getLinksInDOM_$$($JSCompiler_StaticMethods_getLinksInDOM_$self$$){var $q$$=$JSCompiler_StaticMethods_getLinksInDOM_$self$$.$rootNode_$.querySelectorAll($JSCompiler_StaticMethods_getLinksInDOM_$self$$.$linkSelector_$);return[].slice.call($q$$)};$dict$$module$src$utils$object$$({c:!0,v:!0,a:!0,ad:!0,action:!0});function $LinkRewriterManager$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_rewriter_manager$$($ampdoc$jscomp$19$$){this.$rootNode_$=$ampdoc$jscomp$19$$.getRootNode();var $JSCompiler_value$jscomp$inline_75$$=$getServiceForDoc$$module$src$service$$($ampdoc$jscomp$19$$,"documentInfo").get().metaTags["amp-link-rewriter-priorities"];this.$priorityList_$=$JSCompiler_value$jscomp$inline_75$$?$JSCompiler_value$jscomp$inline_75$$.trim().split(/\s+/):[];this.$linkRewriters_$=[];this.$rootNode_$.addEventListener("amp:dom-update",
this.$onDomChanged_$.bind(this));var $navigation$$=$getServiceForDoc$$module$src$service$$($ampdoc$jscomp$19$$,"navigation");$navigation$$.registerAnchorMutator(this.maybeRewriteLink.bind(this),0)}
$LinkRewriterManager$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_rewriter_manager$$.prototype.registerLinkRewriter=function($linkRewriterId$$,$resolveUnknownLinks$jscomp$1$$,$options$jscomp$18$$){var $linkRewriter$$=new $LinkRewriter$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_rewriter$$(this.$rootNode_$,$linkRewriterId$$,$resolveUnknownLinks$jscomp$1$$,$options$jscomp$18$$);$JSCompiler_StaticMethods_insertInListBasedOnPriority_$$(this.$linkRewriters_$,$linkRewriter$$,this.$priorityList_$);
$linkRewriter$$.onDomUpdated();return $linkRewriter$$};
$LinkRewriterManager$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_rewriter_manager$$.prototype.maybeRewriteLink=function($anchor$jscomp$9$$,$event$jscomp$10$$){var $suitableLinkRewriters$$=$JSCompiler_StaticMethods_getSuitableLinkRewritersForLink_$$(this,$anchor$jscomp$9$$);if($suitableLinkRewriters$$.length){for(var $chosenLinkRewriter$$=null,$i$jscomp$26$$=0;$i$jscomp$26$$<$suitableLinkRewriters$$.length;$i$jscomp$26$$++){var $hasReplaced$$=$suitableLinkRewriters$$[$i$jscomp$26$$].rewriteAnchorUrl($anchor$jscomp$9$$);
if($hasReplaced$$){$chosenLinkRewriter$$=$suitableLinkRewriters$$[$i$jscomp$26$$];break}}var $eventData$$={linkRewriterId:$chosenLinkRewriter$$?$chosenLinkRewriter$$.id:null,anchor:$anchor$jscomp$9$$,clickType:$event$jscomp$10$$.type};$suitableLinkRewriters$$.forEach(function($anchor$jscomp$9$$){$anchor$jscomp$9$$.events.fire({type:"CLICK",eventData:$eventData$$})})}};$LinkRewriterManager$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_rewriter_manager$$.prototype.$onDomChanged_$=function(){this.$linkRewriters_$.forEach(function($linkRewriter$jscomp$2$$){$linkRewriter$jscomp$2$$.onDomUpdated()})};
function $JSCompiler_StaticMethods_parseLinkRewriterPriorityForAnchor_$$($anchor$jscomp$10$$){var $dataValue$$=$anchor$jscomp$10$$.hasAttribute("data-link-rewriters")?$anchor$jscomp$10$$.getAttribute("data-link-rewriters").trim():null;return $dataValue$$?$dataValue$$.split(/\s+/):[]}
function $JSCompiler_StaticMethods_insertInListBasedOnPriority_$$($linkRewriterList$$,$linkRewriter$jscomp$3$$,$idPriorityList$$){function $compareFunction$$($linkRewriterList$$,$linkRewriter$jscomp$3$$){var $compareFunction$$=$idPriorityList$$.indexOf($linkRewriterList$$.id),$linkRewriterA$$=$idPriorityList$$.indexOf($linkRewriter$jscomp$3$$.id);return-1===$compareFunction$$&&-1===$linkRewriterA$$?0:-1===$compareFunction$$?$B_HAS_PRIORITY$$:-1===$linkRewriterA$$?$A_HAS_PRIORITY$$:$compareFunction$$>
$linkRewriterA$$?$B_HAS_PRIORITY$$:$A_HAS_PRIORITY$$}var $B_HAS_PRIORITY$$=1,$A_HAS_PRIORITY$$=-1;$linkRewriterList$$.push($linkRewriter$jscomp$3$$);$linkRewriterList$$.sort($compareFunction$$)}
function $JSCompiler_StaticMethods_getSuitableLinkRewritersForLink_$$($JSCompiler_StaticMethods_getSuitableLinkRewritersForLink_$self$$,$anchor$jscomp$11$$){var $linkPriorityList$$=$JSCompiler_StaticMethods_parseLinkRewriterPriorityForAnchor_$$($anchor$jscomp$11$$);return $JSCompiler_StaticMethods_getSuitableLinkRewritersForLink_$self$$.$linkRewriters_$.reduce(function($JSCompiler_StaticMethods_getSuitableLinkRewritersForLink_$self$$,$linkRewriter$jscomp$4$$){$linkRewriter$jscomp$4$$.isWatchingLink($anchor$jscomp$11$$)&&
$JSCompiler_StaticMethods_insertInListBasedOnPriority_$$($JSCompiler_StaticMethods_getSuitableLinkRewritersForLink_$self$$,$linkRewriter$jscomp$4$$,$linkPriorityList$$);return $JSCompiler_StaticMethods_getSuitableLinkRewritersForLink_$self$$},[])};function $deepEquals$$module$src$json$$($a$jscomp$2_queue$jscomp$1$$,$a$6_b$jscomp$2$$){var $b$7_depth$jscomp$9$$=void 0===$b$7_depth$jscomp$9$$?5:$b$7_depth$jscomp$9$$;if(!isFinite($b$7_depth$jscomp$9$$)||0>$b$7_depth$jscomp$9$$)throw Error("Invalid depth: "+$b$7_depth$jscomp$9$$);if($a$jscomp$2_queue$jscomp$1$$===$a$6_b$jscomp$2$$)return!0;for($a$jscomp$2_queue$jscomp$1$$=[{a:$a$jscomp$2_queue$jscomp$1$$,b:$a$6_b$jscomp$2$$,depth:$b$7_depth$jscomp$9$$}];0<$a$jscomp$2_queue$jscomp$1$$.length;){var $$jscomp$destructuring$var22_depth$8$$=
$a$jscomp$2_queue$jscomp$1$$.shift();$a$6_b$jscomp$2$$=$$jscomp$destructuring$var22_depth$8$$.a;$b$7_depth$jscomp$9$$=$$jscomp$destructuring$var22_depth$8$$.b;$$jscomp$destructuring$var22_depth$8$$=$$jscomp$destructuring$var22_depth$8$$.depth;if(0<$$jscomp$destructuring$var22_depth$8$$){if(typeof $a$6_b$jscomp$2$$!==typeof $b$7_depth$jscomp$9$$)return!1;if(Array.isArray($a$6_b$jscomp$2$$)&&Array.isArray($b$7_depth$jscomp$9$$)){if($a$6_b$jscomp$2$$.length!==$b$7_depth$jscomp$9$$.length)return!1;for(var $i$9_i$jscomp$28$$=
0;$i$9_i$jscomp$28$$<$a$6_b$jscomp$2$$.length;$i$9_i$jscomp$28$$++)$a$jscomp$2_queue$jscomp$1$$.push({a:$a$6_b$jscomp$2$$[$i$9_i$jscomp$28$$],b:$b$7_depth$jscomp$9$$[$i$9_i$jscomp$28$$],depth:$$jscomp$destructuring$var22_depth$8$$-1});continue}else if($a$6_b$jscomp$2$$&&$b$7_depth$jscomp$9$$&&"object"===typeof $a$6_b$jscomp$2$$&&"object"===typeof $b$7_depth$jscomp$9$$){var $keysA$$=Object.keys($a$6_b$jscomp$2$$),$keysB$$=Object.keys($b$7_depth$jscomp$9$$);if($keysA$$.length!==$keysB$$.length)return!1;
for($i$9_i$jscomp$28$$=0;$i$9_i$jscomp$28$$<$keysA$$.length;$i$9_i$jscomp$28$$++){var $k$jscomp$5$$=$keysA$$[$i$9_i$jscomp$28$$];$a$jscomp$2_queue$jscomp$1$$.push({a:$a$6_b$jscomp$2$$[$k$jscomp$5$$],b:$b$7_depth$jscomp$9$$[$k$jscomp$5$$],depth:$$jscomp$destructuring$var22_depth$8$$-1})}continue}}if($a$6_b$jscomp$2$$!==$b$7_depth$jscomp$9$$)return!1}return!0};function $Linkmate$$module$extensions$amp_smartlinks$0_1$linkmate$$($ampDoc$jscomp$1$$,$xhr$$,$linkmateOptions$$){this.$ampDoc_$=$ampDoc$jscomp$1$$;this.$xhr_$=$xhr$$;this.$requestExclusiveLinks_$=$linkmateOptions$$.exclusiveLinks;this.$publisherID_$=$linkmateOptions$$.publisherID;this.$linkAttribute_$=$linkmateOptions$$.linkAttribute;this.$rootNode_$=this.$ampDoc_$.getRootNode();this.$linkmateResponse_$=this.$anchorList_$=null}
$Linkmate$$module$extensions$amp_smartlinks$0_1$linkmate$$.prototype.runLinkmate=function($anchorList$jscomp$2$$){var $$jscomp$this$jscomp$17$$=this,$syncMappedLinks$$=null,$anchorListChanged$$=this.$anchorList_$&&!$deepEquals$$module$src$json$$(this.$anchorList_$,$anchorList$jscomp$2$$);this.$linkmateResponse_$&&$anchorListChanged$$&&($syncMappedLinks$$=$JSCompiler_StaticMethods_mapLinks_$$(this));if(!this.$linkmateResponse_$||$anchorListChanged$$){var $asyncMappedLinks$$=$JSCompiler_StaticMethods_postToLinkmate_$$(this,
$anchorList$jscomp$2$$).then(function($syncMappedLinks$$){$$jscomp$this$jscomp$17$$.$linkmateResponse_$=$syncMappedLinks$$.data[0].smart_links;$$jscomp$this$jscomp$17$$.$anchorList_$=$anchorList$jscomp$2$$;return $JSCompiler_StaticMethods_mapLinks_$$($$jscomp$this$jscomp$17$$)});return new $TwoStepsResponse$$module$extensions$amp_skimlinks$0_1$link_rewriter$two_steps_response$$($syncMappedLinks$$,$asyncMappedLinks$$)}this.$anchorList_$=$anchorList$jscomp$2$$;return new $TwoStepsResponse$$module$extensions$amp_skimlinks$0_1$link_rewriter$two_steps_response$$($syncMappedLinks$$,
null)};
function $JSCompiler_StaticMethods_postToLinkmate_$$($JSCompiler_StaticMethods_postToLinkmate_$self$$,$anchorList$jscomp$3_payload$jscomp$1$$){var $linksPayload$$=$JSCompiler_StaticMethods_buildLinksPayload_$$($JSCompiler_StaticMethods_postToLinkmate_$self$$,$anchorList$jscomp$3_payload$jscomp$1$$),$editPayload$$=$dict$$module$src$utils$object$$({name:$JSCompiler_StaticMethods_postToLinkmate_$self$$.$rootNode_$.title||null,url:$JSCompiler_StaticMethods_postToLinkmate_$self$$.$ampDoc_$.getUrl()});$anchorList$jscomp$3_payload$jscomp$1$$=
$dict$$module$src$utils$object$$({article:$editPayload$$,links:$linksPayload$$});var $fetchUrl$$="https://api.narrativ.com/api/v1/publishers/.pub_id./linkmate/smart_links/".replace(".pub_id.",$JSCompiler_StaticMethods_postToLinkmate_$self$$.$publisherID_$.toString()),$postOptions$$={method:"POST",ampCors:!1,headers:$dict$$module$src$utils$object$$({"Content-Type":"application/json"}),body:$anchorList$jscomp$3_payload$jscomp$1$$};return $JSCompiler_StaticMethods_postToLinkmate_$self$$.$xhr_$.fetchJson($fetchUrl$$,
$postOptions$$).then(function($JSCompiler_StaticMethods_postToLinkmate_$self$$){return $JSCompiler_StaticMethods_postToLinkmate_$self$$.json()})}
function $JSCompiler_StaticMethods_buildLinksPayload_$$($JSCompiler_StaticMethods_buildLinksPayload_$self$$,$anchorList$jscomp$4$$){var $postLinks$$=[];$anchorList$jscomp$4$$.forEach(function($anchorList$jscomp$4$$){var $anchor$jscomp$12$$=$anchorList$jscomp$4$$.getAttribute($JSCompiler_StaticMethods_buildLinksPayload_$self$$.$linkAttribute_$);if(/shop-links.co/.test($anchor$jscomp$12$$))/\?amp=true$/.test($anchor$jscomp$12$$)||($anchorList$jscomp$4$$[$JSCompiler_StaticMethods_buildLinksPayload_$self$$.$linkAttribute_$]+=
"?amp=true");else if(!/#donotlink$/.test($anchor$jscomp$12$$)){var $exclusive$$=$JSCompiler_StaticMethods_buildLinksPayload_$self$$.$requestExclusiveLinks_$||/#locklink$/.test($anchor$jscomp$12$$),$linkObj$$={raw_url:$anchor$jscomp$12$$,exclusive_match_requested:$exclusive$$};$postLinks$$.push($linkObj$$)}});return $postLinks$$}
function $JSCompiler_StaticMethods_mapLinks_$$($JSCompiler_StaticMethods_mapLinks_$self$$){var $mappings$$=[];$JSCompiler_StaticMethods_mapLinks_$self$$.$anchorList_$.forEach(function($anchor$jscomp$13$$){$JSCompiler_StaticMethods_mapLinks_$self$$.$linkmateResponse_$.forEach(function($smartLink$$){$anchor$jscomp$13$$.getAttribute($JSCompiler_StaticMethods_mapLinks_$self$$.$linkAttribute_$)===$smartLink$$.url&&$smartLink$$.auction_id&&$mappings$$.push({anchor:$anchor$jscomp$13$$,replacementUrl:"https://shop-links.co/"+
$smartLink$$.auction_id+"/?amp=true"})})});return $mappings$$};function $getConfigOptions$$module$extensions$amp_smartlinks$0_1$linkmate_options$$($JSCompiler_linkSelector$jscomp$inline_87_element$jscomp$68$$){var $JSCompiler_inline_result$jscomp$29$$=$JSCompiler_linkSelector$jscomp$inline_87_element$jscomp$68$$.getAttribute("nrtv-account-name").toLowerCase();var $JSCompiler_temp_const$jscomp$31$$=!!$JSCompiler_linkSelector$jscomp$inline_87_element$jscomp$68$$.hasAttribute("linkmate"),$JSCompiler_temp_const$jscomp$30$$=!!$JSCompiler_linkSelector$jscomp$inline_87_element$jscomp$68$$.hasAttribute("exclusive-links");
var $JSCompiler_inline_result$jscomp$33_JSCompiler_linkAttribute$jscomp$inline_84$$=($JSCompiler_inline_result$jscomp$33_JSCompiler_linkAttribute$jscomp$inline_84$$=$JSCompiler_linkSelector$jscomp$inline_87_element$jscomp$68$$.getAttribute("link-attribute"))?$JSCompiler_inline_result$jscomp$33_JSCompiler_linkAttribute$jscomp$inline_84$$.toLowerCase():"href";$JSCompiler_linkSelector$jscomp$inline_87_element$jscomp$68$$=$JSCompiler_linkSelector$jscomp$inline_87_element$jscomp$68$$.getAttribute("link-selector");
return{nrtvSlug:$JSCompiler_inline_result$jscomp$29$$,linkmateEnabled:$JSCompiler_temp_const$jscomp$31$$,exclusiveLinks:$JSCompiler_temp_const$jscomp$30$$,linkAttribute:$JSCompiler_inline_result$jscomp$33_JSCompiler_linkAttribute$jscomp$inline_84$$,linkSelector:$JSCompiler_linkSelector$jscomp$inline_87_element$jscomp$68$$?$JSCompiler_linkSelector$jscomp$inline_87_element$jscomp$68$$.toLowerCase():"a"}};function $AmpSmartlinks$$module$extensions$amp_smartlinks$0_1$amp_smartlinks$$($$jscomp$super$this_element$jscomp$74$$){$$jscomp$super$this_element$jscomp$74$$=AMP.BaseElement.call(this,$$jscomp$super$this_element$jscomp$74$$)||this;$$jscomp$super$this_element$jscomp$74$$.$xhr_$=null;$$jscomp$super$this_element$jscomp$74$$.$ampDoc_$=null;$$jscomp$super$this_element$jscomp$74$$.$linkRewriterService_$=null;$$jscomp$super$this_element$jscomp$74$$.$smartLinkRewriter_$=null;$$jscomp$super$this_element$jscomp$74$$.$linkmateOptions_$=
null;$$jscomp$super$this_element$jscomp$74$$.$linkmate_$=null;$$jscomp$super$this_element$jscomp$74$$.$referrer_$=null;return $$jscomp$super$this_element$jscomp$74$$}$$jscomp$inherits$$($AmpSmartlinks$$module$extensions$amp_smartlinks$0_1$amp_smartlinks$$,AMP.BaseElement);
$AmpSmartlinks$$module$extensions$amp_smartlinks$0_1$amp_smartlinks$$.prototype.buildCallback=function(){var $$jscomp$this$jscomp$20$$=this;this.$ampDoc_$=this.getAmpDoc();this.$xhr_$=$getService$$module$src$service$$(this.$ampDoc_$.win,"xhr");var $viewer$jscomp$5$$=$getServiceForDoc$$module$src$service$$(this.$ampDoc_$,"viewer");this.$linkmateOptions_$=$getConfigOptions$$module$extensions$amp_smartlinks$0_1$linkmate_options$$(this.element);this.$linkRewriterService_$=new $LinkRewriterManager$$module$extensions$amp_skimlinks$0_1$link_rewriter$link_rewriter_manager$$(this.$ampDoc_$);
return this.$ampDoc_$.whenBodyAvailable().then(function(){return $viewer$jscomp$5$$.getReferrerUrl()}).then(function($referrer$jscomp$2$$){$$jscomp$this$jscomp$20$$.$referrer_$=$referrer$jscomp$2$$;$viewer$jscomp$5$$.whenFirstVisible().then(function(){$JSCompiler_StaticMethods_runSmartlinks_$$($$jscomp$this$jscomp$20$$)})})};
function $JSCompiler_StaticMethods_runSmartlinks_$$($JSCompiler_StaticMethods_runSmartlinks_$self$$){$JSCompiler_StaticMethods_getLinkmateOptions_$$($JSCompiler_StaticMethods_runSmartlinks_$self$$).then(function($JSCompiler_inline_result$jscomp$96_config$jscomp$5$$){$JSCompiler_StaticMethods_runSmartlinks_$self$$.$linkmateOptions_$.linkmateExpected=$JSCompiler_inline_result$jscomp$96_config$jscomp$5$$.linkmate_enabled;$JSCompiler_StaticMethods_runSmartlinks_$self$$.$linkmateOptions_$.publisherID=
$JSCompiler_inline_result$jscomp$96_config$jscomp$5$$.publisher_id;$JSCompiler_StaticMethods_runSmartlinks_$self$$.signals().signal("load-start");$JSCompiler_inline_result$jscomp$96_config$jscomp$5$$=$dict$$module$src$utils$object$$({events:[{is_amp:!0}],organization_id:$JSCompiler_StaticMethods_runSmartlinks_$self$$.$linkmateOptions_$.publisherID,organization_type:"publisher",user:{page_session_uuid:$JSCompiler_StaticMethods_generateUUID_$$(),source_url:$JSCompiler_StaticMethods_runSmartlinks_$self$$.$ampDoc_$.getUrl(),
previous_url:$JSCompiler_StaticMethods_runSmartlinks_$self$$.$referrer_$,user_agent:$JSCompiler_StaticMethods_runSmartlinks_$self$$.$ampDoc_$.win.navigator.userAgent}});var $JSCompiler_builder$jscomp$inline_91$$=new $CustomEventReporterBuilder$$module$src$extension_analytics$$($JSCompiler_StaticMethods_runSmartlinks_$self$$.element);$JSCompiler_builder$jscomp$inline_91$$.track("page-impression","https://api.narrativ.com/api/v1/events/impressions/page_impression/");$JSCompiler_builder$jscomp$inline_91$$.setTransportConfig($dict$$module$src$utils$object$$({beacon:!0,
image:!1,xhrpost:!0,useBody:!0}));$JSCompiler_builder$jscomp$inline_91$$.setExtraUrlParams($JSCompiler_inline_result$jscomp$96_config$jscomp$5$$);$JSCompiler_builder$jscomp$inline_91$$.build().trigger("page-impression");$JSCompiler_StaticMethods_runSmartlinks_$self$$.$linkmate_$=new $Linkmate$$module$extensions$amp_smartlinks$0_1$linkmate$$($JSCompiler_StaticMethods_runSmartlinks_$self$$.$ampDoc_$,$JSCompiler_StaticMethods_runSmartlinks_$self$$.$xhr_$,$JSCompiler_StaticMethods_runSmartlinks_$self$$.$linkmateOptions_$);
$JSCompiler_StaticMethods_runSmartlinks_$self$$.$smartLinkRewriter_$=$JSCompiler_StaticMethods_initLinkRewriter_$$($JSCompiler_StaticMethods_runSmartlinks_$self$$);$JSCompiler_StaticMethods_runSmartlinks_$self$$.$linkmateOptions_$.linkmateEnabled&&$JSCompiler_StaticMethods_runSmartlinks_$self$$.$linkmateOptions_$.linkmateExpected&&$JSCompiler_StaticMethods_runSmartlinks_$self$$.$smartLinkRewriter_$.getAnchorReplacementList()})}
function $JSCompiler_StaticMethods_getLinkmateOptions_$$($JSCompiler_StaticMethods_getLinkmateOptions_$self$$){var $fetchUrl$jscomp$1$$="https://api.narrativ.com/api/v0/publishers/.nrtv_slug./amp_config/".replace(".nrtv_slug.",$JSCompiler_StaticMethods_getLinkmateOptions_$self$$.$linkmateOptions_$.nrtvSlug);try{return $JSCompiler_StaticMethods_getLinkmateOptions_$self$$.$xhr_$.fetchJson($fetchUrl$jscomp$1$$,{method:"GET",ampCors:!1}).then(function($JSCompiler_StaticMethods_getLinkmateOptions_$self$$){return $JSCompiler_StaticMethods_getLinkmateOptions_$self$$.json()}).then(function($JSCompiler_StaticMethods_getLinkmateOptions_$self$$){return $JSCompiler_StaticMethods_getLinkmateOptions_$self$$.data[0].amp_config})}catch($err$jscomp$6$$){return null}}
function $JSCompiler_StaticMethods_initLinkRewriter_$$($JSCompiler_StaticMethods_initLinkRewriter_$self$$){return $JSCompiler_StaticMethods_initLinkRewriter_$self$$.$linkRewriterService_$.registerLinkRewriter("amp-smartlinks",function($anchorList$jscomp$5$$){return $JSCompiler_StaticMethods_initLinkRewriter_$self$$.$linkmate_$.runLinkmate($anchorList$jscomp$5$$)},{linkSelector:$JSCompiler_StaticMethods_initLinkRewriter_$self$$.$linkmateOptions_$.linkSelector})}
function $JSCompiler_StaticMethods_generateUUID_$$(){return"10000000-1000-4000-8000-100000000000".replace(/[018]/g,function($c$jscomp$1$$){return($c$jscomp$1$$^crypto.getRandomValues(new Uint8Array(1))[0]&15>>$c$jscomp$1$$/4).toString(16)})}(function($AMP$jscomp$1$$){$AMP$jscomp$1$$.registerElement("amp-smartlinks",$AmpSmartlinks$$module$extensions$amp_smartlinks$0_1$amp_smartlinks$$)})(self.AMP);
})});

//# sourceMappingURL=amp-smartlinks-0.1.js.map
