(self.AMP=self.AMP||[]).push({n:"amp-instagram",v:"1904281823091",f:(function(AMP,_){
var $JSCompiler_prototypeAlias$$,$$jscomp$objectCreate$$="function"==typeof Object.create?Object.create:function($prototype$$){function $ctor$$(){}$ctor$$.prototype=$prototype$$;return new $ctor$$},$JSCompiler_temp$jscomp$13$$;
if("function"==typeof Object.setPrototypeOf)$JSCompiler_temp$jscomp$13$$=Object.setPrototypeOf;else{var $JSCompiler_inline_result$jscomp$14$$;a:{var $JSCompiler_x$jscomp$inline_16$$={a:!0},$JSCompiler_y$jscomp$inline_17$$={};try{$JSCompiler_y$jscomp$inline_17$$.__proto__=$JSCompiler_x$jscomp$inline_16$$;$JSCompiler_inline_result$jscomp$14$$=$JSCompiler_y$jscomp$inline_17$$.a;break a}catch($JSCompiler_e$jscomp$inline_18$$){}$JSCompiler_inline_result$jscomp$14$$=!1}$JSCompiler_temp$jscomp$13$$=$JSCompiler_inline_result$jscomp$14$$?
function($target$jscomp$83$$,$proto$jscomp$3$$){$target$jscomp$83$$.__proto__=$proto$jscomp$3$$;if($target$jscomp$83$$.__proto__!==$proto$jscomp$3$$)throw new TypeError($target$jscomp$83$$+" is not extensible");return $target$jscomp$83$$}:null}var $$jscomp$setPrototypeOf$$=$JSCompiler_temp$jscomp$13$$;var $optsSupported$$module$src$event_helper_listen$$;
function $internalListenImplementation$$module$src$event_helper_listen$$($element$jscomp$11$$,$listener$jscomp$62$$){var $opt_evtListenerOpts$$=void 0,$localElement$$=$element$jscomp$11$$,$localListener$$=$listener$jscomp$62$$;var $wrapped$$=function($element$jscomp$11$$){try{return $localListener$$($element$jscomp$11$$)}catch($e$jscomp$8$$){throw self.reportError($e$jscomp$8$$),$e$jscomp$8$$;}};var $optsSupported$$=$detectEvtListenerOptsSupport$$module$src$event_helper_listen$$(),$capture$$=!1;$opt_evtListenerOpts$$&&
($capture$$=$opt_evtListenerOpts$$.capture);$localElement$$.addEventListener("message",$wrapped$$,$optsSupported$$?$opt_evtListenerOpts$$:$capture$$);return function(){$localElement$$&&$localElement$$.removeEventListener("message",$wrapped$$,$optsSupported$$?$opt_evtListenerOpts$$:$capture$$);$wrapped$$=$localElement$$=$localListener$$=null}}
function $detectEvtListenerOptsSupport$$module$src$event_helper_listen$$(){if(void 0!==$optsSupported$$module$src$event_helper_listen$$)return $optsSupported$$module$src$event_helper_listen$$;$optsSupported$$module$src$event_helper_listen$$=!1;try{var $options$jscomp$14$$={get capture(){$optsSupported$$module$src$event_helper_listen$$=!0}};self.addEventListener("test-options",null,$options$jscomp$14$$);self.removeEventListener("test-options",null,$options$jscomp$14$$)}catch($err$jscomp$3$$){}return $optsSupported$$module$src$event_helper_listen$$}
;var $toString_$$module$src$types$$=Object.prototype.toString;self.log=self.log||{user:null,dev:null,userForEmbed:null};var $logs$$module$src$log$$=self.log;function $listen$$module$src$event_helper$$($element$jscomp$12$$,$listener$jscomp$63$$){return $internalListenImplementation$$module$src$event_helper_listen$$($element$jscomp$12$$,$listener$jscomp$63$$)};function $startsWith$$module$src$string$$($string$jscomp$6$$,$prefix$jscomp$2$$){return $prefix$jscomp$2$$.length>$string$jscomp$6$$.length?!1:0==$string$jscomp$6$$.lastIndexOf($prefix$jscomp$2$$,0)};var $propertyNameCache$$module$src$style$$,$vendorPrefixes$$module$src$style$$="Webkit webkit Moz moz ms O o".split(" ");
function $setStyles$$module$src$style$$($element$jscomp$19$$,$styles$jscomp$1$$){for(var $k$jscomp$2$$ in $styles$jscomp$1$$){var $JSCompiler_element$jscomp$inline_20$$=$element$jscomp$19$$,$JSCompiler_value$jscomp$inline_22$$=$styles$jscomp$1$$[$k$jscomp$2$$];var $JSCompiler_propertyName$jscomp$inline_25_JSCompiler_style$jscomp$inline_47$$=$JSCompiler_element$jscomp$inline_20$$.style;var $JSCompiler_camelCase$jscomp$inline_48$$=$k$jscomp$2$$;if($startsWith$$module$src$string$$($JSCompiler_camelCase$jscomp$inline_48$$,
"--"))$JSCompiler_propertyName$jscomp$inline_25_JSCompiler_style$jscomp$inline_47$$=$JSCompiler_camelCase$jscomp$inline_48$$;else{$propertyNameCache$$module$src$style$$||($propertyNameCache$$module$src$style$$=Object.create(null));var $JSCompiler_propertyName$jscomp$inline_50$$=$propertyNameCache$$module$src$style$$[$JSCompiler_camelCase$jscomp$inline_48$$];if(!$JSCompiler_propertyName$jscomp$inline_50$$){$JSCompiler_propertyName$jscomp$inline_50$$=$JSCompiler_camelCase$jscomp$inline_48$$;if(void 0===
$JSCompiler_propertyName$jscomp$inline_25_JSCompiler_style$jscomp$inline_47$$[$JSCompiler_camelCase$jscomp$inline_48$$]){var $JSCompiler_prefixedPropertyName$jscomp$inline_52_JSCompiler_titleCase$jscomp$inline_51$$=$JSCompiler_camelCase$jscomp$inline_48$$.charAt(0).toUpperCase()+$JSCompiler_camelCase$jscomp$inline_48$$.slice(1);b:{for(var $JSCompiler_i$jscomp$inline_62$$=0;$JSCompiler_i$jscomp$inline_62$$<$vendorPrefixes$$module$src$style$$.length;$JSCompiler_i$jscomp$inline_62$$++){var $JSCompiler_propertyName$jscomp$inline_63$$=
$vendorPrefixes$$module$src$style$$[$JSCompiler_i$jscomp$inline_62$$]+$JSCompiler_prefixedPropertyName$jscomp$inline_52_JSCompiler_titleCase$jscomp$inline_51$$;if(void 0!==$JSCompiler_propertyName$jscomp$inline_25_JSCompiler_style$jscomp$inline_47$$[$JSCompiler_propertyName$jscomp$inline_63$$]){$JSCompiler_prefixedPropertyName$jscomp$inline_52_JSCompiler_titleCase$jscomp$inline_51$$=$JSCompiler_propertyName$jscomp$inline_63$$;break b}}$JSCompiler_prefixedPropertyName$jscomp$inline_52_JSCompiler_titleCase$jscomp$inline_51$$=
""}void 0!==$JSCompiler_propertyName$jscomp$inline_25_JSCompiler_style$jscomp$inline_47$$[$JSCompiler_prefixedPropertyName$jscomp$inline_52_JSCompiler_titleCase$jscomp$inline_51$$]&&($JSCompiler_propertyName$jscomp$inline_50$$=$JSCompiler_prefixedPropertyName$jscomp$inline_52_JSCompiler_titleCase$jscomp$inline_51$$)}$propertyNameCache$$module$src$style$$[$JSCompiler_camelCase$jscomp$inline_48$$]=$JSCompiler_propertyName$jscomp$inline_50$$}$JSCompiler_propertyName$jscomp$inline_25_JSCompiler_style$jscomp$inline_47$$=
$JSCompiler_propertyName$jscomp$inline_50$$}$JSCompiler_propertyName$jscomp$inline_25_JSCompiler_style$jscomp$inline_47$$&&($JSCompiler_element$jscomp$inline_20$$.style[$JSCompiler_propertyName$jscomp$inline_25_JSCompiler_style$jscomp$inline_47$$]=$JSCompiler_value$jscomp$inline_22$$)}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function $tryParseJson$$module$src$json$$($json$jscomp$1$$){var $opt_onFailed$$;try{return JSON.parse($json$jscomp$1$$)}catch($e$jscomp$16$$){return $opt_onFailed$$&&$opt_onFailed$$($e$jscomp$16$$),null}};function $AmpInstagram$$module$extensions$amp_instagram$0_1$amp_instagram$$($$jscomp$super$this_element$jscomp$45$$){$$jscomp$super$this_element$jscomp$45$$=AMP.BaseElement.call(this,$$jscomp$super$this_element$jscomp$45$$)||this;$$jscomp$super$this_element$jscomp$45$$.$iframe_$=null;$$jscomp$super$this_element$jscomp$45$$.$shortcode_$="";$$jscomp$super$this_element$jscomp$45$$.$unlistenMessage_$=null;$$jscomp$super$this_element$jscomp$45$$.$captioned_$="";$$jscomp$super$this_element$jscomp$45$$.$iframePromise_$=
null;return $$jscomp$super$this_element$jscomp$45$$}var $JSCompiler_parentCtor$jscomp$inline_28$$=AMP.BaseElement;$AmpInstagram$$module$extensions$amp_instagram$0_1$amp_instagram$$.prototype=$$jscomp$objectCreate$$($JSCompiler_parentCtor$jscomp$inline_28$$.prototype);$AmpInstagram$$module$extensions$amp_instagram$0_1$amp_instagram$$.prototype.constructor=$AmpInstagram$$module$extensions$amp_instagram$0_1$amp_instagram$$;
if($$jscomp$setPrototypeOf$$)$$jscomp$setPrototypeOf$$($AmpInstagram$$module$extensions$amp_instagram$0_1$amp_instagram$$,$JSCompiler_parentCtor$jscomp$inline_28$$);else for(var $JSCompiler_p$jscomp$inline_29$$ in $JSCompiler_parentCtor$jscomp$inline_28$$)if("prototype"!=$JSCompiler_p$jscomp$inline_29$$)if(Object.defineProperties){var $JSCompiler_descriptor$jscomp$inline_30$$=Object.getOwnPropertyDescriptor($JSCompiler_parentCtor$jscomp$inline_28$$,$JSCompiler_p$jscomp$inline_29$$);$JSCompiler_descriptor$jscomp$inline_30$$&&
Object.defineProperty($AmpInstagram$$module$extensions$amp_instagram$0_1$amp_instagram$$,$JSCompiler_p$jscomp$inline_29$$,$JSCompiler_descriptor$jscomp$inline_30$$)}else $AmpInstagram$$module$extensions$amp_instagram$0_1$amp_instagram$$[$JSCompiler_p$jscomp$inline_29$$]=$JSCompiler_parentCtor$jscomp$inline_28$$[$JSCompiler_p$jscomp$inline_29$$];$AmpInstagram$$module$extensions$amp_instagram$0_1$amp_instagram$$.$superClass_$=$JSCompiler_parentCtor$jscomp$inline_28$$.prototype;
$JSCompiler_prototypeAlias$$=$AmpInstagram$$module$extensions$amp_instagram$0_1$amp_instagram$$.prototype;$JSCompiler_prototypeAlias$$.preconnectCallback=function($opt_onLayout$$){this.preconnect.url("https://www.instagram.com",$opt_onLayout$$);this.preconnect.url("https://instagram.fsnc1-1.fna.fbcdn.net",$opt_onLayout$$)};$JSCompiler_prototypeAlias$$.renderOutsideViewport=function(){return!1};
$JSCompiler_prototypeAlias$$.buildCallback=function(){var $JSCompiler_shouldBeTrueish$jscomp$inline_32$$=this.element.getAttribute("data-shortcode")||this.element.getAttribute("shortcode"),$JSCompiler_opt_1$jscomp$inline_33$$=this.element;if(!$logs$$module$src$log$$.user)throw Error("failed to call initLogConstructor");this.$shortcode_$=$logs$$module$src$log$$.user.assert($JSCompiler_shouldBeTrueish$jscomp$inline_32$$,"The data-shortcode attribute is required for <amp-instagram> %s",$JSCompiler_opt_1$jscomp$inline_33$$,
void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0);this.$captioned_$=this.element.hasAttribute("data-captioned")?"captioned/":""};
$JSCompiler_prototypeAlias$$.createPlaceholderCallback=function(){var $placeholder$$=this.win.document.createElement("div");$placeholder$$.setAttribute("placeholder","");var $image$jscomp$3$$=this.win.document.createElement("amp-img");$image$jscomp$3$$.setAttribute("noprerender","");$image$jscomp$3$$.setAttribute("src","https://www.instagram.com/p/"+encodeURIComponent(this.$shortcode_$)+"/media/?size=l");$image$jscomp$3$$.setAttribute("layout","fill");$image$jscomp$3$$.setAttribute("referrerpolicy",
"origin");this.propagateAttributes(["alt"],$image$jscomp$3$$);this.element.hasAttribute("data-default-framing")&&this.element.classList.add("amp-instagram-default-framing");$setStyles$$module$src$style$$($image$jscomp$3$$,{top:"0 px",bottom:"0 px",left:"0 px",right:"0 px"});$placeholder$$.appendChild($image$jscomp$3$$);return $placeholder$$};
$JSCompiler_prototypeAlias$$.isLayoutSupported=function($layout$jscomp$3$$){return"fixed"==$layout$jscomp$3$$||"fixed-height"==$layout$jscomp$3$$||"responsive"==$layout$jscomp$3$$||"fill"==$layout$jscomp$3$$||"flex-item"==$layout$jscomp$3$$||"fluid"==$layout$jscomp$3$$||"intrinsic"==$layout$jscomp$3$$};
$JSCompiler_prototypeAlias$$.layoutCallback=function(){var $$jscomp$this$jscomp$1$$=this,$iframe$$=this.element.ownerDocument.createElement("iframe");this.$iframe_$=$iframe$$;this.$unlistenMessage_$=$listen$$module$src$event_helper$$(this.win,this.$handleInstagramMessages_$.bind(this));$iframe$$.setAttribute("scrolling","no");$iframe$$.setAttribute("frameborder","0");$iframe$$.setAttribute("allowtransparency","true");$iframe$$.setAttribute("title","Instagram: "+this.element.getAttribute("alt"));$iframe$$.src=
"https://www.instagram.com/p/"+encodeURIComponent(this.$shortcode_$)+"/embed/"+this.$captioned_$+"?cr=1&v=9";this.applyFillContent($iframe$$);this.element.appendChild($iframe$$);$setStyles$$module$src$style$$($iframe$$,{opacity:0});return this.$iframePromise_$=this.loadPromise($iframe$$).then(function(){$$jscomp$this$jscomp$1$$.getVsync().mutate(function(){$setStyles$$module$src$style$$($iframe$$,{opacity:1})})})};
$JSCompiler_prototypeAlias$$.$handleInstagramMessages_$=function($data$jscomp$57_event$jscomp$9$$){var $$jscomp$this$jscomp$2$$=this;if("https://www.instagram.com"==$data$jscomp$57_event$jscomp$9$$.origin&&$data$jscomp$57_event$jscomp$9$$.source==this.$iframe_$.contentWindow){var $eventData$$=$data$jscomp$57_event$jscomp$9$$.data;if($eventData$$&&("[object Object]"===$toString_$$module$src$types$$.call($eventData$$)||$startsWith$$module$src$string$$($eventData$$,"{"))&&($data$jscomp$57_event$jscomp$9$$=
"[object Object]"===$toString_$$module$src$types$$.call($eventData$$)?$eventData$$:$tryParseJson$$module$src$json$$($eventData$$),void 0!==$data$jscomp$57_event$jscomp$9$$&&"MEASURE"==$data$jscomp$57_event$jscomp$9$$.type&&$data$jscomp$57_event$jscomp$9$$.details)){var $height$jscomp$27$$=$data$jscomp$57_event$jscomp$9$$.details.height;this.getVsync().measure(function(){$$jscomp$this$jscomp$2$$.$iframe_$&&$$jscomp$this$jscomp$2$$.$iframe_$.offsetHeight!==$height$jscomp$27$$&&$$jscomp$this$jscomp$2$$.changeHeight($height$jscomp$27$$)})}}};
$JSCompiler_prototypeAlias$$.unlayoutOnPause=function(){return!0};$JSCompiler_prototypeAlias$$.unlayoutCallback=function(){if(this.$iframe_$){var $JSCompiler_element$jscomp$inline_44$$=this.$iframe_$;$JSCompiler_element$jscomp$inline_44$$.parentElement&&$JSCompiler_element$jscomp$inline_44$$.parentElement.removeChild($JSCompiler_element$jscomp$inline_44$$);this.$iframePromise_$=this.$iframe_$=null}this.$unlistenMessage_$&&this.$unlistenMessage_$();return!0};
(function($AMP$jscomp$1$$){$AMP$jscomp$1$$.registerElement("amp-instagram",$AmpInstagram$$module$extensions$amp_instagram$0_1$amp_instagram$$,"amp-instagram.amp-instagram-default-framing{border:1px solid #dbdbdb!important}\n/*# sourceURL=/extensions/amp-instagram/0.1/amp-instagram.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-instagram-0.1.js.map
