(self.AMP=self.AMP||[]).push({n:"amp-fit-text",v:"1904281823091",f:(function(AMP,_){
var $$jscomp$objectCreate$$="function"==typeof Object.create?Object.create:function($prototype$$){function $ctor$$(){}$ctor$$.prototype=$prototype$$;return new $ctor$$},$JSCompiler_temp$jscomp$9$$;
if("function"==typeof Object.setPrototypeOf)$JSCompiler_temp$jscomp$9$$=Object.setPrototypeOf;else{var $JSCompiler_inline_result$jscomp$10$$;a:{var $JSCompiler_x$jscomp$inline_13$$={a:!0},$JSCompiler_y$jscomp$inline_14$$={};try{$JSCompiler_y$jscomp$inline_14$$.__proto__=$JSCompiler_x$jscomp$inline_13$$;$JSCompiler_inline_result$jscomp$10$$=$JSCompiler_y$jscomp$inline_14$$.a;break a}catch($JSCompiler_e$jscomp$inline_15$$){}$JSCompiler_inline_result$jscomp$10$$=!1}$JSCompiler_temp$jscomp$9$$=$JSCompiler_inline_result$jscomp$10$$?
function($target$jscomp$83$$,$proto$jscomp$3$$){$target$jscomp$83$$.__proto__=$proto$jscomp$3$$;if($target$jscomp$83$$.__proto__!==$proto$jscomp$3$$)throw new TypeError($target$jscomp$83$$+" is not extensible");return $target$jscomp$83$$}:null}var $$jscomp$setPrototypeOf$$=$JSCompiler_temp$jscomp$9$$;self.log=self.log||{user:null,dev:null,userForEmbed:null};var $propertyNameCache$$module$src$style$$,$vendorPrefixes$$module$src$style$$="Webkit webkit Moz moz ms O o".split(" ");
function $setStyle$$module$src$style$$($element$jscomp$13$$,$JSCompiler_inline_result$jscomp$12_property$jscomp$4_propertyName$jscomp$10$$,$value$jscomp$91$$){var $opt_units$$;var $JSCompiler_style$jscomp$inline_17$$=$element$jscomp$13$$.style;if(2>$JSCompiler_inline_result$jscomp$12_property$jscomp$4_propertyName$jscomp$10$$.length||0!=$JSCompiler_inline_result$jscomp$12_property$jscomp$4_propertyName$jscomp$10$$.lastIndexOf("--",0)){$propertyNameCache$$module$src$style$$||($propertyNameCache$$module$src$style$$=
Object.create(null));var $JSCompiler_propertyName$jscomp$inline_20$$=$propertyNameCache$$module$src$style$$[$JSCompiler_inline_result$jscomp$12_property$jscomp$4_propertyName$jscomp$10$$];if(!$JSCompiler_propertyName$jscomp$inline_20$$){$JSCompiler_propertyName$jscomp$inline_20$$=$JSCompiler_inline_result$jscomp$12_property$jscomp$4_propertyName$jscomp$10$$;if(void 0===$JSCompiler_style$jscomp$inline_17$$[$JSCompiler_inline_result$jscomp$12_property$jscomp$4_propertyName$jscomp$10$$]){var $JSCompiler_inline_result$jscomp$37_JSCompiler_prefixedPropertyName$jscomp$inline_22_JSCompiler_titleCase$jscomp$inline_21$$=
$JSCompiler_inline_result$jscomp$12_property$jscomp$4_propertyName$jscomp$10$$.charAt(0).toUpperCase()+$JSCompiler_inline_result$jscomp$12_property$jscomp$4_propertyName$jscomp$10$$.slice(1);b:{for(var $JSCompiler_i$jscomp$inline_44$$=0;$JSCompiler_i$jscomp$inline_44$$<$vendorPrefixes$$module$src$style$$.length;$JSCompiler_i$jscomp$inline_44$$++){var $JSCompiler_propertyName$jscomp$inline_45$$=$vendorPrefixes$$module$src$style$$[$JSCompiler_i$jscomp$inline_44$$]+$JSCompiler_inline_result$jscomp$37_JSCompiler_prefixedPropertyName$jscomp$inline_22_JSCompiler_titleCase$jscomp$inline_21$$;
if(void 0!==$JSCompiler_style$jscomp$inline_17$$[$JSCompiler_propertyName$jscomp$inline_45$$]){$JSCompiler_inline_result$jscomp$37_JSCompiler_prefixedPropertyName$jscomp$inline_22_JSCompiler_titleCase$jscomp$inline_21$$=$JSCompiler_propertyName$jscomp$inline_45$$;break b}}$JSCompiler_inline_result$jscomp$37_JSCompiler_prefixedPropertyName$jscomp$inline_22_JSCompiler_titleCase$jscomp$inline_21$$=""}void 0!==$JSCompiler_style$jscomp$inline_17$$[$JSCompiler_inline_result$jscomp$37_JSCompiler_prefixedPropertyName$jscomp$inline_22_JSCompiler_titleCase$jscomp$inline_21$$]&&
($JSCompiler_propertyName$jscomp$inline_20$$=$JSCompiler_inline_result$jscomp$37_JSCompiler_prefixedPropertyName$jscomp$inline_22_JSCompiler_titleCase$jscomp$inline_21$$)}$propertyNameCache$$module$src$style$$[$JSCompiler_inline_result$jscomp$12_property$jscomp$4_propertyName$jscomp$10$$]=$JSCompiler_propertyName$jscomp$inline_20$$}$JSCompiler_inline_result$jscomp$12_property$jscomp$4_propertyName$jscomp$10$$=$JSCompiler_propertyName$jscomp$inline_20$$}$JSCompiler_inline_result$jscomp$12_property$jscomp$4_propertyName$jscomp$10$$&&
($element$jscomp$13$$.style[$JSCompiler_inline_result$jscomp$12_property$jscomp$4_propertyName$jscomp$10$$]=$opt_units$$?$value$jscomp$91$$+$opt_units$$:$value$jscomp$91$$)}function $setStyles$$module$src$style$$($element$jscomp$15$$,$styles$jscomp$1$$){for(var $k$jscomp$2$$ in $styles$jscomp$1$$)$setStyle$$module$src$style$$($element$jscomp$15$$,$k$jscomp$2$$,$styles$jscomp$1$$[$k$jscomp$2$$])};function $getLengthNumeral$$module$src$layout$$($JSCompiler_value$jscomp$inline_24_length$jscomp$20$$){var $res$$=parseFloat($JSCompiler_value$jscomp$inline_24_length$jscomp$20$$);$JSCompiler_value$jscomp$inline_24_length$jscomp$20$$=$res$$;return"number"===typeof $JSCompiler_value$jscomp$inline_24_length$jscomp$20$$&&isFinite($JSCompiler_value$jscomp$inline_24_length$jscomp$20$$)?$res$$:void 0};function $AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$($$jscomp$super$this_element$jscomp$21$$){$$jscomp$super$this_element$jscomp$21$$=AMP.BaseElement.call(this,$$jscomp$super$this_element$jscomp$21$$)||this;$$jscomp$super$this_element$jscomp$21$$.$content_$=null;$$jscomp$super$this_element$jscomp$21$$.$contentWrapper_$=null;$$jscomp$super$this_element$jscomp$21$$.$measurer_$=null;$$jscomp$super$this_element$jscomp$21$$.$minFontSize_$=-1;$$jscomp$super$this_element$jscomp$21$$.$maxFontSize_$=
-1;return $$jscomp$super$this_element$jscomp$21$$}var $JSCompiler_parentCtor$jscomp$inline_27$$=AMP.BaseElement;$AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$.prototype=$$jscomp$objectCreate$$($JSCompiler_parentCtor$jscomp$inline_27$$.prototype);$AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$.prototype.constructor=$AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$;
if($$jscomp$setPrototypeOf$$)$$jscomp$setPrototypeOf$$($AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$,$JSCompiler_parentCtor$jscomp$inline_27$$);else for(var $JSCompiler_p$jscomp$inline_28$$ in $JSCompiler_parentCtor$jscomp$inline_27$$)if("prototype"!=$JSCompiler_p$jscomp$inline_28$$)if(Object.defineProperties){var $JSCompiler_descriptor$jscomp$inline_29$$=Object.getOwnPropertyDescriptor($JSCompiler_parentCtor$jscomp$inline_27$$,$JSCompiler_p$jscomp$inline_28$$);$JSCompiler_descriptor$jscomp$inline_29$$&&
Object.defineProperty($AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$,$JSCompiler_p$jscomp$inline_28$$,$JSCompiler_descriptor$jscomp$inline_29$$)}else $AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$[$JSCompiler_p$jscomp$inline_28$$]=$JSCompiler_parentCtor$jscomp$inline_27$$[$JSCompiler_p$jscomp$inline_28$$];$AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$.$superClass_$=$JSCompiler_parentCtor$jscomp$inline_27$$.prototype;
$AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$.prototype.isLayoutSupported=function($layout$jscomp$3$$){return"fixed"==$layout$jscomp$3$$||"fixed-height"==$layout$jscomp$3$$||"responsive"==$layout$jscomp$3$$||"fill"==$layout$jscomp$3$$||"flex-item"==$layout$jscomp$3$$||"fluid"==$layout$jscomp$3$$||"intrinsic"==$layout$jscomp$3$$};
$AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$.prototype.buildCallback=function(){var $$jscomp$this$$=this;this.$content_$=this.element.ownerDocument.createElement("div");this.applyFillContent(this.$content_$);this.$content_$.classList.add("i-amphtml-fit-text-content");$setStyles$$module$src$style$$(this.$content_$,{zIndex:2});this.$contentWrapper_$=this.element.ownerDocument.createElement("div");$setStyles$$module$src$style$$(this.$contentWrapper_$,{lineHeight:"1.15em"});this.$content_$.appendChild(this.$contentWrapper_$);
this.$measurer_$=this.element.ownerDocument.createElement("div");$setStyles$$module$src$style$$(this.$measurer_$,{position:"absolute",top:0,left:0,zIndex:1,visibility:"hidden",lineHeight:"1.15em"});this.getRealChildNodes().forEach(function($node$jscomp$2$$){$$jscomp$this$$.$contentWrapper_$.appendChild($node$jscomp$2$$)});this.$measurer_$.innerHTML=this.$contentWrapper_$.innerHTML;this.element.appendChild(this.$content_$);this.element.appendChild(this.$measurer_$);this.$minFontSize_$=$getLengthNumeral$$module$src$layout$$(this.element.getAttribute("min-font-size"))||
6;this.$maxFontSize_$=$getLengthNumeral$$module$src$layout$$(this.element.getAttribute("max-font-size"))||72};$AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$.prototype.prerenderAllowed=function(){return!0};$AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$.prototype.isRelayoutNeeded=function(){return!0};
$AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$.prototype.layoutCallback=function(){var $$jscomp$this$jscomp$1$$=this;return this.mutateElement(function(){var $JSCompiler_maxHeight$jscomp$inline_32_JSCompiler_numberOfLines$jscomp$inline_61$$=$$jscomp$this$jscomp$1$$.element.offsetHeight,$JSCompiler_content$jscomp$inline_55_JSCompiler_measurer$jscomp$inline_47$$=$$jscomp$this$jscomp$1$$.$measurer_$,$JSCompiler_expectedWidth$jscomp$inline_49_JSCompiler_measurer$jscomp$inline_56_JSCompiler_overflown$jscomp$inline_59$$=
$$jscomp$this$jscomp$1$$.element.offsetWidth;var $JSCompiler_inline_result$jscomp$38_JSCompiler_lineHeight$jscomp$inline_60_JSCompiler_minFontSize$jscomp$inline_50$$=$$jscomp$this$jscomp$1$$.$minFontSize_$;var $JSCompiler_maxFontSize$jscomp$inline_51$$=$$jscomp$this$jscomp$1$$.$maxFontSize_$;for($JSCompiler_maxFontSize$jscomp$inline_51$$++;1<$JSCompiler_maxFontSize$jscomp$inline_51$$-$JSCompiler_inline_result$jscomp$38_JSCompiler_lineHeight$jscomp$inline_60_JSCompiler_minFontSize$jscomp$inline_50$$;){var $JSCompiler_mid$jscomp$inline_52$$=
Math.floor(($JSCompiler_inline_result$jscomp$38_JSCompiler_lineHeight$jscomp$inline_60_JSCompiler_minFontSize$jscomp$inline_50$$+$JSCompiler_maxFontSize$jscomp$inline_51$$)/2);$setStyle$$module$src$style$$($JSCompiler_content$jscomp$inline_55_JSCompiler_measurer$jscomp$inline_47$$,"fontSize",$JSCompiler_mid$jscomp$inline_52$$+"px");var $JSCompiler_width$jscomp$inline_53$$=$JSCompiler_content$jscomp$inline_55_JSCompiler_measurer$jscomp$inline_47$$.offsetWidth;$JSCompiler_content$jscomp$inline_55_JSCompiler_measurer$jscomp$inline_47$$.offsetHeight>
$JSCompiler_maxHeight$jscomp$inline_32_JSCompiler_numberOfLines$jscomp$inline_61$$||$JSCompiler_width$jscomp$inline_53$$>$JSCompiler_expectedWidth$jscomp$inline_49_JSCompiler_measurer$jscomp$inline_56_JSCompiler_overflown$jscomp$inline_59$$?$JSCompiler_maxFontSize$jscomp$inline_51$$=$JSCompiler_mid$jscomp$inline_52$$:$JSCompiler_inline_result$jscomp$38_JSCompiler_lineHeight$jscomp$inline_60_JSCompiler_minFontSize$jscomp$inline_50$$=$JSCompiler_mid$jscomp$inline_52$$}$setStyle$$module$src$style$$($$jscomp$this$jscomp$1$$.$contentWrapper_$,
"fontSize",$JSCompiler_inline_result$jscomp$38_JSCompiler_lineHeight$jscomp$inline_60_JSCompiler_minFontSize$jscomp$inline_50$$+"px");$JSCompiler_content$jscomp$inline_55_JSCompiler_measurer$jscomp$inline_47$$=$$jscomp$this$jscomp$1$$.$contentWrapper_$;$JSCompiler_expectedWidth$jscomp$inline_49_JSCompiler_measurer$jscomp$inline_56_JSCompiler_overflown$jscomp$inline_59$$=$$jscomp$this$jscomp$1$$.$measurer_$;$setStyle$$module$src$style$$($JSCompiler_expectedWidth$jscomp$inline_49_JSCompiler_measurer$jscomp$inline_56_JSCompiler_overflown$jscomp$inline_59$$,
"fontSize",$JSCompiler_inline_result$jscomp$38_JSCompiler_lineHeight$jscomp$inline_60_JSCompiler_minFontSize$jscomp$inline_50$$+"px");$JSCompiler_expectedWidth$jscomp$inline_49_JSCompiler_measurer$jscomp$inline_56_JSCompiler_overflown$jscomp$inline_59$$=$JSCompiler_expectedWidth$jscomp$inline_49_JSCompiler_measurer$jscomp$inline_56_JSCompiler_overflown$jscomp$inline_59$$.offsetHeight>$JSCompiler_maxHeight$jscomp$inline_32_JSCompiler_numberOfLines$jscomp$inline_61$$;$JSCompiler_inline_result$jscomp$38_JSCompiler_lineHeight$jscomp$inline_60_JSCompiler_minFontSize$jscomp$inline_50$$*=
1.15;$JSCompiler_maxHeight$jscomp$inline_32_JSCompiler_numberOfLines$jscomp$inline_61$$=Math.floor($JSCompiler_maxHeight$jscomp$inline_32_JSCompiler_numberOfLines$jscomp$inline_61$$/$JSCompiler_inline_result$jscomp$38_JSCompiler_lineHeight$jscomp$inline_60_JSCompiler_minFontSize$jscomp$inline_50$$);$JSCompiler_content$jscomp$inline_55_JSCompiler_measurer$jscomp$inline_47$$.classList.toggle("i-amphtml-fit-text-content-overflown",$JSCompiler_expectedWidth$jscomp$inline_49_JSCompiler_measurer$jscomp$inline_56_JSCompiler_overflown$jscomp$inline_59$$);
$setStyles$$module$src$style$$($JSCompiler_content$jscomp$inline_55_JSCompiler_measurer$jscomp$inline_47$$,{lineClamp:$JSCompiler_expectedWidth$jscomp$inline_49_JSCompiler_measurer$jscomp$inline_56_JSCompiler_overflown$jscomp$inline_59$$?$JSCompiler_maxHeight$jscomp$inline_32_JSCompiler_numberOfLines$jscomp$inline_61$$:"",maxHeight:$JSCompiler_expectedWidth$jscomp$inline_49_JSCompiler_measurer$jscomp$inline_56_JSCompiler_overflown$jscomp$inline_59$$?$JSCompiler_inline_result$jscomp$38_JSCompiler_lineHeight$jscomp$inline_60_JSCompiler_minFontSize$jscomp$inline_50$$*
$JSCompiler_maxHeight$jscomp$inline_32_JSCompiler_numberOfLines$jscomp$inline_61$$+"px":""})})};(function($AMP$jscomp$1$$){$AMP$jscomp$1$$.registerElement("amp-fit-text",$AmpFitText$$module$extensions$amp_fit_text$0_1$amp_fit_text$$,".i-amphtml-fit-text-content,.i-amphtml-fit-text-content.i-amphtml-fill-content{display:block;display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-ms-flex-direction:column;flex-direction:column;-ms-flex-wrap:nowrap;flex-wrap:nowrap;-webkit-box-pack:center;-ms-flex-pack:center;justify-content:center}.i-amphtml-fit-text-content-overflown{display:block;display:-webkit-box;-webkit-box-orient:vertical;overflow:hidden}\n/*# sourceURL=/extensions/amp-fit-text/0.1/amp-fit-text.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-fit-text-0.1.js.map
