(self.AMP=self.AMP||[]).push({n:"amp-access-poool",v:"1904281823091",f:(function(AMP,_){
function $Deferred$$module$src$utils$promise$$(){var $resolve$$,$reject$$;this.promise=new Promise(function($res$$,$rej$$){$resolve$$=$res$$;$reject$$=$rej$$});this.resolve=$resolve$$;this.reject=$reject$$};function $tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($component$jscomp$4$$,$fallback$$){$fallback$$=void 0===$fallback$$?"":$fallback$$;try{return decodeURIComponent($component$jscomp$4$$)}catch($e$jscomp$7$$){return $fallback$$}};var $regex$$module$src$url_parse_query_string$$=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;
function $parseQueryString_$$module$src$url_parse_query_string$$($queryString$$){var $params$jscomp$1$$=Object.create(null);if(!$queryString$$)return $params$jscomp$1$$;for(var $match$$;$match$$=$regex$$module$src$url_parse_query_string$$.exec($queryString$$);){var $name$jscomp$70$$=$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($match$$[1],$match$$[1]),$value$jscomp$87$$=$match$$[2]?$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($match$$[2],$match$$[2]):"";
$params$jscomp$1$$[$name$jscomp$70$$]=$value$jscomp$87$$}return $params$jscomp$1$$};var $rtvVersion$$module$src$mode$$="";
function $getMode$$module$src$mode$$(){var $opt_win$$,$win$$=$opt_win$$||self;if($win$$.AMP_MODE)var $JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_26$$=$win$$.AMP_MODE;else{$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_26$$=$win$$;var $JSCompiler_AMP_CONFIG$jscomp$inline_27_JSCompiler_singlePassType$jscomp$inline_34$$=self.AMP_CONFIG||{},$JSCompiler_runningTests$jscomp$inline_31$$=!!$JSCompiler_AMP_CONFIG$jscomp$inline_27_JSCompiler_singlePassType$jscomp$inline_34$$.test||!(!$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_26$$.AMP_TEST&&
!$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_26$$.__karma__),$JSCompiler_isLocalDev$jscomp$inline_32$$=!!$JSCompiler_AMP_CONFIG$jscomp$inline_27_JSCompiler_singlePassType$jscomp$inline_34$$.localDev||$JSCompiler_runningTests$jscomp$inline_31$$,$JSCompiler_hashQuery$jscomp$inline_33$$=$parseQueryString_$$module$src$url_parse_query_string$$($JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_26$$.location.originalHash||$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_26$$.location.hash);
$JSCompiler_AMP_CONFIG$jscomp$inline_27_JSCompiler_singlePassType$jscomp$inline_34$$=$JSCompiler_AMP_CONFIG$jscomp$inline_27_JSCompiler_singlePassType$jscomp$inline_34$$.spt;var $JSCompiler_searchQuery$jscomp$inline_35$$=$parseQueryString_$$module$src$url_parse_query_string$$($JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_26$$.location.search);$rtvVersion$$module$src$mode$$||($rtvVersion$$module$src$mode$$=$JSCompiler_isLocalDev$jscomp$inline_32$$?"1904281823091":$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_26$$.AMP_CONFIG&&
$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_26$$.AMP_CONFIG.v?$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_26$$.AMP_CONFIG.v:"011904281823091");$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_26$$=$win$$.AMP_MODE={localDev:$JSCompiler_isLocalDev$jscomp$inline_32$$,development:!("1"!=$JSCompiler_hashQuery$jscomp$inline_33$$.development&&!$JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_26$$.AMP_DEV_MODE),examiner:"2"==$JSCompiler_hashQuery$jscomp$inline_33$$.development,
filter:$JSCompiler_hashQuery$jscomp$inline_33$$.filter,geoOverride:$JSCompiler_hashQuery$jscomp$inline_33$$["amp-geo"],minified:!0,lite:void 0!=$JSCompiler_searchQuery$jscomp$inline_35$$.amp_lite,test:$JSCompiler_runningTests$jscomp$inline_31$$,log:$JSCompiler_hashQuery$jscomp$inline_33$$.log,version:"1904281823091",rtvVersion:$rtvVersion$$module$src$mode$$,singlePassType:$JSCompiler_AMP_CONFIG$jscomp$inline_27_JSCompiler_singlePassType$jscomp$inline_34$$}}return $JSCompiler_temp$jscomp$14_JSCompiler_win$jscomp$inline_26$$}
;self.log=self.log||{user:null,dev:null,userForEmbed:null};var $logs$$module$src$log$$=self.log;function $dev$$module$src$log$$(){if($logs$$module$src$log$$.dev)return $logs$$module$src$log$$.dev;throw Error("failed to call initLogConstructor");}
function $userAssert$$module$src$log$$($shouldBeTrueish$jscomp$3$$,$opt_message$jscomp$14$$,$opt_1$jscomp$1$$,$opt_2$jscomp$1$$,$opt_3$jscomp$1$$,$opt_4$jscomp$1$$){if(!$logs$$module$src$log$$.user)throw Error("failed to call initLogConstructor");return $logs$$module$src$log$$.user.assert($shouldBeTrueish$jscomp$3$$,$opt_message$jscomp$14$$,$opt_1$jscomp$1$$,$opt_2$jscomp$1$$,$opt_3$jscomp$1$$,$opt_4$jscomp$1$$,void 0,void 0,void 0,void 0,void 0)};function $getService$$module$src$service$$($win$jscomp$8$$,$id$jscomp$11$$){$win$jscomp$8$$=$win$jscomp$8$$.__AMP_TOP||$win$jscomp$8$$;return $getServiceInternal$$module$src$service$$($win$jscomp$8$$,$id$jscomp$11$$)}function $getAmpdoc$$module$src$service$$($nodeOrDoc$jscomp$2$$){return $nodeOrDoc$jscomp$2$$.nodeType?$getService$$module$src$service$$(($nodeOrDoc$jscomp$2$$.ownerDocument||$nodeOrDoc$jscomp$2$$).defaultView,"ampdoc").getAmpDoc($nodeOrDoc$jscomp$2$$):$nodeOrDoc$jscomp$2$$}
function $getAmpdocServiceHolder$$module$src$service$$($ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$){$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$=$getAmpdoc$$module$src$service$$($ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$);return $ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$.isSingleDoc()?$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$.win:$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$}
function $getServiceInternal$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$,$id$jscomp$19$$){var $services$$=$getServices$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$);$holder$jscomp$4_s$jscomp$8$$=$services$$[$id$jscomp$19$$];$holder$jscomp$4_s$jscomp$8$$.obj||($holder$jscomp$4_s$jscomp$8$$.obj=new $holder$jscomp$4_s$jscomp$8$$.ctor($holder$jscomp$4_s$jscomp$8$$.context),$holder$jscomp$4_s$jscomp$8$$.ctor=null,$holder$jscomp$4_s$jscomp$8$$.context=null,$holder$jscomp$4_s$jscomp$8$$.resolve&&
$holder$jscomp$4_s$jscomp$8$$.resolve($holder$jscomp$4_s$jscomp$8$$.obj));return $holder$jscomp$4_s$jscomp$8$$.obj}
function $getServicePromiseOrNullInternal$$module$src$service$$($holder$jscomp$8$$){var $s$jscomp$11$$=$getServices$$module$src$service$$($holder$jscomp$8$$).access;if($s$jscomp$11$$){if($s$jscomp$11$$.promise)return $s$jscomp$11$$.promise;$getServiceInternal$$module$src$service$$($holder$jscomp$8$$,"access");return $s$jscomp$11$$.promise=Promise.resolve($s$jscomp$11$$.obj)}return null}
function $getServices$$module$src$service$$($holder$jscomp$9$$){var $services$jscomp$5$$=$holder$jscomp$9$$.services;$services$jscomp$5$$||($services$jscomp$5$$=$holder$jscomp$9$$.services={});return $services$jscomp$5$$}
function $emptyServiceHolderWithPromise$$module$src$service$$(){var $deferred$$=new $Deferred$$module$src$utils$promise$$,$$jscomp$destructuring$var2_reject$jscomp$3$$=$deferred$$,$promise$jscomp$1$$=$$jscomp$destructuring$var2_reject$jscomp$3$$.promise,$resolve$jscomp$4$$=$$jscomp$destructuring$var2_reject$jscomp$3$$.resolve;$$jscomp$destructuring$var2_reject$jscomp$3$$=$$jscomp$destructuring$var2_reject$jscomp$3$$.reject;$promise$jscomp$1$$.catch(function(){});return{obj:null,promise:$promise$jscomp$1$$,
resolve:$resolve$jscomp$4$$,reject:$$jscomp$destructuring$var2_reject$jscomp$3$$,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function $dict$$module$src$utils$object$$($opt_initial$jscomp$1$$){return $opt_initial$jscomp$1$$||{}};function $getElementServiceForDoc$$module$src$element_service$$($element$jscomp$32$$){return $getElementServiceIfAvailableForDoc$$module$src$element_service$$($element$jscomp$32$$).then(function($element$jscomp$32$$){return $userAssert$$module$src$log$$($element$jscomp$32$$,"Service %s was requested to be provided through %s, but %s is not loaded in the current page. To fix this problem load the JavaScript file for %s in this page.","access","amp-access","amp-access","amp-access")})}
function $getElementServiceIfAvailableForDoc$$module$src$element_service$$($element$jscomp$33$$){var $s$jscomp$13$$=$getServicePromiseOrNullInternal$$module$src$service$$($getAmpdocServiceHolder$$module$src$service$$($element$jscomp$33$$));if($s$jscomp$13$$)return $s$jscomp$13$$;var $ampdoc$jscomp$7$$=$getAmpdoc$$module$src$service$$($element$jscomp$33$$);return $ampdoc$jscomp$7$$.whenBodyAvailable().then(function(){var $element$jscomp$33$$=$ampdoc$jscomp$7$$.win;var $s$jscomp$13$$=$ampdoc$jscomp$7$$.win.document.head;
if($s$jscomp$13$$){var $JSCompiler_inline_result$jscomp$141_JSCompiler_scripts$jscomp$inline_143$$=[];$s$jscomp$13$$=$s$jscomp$13$$.querySelectorAll("script[custom-element]");for(var $JSCompiler_i$jscomp$inline_145$$=0;$JSCompiler_i$jscomp$inline_145$$<$s$jscomp$13$$.length;$JSCompiler_i$jscomp$inline_145$$++)$JSCompiler_inline_result$jscomp$141_JSCompiler_scripts$jscomp$inline_143$$.push($s$jscomp$13$$[$JSCompiler_i$jscomp$inline_145$$].getAttribute("custom-element"))}else $JSCompiler_inline_result$jscomp$141_JSCompiler_scripts$jscomp$inline_143$$=
[];$element$jscomp$33$$=$JSCompiler_inline_result$jscomp$141_JSCompiler_scripts$jscomp$inline_143$$.includes("amp-access")?$getService$$module$src$service$$($element$jscomp$33$$,"extensions").waitForExtension($element$jscomp$33$$,"amp-access"):Promise.resolve();return $element$jscomp$33$$}).then(function(){var $s$jscomp$13$$=$ampdoc$jscomp$7$$.win;if($s$jscomp$13$$.ampExtendedElements&&$s$jscomp$13$$.ampExtendedElements["amp-access"]){$s$jscomp$13$$=$getAmpdocServiceHolder$$module$src$service$$($element$jscomp$33$$);
var $JSCompiler_cached$jscomp$inline_118$$=$getServicePromiseOrNullInternal$$module$src$service$$($s$jscomp$13$$);$JSCompiler_cached$jscomp$inline_118$$?$s$jscomp$13$$=$JSCompiler_cached$jscomp$inline_118$$:($s$jscomp$13$$=$getServices$$module$src$service$$($s$jscomp$13$$),$s$jscomp$13$$.access=$emptyServiceHolderWithPromise$$module$src$service$$(),$s$jscomp$13$$=$s$jscomp$13$$.access.promise)}else $s$jscomp$13$$=null;return $s$jscomp$13$$})};function $LruCache$$module$src$utils$lru_cache$$(){var $capacity$$=100;this.$capacity_$=$capacity$$;this.$access_$=this.$size_$=0;this.$cache_$=Object.create(null)}$LruCache$$module$src$utils$lru_cache$$.prototype.has=function($key$jscomp$43$$){return!!this.$cache_$[$key$jscomp$43$$]};$LruCache$$module$src$utils$lru_cache$$.prototype.get=function($key$jscomp$44$$){var $cacheable$$=this.$cache_$[$key$jscomp$44$$];if($cacheable$$)return $cacheable$$.access=++this.$access_$,$cacheable$$.payload};
$LruCache$$module$src$utils$lru_cache$$.prototype.put=function($JSCompiler_cache$jscomp$inline_55_key$jscomp$45$$,$payload$$){this.has($JSCompiler_cache$jscomp$inline_55_key$jscomp$45$$)||this.$size_$++;this.$cache_$[$JSCompiler_cache$jscomp$inline_55_key$jscomp$45$$]={payload:$payload$$,access:this.$access_$};if(!(this.$size_$<=this.$capacity_$)){$dev$$module$src$log$$().warn("lru-cache","Trimming LRU cache");$JSCompiler_cache$jscomp$inline_55_key$jscomp$45$$=this.$cache_$;var $JSCompiler_oldest$jscomp$inline_56$$=
this.$access_$+1,$JSCompiler_key$jscomp$inline_58$$;for($JSCompiler_key$jscomp$inline_58$$ in $JSCompiler_cache$jscomp$inline_55_key$jscomp$45$$){var $JSCompiler_access$jscomp$inline_59$$=$JSCompiler_cache$jscomp$inline_55_key$jscomp$45$$[$JSCompiler_key$jscomp$inline_58$$].access;if($JSCompiler_access$jscomp$inline_59$$<$JSCompiler_oldest$jscomp$inline_56$$){$JSCompiler_oldest$jscomp$inline_56$$=$JSCompiler_access$jscomp$inline_59$$;var $JSCompiler_oldestKey$jscomp$inline_57$$=$JSCompiler_key$jscomp$inline_58$$}}void 0!==
$JSCompiler_oldestKey$jscomp$inline_57$$&&(delete $JSCompiler_cache$jscomp$inline_55_key$jscomp$45$$[$JSCompiler_oldestKey$jscomp$inline_57$$],this.$size_$--)}};$dict$$module$src$utils$object$$({c:!0,v:!0,a:!0,ad:!0,action:!0});var $a$$module$src$url$$,$cache$$module$src$url$$;
function $parseUrlDeprecated$$module$src$url$$($JSCompiler_inline_result$jscomp$21_url$jscomp$22$$){var $opt_nocache$$;$a$$module$src$url$$||($a$$module$src$url$$=self.document.createElement("a"),$cache$$module$src$url$$=self.UrlCache||(self.UrlCache=new $LruCache$$module$src$utils$lru_cache$$));var $JSCompiler_opt_cache$jscomp$inline_62$$=$opt_nocache$$?null:$cache$$module$src$url$$,$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$=$a$$module$src$url$$;if($JSCompiler_opt_cache$jscomp$inline_62$$&&
$JSCompiler_opt_cache$jscomp$inline_62$$.has($JSCompiler_inline_result$jscomp$21_url$jscomp$22$$))$JSCompiler_inline_result$jscomp$21_url$jscomp$22$$=$JSCompiler_opt_cache$jscomp$inline_62$$.get($JSCompiler_inline_result$jscomp$21_url$jscomp$22$$);else{$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$.href=$JSCompiler_inline_result$jscomp$21_url$jscomp$22$$;$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$.protocol||($JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$.href=
$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$.href);var $JSCompiler_info$jscomp$inline_64$$={href:$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$.href,protocol:$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$.protocol,host:$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$.host,hostname:$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$.hostname,port:"0"==$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$.port?
"":$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$.port,pathname:$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$.pathname,search:$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$.search,hash:$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$.hash,origin:null};"/"!==$JSCompiler_info$jscomp$inline_64$$.pathname[0]&&($JSCompiler_info$jscomp$inline_64$$.pathname="/"+$JSCompiler_info$jscomp$inline_64$$.pathname);if("http:"==$JSCompiler_info$jscomp$inline_64$$.protocol&&
80==$JSCompiler_info$jscomp$inline_64$$.port||"https:"==$JSCompiler_info$jscomp$inline_64$$.protocol&&443==$JSCompiler_info$jscomp$inline_64$$.port)$JSCompiler_info$jscomp$inline_64$$.port="",$JSCompiler_info$jscomp$inline_64$$.host=$JSCompiler_info$jscomp$inline_64$$.hostname;$JSCompiler_info$jscomp$inline_64$$.origin=$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$.origin&&"null"!=$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$.origin?$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$.origin:
"data:"!=$JSCompiler_info$jscomp$inline_64$$.protocol&&$JSCompiler_info$jscomp$inline_64$$.host?$JSCompiler_info$jscomp$inline_64$$.protocol+"//"+$JSCompiler_info$jscomp$inline_64$$.host:$JSCompiler_info$jscomp$inline_64$$.href;$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$=$getMode$$module$src$mode$$().test&&Object.freeze?Object.freeze($JSCompiler_info$jscomp$inline_64$$):$JSCompiler_info$jscomp$inline_64$$;$JSCompiler_opt_cache$jscomp$inline_62$$&&$JSCompiler_opt_cache$jscomp$inline_62$$.put($JSCompiler_inline_result$jscomp$21_url$jscomp$22$$,
$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$);$JSCompiler_inline_result$jscomp$21_url$jscomp$22$$=$JSCompiler_a$jscomp$inline_63_JSCompiler_frozen$jscomp$inline_65$$}return $JSCompiler_inline_result$jscomp$21_url$jscomp$22$$}
function $appendEncodedParamStringToUrl$$module$src$url$$($url$jscomp$24$$,$paramString$$,$opt_addToFront$$){if(!$paramString$$)return $url$jscomp$24$$;var $mainAndFragment$$=$url$jscomp$24$$.split("#",2),$mainAndQuery$$=$mainAndFragment$$[0].split("?",2),$newUrl$$=$mainAndQuery$$[0]+($mainAndQuery$$[1]?$opt_addToFront$$?"?"+$paramString$$+"&"+$mainAndQuery$$[1]:"?"+$mainAndQuery$$[1]+"&"+$paramString$$:"?"+$paramString$$);return $newUrl$$+=$mainAndFragment$$[1]?"#"+$mainAndFragment$$[1]:""}
function $addParamToUrl$$module$src$url$$($url$jscomp$25$$,$field$jscomp$1_value$jscomp$93$$){$field$jscomp$1_value$jscomp$93$$=encodeURIComponent("iid")+"="+encodeURIComponent($field$jscomp$1_value$jscomp$93$$);return $appendEncodedParamStringToUrl$$module$src$url$$($url$jscomp$25$$,$field$jscomp$1_value$jscomp$93$$,void 0)}
function $addParamsToUrl$$module$src$url$$($url$jscomp$26$$,$params$jscomp$3$$){var $JSCompiler_s$jscomp$inline_68$$=[],$JSCompiler_k$jscomp$inline_69$$;for($JSCompiler_k$jscomp$inline_69$$ in $params$jscomp$3$$){var $JSCompiler_v$jscomp$inline_70_sv$0$jscomp$inline_73$$=$params$jscomp$3$$[$JSCompiler_k$jscomp$inline_69$$];if(null!=$JSCompiler_v$jscomp$inline_70_sv$0$jscomp$inline_73$$)if(Array.isArray($JSCompiler_v$jscomp$inline_70_sv$0$jscomp$inline_73$$))for(var $JSCompiler_i$jscomp$inline_71$$=
0;$JSCompiler_i$jscomp$inline_71$$<$JSCompiler_v$jscomp$inline_70_sv$0$jscomp$inline_73$$.length;$JSCompiler_i$jscomp$inline_71$$++){var $JSCompiler_sv$jscomp$inline_72$$=$JSCompiler_v$jscomp$inline_70_sv$0$jscomp$inline_73$$[$JSCompiler_i$jscomp$inline_71$$];$JSCompiler_s$jscomp$inline_68$$.push(encodeURIComponent($JSCompiler_k$jscomp$inline_69$$)+"="+encodeURIComponent($JSCompiler_sv$jscomp$inline_72$$))}else $JSCompiler_s$jscomp$inline_68$$.push(encodeURIComponent($JSCompiler_k$jscomp$inline_69$$)+
"="+encodeURIComponent($JSCompiler_v$jscomp$inline_70_sv$0$jscomp$inline_73$$))}return $appendEncodedParamStringToUrl$$module$src$url$$($url$jscomp$26$$,$JSCompiler_s$jscomp$inline_68$$.join("&"))};function $tryParseJson$$module$src$json$$($json$jscomp$1$$,$opt_onFailed$$){try{return JSON.parse($json$jscomp$1$$)}catch($e$jscomp$16$$){return $opt_onFailed$$&&$opt_onFailed$$($e$jscomp$16$$),null}};function $deserializeMessage$$module$src$3p_frame_messaging$$($message$jscomp$30$$){if(!$isAmpMessage$$module$src$3p_frame_messaging$$($message$jscomp$30$$))return null;var $startPos$$=$message$jscomp$30$$.indexOf("{");try{return JSON.parse($message$jscomp$30$$.substr($startPos$$))}catch($e$jscomp$17$$){return $dev$$module$src$log$$().error("MESSAGING","Failed to parse message: "+$message$jscomp$30$$,$e$jscomp$17$$),null}}
function $isAmpMessage$$module$src$3p_frame_messaging$$($message$jscomp$31$$){return"string"==typeof $message$jscomp$31$$&&0==$message$jscomp$31$$.indexOf("amp-")&&-1!=$message$jscomp$31$$.indexOf("{")};var $propertyNameCache$$module$src$style$$,$vendorPrefixes$$module$src$style$$="Webkit webkit Moz moz ms O o".split(" ");
function $setStyle$$module$src$style$$($element$jscomp$62$$,$JSCompiler_inline_result$jscomp$23_property$jscomp$4_propertyName$jscomp$10$$,$value$jscomp$95$$){var $opt_units$$;var $JSCompiler_style$jscomp$inline_75$$=$element$jscomp$62$$.style;if(2>$JSCompiler_inline_result$jscomp$23_property$jscomp$4_propertyName$jscomp$10$$.length||0!=$JSCompiler_inline_result$jscomp$23_property$jscomp$4_propertyName$jscomp$10$$.lastIndexOf("--",0)){$propertyNameCache$$module$src$style$$||($propertyNameCache$$module$src$style$$=
Object.create(null));var $JSCompiler_propertyName$jscomp$inline_78$$=$propertyNameCache$$module$src$style$$[$JSCompiler_inline_result$jscomp$23_property$jscomp$4_propertyName$jscomp$10$$];if(!$JSCompiler_propertyName$jscomp$inline_78$$){$JSCompiler_propertyName$jscomp$inline_78$$=$JSCompiler_inline_result$jscomp$23_property$jscomp$4_propertyName$jscomp$10$$;if(void 0===$JSCompiler_style$jscomp$inline_75$$[$JSCompiler_inline_result$jscomp$23_property$jscomp$4_propertyName$jscomp$10$$]){var $JSCompiler_inline_result$jscomp$107_JSCompiler_prefixedPropertyName$jscomp$inline_80_JSCompiler_titleCase$jscomp$inline_79$$=
$JSCompiler_inline_result$jscomp$23_property$jscomp$4_propertyName$jscomp$10$$.charAt(0).toUpperCase()+$JSCompiler_inline_result$jscomp$23_property$jscomp$4_propertyName$jscomp$10$$.slice(1);b:{for(var $JSCompiler_i$jscomp$inline_126$$=0;$JSCompiler_i$jscomp$inline_126$$<$vendorPrefixes$$module$src$style$$.length;$JSCompiler_i$jscomp$inline_126$$++){var $JSCompiler_propertyName$jscomp$inline_127$$=$vendorPrefixes$$module$src$style$$[$JSCompiler_i$jscomp$inline_126$$]+$JSCompiler_inline_result$jscomp$107_JSCompiler_prefixedPropertyName$jscomp$inline_80_JSCompiler_titleCase$jscomp$inline_79$$;
if(void 0!==$JSCompiler_style$jscomp$inline_75$$[$JSCompiler_propertyName$jscomp$inline_127$$]){$JSCompiler_inline_result$jscomp$107_JSCompiler_prefixedPropertyName$jscomp$inline_80_JSCompiler_titleCase$jscomp$inline_79$$=$JSCompiler_propertyName$jscomp$inline_127$$;break b}}$JSCompiler_inline_result$jscomp$107_JSCompiler_prefixedPropertyName$jscomp$inline_80_JSCompiler_titleCase$jscomp$inline_79$$=""}void 0!==$JSCompiler_style$jscomp$inline_75$$[$JSCompiler_inline_result$jscomp$107_JSCompiler_prefixedPropertyName$jscomp$inline_80_JSCompiler_titleCase$jscomp$inline_79$$]&&
($JSCompiler_propertyName$jscomp$inline_78$$=$JSCompiler_inline_result$jscomp$107_JSCompiler_prefixedPropertyName$jscomp$inline_80_JSCompiler_titleCase$jscomp$inline_79$$)}$propertyNameCache$$module$src$style$$[$JSCompiler_inline_result$jscomp$23_property$jscomp$4_propertyName$jscomp$10$$]=$JSCompiler_propertyName$jscomp$inline_78$$}$JSCompiler_inline_result$jscomp$23_property$jscomp$4_propertyName$jscomp$10$$=$JSCompiler_propertyName$jscomp$inline_78$$}$JSCompiler_inline_result$jscomp$23_property$jscomp$4_propertyName$jscomp$10$$&&
($element$jscomp$62$$.style[$JSCompiler_inline_result$jscomp$23_property$jscomp$4_propertyName$jscomp$10$$]=$opt_units$$?$value$jscomp$95$$+$opt_units$$:$value$jscomp$95$$)};function $getListenForSentinel$$module$src$iframe_helper$$($JSCompiler_inline_result$jscomp$24_parentWin$jscomp$2$$,$sentinel$jscomp$1$$,$opt_create$jscomp$1$$){var $JSCompiler_listeningFors$jscomp$inline_84$$=$JSCompiler_inline_result$jscomp$24_parentWin$jscomp$2$$.listeningFors;!$JSCompiler_listeningFors$jscomp$inline_84$$&&$opt_create$jscomp$1$$&&($JSCompiler_listeningFors$jscomp$inline_84$$=$JSCompiler_inline_result$jscomp$24_parentWin$jscomp$2$$.listeningFors=Object.create(null));$JSCompiler_inline_result$jscomp$24_parentWin$jscomp$2$$=
$JSCompiler_listeningFors$jscomp$inline_84$$||null;if(!$JSCompiler_inline_result$jscomp$24_parentWin$jscomp$2$$)return $JSCompiler_inline_result$jscomp$24_parentWin$jscomp$2$$;var $listenSentinel$$=$JSCompiler_inline_result$jscomp$24_parentWin$jscomp$2$$[$sentinel$jscomp$1$$];!$listenSentinel$$&&$opt_create$jscomp$1$$&&($listenSentinel$$=$JSCompiler_inline_result$jscomp$24_parentWin$jscomp$2$$[$sentinel$jscomp$1$$]=[]);return $listenSentinel$$||null}
function $getOrCreateListenForEvents$$module$src$iframe_helper$$($listenSentinel$jscomp$1_parentWin$jscomp$3$$,$iframe$$){var $opt_is3P$$=void 0,$i$jscomp$20_sentinel$jscomp$2$$=$opt_is3P$$?$iframe$$.getAttribute("data-amp-3p-sentinel"):"amp";$listenSentinel$jscomp$1_parentWin$jscomp$3$$=$getListenForSentinel$$module$src$iframe_helper$$($listenSentinel$jscomp$1_parentWin$jscomp$3$$,$i$jscomp$20_sentinel$jscomp$2$$,!0);for($i$jscomp$20_sentinel$jscomp$2$$=0;$i$jscomp$20_sentinel$jscomp$2$$<$listenSentinel$jscomp$1_parentWin$jscomp$3$$.length;$i$jscomp$20_sentinel$jscomp$2$$++){var $we$$=
$listenSentinel$jscomp$1_parentWin$jscomp$3$$[$i$jscomp$20_sentinel$jscomp$2$$];if($we$$.frame===$iframe$$){var $windowEvents$$=$we$$;break}}$windowEvents$$||($windowEvents$$={frame:$iframe$$,events:Object.create(null)},$listenSentinel$jscomp$1_parentWin$jscomp$3$$.push($windowEvents$$));return $windowEvents$$.events}
function $dropListenSentinel$$module$src$iframe_helper$$($listenSentinel$jscomp$3$$){for(var $noopData$$=$dict$$module$src$utils$object$$({sentinel:"unlisten"}),$i$jscomp$22$$=$listenSentinel$jscomp$3$$.length-1;0<=$i$jscomp$22$$;$i$jscomp$22$$--){var $windowEvents$jscomp$2$$=$listenSentinel$jscomp$3$$[$i$jscomp$22$$];if(!$windowEvents$jscomp$2$$.frame.contentWindow){$listenSentinel$jscomp$3$$.splice($i$jscomp$22$$,1);var $events$$=$windowEvents$jscomp$2$$.events,$name$jscomp$75$$;for($name$jscomp$75$$ in $events$$)$events$$[$name$jscomp$75$$].splice(0,
Infinity).forEach(function($listenSentinel$jscomp$3$$){$listenSentinel$jscomp$3$$($noopData$$)})}}}
function $registerGlobalListenerIfNeeded$$module$src$iframe_helper$$($parentWin$jscomp$5$$){if(!$parentWin$jscomp$5$$.listeningFors){var $listenForListener$$=function($listenForListener$$){if($listenForListener$$.data){var $data$jscomp$58$$=$parseIfNeeded$$module$src$iframe_helper$$($listenForListener$$.data);if($data$jscomp$58$$&&$data$jscomp$58$$.sentinel){var $event$jscomp$10$$=$listenForListener$$.source;var $JSCompiler_listenSentinel$jscomp$inline_89$$=$getListenForSentinel$$module$src$iframe_helper$$($parentWin$jscomp$5$$,
$data$jscomp$58$$.sentinel);if($JSCompiler_listenSentinel$jscomp$inline_89$$){for(var $JSCompiler_windowEvents$jscomp$inline_90$$,$JSCompiler_i$jscomp$inline_91$$=0;$JSCompiler_i$jscomp$inline_91$$<$JSCompiler_listenSentinel$jscomp$inline_89$$.length;$JSCompiler_i$jscomp$inline_91$$++){var $JSCompiler_we$jscomp$inline_92$$=$JSCompiler_listenSentinel$jscomp$inline_89$$[$JSCompiler_i$jscomp$inline_91$$],$JSCompiler_contentWindow$jscomp$inline_93$$=$JSCompiler_we$jscomp$inline_92$$.frame.contentWindow;
if($JSCompiler_contentWindow$jscomp$inline_93$$){var $JSCompiler_temp$jscomp$109_JSCompiler_win$jscomp$inline_131$$;if(!($JSCompiler_temp$jscomp$109_JSCompiler_win$jscomp$inline_131$$=$event$jscomp$10$$==$JSCompiler_contentWindow$jscomp$inline_93$$))b:{for($JSCompiler_temp$jscomp$109_JSCompiler_win$jscomp$inline_131$$=$event$jscomp$10$$;$JSCompiler_temp$jscomp$109_JSCompiler_win$jscomp$inline_131$$&&$JSCompiler_temp$jscomp$109_JSCompiler_win$jscomp$inline_131$$!=$JSCompiler_temp$jscomp$109_JSCompiler_win$jscomp$inline_131$$.parent;$JSCompiler_temp$jscomp$109_JSCompiler_win$jscomp$inline_131$$=
$JSCompiler_temp$jscomp$109_JSCompiler_win$jscomp$inline_131$$.parent)if($JSCompiler_temp$jscomp$109_JSCompiler_win$jscomp$inline_131$$==$JSCompiler_contentWindow$jscomp$inline_93$$){$JSCompiler_temp$jscomp$109_JSCompiler_win$jscomp$inline_131$$=!0;break b}$JSCompiler_temp$jscomp$109_JSCompiler_win$jscomp$inline_131$$=!1}if($JSCompiler_temp$jscomp$109_JSCompiler_win$jscomp$inline_131$$){$JSCompiler_windowEvents$jscomp$inline_90$$=$JSCompiler_we$jscomp$inline_92$$;break}}else setTimeout($dropListenSentinel$$module$src$iframe_helper$$,
0,$JSCompiler_listenSentinel$jscomp$inline_89$$)}$event$jscomp$10$$=$JSCompiler_windowEvents$jscomp$inline_90$$?$JSCompiler_windowEvents$jscomp$inline_90$$.events:null}else $event$jscomp$10$$=$JSCompiler_listenSentinel$jscomp$inline_89$$;var $listenForEvents$$=$event$jscomp$10$$;if($listenForEvents$$){var $listeners$$=$listenForEvents$$[$data$jscomp$58$$.type];if($listeners$$)for($listeners$$=$listeners$$.slice(),$event$jscomp$10$$=0;$event$jscomp$10$$<$listeners$$.length;$event$jscomp$10$$++)(0,$listeners$$[$event$jscomp$10$$])($data$jscomp$58$$,
$listenForListener$$.source,$listenForListener$$.origin)}}}};$parentWin$jscomp$5$$.addEventListener("message",$listenForListener$$)}}
function $listenFor$$module$src$iframe_helper$$($iframe$jscomp$1$$,$typeOfMessage$$,$callback$jscomp$66$$){function $listener$jscomp$67$$($typeOfMessage$$,$listener$jscomp$67$$,$listenForEvents$jscomp$1_parentWin$jscomp$6$$){if("amp"==$typeOfMessage$$.sentinel){if($listener$jscomp$67$$!=$iframe$jscomp$1$$.contentWindow)return;var $data$jscomp$59$$="null"==$listenForEvents$jscomp$1_parentWin$jscomp$6$$&&$opt_allowOpaqueOrigin$$;if($iframeOrigin$$!=$listenForEvents$jscomp$1_parentWin$jscomp$6$$&&!$data$jscomp$59$$)return}if($opt_includingNestedWindows$$||
$listener$jscomp$67$$==$iframe$jscomp$1$$.contentWindow)"unlisten"==$typeOfMessage$$.sentinel?$unlisten$jscomp$2$$():$callback$jscomp$66$$($typeOfMessage$$,$listener$jscomp$67$$,$listenForEvents$jscomp$1_parentWin$jscomp$6$$)}var $opt_includingNestedWindows$$,$opt_allowOpaqueOrigin$$,$listenForEvents$jscomp$1_parentWin$jscomp$6$$=$iframe$jscomp$1$$.ownerDocument.defaultView;$registerGlobalListenerIfNeeded$$module$src$iframe_helper$$($listenForEvents$jscomp$1_parentWin$jscomp$6$$);$listenForEvents$jscomp$1_parentWin$jscomp$6$$=
$getOrCreateListenForEvents$$module$src$iframe_helper$$($listenForEvents$jscomp$1_parentWin$jscomp$6$$,$iframe$jscomp$1$$);var $iframeOrigin$$=$parseUrlDeprecated$$module$src$url$$($iframe$jscomp$1$$.src).origin,$events$jscomp$1$$=$listenForEvents$jscomp$1_parentWin$jscomp$6$$[$typeOfMessage$$]||($listenForEvents$jscomp$1_parentWin$jscomp$6$$[$typeOfMessage$$]=[]);$events$jscomp$1$$.push($listener$jscomp$67$$);var $unlisten$jscomp$2$$=function(){if($listener$jscomp$67$$){var $iframe$jscomp$1$$=$events$jscomp$1$$.indexOf($listener$jscomp$67$$);
-1<$iframe$jscomp$1$$&&$events$jscomp$1$$.splice($iframe$jscomp$1$$,1);$callback$jscomp$66$$=$events$jscomp$1$$=$listener$jscomp$67$$=null}}}
function $parseIfNeeded$$module$src$iframe_helper$$($data$jscomp$61$$){"string"==typeof $data$jscomp$61$$&&($data$jscomp$61$$="{"==$data$jscomp$61$$.charAt(0)?$tryParseJson$$module$src$json$$($data$jscomp$61$$,function($data$jscomp$61$$){$dev$$module$src$log$$().warn("IFRAME-HELPER","Postmessage could not be parsed. Is it in a valid JSON format?",$data$jscomp$61$$)})||null:$isAmpMessage$$module$src$3p_frame_messaging$$($data$jscomp$61$$)?$deserializeMessage$$module$src$3p_frame_messaging$$($data$jscomp$61$$):
null);return $data$jscomp$61$$};var $ACCESS_CONFIG$$module$extensions$amp_access_poool$0_1$poool_impl$$={authorization:"https://api.poool.fr/api/v2/amp/access?rid=READER_ID",iframe:"https://assets.poool.fr/amp.html?rid=READER_ID&c=CANONICAL_URL&o=AMPDOC_URL&r=DOCUMENT_REFERRER"};
function $PooolVendor$$module$extensions$amp_access_poool$0_1$poool_impl$$($accessService$$,$accessSource$$){this.ampdoc=$accessService$$.ampdoc;this.$accessSource_$=$accessSource$$;this.$accessUrl_$=$ACCESS_CONFIG$$module$extensions$amp_access_poool$0_1$poool_impl$$.authorization;this.$iframeUrl_$=$ACCESS_CONFIG$$module$extensions$amp_access_poool$0_1$poool_impl$$.iframe;this.$timer_$=$getService$$module$src$service$$(this.ampdoc.win,"timer");this.$xhr_$=$getService$$module$src$service$$(this.ampdoc.win,
"xhr");this.$pooolConfig_$=this.$accessSource_$.getAdapterConfig();this.$bundleID_$=this.$pooolConfig_$.bundleID||"";this.$readerID_$="";this.$itemID_$=this.$pooolConfig_$.itemID||"";this.$iframe_$=document.createElement("iframe");this.$iframe_$.setAttribute("id","poool-iframe");this.$iframe_$.setAttribute("scrolling","no");this.$iframe_$.setAttribute("frameborder","0");$setStyle$$module$src$style$$(this.$iframe_$,"width","100%");if("unlock"==this.$pooolConfig_$.forceWidget){var $JSCompiler_element$jscomp$inline_133_JSCompiler_k$jscomp$inline_139$$=
this.$iframe_$,$JSCompiler_styles$jscomp$inline_134_JSCompiler_styles$jscomp$inline_138$$={height:"250px",position:"fixed",bottom:"0"};for($JSCompiler_element$jscomp$inline_137_JSCompiler_k$jscomp$inline_135$$ in $JSCompiler_styles$jscomp$inline_134_JSCompiler_styles$jscomp$inline_138$$)$setStyle$$module$src$style$$($JSCompiler_element$jscomp$inline_133_JSCompiler_k$jscomp$inline_139$$,$JSCompiler_element$jscomp$inline_137_JSCompiler_k$jscomp$inline_135$$,$JSCompiler_styles$jscomp$inline_134_JSCompiler_styles$jscomp$inline_138$$[$JSCompiler_element$jscomp$inline_137_JSCompiler_k$jscomp$inline_135$$])}else{var $JSCompiler_element$jscomp$inline_137_JSCompiler_k$jscomp$inline_135$$=
this.$iframe_$;$JSCompiler_styles$jscomp$inline_134_JSCompiler_styles$jscomp$inline_138$$={height:"500px",transform:"translateY(-70px)"};for($JSCompiler_element$jscomp$inline_133_JSCompiler_k$jscomp$inline_139$$ in $JSCompiler_styles$jscomp$inline_134_JSCompiler_styles$jscomp$inline_138$$)$setStyle$$module$src$style$$($JSCompiler_element$jscomp$inline_137_JSCompiler_k$jscomp$inline_135$$,$JSCompiler_element$jscomp$inline_133_JSCompiler_k$jscomp$inline_139$$,$JSCompiler_styles$jscomp$inline_134_JSCompiler_styles$jscomp$inline_138$$[$JSCompiler_element$jscomp$inline_133_JSCompiler_k$jscomp$inline_139$$])}$userAssert$$module$src$log$$(this.$bundleID_$,
"BundleID is incorrect or not provided.");$userAssert$$module$src$log$$(this.$itemID_$,"ItemID is not provided.")}
$PooolVendor$$module$extensions$amp_access_poool$0_1$poool_impl$$.prototype.authorize=function(){var $$jscomp$this$jscomp$2$$=this;return $JSCompiler_StaticMethods_getPooolAccess_$$(this).then(function($$jscomp$this$jscomp$2$$){return{access:$$jscomp$this$jscomp$2$$.access}},function($err$jscomp$4$$){if(!$err$jscomp$4$$||!$err$jscomp$4$$.response)throw $err$jscomp$4$$;if(402!==$err$jscomp$4$$.response.status)throw $err$jscomp$4$$;$JSCompiler_StaticMethods_renderPoool_$$($$jscomp$this$jscomp$2$$);
return{access:!1}})};
function $JSCompiler_StaticMethods_getPooolAccess_$$($JSCompiler_StaticMethods_getPooolAccess_$self$$){var $url$jscomp$41$$=$addParamToUrl$$module$src$url$$($JSCompiler_StaticMethods_getPooolAccess_$self$$.$accessUrl_$,$JSCompiler_StaticMethods_getPooolAccess_$self$$.$itemID_$),$urlPromise$$=$JSCompiler_StaticMethods_getPooolAccess_$self$$.$accessSource_$.buildUrl($url$jscomp$41$$,!1);return $urlPromise$$.then(function($url$jscomp$41$$){return $JSCompiler_StaticMethods_getPooolAccess_$self$$.$accessSource_$.getLoginUrl($url$jscomp$41$$)}).then(function($url$jscomp$41$$){$dev$$module$src$log$$().info("amp-access-poool","Authorization URL: ",
$url$jscomp$41$$);return $JSCompiler_StaticMethods_getPooolAccess_$self$$.$timer_$.timeoutPromise(3E3,$JSCompiler_StaticMethods_getPooolAccess_$self$$.$xhr_$.fetchJson($url$jscomp$41$$)).then(function($JSCompiler_StaticMethods_getPooolAccess_$self$$){return $JSCompiler_StaticMethods_getPooolAccess_$self$$.json()})})}
function $JSCompiler_StaticMethods_renderPoool_$$($JSCompiler_StaticMethods_renderPoool_$self$$){var $pooolContainer$$=document.getElementById("poool");$JSCompiler_StaticMethods_renderPoool_$self$$.$accessSource_$.buildUrl($addParamsToUrl$$module$src$url$$($JSCompiler_StaticMethods_renderPoool_$self$$.$iframeUrl_$,$dict$$module$src$utils$object$$({bi:$JSCompiler_StaticMethods_renderPoool_$self$$.$pooolConfig_$.bundleID,iid:$JSCompiler_StaticMethods_renderPoool_$self$$.$pooolConfig_$.itemID,ce:$JSCompiler_StaticMethods_renderPoool_$self$$.$pooolConfig_$.cookiesEnabled,
d:"undefined"!==typeof $JSCompiler_StaticMethods_renderPoool_$self$$.$pooolConfig_$.debug&&null!==$JSCompiler_StaticMethods_renderPoool_$self$$.$pooolConfig_$.debug?$JSCompiler_StaticMethods_renderPoool_$self$$.$pooolConfig_$.debug:$getMode$$module$src$mode$$().development||$getMode$$module$src$mode$$().localDev,fw:$JSCompiler_StaticMethods_renderPoool_$self$$.$pooolConfig_$.forceWidget,cs:$JSCompiler_StaticMethods_renderPoool_$self$$.$pooolConfig_$.customSegment})),!1).then(function($url$jscomp$44$$){$JSCompiler_StaticMethods_renderPoool_$self$$.$iframe_$.src=
$url$jscomp$44$$;$listenFor$$module$src$iframe_helper$$($JSCompiler_StaticMethods_renderPoool_$self$$.$iframe_$,"release",$JSCompiler_StaticMethods_renderPoool_$self$$.$onRelease_$.bind($JSCompiler_StaticMethods_renderPoool_$self$$));$listenFor$$module$src$iframe_helper$$($JSCompiler_StaticMethods_renderPoool_$self$$.$iframe_$,"resize",$JSCompiler_StaticMethods_renderPoool_$self$$.$onResize_$.bind($JSCompiler_StaticMethods_renderPoool_$self$$));$pooolContainer$$.appendChild($JSCompiler_StaticMethods_renderPoool_$self$$.$iframe_$)})}
$PooolVendor$$module$extensions$amp_access_poool$0_1$poool_impl$$.prototype.$onRelease_$=function(){var $articlePreview$$=document.querySelector("[poool-access-preview]");$articlePreview$$.setAttribute("amp-access-hide","");var $articleContent$$=document.querySelector("[poool-access-content]");$articleContent$$.removeAttribute("amp-access-hide");for(var $JSCompiler_element$jscomp$inline_99$$=this.$iframe_$,$JSCompiler_properties$jscomp$inline_100$$=["transform"],$JSCompiler_i$jscomp$inline_101$$=
0;$JSCompiler_i$jscomp$inline_101$$<$JSCompiler_properties$jscomp$inline_100$$.length;$JSCompiler_i$jscomp$inline_101$$++)$setStyle$$module$src$style$$($JSCompiler_element$jscomp$inline_99$$,$JSCompiler_properties$jscomp$inline_100$$[$JSCompiler_i$jscomp$inline_101$$],null)};$PooolVendor$$module$extensions$amp_access_poool$0_1$poool_impl$$.prototype.$onResize_$=function($msg$$){$setStyle$$module$src$style$$(this.$iframe_$,"height",$msg$$.height)};
$PooolVendor$$module$extensions$amp_access_poool$0_1$poool_impl$$.prototype.pingback=function(){return Promise.resolve()};(function($AMP$jscomp$1$$){$AMP$jscomp$1$$.registerServiceForDoc("poool",function($AMP$jscomp$1$$){$AMP$jscomp$1$$=$AMP$jscomp$1$$.getHeadNode();return $getElementServiceForDoc$$module$src$element_service$$($AMP$jscomp$1$$).then(function($AMP$jscomp$1$$){var $ampdoc$jscomp$10_element$jscomp$69$$=$AMP$jscomp$1$$.getVendorSource("poool"),$accessService$jscomp$1$$=new $PooolVendor$$module$extensions$amp_access_poool$0_1$poool_impl$$($AMP$jscomp$1$$,$ampdoc$jscomp$10_element$jscomp$69$$),$adapter$$=$ampdoc$jscomp$10_element$jscomp$69$$.getAdapter();
$adapter$$.registerVendor($accessService$jscomp$1$$);return $accessService$jscomp$1$$})})})(self.AMP);
})});

//# sourceMappingURL=amp-access-poool-0.1.js.map
