(self.AMP=self.AMP||[]).push({n:"amp-install-serviceworker",v:"1904281823091",f:(function(AMP,_){
var $$jscomp$objectCreate$$="function"==typeof Object.create?Object.create:function($prototype$$){function $ctor$$(){}$ctor$$.prototype=$prototype$$;return new $ctor$$},$JSCompiler_temp$jscomp$9$$;
if("function"==typeof Object.setPrototypeOf)$JSCompiler_temp$jscomp$9$$=Object.setPrototypeOf;else{var $JSCompiler_inline_result$jscomp$10$$;a:{var $JSCompiler_x$jscomp$inline_17$$={a:!0},$JSCompiler_y$jscomp$inline_18$$={};try{$JSCompiler_y$jscomp$inline_18$$.__proto__=$JSCompiler_x$jscomp$inline_17$$;$JSCompiler_inline_result$jscomp$10$$=$JSCompiler_y$jscomp$inline_18$$.a;break a}catch($JSCompiler_e$jscomp$inline_19$$){}$JSCompiler_inline_result$jscomp$10$$=!1}$JSCompiler_temp$jscomp$9$$=$JSCompiler_inline_result$jscomp$10$$?
function($target$jscomp$83$$,$proto$jscomp$3$$){$target$jscomp$83$$.__proto__=$proto$jscomp$3$$;if($target$jscomp$83$$.__proto__!==$proto$jscomp$3$$)throw new TypeError($target$jscomp$83$$+" is not extensible");return $target$jscomp$83$$}:null}var $$jscomp$setPrototypeOf$$=$JSCompiler_temp$jscomp$9$$;function $tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($component$jscomp$4$$,$fallback$$){$fallback$$=void 0===$fallback$$?"":$fallback$$;try{return decodeURIComponent($component$jscomp$4$$)}catch($e$jscomp$8$$){return $fallback$$}};var $regex$$module$src$url_parse_query_string$$=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;
function $parseQueryString_$$module$src$url_parse_query_string$$($queryString$$){var $params$jscomp$1$$=Object.create(null);if(!$queryString$$)return $params$jscomp$1$$;for(var $match$$;$match$$=$regex$$module$src$url_parse_query_string$$.exec($queryString$$);){var $name$jscomp$70$$=$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($match$$[1],$match$$[1]),$value$jscomp$87$$=$match$$[2]?$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($match$$[2],$match$$[2]):"";
$params$jscomp$1$$[$name$jscomp$70$$]=$value$jscomp$87$$}return $params$jscomp$1$$};var $rtvVersion$$module$src$mode$$="";
function $getMode$$module$src$mode$$(){var $opt_win$$,$win$$=$opt_win$$||self;if($win$$.AMP_MODE)var $JSCompiler_temp$jscomp$11_JSCompiler_win$jscomp$inline_21$$=$win$$.AMP_MODE;else{$JSCompiler_temp$jscomp$11_JSCompiler_win$jscomp$inline_21$$=$win$$;var $JSCompiler_AMP_CONFIG$jscomp$inline_22_JSCompiler_singlePassType$jscomp$inline_29$$=self.AMP_CONFIG||{},$JSCompiler_runningTests$jscomp$inline_26$$=!!$JSCompiler_AMP_CONFIG$jscomp$inline_22_JSCompiler_singlePassType$jscomp$inline_29$$.test||!(!$JSCompiler_temp$jscomp$11_JSCompiler_win$jscomp$inline_21$$.AMP_TEST&&
!$JSCompiler_temp$jscomp$11_JSCompiler_win$jscomp$inline_21$$.__karma__),$JSCompiler_isLocalDev$jscomp$inline_27$$=!!$JSCompiler_AMP_CONFIG$jscomp$inline_22_JSCompiler_singlePassType$jscomp$inline_29$$.localDev||$JSCompiler_runningTests$jscomp$inline_26$$,$JSCompiler_hashQuery$jscomp$inline_28$$=$parseQueryString_$$module$src$url_parse_query_string$$($JSCompiler_temp$jscomp$11_JSCompiler_win$jscomp$inline_21$$.location.originalHash||$JSCompiler_temp$jscomp$11_JSCompiler_win$jscomp$inline_21$$.location.hash);
$JSCompiler_AMP_CONFIG$jscomp$inline_22_JSCompiler_singlePassType$jscomp$inline_29$$=$JSCompiler_AMP_CONFIG$jscomp$inline_22_JSCompiler_singlePassType$jscomp$inline_29$$.spt;var $JSCompiler_searchQuery$jscomp$inline_30$$=$parseQueryString_$$module$src$url_parse_query_string$$($JSCompiler_temp$jscomp$11_JSCompiler_win$jscomp$inline_21$$.location.search);$rtvVersion$$module$src$mode$$||($rtvVersion$$module$src$mode$$=$JSCompiler_isLocalDev$jscomp$inline_27$$?"1904281823091":$JSCompiler_temp$jscomp$11_JSCompiler_win$jscomp$inline_21$$.AMP_CONFIG&&
$JSCompiler_temp$jscomp$11_JSCompiler_win$jscomp$inline_21$$.AMP_CONFIG.v?$JSCompiler_temp$jscomp$11_JSCompiler_win$jscomp$inline_21$$.AMP_CONFIG.v:"011904281823091");$JSCompiler_temp$jscomp$11_JSCompiler_win$jscomp$inline_21$$=$win$$.AMP_MODE={localDev:$JSCompiler_isLocalDev$jscomp$inline_27$$,development:!("1"!=$JSCompiler_hashQuery$jscomp$inline_28$$.development&&!$JSCompiler_temp$jscomp$11_JSCompiler_win$jscomp$inline_21$$.AMP_DEV_MODE),examiner:"2"==$JSCompiler_hashQuery$jscomp$inline_28$$.development,
filter:$JSCompiler_hashQuery$jscomp$inline_28$$.filter,geoOverride:$JSCompiler_hashQuery$jscomp$inline_28$$["amp-geo"],minified:!0,lite:void 0!=$JSCompiler_searchQuery$jscomp$inline_30$$.amp_lite,test:$JSCompiler_runningTests$jscomp$inline_26$$,log:$JSCompiler_hashQuery$jscomp$inline_28$$.log,version:"1904281823091",rtvVersion:$rtvVersion$$module$src$mode$$,singlePassType:$JSCompiler_AMP_CONFIG$jscomp$inline_22_JSCompiler_singlePassType$jscomp$inline_29$$}}return $JSCompiler_temp$jscomp$11_JSCompiler_win$jscomp$inline_21$$}
;self.log=self.log||{user:null,dev:null,userForEmbed:null};var $logs$$module$src$log$$=self.log;function $user$$module$src$log$$(){if(!$logs$$module$src$log$$.user)throw Error("failed to call initLogConstructor");return $logs$$module$src$log$$.user}
function $userAssert$$module$src$log$$($shouldBeTrueish$jscomp$3$$,$opt_message$jscomp$14$$,$opt_1$jscomp$1$$,$opt_2$jscomp$1$$,$opt_3$jscomp$1$$){$user$$module$src$log$$().assert($shouldBeTrueish$jscomp$3$$,$opt_message$jscomp$14$$,$opt_1$jscomp$1$$,$opt_2$jscomp$1$$,$opt_3$jscomp$1$$,void 0,void 0,void 0,void 0,void 0,void 0)};function $getExistingServiceForDocInEmbedScope$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_60_JSCompiler_holder$jscomp$inline_61_element$jscomp$11$$){var $opt_fallbackToTopWin$$,$win$jscomp$6$$=$JSCompiler_ampdoc$jscomp$inline_60_JSCompiler_holder$jscomp$inline_61_element$jscomp$11$$.ownerDocument.defaultView,$isEmbed$$=$win$jscomp$6$$!=($win$jscomp$6$$.__AMP_TOP||$win$jscomp$6$$);if($isEmbed$$){if($isServiceRegistered$$module$src$service$$($win$jscomp$6$$,"url")){var $embedService$$=$getServiceInternal$$module$src$service$$($win$jscomp$6$$,
"url");if($embedService$$)return $embedService$$}if(!$opt_fallbackToTopWin$$)return null}$JSCompiler_ampdoc$jscomp$inline_60_JSCompiler_holder$jscomp$inline_61_element$jscomp$11$$=$getAmpdoc$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_60_JSCompiler_holder$jscomp$inline_61_element$jscomp$11$$);$JSCompiler_ampdoc$jscomp$inline_60_JSCompiler_holder$jscomp$inline_61_element$jscomp$11$$=$getAmpdocServiceHolder$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_60_JSCompiler_holder$jscomp$inline_61_element$jscomp$11$$);
return $isServiceRegistered$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_60_JSCompiler_holder$jscomp$inline_61_element$jscomp$11$$,"url")?$getServiceInternal$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_60_JSCompiler_holder$jscomp$inline_61_element$jscomp$11$$,"url"):null}
function $getService$$module$src$service$$($win$jscomp$8$$,$id$jscomp$11$$){$win$jscomp$8$$=$win$jscomp$8$$.__AMP_TOP||$win$jscomp$8$$;return $getServiceInternal$$module$src$service$$($win$jscomp$8$$,$id$jscomp$11$$)}
function $getServiceForDoc$$module$src$service$$($elementOrAmpDoc$$,$id$jscomp$15$$){var $ampdoc$jscomp$2_holder$jscomp$2$$=$getAmpdoc$$module$src$service$$($elementOrAmpDoc$$);$ampdoc$jscomp$2_holder$jscomp$2$$=$getAmpdocServiceHolder$$module$src$service$$($ampdoc$jscomp$2_holder$jscomp$2$$);return $getServiceInternal$$module$src$service$$($ampdoc$jscomp$2_holder$jscomp$2$$,$id$jscomp$15$$)}
function $getAmpdoc$$module$src$service$$($nodeOrDoc$jscomp$2$$){return $nodeOrDoc$jscomp$2$$.nodeType?$getService$$module$src$service$$(($nodeOrDoc$jscomp$2$$.ownerDocument||$nodeOrDoc$jscomp$2$$).defaultView,"ampdoc").getAmpDoc($nodeOrDoc$jscomp$2$$):$nodeOrDoc$jscomp$2$$}
function $getAmpdocServiceHolder$$module$src$service$$($ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$){$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$=$getAmpdoc$$module$src$service$$($ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$);return $ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$.isSingleDoc()?$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$.win:$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$}
function $getServiceInternal$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$,$id$jscomp$19$$){$isServiceRegistered$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$,$id$jscomp$19$$);var $JSCompiler_services$jscomp$inline_36$$=$holder$jscomp$4_s$jscomp$8$$.services;$JSCompiler_services$jscomp$inline_36$$||($JSCompiler_services$jscomp$inline_36$$=$holder$jscomp$4_s$jscomp$8$$.services={});var $services$$=$JSCompiler_services$jscomp$inline_36$$;$holder$jscomp$4_s$jscomp$8$$=$services$$[$id$jscomp$19$$];
$holder$jscomp$4_s$jscomp$8$$.obj||($holder$jscomp$4_s$jscomp$8$$.obj=new $holder$jscomp$4_s$jscomp$8$$.ctor($holder$jscomp$4_s$jscomp$8$$.context),$holder$jscomp$4_s$jscomp$8$$.ctor=null,$holder$jscomp$4_s$jscomp$8$$.context=null,$holder$jscomp$4_s$jscomp$8$$.resolve&&$holder$jscomp$4_s$jscomp$8$$.resolve($holder$jscomp$4_s$jscomp$8$$.obj));return $holder$jscomp$4_s$jscomp$8$$.obj}
function $isServiceRegistered$$module$src$service$$($holder$jscomp$12_service$jscomp$4$$,$id$jscomp$27$$){$holder$jscomp$12_service$jscomp$4$$=$holder$jscomp$12_service$jscomp$4$$.services&&$holder$jscomp$12_service$jscomp$4$$.services[$id$jscomp$27$$];return!(!$holder$jscomp$12_service$jscomp$4$$||!$holder$jscomp$12_service$jscomp$4$$.ctor&&!$holder$jscomp$12_service$jscomp$4$$.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function $dict$$module$src$utils$object$$($opt_initial$jscomp$1$$){return $opt_initial$jscomp$1$$||{}};function $closest$$module$src$dom$$($el$jscomp$2_element$jscomp$17$$,$callback$jscomp$60$$){for(var $opt_stopAt$$;$el$jscomp$2_element$jscomp$17$$&&$el$jscomp$2_element$jscomp$17$$!==$opt_stopAt$$;$el$jscomp$2_element$jscomp$17$$=$el$jscomp$2_element$jscomp$17$$.parentElement)if($callback$jscomp$60$$($el$jscomp$2_element$jscomp$17$$))return $el$jscomp$2_element$jscomp$17$$;return null}
function $closestAncestorElementBySelector$$module$src$dom$$($element$jscomp$18$$){return $element$jscomp$18$$.closest?$element$jscomp$18$$.closest("A"):$closest$$module$src$dom$$($element$jscomp$18$$,function($element$jscomp$18$$){var $JSCompiler_matcher$jscomp$inline_40$$=$element$jscomp$18$$.matches||$element$jscomp$18$$.webkitMatchesSelector||$element$jscomp$18$$.mozMatchesSelector||$element$jscomp$18$$.msMatchesSelector||$element$jscomp$18$$.oMatchesSelector;return $JSCompiler_matcher$jscomp$inline_40$$?
$JSCompiler_matcher$jscomp$inline_40$$.call($element$jscomp$18$$,"A"):!1})};var $optsSupported$$module$src$event_helper_listen$$;
function $internalListenImplementation$$module$src$event_helper_listen$$($element$jscomp$55$$,$listener$jscomp$62$$){var $opt_evtListenerOpts$$=void 0,$localElement$$=$element$jscomp$55$$,$localListener$$=$listener$jscomp$62$$;var $wrapped$$=function($element$jscomp$55$$){try{return $localListener$$($element$jscomp$55$$)}catch($e$jscomp$16$$){throw self.reportError($e$jscomp$16$$),$e$jscomp$16$$;}};var $optsSupported$$=$detectEvtListenerOptsSupport$$module$src$event_helper_listen$$(),$capture$$=!1;
$opt_evtListenerOpts$$&&($capture$$=$opt_evtListenerOpts$$.capture);$localElement$$.addEventListener("click",$wrapped$$,$optsSupported$$?$opt_evtListenerOpts$$:$capture$$)}
function $detectEvtListenerOptsSupport$$module$src$event_helper_listen$$(){if(void 0!==$optsSupported$$module$src$event_helper_listen$$)return $optsSupported$$module$src$event_helper_listen$$;$optsSupported$$module$src$event_helper_listen$$=!1;try{var $options$jscomp$14$$={get capture(){$optsSupported$$module$src$event_helper_listen$$=!0}};self.addEventListener("test-options",null,$options$jscomp$14$$);self.removeEventListener("test-options",null,$options$jscomp$14$$)}catch($err$jscomp$3$$){}return $optsSupported$$module$src$event_helper_listen$$}
;var $env$$module$src$config$$=self.AMP_CONFIG||{},$urls$$module$src$config$$={thirdParty:$env$$module$src$config$$.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:$env$$module$src$config$$.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof $env$$module$src$config$$.thirdPartyFrameRegex?new RegExp($env$$module$src$config$$.thirdPartyFrameRegex):$env$$module$src$config$$.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:$env$$module$src$config$$.cdnUrl||
"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof $env$$module$src$config$$.cdnProxyRegex?new RegExp($env$$module$src$config$$.cdnProxyRegex):$env$$module$src$config$$.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:$env$$module$src$config$$.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:$env$$module$src$config$$.localDev||!1};$dict$$module$src$utils$object$$({c:!0,v:!0,a:!0,ad:!0,action:!0});function $removeFragment$$module$src$url$$($url$jscomp$29$$){var $index$jscomp$69$$=$url$jscomp$29$$.indexOf("#");return-1==$index$jscomp$69$$?$url$jscomp$29$$:$url$jscomp$29$$.substring(0,$index$jscomp$69$$)};function $toggle$$module$src$style$$($element$jscomp$63$$){var $opt_display$$=!1;void 0===$opt_display$$&&($opt_display$$=$element$jscomp$63$$.hasAttribute("hidden"));$opt_display$$?$element$jscomp$63$$.removeAttribute("hidden"):$element$jscomp$63$$.setAttribute("hidden","")};function $AmpInstallServiceWorker$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$($$jscomp$super$this_element$jscomp$65$$){$$jscomp$super$this_element$jscomp$65$$=AMP.BaseElement.call(this,$$jscomp$super$this_element$jscomp$65$$)||this;$$jscomp$super$this_element$jscomp$65$$.$iframeSrc_$=null;$$jscomp$super$this_element$jscomp$65$$.$urlRewriter_$=null;$$jscomp$super$this_element$jscomp$65$$.$isSafari_$=$getService$$module$src$service$$($$jscomp$super$this_element$jscomp$65$$.win,
"platform").isSafari();return $$jscomp$super$this_element$jscomp$65$$}var $JSCompiler_parentCtor$jscomp$inline_43$$=AMP.BaseElement;$AmpInstallServiceWorker$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$.prototype=$$jscomp$objectCreate$$($JSCompiler_parentCtor$jscomp$inline_43$$.prototype);$AmpInstallServiceWorker$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$.prototype.constructor=$AmpInstallServiceWorker$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$;
if($$jscomp$setPrototypeOf$$)$$jscomp$setPrototypeOf$$($AmpInstallServiceWorker$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$,$JSCompiler_parentCtor$jscomp$inline_43$$);else for(var $JSCompiler_p$jscomp$inline_44$$ in $JSCompiler_parentCtor$jscomp$inline_43$$)if("prototype"!=$JSCompiler_p$jscomp$inline_44$$)if(Object.defineProperties){var $JSCompiler_descriptor$jscomp$inline_45$$=Object.getOwnPropertyDescriptor($JSCompiler_parentCtor$jscomp$inline_43$$,$JSCompiler_p$jscomp$inline_44$$);
$JSCompiler_descriptor$jscomp$inline_45$$&&Object.defineProperty($AmpInstallServiceWorker$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$,$JSCompiler_p$jscomp$inline_44$$,$JSCompiler_descriptor$jscomp$inline_45$$)}else $AmpInstallServiceWorker$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$[$JSCompiler_p$jscomp$inline_44$$]=$JSCompiler_parentCtor$jscomp$inline_43$$[$JSCompiler_p$jscomp$inline_44$$];
$AmpInstallServiceWorker$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$.$superClass_$=$JSCompiler_parentCtor$jscomp$inline_43$$.prototype;
$AmpInstallServiceWorker$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$.prototype.buildCallback=function(){var $$jscomp$this$jscomp$1$$=this,$win$jscomp$46$$=this.win;if("serviceWorker"in $win$jscomp$46$$.navigator){var $urlService$$=$getExistingServiceForDocInEmbedScope$$module$src$service$$(this.element),$src$jscomp$4$$=this.element.getAttribute("src");$urlService$$.assertHttpsUrl($src$jscomp$4$$,this.element);if(!$urlService$$.isProxyOrigin($src$jscomp$4$$)&&!$urlService$$.isProxyOrigin($win$jscomp$46$$.location.href)||
this.$isSafari_$)$urlService$$.parse($win$jscomp$46$$.location.href).origin==$urlService$$.parse($src$jscomp$4$$).origin?$JSCompiler_StaticMethods_whenLoadedAndVisiblePromise_$$(this).then(function(){return $install$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$($$jscomp$this$jscomp$1$$.win,$src$jscomp$4$$,$$jscomp$this$jscomp$1$$.element)}):this.user().error("amp-install-serviceworker","Did not install ServiceWorker because it does not match the current origin: "+$src$jscomp$4$$);
else{var $iframeSrc$$=this.element.getAttribute("data-iframe-src");if($iframeSrc$$){$urlService$$.assertHttpsUrl($iframeSrc$$,this.element);var $origin$jscomp$1$$=$urlService$$.parse($iframeSrc$$).origin,$docInfo$$=$getServiceForDoc$$module$src$service$$(this.element,"documentInfo").get(),$sourceUrl$$=$urlService$$.parse($docInfo$$.sourceUrl),$canonicalUrl$$=$urlService$$.parse($docInfo$$.canonicalUrl);$userAssert$$module$src$log$$($origin$jscomp$1$$==$sourceUrl$$.origin||$origin$jscomp$1$$==$canonicalUrl$$.origin,
"data-iframe-src (%s) should be a URL on the same origin as the source (%s) or canonical URL (%s) of the AMP-document.",$origin$jscomp$1$$,$sourceUrl$$.origin,$canonicalUrl$$.origin);this.$iframeSrc_$=$iframeSrc$$;$JSCompiler_StaticMethods_whenLoadedAndVisiblePromise_$$(this).then(function(){return $JSCompiler_StaticMethods_insertIframe_$$($$jscomp$this$jscomp$1$$)})}}($urlService$$.isProxyOrigin($src$jscomp$4$$)||$urlService$$.isProxyOrigin($win$jscomp$46$$.location.href))&&this.$isSafari_$&&this.user().error("amp-install-serviceworker",
"Did not install ServiceWorker because of safari double keyring caching as it will not have any effect")}else $JSCompiler_StaticMethods_maybeInstallUrlRewrite_$$(this)};
function $JSCompiler_StaticMethods_whenLoadedAndVisiblePromise_$$($JSCompiler_StaticMethods_whenLoadedAndVisiblePromise_$self$$){return Promise.all([$JSCompiler_StaticMethods_whenLoadedAndVisiblePromise_$self$$.loadPromise($JSCompiler_StaticMethods_whenLoadedAndVisiblePromise_$self$$.win),$getServiceForDoc$$module$src$service$$($JSCompiler_StaticMethods_whenLoadedAndVisiblePromise_$self$$.getAmpDoc(),"viewer").whenFirstVisible()])}
function $JSCompiler_StaticMethods_insertIframe_$$($JSCompiler_StaticMethods_insertIframe_$self$$){return $JSCompiler_StaticMethods_insertIframe_$self$$.mutateElement(function(){$toggle$$module$src$style$$($JSCompiler_StaticMethods_insertIframe_$self$$.element);var $iframe$$=$JSCompiler_StaticMethods_insertIframe_$self$$.win.document.createElement("iframe");$iframe$$.setAttribute("sandbox","allow-same-origin allow-scripts");$iframe$$.src=$JSCompiler_StaticMethods_insertIframe_$self$$.$iframeSrc_$;
$JSCompiler_StaticMethods_insertIframe_$self$$.element.appendChild($iframe$$)})}
function $JSCompiler_StaticMethods_maybeInstallUrlRewrite_$$($JSCompiler_StaticMethods_maybeInstallUrlRewrite_$self$$){if($JSCompiler_StaticMethods_maybeInstallUrlRewrite_$self$$.getAmpDoc().isSingleDoc()){var $ampdoc$jscomp$10$$=$JSCompiler_StaticMethods_maybeInstallUrlRewrite_$self$$.getAmpDoc(),$win$jscomp$47$$=$JSCompiler_StaticMethods_maybeInstallUrlRewrite_$self$$.win,$urlService$jscomp$1$$=$getExistingServiceForDocInEmbedScope$$module$src$service$$($JSCompiler_StaticMethods_maybeInstallUrlRewrite_$self$$.element),$winUrl$$=
$urlService$jscomp$1$$.parse($win$jscomp$47$$.location.href),$urlMatch$$=$JSCompiler_StaticMethods_maybeInstallUrlRewrite_$self$$.element.getAttribute("data-no-service-worker-fallback-url-match"),$shellUrl$$=$JSCompiler_StaticMethods_maybeInstallUrlRewrite_$self$$.element.getAttribute("data-no-service-worker-fallback-shell-url");if($urlMatch$$||$shellUrl$$){$userAssert$$module$src$log$$($urlMatch$$&&$shellUrl$$,'Both, "%s" and "%s" must be specified for url-rewrite',"data-no-service-worker-fallback-url-match",
"data-no-service-worker-fallback-shell-url");$shellUrl$$=$removeFragment$$module$src$url$$($shellUrl$$);try{var $urlMatchExpr$$=new RegExp($urlMatch$$)}catch($e$jscomp$18$$){throw $user$$module$src$log$$().createError('Invalid "data-no-service-worker-fallback-url-match" expression',$e$jscomp$18$$);}$userAssert$$module$src$log$$($urlService$jscomp$1$$.getSourceOrigin($winUrl$$)==$urlService$jscomp$1$$.parse($shellUrl$$).origin,'Shell source origin "%s" must be the same as source origin "%s"',$shellUrl$$,
$winUrl$$.href);$JSCompiler_StaticMethods_maybeInstallUrlRewrite_$self$$.$urlRewriter_$=new $UrlRewriter_$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$($ampdoc$jscomp$10$$,$urlMatchExpr$$,$shellUrl$$,$JSCompiler_StaticMethods_maybeInstallUrlRewrite_$self$$.element);$urlService$jscomp$1$$.isSecure($shellUrl$$)&&$JSCompiler_StaticMethods_waitToPreloadShell_$$($JSCompiler_StaticMethods_maybeInstallUrlRewrite_$self$$,$shellUrl$$)}}}
function $JSCompiler_StaticMethods_waitToPreloadShell_$$($JSCompiler_StaticMethods_waitToPreloadShell_$self$$,$shellUrl$jscomp$1$$){$JSCompiler_StaticMethods_whenLoadedAndVisiblePromise_$$($JSCompiler_StaticMethods_waitToPreloadShell_$self$$).then(function(){$JSCompiler_StaticMethods_waitToPreloadShell_$self$$.mutateElement(function(){return $JSCompiler_StaticMethods_preloadShell_$$($JSCompiler_StaticMethods_waitToPreloadShell_$self$$,$shellUrl$jscomp$1$$)})})}
function $JSCompiler_StaticMethods_preloadShell_$$($JSCompiler_StaticMethods_preloadShell_$self$$,$shellUrl$jscomp$2$$){var $iframe$jscomp$1$$=$JSCompiler_StaticMethods_preloadShell_$self$$.win.document.createElement("iframe");$iframe$jscomp$1$$.id="i-amphtml-shell-preload";$iframe$jscomp$1$$.setAttribute("src",$shellUrl$jscomp$2$$+"#preload");$toggle$$module$src$style$$($iframe$jscomp$1$$);$iframe$jscomp$1$$.setAttribute("sandbox","allow-scripts allow-same-origin");var $loaded$$=$JSCompiler_StaticMethods_preloadShell_$self$$.loadPromise($iframe$jscomp$1$$);
$loaded$$.then(function(){$iframe$jscomp$1$$.parentElement&&$iframe$jscomp$1$$.parentElement.removeChild($iframe$jscomp$1$$)});$JSCompiler_StaticMethods_preloadShell_$self$$.element.appendChild($iframe$jscomp$1$$)}
function $UrlRewriter_$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$($JSCompiler_element$jscomp$inline_49_ampdoc$jscomp$11$$,$JSCompiler_listener$jscomp$inline_50_urlMatchExpr$jscomp$1$$,$shellUrl$jscomp$3$$,$element$jscomp$66$$){this.win=$JSCompiler_element$jscomp$inline_49_ampdoc$jscomp$11$$.win;this.$urlMatchExpr_$=$JSCompiler_listener$jscomp$inline_50_urlMatchExpr$jscomp$1$$;this.$shellUrl_$=$shellUrl$jscomp$3$$;this.$urlService_$=$getExistingServiceForDocInEmbedScope$$module$src$service$$($element$jscomp$66$$);
this.$shellLoc_$=this.$urlService_$.parse($shellUrl$jscomp$3$$);$JSCompiler_element$jscomp$inline_49_ampdoc$jscomp$11$$=$JSCompiler_element$jscomp$inline_49_ampdoc$jscomp$11$$.getRootNode();$JSCompiler_listener$jscomp$inline_50_urlMatchExpr$jscomp$1$$=this.$handle_$.bind(this);$internalListenImplementation$$module$src$event_helper_listen$$($JSCompiler_element$jscomp$inline_49_ampdoc$jscomp$11$$,$JSCompiler_listener$jscomp$inline_50_urlMatchExpr$jscomp$1$$)}
$UrlRewriter_$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$.prototype.$handle_$=function($event$jscomp$9_target$jscomp$87$$){if(!$event$jscomp$9_target$jscomp$87$$.defaultPrevented&&($event$jscomp$9_target$jscomp$87$$=$closestAncestorElementBySelector$$module$src$dom$$($event$jscomp$9_target$jscomp$87$$.target))&&$event$jscomp$9_target$jscomp$87$$.href){var $tgtLoc$$=this.$urlService_$.parse($event$jscomp$9_target$jscomp$87$$.href);if($tgtLoc$$.origin==this.$shellLoc_$.origin&&
$tgtLoc$$.pathname!=this.$shellLoc_$.pathname&&this.$urlMatchExpr_$.test($tgtLoc$$.href)&&!$event$jscomp$9_target$jscomp$87$$.getAttribute("i-amphtml-orig-href")){var $win$jscomp$49$$=this.win;$removeFragment$$module$src$url$$($tgtLoc$$.href)!=$removeFragment$$module$src$url$$($win$jscomp$49$$.location.href)&&($event$jscomp$9_target$jscomp$87$$.setAttribute("i-amphtml-orig-href",$event$jscomp$9_target$jscomp$87$$.href),$event$jscomp$9_target$jscomp$87$$.href=this.$shellUrl_$+"#href="+encodeURIComponent(""+
$tgtLoc$$.pathname+$tgtLoc$$.search+$tgtLoc$$.hash))}}};
function $install$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$($win$jscomp$50$$,$src$jscomp$5$$,$element$jscomp$67$$){var $options$jscomp$15$$={};$element$jscomp$67$$.hasAttribute("data-scope")&&($options$jscomp$15$$.scope=$element$jscomp$67$$.getAttribute("data-scope"));return $win$jscomp$50$$.navigator.serviceWorker.register($src$jscomp$5$$,$options$jscomp$15$$).then(function($src$jscomp$5$$){$getMode$$module$src$mode$$().development&&$user$$module$src$log$$().info("amp-install-serviceworker",
"ServiceWorker registration successful with scope: ",$src$jscomp$5$$.scope);var $options$jscomp$15$$=$src$jscomp$5$$.installing;$options$jscomp$15$$?$options$jscomp$15$$.addEventListener("statechange",function($options$jscomp$15$$){"activated"===$options$jscomp$15$$.target.state&&$performServiceWorkerOptimizations$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$($src$jscomp$5$$,$win$jscomp$50$$,$element$jscomp$67$$)}):$src$jscomp$5$$.active&&$performServiceWorkerOptimizations$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$($src$jscomp$5$$,
$win$jscomp$50$$,$element$jscomp$67$$);return $src$jscomp$5$$},function($win$jscomp$50$$){$user$$module$src$log$$().error("amp-install-serviceworker","ServiceWorker registration failed:",$win$jscomp$50$$)})}
function $performServiceWorkerOptimizations$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$($registration$jscomp$1$$,$win$jscomp$51$$,$element$jscomp$68$$){$sendAmpScriptToSwOnFirstVisit$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$($win$jscomp$51$$,$registration$jscomp$1$$);$element$jscomp$68$$.hasAttribute("data-prefetch")&&$prefetchOutgoingLinks$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$($registration$jscomp$1$$,
$win$jscomp$51$$)}
function $sendAmpScriptToSwOnFirstVisit$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$($win$jscomp$52$$,$registration$jscomp$2$$){if("performance"in $win$jscomp$52$$){var $ampScriptsUsed$$=$win$jscomp$52$$.performance.getEntriesByType("resource").filter(function($win$jscomp$52$$){var $registration$jscomp$2$$;if($registration$jscomp$2$$="script"===$win$jscomp$52$$.initiatorType){$registration$jscomp$2$$=$win$jscomp$52$$.name;var $ampScriptsUsed$$=$urls$$module$src$config$$.cdn;$registration$jscomp$2$$=
$ampScriptsUsed$$.length>$registration$jscomp$2$$.length?!1:0==$registration$jscomp$2$$.lastIndexOf($ampScriptsUsed$$,0)}return $registration$jscomp$2$$}).map(function($win$jscomp$52$$){return $win$jscomp$52$$.name}),$activeSW$$=$registration$jscomp$2$$.active;$activeSW$$.postMessage&&$activeSW$$.postMessage(JSON.stringify($dict$$module$src$utils$object$$({type:"AMP__FIRST-VISIT-CACHING",payload:$ampScriptsUsed$$})))}}
function $prefetchOutgoingLinks$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$($activeSW$jscomp$1_registration$jscomp$3$$,$win$jscomp$53$$){var $document$jscomp$2$$=$win$jscomp$53$$.document,$links$$=[].map.call($document$jscomp$2$$.querySelectorAll("a[data-rel=prefetch]"),function($activeSW$jscomp$1_registration$jscomp$3$$){return $activeSW$jscomp$1_registration$jscomp$3$$.href});$supportsPrefetch$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$($document$jscomp$2$$)?
$links$$.forEach(function($activeSW$jscomp$1_registration$jscomp$3$$){var $win$jscomp$53$$=$document$jscomp$2$$.createElement("link");$win$jscomp$53$$.setAttribute("rel","prefetch");$win$jscomp$53$$.setAttribute("href",$activeSW$jscomp$1_registration$jscomp$3$$);$document$jscomp$2$$.head.appendChild($win$jscomp$53$$)}):($activeSW$jscomp$1_registration$jscomp$3$$=$activeSW$jscomp$1_registration$jscomp$3$$.active,$activeSW$jscomp$1_registration$jscomp$3$$.postMessage&&$activeSW$jscomp$1_registration$jscomp$3$$.postMessage(JSON.stringify($dict$$module$src$utils$object$$({type:"AMP__LINK-PREFETCH",
payload:$links$$}))))}function $supportsPrefetch$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$($doc$jscomp$14$$){var $fakeLink$$=$doc$jscomp$14$$.createElement("link");return $fakeLink$$.relList&&$fakeLink$$.relList.supports?$fakeLink$$.relList.supports("prefetch"):!1}(function($AMP$jscomp$1$$){$AMP$jscomp$1$$.registerElement("amp-install-serviceworker",$AmpInstallServiceWorker$$module$extensions$amp_install_serviceworker$0_1$amp_install_serviceworker$$)})(self.AMP);
})});

//# sourceMappingURL=amp-install-serviceworker-0.1.js.map
