(self.AMP=self.AMP||[]).push({n:"amp-sticky-ad",v:"1904281823091",f:(function(AMP,_){
var $JSCompiler_prototypeAlias$$,$$jscomp$objectCreate$$="function"==typeof Object.create?Object.create:function($prototype$$){function $ctor$$(){}$ctor$$.prototype=$prototype$$;return new $ctor$$},$JSCompiler_temp$jscomp$6$$;
if("function"==typeof Object.setPrototypeOf)$JSCompiler_temp$jscomp$6$$=Object.setPrototypeOf;else{var $JSCompiler_inline_result$jscomp$7$$;a:{var $JSCompiler_x$jscomp$inline_10$$={a:!0},$JSCompiler_y$jscomp$inline_11$$={};try{$JSCompiler_y$jscomp$inline_11$$.__proto__=$JSCompiler_x$jscomp$inline_10$$;$JSCompiler_inline_result$jscomp$7$$=$JSCompiler_y$jscomp$inline_11$$.a;break a}catch($JSCompiler_e$jscomp$inline_12$$){}$JSCompiler_inline_result$jscomp$7$$=!1}$JSCompiler_temp$jscomp$6$$=$JSCompiler_inline_result$jscomp$7$$?
function($target$jscomp$83$$,$proto$jscomp$3$$){$target$jscomp$83$$.__proto__=$proto$jscomp$3$$;if($target$jscomp$83$$.__proto__!==$proto$jscomp$3$$)throw new TypeError($target$jscomp$83$$+" is not extensible");return $target$jscomp$83$$}:null}var $$jscomp$setPrototypeOf$$=$JSCompiler_temp$jscomp$6$$;self.log=self.log||{user:null,dev:null,userForEmbed:null};var $logs$$module$src$log$$=self.log;function $user$$module$src$log$$(){if(!$logs$$module$src$log$$.user)throw Error("failed to call initLogConstructor");return $logs$$module$src$log$$.user}function $userAssert$$module$src$log$$($shouldBeTrueish$jscomp$3$$){$user$$module$src$log$$().assert($shouldBeTrueish$jscomp$3$$,"amp-sticky-ad must have a single amp-ad child",void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function $map$$module$src$utils$object$$(){var $opt_initial$$,$obj$jscomp$25$$=Object.create(null);$opt_initial$$&&Object.assign($obj$jscomp$25$$,$opt_initial$$);return $obj$jscomp$25$$};function $startsWith$$module$src$string$$($string$jscomp$6$$,$prefix$jscomp$2$$){return $prefix$jscomp$2$$.length>$string$jscomp$6$$.length?!1:0==$string$jscomp$6$$.lastIndexOf($prefix$jscomp$2$$,0)};var $propertyNameCache$$module$src$style$$,$vendorPrefixes$$module$src$style$$="Webkit webkit Moz moz ms O o".split(" ");function $toggle$$module$src$style$$($element$jscomp$15$$,$opt_display$$){void 0===$opt_display$$&&($opt_display$$=$element$jscomp$15$$.hasAttribute("hidden"));$opt_display$$?$element$jscomp$15$$.removeAttribute("hidden"):$element$jscomp$15$$.setAttribute("hidden","")};function $Deferred$$module$src$utils$promise$$(){var $resolve$$,$reject$$;this.promise=new Promise(function($res$$,$rej$$){$resolve$$=$res$$;$reject$$=$rej$$});this.resolve=$resolve$$;this.reject=$reject$$};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function $whenUpgradedToCustomElement$$module$src$dom$$($element$jscomp$30$$){$startsWith$$module$src$string$$($element$jscomp$30$$.tagName,"AMP-");if($element$jscomp$30$$.createdCallback)return Promise.resolve($element$jscomp$30$$);if(!$element$jscomp$30$$.__AMP_UPG_PRM){var $deferred$$=new $Deferred$$module$src$utils$promise$$;$element$jscomp$30$$.__AMP_UPG_PRM=$deferred$$.promise;$element$jscomp$30$$.__AMP_UPG_RES=$deferred$$.resolve}return $element$jscomp$30$$.__AMP_UPG_PRM};function $AmpStickyAd$$module$extensions$amp_sticky_ad$1_0$amp_sticky_ad$$($$jscomp$super$this_element$jscomp$36$$){$$jscomp$super$this_element$jscomp$36$$=AMP.BaseElement.call(this,$$jscomp$super$this_element$jscomp$36$$)||this;$$jscomp$super$this_element$jscomp$36$$.$vsync_$=$$jscomp$super$this_element$jscomp$36$$.getVsync();$$jscomp$super$this_element$jscomp$36$$.$ad_$=null;$$jscomp$super$this_element$jscomp$36$$.$viewport_$=null;$$jscomp$super$this_element$jscomp$36$$.$visible_$=!1;$$jscomp$super$this_element$jscomp$36$$.$scrollUnlisten_$=
null;$$jscomp$super$this_element$jscomp$36$$.$collapsed_$=!1;$$jscomp$super$this_element$jscomp$36$$.$adReadyPromise_$=null;return $$jscomp$super$this_element$jscomp$36$$}var $JSCompiler_parentCtor$jscomp$inline_21$$=AMP.BaseElement;$AmpStickyAd$$module$extensions$amp_sticky_ad$1_0$amp_sticky_ad$$.prototype=$$jscomp$objectCreate$$($JSCompiler_parentCtor$jscomp$inline_21$$.prototype);$AmpStickyAd$$module$extensions$amp_sticky_ad$1_0$amp_sticky_ad$$.prototype.constructor=$AmpStickyAd$$module$extensions$amp_sticky_ad$1_0$amp_sticky_ad$$;
if($$jscomp$setPrototypeOf$$)$$jscomp$setPrototypeOf$$($AmpStickyAd$$module$extensions$amp_sticky_ad$1_0$amp_sticky_ad$$,$JSCompiler_parentCtor$jscomp$inline_21$$);else for(var $JSCompiler_p$jscomp$inline_22$$ in $JSCompiler_parentCtor$jscomp$inline_21$$)if("prototype"!=$JSCompiler_p$jscomp$inline_22$$)if(Object.defineProperties){var $JSCompiler_descriptor$jscomp$inline_23$$=Object.getOwnPropertyDescriptor($JSCompiler_parentCtor$jscomp$inline_21$$,$JSCompiler_p$jscomp$inline_22$$);$JSCompiler_descriptor$jscomp$inline_23$$&&
Object.defineProperty($AmpStickyAd$$module$extensions$amp_sticky_ad$1_0$amp_sticky_ad$$,$JSCompiler_p$jscomp$inline_22$$,$JSCompiler_descriptor$jscomp$inline_23$$)}else $AmpStickyAd$$module$extensions$amp_sticky_ad$1_0$amp_sticky_ad$$[$JSCompiler_p$jscomp$inline_22$$]=$JSCompiler_parentCtor$jscomp$inline_21$$[$JSCompiler_p$jscomp$inline_22$$];$AmpStickyAd$$module$extensions$amp_sticky_ad$1_0$amp_sticky_ad$$.$superClass_$=$JSCompiler_parentCtor$jscomp$inline_21$$.prototype;
$JSCompiler_prototypeAlias$$=$AmpStickyAd$$module$extensions$amp_sticky_ad$1_0$amp_sticky_ad$$.prototype;
$JSCompiler_prototypeAlias$$.buildCallback=function(){var $$jscomp$this$jscomp$1$$=this;this.$viewport_$=this.getViewport();this.element.classList.add("i-amphtml-sticky-ad-layout");var $children$jscomp$127$$=this.getRealChildren();$userAssert$$module$src$log$$(1==$children$jscomp$127$$.length&&"AMP-AD"==$children$jscomp$127$$[0].tagName);this.$ad_$=$children$jscomp$127$$[0];this.setAsOwner(this.$ad_$);this.$adReadyPromise_$=$whenUpgradedToCustomElement$$module$src$dom$$(this.$ad_$).then(function($$jscomp$this$jscomp$1$$){return $$jscomp$this$jscomp$1$$.whenBuilt()}).then(function(){return $$jscomp$this$jscomp$1$$.mutateElement(function(){$toggle$$module$src$style$$($$jscomp$this$jscomp$1$$.element,
!0)})});var $paddingBar$$=this.win.document.createElement("amp-sticky-ad-top-padding");$paddingBar$$.classList.add("amp-sticky-ad-top-padding");this.element.insertBefore($paddingBar$$,this.$ad_$);this.win.setTimeout(function(){$$jscomp$this$jscomp$1$$.$scrollUnlisten_$=$$jscomp$this$jscomp$1$$.$viewport_$.onScroll(function(){1<$$jscomp$this$jscomp$1$$.$viewport_$.getScrollTop()&&$JSCompiler_StaticMethods_display_$$($$jscomp$this$jscomp$1$$)})})};
$JSCompiler_prototypeAlias$$.layoutCallback=function(){if(this.$visible_$){$toggle$$module$src$style$$(this.element,!0);var $borderBottom$$=this.element.offsetHeight;this.$viewport_$.updatePaddingBottom($borderBottom$$);this.updateInViewport(this.$ad_$,!0);this.scheduleLayout(this.$ad_$)}return Promise.resolve()};$JSCompiler_prototypeAlias$$.isAlwaysFixed=function(){return!0};$JSCompiler_prototypeAlias$$.unlayoutCallback=function(){this.$viewport_$.updatePaddingBottom(0);return!0};
$JSCompiler_prototypeAlias$$.detachedCallback=function(){$JSCompiler_StaticMethods_removeOnScrollListener_$$(this)};$JSCompiler_prototypeAlias$$.collapsedCallback=function(){var $$jscomp$this$jscomp$2$$=this;this.$collapsed_$=!0;this.$visible_$=!1;$toggle$$module$src$style$$(this.element,!1);this.$vsync_$.mutate(function(){$$jscomp$this$jscomp$2$$.$viewport_$.updatePaddingBottom(0)})};
function $JSCompiler_StaticMethods_removeOnScrollListener_$$($JSCompiler_StaticMethods_removeOnScrollListener_$self$$){$JSCompiler_StaticMethods_removeOnScrollListener_$self$$.$scrollUnlisten_$&&($JSCompiler_StaticMethods_removeOnScrollListener_$self$$.$scrollUnlisten_$(),$JSCompiler_StaticMethods_removeOnScrollListener_$self$$.$scrollUnlisten_$=null)}
function $JSCompiler_StaticMethods_display_$$($JSCompiler_StaticMethods_display_$self$$){$JSCompiler_StaticMethods_removeOnScrollListener_$$($JSCompiler_StaticMethods_display_$self$$);$JSCompiler_StaticMethods_display_$self$$.$adReadyPromise_$.then(function(){$JSCompiler_StaticMethods_display_$self$$.mutateElement(function(){$JSCompiler_StaticMethods_display_$self$$.$collapsed_$||($JSCompiler_StaticMethods_display_$self$$.$visible_$=!0,$JSCompiler_StaticMethods_addCloseButton_$$($JSCompiler_StaticMethods_display_$self$$),
$JSCompiler_StaticMethods_display_$self$$.$viewport_$.addToFixedLayer($JSCompiler_StaticMethods_display_$self$$.element,!0).then(function(){return $JSCompiler_StaticMethods_scheduleLayoutForAd_$$($JSCompiler_StaticMethods_display_$self$$)}))})})}
function $JSCompiler_StaticMethods_scheduleLayoutForAd_$$($JSCompiler_StaticMethods_scheduleLayoutForAd_$self$$){$whenUpgradedToCustomElement$$module$src$dom$$($JSCompiler_StaticMethods_scheduleLayoutForAd_$self$$.$ad_$).then(function($ad$jscomp$1$$){$ad$jscomp$1$$.whenBuilt().then($JSCompiler_StaticMethods_scheduleLayoutForAd_$self$$.$layoutAd_$.bind($JSCompiler_StaticMethods_scheduleLayoutForAd_$self$$))})}
$JSCompiler_prototypeAlias$$.$layoutAd_$=function(){var $$jscomp$this$jscomp$5$$=this,$ad$jscomp$2$$=this.$ad_$;this.updateInViewport($ad$jscomp$2$$,!0);this.scheduleLayout($ad$jscomp$2$$);var $signals$$=$ad$jscomp$2$$.signals();return Promise.race([$signals$$.whenSignal("render-start"),$signals$$.whenSignal("load-end")]).then(function(){var $ad$jscomp$2$$;return $$jscomp$this$jscomp$5$$.measureElement(function(){$ad$jscomp$2$$=($$jscomp$this$jscomp$5$$.win.getComputedStyle($$jscomp$this$jscomp$5$$.element)||
$map$$module$src$utils$object$$()).backgroundColor}).then(function(){return $$jscomp$this$jscomp$5$$.$vsync_$.mutatePromise(function(){$$jscomp$this$jscomp$5$$.element.setAttribute("visible","");$$jscomp$this$jscomp$5$$.$viewport_$.updatePaddingBottom($$jscomp$this$jscomp$5$$.element.offsetHeight);var $signals$$=$ad$jscomp$2$$,$JSCompiler_newBackgroundColor$jscomp$inline_30$$=$signals$$.replace(/\(([^,]+),([^,]+),([^,)]+),[^)]+\)/g,"($1,$2,$3, 1)");if($signals$$!=$JSCompiler_newBackgroundColor$jscomp$inline_30$$){$user$$module$src$log$$().warn("AMP-STICKY-AD",
"Do not allow container to be semitransparent");$signals$$=$$jscomp$this$jscomp$5$$.element;var $JSCompiler_inline_result$jscomp$40_JSCompiler_propertyName$jscomp$inline_37_JSCompiler_style$jscomp$inline_42$$=$signals$$.style;if($startsWith$$module$src$string$$("background-color","--"))$JSCompiler_inline_result$jscomp$40_JSCompiler_propertyName$jscomp$inline_37_JSCompiler_style$jscomp$inline_42$$="background-color";else{$propertyNameCache$$module$src$style$$||($propertyNameCache$$module$src$style$$=
$map$$module$src$utils$object$$());var $JSCompiler_propertyName$jscomp$inline_44$$=$propertyNameCache$$module$src$style$$["background-color"];if(!$JSCompiler_propertyName$jscomp$inline_44$$){$JSCompiler_propertyName$jscomp$inline_44$$="background-color";if(void 0===$JSCompiler_inline_result$jscomp$40_JSCompiler_propertyName$jscomp$inline_37_JSCompiler_style$jscomp$inline_42$$["background-color"]){var $JSCompiler_i$jscomp$inline_54_JSCompiler_inline_result$jscomp$49_JSCompiler_prefixedPropertyName$jscomp$inline_46$$;
b:{for($JSCompiler_i$jscomp$inline_54_JSCompiler_inline_result$jscomp$49_JSCompiler_prefixedPropertyName$jscomp$inline_46$$=0;$JSCompiler_i$jscomp$inline_54_JSCompiler_inline_result$jscomp$49_JSCompiler_prefixedPropertyName$jscomp$inline_46$$<$vendorPrefixes$$module$src$style$$.length;$JSCompiler_i$jscomp$inline_54_JSCompiler_inline_result$jscomp$49_JSCompiler_prefixedPropertyName$jscomp$inline_46$$++){var $JSCompiler_propertyName$jscomp$inline_55$$=$vendorPrefixes$$module$src$style$$[$JSCompiler_i$jscomp$inline_54_JSCompiler_inline_result$jscomp$49_JSCompiler_prefixedPropertyName$jscomp$inline_46$$]+
"Background-color";if(void 0!==$JSCompiler_inline_result$jscomp$40_JSCompiler_propertyName$jscomp$inline_37_JSCompiler_style$jscomp$inline_42$$[$JSCompiler_propertyName$jscomp$inline_55$$]){$JSCompiler_i$jscomp$inline_54_JSCompiler_inline_result$jscomp$49_JSCompiler_prefixedPropertyName$jscomp$inline_46$$=$JSCompiler_propertyName$jscomp$inline_55$$;break b}}$JSCompiler_i$jscomp$inline_54_JSCompiler_inline_result$jscomp$49_JSCompiler_prefixedPropertyName$jscomp$inline_46$$=""}void 0!==$JSCompiler_inline_result$jscomp$40_JSCompiler_propertyName$jscomp$inline_37_JSCompiler_style$jscomp$inline_42$$[$JSCompiler_i$jscomp$inline_54_JSCompiler_inline_result$jscomp$49_JSCompiler_prefixedPropertyName$jscomp$inline_46$$]&&
($JSCompiler_propertyName$jscomp$inline_44$$=$JSCompiler_i$jscomp$inline_54_JSCompiler_inline_result$jscomp$49_JSCompiler_prefixedPropertyName$jscomp$inline_46$$)}$propertyNameCache$$module$src$style$$["background-color"]=$JSCompiler_propertyName$jscomp$inline_44$$}$JSCompiler_inline_result$jscomp$40_JSCompiler_propertyName$jscomp$inline_37_JSCompiler_style$jscomp$inline_42$$=$JSCompiler_propertyName$jscomp$inline_44$$}$JSCompiler_inline_result$jscomp$40_JSCompiler_propertyName$jscomp$inline_37_JSCompiler_style$jscomp$inline_42$$&&
($signals$$.style[$JSCompiler_inline_result$jscomp$40_JSCompiler_propertyName$jscomp$inline_37_JSCompiler_style$jscomp$inline_42$$]=$JSCompiler_newBackgroundColor$jscomp$inline_30$$)}})})})};
function $JSCompiler_StaticMethods_addCloseButton_$$($JSCompiler_StaticMethods_addCloseButton_$self$$){var $closeButton$$=$JSCompiler_StaticMethods_addCloseButton_$self$$.win.document.createElement("button");$closeButton$$.classList.add("amp-sticky-ad-close-button");$closeButton$$.setAttribute("aria-label",$JSCompiler_StaticMethods_addCloseButton_$self$$.element.getAttribute("data-close-button-aria-label")||"Close this ad");var $boundOnCloseButtonClick$$=$JSCompiler_StaticMethods_addCloseButton_$self$$.$onCloseButtonClick_$.bind($JSCompiler_StaticMethods_addCloseButton_$self$$);
$closeButton$$.addEventListener("click",$boundOnCloseButtonClick$$);$JSCompiler_StaticMethods_addCloseButton_$self$$.element.appendChild($closeButton$$)}
$JSCompiler_prototypeAlias$$.$onCloseButtonClick_$=function(){var $$jscomp$this$jscomp$6$$=this;this.$vsync_$.mutate(function(){$$jscomp$this$jscomp$6$$.$visible_$=!1;$$jscomp$this$jscomp$6$$.scheduleUnlayout($$jscomp$this$jscomp$6$$.$ad_$);$$jscomp$this$jscomp$6$$.$viewport_$.removeFromFixedLayer($$jscomp$this$jscomp$6$$.element);var $JSCompiler_element$jscomp$inline_32$$=$$jscomp$this$jscomp$6$$.element;$JSCompiler_element$jscomp$inline_32$$.parentElement&&$JSCompiler_element$jscomp$inline_32$$.parentElement.removeChild($JSCompiler_element$jscomp$inline_32$$);
$$jscomp$this$jscomp$6$$.$viewport_$.updatePaddingBottom(0)})};(function($AMP$jscomp$1$$){$AMP$jscomp$1$$.registerElement("amp-sticky-ad",$AmpStickyAd$$module$extensions$amp_sticky_ad$1_0$amp_sticky_ad$$,"amp-sticky-ad{position:fixed!important;text-align:center;bottom:0!important;left:0;width:100%!important;z-index:11;max-height:100px!important;box-sizing:border-box;opacity:1!important;background-image:none!important;background-color:#fff;box-shadow:0 0 5px 0 rgba(0,0,0,0.2)!important;margin-bottom:0!important}amp-sticky-ad-top-padding{display:block;width:100%!important;background:#fff;height:4px;max-height:5px!important;z-index:12}.i-amphtml-sticky-ad-layout{display:-webkit-box;display:-ms-flexbox;display:flex;visibility:hidden!important;-webkit-box-orient:vertical;-webkit-box-direction:normal;-ms-flex-direction:column;flex-direction:column;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:center;-ms-flex-pack:center;justify-content:center;overflow:visible!important;-webkit-transform:translateZ(0)!important;transform:translateZ(0)!important}amp-sticky-ad[visible]{visibility:visible!important}.i-amphtml-sticky-ad-layout>amp-ad{display:block}.amp-sticky-ad-close-button{position:absolute;visibility:hidden;width:28px;height:28px;top:-28px;right:0;background-image:url(\"data:image/svg+xml;charset=utf-8,%3Csvg width='13' height='13' viewBox='341 8 13 13' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath fill='%234F4F4F' d='M354 9.31L352.69 8l-5.19 5.19L342.31 8 341 9.31l5.19 5.19-5.19 5.19 1.31 1.31 5.19-5.19 5.19 5.19 1.31-1.31-5.19-5.19z' fill-rule='evenodd'/%3E%3C/svg%3E\");background-size:13px 13px;background-position:9px;background-color:#fff;background-repeat:no-repeat;box-shadow:0 -1px 1px 0 rgba(0,0,0,0.2);border:none;border-radius:12px 0 0 0}amp-sticky-ad[visible]>.amp-sticky-ad-close-button{visibility:visible}.amp-sticky-ad-close-button:before{position:absolute;content:\"\";top:-20px;right:0;left:-20px;bottom:0}[dir=rtl] .amp-sticky-ad-close-button{right:auto;left:0;border-top-left-radius:0;border-top-right-radius:12px;background-position:6px}[dir=rtl] .amp-sticky-ad-close-button:before{right:-20px;left:0}\n/*# sourceURL=/extensions/amp-sticky-ad/1.0/amp-sticky-ad.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-sticky-ad-1.0.js.map
