(self.AMP=self.AMP||[]).push({n:"amp-mraid",v:"1904281823091",f:(function(AMP,_){
function $Deferred$$module$src$utils$promise$$(){var $resolve$$,$reject$$;this.promise=new Promise(function($res$$,$rej$$){$resolve$$=$res$$;$reject$$=$rej$$});this.resolve=$resolve$$;this.reject=$reject$$};function $tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($component$jscomp$4$$,$fallback$$){$fallback$$=void 0===$fallback$$?"":$fallback$$;try{return decodeURIComponent($component$jscomp$4$$)}catch($e$jscomp$7$$){return $fallback$$}};var $regex$$module$src$url_parse_query_string$$=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;
function $parseQueryString_$$module$src$url_parse_query_string$$($queryString$$){var $params$jscomp$1$$=Object.create(null);if(!$queryString$$)return $params$jscomp$1$$;for(var $match$$;$match$$=$regex$$module$src$url_parse_query_string$$.exec($queryString$$);){var $name$jscomp$70$$=$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($match$$[1],$match$$[1]),$value$jscomp$87$$=$match$$[2]?$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($match$$[2],$match$$[2]):"";
$params$jscomp$1$$[$name$jscomp$70$$]=$value$jscomp$87$$}return $params$jscomp$1$$};var $rtvVersion$$module$src$mode$$="";
function $getMode$$module$src$mode$$(){var $opt_win$$,$win$$=$opt_win$$||self;if($win$$.AMP_MODE)var $JSCompiler_temp$jscomp$8_JSCompiler_win$jscomp$inline_11$$=$win$$.AMP_MODE;else{$JSCompiler_temp$jscomp$8_JSCompiler_win$jscomp$inline_11$$=$win$$;var $JSCompiler_AMP_CONFIG$jscomp$inline_12_JSCompiler_singlePassType$jscomp$inline_19$$=self.AMP_CONFIG||{},$JSCompiler_runningTests$jscomp$inline_16$$=!!$JSCompiler_AMP_CONFIG$jscomp$inline_12_JSCompiler_singlePassType$jscomp$inline_19$$.test||!(!$JSCompiler_temp$jscomp$8_JSCompiler_win$jscomp$inline_11$$.AMP_TEST&&
!$JSCompiler_temp$jscomp$8_JSCompiler_win$jscomp$inline_11$$.__karma__),$JSCompiler_isLocalDev$jscomp$inline_17$$=!!$JSCompiler_AMP_CONFIG$jscomp$inline_12_JSCompiler_singlePassType$jscomp$inline_19$$.localDev||$JSCompiler_runningTests$jscomp$inline_16$$,$JSCompiler_hashQuery$jscomp$inline_18$$=$parseQueryString_$$module$src$url_parse_query_string$$($JSCompiler_temp$jscomp$8_JSCompiler_win$jscomp$inline_11$$.location.originalHash||$JSCompiler_temp$jscomp$8_JSCompiler_win$jscomp$inline_11$$.location.hash);
$JSCompiler_AMP_CONFIG$jscomp$inline_12_JSCompiler_singlePassType$jscomp$inline_19$$=$JSCompiler_AMP_CONFIG$jscomp$inline_12_JSCompiler_singlePassType$jscomp$inline_19$$.spt;var $JSCompiler_searchQuery$jscomp$inline_20$$=$parseQueryString_$$module$src$url_parse_query_string$$($JSCompiler_temp$jscomp$8_JSCompiler_win$jscomp$inline_11$$.location.search);$rtvVersion$$module$src$mode$$||($rtvVersion$$module$src$mode$$=$JSCompiler_isLocalDev$jscomp$inline_17$$?"1904281823091":$JSCompiler_temp$jscomp$8_JSCompiler_win$jscomp$inline_11$$.AMP_CONFIG&&
$JSCompiler_temp$jscomp$8_JSCompiler_win$jscomp$inline_11$$.AMP_CONFIG.v?$JSCompiler_temp$jscomp$8_JSCompiler_win$jscomp$inline_11$$.AMP_CONFIG.v:"011904281823091");$JSCompiler_temp$jscomp$8_JSCompiler_win$jscomp$inline_11$$=$win$$.AMP_MODE={localDev:$JSCompiler_isLocalDev$jscomp$inline_17$$,development:!("1"!=$JSCompiler_hashQuery$jscomp$inline_18$$.development&&!$JSCompiler_temp$jscomp$8_JSCompiler_win$jscomp$inline_11$$.AMP_DEV_MODE),examiner:"2"==$JSCompiler_hashQuery$jscomp$inline_18$$.development,
filter:$JSCompiler_hashQuery$jscomp$inline_18$$.filter,geoOverride:$JSCompiler_hashQuery$jscomp$inline_18$$["amp-geo"],minified:!0,lite:void 0!=$JSCompiler_searchQuery$jscomp$inline_20$$.amp_lite,test:$JSCompiler_runningTests$jscomp$inline_16$$,log:$JSCompiler_hashQuery$jscomp$inline_18$$.log,version:"1904281823091",rtvVersion:$rtvVersion$$module$src$mode$$,singlePassType:$JSCompiler_AMP_CONFIG$jscomp$inline_12_JSCompiler_singlePassType$jscomp$inline_19$$}}return $JSCompiler_temp$jscomp$8_JSCompiler_win$jscomp$inline_11$$}
;self.log=self.log||{user:null,dev:null,userForEmbed:null};var $logs$$module$src$log$$=self.log;function $dev$$module$src$log$$(){if($logs$$module$src$log$$.dev)return $logs$$module$src$log$$.dev;throw Error("failed to call initLogConstructor");};function $registerServiceBuilderForDoc$$module$src$service$$($nodeOrDoc$$,$id$jscomp$9$$,$constructor$jscomp$2$$){var $ampdoc$$=$getAmpdoc$$module$src$service$$($nodeOrDoc$$),$holder$$=$getAmpdocServiceHolder$$module$src$service$$($ampdoc$$),$JSCompiler_holder$jscomp$inline_22$$=$holder$$,$JSCompiler_services$jscomp$inline_26$$=$getServices$$module$src$service$$($JSCompiler_holder$jscomp$inline_22$$),$JSCompiler_s$jscomp$inline_27$$=$JSCompiler_services$jscomp$inline_26$$[$id$jscomp$9$$];$JSCompiler_s$jscomp$inline_27$$||
($JSCompiler_s$jscomp$inline_27$$=$JSCompiler_services$jscomp$inline_26$$[$id$jscomp$9$$]={obj:null,promise:null,resolve:null,reject:null,context:null,ctor:null});$JSCompiler_s$jscomp$inline_27$$.ctor||$JSCompiler_s$jscomp$inline_27$$.obj||($JSCompiler_s$jscomp$inline_27$$.ctor=$constructor$jscomp$2$$,$JSCompiler_s$jscomp$inline_27$$.context=$ampdoc$$,$JSCompiler_s$jscomp$inline_27$$.resolve&&$getServiceInternal$$module$src$service$$($JSCompiler_holder$jscomp$inline_22$$,$id$jscomp$9$$));$getServiceInternal$$module$src$service$$($holder$$,
$id$jscomp$9$$)}
function $rejectServicePromiseForDoc$$module$src$service$$($JSCompiler_services$jscomp$inline_32_ampdoc$jscomp$1_holder$jscomp$1_nodeOrDoc$jscomp$1$$,$id$jscomp$10$$,$error$jscomp$12$$){$JSCompiler_services$jscomp$inline_32_ampdoc$jscomp$1_holder$jscomp$1_nodeOrDoc$jscomp$1$$=$getAmpdoc$$module$src$service$$($JSCompiler_services$jscomp$inline_32_ampdoc$jscomp$1_holder$jscomp$1_nodeOrDoc$jscomp$1$$);$JSCompiler_services$jscomp$inline_32_ampdoc$jscomp$1_holder$jscomp$1_nodeOrDoc$jscomp$1$$=$getAmpdocServiceHolder$$module$src$service$$($JSCompiler_services$jscomp$inline_32_ampdoc$jscomp$1_holder$jscomp$1_nodeOrDoc$jscomp$1$$);
$JSCompiler_services$jscomp$inline_32_ampdoc$jscomp$1_holder$jscomp$1_nodeOrDoc$jscomp$1$$=$getServices$$module$src$service$$($JSCompiler_services$jscomp$inline_32_ampdoc$jscomp$1_holder$jscomp$1_nodeOrDoc$jscomp$1$$);var $JSCompiler_s$jscomp$inline_33$$=$JSCompiler_services$jscomp$inline_32_ampdoc$jscomp$1_holder$jscomp$1_nodeOrDoc$jscomp$1$$[$id$jscomp$10$$];$JSCompiler_s$jscomp$inline_33$$?$JSCompiler_s$jscomp$inline_33$$.reject&&$JSCompiler_s$jscomp$inline_33$$.reject($error$jscomp$12$$):($JSCompiler_services$jscomp$inline_32_ampdoc$jscomp$1_holder$jscomp$1_nodeOrDoc$jscomp$1$$[$id$jscomp$10$$]=
$emptyServiceHolderWithPromise$$module$src$service$$(),$JSCompiler_services$jscomp$inline_32_ampdoc$jscomp$1_holder$jscomp$1_nodeOrDoc$jscomp$1$$[$id$jscomp$10$$].reject($error$jscomp$12$$))}
function $getAmpdoc$$module$src$service$$($JSCompiler_temp$jscomp$44_nodeOrDoc$jscomp$2$$){if($JSCompiler_temp$jscomp$44_nodeOrDoc$jscomp$2$$.nodeType){var $JSCompiler_win$jscomp$inline_46$$=($JSCompiler_temp$jscomp$44_nodeOrDoc$jscomp$2$$.ownerDocument||$JSCompiler_temp$jscomp$44_nodeOrDoc$jscomp$2$$).defaultView;$JSCompiler_win$jscomp$inline_46$$=$JSCompiler_win$jscomp$inline_46$$.__AMP_TOP||$JSCompiler_win$jscomp$inline_46$$;$JSCompiler_temp$jscomp$44_nodeOrDoc$jscomp$2$$=$getServiceInternal$$module$src$service$$($JSCompiler_win$jscomp$inline_46$$,
"ampdoc").getAmpDoc($JSCompiler_temp$jscomp$44_nodeOrDoc$jscomp$2$$)}return $JSCompiler_temp$jscomp$44_nodeOrDoc$jscomp$2$$}function $getAmpdocServiceHolder$$module$src$service$$($ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$){$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$=$getAmpdoc$$module$src$service$$($ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$);return $ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$.isSingleDoc()?$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$.win:$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$}
function $getServiceInternal$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$,$id$jscomp$19$$){var $services$$=$getServices$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$);$holder$jscomp$4_s$jscomp$8$$=$services$$[$id$jscomp$19$$];$holder$jscomp$4_s$jscomp$8$$.obj||($holder$jscomp$4_s$jscomp$8$$.obj=new $holder$jscomp$4_s$jscomp$8$$.ctor($holder$jscomp$4_s$jscomp$8$$.context),$holder$jscomp$4_s$jscomp$8$$.ctor=null,$holder$jscomp$4_s$jscomp$8$$.context=null,$holder$jscomp$4_s$jscomp$8$$.resolve&&
$holder$jscomp$4_s$jscomp$8$$.resolve($holder$jscomp$4_s$jscomp$8$$.obj));return $holder$jscomp$4_s$jscomp$8$$.obj}function $getServices$$module$src$service$$($holder$jscomp$9$$){var $services$jscomp$5$$=$holder$jscomp$9$$.services;$services$jscomp$5$$||($services$jscomp$5$$=$holder$jscomp$9$$.services={});return $services$jscomp$5$$}
function $emptyServiceHolderWithPromise$$module$src$service$$(){var $deferred$$=new $Deferred$$module$src$utils$promise$$,$$jscomp$destructuring$var2_reject$jscomp$3$$=$deferred$$,$promise$jscomp$1$$=$$jscomp$destructuring$var2_reject$jscomp$3$$.promise,$resolve$jscomp$4$$=$$jscomp$destructuring$var2_reject$jscomp$3$$.resolve;$$jscomp$destructuring$var2_reject$jscomp$3$$=$$jscomp$destructuring$var2_reject$jscomp$3$$.reject;$promise$jscomp$1$$.catch(function(){});return{obj:null,promise:$promise$jscomp$1$$,
resolve:$resolve$jscomp$4$$,reject:$$jscomp$destructuring$var2_reject$jscomp$3$$,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function $HostServices$$module$src$inabox$host_services$installVisibilityServiceForDoc$$($elementOrAmpDoc$jscomp$20$$,$impl$$){$registerServiceBuilderForDoc$$module$src$service$$($elementOrAmpDoc$jscomp$20$$,"host-visibility",$impl$$)}function $HostServices$$module$src$inabox$host_services$rejectVisibilityServiceForDoc$$($elementOrAmpDoc$jscomp$21$$,$error$jscomp$14$$){$rejectServicePromiseForDoc$$module$src$service$$($elementOrAmpDoc$jscomp$21$$,"host-visibility",$error$jscomp$14$$)}
function $HostServices$$module$src$inabox$host_services$installFullscreenServiceForDoc$$($elementOrAmpDoc$jscomp$23$$,$impl$jscomp$1$$){$registerServiceBuilderForDoc$$module$src$service$$($elementOrAmpDoc$jscomp$23$$,"host-fullscreen",$impl$jscomp$1$$)}
function $HostServices$$module$src$inabox$host_services$rejectFullscreenServiceForDoc$$($elementOrAmpDoc$jscomp$24$$,$error$jscomp$15$$){$rejectServicePromiseForDoc$$module$src$service$$($elementOrAmpDoc$jscomp$24$$,"host-fullscreen",$error$jscomp$15$$)}function $HostServices$$module$src$inabox$host_services$installExitServiceForDoc$$($elementOrAmpDoc$jscomp$26$$,$impl$jscomp$2$$){$registerServiceBuilderForDoc$$module$src$service$$($elementOrAmpDoc$jscomp$26$$,"host-exit",$impl$jscomp$2$$)}
function $HostServices$$module$src$inabox$host_services$rejectExitServiceForDoc$$($elementOrAmpDoc$jscomp$27$$){$rejectServicePromiseForDoc$$module$src$service$$($elementOrAmpDoc$jscomp$27$$,"host-exit",{fallback:!0})};function $MraidService$$module$extensions$amp_mraid$0_1$mraid_service$$($mraid$$){this.$mraid_$=$mraid$$;this.$expanded_$=!1}
$MraidService$$module$extensions$amp_mraid$0_1$mraid_service$$.prototype.onVisibilityChange=function($callback$jscomp$66$$){this.$mraid_$.addEventListener("exposureChange",function($exposedPercentage$$,$visibleRectangle$$){var $JSCompiler_left$jscomp$inline_39$$=$visibleRectangle$$&&$visibleRectangle$$.x?$visibleRectangle$$.x:0,$JSCompiler_top$jscomp$inline_40$$=$visibleRectangle$$&&$visibleRectangle$$.y?$visibleRectangle$$.y:0,$JSCompiler_width$jscomp$inline_41$$=$visibleRectangle$$&&$visibleRectangle$$.width?
$visibleRectangle$$.width:0,$JSCompiler_height$jscomp$inline_42$$=$visibleRectangle$$&&$visibleRectangle$$.height?$visibleRectangle$$.height:0;$callback$jscomp$66$$({visibleRect:{left:$JSCompiler_left$jscomp$inline_39$$,top:$JSCompiler_top$jscomp$inline_40$$,width:$JSCompiler_width$jscomp$inline_41$$,height:$JSCompiler_height$jscomp$inline_42$$,bottom:$JSCompiler_top$jscomp$inline_40$$+$JSCompiler_height$jscomp$inline_42$$,right:$JSCompiler_left$jscomp$inline_39$$+$JSCompiler_width$jscomp$inline_41$$,
x:$JSCompiler_left$jscomp$inline_39$$,y:$JSCompiler_top$jscomp$inline_40$$},visibleRatio:$exposedPercentage$$/100})})};$MraidService$$module$extensions$amp_mraid$0_1$mraid_service$$.prototype.enterFullscreenOverlay=function(){if(this.$expanded_$)return Promise.resolve(!1);this.$mraid_$.expand();this.$expanded_$=!0;return Promise.resolve(!0)};
$MraidService$$module$extensions$amp_mraid$0_1$mraid_service$$.prototype.exitFullscreenOverlay=function(){if(!this.$expanded_$)return Promise.resolve(!1);this.$mraid_$.close();this.$expanded_$=!1;return Promise.resolve(!0)};$MraidService$$module$extensions$amp_mraid$0_1$mraid_service$$.prototype.openUrl=function($url$jscomp$22$$){this.$mraid_$.open($url$jscomp$22$$);return Promise.resolve(!0)};var $env$$module$src$config$$=self.AMP_CONFIG||{},$urls$$module$src$config$$={thirdParty:$env$$module$src$config$$.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:$env$$module$src$config$$.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof $env$$module$src$config$$.thirdPartyFrameRegex?new RegExp($env$$module$src$config$$.thirdPartyFrameRegex):$env$$module$src$config$$.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:$env$$module$src$config$$.cdnUrl||
"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof $env$$module$src$config$$.cdnProxyRegex?new RegExp($env$$module$src$config$$.cdnProxyRegex):$env$$module$src$config$$.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:$env$$module$src$config$$.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:$env$$module$src$config$$.localDev||!1};function $MraidInitializer$$module$extensions$amp_mraid$0_1$amp_mraid$$($ampdoc$jscomp$10$$){var $$jscomp$this$jscomp$1$$=this;this.$ampdoc_$=$ampdoc$jscomp$10$$;this.$registeredWithHostServices_$=!1;this.$mraid_$=null;this.$fallback_$=!0;var $ampMraidScripts$$=this.$ampdoc_$.getHeadNode().querySelectorAll('script[host-service="amp-mraid"]');if(1<$ampMraidScripts$$.length)$dev$$module$src$log$$().error("amp-mraid","Multiple amp-mraid scripts.");else if(1>$ampMraidScripts$$.length)$dev$$module$src$log$$().error("amp-mraid",
"Missing amp-mraid scripts.");else if(null!=$ampMraidScripts$$[0].getAttribute("no-fallback")&&(this.$fallback_$=!1),"inabox"!==$getMode$$module$src$mode$$().runtime)$JSCompiler_StaticMethods_handleMismatch_$$(this);else{var $mraidJs$$=document.createElement("script");$mraidJs$$.setAttribute("type","text/javascript");$mraidJs$$.setAttribute("src",$urls$$module$src$config$$.cdn+"/mraid.js");$mraidJs$$.addEventListener("load",function(){$JSCompiler_StaticMethods_mraidLoadSuccess_$$($$jscomp$this$jscomp$1$$)});
$mraidJs$$.addEventListener("error",function(){$$jscomp$this$jscomp$1$$.$registeredWithHostServices_$||$JSCompiler_StaticMethods_handleMismatch_$$($$jscomp$this$jscomp$1$$)});document.getElementsByTagName("head").item(0).appendChild($mraidJs$$)}}
function $JSCompiler_StaticMethods_mraidReady_$$($JSCompiler_StaticMethods_mraidReady_$self$$){var $mraidService$$=new $MraidService$$module$extensions$amp_mraid$0_1$mraid_service$$($JSCompiler_StaticMethods_mraidReady_$self$$.$mraid_$);$JSCompiler_StaticMethods_mraidReady_$self$$.$mraid_$.addEventListener?$HostServices$$module$src$inabox$host_services$installVisibilityServiceForDoc$$($JSCompiler_StaticMethods_mraidReady_$self$$.$ampdoc_$,function(){return $mraidService$$}):$HostServices$$module$src$inabox$host_services$rejectVisibilityServiceForDoc$$($JSCompiler_StaticMethods_mraidReady_$self$$.$ampdoc_$,
{fallback:!1});$JSCompiler_StaticMethods_mraidReady_$self$$.$mraid_$.expand&&$JSCompiler_StaticMethods_mraidReady_$self$$.$mraid_$.close?$HostServices$$module$src$inabox$host_services$installFullscreenServiceForDoc$$($JSCompiler_StaticMethods_mraidReady_$self$$.$ampdoc_$,function(){return $mraidService$$}):$HostServices$$module$src$inabox$host_services$rejectFullscreenServiceForDoc$$($JSCompiler_StaticMethods_mraidReady_$self$$.$ampdoc_$,{fallback:!1});$JSCompiler_StaticMethods_mraidReady_$self$$.$mraid_$.open?
$HostServices$$module$src$inabox$host_services$installExitServiceForDoc$$($JSCompiler_StaticMethods_mraidReady_$self$$.$ampdoc_$,function(){return $mraidService$$}):$HostServices$$module$src$inabox$host_services$rejectExitServiceForDoc$$($JSCompiler_StaticMethods_mraidReady_$self$$.$ampdoc_$);$JSCompiler_StaticMethods_mraidReady_$self$$.$registeredWithHostServices_$=!0}
function $JSCompiler_StaticMethods_mraidLoadSuccess_$$($JSCompiler_StaticMethods_mraidLoadSuccess_$self$$){var $mraid$jscomp$1$$=window.mraid;$mraid$jscomp$1$$&&$mraid$jscomp$1$$.getState?($JSCompiler_StaticMethods_mraidLoadSuccess_$self$$.$mraid_$=$mraid$jscomp$1$$,"loading"===$mraid$jscomp$1$$.getState()?$mraid$jscomp$1$$.addEventListener("ready",function(){$JSCompiler_StaticMethods_mraidReady_$$($JSCompiler_StaticMethods_mraidLoadSuccess_$self$$)}):$JSCompiler_StaticMethods_mraidReady_$$($JSCompiler_StaticMethods_mraidLoadSuccess_$self$$)):
$JSCompiler_StaticMethods_handleMismatch_$$($JSCompiler_StaticMethods_mraidLoadSuccess_$self$$)}
function $JSCompiler_StaticMethods_handleMismatch_$$($JSCompiler_StaticMethods_handleMismatch_$self$$){$HostServices$$module$src$inabox$host_services$rejectVisibilityServiceForDoc$$($JSCompiler_StaticMethods_handleMismatch_$self$$.$ampdoc_$,{fallback:$JSCompiler_StaticMethods_handleMismatch_$self$$.$fallback_$});$HostServices$$module$src$inabox$host_services$rejectExitServiceForDoc$$($JSCompiler_StaticMethods_handleMismatch_$self$$.$ampdoc_$);$HostServices$$module$src$inabox$host_services$rejectFullscreenServiceForDoc$$($JSCompiler_StaticMethods_handleMismatch_$self$$.$ampdoc_$,
{fallback:$JSCompiler_StaticMethods_handleMismatch_$self$$.$fallback_$})}(function($AMP$jscomp$1$$){$AMP$jscomp$1$$.registerServiceForDoc("amp-mraid",$MraidInitializer$$module$extensions$amp_mraid$0_1$amp_mraid$$)})(self.AMP);
})});

//# sourceMappingURL=amp-mraid-0.1.js.map
