(self.AMP=self.AMP||[]).push({n:"amp-action-macro",v:"1904281823091",f:(function(AMP,_){
var $$jscomp$objectCreate$$="function"==typeof Object.create?Object.create:function($prototype$$){function $ctor$$(){}$ctor$$.prototype=$prototype$$;return new $ctor$$},$JSCompiler_temp$jscomp$15$$;
if("function"==typeof Object.setPrototypeOf)$JSCompiler_temp$jscomp$15$$=Object.setPrototypeOf;else{var $JSCompiler_inline_result$jscomp$16$$;a:{var $JSCompiler_x$jscomp$inline_22$$={a:!0},$JSCompiler_y$jscomp$inline_23$$={};try{$JSCompiler_y$jscomp$inline_23$$.__proto__=$JSCompiler_x$jscomp$inline_22$$;$JSCompiler_inline_result$jscomp$16$$=$JSCompiler_y$jscomp$inline_23$$.a;break a}catch($JSCompiler_e$jscomp$inline_24$$){}$JSCompiler_inline_result$jscomp$16$$=!1}$JSCompiler_temp$jscomp$15$$=$JSCompiler_inline_result$jscomp$16$$?
function($target$jscomp$83$$,$proto$jscomp$3$$){$target$jscomp$83$$.__proto__=$proto$jscomp$3$$;if($target$jscomp$83$$.__proto__!==$proto$jscomp$3$$)throw new TypeError($target$jscomp$83$$+" is not extensible");return $target$jscomp$83$$}:null}var $$jscomp$setPrototypeOf$$=$JSCompiler_temp$jscomp$15$$;
function $tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($component$jscomp$4$$,$fallback$$){$fallback$$=void 0===$fallback$$?"":$fallback$$;try{return decodeURIComponent($component$jscomp$4$$)}catch($e$jscomp$8$$){return $fallback$$}};var $regex$$module$src$url_parse_query_string$$=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;self.log=self.log||{user:null,dev:null,userForEmbed:null};var $logs$$module$src$log$$=self.log;function $userAssert$$module$src$log$$($shouldBeTrueish$jscomp$3$$,$opt_message$jscomp$14$$,$opt_1$jscomp$1$$,$opt_2$jscomp$1$$){if(!$logs$$module$src$log$$.user)throw Error("failed to call initLogConstructor");$logs$$module$src$log$$.user.assert($shouldBeTrueish$jscomp$3$$,$opt_message$jscomp$14$$,$opt_1$jscomp$1$$,$opt_2$jscomp$1$$,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function $getExistingServiceForDocInEmbedScope$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_71_JSCompiler_ampdoc$jscomp$inline_73_JSCompiler_inline_result$jscomp$inline_72_element$jscomp$21$$){var $opt_fallbackToTopWin$$,$win$jscomp$7$$=$JSCompiler_ampdoc$jscomp$inline_71_JSCompiler_ampdoc$jscomp$inline_73_JSCompiler_inline_result$jscomp$inline_72_element$jscomp$21$$.ownerDocument.defaultView,$isEmbed$$=$win$jscomp$7$$!=($win$jscomp$7$$.__AMP_TOP||$win$jscomp$7$$);if($isEmbed$$){if($isServiceRegistered$$module$src$service$$($win$jscomp$7$$,
"action")){var $embedService$$=$getServiceInternal$$module$src$service$$($win$jscomp$7$$,"action");if($embedService$$)return $embedService$$}if(!$opt_fallbackToTopWin$$)return null}$JSCompiler_ampdoc$jscomp$inline_71_JSCompiler_ampdoc$jscomp$inline_73_JSCompiler_inline_result$jscomp$inline_72_element$jscomp$21$$=$getAmpdoc$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_71_JSCompiler_ampdoc$jscomp$inline_73_JSCompiler_inline_result$jscomp$inline_72_element$jscomp$21$$);$JSCompiler_ampdoc$jscomp$inline_71_JSCompiler_ampdoc$jscomp$inline_73_JSCompiler_inline_result$jscomp$inline_72_element$jscomp$21$$=
$getAmpdoc$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_71_JSCompiler_ampdoc$jscomp$inline_73_JSCompiler_inline_result$jscomp$inline_72_element$jscomp$21$$);$JSCompiler_ampdoc$jscomp$inline_71_JSCompiler_ampdoc$jscomp$inline_73_JSCompiler_inline_result$jscomp$inline_72_element$jscomp$21$$=$JSCompiler_ampdoc$jscomp$inline_71_JSCompiler_ampdoc$jscomp$inline_73_JSCompiler_inline_result$jscomp$inline_72_element$jscomp$21$$.isSingleDoc()?$JSCompiler_ampdoc$jscomp$inline_71_JSCompiler_ampdoc$jscomp$inline_73_JSCompiler_inline_result$jscomp$inline_72_element$jscomp$21$$.win:
$JSCompiler_ampdoc$jscomp$inline_71_JSCompiler_ampdoc$jscomp$inline_73_JSCompiler_inline_result$jscomp$inline_72_element$jscomp$21$$;return $isServiceRegistered$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_71_JSCompiler_ampdoc$jscomp$inline_73_JSCompiler_inline_result$jscomp$inline_72_element$jscomp$21$$,"action")?$getServiceInternal$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_71_JSCompiler_ampdoc$jscomp$inline_73_JSCompiler_inline_result$jscomp$inline_72_element$jscomp$21$$,
"action"):null}
function $getAmpdoc$$module$src$service$$($JSCompiler_temp$jscomp$62_nodeOrDoc$jscomp$3$$){if($JSCompiler_temp$jscomp$62_nodeOrDoc$jscomp$3$$.nodeType){var $JSCompiler_win$jscomp$inline_75$$=($JSCompiler_temp$jscomp$62_nodeOrDoc$jscomp$3$$.ownerDocument||$JSCompiler_temp$jscomp$62_nodeOrDoc$jscomp$3$$).defaultView;$JSCompiler_win$jscomp$inline_75$$=$JSCompiler_win$jscomp$inline_75$$.__AMP_TOP||$JSCompiler_win$jscomp$inline_75$$;$JSCompiler_temp$jscomp$62_nodeOrDoc$jscomp$3$$=$getServiceInternal$$module$src$service$$($JSCompiler_win$jscomp$inline_75$$,"ampdoc").getAmpDoc($JSCompiler_temp$jscomp$62_nodeOrDoc$jscomp$3$$)}return $JSCompiler_temp$jscomp$62_nodeOrDoc$jscomp$3$$}
function $getServiceInternal$$module$src$service$$($holder$jscomp$4_s$jscomp$10$$,$id$jscomp$19$$){$isServiceRegistered$$module$src$service$$($holder$jscomp$4_s$jscomp$10$$,$id$jscomp$19$$);var $JSCompiler_services$jscomp$inline_32$$=$holder$jscomp$4_s$jscomp$10$$.services;$JSCompiler_services$jscomp$inline_32$$||($JSCompiler_services$jscomp$inline_32$$=$holder$jscomp$4_s$jscomp$10$$.services={});var $services$$=$JSCompiler_services$jscomp$inline_32$$;$holder$jscomp$4_s$jscomp$10$$=$services$$[$id$jscomp$19$$];
$holder$jscomp$4_s$jscomp$10$$.obj||($holder$jscomp$4_s$jscomp$10$$.obj=new $holder$jscomp$4_s$jscomp$10$$.ctor($holder$jscomp$4_s$jscomp$10$$.context),$holder$jscomp$4_s$jscomp$10$$.ctor=null,$holder$jscomp$4_s$jscomp$10$$.context=null,$holder$jscomp$4_s$jscomp$10$$.resolve&&$holder$jscomp$4_s$jscomp$10$$.resolve($holder$jscomp$4_s$jscomp$10$$.obj));return $holder$jscomp$4_s$jscomp$10$$.obj}
function $isServiceRegistered$$module$src$service$$($holder$jscomp$12_service$jscomp$4$$,$id$jscomp$27$$){$holder$jscomp$12_service$jscomp$4$$=$holder$jscomp$12_service$jscomp$4$$.services&&$holder$jscomp$12_service$jscomp$4$$.services[$id$jscomp$27$$];return!(!$holder$jscomp$12_service$jscomp$4$$||!$holder$jscomp$12_service$jscomp$4$$.ctor&&!$holder$jscomp$12_service$jscomp$4$$.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
(function($opt_initial$jscomp$1$$){return $opt_initial$jscomp$1$$||{}})({c:!0,v:!0,a:!0,ad:!0,action:!0});function $isExperimentOn$$module$src$experiments$$($JSCompiler_params$jscomp$inline_82_win$jscomp$52$$){var $experimentId$$="amp-action-macro";if($JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.__AMP__EXPERIMENT_TOGGLES)var $JSCompiler_inline_result$jscomp$21_JSCompiler_toggles$jscomp$inline_35$$=$JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.__AMP__EXPERIMENT_TOGGLES;else{$JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.__AMP__EXPERIMENT_TOGGLES=Object.create(null);$JSCompiler_inline_result$jscomp$21_JSCompiler_toggles$jscomp$inline_35$$=
$JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.__AMP__EXPERIMENT_TOGGLES;if($JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.AMP_CONFIG)for(var $JSCompiler_allowed$jscomp$inline_38_JSCompiler_experimentId$jscomp$inline_36_allowed$5$jscomp$inline_42$$ in $JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.AMP_CONFIG){var $JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$=
$JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.AMP_CONFIG[$JSCompiler_allowed$jscomp$inline_38_JSCompiler_experimentId$jscomp$inline_36_allowed$5$jscomp$inline_42$$];"number"===typeof $JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$&&0<=$JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$&&
1>=$JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$&&($JSCompiler_inline_result$jscomp$21_JSCompiler_toggles$jscomp$inline_35$$[$JSCompiler_allowed$jscomp$inline_38_JSCompiler_experimentId$jscomp$inline_36_allowed$5$jscomp$inline_42$$]=Math.random()<$JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$)}if($JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.AMP_CONFIG&&
Array.isArray($JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.AMP_CONFIG["allow-doc-opt-in"])&&0<$JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.AMP_CONFIG["allow-doc-opt-in"].length&&($JSCompiler_allowed$jscomp$inline_38_JSCompiler_experimentId$jscomp$inline_36_allowed$5$jscomp$inline_42$$=$JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.AMP_CONFIG["allow-doc-opt-in"],$JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$=
$JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){$JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$=$JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$.getAttribute("content").split(",");
for(var $JSCompiler_i$jscomp$inline_41_JSCompiler_name$jscomp$inline_84_JSCompiler_param$jscomp$inline_45$$=0;$JSCompiler_i$jscomp$inline_41_JSCompiler_name$jscomp$inline_84_JSCompiler_param$jscomp$inline_45$$<$JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$.length;$JSCompiler_i$jscomp$inline_41_JSCompiler_name$jscomp$inline_84_JSCompiler_param$jscomp$inline_45$$++)-1!=
$JSCompiler_allowed$jscomp$inline_38_JSCompiler_experimentId$jscomp$inline_36_allowed$5$jscomp$inline_42$$.indexOf($JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$[$JSCompiler_i$jscomp$inline_41_JSCompiler_name$jscomp$inline_84_JSCompiler_param$jscomp$inline_45$$])&&($JSCompiler_inline_result$jscomp$21_JSCompiler_toggles$jscomp$inline_35$$[$JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$[$JSCompiler_i$jscomp$inline_41_JSCompiler_name$jscomp$inline_84_JSCompiler_param$jscomp$inline_45$$]]=
!0)}Object.assign($JSCompiler_inline_result$jscomp$21_JSCompiler_toggles$jscomp$inline_35$$,$getExperimentTogglesFromCookie$$module$src$experiments$$($JSCompiler_params$jscomp$inline_82_win$jscomp$52$$));if($JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.AMP_CONFIG&&Array.isArray($JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.AMP_CONFIG["allow-url-opt-in"])&&0<$JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.AMP_CONFIG["allow-url-opt-in"].length){$JSCompiler_allowed$jscomp$inline_38_JSCompiler_experimentId$jscomp$inline_36_allowed$5$jscomp$inline_42$$=
$JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.AMP_CONFIG["allow-url-opt-in"];$JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$=$JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.location.originalHash||$JSCompiler_params$jscomp$inline_82_win$jscomp$52$$.location.hash;$JSCompiler_params$jscomp$inline_82_win$jscomp$52$$=Object.create(null);if($JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$)for(var $JSCompiler_match$jscomp$inline_83_JSCompiler_value$jscomp$inline_85$$;$JSCompiler_match$jscomp$inline_83_JSCompiler_value$jscomp$inline_85$$=
$regex$$module$src$url_parse_query_string$$.exec($JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$);)$JSCompiler_i$jscomp$inline_41_JSCompiler_name$jscomp$inline_84_JSCompiler_param$jscomp$inline_45$$=$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($JSCompiler_match$jscomp$inline_83_JSCompiler_value$jscomp$inline_85$$[1],$JSCompiler_match$jscomp$inline_83_JSCompiler_value$jscomp$inline_85$$[1]),
$JSCompiler_match$jscomp$inline_83_JSCompiler_value$jscomp$inline_85$$=$JSCompiler_match$jscomp$inline_83_JSCompiler_value$jscomp$inline_85$$[2]?$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($JSCompiler_match$jscomp$inline_83_JSCompiler_value$jscomp$inline_85$$[2],$JSCompiler_match$jscomp$inline_83_JSCompiler_value$jscomp$inline_85$$[2]):"",$JSCompiler_params$jscomp$inline_82_win$jscomp$52$$[$JSCompiler_i$jscomp$inline_41_JSCompiler_name$jscomp$inline_84_JSCompiler_param$jscomp$inline_45$$]=
$JSCompiler_match$jscomp$inline_83_JSCompiler_value$jscomp$inline_85$$;for($JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$=0;$JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$<$JSCompiler_allowed$jscomp$inline_38_JSCompiler_experimentId$jscomp$inline_36_allowed$5$jscomp$inline_42$$.length;$JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$++)$JSCompiler_i$jscomp$inline_41_JSCompiler_name$jscomp$inline_84_JSCompiler_param$jscomp$inline_45$$=
$JSCompiler_params$jscomp$inline_82_win$jscomp$52$$["e-"+$JSCompiler_allowed$jscomp$inline_38_JSCompiler_experimentId$jscomp$inline_36_allowed$5$jscomp$inline_42$$[$JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$]],"1"==$JSCompiler_i$jscomp$inline_41_JSCompiler_name$jscomp$inline_84_JSCompiler_param$jscomp$inline_45$$&&($JSCompiler_inline_result$jscomp$21_JSCompiler_toggles$jscomp$inline_35$$[$JSCompiler_allowed$jscomp$inline_38_JSCompiler_experimentId$jscomp$inline_36_allowed$5$jscomp$inline_42$$[$JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$]]=
!0),"0"==$JSCompiler_i$jscomp$inline_41_JSCompiler_name$jscomp$inline_84_JSCompiler_param$jscomp$inline_45$$&&($JSCompiler_inline_result$jscomp$21_JSCompiler_toggles$jscomp$inline_35$$[$JSCompiler_allowed$jscomp$inline_38_JSCompiler_experimentId$jscomp$inline_36_allowed$5$jscomp$inline_42$$[$JSCompiler_frequency$jscomp$inline_37_JSCompiler_meta$jscomp$inline_39_JSCompiler_optedInExperiments$jscomp$inline_40_JSCompiler_queryString$jscomp$inline_81_i$6$jscomp$inline_44$$]]=!1)}}var $toggles$$=$JSCompiler_inline_result$jscomp$21_JSCompiler_toggles$jscomp$inline_35$$;
return!!$toggles$$[$experimentId$$]}
function $getExperimentTogglesFromCookie$$module$src$experiments$$($JSCompiler_cookieString$jscomp$inline_49_JSCompiler_cookies$jscomp$inline_50_JSCompiler_inline_result$jscomp$20_JSCompiler_value$jscomp$inline_54_toggles$jscomp$3_win$jscomp$56$$){a:{try{var $JSCompiler_i$jscomp$inline_51_JSCompiler_inline_result$jscomp$65_i$jscomp$19$$=$JSCompiler_cookieString$jscomp$inline_49_JSCompiler_cookies$jscomp$inline_50_JSCompiler_inline_result$jscomp$20_JSCompiler_value$jscomp$inline_54_toggles$jscomp$3_win$jscomp$56$$.document.cookie}catch($JSCompiler_e$jscomp$inline_78$$){$JSCompiler_i$jscomp$inline_51_JSCompiler_inline_result$jscomp$65_i$jscomp$19$$=""}if($JSCompiler_cookieString$jscomp$inline_49_JSCompiler_cookies$jscomp$inline_50_JSCompiler_inline_result$jscomp$20_JSCompiler_value$jscomp$inline_54_toggles$jscomp$3_win$jscomp$56$$=
$JSCompiler_i$jscomp$inline_51_JSCompiler_inline_result$jscomp$65_i$jscomp$19$$)for($JSCompiler_cookieString$jscomp$inline_49_JSCompiler_cookies$jscomp$inline_50_JSCompiler_inline_result$jscomp$20_JSCompiler_value$jscomp$inline_54_toggles$jscomp$3_win$jscomp$56$$=$JSCompiler_cookieString$jscomp$inline_49_JSCompiler_cookies$jscomp$inline_50_JSCompiler_inline_result$jscomp$20_JSCompiler_value$jscomp$inline_54_toggles$jscomp$3_win$jscomp$56$$.split(";"),$JSCompiler_i$jscomp$inline_51_JSCompiler_inline_result$jscomp$65_i$jscomp$19$$=
0;$JSCompiler_i$jscomp$inline_51_JSCompiler_inline_result$jscomp$65_i$jscomp$19$$<$JSCompiler_cookieString$jscomp$inline_49_JSCompiler_cookies$jscomp$inline_50_JSCompiler_inline_result$jscomp$20_JSCompiler_value$jscomp$inline_54_toggles$jscomp$3_win$jscomp$56$$.length;$JSCompiler_i$jscomp$inline_51_JSCompiler_inline_result$jscomp$65_i$jscomp$19$$++){var $JSCompiler_cookie$jscomp$inline_52$$=$JSCompiler_cookieString$jscomp$inline_49_JSCompiler_cookies$jscomp$inline_50_JSCompiler_inline_result$jscomp$20_JSCompiler_value$jscomp$inline_54_toggles$jscomp$3_win$jscomp$56$$[$JSCompiler_i$jscomp$inline_51_JSCompiler_inline_result$jscomp$65_i$jscomp$19$$].trim(),
$JSCompiler_eq$jscomp$inline_53$$=$JSCompiler_cookie$jscomp$inline_52$$.indexOf("=");if(-1!=$JSCompiler_eq$jscomp$inline_53$$&&"AMP_EXP"==$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($JSCompiler_cookie$jscomp$inline_52$$.substring(0,$JSCompiler_eq$jscomp$inline_53$$).trim(),void 0)){$JSCompiler_cookieString$jscomp$inline_49_JSCompiler_cookies$jscomp$inline_50_JSCompiler_inline_result$jscomp$20_JSCompiler_value$jscomp$inline_54_toggles$jscomp$3_win$jscomp$56$$=$JSCompiler_cookie$jscomp$inline_52$$.substring($JSCompiler_eq$jscomp$inline_53$$+
1).trim();$JSCompiler_cookieString$jscomp$inline_49_JSCompiler_cookies$jscomp$inline_50_JSCompiler_inline_result$jscomp$20_JSCompiler_value$jscomp$inline_54_toggles$jscomp$3_win$jscomp$56$$=$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($JSCompiler_cookieString$jscomp$inline_49_JSCompiler_cookies$jscomp$inline_50_JSCompiler_inline_result$jscomp$20_JSCompiler_value$jscomp$inline_54_toggles$jscomp$3_win$jscomp$56$$,$JSCompiler_cookieString$jscomp$inline_49_JSCompiler_cookies$jscomp$inline_50_JSCompiler_inline_result$jscomp$20_JSCompiler_value$jscomp$inline_54_toggles$jscomp$3_win$jscomp$56$$);
break a}}$JSCompiler_cookieString$jscomp$inline_49_JSCompiler_cookies$jscomp$inline_50_JSCompiler_inline_result$jscomp$20_JSCompiler_value$jscomp$inline_54_toggles$jscomp$3_win$jscomp$56$$=null}var $experimentCookie$$=$JSCompiler_cookieString$jscomp$inline_49_JSCompiler_cookies$jscomp$inline_50_JSCompiler_inline_result$jscomp$20_JSCompiler_value$jscomp$inline_54_toggles$jscomp$3_win$jscomp$56$$,$tokens$$=$experimentCookie$$?$experimentCookie$$.split(/\s*,\s*/g):[];$JSCompiler_cookieString$jscomp$inline_49_JSCompiler_cookies$jscomp$inline_50_JSCompiler_inline_result$jscomp$20_JSCompiler_value$jscomp$inline_54_toggles$jscomp$3_win$jscomp$56$$=
Object.create(null);for($JSCompiler_i$jscomp$inline_51_JSCompiler_inline_result$jscomp$65_i$jscomp$19$$=0;$JSCompiler_i$jscomp$inline_51_JSCompiler_inline_result$jscomp$65_i$jscomp$19$$<$tokens$$.length;$JSCompiler_i$jscomp$inline_51_JSCompiler_inline_result$jscomp$65_i$jscomp$19$$++)0!=$tokens$$[$JSCompiler_i$jscomp$inline_51_JSCompiler_inline_result$jscomp$65_i$jscomp$19$$].length&&("-"==$tokens$$[$JSCompiler_i$jscomp$inline_51_JSCompiler_inline_result$jscomp$65_i$jscomp$19$$][0]?$JSCompiler_cookieString$jscomp$inline_49_JSCompiler_cookies$jscomp$inline_50_JSCompiler_inline_result$jscomp$20_JSCompiler_value$jscomp$inline_54_toggles$jscomp$3_win$jscomp$56$$[$tokens$$[$JSCompiler_i$jscomp$inline_51_JSCompiler_inline_result$jscomp$65_i$jscomp$19$$].substr(1)]=
!1:$JSCompiler_cookieString$jscomp$inline_49_JSCompiler_cookies$jscomp$inline_50_JSCompiler_inline_result$jscomp$20_JSCompiler_value$jscomp$inline_54_toggles$jscomp$3_win$jscomp$56$$[$tokens$$[$JSCompiler_i$jscomp$inline_51_JSCompiler_inline_result$jscomp$65_i$jscomp$19$$]]=!0);return $JSCompiler_cookieString$jscomp$inline_49_JSCompiler_cookies$jscomp$inline_50_JSCompiler_inline_result$jscomp$20_JSCompiler_value$jscomp$inline_54_toggles$jscomp$3_win$jscomp$56$$};function $AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$($$jscomp$super$this_element$jscomp$65$$){$$jscomp$super$this_element$jscomp$65$$=AMP.BaseElement.call(this,$$jscomp$super$this_element$jscomp$65$$)||this;$$jscomp$super$this_element$jscomp$65$$.$actions_$=null;$$jscomp$super$this_element$jscomp$65$$.$arguments_$=[];return $$jscomp$super$this_element$jscomp$65$$}var $JSCompiler_parentCtor$jscomp$inline_57$$=AMP.BaseElement;
$AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$.prototype=$$jscomp$objectCreate$$($JSCompiler_parentCtor$jscomp$inline_57$$.prototype);$AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$.prototype.constructor=$AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$;
if($$jscomp$setPrototypeOf$$)$$jscomp$setPrototypeOf$$($AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$,$JSCompiler_parentCtor$jscomp$inline_57$$);else for(var $JSCompiler_p$jscomp$inline_58$$ in $JSCompiler_parentCtor$jscomp$inline_57$$)if("prototype"!=$JSCompiler_p$jscomp$inline_58$$)if(Object.defineProperties){var $JSCompiler_descriptor$jscomp$inline_59$$=Object.getOwnPropertyDescriptor($JSCompiler_parentCtor$jscomp$inline_57$$,$JSCompiler_p$jscomp$inline_58$$);$JSCompiler_descriptor$jscomp$inline_59$$&&
Object.defineProperty($AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$,$JSCompiler_p$jscomp$inline_58$$,$JSCompiler_descriptor$jscomp$inline_59$$)}else $AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$[$JSCompiler_p$jscomp$inline_58$$]=$JSCompiler_parentCtor$jscomp$inline_57$$[$JSCompiler_p$jscomp$inline_58$$];$AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$.$superClass_$=$JSCompiler_parentCtor$jscomp$inline_57$$.prototype;
$AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$.prototype.buildCallback=function(){$userAssert$$module$src$log$$($isExperimentOn$$module$src$experiments$$(this.win),"Experiment is off");var $element$jscomp$66$$=this.element;this.$actions_$=$getExistingServiceForDocInEmbedScope$$module$src$service$$($element$jscomp$66$$);var $argVarNames$$=$element$jscomp$66$$.getAttribute("arguments");$argVarNames$$&&(this.$arguments_$=$argVarNames$$.split(",").map(function($element$jscomp$66$$){return $element$jscomp$66$$.trim()}));
this.registerAction("execute",this.$execute_$.bind(this))};$AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$.prototype.getLayoutPriority=function(){return 1};
$AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$.prototype.$execute_$=function($invocation$$){var $$jscomp$destructuring$var15$$=$invocation$$,$actionEventType$$=$$jscomp$destructuring$var15$$.actionEventType,$args$$=$$jscomp$destructuring$var15$$.args,$event$jscomp$5$$=$$jscomp$destructuring$var15$$.event,$trust$$=$$jscomp$destructuring$var15$$.trust;if($args$$&&0<this.$arguments_$.length)for(var $arg$jscomp$7$$ in $args$$)$userAssert$$module$src$log$$(this.$arguments_$.includes($arg$jscomp$7$$),
'Variable argument name "%s" is not defined in %s',$arg$jscomp$7$$,this.element);"amp-action-macro"===$invocation$$.caller.tagName.toLowerCase()&&$userAssert$$module$src$log$$(!!(this.element.compareDocumentPosition($invocation$$.caller)&Node.DOCUMENT_POSITION_FOLLOWING),'Action macro with ID "%s" cannot reference itself or macros defined after it',this.element.getAttribute("id"));this.$actions_$.trigger(this.element,""+$actionEventType$$,$event$jscomp$5$$,$trust$$,$args$$)};
$AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$.prototype.renderOutsideViewport=function(){return!0};(function($AMP$jscomp$1$$){$AMP$jscomp$1$$.registerElement("amp-action-macro",$AmpActionMacro$$module$extensions$amp_action_macro$0_1$amp_action_macro$$)})(self.AMP);
})});

//# sourceMappingURL=amp-action-macro-0.1.js.map
