(self.AMP=self.AMP||[]).push({n:"amp-gfycat",v:"1904281823091",f:(function(AMP,_){
var $JSCompiler_prototypeAlias$$,$$jscomp$objectCreate$$="function"==typeof Object.create?Object.create:function($prototype$$){function $ctor$$(){}$ctor$$.prototype=$prototype$$;return new $ctor$$},$JSCompiler_temp$jscomp$20$$;
if("function"==typeof Object.setPrototypeOf)$JSCompiler_temp$jscomp$20$$=Object.setPrototypeOf;else{var $JSCompiler_inline_result$jscomp$21$$;a:{var $JSCompiler_x$jscomp$inline_41$$={a:!0},$JSCompiler_y$jscomp$inline_42$$={};try{$JSCompiler_y$jscomp$inline_42$$.__proto__=$JSCompiler_x$jscomp$inline_41$$;$JSCompiler_inline_result$jscomp$21$$=$JSCompiler_y$jscomp$inline_42$$.a;break a}catch($JSCompiler_e$jscomp$inline_43$$){}$JSCompiler_inline_result$jscomp$21$$=!1}$JSCompiler_temp$jscomp$20$$=$JSCompiler_inline_result$jscomp$21$$?
function($target$jscomp$83$$,$proto$jscomp$3$$){$target$jscomp$83$$.__proto__=$proto$jscomp$3$$;if($target$jscomp$83$$.__proto__!==$proto$jscomp$3$$)throw new TypeError($target$jscomp$83$$+" is not extensible");return $target$jscomp$83$$}:null}var $$jscomp$setPrototypeOf$$=$JSCompiler_temp$jscomp$20$$;function $tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($component$jscomp$4$$,$fallback$$){$fallback$$=void 0===$fallback$$?"":$fallback$$;try{return decodeURIComponent($component$jscomp$4$$)}catch($e$jscomp$8$$){return $fallback$$}};var $regex$$module$src$url_parse_query_string$$=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;
function $parseQueryString_$$module$src$url_parse_query_string$$($queryString$$){var $params$jscomp$1$$=Object.create(null);if(!$queryString$$)return $params$jscomp$1$$;for(var $match$$;$match$$=$regex$$module$src$url_parse_query_string$$.exec($queryString$$);){var $name$jscomp$70$$=$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($match$$[1],$match$$[1]),$value$jscomp$87$$=$match$$[2]?$tryDecodeUriComponent_$$module$src$url_try_decode_uri_component$$($match$$[2],$match$$[2]):"";
$params$jscomp$1$$[$name$jscomp$70$$]=$value$jscomp$87$$}return $params$jscomp$1$$};var $rtvVersion$$module$src$mode$$="";var $toString_$$module$src$types$$=Object.prototype.toString;function $isFiniteNumber$$module$src$types$$($value$jscomp$91$$){return"number"===typeof $value$jscomp$91$$&&isFinite($value$jscomp$91$$)};self.log=self.log||{user:null,dev:null,userForEmbed:null};var $logs$$module$src$log$$=self.log;function $user$$module$src$log$$(){if(!$logs$$module$src$log$$.user)throw Error("failed to call initLogConstructor");return $logs$$module$src$log$$.user}function $dev$$module$src$log$$(){if($logs$$module$src$log$$.dev)return $logs$$module$src$log$$.dev;throw Error("failed to call initLogConstructor");}
function $userAssert$$module$src$log$$($shouldBeTrueish$jscomp$3$$,$opt_message$jscomp$14$$,$opt_1$jscomp$1$$){return $user$$module$src$log$$().assert($shouldBeTrueish$jscomp$3$$,$opt_message$jscomp$14$$,$opt_1$jscomp$1$$,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function $getExistingServiceForDocInEmbedScope$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_50_JSCompiler_holder$jscomp$inline_51_element$jscomp$11$$,$id$jscomp$6$$){var $opt_fallbackToTopWin$$,$win$jscomp$6$$=$JSCompiler_ampdoc$jscomp$inline_50_JSCompiler_holder$jscomp$inline_51_element$jscomp$11$$.ownerDocument.defaultView,$isEmbed$$=$win$jscomp$6$$!=($win$jscomp$6$$.__AMP_TOP||$win$jscomp$6$$);if($isEmbed$$){if($isServiceRegistered$$module$src$service$$($win$jscomp$6$$,$id$jscomp$6$$)){var $embedService$$=
$getServiceInternal$$module$src$service$$($win$jscomp$6$$,$id$jscomp$6$$);if($embedService$$)return $embedService$$}if(!$opt_fallbackToTopWin$$)return null}$JSCompiler_ampdoc$jscomp$inline_50_JSCompiler_holder$jscomp$inline_51_element$jscomp$11$$=$getAmpdoc$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_50_JSCompiler_holder$jscomp$inline_51_element$jscomp$11$$);$JSCompiler_ampdoc$jscomp$inline_50_JSCompiler_holder$jscomp$inline_51_element$jscomp$11$$=$getAmpdocServiceHolder$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_50_JSCompiler_holder$jscomp$inline_51_element$jscomp$11$$);
return $isServiceRegistered$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_50_JSCompiler_holder$jscomp$inline_51_element$jscomp$11$$,$id$jscomp$6$$)?$getServiceInternal$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_50_JSCompiler_holder$jscomp$inline_51_element$jscomp$11$$,$id$jscomp$6$$):null}
function $getService$$module$src$service$$($win$jscomp$8$$,$id$jscomp$11$$){$win$jscomp$8$$=$win$jscomp$8$$.__AMP_TOP||$win$jscomp$8$$;return $getServiceInternal$$module$src$service$$($win$jscomp$8$$,$id$jscomp$11$$)}
function $getServiceForDoc$$module$src$service$$($elementOrAmpDoc$$,$id$jscomp$15$$){var $ampdoc$jscomp$2_holder$jscomp$2$$=$getAmpdoc$$module$src$service$$($elementOrAmpDoc$$);$ampdoc$jscomp$2_holder$jscomp$2$$=$getAmpdocServiceHolder$$module$src$service$$($ampdoc$jscomp$2_holder$jscomp$2$$);return $getServiceInternal$$module$src$service$$($ampdoc$jscomp$2_holder$jscomp$2$$,$id$jscomp$15$$)}
function $getAmpdoc$$module$src$service$$($nodeOrDoc$jscomp$2$$){return $nodeOrDoc$jscomp$2$$.nodeType?$getService$$module$src$service$$(($nodeOrDoc$jscomp$2$$.ownerDocument||$nodeOrDoc$jscomp$2$$).defaultView,"ampdoc").getAmpDoc($nodeOrDoc$jscomp$2$$):$nodeOrDoc$jscomp$2$$}
function $getAmpdocServiceHolder$$module$src$service$$($ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$){$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$=$getAmpdoc$$module$src$service$$($ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$);return $ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$.isSingleDoc()?$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$.win:$ampdoc$jscomp$4_nodeOrDoc$jscomp$3$$}
function $getServiceInternal$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$,$id$jscomp$19$$){$isServiceRegistered$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$,$id$jscomp$19$$);var $services$$=$getServices$$module$src$service$$($holder$jscomp$4_s$jscomp$8$$);$holder$jscomp$4_s$jscomp$8$$=$services$$[$id$jscomp$19$$];$holder$jscomp$4_s$jscomp$8$$.obj||($holder$jscomp$4_s$jscomp$8$$.obj=new $holder$jscomp$4_s$jscomp$8$$.ctor($holder$jscomp$4_s$jscomp$8$$.context),$holder$jscomp$4_s$jscomp$8$$.ctor=
null,$holder$jscomp$4_s$jscomp$8$$.context=null,$holder$jscomp$4_s$jscomp$8$$.resolve&&$holder$jscomp$4_s$jscomp$8$$.resolve($holder$jscomp$4_s$jscomp$8$$.obj));return $holder$jscomp$4_s$jscomp$8$$.obj}function $getServices$$module$src$service$$($holder$jscomp$9$$){var $services$jscomp$5$$=$holder$jscomp$9$$.services;$services$jscomp$5$$||($services$jscomp$5$$=$holder$jscomp$9$$.services={});return $services$jscomp$5$$}
function $isServiceRegistered$$module$src$service$$($holder$jscomp$12_service$jscomp$4$$,$id$jscomp$27$$){$holder$jscomp$12_service$jscomp$4$$=$holder$jscomp$12_service$jscomp$4$$.services&&$holder$jscomp$12_service$jscomp$4$$.services[$id$jscomp$27$$];return!(!$holder$jscomp$12_service$jscomp$4$$||!$holder$jscomp$12_service$jscomp$4$$.ctor&&!$holder$jscomp$12_service$jscomp$4$$.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function $map$$module$src$utils$object$$($opt_initial$$){var $obj$jscomp$25$$=Object.create(null);$opt_initial$$&&Object.assign($obj$jscomp$25$$,$opt_initial$$);return $obj$jscomp$25$$}function $dict$$module$src$utils$object$$($opt_initial$jscomp$1$$){return $opt_initial$jscomp$1$$||{}};function $startsWith$$module$src$string$$($string$jscomp$6$$,$prefix$jscomp$2$$){return $prefix$jscomp$2$$.length>$string$jscomp$6$$.length?!1:0==$string$jscomp$6$$.lastIndexOf($prefix$jscomp$2$$,0)};function $removeElement$$module$src$dom$$($element$jscomp$13$$){$element$jscomp$13$$.parentElement&&$element$jscomp$13$$.parentElement.removeChild($element$jscomp$13$$)}
function $getDataParamsFromAttributes$$module$src$dom$$($element$jscomp$20_params$jscomp$2$$){var $opt_computeParamNameFunc$$,$opt_paramPattern$$,$computeParamNameFunc$$=$opt_computeParamNameFunc$$||function($element$jscomp$20_params$jscomp$2$$){return $element$jscomp$20_params$jscomp$2$$},$dataset$$=$element$jscomp$20_params$jscomp$2$$.dataset;$element$jscomp$20_params$jscomp$2$$={};var $paramPattern$$=$opt_paramPattern$$?$opt_paramPattern$$:/^param(.+)/,$key$jscomp$41$$;for($key$jscomp$41$$ in $dataset$$){var $matches$$=
$key$jscomp$41$$.match($paramPattern$$);$matches$$&&($element$jscomp$20_params$jscomp$2$$[$computeParamNameFunc$$($matches$$[1][0].toLowerCase()+$matches$$[1].substr(1))]=$dataset$$[$key$jscomp$41$$])}return $element$jscomp$20_params$jscomp$2$$};$dict$$module$src$utils$object$$({c:!0,v:!0,a:!0,ad:!0,action:!0});var $optsSupported$$module$src$event_helper_listen$$;
function $internalListenImplementation$$module$src$event_helper_listen$$($element$jscomp$56$$,$eventType$jscomp$3$$,$listener$jscomp$62$$,$opt_evtListenerOpts$$){var $localElement$$=$element$jscomp$56$$,$localListener$$=$listener$jscomp$62$$;var $wrapped$$=function($element$jscomp$56$$){try{return $localListener$$($element$jscomp$56$$)}catch($e$jscomp$16$$){throw self.reportError($e$jscomp$16$$),$e$jscomp$16$$;}};var $optsSupported$$=$detectEvtListenerOptsSupport$$module$src$event_helper_listen$$(),$capture$$=
!1;$opt_evtListenerOpts$$&&($capture$$=$opt_evtListenerOpts$$.capture);$localElement$$.addEventListener($eventType$jscomp$3$$,$wrapped$$,$optsSupported$$?$opt_evtListenerOpts$$:$capture$$);return function(){$localElement$$&&$localElement$$.removeEventListener($eventType$jscomp$3$$,$wrapped$$,$optsSupported$$?$opt_evtListenerOpts$$:$capture$$);$wrapped$$=$localElement$$=$localListener$$=null}}
function $detectEvtListenerOptsSupport$$module$src$event_helper_listen$$(){if(void 0!==$optsSupported$$module$src$event_helper_listen$$)return $optsSupported$$module$src$event_helper_listen$$;$optsSupported$$module$src$event_helper_listen$$=!1;try{var $options$jscomp$14$$={get capture(){$optsSupported$$module$src$event_helper_listen$$=!0}};self.addEventListener("test-options",null,$options$jscomp$14$$);self.removeEventListener("test-options",null,$options$jscomp$14$$)}catch($err$jscomp$3$$){}return $optsSupported$$module$src$event_helper_listen$$}
;function $createCustomEvent$$module$src$event_helper$$($e$jscomp$17_win$jscomp$44$$,$type$jscomp$134$$,$detail$jscomp$3$$){var $eventInit$$={detail:$detail$jscomp$3$$};Object.assign($eventInit$$,void 0);if("function"==typeof $e$jscomp$17_win$jscomp$44$$.CustomEvent)return new $e$jscomp$17_win$jscomp$44$$.CustomEvent($type$jscomp$134$$,$eventInit$$);$e$jscomp$17_win$jscomp$44$$=$e$jscomp$17_win$jscomp$44$$.document.createEvent("CustomEvent");$e$jscomp$17_win$jscomp$44$$.initCustomEvent($type$jscomp$134$$,
!!$eventInit$$.bubbles,!!$eventInit$$.cancelable,$detail$jscomp$3$$);return $e$jscomp$17_win$jscomp$44$$}function $listen$$module$src$event_helper$$($element$jscomp$57$$,$eventType$jscomp$4$$,$listener$jscomp$63$$){return $internalListenImplementation$$module$src$event_helper_listen$$($element$jscomp$57$$,$eventType$jscomp$4$$,$listener$jscomp$63$$,void 0)}
function $listenOnce$$module$src$event_helper$$($element$jscomp$58$$,$eventType$jscomp$5$$,$listener$jscomp$64$$,$opt_evtListenerOpts$jscomp$2$$){var $localListener$jscomp$1$$=$listener$jscomp$64$$,$unlisten$$=$internalListenImplementation$$module$src$event_helper_listen$$($element$jscomp$58$$,$eventType$jscomp$5$$,function($element$jscomp$58$$){try{$localListener$jscomp$1$$($element$jscomp$58$$)}finally{$localListener$jscomp$1$$=null,$unlisten$$()}},$opt_evtListenerOpts$jscomp$2$$);return $unlisten$$}
function $listenOncePromise$$module$src$event_helper$$($element$jscomp$59$$){var $opt_cancel$$,$unlisten$jscomp$1$$,$eventPromise$$=new Promise(function($opt_cancel$$){$unlisten$jscomp$1$$=$listenOnce$$module$src$event_helper$$($element$jscomp$59$$,"load",$opt_cancel$$,void 0)});$eventPromise$$.then($unlisten$jscomp$1$$,$unlisten$jscomp$1$$);$opt_cancel$$&&$opt_cancel$$($unlisten$jscomp$1$$);return $eventPromise$$};var $EMPTY_METADATA$$module$src$mediasession_helper$$={title:"",artist:"",album:"",artwork:[{src:""}]};
function $parseSchemaImage$$module$src$mediasession_helper$$($doc$jscomp$14$$){var $schema$$=$doc$jscomp$14$$.querySelector('script[type="application/ld+json"]');if($schema$$){try{var $JSCompiler_inline_result$jscomp$26$$=JSON.parse($schema$$.textContent)}catch($JSCompiler_e$jscomp$inline_55$$){$JSCompiler_inline_result$jscomp$26$$=null}var $schemaJson$$=$JSCompiler_inline_result$jscomp$26$$;if($schemaJson$$&&$schemaJson$$.image){if("string"===typeof $schemaJson$$.image)return $schemaJson$$.image;
if($schemaJson$$.image["@list"]&&"string"===typeof $schemaJson$$.image["@list"][0])return $schemaJson$$.image["@list"][0];if("string"===typeof $schemaJson$$.image.url)return $schemaJson$$.image.url;if("string"===typeof $schemaJson$$.image[0])return $schemaJson$$.image[0]}}}
function $validateMetadata$$module$src$mediasession_helper$$($element$jscomp$62$$,$metadata$jscomp$1$$){var $urlService$$=$getExistingServiceForDocInEmbedScope$$module$src$service$$($element$jscomp$62$$,"url");if($metadata$jscomp$1$$&&$metadata$jscomp$1$$.artwork){var $artwork$$=$metadata$jscomp$1$$.artwork;$artwork$$.forEach(function($element$jscomp$62$$){if($element$jscomp$62$$){var $metadata$jscomp$1$$="[object Object]"===$toString_$$module$src$types$$.call($element$jscomp$62$$)?$element$jscomp$62$$.src:
$element$jscomp$62$$;$userAssert$$module$src$log$$($urlService$$.isProtocolValid($metadata$jscomp$1$$))}})}};function $Observable$$module$src$observable$$(){this.$handlers_$=null}$JSCompiler_prototypeAlias$$=$Observable$$module$src$observable$$.prototype;$JSCompiler_prototypeAlias$$.add=function($handler$jscomp$4$$){var $$jscomp$this$jscomp$1$$=this;this.$handlers_$||(this.$handlers_$=[]);this.$handlers_$.push($handler$jscomp$4$$);return function(){$$jscomp$this$jscomp$1$$.remove($handler$jscomp$4$$)}};
$JSCompiler_prototypeAlias$$.remove=function($handler$jscomp$5_index$jscomp$72$$){this.$handlers_$&&($handler$jscomp$5_index$jscomp$72$$=this.$handlers_$.indexOf($handler$jscomp$5_index$jscomp$72$$),-1<$handler$jscomp$5_index$jscomp$72$$&&this.$handlers_$.splice($handler$jscomp$5_index$jscomp$72$$,1))};$JSCompiler_prototypeAlias$$.removeAll=function(){this.$handlers_$&&(this.$handlers_$.length=0)};
$JSCompiler_prototypeAlias$$.fire=function($opt_event$$){if(this.$handlers_$)for(var $handlers$$=this.$handlers_$,$i$jscomp$15$$=0;$i$jscomp$15$$<$handlers$$.length;$i$jscomp$15$$++)(0,$handlers$$[$i$jscomp$15$$])($opt_event$$)};$JSCompiler_prototypeAlias$$.getHandlerCount=function(){return this.$handlers_$?this.$handlers_$.length:0};function $VideoSessionManager$$module$src$service$video_session_manager$$(){this.$isSessionActive_$=!1;this.$endSessionObservable_$=new $Observable$$module$src$observable$$}$VideoSessionManager$$module$src$service$video_session_manager$$.prototype.onSessionEnd=function($listener$jscomp$65$$){this.$endSessionObservable_$.add($listener$jscomp$65$$)};$VideoSessionManager$$module$src$service$video_session_manager$$.prototype.beginSession=function(){this.$isSessionActive_$=!0};
$VideoSessionManager$$module$src$service$video_session_manager$$.prototype.endSession=function(){this.$isSessionActive_$&&this.$endSessionObservable_$.fire();this.$isSessionActive_$=!1};$VideoSessionManager$$module$src$service$video_session_manager$$.prototype.isSessionActive=function(){return this.$isSessionActive_$};function $once$$module$src$utils$function$$($fn$jscomp$3$$){var $evaluated$$=!1,$retValue$$=null,$callback$jscomp$66$$=$fn$jscomp$3$$;return function($fn$jscomp$3$$){for(var $args$$=[],$$jscomp$restIndex$$=0;$$jscomp$restIndex$$<arguments.length;++$$jscomp$restIndex$$)$args$$[$$jscomp$restIndex$$-0]=arguments[$$jscomp$restIndex$$];$evaluated$$||($retValue$$=$callback$jscomp$66$$.apply(self,$args$$),$evaluated$$=!0,$callback$jscomp$66$$=null);return $retValue$$}};var $propertyNameCache$$module$src$style$$,$vendorPrefixes$$module$src$style$$="Webkit webkit Moz moz ms O o".split(" ");
function $setStyles$$module$src$style$$($element$jscomp$66$$){var $styles$jscomp$1$$={position:"fixed",top:"0",width:"0",height:"0",opacity:"0"},$k$jscomp$5$$;for($k$jscomp$5$$ in $styles$jscomp$1$$){var $JSCompiler_element$jscomp$inline_57$$=$element$jscomp$66$$,$JSCompiler_value$jscomp$inline_59$$=$styles$jscomp$1$$[$k$jscomp$5$$];var $JSCompiler_propertyName$jscomp$inline_62_JSCompiler_style$jscomp$inline_162$$=$JSCompiler_element$jscomp$inline_57$$.style;var $JSCompiler_camelCase$jscomp$inline_163$$=
$k$jscomp$5$$;if($startsWith$$module$src$string$$($JSCompiler_camelCase$jscomp$inline_163$$,"--"))$JSCompiler_propertyName$jscomp$inline_62_JSCompiler_style$jscomp$inline_162$$=$JSCompiler_camelCase$jscomp$inline_163$$;else{$propertyNameCache$$module$src$style$$||($propertyNameCache$$module$src$style$$=$map$$module$src$utils$object$$());var $JSCompiler_propertyName$jscomp$inline_165$$=$propertyNameCache$$module$src$style$$[$JSCompiler_camelCase$jscomp$inline_163$$];if(!$JSCompiler_propertyName$jscomp$inline_165$$){$JSCompiler_propertyName$jscomp$inline_165$$=
$JSCompiler_camelCase$jscomp$inline_163$$;if(void 0===$JSCompiler_propertyName$jscomp$inline_62_JSCompiler_style$jscomp$inline_162$$[$JSCompiler_camelCase$jscomp$inline_163$$]){var $JSCompiler_prefixedPropertyName$jscomp$inline_167_JSCompiler_titleCase$jscomp$inline_166$$=$JSCompiler_camelCase$jscomp$inline_163$$.charAt(0).toUpperCase()+$JSCompiler_camelCase$jscomp$inline_163$$.slice(1);b:{for(var $JSCompiler_i$jscomp$inline_238$$=0;$JSCompiler_i$jscomp$inline_238$$<$vendorPrefixes$$module$src$style$$.length;$JSCompiler_i$jscomp$inline_238$$++){var $JSCompiler_propertyName$jscomp$inline_239$$=
$vendorPrefixes$$module$src$style$$[$JSCompiler_i$jscomp$inline_238$$]+$JSCompiler_prefixedPropertyName$jscomp$inline_167_JSCompiler_titleCase$jscomp$inline_166$$;if(void 0!==$JSCompiler_propertyName$jscomp$inline_62_JSCompiler_style$jscomp$inline_162$$[$JSCompiler_propertyName$jscomp$inline_239$$]){$JSCompiler_prefixedPropertyName$jscomp$inline_167_JSCompiler_titleCase$jscomp$inline_166$$=$JSCompiler_propertyName$jscomp$inline_239$$;break b}}$JSCompiler_prefixedPropertyName$jscomp$inline_167_JSCompiler_titleCase$jscomp$inline_166$$=
""}void 0!==$JSCompiler_propertyName$jscomp$inline_62_JSCompiler_style$jscomp$inline_162$$[$JSCompiler_prefixedPropertyName$jscomp$inline_167_JSCompiler_titleCase$jscomp$inline_166$$]&&($JSCompiler_propertyName$jscomp$inline_165$$=$JSCompiler_prefixedPropertyName$jscomp$inline_167_JSCompiler_titleCase$jscomp$inline_166$$)}$propertyNameCache$$module$src$style$$[$JSCompiler_camelCase$jscomp$inline_163$$]=$JSCompiler_propertyName$jscomp$inline_165$$}$JSCompiler_propertyName$jscomp$inline_62_JSCompiler_style$jscomp$inline_162$$=
$JSCompiler_propertyName$jscomp$inline_165$$}$JSCompiler_propertyName$jscomp$inline_62_JSCompiler_style$jscomp$inline_162$$&&($JSCompiler_element$jscomp$inline_57$$.style[$JSCompiler_propertyName$jscomp$inline_62_JSCompiler_style$jscomp$inline_162$$]=$JSCompiler_value$jscomp$inline_59$$)}};function $isAutoplaySupportedImpl$$module$src$utils$video$$($win$jscomp$47$$,$isLiteViewer$$){if($isLiteViewer$$)return Promise.resolve(!1);var $detectionElement$$=$win$jscomp$47$$.document.createElement("video");$detectionElement$$.setAttribute("muted","");$detectionElement$$.setAttribute("playsinline","");$detectionElement$$.setAttribute("webkit-playsinline","");$detectionElement$$.setAttribute("height","0");$detectionElement$$.setAttribute("width","0");$detectionElement$$.muted=!0;$detectionElement$$.playsinline=
!0;$detectionElement$$.webkitPlaysinline=!0;$setStyles$$module$src$style$$($detectionElement$$);(new Promise(function($win$jscomp$47$$){return $win$jscomp$47$$($detectionElement$$.play())})).catch(function(){});return Promise.resolve(!$detectionElement$$.paused)}var $isAutoplaySupported$$module$src$utils$video$$=null;function $clamp$$module$src$utils$math$$($val$jscomp$5$$){var $min$$=250,$max$$=4E3;return Math.min(Math.max($val$jscomp$5$$,$min$$),$max$$)};function $getExistingStyleElement$$module$src$style_installer$$($cssRoot$jscomp$2_existing$jscomp$1$$,$styleMap$jscomp$1$$,$key$jscomp$50$$){return $styleMap$jscomp$1$$[$key$jscomp$50$$]?$styleMap$jscomp$1$$[$key$jscomp$50$$]:($cssRoot$jscomp$2_existing$jscomp$1$$=$cssRoot$jscomp$2_existing$jscomp$1$$.querySelector("style["+$key$jscomp$50$$+"]"))?$styleMap$jscomp$1$$[$key$jscomp$50$$]=$cssRoot$jscomp$2_existing$jscomp$1$$:null};var $container$$module$src$static_template$$;
function $htmlFor$$module$src$static_template$$($doc$jscomp$25_nodeOrDoc$jscomp$4$$){$doc$jscomp$25_nodeOrDoc$jscomp$4$$=$doc$jscomp$25_nodeOrDoc$jscomp$4$$.ownerDocument||$doc$jscomp$25_nodeOrDoc$jscomp$4$$;$container$$module$src$static_template$$&&$container$$module$src$static_template$$.ownerDocument===$doc$jscomp$25_nodeOrDoc$jscomp$4$$||($container$$module$src$static_template$$=$doc$jscomp$25_nodeOrDoc$jscomp$4$$.createElement("div"));return $html$$module$src$static_template$$}
function $html$$module$src$static_template$$($strings$$){$container$$module$src$static_template$$.innerHTML=$strings$$[0];var $el$jscomp$9$$=$container$$module$src$static_template$$.firstElementChild;$container$$module$src$static_template$$.removeChild($el$jscomp$9$$);return $el$jscomp$9$$};var $$jscomp$templatelit$1$$=['<i-amphtml-video-icon class="amp-video-eq">\n    <div class="amp-video-eq-col">\n      <div class="amp-video-eq-filler"></div>\n      <div class="amp-video-eq-filler"></div>\n    </div>\n  </i-amphtml-video-icon>'];$$jscomp$templatelit$1$$.raw=$$jscomp$templatelit$1$$.slice();var $$jscomp$templatelit$0$$=['<i-amphtml-video-mask class="i-amphtml-fill-content" role=button>\n    </i-amphtml-video-mask>'];$$jscomp$templatelit$0$$.raw=$$jscomp$templatelit$0$$.slice();
function $renderInteractionOverlay$$module$src$service$video$autoplay$$($elOrDoc$$){var $html$$=$htmlFor$$module$src$static_template$$($elOrDoc$$);return $html$$($$jscomp$templatelit$0$$)}
function $renderIcon$$module$src$service$video$autoplay$$($win$jscomp$53$$,$elOrDoc$jscomp$1_i$jscomp$20$$){var $icon$$=$htmlFor$$module$src$static_template$$($elOrDoc$jscomp$1_i$jscomp$20$$)($$jscomp$templatelit$1$$),$firstCol$$=$icon$$.firstElementChild;for($elOrDoc$jscomp$1_i$jscomp$20$$=0;4>$elOrDoc$jscomp$1_i$jscomp$20$$;$elOrDoc$jscomp$1_i$jscomp$20$$++){for(var $col$$=$firstCol$$.cloneNode(!0),$fillers$$=$col$$.children,$j$$=0;$j$$<$fillers$$.length;$j$$++){var $filler$$=$fillers$$[$j$$];$filler$$.classList.add("amp-video-eq-"+
($elOrDoc$jscomp$1_i$jscomp$20$$+1)+"-"+($j$$+1))}$icon$$.appendChild($col$$)}$removeElement$$module$src$dom$$($firstCol$$);$getService$$module$src$service$$($win$jscomp$53$$,"platform").isIos()&&$icon$$.setAttribute("unpausable","");return $icon$$};function $VideoManager$$module$src$service$video_manager_impl$$($ampdoc$jscomp$12$$){var $$jscomp$this$jscomp$2$$=this;this.ampdoc=$ampdoc$jscomp$12$$;this.installAutoplayStyles=$once$$module$src$utils$function$$(function(){var $ampdoc$jscomp$12$$=$$jscomp$this$jscomp$2$$.ampdoc.getHeadNode(),$JSCompiler_styleMap$jscomp$inline_249_JSCompiler_transformer$jscomp$inline_243$$=$ampdoc$jscomp$12$$.__AMP_CSS_TR;var $JSCompiler_after$jscomp$inline_255_JSCompiler_inline_result$jscomp$234$$=$JSCompiler_styleMap$jscomp$inline_249_JSCompiler_transformer$jscomp$inline_243$$?
$JSCompiler_styleMap$jscomp$inline_249_JSCompiler_transformer$jscomp$inline_243$$("i-amphtml-video-mask{display:block;z-index:1}.amp-video-eq{display:none}.i-amphtml-video-component:not(amp-video) .amp-video-eq,amp-story .amp-video-eq,amp-video[controls] .amp-video-eq{display:-webkit-box;display:-ms-flexbox;display:flex}[noaudio] .amp-video-eq{display:none!important}.amp-video-eq{pointer-events:none!important;-webkit-box-align:end;-ms-flex-align:end;align-items:flex-end;bottom:7px;height:12px;opacity:0.8;overflow:hidden;position:absolute;right:7px;width:20px;z-index:1}.amp-video-eq .amp-video-eq-col{-webkit-box-flex:1;-ms-flex:1;flex:1;height:100%;margin-right:1px;position:relative}.amp-video-eq .amp-video-eq-col div{-webkit-animation-name:amp-video-eq-animation;animation-name:amp-video-eq-animation;-webkit-animation-timing-function:linear;animation-timing-function:linear;-webkit-animation-iteration-count:infinite;animation-iteration-count:infinite;-webkit-animation-direction:alternate;animation-direction:alternate;background-color:#fafafa;height:100%;position:absolute;width:100%;will-change:transform;-webkit-animation-play-state:paused;animation-play-state:paused}.amp-video-eq[unpausable] .amp-video-eq-col div{-webkit-animation-name:none;animation-name:none}.amp-video-eq[unpausable].amp-video-eq-play .amp-video-eq-col div{-webkit-animation-name:amp-video-eq-animation;animation-name:amp-video-eq-animation}.amp-video-eq.amp-video-eq-play .amp-video-eq-col div{-webkit-animation-play-state:running;animation-play-state:running}.amp-video-eq-1-1{-webkit-animation-duration:0.3s;animation-duration:0.3s}.amp-video-eq-1-1,.amp-video-eq-1-2{-webkit-transform:translateY(60%);transform:translateY(60%)}.amp-video-eq-1-2{-webkit-animation-duration:0.45s;animation-duration:0.45s}.amp-video-eq-2-1{-webkit-animation-duration:0.5s;animation-duration:0.5s}.amp-video-eq-2-1,.amp-video-eq-2-2{-webkit-transform:translateY(30%);transform:translateY(30%)}.amp-video-eq-2-2{-webkit-animation-duration:0.4s;animation-duration:0.4s}.amp-video-eq-3-1{-webkit-animation-duration:0.3s;animation-duration:0.3s}.amp-video-eq-3-1,.amp-video-eq-3-2{-webkit-transform:translateY(70%);transform:translateY(70%)}.amp-video-eq-3-2{-webkit-animation-duration:0.35s;animation-duration:0.35s}.amp-video-eq-4-1{-webkit-animation-duration:0.4s;animation-duration:0.4s}.amp-video-eq-4-1,.amp-video-eq-4-2{-webkit-transform:translateY(50%);transform:translateY(50%)}.amp-video-eq-4-2{-webkit-animation-duration:0.25s;animation-duration:0.25s}@-webkit-keyframes amp-video-eq-animation{0%{-webkit-transform:translateY(100%);transform:translateY(100%)}to{-webkit-transform:translateY(0);transform:translateY(0)}}@keyframes amp-video-eq-animation{0%{-webkit-transform:translateY(100%);transform:translateY(100%)}to{-webkit-transform:translateY(0);transform:translateY(0)}}\n/*# sourceURL=/css/video-autoplay.css*/"):
"i-amphtml-video-mask{display:block;z-index:1}.amp-video-eq{display:none}.i-amphtml-video-component:not(amp-video) .amp-video-eq,amp-story .amp-video-eq,amp-video[controls] .amp-video-eq{display:-webkit-box;display:-ms-flexbox;display:flex}[noaudio] .amp-video-eq{display:none!important}.amp-video-eq{pointer-events:none!important;-webkit-box-align:end;-ms-flex-align:end;align-items:flex-end;bottom:7px;height:12px;opacity:0.8;overflow:hidden;position:absolute;right:7px;width:20px;z-index:1}.amp-video-eq .amp-video-eq-col{-webkit-box-flex:1;-ms-flex:1;flex:1;height:100%;margin-right:1px;position:relative}.amp-video-eq .amp-video-eq-col div{-webkit-animation-name:amp-video-eq-animation;animation-name:amp-video-eq-animation;-webkit-animation-timing-function:linear;animation-timing-function:linear;-webkit-animation-iteration-count:infinite;animation-iteration-count:infinite;-webkit-animation-direction:alternate;animation-direction:alternate;background-color:#fafafa;height:100%;position:absolute;width:100%;will-change:transform;-webkit-animation-play-state:paused;animation-play-state:paused}.amp-video-eq[unpausable] .amp-video-eq-col div{-webkit-animation-name:none;animation-name:none}.amp-video-eq[unpausable].amp-video-eq-play .amp-video-eq-col div{-webkit-animation-name:amp-video-eq-animation;animation-name:amp-video-eq-animation}.amp-video-eq.amp-video-eq-play .amp-video-eq-col div{-webkit-animation-play-state:running;animation-play-state:running}.amp-video-eq-1-1{-webkit-animation-duration:0.3s;animation-duration:0.3s}.amp-video-eq-1-1,.amp-video-eq-1-2{-webkit-transform:translateY(60%);transform:translateY(60%)}.amp-video-eq-1-2{-webkit-animation-duration:0.45s;animation-duration:0.45s}.amp-video-eq-2-1{-webkit-animation-duration:0.5s;animation-duration:0.5s}.amp-video-eq-2-1,.amp-video-eq-2-2{-webkit-transform:translateY(30%);transform:translateY(30%)}.amp-video-eq-2-2{-webkit-animation-duration:0.4s;animation-duration:0.4s}.amp-video-eq-3-1{-webkit-animation-duration:0.3s;animation-duration:0.3s}.amp-video-eq-3-1,.amp-video-eq-3-2{-webkit-transform:translateY(70%);transform:translateY(70%)}.amp-video-eq-3-2{-webkit-animation-duration:0.35s;animation-duration:0.35s}.amp-video-eq-4-1{-webkit-animation-duration:0.4s;animation-duration:0.4s}.amp-video-eq-4-1,.amp-video-eq-4-2{-webkit-transform:translateY(50%);transform:translateY(50%)}.amp-video-eq-4-2{-webkit-animation-duration:0.25s;animation-duration:0.25s}@-webkit-keyframes amp-video-eq-animation{0%{-webkit-transform:translateY(100%);transform:translateY(100%)}to{-webkit-transform:translateY(0);transform:translateY(0)}}@keyframes amp-video-eq-animation{0%{-webkit-transform:translateY(100%);transform:translateY(100%)}to{-webkit-transform:translateY(0);transform:translateY(0)}}\n/*# sourceURL=/css/video-autoplay.css*/";
($JSCompiler_styleMap$jscomp$inline_249_JSCompiler_transformer$jscomp$inline_243$$=$ampdoc$jscomp$12$$.__AMP_CSS_SM)||($JSCompiler_styleMap$jscomp$inline_249_JSCompiler_transformer$jscomp$inline_243$$=$ampdoc$jscomp$12$$.__AMP_CSS_SM=$map$$module$src$utils$object$$());var $JSCompiler_existing$jscomp$inline_252_JSCompiler_style$jscomp$inline_253$$=$getExistingStyleElement$$module$src$style_installer$$($ampdoc$jscomp$12$$,$JSCompiler_styleMap$jscomp$inline_249_JSCompiler_transformer$jscomp$inline_243$$,
"amp-extension=amp-video-autoplay");$JSCompiler_existing$jscomp$inline_252_JSCompiler_style$jscomp$inline_253$$?$JSCompiler_existing$jscomp$inline_252_JSCompiler_style$jscomp$inline_253$$.textContent!==$JSCompiler_after$jscomp$inline_255_JSCompiler_inline_result$jscomp$234$$&&($JSCompiler_existing$jscomp$inline_252_JSCompiler_style$jscomp$inline_253$$.textContent=$JSCompiler_after$jscomp$inline_255_JSCompiler_inline_result$jscomp$234$$):($JSCompiler_existing$jscomp$inline_252_JSCompiler_style$jscomp$inline_253$$=
($ampdoc$jscomp$12$$.ownerDocument||$ampdoc$jscomp$12$$).createElement("style"),$JSCompiler_existing$jscomp$inline_252_JSCompiler_style$jscomp$inline_253$$.textContent=$JSCompiler_after$jscomp$inline_255_JSCompiler_inline_result$jscomp$234$$,$JSCompiler_existing$jscomp$inline_252_JSCompiler_style$jscomp$inline_253$$.setAttribute("amp-extension","amp-video-autoplay"),$JSCompiler_after$jscomp$inline_255_JSCompiler_inline_result$jscomp$234$$=$getExistingStyleElement$$module$src$style_installer$$($ampdoc$jscomp$12$$,
$JSCompiler_styleMap$jscomp$inline_249_JSCompiler_transformer$jscomp$inline_243$$,"amp-runtime"),$ampdoc$jscomp$12$$.insertBefore($JSCompiler_existing$jscomp$inline_252_JSCompiler_style$jscomp$inline_253$$,$JSCompiler_after$jscomp$inline_255_JSCompiler_inline_result$jscomp$234$$?$JSCompiler_after$jscomp$inline_255_JSCompiler_inline_result$jscomp$234$$.nextSibling:$ampdoc$jscomp$12$$.firstChild),$JSCompiler_styleMap$jscomp$inline_249_JSCompiler_transformer$jscomp$inline_243$$["amp-extension=amp-video-autoplay"]=
$JSCompiler_existing$jscomp$inline_252_JSCompiler_style$jscomp$inline_253$$)});this.$viewport_$=$getServiceForDoc$$module$src$service$$(this.ampdoc,"viewport");this.$entries_$=null;this.$scrollListenerInstalled_$=!1;this.$timer_$=$getService$$module$src$service$$($ampdoc$jscomp$12$$.win,"timer");this.$actions_$=$getExistingServiceForDocInEmbedScope$$module$src$service$$($ampdoc$jscomp$12$$.getHeadNode(),"action");this.$boundSecondsPlaying_$=function(){for(var $ampdoc$jscomp$12$$=0;$ampdoc$jscomp$12$$<
$$jscomp$this$jscomp$2$$.$entries_$.length;$ampdoc$jscomp$12$$++){var $JSCompiler_entry$jscomp$inline_72$$=$$jscomp$this$jscomp$2$$.$entries_$[$ampdoc$jscomp$12$$];if("paused"!==$JSCompiler_entry$jscomp$inline_72$$.getPlayingState()){$analyticsEvent$$module$src$service$video_manager_impl$$($JSCompiler_entry$jscomp$inline_72$$,"video-seconds-played");var $JSCompiler_currentTime$jscomp$inline_180_JSCompiler_event$jscomp$inline_183$$=$JSCompiler_entry$jscomp$inline_72$$.video.getCurrentTime(),$JSCompiler_duration$jscomp$inline_181$$=
$JSCompiler_entry$jscomp$inline_72$$.video.getDuration();$isFiniteNumber$$module$src$types$$($JSCompiler_currentTime$jscomp$inline_180_JSCompiler_event$jscomp$inline_183$$)&&$isFiniteNumber$$module$src$types$$($JSCompiler_duration$jscomp$inline_181$$)&&0<$JSCompiler_duration$jscomp$inline_181$$&&($JSCompiler_currentTime$jscomp$inline_180_JSCompiler_event$jscomp$inline_183$$=$createCustomEvent$$module$src$event_helper$$($$jscomp$this$jscomp$2$$.ampdoc.win,"video-manager.timeUpdate",$dict$$module$src$utils$object$$({time:$JSCompiler_currentTime$jscomp$inline_180_JSCompiler_event$jscomp$inline_183$$,
percent:$JSCompiler_currentTime$jscomp$inline_180_JSCompiler_event$jscomp$inline_183$$/$JSCompiler_duration$jscomp$inline_181$$})),$$jscomp$this$jscomp$2$$.$actions_$.trigger($JSCompiler_entry$jscomp$inline_72$$.video.element,"timeUpdate",$JSCompiler_currentTime$jscomp$inline_180_JSCompiler_event$jscomp$inline_183$$,1))}}$$jscomp$this$jscomp$2$$.$timer_$.delay($$jscomp$this$jscomp$2$$.$boundSecondsPlaying_$,1E3)};this.$getAutoFullscreenManager_$=$once$$module$src$utils$function$$(function(){return new $AutoFullscreenManager$$module$src$service$video_manager_impl$$($$jscomp$this$jscomp$2$$.ampdoc,
$$jscomp$this$jscomp$2$$)});this.$timer_$.delay(this.$boundSecondsPlaying_$,1E3)}$JSCompiler_prototypeAlias$$=$VideoManager$$module$src$service$video_manager_impl$$.prototype;$JSCompiler_prototypeAlias$$.dispose=function(){if(this.$entries_$)for(var $i$jscomp$21$$=0;$i$jscomp$21$$<this.$entries_$.length;$i$jscomp$21$$++){var $entry$$=this.$entries_$[$i$jscomp$21$$];$entry$$.dispose()}};
$JSCompiler_prototypeAlias$$.register=function($video$jscomp$2$$){$JSCompiler_StaticMethods_registerCommonActions_$$($video$jscomp$2$$);if($video$jscomp$2$$.supportsPlatform()){this.$entries_$=this.$entries_$||[];var $element$jscomp$71_entry$jscomp$3$$=new $VideoEntry$$module$src$service$video_manager_impl$$(this,$video$jscomp$2$$);$JSCompiler_StaticMethods_maybeInstallVisibilityObserver_$$(this,$element$jscomp$71_entry$jscomp$3$$);this.$entries_$.push($element$jscomp$71_entry$jscomp$3$$);$element$jscomp$71_entry$jscomp$3$$=
$element$jscomp$71_entry$jscomp$3$$.video.element;$element$jscomp$71_entry$jscomp$3$$.dispatchCustomEvent("registered");$element$jscomp$71_entry$jscomp$3$$.classList.add("i-amphtml-video-component");var $signals$$=$video$jscomp$2$$.signals();$signals$$.signal("registered");$element$jscomp$71_entry$jscomp$3$$.classList.add("i-amphtml-video-interface")}};
function $JSCompiler_StaticMethods_registerCommonActions_$$($video$jscomp$3$$){function $registerAction$$($registerAction$$,$fn$jscomp$4$$){$video$jscomp$3$$.registerAction($registerAction$$,function(){$video$jscomp$3$$.signals().signal("user-interacted");$fn$jscomp$4$$()},$trust$$)}var $trust$$=1;$registerAction$$("play",function(){return $video$jscomp$3$$.play(!1)});$registerAction$$("pause",function(){return $video$jscomp$3$$.pause()});$registerAction$$("mute",function(){return $video$jscomp$3$$.mute()});
$registerAction$$("unmute",function(){return $video$jscomp$3$$.unmute()});$registerAction$$("fullscreen",function(){return $video$jscomp$3$$.fullscreenEnter()})}
function $JSCompiler_StaticMethods_maybeInstallVisibilityObserver_$$($JSCompiler_StaticMethods_maybeInstallVisibilityObserver_$self$$,$entry$jscomp$4$$){var $element$jscomp$72$$=$entry$jscomp$4$$.video.element;$listen$$module$src$event_helper$$($element$jscomp$72$$,"amp:video:visibility",function($JSCompiler_StaticMethods_maybeInstallVisibilityObserver_$self$$){var $element$jscomp$72$$=$JSCompiler_StaticMethods_maybeInstallVisibilityObserver_$self$$.data;$element$jscomp$72$$&&1==$element$jscomp$72$$.visible?
$entry$jscomp$4$$.updateVisibility(!0):$entry$jscomp$4$$.updateVisibility()});$listen$$module$src$event_helper$$($element$jscomp$72$$,"reloaded",function(){$entry$jscomp$4$$.videoLoaded()});if(!$JSCompiler_StaticMethods_maybeInstallVisibilityObserver_$self$$.$scrollListenerInstalled_$){var $scrollListener$$=function(){for(var $entry$jscomp$4$$=0;$entry$jscomp$4$$<$JSCompiler_StaticMethods_maybeInstallVisibilityObserver_$self$$.$entries_$.length;$entry$jscomp$4$$++)$JSCompiler_StaticMethods_maybeInstallVisibilityObserver_$self$$.$entries_$[$entry$jscomp$4$$].updateVisibility()};
$JSCompiler_StaticMethods_maybeInstallVisibilityObserver_$self$$.$viewport_$.onScroll($scrollListener$$);$JSCompiler_StaticMethods_maybeInstallVisibilityObserver_$self$$.$viewport_$.onChanged($scrollListener$$);$JSCompiler_StaticMethods_maybeInstallVisibilityObserver_$self$$.$scrollListenerInstalled_$=!0}}
function $JSCompiler_StaticMethods_getEntryForVideo_$$($JSCompiler_StaticMethods_getEntryForVideo_$self$$,$video$jscomp$4$$){for(var $i$jscomp$24$$=0;$i$jscomp$24$$<$JSCompiler_StaticMethods_getEntryForVideo_$self$$.$entries_$.length;$i$jscomp$24$$++)if($JSCompiler_StaticMethods_getEntryForVideo_$self$$.$entries_$[$i$jscomp$24$$].video===$video$jscomp$4$$)return $JSCompiler_StaticMethods_getEntryForVideo_$self$$.$entries_$[$i$jscomp$24$$];$dev$$module$src$log$$().error("video-manager","video is not registered to this video manager");
return null}
$JSCompiler_prototypeAlias$$.getAnalyticsDetails=function($videoElement$$){var $JSCompiler_i$jscomp$inline_78_JSCompiler_inline_result$jscomp$30_entry$jscomp$6$$;a:{for($JSCompiler_i$jscomp$inline_78_JSCompiler_inline_result$jscomp$30_entry$jscomp$6$$=0;$JSCompiler_i$jscomp$inline_78_JSCompiler_inline_result$jscomp$30_entry$jscomp$6$$<this.$entries_$.length;$JSCompiler_i$jscomp$inline_78_JSCompiler_inline_result$jscomp$30_entry$jscomp$6$$++){var $JSCompiler_entry$jscomp$inline_79$$=this.$entries_$[$JSCompiler_i$jscomp$inline_78_JSCompiler_inline_result$jscomp$30_entry$jscomp$6$$];if($JSCompiler_entry$jscomp$inline_79$$.video.element===
$videoElement$$){$JSCompiler_i$jscomp$inline_78_JSCompiler_inline_result$jscomp$30_entry$jscomp$6$$=$JSCompiler_entry$jscomp$inline_79$$;break a}}$dev$$module$src$log$$().error("video-manager","video is not registered to this video manager");$JSCompiler_i$jscomp$inline_78_JSCompiler_inline_result$jscomp$30_entry$jscomp$6$$=null}return $JSCompiler_i$jscomp$inline_78_JSCompiler_inline_result$jscomp$30_entry$jscomp$6$$?$JSCompiler_i$jscomp$inline_78_JSCompiler_inline_result$jscomp$30_entry$jscomp$6$$.getAnalyticsDetails():
Promise.resolve()};$JSCompiler_prototypeAlias$$.getPlayingState=function($video$jscomp$5$$){return $JSCompiler_StaticMethods_getEntryForVideo_$$(this,$video$jscomp$5$$).getPlayingState()};$JSCompiler_prototypeAlias$$.isMuted=function($video$jscomp$6$$){return $JSCompiler_StaticMethods_getEntryForVideo_$$(this,$video$jscomp$6$$).isMuted()};$JSCompiler_prototypeAlias$$.userInteracted=function($video$jscomp$7$$){return $JSCompiler_StaticMethods_getEntryForVideo_$$(this,$video$jscomp$7$$).userInteracted()};
$JSCompiler_prototypeAlias$$.registerForAutoFullscreen=function($entry$jscomp$7$$){this.$getAutoFullscreenManager_$().register($entry$jscomp$7$$)};$JSCompiler_prototypeAlias$$.$getAutoFullscreenManagerForTesting_$=function(){return this.$getAutoFullscreenManager_$()};
function $VideoEntry$$module$src$service$video_manager_impl$$($manager$$,$video$jscomp$8$$){var $$jscomp$this$jscomp$4$$=this;this.$manager_$=$manager$$;this.$ampdoc_$=$manager$$.ampdoc;this.video=$video$jscomp$8$$;this.$allowAutoplay_$=!0;this.$isVisible_$=this.$isPlaying_$=this.$loaded_$=!1;this.$actionSessionManager_$=new $VideoSessionManager$$module$src$service$video_session_manager$$;this.$actionSessionManager_$.onSessionEnd(function(){return $analyticsEvent$$module$src$service$video_manager_impl$$($$jscomp$this$jscomp$4$$,
"video-session")});this.$visibilitySessionManager_$=new $VideoSessionManager$$module$src$service$video_session_manager$$;this.$visibilitySessionManager_$.onSessionEnd(function(){return $analyticsEvent$$module$src$service$video_manager_impl$$($$jscomp$this$jscomp$4$$,"video-session-visible")});this.$supportsAutoplay_$=function(){var $manager$$=$$jscomp$this$jscomp$4$$.$ampdoc_$.win,$video$jscomp$8$$=$manager$$||self;if($video$jscomp$8$$.AMP_MODE)$video$jscomp$8$$=$video$jscomp$8$$.AMP_MODE;else{var $JSCompiler_AMP_CONFIG$jscomp$inline_186_JSCompiler_singlePassType$jscomp$inline_193$$=
self.AMP_CONFIG||{},$JSCompiler_runningTests$jscomp$inline_190$$=!!$JSCompiler_AMP_CONFIG$jscomp$inline_186_JSCompiler_singlePassType$jscomp$inline_193$$.test||!(!$video$jscomp$8$$.AMP_TEST&&!$video$jscomp$8$$.__karma__),$JSCompiler_isLocalDev$jscomp$inline_191$$=!!$JSCompiler_AMP_CONFIG$jscomp$inline_186_JSCompiler_singlePassType$jscomp$inline_193$$.localDev||$JSCompiler_runningTests$jscomp$inline_190$$,$JSCompiler_hashQuery$jscomp$inline_192$$=$parseQueryString_$$module$src$url_parse_query_string$$($video$jscomp$8$$.location.originalHash||
$video$jscomp$8$$.location.hash);$JSCompiler_AMP_CONFIG$jscomp$inline_186_JSCompiler_singlePassType$jscomp$inline_193$$=$JSCompiler_AMP_CONFIG$jscomp$inline_186_JSCompiler_singlePassType$jscomp$inline_193$$.spt;var $JSCompiler_searchQuery$jscomp$inline_194$$=$parseQueryString_$$module$src$url_parse_query_string$$($video$jscomp$8$$.location.search);$rtvVersion$$module$src$mode$$||($rtvVersion$$module$src$mode$$=$JSCompiler_isLocalDev$jscomp$inline_191$$?"1904281823091":$video$jscomp$8$$.AMP_CONFIG&&
$video$jscomp$8$$.AMP_CONFIG.v?$video$jscomp$8$$.AMP_CONFIG.v:"011904281823091");$video$jscomp$8$$=$video$jscomp$8$$.AMP_MODE={localDev:$JSCompiler_isLocalDev$jscomp$inline_191$$,development:!("1"!=$JSCompiler_hashQuery$jscomp$inline_192$$.development&&!$video$jscomp$8$$.AMP_DEV_MODE),examiner:"2"==$JSCompiler_hashQuery$jscomp$inline_192$$.development,filter:$JSCompiler_hashQuery$jscomp$inline_192$$.filter,geoOverride:$JSCompiler_hashQuery$jscomp$inline_192$$["amp-geo"],minified:!0,lite:void 0!=$JSCompiler_searchQuery$jscomp$inline_194$$.amp_lite,
test:$JSCompiler_runningTests$jscomp$inline_190$$,log:$JSCompiler_hashQuery$jscomp$inline_192$$.log,version:"1904281823091",rtvVersion:$rtvVersion$$module$src$mode$$,singlePassType:$JSCompiler_AMP_CONFIG$jscomp$inline_186_JSCompiler_singlePassType$jscomp$inline_193$$}}$video$jscomp$8$$=$video$jscomp$8$$.lite;$isAutoplaySupported$$module$src$utils$video$$||($isAutoplaySupported$$module$src$utils$video$$=$once$$module$src$utils$function$$($isAutoplaySupportedImpl$$module$src$utils$video$$));return $isAutoplaySupported$$module$src$utils$video$$($manager$$,
$video$jscomp$8$$)};this.$getAnalyticsPercentageTracker_$=$once$$module$src$utils$function$$(function(){return new $AnalyticsPercentageTracker$$module$src$service$video_manager_impl$$($$jscomp$this$jscomp$4$$.$ampdoc_$.win,$$jscomp$this$jscomp$4$$)});this.$pauseCalledByAutoplay_$=this.$playCalledByAutoplay_$=!1;this.$internalElement_$=null;this.$muted_$=!1;(this.hasAutoplay=$video$jscomp$8$$.element.hasAttribute("autoplay"))&&this.$manager_$.installAutoplayStyles();this.$metadata_$=$EMPTY_METADATA$$module$src$mediasession_helper$$;
this.$boundMediasessionPlay_$=function(){$$jscomp$this$jscomp$4$$.video.play(!1)};this.$boundMediasessionPause_$=function(){$$jscomp$this$jscomp$4$$.video.pause()};$listenOncePromise$$module$src$event_helper$$($video$jscomp$8$$.element).then(function(){return $$jscomp$this$jscomp$4$$.videoLoaded()});$listen$$module$src$event_helper$$($video$jscomp$8$$.element,"pause",function(){$analyticsEvent$$module$src$service$video_manager_impl$$($$jscomp$this$jscomp$4$$,"video-pause");$$jscomp$this$jscomp$4$$.$isPlaying_$=
!1;$$jscomp$this$jscomp$4$$.$pauseCalledByAutoplay_$?$$jscomp$this$jscomp$4$$.$pauseCalledByAutoplay_$=!1:$$jscomp$this$jscomp$4$$.$actionSessionManager_$.endSession()});$listen$$module$src$event_helper$$($video$jscomp$8$$.element,"playing",function(){$$jscomp$this$jscomp$4$$.$isPlaying_$=!0;"playing_manual"==$$jscomp$this$jscomp$4$$.getPlayingState()&&$$jscomp$this$jscomp$4$$.$firstPlayEventOrNoop_$();var $manager$$=$$jscomp$this$jscomp$4$$.video,$video$jscomp$8$$=$manager$$.element;if(!$manager$$.preimplementsMediaSessionAPI()&&
!$video$jscomp$8$$.classList.contains("i-amphtml-disable-mediasession")){$manager$$=$$jscomp$this$jscomp$4$$.$ampdoc_$.win;var $JSCompiler_metadata$jscomp$inline_199$$=$$jscomp$this$jscomp$4$$.$metadata_$,$JSCompiler_playHandler$jscomp$inline_200$$=$$jscomp$this$jscomp$4$$.$boundMediasessionPlay_$,$JSCompiler_pauseHandler$jscomp$inline_201$$=$$jscomp$this$jscomp$4$$.$boundMediasessionPause_$,$JSCompiler_navigator$jscomp$inline_202$$=$manager$$.navigator;"mediaSession"in $JSCompiler_navigator$jscomp$inline_202$$&&
$manager$$.MediaMetadata&&($JSCompiler_navigator$jscomp$inline_202$$.mediaSession.metadata=new $manager$$.MediaMetadata($EMPTY_METADATA$$module$src$mediasession_helper$$),$validateMetadata$$module$src$mediasession_helper$$($video$jscomp$8$$,$JSCompiler_metadata$jscomp$inline_199$$),$JSCompiler_navigator$jscomp$inline_202$$.mediaSession.metadata=new $manager$$.MediaMetadata($JSCompiler_metadata$jscomp$inline_199$$),$JSCompiler_navigator$jscomp$inline_202$$.mediaSession.setActionHandler("play",$JSCompiler_playHandler$jscomp$inline_200$$),
$JSCompiler_navigator$jscomp$inline_202$$.mediaSession.setActionHandler("pause",$JSCompiler_pauseHandler$jscomp$inline_201$$))}$$jscomp$this$jscomp$4$$.$actionSessionManager_$.beginSession();$$jscomp$this$jscomp$4$$.$isVisible_$&&$$jscomp$this$jscomp$4$$.$visibilitySessionManager_$.beginSession();$analyticsEvent$$module$src$service$video_manager_impl$$($$jscomp$this$jscomp$4$$,"video-play")});$listen$$module$src$event_helper$$($video$jscomp$8$$.element,"muted",function(){return $$jscomp$this$jscomp$4$$.$muted_$=
!0});$listen$$module$src$event_helper$$($video$jscomp$8$$.element,"unmuted",function(){return $$jscomp$this$jscomp$4$$.$muted_$=!1});$listen$$module$src$event_helper$$($video$jscomp$8$$.element,"ended",function(){$analyticsEvent$$module$src$service$video_manager_impl$$($$jscomp$this$jscomp$4$$,"video-ended")});$listen$$module$src$event_helper$$($video$jscomp$8$$.element,"video-hosted-custom",function($manager$$){$manager$$=$manager$$.data;var $video$jscomp$8$$=$manager$$.vars;$JSCompiler_StaticMethods_logCustomAnalytics_$$($$jscomp$this$jscomp$4$$,
$manager$$.eventType,$video$jscomp$8$$)});$video$jscomp$8$$.signals().whenSignal("registered").then(function(){var $manager$$=$$jscomp$this$jscomp$4$$.video.element;($$jscomp$this$jscomp$4$$.video.preimplementsAutoFullscreen()||!$manager$$.hasAttribute("rotate-to-fullscreen")?0:$userAssert$$module$src$log$$($$jscomp$this$jscomp$4$$.video.isInteractive(),"Only interactive videos are allowed to enter fullscreen on rotate. Set the `controls` attribute on %s to enable.",$manager$$))&&$$jscomp$this$jscomp$4$$.$manager_$.registerForAutoFullscreen($$jscomp$this$jscomp$4$$);
$$jscomp$this$jscomp$4$$.updateVisibility();$$jscomp$this$jscomp$4$$.hasAutoplay&&$JSCompiler_StaticMethods_autoplayVideoBuilt_$$($$jscomp$this$jscomp$4$$)});this.$firstPlayEventOrNoop_$=$once$$module$src$utils$function$$(function(){var $manager$$="firstPlay",$video$jscomp$8$$=$createCustomEvent$$module$src$event_helper$$($$jscomp$this$jscomp$4$$.$ampdoc_$.win,$manager$$,$dict$$module$src$utils$object$$({})),$element$jscomp$74$$=$$jscomp$this$jscomp$4$$.video.element,$actions$$=$getExistingServiceForDocInEmbedScope$$module$src$service$$($element$jscomp$74$$,
"action");$actions$$.trigger($element$jscomp$74$$,$manager$$,$video$jscomp$8$$,1)});$JSCompiler_StaticMethods_listenForAutoplayDelegation_$$(this)}$JSCompiler_prototypeAlias$$=$VideoEntry$$module$src$service$video_manager_impl$$.prototype;$JSCompiler_prototypeAlias$$.dispose=function(){this.$getAnalyticsPercentageTracker_$().stop()};
function $JSCompiler_StaticMethods_logCustomAnalytics_$$($JSCompiler_StaticMethods_logCustomAnalytics_$self$$,$eventType$jscomp$8$$,$vars$jscomp$1$$){var $prefixedVars$$={};Object.keys($vars$jscomp$1$$).forEach(function($JSCompiler_StaticMethods_logCustomAnalytics_$self$$){$prefixedVars$$["custom_"+$JSCompiler_StaticMethods_logCustomAnalytics_$self$$]=$vars$jscomp$1$$[$JSCompiler_StaticMethods_logCustomAnalytics_$self$$]});$analyticsEvent$$module$src$service$video_manager_impl$$($JSCompiler_StaticMethods_logCustomAnalytics_$self$$,
$eventType$jscomp$8$$,$prefixedVars$$)}
function $JSCompiler_StaticMethods_listenForAutoplayDelegation_$$($JSCompiler_StaticMethods_listenForAutoplayDelegation_$self$$){$JSCompiler_StaticMethods_listenForAutoplayDelegation_$self$$.video.signals().whenSignal("autoplay-delegated").then(function(){$JSCompiler_StaticMethods_listenForAutoplayDelegation_$self$$.$allowAutoplay_$=!1;$JSCompiler_StaticMethods_listenForAutoplayDelegation_$self$$.$isPlaying_$&&$JSCompiler_StaticMethods_listenForAutoplayDelegation_$self$$.video.pause()})}
$JSCompiler_prototypeAlias$$.isMuted=function(){return this.$muted_$};
$JSCompiler_prototypeAlias$$.videoLoaded=function(){this.$loaded_$=!0;this.$internalElement_$=this.video.element.querySelector("video, iframe");if(!this.video.preimplementsMediaSessionAPI()){this.video.getMetadata()&&(this.$metadata_$=$map$$module$src$utils$object$$(this.video.getMetadata()));var $JSCompiler_doc$jscomp$inline_98_JSCompiler_title$jscomp$inline_100$$=this.$ampdoc_$.win.document;if(!this.$metadata_$.artwork||0==this.$metadata_$.artwork.length){var $JSCompiler_linkTag$jscomp$inline_211_JSCompiler_metaTag$jscomp$inline_208_JSCompiler_posterUrl$jscomp$inline_99_JSCompiler_temp$jscomp$158_JSCompiler_temp$jscomp$159$$;($JSCompiler_linkTag$jscomp$inline_211_JSCompiler_metaTag$jscomp$inline_208_JSCompiler_posterUrl$jscomp$inline_99_JSCompiler_temp$jscomp$158_JSCompiler_temp$jscomp$159$$=
$parseSchemaImage$$module$src$mediasession_helper$$($JSCompiler_doc$jscomp$inline_98_JSCompiler_title$jscomp$inline_100$$))||($JSCompiler_linkTag$jscomp$inline_211_JSCompiler_metaTag$jscomp$inline_208_JSCompiler_posterUrl$jscomp$inline_99_JSCompiler_temp$jscomp$158_JSCompiler_temp$jscomp$159$$=($JSCompiler_linkTag$jscomp$inline_211_JSCompiler_metaTag$jscomp$inline_208_JSCompiler_posterUrl$jscomp$inline_99_JSCompiler_temp$jscomp$158_JSCompiler_temp$jscomp$159$$=$JSCompiler_doc$jscomp$inline_98_JSCompiler_title$jscomp$inline_100$$.querySelector('meta[property="og:image"]'))?
$JSCompiler_linkTag$jscomp$inline_211_JSCompiler_metaTag$jscomp$inline_208_JSCompiler_posterUrl$jscomp$inline_99_JSCompiler_temp$jscomp$158_JSCompiler_temp$jscomp$159$$.getAttribute("content"):void 0);$JSCompiler_linkTag$jscomp$inline_211_JSCompiler_metaTag$jscomp$inline_208_JSCompiler_posterUrl$jscomp$inline_99_JSCompiler_temp$jscomp$158_JSCompiler_temp$jscomp$159$$||($JSCompiler_linkTag$jscomp$inline_211_JSCompiler_metaTag$jscomp$inline_208_JSCompiler_posterUrl$jscomp$inline_99_JSCompiler_temp$jscomp$158_JSCompiler_temp$jscomp$159$$=
($JSCompiler_linkTag$jscomp$inline_211_JSCompiler_metaTag$jscomp$inline_208_JSCompiler_posterUrl$jscomp$inline_99_JSCompiler_temp$jscomp$158_JSCompiler_temp$jscomp$159$$=$JSCompiler_doc$jscomp$inline_98_JSCompiler_title$jscomp$inline_100$$.querySelector('link[rel="shortcut icon"]')||$JSCompiler_doc$jscomp$inline_98_JSCompiler_title$jscomp$inline_100$$.querySelector('link[rel="icon"]'))?$JSCompiler_linkTag$jscomp$inline_211_JSCompiler_metaTag$jscomp$inline_208_JSCompiler_posterUrl$jscomp$inline_99_JSCompiler_temp$jscomp$158_JSCompiler_temp$jscomp$159$$.getAttribute("href"):
void 0);$JSCompiler_linkTag$jscomp$inline_211_JSCompiler_metaTag$jscomp$inline_208_JSCompiler_posterUrl$jscomp$inline_99_JSCompiler_temp$jscomp$158_JSCompiler_temp$jscomp$159$$&&(this.$metadata_$.artwork=[{src:$JSCompiler_linkTag$jscomp$inline_211_JSCompiler_metaTag$jscomp$inline_208_JSCompiler_posterUrl$jscomp$inline_99_JSCompiler_temp$jscomp$158_JSCompiler_temp$jscomp$159$$}])}!this.$metadata_$.title&&($JSCompiler_doc$jscomp$inline_98_JSCompiler_title$jscomp$inline_100$$=this.video.element.getAttribute("title")||
this.video.element.getAttribute("aria-label")||this.$internalElement_$.getAttribute("title")||this.$internalElement_$.getAttribute("aria-label")||$JSCompiler_doc$jscomp$inline_98_JSCompiler_title$jscomp$inline_100$$.title)&&(this.$metadata_$.title=$JSCompiler_doc$jscomp$inline_98_JSCompiler_title$jscomp$inline_100$$)}this.$getAnalyticsPercentageTracker_$().start();this.updateVisibility();this.$isVisible_$&&$JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$$(this)};
function $JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$$($JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$){$getServiceForDoc$$module$src$service$$($JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$.$ampdoc_$,"viewer").isVisible()&&$JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$.$supportsAutoplay_$().then(function($supportsAutoplay$$){var $canAutoplay$$=$JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$.hasAutoplay&&!$JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$.userInteracted();
$canAutoplay$$&&$supportsAutoplay$$?$JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$.$allowAutoplay_$&&($JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$.$isVisible_$?($JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$.$visibilitySessionManager_$.beginSession(),$JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$.video.play(!0),$JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$.$playCalledByAutoplay_$=!0):($JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$.$isPlaying_$&&
$JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$.$visibilitySessionManager_$.endSession(),$JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$.video.pause(),$JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$.$pauseCalledByAutoplay_$=!0)):$JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$.$isVisible_$?$JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$.$visibilitySessionManager_$.beginSession():$JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$.$isPlaying_$&&
$JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$self$$.$visibilitySessionManager_$.endSession()})}
function $JSCompiler_StaticMethods_autoplayVideoBuilt_$$($JSCompiler_StaticMethods_autoplayVideoBuilt_$self$$){$JSCompiler_StaticMethods_autoplayVideoBuilt_$self$$.video.isInteractive()&&$JSCompiler_StaticMethods_autoplayVideoBuilt_$self$$.video.hideControls();$JSCompiler_StaticMethods_autoplayVideoBuilt_$self$$.$supportsAutoplay_$().then(function($supportsAutoplay$jscomp$1$$){!$supportsAutoplay$jscomp$1$$&&$JSCompiler_StaticMethods_autoplayVideoBuilt_$self$$.video.isInteractive()?$JSCompiler_StaticMethods_autoplayVideoBuilt_$self$$.video.showControls():
($JSCompiler_StaticMethods_autoplayVideoBuilt_$self$$.video.mute(),$JSCompiler_StaticMethods_installAutoplayArtifacts_$$($JSCompiler_StaticMethods_autoplayVideoBuilt_$self$$))})}
function $JSCompiler_StaticMethods_installAutoplayArtifacts_$$($JSCompiler_StaticMethods_installAutoplayArtifacts_$self$$){var $video$jscomp$10$$=$JSCompiler_StaticMethods_installAutoplayArtifacts_$self$$.video,$$jscomp$destructuring$var25_win$jscomp$55$$=$JSCompiler_StaticMethods_installAutoplayArtifacts_$self$$.video,$element$jscomp$77$$=$$jscomp$destructuring$var25_win$jscomp$55$$.element;$$jscomp$destructuring$var25_win$jscomp$55$$=$$jscomp$destructuring$var25_win$jscomp$55$$.win;if(!$element$jscomp$77$$.hasAttribute("noaudio")&&
!$element$jscomp$77$$.signals().get("user-interacted")){var $animation$$=$renderIcon$$module$src$service$video$autoplay$$($$jscomp$destructuring$var25_win$jscomp$55$$,$element$jscomp$77$$),$toggleAnimation$$=function($JSCompiler_StaticMethods_installAutoplayArtifacts_$self$$){$video$jscomp$10$$.mutateElement(function(){$animation$$.classList.toggle("amp-video-eq-play",$JSCompiler_StaticMethods_installAutoplayArtifacts_$self$$)})};$video$jscomp$10$$.mutateElement(function(){$element$jscomp$77$$.appendChild($animation$$)});
var $unlisteners$$=[$listen$$module$src$event_helper$$($element$jscomp$77$$,"pause",function(){return $toggleAnimation$$(!1)}),$listen$$module$src$event_helper$$($element$jscomp$77$$,"playing",function(){return $toggleAnimation$$(!0)})];$video$jscomp$10$$.signals().whenSignal("user-interacted").then(function(){var $video$jscomp$10$$=$JSCompiler_StaticMethods_installAutoplayArtifacts_$self$$.video,$$jscomp$destructuring$var25_win$jscomp$55$$=$video$jscomp$10$$.element;$JSCompiler_StaticMethods_installAutoplayArtifacts_$self$$.$firstPlayEventOrNoop_$();
$video$jscomp$10$$.isInteractive()&&$video$jscomp$10$$.showControls();$video$jscomp$10$$.unmute();$unlisteners$$.forEach(function($JSCompiler_StaticMethods_installAutoplayArtifacts_$self$$){$JSCompiler_StaticMethods_installAutoplayArtifacts_$self$$()});$video$jscomp$10$$=$$jscomp$destructuring$var25_win$jscomp$55$$.querySelector(".amp-video-eq");$$jscomp$destructuring$var25_win$jscomp$55$$=$$jscomp$destructuring$var25_win$jscomp$55$$.querySelector("i-amphtml-video-mask");$video$jscomp$10$$&&$removeElement$$module$src$dom$$($video$jscomp$10$$);
$$jscomp$destructuring$var25_win$jscomp$55$$&&$removeElement$$module$src$dom$$($$jscomp$destructuring$var25_win$jscomp$55$$)});if($video$jscomp$10$$.isInteractive()){var $mask$jscomp$6$$=$renderInteractionOverlay$$module$src$service$video$autoplay$$($element$jscomp$77$$),$setMaskDisplay$$=function($JSCompiler_StaticMethods_installAutoplayArtifacts_$self$$){$video$jscomp$10$$.mutateElement(function(){var $video$jscomp$10$$=$JSCompiler_StaticMethods_installAutoplayArtifacts_$self$$;void 0===$video$jscomp$10$$&&
($video$jscomp$10$$=$mask$jscomp$6$$.hasAttribute("hidden"));$video$jscomp$10$$?$mask$jscomp$6$$.removeAttribute("hidden"):$mask$jscomp$6$$.setAttribute("hidden","")})};$video$jscomp$10$$.hideControls();$video$jscomp$10$$.mutateElement(function(){$element$jscomp$77$$.appendChild($mask$jscomp$6$$)});[$listen$$module$src$event_helper$$($mask$jscomp$6$$,"click",function(){$video$jscomp$10$$.signals().signal("user-interacted")}),$listen$$module$src$event_helper$$($element$jscomp$77$$,"ad_start",function(){return $setMaskDisplay$$(!1)}),
$listen$$module$src$event_helper$$($element$jscomp$77$$,"ad_end",function(){return $setMaskDisplay$$(!0)})].forEach(function($JSCompiler_StaticMethods_installAutoplayArtifacts_$self$$){return $unlisteners$$.push($JSCompiler_StaticMethods_installAutoplayArtifacts_$self$$)})}}}
$JSCompiler_prototypeAlias$$.updateVisibility=function($opt_forceVisible$$){var $wasVisible$$=this.$isVisible_$;if($opt_forceVisible$$)this.$isVisible_$=!0;else{var $ratio$$=this.video.element.getIntersectionChangeEntry().intersectionRatio;this.$isVisible_$=.5<=($isFiniteNumber$$module$src$types$$($ratio$$)?$ratio$$:0)}this.$isVisible_$!=$wasVisible$$&&this.$loaded_$&&$JSCompiler_StaticMethods_loadedVideoVisibilityChanged_$$(this)};
$JSCompiler_prototypeAlias$$.getPlayingState=function(){return this.$isPlaying_$?this.$isPlaying_$&&this.$playCalledByAutoplay_$&&!this.userInteracted()?"playing_auto":"playing_manual":"paused"};$JSCompiler_prototypeAlias$$.userInteracted=function(){return null!=this.video.signals().get("user-interacted")};
$JSCompiler_prototypeAlias$$.getAnalyticsDetails=function(){var $$jscomp$this$jscomp$9$$=this,$video$jscomp$12$$=this.video;return this.$supportsAutoplay_$().then(function($supportsAutoplay$jscomp$2$$){var $$jscomp$destructuring$var30_height$jscomp$26$$=$video$jscomp$12$$.element.getLayoutBox(),$width$jscomp$27$$=$$jscomp$destructuring$var30_height$jscomp$26$$.width;$$jscomp$destructuring$var30_height$jscomp$26$$=$$jscomp$destructuring$var30_height$jscomp$26$$.height;var $autoplay$$=$$jscomp$this$jscomp$9$$.hasAutoplay&&
$supportsAutoplay$jscomp$2$$,$playedRanges$$=$video$jscomp$12$$.getPlayedRanges(),$playedTotal$$=$playedRanges$$.reduce(function($$jscomp$this$jscomp$9$$,$video$jscomp$12$$){return $$jscomp$this$jscomp$9$$+$video$jscomp$12$$[1]-$video$jscomp$12$$[0]},0);return{autoplay:$autoplay$$,currentTime:$video$jscomp$12$$.getCurrentTime(),duration:$video$jscomp$12$$.getDuration(),height:$$jscomp$destructuring$var30_height$jscomp$26$$,id:$video$jscomp$12$$.element.id,muted:$$jscomp$this$jscomp$9$$.$muted_$,playedTotal:$playedTotal$$,
playedRangesJson:JSON.stringify($playedRanges$$),state:$$jscomp$this$jscomp$9$$.getPlayingState(),width:$width$jscomp$27$$}})};
function $AutoFullscreenManager$$module$src$service$video_manager_impl$$($ampdoc$jscomp$13$$,$manager$jscomp$1$$){var $$jscomp$this$jscomp$10$$=this;this.$manager_$=$manager$jscomp$1$$;this.$ampdoc_$=$ampdoc$jscomp$13$$;this.$currentlyCentered_$=this.$currentlyInFullscreen_$=null;this.$entries_$=[];this.$boundSelectBestCentered_$=function(){return $JSCompiler_StaticMethods_selectBestCenteredInPortrait_$$($$jscomp$this$jscomp$10$$)};this.$boundIncludeOnlyPlaying_$=function($ampdoc$jscomp$13$$){return"playing_manual"==
$$jscomp$this$jscomp$10$$.$manager_$.getPlayingState($ampdoc$jscomp$13$$)};this.$boundCompareEntries_$=function($ampdoc$jscomp$13$$,$manager$jscomp$1$$){$ampdoc$jscomp$13$$=$ampdoc$jscomp$13$$.element.getIntersectionChangeEntry();var $JSCompiler_$jscomp$inline_116_JSCompiler_inline_result$jscomp$39_JSCompiler_rectA$jscomp$inline_118_a$jscomp$4$$=$ampdoc$jscomp$13$$.intersectionRatio;$ampdoc$jscomp$13$$=$ampdoc$jscomp$13$$.boundingClientRect;var $JSCompiler_$jscomp$inline_119_JSCompiler_centerB$jscomp$inline_126_JSCompiler_viewport$jscomp$inline_124$$=
$manager$jscomp$1$$.element.getIntersectionChangeEntry();$manager$jscomp$1$$=$JSCompiler_$jscomp$inline_119_JSCompiler_centerB$jscomp$inline_126_JSCompiler_viewport$jscomp$inline_124$$.boundingClientRect;$JSCompiler_$jscomp$inline_116_JSCompiler_inline_result$jscomp$39_JSCompiler_rectA$jscomp$inline_118_a$jscomp$4$$-=$JSCompiler_$jscomp$inline_119_JSCompiler_centerB$jscomp$inline_126_JSCompiler_viewport$jscomp$inline_124$$.intersectionRatio;.1<Math.abs($JSCompiler_$jscomp$inline_116_JSCompiler_inline_result$jscomp$39_JSCompiler_rectA$jscomp$inline_118_a$jscomp$4$$)?
$ampdoc$jscomp$13$$=$JSCompiler_$jscomp$inline_116_JSCompiler_inline_result$jscomp$39_JSCompiler_rectA$jscomp$inline_118_a$jscomp$4$$:($JSCompiler_$jscomp$inline_119_JSCompiler_centerB$jscomp$inline_126_JSCompiler_viewport$jscomp$inline_124$$=$getServiceForDoc$$module$src$service$$($$jscomp$this$jscomp$10$$.$ampdoc_$,"viewport"),$JSCompiler_$jscomp$inline_116_JSCompiler_inline_result$jscomp$39_JSCompiler_rectA$jscomp$inline_118_a$jscomp$4$$=$centerDist$$module$src$service$video_manager_impl$$($JSCompiler_$jscomp$inline_119_JSCompiler_centerB$jscomp$inline_126_JSCompiler_viewport$jscomp$inline_124$$,
$ampdoc$jscomp$13$$),$JSCompiler_$jscomp$inline_119_JSCompiler_centerB$jscomp$inline_126_JSCompiler_viewport$jscomp$inline_124$$=$centerDist$$module$src$service$video_manager_impl$$($JSCompiler_$jscomp$inline_119_JSCompiler_centerB$jscomp$inline_126_JSCompiler_viewport$jscomp$inline_124$$,$manager$jscomp$1$$),$ampdoc$jscomp$13$$=$JSCompiler_$jscomp$inline_116_JSCompiler_inline_result$jscomp$39_JSCompiler_rectA$jscomp$inline_118_a$jscomp$4$$<$JSCompiler_$jscomp$inline_119_JSCompiler_centerB$jscomp$inline_126_JSCompiler_viewport$jscomp$inline_124$$||
$JSCompiler_$jscomp$inline_116_JSCompiler_inline_result$jscomp$39_JSCompiler_rectA$jscomp$inline_118_a$jscomp$4$$>$JSCompiler_$jscomp$inline_119_JSCompiler_centerB$jscomp$inline_126_JSCompiler_viewport$jscomp$inline_124$$?$JSCompiler_$jscomp$inline_116_JSCompiler_inline_result$jscomp$39_JSCompiler_rectA$jscomp$inline_118_a$jscomp$4$$-$JSCompiler_$jscomp$inline_119_JSCompiler_centerB$jscomp$inline_126_JSCompiler_viewport$jscomp$inline_124$$:$ampdoc$jscomp$13$$.top-$manager$jscomp$1$$.top);return $ampdoc$jscomp$13$$};
$JSCompiler_StaticMethods_installOrientationObserver_$$(this);$JSCompiler_StaticMethods_installFullscreenListener_$$(this)}
$AutoFullscreenManager$$module$src$service$video_manager_impl$$.prototype.register=function($entry$jscomp$8_video$jscomp$15$$){$entry$jscomp$8_video$jscomp$15$$=$entry$jscomp$8_video$jscomp$15$$.video;var $element$jscomp$80$$=$entry$jscomp$8_video$jscomp$15$$.element;if("video"==$element$jscomp$80$$.querySelector("video, iframe").tagName.toLowerCase())var $JSCompiler_inline_result$jscomp$37_JSCompiler_platform$jscomp$inline_131$$=!0;else $JSCompiler_inline_result$jscomp$37_JSCompiler_platform$jscomp$inline_131$$=
$getService$$module$src$service$$(this.$ampdoc_$.win,"platform"),$JSCompiler_inline_result$jscomp$37_JSCompiler_platform$jscomp$inline_131$$=$JSCompiler_inline_result$jscomp$37_JSCompiler_platform$jscomp$inline_131$$.isIos()||$JSCompiler_inline_result$jscomp$37_JSCompiler_platform$jscomp$inline_131$$.isSafari()?!!{"amp-dailymotion":!0,"amp-ima-video":!0}[$element$jscomp$80$$.tagName.toLowerCase()]:!0;$JSCompiler_inline_result$jscomp$37_JSCompiler_platform$jscomp$inline_131$$&&(this.$entries_$.push($entry$jscomp$8_video$jscomp$15$$),
$listen$$module$src$event_helper$$($element$jscomp$80$$,"pause",this.$boundSelectBestCentered_$),$listen$$module$src$event_helper$$($element$jscomp$80$$,"playing",this.$boundSelectBestCentered_$),$listen$$module$src$event_helper$$($element$jscomp$80$$,"ended",this.$boundSelectBestCentered_$),$entry$jscomp$8_video$jscomp$15$$.signals().whenSignal("user-interacted").then(this.$boundSelectBestCentered_$),$JSCompiler_StaticMethods_selectBestCenteredInPortrait_$$(this))};
function $JSCompiler_StaticMethods_installFullscreenListener_$$($JSCompiler_StaticMethods_installFullscreenListener_$self$$){function $exitHandler$$(){$JSCompiler_StaticMethods_installFullscreenListener_$self$$.$currentlyInFullscreen_$=null}var $root$jscomp$8$$=$JSCompiler_StaticMethods_installFullscreenListener_$self$$.$ampdoc_$.getRootNode();$listen$$module$src$event_helper$$($root$jscomp$8$$,"webkitfullscreenchange",$exitHandler$$);$listen$$module$src$event_helper$$($root$jscomp$8$$,"mozfullscreenchange",
$exitHandler$$);$listen$$module$src$event_helper$$($root$jscomp$8$$,"fullscreenchange",$exitHandler$$);$listen$$module$src$event_helper$$($root$jscomp$8$$,"MSFullscreenChange",$exitHandler$$)}
$AutoFullscreenManager$$module$src$service$video_manager_impl$$.prototype.isInLandscape=function(){var $JSCompiler_win$jscomp$inline_135$$=this.$ampdoc_$.win;return $JSCompiler_win$jscomp$inline_135$$.screen&&"orientation"in $JSCompiler_win$jscomp$inline_135$$.screen?$startsWith$$module$src$string$$($JSCompiler_win$jscomp$inline_135$$.screen.orientation.type,"landscape"):90==Math.abs($JSCompiler_win$jscomp$inline_135$$.orientation)};
function $JSCompiler_StaticMethods_installOrientationObserver_$$($JSCompiler_StaticMethods_installOrientationObserver_$self$$){var $win$jscomp$56$$=$JSCompiler_StaticMethods_installOrientationObserver_$self$$.$ampdoc_$.win,$screen$jscomp$1$$=$win$jscomp$56$$.screen;if($screen$jscomp$1$$&&"orientation"in $screen$jscomp$1$$){var $orient$$=$screen$jscomp$1$$.orientation;$listen$$module$src$event_helper$$($orient$$,"change",function(){return $JSCompiler_StaticMethods_onRotation_$$($JSCompiler_StaticMethods_installOrientationObserver_$self$$)})}$listen$$module$src$event_helper$$($win$jscomp$56$$,
"orientationchange",function(){return $JSCompiler_StaticMethods_onRotation_$$($JSCompiler_StaticMethods_installOrientationObserver_$self$$)})}
function $JSCompiler_StaticMethods_onRotation_$$($JSCompiler_StaticMethods_onRotation_$self$$){$JSCompiler_StaticMethods_onRotation_$self$$.isInLandscape()?null!=$JSCompiler_StaticMethods_onRotation_$self$$.$currentlyCentered_$&&$JSCompiler_StaticMethods_enter_$$($JSCompiler_StaticMethods_onRotation_$self$$,$JSCompiler_StaticMethods_onRotation_$self$$.$currentlyCentered_$):$JSCompiler_StaticMethods_onRotation_$self$$.$currentlyInFullscreen_$&&$JSCompiler_StaticMethods_exit_$$($JSCompiler_StaticMethods_onRotation_$self$$,
$JSCompiler_StaticMethods_onRotation_$self$$.$currentlyInFullscreen_$)}
function $JSCompiler_StaticMethods_enter_$$($JSCompiler_StaticMethods_enter_$self$$,$video$jscomp$17$$){var $platform$jscomp$1$$=$getService$$module$src$service$$($JSCompiler_StaticMethods_enter_$self$$.$ampdoc_$.win,"platform");$JSCompiler_StaticMethods_enter_$self$$.$currentlyInFullscreen_$=$video$jscomp$17$$;$platform$jscomp$1$$.isAndroid()&&$platform$jscomp$1$$.isChrome()?$video$jscomp$17$$.fullscreenEnter():$JSCompiler_StaticMethods_scrollIntoIfNotVisible_$$($JSCompiler_StaticMethods_enter_$self$$,$video$jscomp$17$$).then(function(){return $video$jscomp$17$$.fullscreenEnter()})}
function $JSCompiler_StaticMethods_exit_$$($JSCompiler_StaticMethods_exit_$self$$,$video$jscomp$18$$){$JSCompiler_StaticMethods_exit_$self$$.$currentlyInFullscreen_$=null;$JSCompiler_StaticMethods_scrollIntoIfNotVisible_$$($JSCompiler_StaticMethods_exit_$self$$,$video$jscomp$18$$,"center").then(function(){return $video$jscomp$18$$.fullscreenExit()})}
function $JSCompiler_StaticMethods_scrollIntoIfNotVisible_$$($JSCompiler_StaticMethods_scrollIntoIfNotVisible_$self$$,$video$jscomp$19$$,$optPos$$){$optPos$$=void 0===$optPos$$?null:$optPos$$;var $element$jscomp$81$$=$video$jscomp$19$$.element,$viewport$$=$getServiceForDoc$$module$src$service$$($JSCompiler_StaticMethods_scrollIntoIfNotVisible_$self$$.$ampdoc_$,"viewport");return $JSCompiler_StaticMethods_onceOrientationChanges_$$($JSCompiler_StaticMethods_scrollIntoIfNotVisible_$self$$).then(function(){var $JSCompiler_StaticMethods_scrollIntoIfNotVisible_$self$$=
$element$jscomp$81$$.getIntersectionChangeEntry().boundingClientRect,$video$jscomp$19$$=$JSCompiler_StaticMethods_scrollIntoIfNotVisible_$self$$,$top$jscomp$2$$=$video$jscomp$19$$.top;$video$jscomp$19$$=$video$jscomp$19$$.bottom;var $vh$$=$viewport$$.getSize().height,$fullyVisible$$=0<=$top$jscomp$2$$&&$video$jscomp$19$$<=$vh$$;return $fullyVisible$$?Promise.resolve():$viewport$$.animateScrollIntoView($element$jscomp$81$$,$optPos$$?$optPos$$:$video$jscomp$19$$>$vh$$?"bottom":"top")})}
function $JSCompiler_StaticMethods_onceOrientationChanges_$$($JSCompiler_StaticMethods_onceOrientationChanges_$self$$){var $magicNumber$$=330;return $getService$$module$src$service$$($JSCompiler_StaticMethods_onceOrientationChanges_$self$$.$ampdoc_$.win,"timer").promise($magicNumber$$)}
function $JSCompiler_StaticMethods_selectBestCenteredInPortrait_$$($JSCompiler_StaticMethods_selectBestCenteredInPortrait_$self$$){if($JSCompiler_StaticMethods_selectBestCenteredInPortrait_$self$$.isInLandscape())return $JSCompiler_StaticMethods_selectBestCenteredInPortrait_$self$$.$currentlyCentered_$;$JSCompiler_StaticMethods_selectBestCenteredInPortrait_$self$$.$currentlyCentered_$=null;var $selected$$=$JSCompiler_StaticMethods_selectBestCenteredInPortrait_$self$$.$entries_$.filter($JSCompiler_StaticMethods_selectBestCenteredInPortrait_$self$$.$boundIncludeOnlyPlaying_$).sort($JSCompiler_StaticMethods_selectBestCenteredInPortrait_$self$$.$boundCompareEntries_$)[0];
if($selected$$){var $intersectionRatio$$=$selected$$.element.getIntersectionChangeEntry().intersectionRatio;.5<=$intersectionRatio$$&&($JSCompiler_StaticMethods_selectBestCenteredInPortrait_$self$$.$currentlyCentered_$=$selected$$)}return $JSCompiler_StaticMethods_selectBestCenteredInPortrait_$self$$.$currentlyCentered_$}
function $centerDist$$module$src$service$video_manager_impl$$($viewport$jscomp$2$$,$rect$$){var $centerY$$=$rect$$.top+$rect$$.height/2,$centerViewport$$=$viewport$jscomp$2$$.getSize().height/2;return Math.abs($centerY$$-$centerViewport$$)}
function $AnalyticsPercentageTracker$$module$src$service$video_manager_impl$$($win$jscomp$58$$,$entry$jscomp$9$$){this.$timer_$=$getService$$module$src$service$$($win$jscomp$58$$,"timer");this.$entry_$=$entry$jscomp$9$$;this.$unlisteners_$=null;this.$triggerId_$=this.$last_$=0}
$AnalyticsPercentageTracker$$module$src$service$video_manager_impl$$.prototype.start=function(){var $$jscomp$this$jscomp$13$$=this,$element$jscomp$82$$=this.$entry_$.video.element;this.stop();this.$unlisteners_$=this.$unlisteners_$||[];this.$unlisteners_$.push($listenOnce$$module$src$event_helper$$($element$jscomp$82$$,"loadedmetadata",function(){$JSCompiler_StaticMethods_hasDuration_$$($$jscomp$this$jscomp$13$$)&&$JSCompiler_StaticMethods_calculate_$$($$jscomp$this$jscomp$13$$,$$jscomp$this$jscomp$13$$.$triggerId_$)}),
$listen$$module$src$event_helper$$($element$jscomp$82$$,"ended",function(){$JSCompiler_StaticMethods_hasDuration_$$($$jscomp$this$jscomp$13$$)&&$JSCompiler_StaticMethods_maybeTrigger_$$($$jscomp$this$jscomp$13$$,100)}))};$AnalyticsPercentageTracker$$module$src$service$video_manager_impl$$.prototype.stop=function(){if(this.$unlisteners_$){for(;0<this.$unlisteners_$.length;)this.$unlisteners_$.pop().call();this.$triggerId_$++}};
function $JSCompiler_StaticMethods_hasDuration_$$($JSCompiler_StaticMethods_hasDuration_$self$$){var $video$jscomp$21$$=$JSCompiler_StaticMethods_hasDuration_$self$$.$entry_$.video,$duration$jscomp$2$$=$video$jscomp$21$$.getDuration();if(!$duration$jscomp$2$$||isNaN($duration$jscomp$2$$)||0>=$duration$jscomp$2$$)return!1;if(250>50*$duration$jscomp$2$$){var $bestResultLength$$=5;$JSCompiler_StaticMethods_hasDuration_$self$$.$warnForTesting_$("This video is too short for `video-percentage-played`. Reports may be innacurate. For best results, use videos over",
$bestResultLength$$,"seconds long.",$video$jscomp$21$$.element)}return!0}
$AnalyticsPercentageTracker$$module$src$service$video_manager_impl$$.prototype.$warnForTesting_$=function($args$jscomp$1$$){for(var $$jscomp$restParams$jscomp$1$$=[],$$jscomp$restIndex$jscomp$1$$=0;$$jscomp$restIndex$jscomp$1$$<arguments.length;++$$jscomp$restIndex$jscomp$1$$)$$jscomp$restParams$jscomp$1$$[$$jscomp$restIndex$jscomp$1$$-0]=arguments[$$jscomp$restIndex$jscomp$1$$];$user$$module$src$log$$().warn.apply($user$$module$src$log$$(),["video-manager"].concat($$jscomp$restParams$jscomp$1$$))};
function $JSCompiler_StaticMethods_calculate_$$($JSCompiler_StaticMethods_calculate_$self$$,$triggerId$$){if($triggerId$$==$JSCompiler_StaticMethods_calculate_$self$$.$triggerId_$){var $duration$jscomp$3_entry$jscomp$10$$=$JSCompiler_StaticMethods_calculate_$self$$.$entry_$,$timer$$=$JSCompiler_StaticMethods_calculate_$self$$.$timer_$,$video$jscomp$22$$=$duration$jscomp$3_entry$jscomp$10$$.video,$calculateAgain$$=function(){return $JSCompiler_StaticMethods_calculate_$$($JSCompiler_StaticMethods_calculate_$self$$,
$triggerId$$)};if("paused"==$duration$jscomp$3_entry$jscomp$10$$.getPlayingState())$timer$$.delay($calculateAgain$$,500);else{$duration$jscomp$3_entry$jscomp$10$$=$video$jscomp$22$$.getDuration();var $frequencyMs$$=$clamp$$module$src$utils$math$$(50*$duration$jscomp$3_entry$jscomp$10$$),$percentage$$=$video$jscomp$22$$.getCurrentTime()/$duration$jscomp$3_entry$jscomp$10$$*100,$normalizedPercentage$$=5*Math.floor($percentage$$/5);$isFiniteNumber$$module$src$types$$($normalizedPercentage$$);$JSCompiler_StaticMethods_maybeTrigger_$$($JSCompiler_StaticMethods_calculate_$self$$,
$normalizedPercentage$$);$timer$$.delay($calculateAgain$$,$frequencyMs$$)}}}
function $JSCompiler_StaticMethods_maybeTrigger_$$($JSCompiler_StaticMethods_maybeTrigger_$self$$,$normalizedPercentage$jscomp$1$$){0>=$normalizedPercentage$jscomp$1$$||$JSCompiler_StaticMethods_maybeTrigger_$self$$.$last_$==$normalizedPercentage$jscomp$1$$||($JSCompiler_StaticMethods_maybeTrigger_$self$$.$last_$=$normalizedPercentage$jscomp$1$$,$analyticsEvent$$module$src$service$video_manager_impl$$($JSCompiler_StaticMethods_maybeTrigger_$self$$.$entry_$,"video-percentage-played",{normalizedPercentage:$normalizedPercentage$jscomp$1$$.toString()}))}
function $analyticsEvent$$module$src$service$video_manager_impl$$($entry$jscomp$11$$,$eventType$jscomp$9$$,$opt_vars$$){var $video$jscomp$23$$=$entry$jscomp$11$$.video;$entry$jscomp$11$$.getAnalyticsDetails().then(function($entry$jscomp$11$$){$opt_vars$$&&Object.assign($entry$jscomp$11$$,$opt_vars$$);$video$jscomp$23$$.element.dispatchCustomEvent($eventType$jscomp$9$$,$entry$jscomp$11$$)})};function $AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat$$($$jscomp$super$this_element$jscomp$86$$){$$jscomp$super$this_element$jscomp$86$$=AMP.BaseElement.call(this,$$jscomp$super$this_element$jscomp$86$$)||this;$$jscomp$super$this_element$jscomp$86$$.$videoid_$="";$$jscomp$super$this_element$jscomp$86$$.$iframe_$=null;$$jscomp$super$this_element$jscomp$86$$.$videoIframeSrc_$=null;$$jscomp$super$this_element$jscomp$86$$.$unlistenMessage_$=null;return $$jscomp$super$this_element$jscomp$86$$}
var $JSCompiler_parentCtor$jscomp$inline_141$$=AMP.BaseElement;$AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat$$.prototype=$$jscomp$objectCreate$$($JSCompiler_parentCtor$jscomp$inline_141$$.prototype);$AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat$$.prototype.constructor=$AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat$$;
if($$jscomp$setPrototypeOf$$)$$jscomp$setPrototypeOf$$($AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat$$,$JSCompiler_parentCtor$jscomp$inline_141$$);else for(var $JSCompiler_p$jscomp$inline_142$$ in $JSCompiler_parentCtor$jscomp$inline_141$$)if("prototype"!=$JSCompiler_p$jscomp$inline_142$$)if(Object.defineProperties){var $JSCompiler_descriptor$jscomp$inline_143$$=Object.getOwnPropertyDescriptor($JSCompiler_parentCtor$jscomp$inline_141$$,$JSCompiler_p$jscomp$inline_142$$);$JSCompiler_descriptor$jscomp$inline_143$$&&
Object.defineProperty($AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat$$,$JSCompiler_p$jscomp$inline_142$$,$JSCompiler_descriptor$jscomp$inline_143$$)}else $AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat$$[$JSCompiler_p$jscomp$inline_142$$]=$JSCompiler_parentCtor$jscomp$inline_141$$[$JSCompiler_p$jscomp$inline_142$$];$AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat$$.$superClass_$=$JSCompiler_parentCtor$jscomp$inline_141$$.prototype;$JSCompiler_prototypeAlias$$=$AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat$$.prototype;
$JSCompiler_prototypeAlias$$.preconnectCallback=function($opt_onLayout$$){this.preconnect.url("https://gfycat.com",$opt_onLayout$$);this.preconnect.url("https://giant.gfycat.com",$opt_onLayout$$);this.preconnect.url("https://thumbs.gfycat.com",$opt_onLayout$$)};
$JSCompiler_prototypeAlias$$.isLayoutSupported=function($layout$jscomp$3$$){return"fixed"==$layout$jscomp$3$$||"fixed-height"==$layout$jscomp$3$$||"responsive"==$layout$jscomp$3$$||"fill"==$layout$jscomp$3$$||"flex-item"==$layout$jscomp$3$$||"fluid"==$layout$jscomp$3$$||"intrinsic"==$layout$jscomp$3$$};
$JSCompiler_prototypeAlias$$.buildCallback=function(){this.$videoid_$=$userAssert$$module$src$log$$(this.element.getAttribute("data-gfyid"),"The data-gfyid attribute is required for <amp-gfycat> %s",this.element);this.element.hasAttribute("noautoplay")||this.element.setAttribute("autoplay","");var $JSCompiler_ampdoc$jscomp$inline_215$$=$getAmpdoc$$module$src$service$$(this.element),$JSCompiler_holder$jscomp$inline_216$$=$getAmpdocServiceHolder$$module$src$service$$($JSCompiler_ampdoc$jscomp$inline_215$$),
$JSCompiler_services$jscomp$inline_260$$=$getServices$$module$src$service$$($JSCompiler_holder$jscomp$inline_216$$),$JSCompiler_s$jscomp$inline_261$$=$JSCompiler_services$jscomp$inline_260$$["video-manager"];$JSCompiler_s$jscomp$inline_261$$||($JSCompiler_s$jscomp$inline_261$$=$JSCompiler_services$jscomp$inline_260$$["video-manager"]={obj:null,promise:null,resolve:null,reject:null,context:null,ctor:null});$JSCompiler_s$jscomp$inline_261$$.ctor||$JSCompiler_s$jscomp$inline_261$$.obj||($JSCompiler_s$jscomp$inline_261$$.ctor=
$VideoManager$$module$src$service$video_manager_impl$$,$JSCompiler_s$jscomp$inline_261$$.context=$JSCompiler_ampdoc$jscomp$inline_215$$,$JSCompiler_s$jscomp$inline_261$$.resolve&&$getServiceInternal$$module$src$service$$($JSCompiler_holder$jscomp$inline_216$$,"video-manager"));$getServiceForDoc$$module$src$service$$(this.element,"video-manager").register(this)};
$JSCompiler_prototypeAlias$$.createPlaceholderCallback=function(){var $placeholder$$=this.win.document.createElement("amp-img"),$videoid$$=this.$videoid_$;this.propagateAttributes(["alt","aria-label"],$placeholder$$);$placeholder$$.setAttribute("src","https://thumbs.gfycat.com/"+encodeURIComponent($videoid$$)+"-poster.jpg");$placeholder$$.setAttribute("layout","fill");$placeholder$$.setAttribute("placeholder","");$placeholder$$.setAttribute("referrerpolicy","origin");this.element.hasAttribute("aria-label")?
$placeholder$$.setAttribute("alt","Loading gif "+this.element.getAttribute("aria-label")):this.element.hasAttribute("alt")?$placeholder$$.setAttribute("alt","Loading gif "+this.element.getAttribute("alt")):$placeholder$$.setAttribute("alt","Loading gif");this.applyFillContent($placeholder$$);return $placeholder$$};
function $JSCompiler_StaticMethods_getVideoIframeSrc_$$($JSCompiler_StaticMethods_getVideoIframeSrc_$self$$){if($JSCompiler_StaticMethods_getVideoIframeSrc_$self$$.$videoIframeSrc_$)return $JSCompiler_StaticMethods_getVideoIframeSrc_$self$$.$videoIframeSrc_$;var $JSCompiler_mainAndFragment$jscomp$inline_229_JSCompiler_temp_const$jscomp$155_src$jscomp$5$$="https://gfycat.com/ifr/"+encodeURIComponent($JSCompiler_StaticMethods_getVideoIframeSrc_$self$$.$videoid_$),$JSCompiler_inline_result$jscomp$156_JSCompiler_newUrl$jscomp$inline_231_params$jscomp$6$$=
$getDataParamsFromAttributes$$module$src$dom$$($JSCompiler_StaticMethods_getVideoIframeSrc_$self$$.element),$noautoplay$$=$JSCompiler_StaticMethods_getVideoIframeSrc_$self$$.element.hasAttribute("noautoplay");$noautoplay$$&&($JSCompiler_inline_result$jscomp$156_JSCompiler_newUrl$jscomp$inline_231_params$jscomp$6$$.autoplay="0");var $JSCompiler_s$jscomp$inline_219$$=[];for($JSCompiler_k$jscomp$inline_220_JSCompiler_mainAndQuery$jscomp$inline_230$$ in $JSCompiler_inline_result$jscomp$156_JSCompiler_newUrl$jscomp$inline_231_params$jscomp$6$$){var $JSCompiler_v$jscomp$inline_221_sv$3$jscomp$inline_224$$=
$JSCompiler_inline_result$jscomp$156_JSCompiler_newUrl$jscomp$inline_231_params$jscomp$6$$[$JSCompiler_k$jscomp$inline_220_JSCompiler_mainAndQuery$jscomp$inline_230$$];if(null!=$JSCompiler_v$jscomp$inline_221_sv$3$jscomp$inline_224$$)if(Array.isArray($JSCompiler_v$jscomp$inline_221_sv$3$jscomp$inline_224$$))for(var $JSCompiler_i$jscomp$inline_222$$=0;$JSCompiler_i$jscomp$inline_222$$<$JSCompiler_v$jscomp$inline_221_sv$3$jscomp$inline_224$$.length;$JSCompiler_i$jscomp$inline_222$$++){var $JSCompiler_sv$jscomp$inline_223$$=
$JSCompiler_v$jscomp$inline_221_sv$3$jscomp$inline_224$$[$JSCompiler_i$jscomp$inline_222$$];$JSCompiler_s$jscomp$inline_219$$.push(encodeURIComponent($JSCompiler_k$jscomp$inline_220_JSCompiler_mainAndQuery$jscomp$inline_230$$)+"="+encodeURIComponent($JSCompiler_sv$jscomp$inline_223$$))}else $JSCompiler_s$jscomp$inline_219$$.push(encodeURIComponent($JSCompiler_k$jscomp$inline_220_JSCompiler_mainAndQuery$jscomp$inline_230$$)+"="+encodeURIComponent($JSCompiler_v$jscomp$inline_221_sv$3$jscomp$inline_224$$))}$JSCompiler_inline_result$jscomp$156_JSCompiler_newUrl$jscomp$inline_231_params$jscomp$6$$=
$JSCompiler_s$jscomp$inline_219$$.join("&");if($JSCompiler_inline_result$jscomp$156_JSCompiler_newUrl$jscomp$inline_231_params$jscomp$6$$){$JSCompiler_mainAndFragment$jscomp$inline_229_JSCompiler_temp_const$jscomp$155_src$jscomp$5$$=$JSCompiler_mainAndFragment$jscomp$inline_229_JSCompiler_temp_const$jscomp$155_src$jscomp$5$$.split("#",2);var $JSCompiler_k$jscomp$inline_220_JSCompiler_mainAndQuery$jscomp$inline_230$$=$JSCompiler_mainAndFragment$jscomp$inline_229_JSCompiler_temp_const$jscomp$155_src$jscomp$5$$[0].split("?",
2);$JSCompiler_inline_result$jscomp$156_JSCompiler_newUrl$jscomp$inline_231_params$jscomp$6$$=$JSCompiler_k$jscomp$inline_220_JSCompiler_mainAndQuery$jscomp$inline_230$$[0]+($JSCompiler_k$jscomp$inline_220_JSCompiler_mainAndQuery$jscomp$inline_230$$[1]?"?"+$JSCompiler_k$jscomp$inline_220_JSCompiler_mainAndQuery$jscomp$inline_230$$[1]+"&"+$JSCompiler_inline_result$jscomp$156_JSCompiler_newUrl$jscomp$inline_231_params$jscomp$6$$:"?"+$JSCompiler_inline_result$jscomp$156_JSCompiler_newUrl$jscomp$inline_231_params$jscomp$6$$);
$JSCompiler_mainAndFragment$jscomp$inline_229_JSCompiler_temp_const$jscomp$155_src$jscomp$5$$=$JSCompiler_inline_result$jscomp$156_JSCompiler_newUrl$jscomp$inline_231_params$jscomp$6$$+=$JSCompiler_mainAndFragment$jscomp$inline_229_JSCompiler_temp_const$jscomp$155_src$jscomp$5$$[1]?"#"+$JSCompiler_mainAndFragment$jscomp$inline_229_JSCompiler_temp_const$jscomp$155_src$jscomp$5$$[1]:""}return $JSCompiler_StaticMethods_getVideoIframeSrc_$self$$.$videoIframeSrc_$=$JSCompiler_mainAndFragment$jscomp$inline_229_JSCompiler_temp_const$jscomp$155_src$jscomp$5$$}
$JSCompiler_prototypeAlias$$.layoutCallback=function(){var $$jscomp$this$jscomp$15$$=this,$iframe$$=this.element.ownerDocument.createElement("iframe"),$src$jscomp$6$$=$JSCompiler_StaticMethods_getVideoIframeSrc_$$(this);$iframe$$.setAttribute("frameborder","0");$iframe$$.src=$src$jscomp$6$$;this.applyFillContent($iframe$$);this.$iframe_$=$iframe$$;this.$unlistenMessage_$=$listen$$module$src$event_helper$$(this.win,"message",this.$handleGfycatMessages_$.bind(this));this.element.appendChild($iframe$$);
return this.loadPromise(this.$iframe_$).then(function(){$$jscomp$this$jscomp$15$$.element.dispatchCustomEvent("load")})};$JSCompiler_prototypeAlias$$.unlayoutCallback=function(){this.$iframe_$&&($removeElement$$module$src$dom$$(this.$iframe_$),this.$iframe_$=null);this.$unlistenMessage_$&&this.$unlistenMessage_$();return!0};
$JSCompiler_prototypeAlias$$.$handleGfycatMessages_$=function($event$jscomp$11$$){var $eventData$$=$event$jscomp$11$$.data;"https://gfycat.com"===$event$jscomp$11$$.origin&&$event$jscomp$11$$.source==this.$iframe_$.contentWindow&&"string"===typeof $eventData$$&&("paused"==$eventData$$?this.element.dispatchCustomEvent("pause"):"playing"==$eventData$$&&this.element.dispatchCustomEvent("playing"))};$JSCompiler_prototypeAlias$$.pauseCallback=function(){this.pause()};
$JSCompiler_prototypeAlias$$.supportsPlatform=function(){return!0};$JSCompiler_prototypeAlias$$.isInteractive=function(){return!1};$JSCompiler_prototypeAlias$$.play=function(){this.$iframe_$&&this.$iframe_$.contentWindow&&this.$iframe_$.contentWindow.postMessage("play","*")};$JSCompiler_prototypeAlias$$.pause=function(){this.$iframe_$&&this.$iframe_$.contentWindow&&this.$iframe_$.contentWindow.postMessage("pause","*")};$JSCompiler_prototypeAlias$$.mute=function(){};
$JSCompiler_prototypeAlias$$.unmute=function(){};$JSCompiler_prototypeAlias$$.showControls=function(){};$JSCompiler_prototypeAlias$$.hideControls=function(){};$JSCompiler_prototypeAlias$$.fullscreenEnter=function(){};$JSCompiler_prototypeAlias$$.fullscreenExit=function(){};$JSCompiler_prototypeAlias$$.isFullscreen=function(){return!1};$JSCompiler_prototypeAlias$$.getMetadata=function(){};$JSCompiler_prototypeAlias$$.preimplementsMediaSessionAPI=function(){return!1};
$JSCompiler_prototypeAlias$$.preimplementsAutoFullscreen=function(){return!1};$JSCompiler_prototypeAlias$$.getCurrentTime=function(){return 0};$JSCompiler_prototypeAlias$$.getDuration=function(){return 1};$JSCompiler_prototypeAlias$$.getPlayedRanges=function(){return[]};$JSCompiler_prototypeAlias$$.seekTo=function(){this.user().error("amp-gfycat","`seekTo` not supported.")};(function($AMP$jscomp$1$$){$AMP$jscomp$1$$.registerElement("amp-gfycat",$AmpGfycat$$module$extensions$amp_gfycat$0_1$amp_gfycat$$)})(self.AMP);
})});

//# sourceMappingURL=amp-gfycat-0.1.js.map
