workspace(name = "validator")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_google_absl",
    sha256 = "2247c732ba0832c4e9fd594f5557ae251e4b57b2646aeb97d93135f3a4562059",
    strip_prefix = "abseil-cpp-08850701d27544b4af6501154791d3d45e28b0f8",
    urls = ["https://github.com/abseil/abseil-cpp/archive/08850701d27544b4af6501154791d3d45e28b0f8.zip"],
)

http_archive(
    name = "com_google_googletest",
    sha256 = "cc144a5bea428144bf2280881d6323a3d259713cc0bdc9ff7cbc04bda3f83e56",
    strip_prefix = "googletest-ff233bdd4cac0a0bf6e5cd45bda3406814cb2796",
    urls = ["https://github.com/google/googletest/archive/ff233bdd4cac0a0bf6e5cd45bda3406814cb2796.zip"],  # 2019-01-07
)

http_archive(
    name = "com_google_protobuf",
    sha256 = "85551558577d3fec4ebf9c1919c34845dc467a71da78d734d862b1f32e8099a4",
    strip_prefix = "protobuf-d794139f09230bed72ec765426854723deac012d",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/d794139f09230bed72ec765426854723deac012d.zip"],
)
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()

http_archive(
    name = "com_github_gflags_gflags",
    sha256 = "4753cbb1e1460d54d03cc1413960a63a46b42c0d691dad45c3f0ce71741d97d6",
    strip_prefix = "gflags-03a4842c9c6aaef438d7bf0c84e8a62c8064992b",
    urls = ["https://github.com/gflags/gflags/archive/03a4842c9c6aaef438d7bf0c84e8a62c8064992b.zip"],
)

http_archive(
    name = "com_googlesource_code_re2",
    sha256 = "566f95b2427efc0ef8926d2df167cc77ccba55c06f206abc02e8c17081fa5ffd",
    strip_prefix = "re2-6dcd83d60f7944926bfd308cc13979fc53dd69ca",
    urls = ["https://github.com/google/re2/archive/6dcd83d60f7944926bfd308cc13979fc53dd69ca.zip"],
)

# rules_cc defines rules for generating C++ code from Protocol Buffers.
http_archive(
    name = "rules_cc",
    sha256 = "ba1b87ba6853b5edc4e6a4088bb4115a73e1e3f24a51ca330776d558c1982555",
    strip_prefix = "rules_cc-84fceed8876865dc3419e9646a03091e44e90699",
    urls = ["https://github.com/bazelbuild/rules_cc/archive/84fceed8876865dc3419e9646a03091e44e90699.zip"],
)
load("@rules_cc//cc:repositories.bzl", "rules_cc_dependencies")
rules_cc_dependencies()

# rules_proto defines abstract rules for building Protocol Buffers.
http_archive(
    name = "rules_proto",
    sha256 = "2b0f9c9314edcf7e0937f6b68124494c58643df763fd59e37fb5dc742e0202d4",
    strip_prefix = "rules_proto-557db790e7a71993ff85bf523099dfd25060ae2f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/557db790e7a71993ff85bf523099dfd25060ae2f.tar.gz",
        "https://github.com/bazelbuild/rules_proto/archive/557db790e7a71993ff85bf523099dfd25060ae2f.tar.gz",
    ],
)
load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()

http_archive(
    name = "emsdk",
    sha256 = "d0108e8e3b944b0e42484a0b8b60f34ab203a834e7dc08bda80a11f99048ba83",
    strip_prefix = "emsdk-476dc4e01fce997b540d9a507241f136256344e3/bazel",
    url = "https://github.com/emscripten-core/emsdk/archive/476dc4e01fce997b540d9a507241f136256344e3.tar.gz",
)

load("@emsdk//:deps.bzl", emsdk_deps = "deps")
emsdk_deps()

load("@emsdk//:emscripten_deps.bzl", emsdk_emscripten_deps = "emscripten_deps")
emsdk_emscripten_deps(emscripten_version = "2.0.31")

http_archive(
    name = "com_google_javascript_closure_library",
    sha256 = "303f99eb72c47a23a28b8bda1b2c5c14fae4f81788667fb36513a8ab5aaa02a7",
    strip_prefix = "closure-library-b312823ec5f84239ff1db7526f4a75cba0420a33",
    urls = ["https://github.com/google/closure-library/archive/b312823ec5f84239ff1db7526f4a75cba0420a33.tar.gz"],
)

http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "70ef2b4da987bf0d266e663d7c251eac509ff70dd65bba02d41d1e86e840a569",
    strip_prefix = "rules_closure-0.13.0",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.13.0.tar.gz",
        "https://github.com/bazelbuild/rules_closure/archive/0.13.0.tar.gz",
    ],
)

load("@io_bazel_rules_closure//closure:repositories.bzl", "rules_closure_dependencies", "rules_closure_toolchains")
rules_closure_dependencies()
rules_closure_toolchains()

local_repository(
    name = "amphtml-extensions",
    path = "../extensions",
)
