/** This file is automatically generated from preact.d.ts **/

/** @externs */

/** @const */
var PreactDef = {};
/**
 * @record
 * @struct
 */
PreactDef.Provider = function() {};

/* TODO: CallSignature: PreactDef */
/**
 * @record
 * @struct
 */
PreactDef.Consumer = function() {};

/* TODO: CallSignature: PreactDef */
/**
 * @record
 * @struct
 */
PreactDef.InnerHTML = function() {};
/** @type {string} */
PreactDef.InnerHTML.prototype.__html;

/** @typedef {function(...?): (string|number|boolean|void|function(...?): ?|!Array<(string|number|boolean|void)>|!Array<?>|!Array<!Array<(string|number|boolean|void|?)>>)} */
PreactDef.FunctionalComponent;

/** @typedef {function(...?): ?} */
PreactDef.VNode;

/** @typedef {function(...?): ?} */
PreactDef.Context;

/** @typedef {(string|number|boolean|void)} */
PreactDef.SimpleRenderable;

/** @typedef {(string|number|boolean|void|function(...?): ?|!Array<(string|number|boolean|void)>|!Array<?>|!Array<!Array<(string|number|boolean|void|?)>>)} */
PreactDef.Renderable;
