/**
 * Copyright 2021 The AMP HTML Authors. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS-IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** This file is automatically generated from video-wrapper.d.ts **/

/** @externs */

/** @const */
var VideoWrapperDef = {};
/**
 * @record
 * @struct
 */
VideoWrapperDef.Api = function () {};
/** @type {function(): (void|!Promise<void>)} */
VideoWrapperDef.Api.prototype.play;
/** @type {function(): void} */
VideoWrapperDef.Api.prototype.pause;
/** @type {function(): (void|!Promise<void>)} */
VideoWrapperDef.Api.prototype.requestFullscreen;
/** @type {number} */
VideoWrapperDef.Api.prototype.currentTime;
/** @type {number} */
VideoWrapperDef.Api.prototype.duration;
/** @type {boolean} */
VideoWrapperDef.Api.prototype.autoplay;
/** @type {boolean} */
VideoWrapperDef.Api.prototype.controls;
/** @type {boolean} */
VideoWrapperDef.Api.prototype.loop;
/** @type {function(): void} */
VideoWrapperDef.Api.prototype.mute;
/** @type {function(): void} */
VideoWrapperDef.Api.prototype.unmute;
/** @type {function(): void} */
VideoWrapperDef.Api.prototype.userInteracted;

/** @typedef {function(): (string|number|boolean|void|function(...?): ?|!Array<(string|number|boolean|void)>|!Array<?>|!Array<!Array<(string|number|boolean|void|?)>>)} */
VideoWrapperDef.PlayerComponent;
/**
 * @record
 * @struct
 */
VideoWrapperDef.Props = function () {};
/** @type {function(): (string|number|boolean|void|function(...?): ?|!Array<(string|number|boolean|void)>|!Array<?>|!Array<!Array<(string|number|boolean|void|?)>>)} */
VideoWrapperDef.Props.prototype.component;
/** @type {string} */
VideoWrapperDef.Props.prototype.loading;
/** @type {string} */
VideoWrapperDef.Props.prototype.src;
/** @type {(string|number|boolean|void|function(...?): ?|!Array<(string|number|boolean|void)>|!Array<?>|!Array<!Array<(string|number|boolean|void|?)>>)} */
VideoWrapperDef.Props.prototype.sources;
/** @type {boolean} */
VideoWrapperDef.Props.prototype.autoplay;
/** @type {boolean} */
VideoWrapperDef.Props.prototype.controls;
/** @type {boolean} */
VideoWrapperDef.Props.prototype.noaudio;
/** @type {string} */
VideoWrapperDef.Props.prototype.poster;
/** @type {boolean} */
VideoWrapperDef.Props.prototype.mediasession;
/** @type {string} */
VideoWrapperDef.Props.prototype.title;
/** @type {string} */
VideoWrapperDef.Props.prototype.artist;
/** @type {string} */
VideoWrapperDef.Props.prototype.album;
/** @type {string} */
VideoWrapperDef.Props.prototype.artwork;
/** @type {function(?, ?=): void} */
VideoWrapperDef.Props.prototype.onReadyState;
/**
 * @record
 * @struct
 */
VideoWrapperDef.AutoplayProps = function () {};
/** @type {!Object} */
VideoWrapperDef.AutoplayProps.prototype.metadata;
/** @type {boolean} */
VideoWrapperDef.AutoplayProps.prototype.displayIcon;
/** @type {boolean} */
VideoWrapperDef.AutoplayProps.prototype.playing;
/** @type {boolean} */
VideoWrapperDef.AutoplayProps.prototype.displayOverlay;
/** @type {function(...?): ?} */
VideoWrapperDef.AutoplayProps.prototype.onOverlayClick;
/** @type {{current: !Element}} */
VideoWrapperDef.AutoplayProps.prototype.wrapperRef;
/** @type {function(...?): ?} */
VideoWrapperDef.AutoplayProps.prototype.play;
/** @type {function(...?): ?} */
VideoWrapperDef.AutoplayProps.prototype.pause;
