(self.AMP=self.AMP||[]).push({n:"amp-auto-lightbox",v:"1908231648370",f:(function(AMP,_){
(function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a})(this);function n(){var a,b;this.promise=new Promise(function(c,g){a=c;b=g});this.resolve=a;this.reject=b};function p(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var q=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function r(a){return a?Array.prototype.slice.call(a):[]};self.log=self.log||{user:null,dev:null,userForEmbed:null};var t=self.log;function u(){if(t.dev)return t.dev;throw Error("failed to call initLogConstructor");};(function(a){return a||{}})({c:!0,v:!0,a:!0,ad:!0,action:!0});function v(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(f){u().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var g=0;g<c.length;g++)0!=c[g].length&&("-"==c[g][0]?a[c[g].substr(1)]=!1:a[c[g]]=!0);return a};function w(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return x(a,b)}function y(a){return a.nodeType?w((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function z(a){a=y(a);return a.isSingleDoc()?a.win:a}function x(a,b){A(a,b);var c=a.services;c||(c=a.services={});var g=c;a=g[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function A(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function B(a,b){for(var c;a&&a!==c;a=a.parentElement)if(b(a))return a;return null}
function C(a){return a.closest?a.closest("a[href],amp-script,amp-story,button,amp-lightbox,amp-carousel,[placeholder],[data-amp-auto-lightbox-disable],amp-selector [option],[subscriptions-action]"):B(a,function(a){var b=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return b?b.call(a,"a[href],amp-script,amp-story,button,amp-lightbox,amp-carousel,[placeholder],[data-amp-auto-lightbox-disable],amp-selector [option],[subscriptions-action]"):!1})}
function D(a){var b=a.tagName;4>b.length||b.lastIndexOf("AMP-",0);if(a.createdCallback)return Promise.resolve(a);a.__AMP_UPG_PRM||(b=new n,a.__AMP_UPG_PRM=b.promise,a.__AMP_UPG_RES=b.resolve);return a.__AMP_UPG_PRM};/nochunking=1/.test(self.location.hash);Promise.resolve();var E={Article:!0,NewsArticle:!0,BlogPosting:!0,LiveBlogPosting:!0,DiscussionForumPosting:!0};function F(){}function G(a){return H(a,function(){a.setAttribute("i-amphtml-auto-lightbox-visited","")})}function I(a){return D(a).then(function(a){return a.signals().whenSignal("load-end")})}
function J(a){return r(a.getRootNode().querySelectorAll('script[type="application/ld+json"]')).map(function(a){var b=a.textContent;try{var g=JSON.parse(b)}catch(f){g=null}return(g||{})["@type"]}).filter(function(a){return a})}function K(a){return J(a).some(function(a){return E[a]})}function H(a,b){return D(a).then(function(a){return a.getResources().mutateElement(a,b)})}
function L(a){function b(b){return!!a.getRootNode().querySelector(b)}var c='script[custom-element="amp-lightbox-gallery"]',g="[lightbox]:not([i-amphtml-auto-lightbox-visited])";return b(c)&&b(g)}var M=0;function N(a,b){return H(b,function(){b.setAttribute("lightbox","i-amphtml-auto-lightbox-"+M++)}).then(function(){w(a.win,"extensions").installExtensionForDoc(a,"amp-lightbox-gallery");b.dispatchCustomEvent("amp-auto-lightbox:newly-set");return b})}
function O(a,b){b.map(function(b){return I(b).then(function(){var c=b.querySelector("img");var f=c.naturalWidth;c=c.naturalHeight;var d=b.getLayoutBox(),l=d.width;d=d.height;var e=y(b);e=z(e);var h=x(e,"viewport").getSize();e=h.width;h=h.height;l*=d;if(f=1.2<=f*c/l||f>e||c>h||.25<=l/(e*h))if(C(b))f=!1;else{f=b.ownerDocument.defaultView;d=f.__AMP_TOP||(f.__AMP_TOP=f);c=f!=d;if(d.__AMP__EXPERIMENT_TOGGLES)var k=d.__AMP__EXPERIMENT_TOGGLES;else{d.__AMP__EXPERIMENT_TOGGLES=Object.create(null);l=d.__AMP__EXPERIMENT_TOGGLES;
if(d.AMP_CONFIG)for(k in d.AMP_CONFIG)e=d.AMP_CONFIG[k],"number"===typeof e&&0<=e&&1>=e&&(l[k]=Math.random()<e);if(d.AMP_CONFIG&&Array.isArray(d.AMP_CONFIG["allow-doc-opt-in"])&&0<d.AMP_CONFIG["allow-doc-opt-in"].length&&(k=d.AMP_CONFIG["allow-doc-opt-in"],e=d.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(e=e.getAttribute("content").split(","),h=0;h<e.length;h++)-1!=k.indexOf(e[h])&&(l[e[h]]=!0);Object.assign(l,v(d));if(d.AMP_CONFIG&&Array.isArray(d.AMP_CONFIG["allow-url-opt-in"])&&
0<d.AMP_CONFIG["allow-url-opt-in"].length){k=d.AMP_CONFIG["allow-url-opt-in"];e=d.location.originalHash||d.location.hash;d=Object.create(null);if(e)for(var m;m=q.exec(e);)h=p(m[1],m[1]),m=m[2]?p(m[2],m[2]):"",d[h]=m;for(e=0;e<k.length;e++)h=d["e-"+k[e]],"1"==h&&(l[k[e]]=!0),"0"==h&&(l[k[e]]=!1)}k=l}k=!!k["ampdoc-fie"];c&&!k?f=A(f,"action")?x(f,"action"):null:(f=y(b),f=z(f),f=A(f,"action")?x(f,"action"):null);f=!f.hasResolvableAction(b,"tap")}if(f)return u().info("amp-auto-lightbox","apply",b),N(a,
b)},F)})}function P(a,b){if(L(a))var c=0;else c=(c=a.getRootNode().querySelector('meta[property="og:type"]'))?c.getAttribute("content"):void 0,c="article"==c||K(a);c?(c=r((b||a.win.document).querySelectorAll("amp-img:not([lightbox]):not([i-amphtml-auto-lightbox-visited])")),c.forEach(G),O(a,c)):u().info("amp-auto-lightbox","disabled")}(function(a){var b=a.ampdoc;b.whenReady().then(function(){b.getRootNode().addEventListener("amp:dom-update",function(a){P(b,a.target)});P(b)})})(self.AMP);
})});

//# sourceMappingURL=amp-auto-lightbox-0.1.js.map
