---
name: Error Report
description: Report a production error seen in AMP Error Reporting.
labels: "Type: Error Report"
title: "\U0001F6A8 Error: [error message]"
body:
- type: markdown
  id: header
  attributes:
    value: |
      Thanks for filling out this error report.
      - Please only file reports from AMP Error Reporting here.
      - Check [existing reports](https://github.com/ampproject/amphtml/issues?q=label%3A%22Type%3A+Error+Report%22) to see if one already exists for the issue you are about to file.
- type: textarea
  id: details
  attributes:
    label: Details
    description: Information about the error being reported.
    value: |
      <!-- Replace ERROR_ID with the ID from the Cloud Error Reporting URL. -->
      **Error report:** [link](go/ampe/ERROR_ID)

      <!-- Select "1 day" on the error details page and replace FIRST_SEEN_DATE with the date on which it was first seen. -->
      **First seen:** FIRST_SEEN_DATE

      <!-- Select "1 day" on the error details page and replace DAILY_OCCURRENCES with the number of daily occurrences. -->
      **Frequency:** ~DAILY_OCCURRENCES/day
  validations:
    required: true
- type: textarea
  id: stack_trace
  attributes:
    label: Stack Trace
    description: The full stack trace for the error.
    placeholder: Paste the stack trace here. It will automatically be formatted as code.
    render: shell
  validations:
    required: true
- type: textarea
  id: additional_context
  attributes:
    label: Additional Context
    description: Other relevant context.
    placeholder: Provide additional context here. If there are interesting trends to note (e.g. all user-agent strings are from iPhones, there was a sudden jump in volume with recent release, etc.), include them in this section.
- type: textarea
  id: notifications
  attributes:
    label: Notifications
    description: Add working groups or individuals you want to notify about this error report.
    value: /cc @ampproject/release-on-duty
