---
name: Release Tracker
description: Track a new AMP release.
labels: 'Type: Release'
title: "\U0001F684 Release VERSION"
body:
  - type: textarea
    id: amp_version
    attributes:
      label: AMP Version
      description: Replace VERSION with AMP version.
      value: |
        [VERSION](https://github.com/ampproject/amphtml/releases/tag/VERSION)
    validations:
      required: true
  - type: textarea
    id: promotions
    attributes:
      label: Promotions
      description: Replace VERSION with AMP version and PROMOTE_TIME with CL submit time.
      value: |
        - [ ] VERSION promoted to Experimental and Beta (opt-in) channels (PROMOTE_TIME)
        - [ ] VERSION promoted to Experimental and Beta (1% traffic) channels (PROMOTE_TIME)
        - [ ] VERSION promoted to Stable channel (PROMOTE_TIME)
        - [ ] (optional) VERSION promoted to LTS channel (PROMOTE_TIME)

        /cc @ampproject/release-on-duty
    validations:
      required: true
