---
name: Release Tracker
description: Manually track a new AMP release. (This is automatically updated by the release-tagger GitHub Action).
labels: 'Type: Release'
title: "\U0001F684 Release VERSION"
body:
  - type: textarea
    id: amp_version
    attributes:
      label: AMP Version
      description: Replace VERSION with AMP version.
      value: |
        [VERSION](https://github.com/ampproject/amphtml/releases/tag/VERSION)
    validations:
      required: true
  - type: textarea
    id: promotions
    attributes:
      label: Promotions
      description: Replace `VERSION` with AMP version and `<!-- promote-time -->` with CL submit time.
      value: |
        - [ ] <!-- amp-version=VERSION channel=beta-opt-in -->VERSION promoted to Experimental and Beta (opt-in) channels <!-- promote-time -->
        - [ ] <!-- amp-version=VERSION channel=beta-percent -->VERSION promoted to Experimental and Beta (1% traffic) channels <!-- promote-time -->
        - [ ] <!-- amp-version=VERSION channel=stable -->VERSION promoted to Stable channel <!-- promote-time -->
        - [ ] <!-- amp-version=VERSION channel=lts -->VERSION promoted to LTS channel <!-- promote-time -->

        /cc @ampproject/release-on-duty
    validations:
      required: true
