---
name: Release Tracker
description: Track a new AMP release.
labels: 'Type: Release'
title: "\U0001F684 Release VERSION"
body:
  - type: input
    id: amp_version
    attributes:
      label: AMP version
      placeholder: e.g. 2107170150000
    validations:
      required: true
  - type: checkboxes
    id: promotions
    attributes:
      label: Promotions for this release.
      options:
        - label: Release VERSION promoted to Experimental and Beta (opt-in) channels (PROMOTE_TIME)
        - label: Release VERSION promoted to Experimental and Beta (1% traffic) channels (PROMOTE_TIME)
        - label: Release VERSION promoted to Stable channel (PROMOTE_TIME)
        - label: (optional) Release VERSION promoted to LTS channel (PROMOTE_TIME)
  - type: textarea
    id: notifications
    attributes:
      label: Notifications
      description: Add working groups or individuals you want to notify about this release.
      value: /cc @ampproject/release-on-duty
