package(default_visibility = ["//visibility:public"])

licenses(["notice"])

exports_files(
    [
        "CaseFolding.txt",
        "amptags.txt",
        "entities.json",
        "htmlattributes.txt",
        "htmltags.txt",
        "javascriptevents.txt",
        "jsongrammar.txt",
    ],
)
