# Reusable workflow for promote jobs.

on:
  workflow_call:
    inputs:
      channel-name:
        description: 'Human readable name of the channel to promote'
        required: true
        type: string
      js-file:
        description: 'Machine name of the JS file to execute, under build-system/release-workflows/'
        required: true
        type: string

jobs:
  promote:
    environment: release_tagger
    if: github.repository == 'ampproject/amphtml'
    name: Promote ${{ inputs.channel-name }} Channel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Set Up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set Up Environment
        run: sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}

      - name: Install Dependencies
        run: npm ci

      - name: ⭐ Promote ${{ inputs.channel-name }} Channel ⭐
        run: node --unhandled-rejections=strict build-system/release-workflows/${{ inputs.js-file }}.js
        env:
          GITHUB_TOKEN: ${{ secrets.AMPPROJECTBOT }}
