runtime: go113

main: ./main

handlers:
- url: /fetch
  script: auto
  secure: always

- url: /$
  static_files: index_wasm.html
  upload: index_wasm\.html
  secure: always

- url: /index_wasm\.html$
  static_files: index_wasm.html
  upload: index_wasm\.html
  secure: always

- url: /amp_favicon.png$
  static_files: amp_favicon.png
  upload: amp_favicon\.png$
  secure: always

- url: /logo-blue.svg$
  static_files: logo-blue.svg
  upload: logo-blue\.svg$
  secure: always
