version: 1
runtime: go
api_version: go1

handlers:
- url: /fetch
  script: _go_app

- url: /$
  static_files: index.html
  upload: index.html

- url: /amp_favicon.png$
  static_files: amp_favicon.png
  upload: amp_favicon\.png$
