version: 1
runtime: go
api_version: go1

handlers:
- url: /fetch
  script: _go_app

- url: /$
  static_files: index.html
  upload: index.html

- url: /cm/(.*\.(js|css))$
  static_files: codemirror/\1
  upload: codemirror/.*\.(js|css)$

- url: /pm/(.*\.html)$
  static_files: polymer/\1
  upload: polymer/.*\.html$

- url: /webcomponents-lite.js$
  static_files: webcomponents-lite.js
  upload: webcomponents-lite\.js$

- url: /amp_favicon.png$
  static_files: amp_favicon.png
  upload: amp_favicon\.png$
