runtime: go
api_version: go1

handlers:
- url: /fetch
  script: _go_app

- url: /$
  static_files: index.html
  upload: index.html

- url: /cm/(.*\.(js|css))$
  static_files: ../node_modules/codemirror/\1
  upload: ../node_modules/codemirror/.*\.(js|css)$

- url: /pm/(.*\.html)$
  static_files: ../node_modules/@polymer/\1
  upload: ../node_modules/@polymer/.*\.html$

- url: /webcomponents-lite.js$
  static_files: ../node_modules/webcomponents-lite/webcomponents-lite.js
  upload: ../node_modules/webcomponents-lite/webcomponents-lite\.js$
