workspace(name = "ampvalidator")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_google_absl",
    strip_prefix = "abseil-cpp-master",
    urls = ["https://github.com/abseil/abseil-cpp/archive/master.zip"],
)

http_archive(
    name = "com_google_googletest",
    sha256 = "de682ea824bfffba05b4e33b67431c247397d6175962534305136aa06f92e049",
    strip_prefix = "googletest-4ec4cd23f486bf70efcc5d2caa40f24368f752e3",
    urls = ["https://github.com/google/googletest/archive/4ec4cd23f486bf70efcc5d2caa40f24368f752e3.zip"],  # 2019-01-07
)

http_archive(
    name = "com_googlesource_code_re2",
    sha256 = "02fcb0b30819a08ab33966bbfb5c11686deffca634a0096574ccf1aca804bccd",
    strip_prefix = "re2-5aec8b553863350e32d13bbf745eae81adcdce93",
    urls = [
        "https://github.com/google/re2/archive/5aec8b553863350e32d13bbf745eae81adcdce93.tar.gz",
    ],
)

http_archive(
    name = "com_github_gflags_gflags",
    strip_prefix = "gflags-master",
    urls = ["https://github.com/gflags/gflags/archive/master.zip"],
)

http_archive(
    name = "com_github_re2",
    strip_prefix = "re2-main",
    urls = ["https://github.com/google/re2/archive/main.zip"],
)

http_archive(
    name = "com_github_glog",
    strip_prefix = "glog-master",
    urls = ["https://github.com/google/glog/archive/master.zip"],
)

http_archive(
    name = "com_google_protobuf",
    strip_prefix = "protobuf-master",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/master.zip"],
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()

local_repository(
    name = "amphtml-extensions",
    path = "../../../extensions/",
)

local_repository(
    name = "validator",
    path = "../../",
)

local_repository(
    name = "htmlparser",
    path = "../htmlparser/",
)
