name: Create Design Review Issues

on:
  schedule:
    # Every Wednesday at 00:00:00
    - cron: '0 0 * * 3'

jobs:
  create-design-review-issues:
    name: Create Design Review Issues
    runs-on: ubuntu-latest

    steps:
      - name: Set Up Node
        uses: actions/setup-node@v2.1.5

      - name: Create Next Issue
        run: |
          wget -q -O - https://raw.githubusercontent.com/ampproject/amphtml/master/build-system/tasks/create-design-review-issues/index.js | node
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
