# Promotes the current Stable traffic channel to LTS on a schedule.

name: Promote LTS Channel

on:
  schedule:
    # 1:30 a.m. PST / 12:30 a.m. PDT, Mondays.
    # Note that the job itself ensures it is running on the 2nd Monday of the
    # month, since crontab does not support this condition.
    - cron: '30 1 * * 1'

jobs:
  promote-lts:
    environment: release_tagger
    if: github.repository == 'ampproject/amphtml'
    name: Promote LTS Channel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Set Up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set Up Environment
        run: sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}

      - name: Install Dependencies
        run: npm ci

      - name: ⭐ Promote LTS Channel ⭐
        run: node --unhandled-rejections=strict build-system/release-workflows/promote-lts.js
        env:
          GITHUB_TOKEN: ${{ secrets.AMPPROJECTBOT }}
