# Promotes a new build to the Nightly channel on a schedule.

name: Promote Nightly Channel

on:
  schedule:
    # 1:30 a.m. PST / 12:30 a.m. PDT, Tuesdays through Saturdays.
    # Half an hour after cut-nightly.yml.
    - cron: '30 8 * * 2-6'

jobs:
  promote-nightly:
    environment: release_tagger
    if: github.repository == 'ampproject/amphtml'
    name: Promote Nightly Channel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Set Up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set Up Environment
        run: sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}

      - name: Install Dependencies
        run: npm ci

      - name: ⭐ Promote Nightly Channel ⭐
        run: node --unhandled-rejections=strict build-system/release-workflows/promote-nightly.js
        env:
          GITHUB_TOKEN: ${{ secrets.AMPPROJECTBOT }}
