# Promotes the current Beta/Experimental opt-in channel to Beta/Experimental traffic on a schedule.

name: Promote Beta/Experimental traffic Channels

on:
  schedule:
    # 1:30 a.m. PST / 12:30 a.m. PDT, Wednesdays.
    - cron: '30 1 * * 3'

jobs:
  promote-beta-experimental-traffic:
    environment: release_tagger
    if: github.repository == 'ampproject/amphtml'
    name: Promote Beta/Experimental traffic Channel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Set Up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set Up Environment
        run: sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}

      - name: Install Dependencies
        run: npm ci

      - name: ⭐ Promote Beta/Experimental traffic Channel ⭐
        run: node --unhandled-rejections=strict build-system/release-workflows/promote-beta-experimental-traffic.js
        env:
          GITHUB_TOKEN: ${{ secrets.AMPPROJECTBOT }}
