name: Update Design Review Issues

on:
  # This schedule should match the time rotation configured on
  # update-design-review-issues.js.
  # Times correspond to session end, and additionally 1 hour earlier to account
  # for Daylight Savings.
  schedule:
    # Africa/Europe/western Asia
    # At 16:30 and 17:30 on Wednesday.
    - cron: '30 16,17 * * 3'
    # Americas
    # At 21:00 and 22:00 on Wednesday.
    - cron: '00 21,22 * * 3'
    # Asia/Oceania
    # At 01:00 and 02:00 on Thursday.
    - cron: '00 01,02 * * 4'

jobs:
  update-design-review-issues:
    if: github.repository == 'ampproject/amphtml'
    name: Update Design Review Issues
    runs-on: ubuntu-latest
    steps:
      - name: Update Design Review Issues
        run: |
          wget -q -O - "https://raw.githubusercontent.com/ampproject/amphtml/main/build-system/common/update-design-review-issues.js" | node
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
