name: Update Design Review Issues

on:
  # This schedule should match the time rotation configured on
  # update-design-review-issues.js.
  # Times correspond to session end, and additionally 1 hour earlier to account
  # for Daylight Savings.
  schedule:
    - cron: '30 16,17 * * 3' # Africa/Europe/western Asia
    - cron: '0 21,22 * * 3' # Americas
    - cron: '0 1,2 * * 4' # Asia/Oceania

jobs:
  update-design-review-issues:
    if: github.repository == 'ampproject/amphtml'
    name: Update Design Review Issues
    runs-on: ubuntu-latest
    steps:
      - name: Update Design Review Issues
        run: |
          wget -q -O - "https://raw.githubusercontent.com/ampproject/amphtml/main/build-system/common/update-design-review-issues.js" | node
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
